### PR TITLE
commitlog: Revert/modify fac2bc4 - do footprint add in delete

### LINKED ISSUE #11184: Recycled-CommitLog-X-XXXXXXXXX files fill the disk without limits
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 4.4.6 and 4.6.3
Cluster size: 35 nodes and 70 nodes
OS: CentOS 7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): on-premise kubernetes
Hardware: sockets=2 cores=8 hyperthreading=yes memory=256GB
Disks: 1 SSD disk 6TB

One year after installation of our clusters, we observe that their disk is almost full whereas dataset is far from consuming all available space. When looking at disk content, we observed up to 3TB consumed by commitlog, mostly by Recycle-CommitLog-XXX files.
cf. output of ls -l /var/lib/scylla/commitlog

[scylla-commitlog-ls.txt.gz](https://github.com/scylladb/scylladb/files/9234492/scylla-commitlog-ls.txt.gz)

```
$  zcat ../scylla-commitlog-ls.txt.gz | grep Recycled | awk '{s+=$5} END {print s}'
3327123259392 => 3TB
```

```
$  zcat ../scylla-commitlog-ls.txt.gz | grep -v Recycled | awk '{s+=$5} END {print s}'
140156862464 => 127GB
```

Here are our commitlog parameters from scylla.yaml :
```
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
```

From our understanding of scylla code (db/commitlog/commitlog.cc):
- at startup, scylla doesn't initialize _recycled_segments with Recycled-CommitLog-XXX files already present on disk
- so they aren't accounted in disk space consumed by commitlog
- and if for any reason scylla doesn't properly shutdown, Recycled-CommitLog-XXX files created during process lifetime won't be deleted and will stay forever on disk.

We believe it would make sense to reuse and account already created Recycled-CommitLog-XXX at scylla startup.

### LINKED ISSUE #11237: Node hangs during start up in test_total_space_limit_of_commitlog_with_medium_limit
Seen first in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/71/artifact/logs-full.release.001/1659755830552_commitlog_test.py%3A%3ATestCommitLog%3A%3Atest_total_space_limit_of_commitlog_with_medium_limit/node1.log
```
Scylla version 5.2.0~dev-0.20220805.fbbe2529c11d with build-id be8ad53ed567b044861b8b8fa8042e72d818c935 starting ...

INFO  2022-08-06 03:05:59,631 [shard 0] init - initializing batchlog manager
INFO  2022-08-06 03:05:59,632 [shard 0] system_keyspace - Loaded local host id: b30f75cb-725a-42b6-a031-eb8b5071ccbd
INFO  2022-08-06 03:05:59,633 [shard 0] format_selector - Selected me sstables format
INFO  2022-08-06 03:15:02,419 [shard 0] compaction_manager - Asked to stop
INFO  2022-08-06 03:15:02,419 [shard 0] compaction_manager - Stopped
INFO  2022-08-06 03:15:02,419 [shard 1] compaction_manager - Asked to stop
INFO  2022-08-06 03:15:02,419 [shard 1] compaction_manager - Stopped
```

Note the ~9 minutes gap between the last start up message and the first shutdown message
when the dtest tries to kill the node when the test fails on timeout.
Shutting down the node times out too and a core dump is produced: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/71/artifact/logs-full.release.001/1659755830552_commitlog_test.py%3A%3ATestCommitLog%3A%3Atest_total_space_limit_of_commitlog_with_medium_limit/node1-scylla.32900.1659755829.core.gz

This seems to be highly reproducible, at least on the Jenkins runs.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #11184
Fixes #11237

In prev (broken) fix for https://github.com/scylladb/scylladb/issues/11184 we added the footprint for left-over
files (replay candidates) to disk footprint on commitlog init.

This effectively prevents us from creating segments iff we have tight limits. Since we nowadays do quite a bit of inserts _before_ commitlog replay (system.local, but...) we can end up in a situation where we deadlock start because we cannot get to the actual replay that will eventually free things.

Another, not thought through, consequence is that we add a single footprint to _all_ commitlog shard instances - even though only shard 0 will get to actually replay + delete (i.e. drop footprint).
So shards 1-X would all be either locked out or performance degraded.

Simplest fix is to add the footprint in delete call instead. This will lock out segment creation until delete call is done, but this is fast. Also ensures that only replay shard is involved.

To further emphasize this, don't store segments found on init scan in all shard instances,
instead retrieve (based on low time-pos for current gen) when required. This changes very little, but we at last don't store
pointless string lists in shards 1 to X, and also we can potentially ask for the list twice. 
More to the point, goes better hand-in-hand with the semantics of "delete_segments", where any file sent in is
considered candidate for recycling, and included in footprint.

### CODE REVIEW

**Comment by nyh** [comment]
@elcallio unfortunately this patch conflicts with the latest master. Please rebase.

**Comment by elcallio** [comment]
rebased.

File: main.cc [hunk 1]
```diff
@@ -1138,14 +1138,14 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
...
-                auto paths = sch_cl->get_segments_to_replay();
+                auto paths = sch_cl->get_segments_to_replay().get();
                 if (!paths.empty()) {
                     supervisor::notify("replaying schema commit log");
                     auto rp = db::commitlog_replayer::create_replayer(db).get0();
                     rp.recover(paths, db::schema_tables::COMMITLOG_FILENAME_PREFIX).get();
                     supervisor::notify("replaying schema commit log - flushing memtables");
                     db.invoke_on_all([] (replica::database& db) {
-                        return db.flush_all_memtables();
+                        return db.flush_all_memtables();
```
Comment (denesb) [inline main.cc:1148]: Unnecessary trailing whitespace.

**Comment by denesb** [comment]
@avikivity please review.

**Comment by elcallio** [comment]
ping?

**Comment by denesb** [comment]
I was hesitant to merge because I'm not familiar enough with this code to really understand the change. But in the interest of forward progress I queued it.
