### PR TITLE
alternator: fix validation of numbers' magnitude and precision

### LINKED ISSUE #6794: Limit scale and precision of numbers in Alternator
DynamoDB has a number type - for integers and floating point - which doesn't match any of the standard C++ types. It is basically a floating point number with 38 _decimal_ digits of precision and decimal exponent between -130 and 125 - see more information 
[here](https://docs.google.com/document/d/1i4yjF5OSAazAY_-T8CBce9-2ykW4twx_E_Nt2zDoOVs/edit#heading=h.vvocat9deqa9) or [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes).

In Alternator we implemented this number type using Scylla's `big_decimal` type. However, `big_decimal` (based on Java's `BigDecimal`) is an overkill: it allows for numbers of _unlimited_ precision and huge scales - far beyond what DynamoDB allows.

The risk is that Alternator users may discover these unlimited-precision numbers in Alternator, and come to rely on them, so if in the future we may want to change the implementation of numbers (e.g., to make them take less space), these use cases will break. 

When DynamoDB attempts to store or calculate numbers with excessive scale or precision, it produces an error and refuses to store such overflowing or over-precise numbers. We should behave similarly.

### PR DESCRIPTION
**Pull request by nyh**
DynamoDB limits the allowed magnitude and precision of numbers - valid
decimal exponents are between -130 and 125 and up to 38 significant
decimal digitst are allowed. In contrast, Scylla uses the CQL "decimal"
type which offers unlimited precision. This can cause two problems:
    
1. Users might get used to this "unofficial" feature and start relying
    on it, not allowing us to switch to a more efficient limited-precision
    implementation later.
    
2. If huge exponents are allowed, e.g., 1e-1000000, summing such a
    number with 1.0 will result in a huge number, huge allocations and
    stalls. This is highly undesirable.

This series adds more tests in this area covering additional corner cases,
and then fixes the issue by adding the missing verification where it's
needed. After the series, all 12 tests in test/alternator/test_number.py now pass.
        
Fixes #6794

### CODE REVIEW

**Comment by nyh** [comment]
Note: although this series fixes the problem, and adds a bunch of missing tests, I **don't like** my implementation of `get_magnitude_and_precision()` which is much longer and uglier than I had hoped :-(
Also, if we do decide to keep that implementation, I will need to write a unit test (in C++) just for this low-level function because it's too risky that I didn't cover all its corner cases in high-level Alternator-API tests.

**Comment by nyh** [comment]
Pushed new version with a unit test for the delicate get_magnitude_and_precision() function, fixed a few bugs discovered by this new unit test, and also improved the coverage of the original python tests.

File: test/boost/alternator_unit_test.cc [hunk 1]
```diff
@@ -86,3 +83,86 @@ BOOST_AUTO_TEST_CASE(test_allocator_fail_gracefully) {
...
+    BOOST_CHECK(res.magnitude > 1000);
+    res = alternator::internal::get_magnitude_and_precision("1e-1000000");
+    BOOST_CHECK(res.magnitude < -1000);
+    // Even if an exponent so huge that it doesn't even fit in a 32-bit
+    // integer, we shouldn't fail to recognize its excessive magnitude:
+    res = alternator::internal::get_magnitude_and_precision("1e1000000000000");
+    BOOST_CHECK(res.magnitude > 1000);
+    res = alternator::internal::get_magnitude_and_precision("1e-1000000000000");
+    BOOST_CHECK(res.magnitude < -1000);
+}
```
Comment (denesb) [inline test/boost/alternator_unit_test.cc:168]: I think it would be worth adding some negative checks too, for invalid numeric strings, to ensure the validator will correctly recognize it.

Comment (nyh) [reply test/boost/alternator_unit_test.cc:168]: The function get_magnitude_and_precision() is written to assume that the number was already parsed correctly into a big_decimal() - the caller (Alternator) first creates a big_decimal() and only if it succeeds, validates the magnitude and precision).

As I explained in a comment, in a perfect world, the function would have used the already-parsed big_decimal and not reparse the string - but I didn't manage to do this  :-( Just now I realized that boost::multiprecision::cpp_int (which we use) implements msb() and lsb() functions - https://www.boost.org/doc/libs/1_55_0/libs/multiprecision/doc/html/boost_multiprecision/tut/gen_int.html - maybe I can rewrite my function in terms of those functions, working on a parsed big_decimal! I'll consider doing this, but I think maybe I already spent too much time on this issue already :-(

Comment (denesb) [reply test/boost/alternator_unit_test.cc:168]: Ok, queued. It can be improved it later if you find the time or reason.

**Comment by nyh** [comment]
Thanks @denesb.
I wanted to try rewriting the the ugly string-processing function with something that processes the already-parsed big_decimal. It turns out it's fairly easy to write a function which somehow limits the magnitude and precision of numbers:
```c++
    auto sign = d.unscaled_value().sign();
    if (sign == 0) {
        return magnitude_and_precision {0, 0};
    }
    // The lsb() and msb() functions refuse to work on negative numbers (or
    // zero), so we may need to run them on -d (which unfortunately requires
    // a temporary copy of the number).
    auto d_lsb = sign > 0 ? lsb(d.unscaled_value()) : lsb(-d.unscaled_value());
    auto d_msb = sign > 0 ? msb(d.unscaled_value()) : msb(-d.unscaled_value());
    // now use d.scale(), d_lsb and msb to calculate the magnitude and precision of d
    ...
```
The problem is that d_lsb and d_msb (unlike d.scale()) counts base-2 digits. So if we want to be 100% compatible with DynamoDB's limit, and accept 9.9999e125 but reject 1e126, it's not accurate enough to count base-2 digits.

For the magnitude, there is an easier solution: For a positive number we just need to check that it's strictly lower than 1e126 and higher than 1e-131. However big_decimal's scale() forces us to do some pow() or multiplication to to create the numbers to compare, so it won't be super-quick as I wanted it to be. And in any case, I don't know how to implement precision in this way :-(

So I'm giving up and leaving the code I wrote yesterday (which is already merged, anyway).
