### PR TITLE
abstract_replication_strategy: make get_ranges async

### LINKED ISSUE #19757: vnode_effective_replication_map::do_get_ranges might stall
The following long stalls were seen with large clusters (of close to 70 nodes):

```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar.lto/./seastar/include/seastar/util/backtrace.hh:64
seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:839
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:858
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:1469
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:1206
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar.lto/./seastar/src/core/reactor.cc:1226
?? ??:0
logalloc::region_impl::object_descriptor::live_size(void const*) const at ./utils/logalloc.cc:1602
 (inlined by) void logalloc::region_impl::for_each_live<logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}>(logalloc::segment*, logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&)::{lambda(logalloc::region_impl::object_descriptor const*, void*, unsigned long)#1}&&) at ./utils/logalloc.cc:1730
 (inlined by) logalloc::region_impl::compact_segment_locked(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:1884
logalloc::region_impl::compact_segment(logalloc::segment*, logalloc::segment_descriptor&) at ./utils/logalloc.cc:2269
 (inlined by) logalloc::segment_pool::compact_segment(logalloc::segment*) at ./utils/logalloc.cc:2857
 (inlined by) logalloc::segment_pool::reclaim_segments(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:1235
logalloc::tracker::impl::reclaim_locked(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2636
 (inlined by) logalloc::tracker::impl::reclaim(unsigned long, seastar::bool_class<is_preemptible_tag>) at ./utils/logalloc.cc:2606
logalloc::tracker::reclaim(unsigned long) at ./utils/logalloc.cc:563
 (inlined by) logalloc::tracker::reclaim(seastar::memory::reclaimer::request) at ./utils/logalloc.cc:2343
 (inlined by) logalloc::tracker::tracker()::$_0::operator()(seastar::memory::reclaimer::request) const at ./utils/logalloc.cc:551
 (inlined by) seastar::memory::reclaiming_result std::__invoke_impl<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>(std::__invoke_other, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>, seastar::memory::reclaiming_result>::type std::__invoke_r<seastar::memory::reclaiming_result, logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request>(logalloc::tracker::tracker()::$_0&, seastar::memory::reclaimer::request&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request), logalloc::tracker::tracker()::$_0>::_M_invoke(std::_Any_data const&, seastar::memory::reclaimer::request&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<seastar::memory::reclaiming_result (seastar::memory::reclaimer::request)>::operator()(seastar::memory::reclaimer::request) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) seastar::memory::reclaimer::do_reclaim(unsigned long) at ./build/release/seastar.lto/./seastar/include/seastar/core/memory.hh:227
 (inlined by) seastar::memory::cpu_pages::run_reclaimers(seastar::memory::reclaimer_scope, unsigned long) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:1197
seastar::memory::cpu_pages::find_and_unlink_span_reclaiming(unsigned int) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:755
 (inlined by) seastar::memory::cpu_pages::allocate_large_and_trim(unsigned int) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:780
seastar::memory::cpu_pages::allocate_large(unsigned int) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:826
 (inlined by) seastar::memory::allocate_large(unsigned long) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:1392
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:1453
 (inlined by) operator new(unsigned long) at ./build/release/seastar.lto/./seastar/src/core/memory.cc:2148
std::__new_allocator<nonwrapping_interval<dht::token> >::allocate(unsigned long, void const*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/new_allocator.h:147
 (inlined by) std::allocator<nonwrapping_interval<dht::token> >::allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/allocator.h:198
 (inlined by) std::allocator_traits<std::allocator<nonwrapping_interval<dht::token> > >::allocate(std::allocator<nonwrapping_interval<dht::token> >&, unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/alloc_traits.h:482
 (inlined by) std::_Vector_base<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_vector.h:378
 (inlined by) void std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_realloc_insert<nonwrapping_interval<dht::token> >(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token>*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, nonwrapping_interval<dht::token>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/vector.tcc:459
 (inlined by) std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::_M_insert_rval(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token> const*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, nonwrapping_interval<dht::token>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/vector.tcc:372
 (inlined by) std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >::insert(__gnu_cxx::__normal_iterator<nonwrapping_interval<dht::token> const*, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > >, nonwrapping_interval<dht::token>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_vector.h:1391
 (inlined by) locator::insert_token_range_to_sorted_container_while_unwrapping(dht::token const&, dht::token const&, std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > >&) at ./locator/abstract_replication_strategy.cc:183
locator::vnode_effective_replication_map::do_get_ranges(seastar::noncopyable_function<seastar::bool_class<seastar::stop_iteration_tag> (bool&, gms::inet_address const&)>) const at ./locator/abstract_replication_strategy.cc:214
locator::vnode_effective_replication_map::get_ranges(gms::inet_address) const at ./locator/abstract_replication_strategy.cc:226
repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_0::operator()() at ./repair/repair.cc:1653
```

### PR DESCRIPTION
**Pull request by bhalevy**
To prevent stalls due to large number of tokens.
For example, large cluster with say 70 nodes can have
more than 16K tokens.

Fixes #19757

### CODE REVIEW

**Comment by bhalevy** [comment]
@nyh please review, in particular the changes in alternator/ttl.cc
The refactoring makes sense on its own IMHO, so I can submit it separately if the async get_ranges part of it would turn out to be controversial.

**Comment by bhalevy** [comment]
In v2 ([da87834](https://github.com/scylladb/scylladb/commit/da878346c1a703068847374e76c79ec936cdd866)):
- rebase
- prevent use after free of the effective_replication_map in database::get_keyspace_local_ranges
  - compaction: task_manager_module: open code maybe_get_keyspace_local_ranges
  - database: get_keyspace_local_ranges: get vnode_effective_replication_map_ptr param

**Comment by avikivity** [comment]
Is get_ranges() a reasonable API? Should we iterate instead?

**Comment by bhalevy** [comment]
> Is get_ranges() a reasonable API? Should we iterate instead?

We can iterate in some cases more easily than others (without major restructuring of the code).
It does make sense to return a generator.
I've prepared a follow patch for that, but it depends on https://github.com/scylladb/seastar/pull/2354, otherwise there are crashes.

**Comment by bhalevy** [comment]
I'll rebase and drop the last patch that uses the experimental generator until https://github.com/scylladb/seastar/pull/2218

File: alternator/ttl.cc [hunk 1]
```diff
@@ -393,52 +393,48 @@ static std::vector<std::pair<dht::token_range, gms::inet_address>> get_secondary
...
+        return _token_ranges[i].first;
+    }
+    // range i should be skipped if its primary owner is alive.
+    bool should_skip(std::size_t i) const {
+        return _gossiper.is_alive(_token_ranges[i].second);
+    }
+};
+
+template<class primary_or_secondary_t>
+class token_ranges_owned_by_this_shard {
```
Comment (avikivity) [inline alternator/ttl.cc:437]: This looks pretty bloated, but this patch doesn't introduce the bloat so okay.

File: compaction/task_manager_module.cc [hunk 2]
```diff
@@ -467,7 +467,11 @@ future<> shard_cleanup_keyspace_compaction_task_impl::run() {
 
 future<> table_cleanup_keyspace_compaction_task_impl::run() {
     co_await wait_for_your_turn(_cv, _current_task, _status.id);
-    auto owned_ranges_ptr = compaction::make_owned_ranges_ptr(_db.get_keyspace_local_ranges(_status.keyspace));
+    auto get_owned_ranges = [&] (std::string_view keyspace_name) -> owned_ranges_ptr {
+        const auto& erm = _db.find_keyspace(keyspace_name).get_vnode_effective_replication_map();
+        return compaction::make_owned_ranges_ptr(_db.get_keyspace_local_ranges(erm));
+    };
```
Comment (avikivity) [inline compaction/task_manager_module.cc:473]: Isn't the result immediately invalidated by a following range movement?

Comment (avikivity) [reply compaction/task_manager_module.cc:473]: I guess you can say with vnodes the operator is responsible for not performing additional incompatible range movements, but a comment is needed when violating the rules of using effective replication maps.

Comment (bhalevy) [reply compaction/task_manager_module.cc:473]: yes, that makes sense.

File: message/messaging_service.hh [hunk 3]
```diff
@@ -64,14 +65,6 @@ class frozen_mutation;
...
 class canonical_mutation;
 
-namespace dht {
-    class token;
-    class ring_position;
-    using partition_range = interval<ring_position>;
-    using token_range = interval<token>;
-    using token_range_vector = std::vector<token_range>;
-}
-
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply message/messaging_service.hh:74]: Hmm, I'm not sure why it was done in this series.
Since it's the last patch in the series, indeed nothing depends on it at the moment.

[the remark this answers is not in the document]
Comment (bhalevy) [reply message/messaging_service.hh:74]: I'll send it separately since in general I don't like forward declaration that include types (like `using token_range_vector = std::vector<token_range>`) and not just class names, to be distributed all over the place.
We better have one source of truth for them in the include _fwd header file.

[the remark this answers is not in the document]
Comment (avikivity) [reply message/messaging_service.hh:74]: I agree (and the patch is good) but this is a lost cause.

To get a single source of truth, we need C++ modules.

File: compaction/task_manager_module.cc (hunk 2 above)
Comment (bhalevy) [reply compaction/task_manager_module.cc:477]: Add comment in v4

File: message/messaging_service.hh (hunk 3 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply message/messaging_service.hh]: dropped this patch in v4

**Comment by bhalevy** [comment]
In v4 [686a8f2](https://github.com/scylladb/scylladb/commit/686a8f29395eb043170ef2f49c5b3591ce03fe03):
- rebased
- added comment for `table_cleanup_keyspace_compaction_task_impl::run` about volatility of owned ranges and admin's responsibility while erm_ptr is not held to prevent conflicting topology changes.
- dropped "messaging_service: include dht/i_partitioner_fwd.hh"

**Comment by bhalevy** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11096/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11096/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/database_test 🔹 boost/network_topology_strategy_test 🔹 boost/sstable_compaction_test 🔹 boost/sstable_directory_test ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11096/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/149/)

https://github.com/scylladb/scylladb/issues/19665

> ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/3195/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/11219/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11096/)

respinning
