### PR TITLE
raft_group0: split shutdown into abort-and-drain and destroy

### LINKED ISSUE #24625: Coredump during drain with `terminate called after throwing an instance of 'service::raft_group_not_found'`
Scylla version: `2025.3.0~dev-20250622.85c19d21bb4a` with build-id `fe80e69508a8d3a710d97de044089286ed8d718a`
Kernel Version: `6.11.0-1015-azure`
Argus: https://argus.scylladb.com/tests/scylla-cluster-tests/c1f2a170-b8a7-4be8-88e4-e806751f7a20
Coredump: https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/c1f2a170-b8a7-4be8-88e4-e806751f7a20/log/core.scylla-longevity-10gb-3h-master-db-node-c1f2a170-eastus-13-2025-06-23_11-18-16.gz/download

Log
```
2025-06-23T11:15:33.091+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:  [shard 0:strm] storage_service - entering DRAINED mode
2025-06-23T11:15:33.091+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:  [shard 0:main] raft_group_registry - marking Raft server a425fa42-efc6-4608-8e21-cbf5a10e7ffd as dead for raft groups
2025-06-23T11:15:33.091+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:  [shard 0:main] raft_group_registry - marking Raft server 199f4f13-af10-43d6-8110-93e69df51e1c as dead for raft groups
2025-06-23T11:15:33.091+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:  [shard 0:main] raft_group_registry - marking Raft server affaebdd-402f-4502-b409-5390cd15fc0f as dead for raft groups
2025-06-23T11:15:33.091+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:  [shard 0:main] raft_group_registry - marking Raft server bb51cde3-66a2-44a7-90d3-bfac09007824 as dead for raft groups
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:  [shard 0:main] raft_group_registry - marking Raft server 1cfb0b15-b25e-4054-8870-c6efbc797daf as dead for raft groups
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]: terminate called after throwing an instance of 'service::raft_group_not_found'
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   what():  Raft group f841abb1-5004-11f0-806b-2fe61ce5956a not found
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]: Aborting on shard 0, in scheduling group main.
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]: Backtrace:
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x5b84daa
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x5b80bfa
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x5bb54f6
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libc.so.6+0x1a04f
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libc.so.6+0x72f53
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libc.so.6+0x19f9d
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libc.so.6+0x1941
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libstdc++.so.6+0x9da8
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libstdc++.so.6+0x1bc2b
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libstdc++.so.6+0x9950
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x191a04a
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x4dc2860
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x2b6e9a1
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x1956826
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x2860258
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x2860904
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x2860362
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x285e005
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x285a332
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libc.so.6+0x3247
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   /opt/scylladb/libreloc/libc.so.6+0x330a
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla[4357]:   0x30cb1c4
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | systemd[1]: Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
2025-06-23T11:15:33.160+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | systemd[1]: Started systemd-coredump@0-5892-0.service - Process Core Dump (PID 5892/UID 0).
2025-06-23T11:15:33.844+00:00 longevity-10gb-3h-master-db-node-c1f2a170-eastus-13     !INFO | scylla-cluster-tests[5894]: nodetool /usr/bin/nodetool  drain  completed after 5.06s on longevity-10gb-3h-master-db-node-c1f2a170-eastus-13 [10.0.0.5]

```

decoded backtrace
```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&, bool) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:89
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:817
seastar::print_with_backtrace(char const*, bool, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:870
 (inlined by) seastar::sigabrt_action(siginfo_t*, ucontext_t*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4076
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)(siginfo_t*, ucontext_t*))(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4005
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)(siginfo_t*, ucontext_t*))(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4000
/data/scylla-s3-reloc.cache/by-build-id/fe80e69508a8d3a710d97de044089286ed8d718a/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b840d32d15506ed2f29610c7f512d9084f2d7d69, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
/data/scylla-s3-reloc.cache/by-build-id/fe80e69508a8d3a710d97de044089286ed8d718a/extracted/scylla/libreloc/libstdc++.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2433a579334ce4caa8fb2d2fee7b787288792ae0, stripped

std::unexpected() at ??:?
std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:?
std::terminate() at ??:?
__clang_call_terminate at main.cc:?
service::storage_service::is_raft_leader() const at ././service/storage_service.cc:5329
sstable_dict_autotrainer::run() at ././sstable_dict_autotrainer.cc:142
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ./build/release/seastar/./seastar/include/seastar/core/coroutine.hh:122
 (inlined by) seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2622
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3092
 (inlined by) seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3255
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3143
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:273
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:754
main at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

coredump event
```
2025-06-23 11:18:16.096 <2025-06-23 11:15:33.000>: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=d49817a4-7beb-4c8c-b0e6-8dd144a064cd node=Node longevity-10gb-3h-master-db-node-c1f2a170-eastus-13 [None | 10.0.0.5] (rack: RACK1)
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000./core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000.zst
backtrace=           PID: 4357 (scylla)
UID: 107 (scylla)
GID: 111 (scylla)
Signal: 6 (ABRT)
Timestamp: Mon 2025-06-23 11:15:33 UTC (2min 24s ago)
Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 25 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7 --lock-memory=1
Executable: /opt/scylladb/libexec/scylla
Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
Unit: scylla-server.service
Slice: scylla-server.slice
Boot ID: 49ddb4e15172485b9ff36b21566bd9a1
Machine ID: 8122f42f9a3a431b8529a3acc5411ada
Hostname: longevity-10gb-3h-master-db-node-c1f2a170-eastus-13
Storage: /var/lib/systemd/coredump/core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000.zst (present)
Size on Disk: 2.2G
Message: Process 4357 (scylla) of user 107 dumped core.
Module libboost_atomic.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Module libicudata.so.74 from rpm icu-74.2-2.fc41.x86_64
Module libssl.so.3 from rpm openssl-3.2.4-1.fc41.x86_64
Module libsasl2.so.3 from rpm cyrus-sasl-2.1.28-27.fc41.x86_64
Module libevent-2.1.so.7 from rpm libevent-2.1.12-14.fc41.x86_64
Module libcap.so.2 from rpm libcap-2.70-4.fc41.x86_64
Module libffi.so.8 from rpm libffi-3.4.6-3.fc41.x86_64
Module libboost_unit_test_framework.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Module libboost_filesystem.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Module liblua-5.4.so from rpm lua-5.4.7-3.fc41.x86_64
Module libjsoncpp.so.25 from rpm jsoncpp-1.9.5-8.fc41.x86_64
Module libsystemd.so.0 from rpm systemd-256.12-1.fc41.x86_64
Module libdeflate.so.0 from rpm libdeflate-1.23-1.fc41.x86_64
Module libxxhash.so.0 from rpm xxhash-0.8.3-1.fc41.x86_64
Module libicui18n.so.74 from rpm icu-74.2-2.fc41.x86_64
Module libicuuc.so.74 from rpm icu-74.2-2.fc41.x86_64
Module libboost_regex.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Module libboost_date_time.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Module libcryptopp.so.8 from rpm cryptopp-8.8.0-8.fc41.x86_64
Module libcrypt.so.2 from rpm libxcrypt-4.4.38-7.fc41.x86_64
Module libcrypto.so.3 from rpm openssl-3.2.4-1.fc41.x86_64
Module libsnappy.so.1 from rpm snappy-1.2.1-2.fc41.x86_64
Module libyaml-cpp.so.0.7 from rpm yaml-cpp-0.7.0-6.fc41.x86_64
Module libudev.so.1 from rpm systemd-256.12-1.fc41.x86_64
Module libhwloc.so.15 from rpm hwloc-2.12.0-1.fc41.x86_64
Module libz.so.1 from rpm zlib-ng-2.2.3-2.fc41.x86_64
Module libprotobuf.so.30 from rpm protobuf-3.19.6-10.fc41.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.5-3.fc41.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.8-1.fc41.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.20.0-1.fc41.x86_64
Module libnettle.so.8 from rpm nettle-3.10-3.fc41.x86_64
Module libhogweed.so.6 from rpm nettle-3.10-3.fc41.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-8.fc41.x86_64
Module libgmp.so.10 from rpm gmp-6.3.0-2.fc41.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.9-2.fc41.x86_64
Module liblz4.so.1 from rpm lz4-1.10.0-1.fc41.x86_64
Module liburing.so.2 from rpm liburing-2.6-2.fc41.x86_64
Module libsctp.so.1 from rpm lksctp-tools-1.0.20-1.fc41.x86_64
Module libfmt.so.11 from rpm fmt-11.0.2-2.fc41.x86_64
Module libcares.so.2 from rpm c-ares-1.34.5-1.fc41.x86_64
Module libboost_thread.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Module libboost_program_options.so.1.83.0 from rpm boost-1.83.0-8.fc41.x86_64
Stack trace of thread 4357:
#0  0x000000004160ef54 __pthread_kill_implementation (libc.so.6 + 0x72f54)
#1  0x00000000415b5f9e raise (libc.so.6 + 0x19f9e)
#2  0x000000004159d942 abort (libc.so.6 + 0x1942)
#3  0x0000000043009da9 n/a (libstdc++.so.6 + 0x9da9)
#4  0x000000004301bc2c n/a (libstdc++.so.6 + 0x1bc2c)
#5  0x0000000043009951 _ZSt9terminatev (libstdc++.so.6 + 0x9951)
#6  0x000000000191a04b __clang_call_terminate (scylla + 0x171a04b)
#7  0x0000000004dc2861 _ZNK7service15storage_service14is_raft_leaderEv (scylla + 0x4bc2861)
#8  0x0000000002b6e9a2 _ZN24sstable_dict_autotrainer3runEv.resume (scylla + 0x296e9a2)
#9  0x0000000001956827 _ZN7seastar7reactor6do_runEv (scylla + 0x1756827)
#10 0x0000000002860259 _ZN7seastar7reactor3runEv (scylla + 0x2660259)
#11 0x0000000002860905 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla + 0x2660905)
#12 0x0000000002860363 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIiEEvEE (scylla + 0x2660363)
#13 0x000000000285e006 _ZL11scylla_mainiPPc (scylla + 0x265e006)
#14 0x000000000285a333 main (scylla + 0x265a333)
#15 0x000000004159f248 __libc_start_call_main (libc.so.6 + 0x3248)
#16 0x000000004159f30b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x330b)
#17 0x00000000030cb1c5 _start (scylla + 0x2ecb1c5)
Stack trace of thread 4364:
#0  0x000000004168ed9d syscall (libc.so.6 + 0xf2d9d)
#1  0x0000000005bcb3ef _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla + 0x59cb3ef)
#2  0x00000000019e1a52 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla + 0x17e1a52)
#3  0x00000000019e1b81 _ZN7seastar19reactor_backend_aio23wait_and_process_eventsEPK10__sigset_t (scylla + 0x17e1b81)
#4  0x0000000001956d2f _ZN7seastar7reactor6do_runEv (scylla + 0x1756d2f)
#5  0x0000000005bb5d26 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x59b5d26)
#6  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#7  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#8  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4359:
#0  0x000000004168ed9d syscall (libc.so.6 + 0xf2d9d)
#1  0x0000000005bcb3ef _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla + 0x59cb3ef)
#2  0x00000000019e1a52 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla + 0x17e1a52)
#3  0x00000000019e1b81 _ZN7seastar19reactor_backend_aio23wait_and_process_eventsEPK10__sigset_t (scylla + 0x17e1b81)
#4  0x0000000001956d2f _ZN7seastar7reactor6do_runEv (scylla + 0x1756d2f)
#5  0x0000000005bb5d26 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x59b5d26)
#6  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#7  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#8  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4365:
#0  0x000000004168ed9d syscall (libc.so.6 + 0xf2d9d)
#1  0x0000000005bcb3ef _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla + 0x59cb3ef)
#2  0x00000000019e1a52 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla + 0x17e1a52)
#3  0x00000000019e1b81 _ZN7seastar19reactor_backend_aio23wait_and_process_eventsEPK10__sigset_t (scylla + 0x17e1b81)
#4  0x0000000001956d2f _ZN7seastar7reactor6do_runEv (scylla + 0x1756d2f)
#5  0x0000000005bb5d26 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x59b5d26)
#6  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#7  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#8  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4361:
#0  0x000000004168ed9d syscall (libc.so.6 + 0xf2d9d)
#1  0x0000000005bcb3ef _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla + 0x59cb3ef)
#2  0x00000000019e1a52 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla + 0x17e1a52)
#3  0x00000000019e1b81 _ZN7seastar19reactor_backend_aio23wait_and_process_eventsEPK10__sigset_t (scylla + 0x17e1b81)
#4  0x0000000001956d2f _ZN7seastar7reactor6do_runEv (scylla + 0x1756d2f)
#5  0x0000000005bb5d26 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x59b5d26)
#6  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#7  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#8  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4360:
#0  0x000000004168ed9d syscall (libc.so.6 + 0xf2d9d)
#1  0x0000000005bcb3ef _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla + 0x59cb3ef)
#2  0x00000000019e1a52 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla + 0x17e1a52)
#3  0x00000000019e1b81 _ZN7seastar19reactor_backend_aio23wait_and_process_eventsEPK10__sigset_t (scylla + 0x17e1b81)
#4  0x0000000001956d2f _ZN7seastar7reactor6do_runEv (scylla + 0x1756d2f)
#5  0x0000000005bb5d26 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x59b5d26)
#6  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#7  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#8  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4366:
#0  0x000000004168ed9d syscall (libc.so.6 + 0xf2d9d)
#1  0x0000000005bcb3ef _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla + 0x59cb3ef)
#2  0x00000000019e1a52 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla + 0x17e1a52)
#3  0x00000000019e1b81 _ZN7seastar19reactor_backend_aio23wait_and_process_eventsEPK10__sigset_t (scylla + 0x17e1b81)
#4  0x0000000001956d2f _ZN7seastar7reactor6do_runEv (scylla + 0x1756d2f)
#5  0x0000000005bb5d26 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x59b5d26)
#6  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#7  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#8  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4368:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4370:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4371:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4367:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4358:
#0  0x0000000041609bf9 __futex_abstimed_wait_common (libc.so.6 + 0x6dbf9)
#1  0x000000004160c38e pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x7038e)
#2  0x00000000430416c0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0x416c0)
#3  0x0000000003ede385 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5utils12alien_worker5spawnERN7seastar6loggerEiE3$_0EEEEE6_M_runEv (scylla + 0x3cde385)
#4  0x000000004304b524 n/a (libstdc++.so.6 + 0x4b524)
#5  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#6  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4369:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4372:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
Stack trace of thread 4373:
#0  0x000000004168384a read (libc.so.6 + 0xe784a)
#1  0x0000000005bcb905 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1ERNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data.llvm.1975846569410394747 (scylla + 0x59cb905)
#2  0x0000000005b694bb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x59694bb)
#3  0x000000004160cfa8 start_thread (libc.so.6 + 0x70fa8)
#4  0x0000000041690fcc __clone3 (libc.so.6 + 0xf4fcc)
ELF object binary architecture: AMD x86-64
Info about modules can be found in SCT logs by search for 'Coredump Modules info'
download_instructions:
gsutil cp gs://upload.scylladb.com/core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000./core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000.zst .
unzstd core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000.zst
executable=/opt/scylladb/libexec/scylla executable_version=2025.3.0
```

---

## Installation details

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-9 (null | 10.0.0.15) (shards: -1)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-8 (null | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-7 (null | 10.0.0.5) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-6 (null | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-5 (null | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-4 (null | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-3 (null | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-2 (null | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-15 (null | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-14 (null | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-13 (null | 10.0.0.5) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-12 (null | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-11 (null | 10.0.0.5) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-10 (null | 10.0.0.16) (shards: 7)
- longevity-10gb-3h-master-db-node-c1f2a170-eastus-1 (null | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-2025.3.0-dev-x86_64-2025-06-23T09-53-46` (azure: undefined_region)

Test: `longevity-10gb-3h-azure-test`
Test id: `c1f2a170-b8a7-4be8-88e4-e806751f7a20`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3612a404fde91199cc655e714fe3e93c939ccabb/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c1f2a170-b8a7-4be8-88e4-e806751f7a20`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c1f2a170-b8a7-4be8-88e4-e806751f7a20)
- Show all stored logs command: `$ hydra investigate show-logs c1f2a170-b8a7-4be8-88e4-e806751f7a20`

## Logs:
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-1-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-1-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-7-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-7-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-11** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-11-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-11-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-3-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-3-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-8-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-8-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-6-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-6-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-15** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-15-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-15-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-10-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-10-c1f2a170.tar.zst)
- **longevity-10gb-3h-master-db-node-c1f2a170-eastus-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-5-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_073405/longevity-10gb-3h-master-db-node-c1f2a170-eastus-5-c1f2a170.tar.zst)
- **core.scylla-longevity-10gb-3h-master-db-node-c1f2a170-eastus-13-2025-06-23_11-18-16.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000./core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000./core.scylla.107.49ddb4e15172485b9ff36b21566bd9a1.4357.1750677333000000.zst)
- **db-cluster-c1f2a170.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/db-cluster-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/db-cluster-c1f2a170.tar.zst)
- **schema-logs-c1f2a170.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/schema-logs-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/schema-logs-c1f2a170.tar.zst)
- **sct-runner-events-c1f2a170.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/sct-runner-events-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/sct-runner-events-c1f2a170.tar.zst)
- **sct-c1f2a170.log.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/sct-c1f2a170.log.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/sct-c1f2a170.log.tar.zst)
- **loader-set-c1f2a170.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/loader-set-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/loader-set-c1f2a170.tar.zst)
- **monitor-set-c1f2a170.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/monitor-set-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/monitor-set-c1f2a170.tar.zst)
- **parallel-timelines-report-c1f2a170.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/parallel-timelines-report-c1f2a170.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/20250623_112050/parallel-timelines-report-c1f2a170.tar.zst)
- **builder-c1f2a170.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/upload_20250623_112237/builder-c1f2a170.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1f2a170-b8a7-4be8-88e4-e806751f7a20/upload_20250623_112237/builder-c1f2a170.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/695/)
[Argus](https://argus.scylladb.com/test/aa05fe67-89bd-4e30-88db-5e2b2e3d986d/runs?additionalRuns[]=c1f2a170-b8a7-4be8-88e4-e806751f7a20)
</details>

### PR DESCRIPTION
**Pull request by gusev-p**
Previously, `raft_group0::abort()` was called in `storage_service::do_drain` (introduced in #24418) to stop the group0 Raft server before destroying local storage. This was necessary because `raft::server` depends on storage (via `raft_sys_table_storage` and `group0_state_machine`).

However, this caused issues: services like `sstable_dict_autotrainer` and `auth::service`, which use `group0_client` but are not stopped by `storage_service`, could trigger use-after-free if `raft_group0` was destroyed too early. This can happen both during normal shutdown and when 'nodetool drain' is used.

This PR reworks the shutdown logic:
* Introduces `abort_and_drain()`, which aborts the server and waits for background tasks to finish, but keeps the server object alive. Clients will see `raft::stopped_error` if they try to access group0 after this method is called.
* Final destruction now happens in `abort_and_destroy()`, called later from `main.cc`, ensuring safe cleanup.

The `raft_server_for_group::aborted` is changed to a `shared_future`, as it is now awaited in both abort methods.

Node startup can fail before reaching `storage_service`, in which case `drain_on_shutdown()` and `abort_and_drain()` are never called. To ensure proper cleanup, `raft_group0` deinitialization logic must be included in both `abort_and_drain()` and `abort_and_destroy()`.

Refs #25115

Fixes #24625

Backport: the changes are complicated and not safe to backport, we'll backport a revert of the original patch (#24418) in a separate PR.

### CODE REVIEW

**Comment by michoecho** [comment]
> Backport: not needed since the original patch https://github.com/scylladb/scylladb/pull/24418 was not backported.

The original patch is in branch-2025.3, so this PR does need a backport, to 2025.3.

**Review by michoecho — COMMENTED** [review]
I acknowledge the PR, but I don't understand the subject matter well enough to approve it.

**Comment by gusev-p** [comment]
> I acknowledge the PR, but I don't understand the subject matter well enough to approve it.

Thanks, I asked @gleb-cloudius for review.

**Comment by gusev-p** [comment]
> > Backport: not needed since the original patch #24418 was not backported.
> 
> The original patch is in branch-2025.3, so this PR does need a backport, to 2025.3.

OK

File: service/raft/raft_group0.cc [hunk 1]
```diff
@@ -425,10 +430,20 @@ future<> raft_group0::abort() {
     co_await _shutdown_gate.close();
 
     co_await std::move(_leadership_monitor);
+}
 
-    co_await stop_group0();
+future<> raft_group0::abort_and_drain() {
+    group0_log.debug("Aborting raft group0 service...");
+    co_await ensure_aborted();
```
Comment (gleb-cloudius) [inline service/raft/raft_group0.cc]: The way it is written the function can return before abort completes if called twice.

File: service/raft/raft_group_registry.cc [hunk 2]
```diff
@@ -405,13 +406,15 @@ future<> raft_group_registry::start_server_for_group(raft_server_for_group new_g
...
-void raft_group_registry::abort_server(raft::group_id gid, sstring reason) {
+future<> raft_group_registry::abort_server(raft::group_id gid, sstring reason) {
     // abort_server could be called from on_background_error for group0
     // when the server has not yet been added to _servers.
     // In this case we won't find gid in the if below.
     if (const auto it = _servers.find(gid); it != _servers.end()) {
         ensure_aborted(it->second, std::move(reason));
+        return it->second.aborted->get_future();
     }
+    return make_ready_future<>();
```
Comment (gleb-cloudius) [inline service/raft/raft_group_registry.cc:399]: Here again it `abort_server()` id called twice the second call will return before the server is aborted, no?

File: service/raft/raft_group0.hh [hunk 3]
```diff
@@ -154,8 +155,14 @@ public:
...
-    // Call before destroying the object.
-    future<> abort();
+    // Deinitializes the group0 Raft server and stops all its background activities.
+    // The server object remains alive, but new requests will get raft::stopped_error.
+    future<> abort_and_drain();
+
+    // Destroys the Raft server instance registered in raft_group_registry.
+    // It must be ensured that no one accesses it from this point on, including via raft_group0_client.
+    // Must be called before destroying the raft_group0 object.
+    future<> abort_and_destroy();
```
Comment (gleb-cloudius) [inline service/raft/raft_group0.hh]: Wouldn't it be more composable to have two functions `future<> abort()` that only aborts but not destroys and `void destroy()` that actually frees the object?

Comment (gusev-p) [reply service/raft/raft_group0.hh]: probably we can even have one function abort(), which does `abort_and_drain` and do destroy() in raft_group0 destructor

File: service/raft/raft_group_registry.cc (hunk 2 above)
Comment (gusev-p) [reply service/raft/raft_group_registry.cc:399]: if we didn't find gid, then the server was already drained and destroyed. If drain_and_abort is in progress, then we'll look at the same abort future.

**Comment by gusev-p** [comment]
new version:
  * abort_and_destroy -> destroy
  * remove raft_group_registry::stop_servers and drain_on_shutdown

File: service/raft/raft_group0.cc [hunk 4]
```diff
@@ -413,8 +414,12 @@ future<group0_info> persistent_discovery::run(
     }
 }
 
-future<> raft_group0::abort() {
-    group0_log.debug("Raft group0 service is aborting...");
+future<> raft_group0::abort_and_drain() {
+    if (_aborted) {
+        co_return;
```
Comment (gleb-cloudius) [inline service/raft/raft_group0.cc]: Shouldn't we assert here? How do we know previous abort completed?

Comment (gusev-p) [reply service/raft/raft_group0.cc]: `abort_and_drain` is not supposed to be called concurrently. What's possible is that we called it in `do_drain`, got exception, and then call it again from main.cc, but then there's little value to wait on that previous abort future -- we'll get the same exception.

File: service/raft/raft_group0.hh (hunk 3 above)
Comment (gusev-p) [reply service/raft/raft_group0.hh]: Unfortunately, we can't do this in destructor, because `raft_gr.stop().get();` is called at `main.cc:1708`, before `service::raft_group0 group0_service` is destroyed at `main.cc:1658`.

**Comment by gusev-p** [comment]
Created [Jenkins job](https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/3129/parameters/) with all test.py and dtest tests

File: service/raft/raft_group0.cc (hunk 4 above)
Comment (gleb-cloudius) [reply service/raft/raft_group0.cc]: But then we will continue with shutdown without waiting for background work to complete. May be `_abort` should be a feature?

Comment (gusev-p) [reply service/raft/raft_group0.cc]: > But then we will continue with shutdown without waiting for background work to complete.

What specific scenario you have in mind? I can think of this one:
* `on_background_error` calls `abort_server`
* `abort_and_drain` called from `do_drain`, fails before reaching `abort_server`
* `abort_and_drain` is called from main.cc and skips the entire `raft_group0` abort procedure

This way `abort_server` future won't be waited on.

It doesn't seem like this code can throw:
```
co_await smp::invoke_on_all([this]() {
   return uninit_rpc_verbs(_ms.local());
});

_leadership_monitor_as.request_abort();

co_await _shutdown_gate.close();

co_await std::move(_leadership_monitor);
```
but we could try/catch/swallow it just in case

Comment (gleb-cloudius) [reply service/raft/raft_group0.cc]: > > But then we will continue with shutdown without waiting for background work to complete.
> 
> What specific scenario you have in mind? I can think of this one:

I want API to be safe to use. The code changes all the time.

Comment (gusev-p) [reply service/raft/raft_group0.cc]: updated

**Comment by gusev-p** [comment]
new version:
   * raft_group0._aborted -> future
   * try/catch raft_group0 own abort code
   * inline ensure_aborted, since it now has only one usage

File: service/raft/raft_group0.cc [hunk 5]
```diff
@@ -413,22 +414,45 @@ future<group0_info> persistent_discovery::run(
     }
 }
 
-future<> raft_group0::abort() {
-    group0_log.debug("Raft group0 service is aborting...");
+future<> raft_group0::abort_and_drain() {
+    if (!_aborted) {
+        _aborted = futurize_invoke([this]() -> future<> {
```
Comment (gleb-cloudius) [inline service/raft/raft_group0.cc]: I think this lambda co-routine here will be freed to early.

Comment (gusev-p) [reply service/raft/raft_group0.cc]: It doesn't use any lambda-local state -- no problem)

I remember I added a helper `ensure_alive` in `storage_service`, probably i can reuse it here.

Comment (gleb-cloudius) [reply service/raft/raft_group0.cc]: > It doesn't use any lambda-local state -- no problem)
> 

It uses `this`.

Comment (gusev-p) [reply service/raft/raft_group0.cc]: extracted a helper

File: service/raft/raft_group0.cc [hunk 6]
```diff
@@ -413,26 +414,51 @@ future<group0_info> persistent_discovery::run(
...
-    if (_aborted) {
-        co_return;
+future<> raft_group0::abort_and_drain() {
+    if (!_aborted) {
+        // Async lambdas are destroyed at the first co_await,
+        // so accessing lambda-local state (like 'this') afterward would result
+        // in use-after-free. To avoid that, we delegate to a helper function,
+        // do_abort_and_drain().
+
+        _aborted = futurize_invoke([this]() { return do_abort_and_drain(); });
```
Comment (michoecho) [inline service/raft/raft_group0.cc:424]:
```suggestion
        _aborted = do_abort_and_drain();
```

Comment (gusev-p) [reply service/raft/raft_group0.cc:424]: this wouldn't capture exceptions thrown before the first co_await, would it?

Comment (michoecho) [reply service/raft/raft_group0.cc:424]: You're right. I didn't realize you were thinking about exceptions here. Nevermind.

File: service/raft/raft_group_registry.cc [hunk 7]
```diff
@@ -297,15 +276,13 @@ const raft::server_id& raft_group_registry::get_my_raft_id() {
 }
 
 seastar::future<> raft_group_registry::stop() {
-    co_await drain_on_shutdown();
+    if (_servers.size() > 0) {
+        on_internal_error(rslog, format("stop(): server {} is not destroyed", _servers.begin()->first));
```
Comment (patjed41) [inline service/raft/raft_group_registry.cc]: nit: you log group id here, but you call it "server". Maybe change it to "server for group {} is not destroyed"

File: main.cc [hunk 8]
```diff
@@ -2134,7 +2134,8 @@ sharded<locator::shared_token_metadata> token_metadata;
             group0_service.start().get();
```
Comment (patjed41) [inline main.cc:2134]: The bot will refuse to backport this PR without Fixes in the cover letter.

Also, backporting the first commit of this PR only to 2025.3 makes sense, but backporting the second commit only to 2025.3 doesn't seem right. We should either:
- not backport this commit at all, or
- backport it to all supported branches having #24401 (which seem to be all supported branches).

#24418 has
> Backport: no backport -- not safe and the problem is minor.

and you explained that backporting it is problematic: https://github.com/scylladb/scylladb/issues/24401#issuecomment-3097521269. The second commit of this PR looks even more risky than #24418 to me, so I wouldn't backport it.

You can change the backport label to none and send a PR to 2025.3 that reverts 6b85ab79d60c37fe1ac745e5613adb5429ab565b manually.

**Review by patjed41 — CHANGES_REQUESTED** [review]
Looks good, although it would be best if all group0 users were drained before aborting

File: main.cc (hunk 8 above)
Comment (patjed41) [reply main.cc:2134]: If we don't backport the second commit to 2025.3, we will also have to revert b1050944a3df28b3368e4328dfd506bcf8e1f424 there.

Comment (patjed41) [reply main.cc:2134]: I see that https://github.com/scylladb/scylladb/pull/25115 and https://github.com/scylladb/scylladb/pull/25101 are going to be backported to 2025.3, so maybe we should backport everything only to 2025.3. I'm not sure anymore.

File: service/raft/raft_group_registry.cc (hunk 7 above)
Comment (gusev-p) [reply service/raft/raft_group_registry.cc]: Yes, this is a typo, I'll fix it, thanks.

File: main.cc (hunk 8 above)
Comment (gusev-p) [reply main.cc:2134]: I added `backport/2025.3` because #25115 and #25101 need to be backported to 2025.3. I would prefer not to backport this PR anywhere else, if possible. The problem with group0 shutdown order that `test_create_lots_of_schema_churn` reveals is not that severe.

Comment (patjed41) [reply main.cc:2134]: IIUC, if we only revert 6b85ab79d60c37fe1ac745e5613adb5429ab565b and b1050944a3df28b3368e4328dfd506bcf8e1f424 on 2025.3, then we don't have to backport anything else. 2025.3 will have #24401 like other branches and that's it. I'd rather have a not severe known problem on 2025.3 than suddenly backport so many untested and complicated shutdown changes (especially the second commit of this PR).

Comment (gusev-p) [reply main.cc:2134]: Agree.

I'll remove `backport/2025.3` and prepare a manual backport for https://github.com/scylladb/scylladb/commit/6b85ab79d60c37fe1ac745e5613adb5429ab565b and https://github.com/scylladb/scylladb/commit/b1050944a3df28b3368e4328dfd506bcf8e1f424

**Review by gleb-cloudius — APPROVED** [review]

**Comment by gusev-p** [comment]
@patjed41 please review/merge

File: main.cc (hunk 8 above)
Comment (gusev-p) [reply main.cc:2134]: https://github.com/scylladb/scylladb/pull/25206 - backport to `2025.3`

**Comment by michoecho** [comment]
@gusev-p Add a `Fixes #24625` line to the PR cover letter so that we don't forget to close the issue when this gets merged.
