### PR TITLE
Fix topology management when raft-based topology is enabled

### LINKED ISSUE #13495: Cannot boot a node with experimental raft: "cannot pop this_node"
HEAD: 50ee4033a92e395e70c08e64d60667bb2681fd2b

I cannot manage to successfully start a single node cluster with `--experimental-features raft` enabled.

Command used:
```
build/dev/scylla --alternator-address 127.0.0.1 --api-address 127.0.0.1 --developer-mode true --experimental true --experimental-features raft --listen-address 127.0.0.1 --memory 3G --overprovisioned --prometheus-address 127.0.0.1 --ring-delay-ms 5000 --rpc-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --shadow-round-ms 10000 --skip-wait-for-gossip-to-settle 0 --smp 1 --unsafe-bypass-fsync 1 --workdir /tmp/scylla-workdir-hxjh897_
```

Very soon after starting a node I get the following error:

```
INFO  2023-04-13 09:01:15,510 [shard 0] storage_service - raft topology: adding myself to topology: 17a36569-b2fb-4dd6-922b-7c45110c0156
INFO  2023-04-13 09:01:15,511 [shard 0] storage_service - raft topology: coordinator fiber found a node to work on id=17a36569-b2fb-4dd6-922b-7c45110c0156 state=none
INFO  2023-04-13 09:01:15,511 [shard 0] boot_strapper - Get random bootstrap_tokens={<tokens cut for brevity>}
ERROR 2023-04-13 09:01:15,513 [shard 0] topology - topology[0x6000001cfd68]: node=0x600006e3e660 idx=0 host_id=00000000-0000-0000-0000-000000000000 endpoint=127.0.0.1 dc=datacenter1 rack=rack1 state=joining this_node=false: cannot pop this_node
ERROR 2023-04-13 09:01:15,513 [shard 0] storage_service - Failed to update pending ranges for bootstrapping node 17a36569-b2fb-4dd6-922b-7c45110c0156/127.0.0.1: seastar::internal::backtraced<std::runtime_error> (topology[0x6000001cfd68]: node=0x600006e3e660 idx=0 host_id=00000000-0000-0000-0000-000000000000 endpoint=127.0.0.1 dc=datacenter1 rack=rack1 state=joining this_node=false: cannot pop this_node Backtrace: <backtrace cut for brevity>
```

I noticed the issue after rebasing my changes on top of newest master. 36e53d571cb934b7ca64fc9c7270388144e91730 doesn't have this problem. I didn't try bisecting.

### PR DESCRIPTION
**Pull request by tgrabiec**
Fixes a problem when raft-based topology is enabled, which loads
topology from storage. It starts by clearing topology and then adding
nodes one by one. Before this patch, this violates internal invariant
of topology object which puts the local node as the first node. This
would manifest by triggering an assert in topology::pop_node() which
throws if popping the node at index 0 in order to keep the information
about local node around. This is normally prevented by a check in
topology::remove_node() which avoid calling pop_node() if removing the
local node. But since there is no node which is marked as local, this
check allows the first node to be popped.

To fix the problem I lift the invariant that local node is always in
_nodes. We still have information about local node in config. Instead
of keeping it in _nodes, we recognize it as part of indexing. We also
allow removing the local node like a regular node.

The path which reloads topology works correctly after this, the local
node will be recognized when (if) it is added to the topology.

Fixes #13495

### CODE REVIEW

File: locator/topology.cc [hunk 1]
```diff
@@ -307,6 +312,10 @@ void topology::index_node(const node* node) {
     _dc_endpoints[dc].insert(endpoint);
     _dc_racks[dc][rack].insert(endpoint);
     _datacenters.insert(dc);
+
+    if (node->is_this_node()) {
+        _this_node = node;
+    }
```
Comment (bhalevy) [inline locator/topology.cc:318]: nit: please add a comment that the function must no throw below this point

File: locator/topology.cc [hunk 2]
```diff
@@ -503,6 +503,18 @@ std::weak_ordering topology::compare_endpoints(const inet_address& address, cons
...
+        << ", this_endpoint: " << t._cfg.this_endpoint
+        << ", dc: " << t._cfg.local_dc_rack.dc
+        << ", rack: " << t._cfg.local_dc_rack.rack
+        << ", nodes:\n";
+    for (auto&& node : t._nodes) {
+        out << "  " << topology::debug_format(&*node) << "\n";
+    }
+    return out << "}";
+}
+
```
Comment (bhalevy) [inline locator/topology.cc:517]: why not in namespace std like the other printers?

File: locator/topology.cc (hunk 1 above)
Comment (tgrabiec) [reply locator/topology.cc:318]: It actually can throw, when invoked from add_node(), the node will be popped, which will revert this change.

When called from update_node(), failure is not handled, but that seems to be a more general bug in update_node(), because index_node() may throw and partially index the node. What are the exception safety guarantees of update_node()? I don't see it documented.

Comment (bhalevy) [reply locator/topology.cc:318]: That's a good point.
You're right about reverting the change in pop_node and about mutating a temporary copy at the higher level.

File: locator/topology.cc [hunk 3]
```diff
@@ -72,14 +73,12 @@ topology::topology(config cfg)
 {
     tlogger.trace("topology[{}]: constructing using config: host_id={} endpoint={} dc={} rack={}", fmt::ptr(this),
             cfg.this_host_id, cfg.this_endpoint, cfg.local_dc_rack.dc, cfg.local_dc_rack.rack);
-    if (cfg.this_host_id || cfg.this_endpoint != inet_address{}) {
-        add_node(node::make(this, cfg.this_host_id, cfg.this_endpoint, cfg.local_dc_rack, node::state::joining, node::this_node::yes));
-    }
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply locator/topology.cc:82]: But then aren't we back to the problem of losing `this_node` after clear_gently()?

I think that even before this patch, replacing with the same ip will put `this_node` on the bootstrapping node into leaving state, because we lookup by IP when changing state. There is no way to hold two nodes with the same IP currently because data structures are indexed by IP.

The only cure for nervousness is to identify nodes by host_id and have the state of topology not depend on the order of operations. If we identify by host id, and we want to keep both nodes, we should put the local host id into topology::config before populating it for the topology to distinguish the nodes. But that requires also changing the interface for updates to accept host id instead of IP.

[the remark this answers is not in the document]
Comment (bhalevy) [reply locator/topology.cc:82]: That's the direction we're aiming at but we're not quite there yet.

We need to test the hello out of this change to make sure it doesn't introduce regressions.
I recommend the following dtest suites: repair_based_node_operations.py replace_address_test.py update_cluster_layout_tests.py

[the remark this answers is not in the document]
Comment (tgrabiec) [reply locator/topology.cc:82]: I ran repair_based_node_operations.py and replace_address_test.py and they passed except for replace_address_test.py::TestReplaceAddress::test_replace_node_no_hibernate_state, which is a preexisting issue (reproduces without the PR): https://github.com/scylladb/scylladb/issues/13543

File: locator/topology.cc (hunk 2 above)
Comment (tgrabiec) [reply locator/topology.cc:517]: Fixed.

**Comment by tgrabiec** [comment]
In V2:
  - moved operator<< to std namespace
  - added unit test

**Comment by kbr-scylla** [comment]
@gleb-cloudius please review
@bhalevy please re-review

without this it's harder to work on topology coordinator follow-ups, and it's blocking #13387

File: locator/topology.cc [hunk 4]
```diff
@@ -72,14 +73,12 @@ topology::topology(config cfg)
...
 }
 
 topology::topology(topology&& o) noexcept
     : _shard(o._shard)
     , _cfg(std::move(o._cfg))
+    , _this_node(std::move(o._this_node))
```
Comment (bhalevy) [inline locator/topology.cc:81]: nit: should be `std::exchange(o._this_node, nullptr)`

**Review by bhalevy — APPROVED** [review]
I had just one nit comment.
Can be fixed in a follow up

**Comment by tgrabiec** [comment]
It needs a rebase, I'll send a new version.

**Comment by tgrabiec** [comment]
In V3:
  - rebased and adapted locator_topology_test to new rules
  - null _this_node when moving
  - fix move assignment operator (preexisting problem) and add unit test for it

**Review by bhalevy — APPROVED** [review]
LGTM, thanks

File: locator/topology.cc [hunk 5]
```diff
@@ -105,7 +101,7 @@ topology::topology(topology&& o) noexcept
 }
 
 future<topology> topology::clone_gently() const {
-    topology ret;
+    topology ret(_cfg);
```
Comment (kbr-scylla) [inline locator/topology.cc:111]: This constructor has an `add_node` call in it, unlike the previously used default constructor.
Won't this potentially cause `add_node` to be called twice for the same node - by the constructor and later by the `for` loop below?

Comment (kbr-scylla) [reply locator/topology.cc:111]: Hm, but I see you remove the `add_node` call in the constructor in a later commit.

**Comment by kbr-scylla** [comment]
Qd
