### PR TITLE
topology_coordinator: stop: await all background_action_holder:s

### LINKED ISSUE #23755: topology_coordinator::stop doesn't await all background actions
This was seen as the following warnings about an abandoned failed future with a version earlier than scylladb/scylladb@9f97d21339.
But the background actions must be awaited whether successful or not.

Currently, we still keep the failed action
exceptional future in the `background_action_holder`. This triggers warnings about ignored exceptional futures, like the ones seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7169/artifact/testlog/x86_64/debug/scylla-1176.log for example:
```
WARN  2024-03-06 18:27:07,967 [shard 0:strm] seastar - Exceptional future ignored: seastar::broken_promise (broken promise), backtrace: 0xd4179ca /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5685f9c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5685cf7 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5688075 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5688acf /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4391abf /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4391dbb 0x1374f403 0x1374f262 0x1374ef56 0x1374eede 0x1375cb72 0x137062c6 0x136f3250 0xd669ef6 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4715728 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x471dce8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4721d80 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x471fa03 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4258cda /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x425627a 0xd4b1389 0xd4ae26f /lib64/libc.so.6+0x27b89 /lib64/libc.so.6+0x27c4a 0xd3d22a4
```

Decoded:
```
seastar::future_state_base::any::check_failure() at ././seastar/include/seastar/core/future.hh:561
 (inlined by) seastar::future_state<seastar::internal::monostate>::clear() at ././seastar/include/seastar/core/future.hh:606
 (inlined by) ~future_state at ././seastar/include/seastar/core/future.hh:611
 (inlined by) ~future at ././seastar/include/seastar/core/scheduling.hh:42
 (inlined by) std::_Optional_payload_base<seastar::future<void> >::_M_destroy() at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/optional:287
 (inlined by) std::_Optional_payload_base<seastar::future<void> >::_M_reset() at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/optional:318
 (inlined by) ~_Optional_payload at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/optional:439
 (inlined by) ~_Optional_base at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/optional:510
 (inlined by) ~pair at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:187
 (inlined by) void std::destroy_at<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > > >(std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_construct.h:88
 (inlined by) void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, false> > >::destroy<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > > >(std::allocator<std::__detail::_Hash_node<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, false> >&, std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/alloc_traits.h:559
 (inlined by) std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, false> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, false>*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/hashtable_policy.h:2024
std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, false> > >::_M_deallocate_nodes(std::__detail::_Hash_node<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, false>*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/hashtable_policy.h:2046
 (inlined by) std::_Hashtable<locator::tablet_transition_stage, std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > >, std::allocator<std::pair<locator::tablet_transition_stage const, std::optional<seastar::future<void> > > >, std::__detail::_Select1st, std::equal_to<locator::tablet_transition_stage>, std::hash<locator::tablet_transition_stage>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear() at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/hashtable.h:2509
~_Hashtable at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/hashtable.h:1593
 (inlined by) ~unordered_map at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unordered_map.h:109
 (inlined by) ~tablet_migration_state at ./service/topology_coordinator.cc:823
```

### PR DESCRIPTION
**Pull request by bhalevy**
Add missing awaits for the rebuild_repair and repair background actions.
Although the background actions hold the _async_gate
which is closed in topology_coordinator::run(),
stop() still needs to await all background action futures
and handle any errors they may have left behind.

Fixes #23755

* The issue exists since 6.2

### CODE REVIEW

**Comment by bhalevy** [comment]
@tgrabiec ping, please review

**Comment by avikivity** [comment]
Dequeuing, breaks build

**Comment by bhalevy** [comment]
In v2 ([ae51651](https://github.com/scylladb/scylladb/commit/ae516512d1214ca6f967e534983c6e1283b34c94)):
- turned `background_action_holder` into a proper class that handles all errors from the delayed action and returns them on `wait()`

**Comment by tgrabiec** [comment]
What was the cause for those warnings exactly?

The fact that topology_coordinator::stop() didn't join with all the holders? Why not fix that, and add tablet_migration_state::stop()

**Comment by bhalevy** [comment]
> What was the cause for those warnings exactly?
> 
> The fact that topology_coordinator::stop() didn't join with all the holders? Why not fix that, and add tablet_migration_state::stop()

I don't know exactly, but if we make sure to never abandon any holder and it would work too.
I think it's more fragile though.

**Comment by tgrabiec** [comment]
If `topology_coordinator::stop()` is supposed to join with background tasks, then we're papering-over a bug here.

**Comment by bhalevy** [comment]
> If `topology_coordinator::stop()` is supposed to join with background tasks, then we're papering-over a bug here.

You're right.
Opened https://github.com/scylladb/scylladb/issues/23755 to track that.

**Comment by bhalevy** [comment]
In v3 ([7ca1caa](https://github.com/scylladb/scylladb/commit/7ca1caa8a1d586620d9302e36f7b28e2c35e4e57)):
- topology_coordinator: stop: define stop_background_action helper
- topology_coordinator: stop: await all background_action_holder:s

File: service/topology_coordinator.cc [hunk 1]
```diff
@@ -3537,6 +3537,12 @@ future<> topology_coordinator::stop() {
         if (tablet_state.cleanup) {
             co_await stop_background_action(tablet_state.cleanup, gid, [] { return "when cleanup"; });
         }
+        if (tablet_state.rebuild_repair) {
+            co_await stop_background_action(tablet_state.rebuild_repair, gid, [] { return "when rebuild_repair"; });
+        }
+        if (tablet_state.repair) {
+            co_await stop_background_action(tablet_state.repair, gid, [] { return "when repair"; });
```
Comment (tgrabiec) [inline service/topology_coordinator.cc:3544]: "failed ... when repair" doesn't sound grammatical, maybe "failed ... during repair".

File: service/topology_coordinator.cc [hunk 2]
```diff
@@ -3513,35 +3513,29 @@ future<> topology_coordinator::stop() {
...
-            try {
-                co_await std::move(*barrier);
-            } catch (...) {
-                rtlogger.warn("Tablet '{}' migration failed at stage {}: {}",
-                              gid, tablet_transition_stage_to_string(stage), std::current_exception());
-            }
+            co_await stop_background_action(barrier, gid, [stage] { return format("at stage {}", tablet_transition_stage_to_string(stage)); });
         }
 
         if (tablet_state.streaming) {
```
Comment (tgrabiec) [inline service/topology_coordinator.cc:3534]: You can fold the if into stop_background_action().

Comment (bhalevy) [reply service/topology_coordinator.cc:3534]: Yes, actually that was my first approach, but that will allocate the coroutine frame for every call.
OTOH, the stop path doesn't need to be optimized.

**Comment by bhalevy** [comment]
> #### Failed Tests (1/43746):
> * [test_read_with_partition_row_limits](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/16796/testReport/junit/boost/multishard_mutation_query_test/test_read_with_partition_row_limits) [🔍](https://github.com/scylladb/scylladb/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+test_read_with_partition_row_limits)

Unrelated: https://github.com/scylladb/scylladb/issues/16794

File: service/topology_coordinator.cc (hunk 1 above)
Comment (bhalevy) [reply service/topology_coordinator.cc:3544]: I followed the "when cleanup" convention, but can change to make the message make more sense.
We can probably

**Comment by bhalevy** [comment]
I v4 ([7a0f5e0](https://github.com/scylladb/scylladb/commit/7a0f5e0a54d9a401bf7cac44005bf3b34f1cbf9c)):
- Folded `if (holder)` into the `stop_background_action` helper.
- Improved error messages grammar.

**Review by tgrabiec — APPROVED** [review]

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider merging
