### PR TITLE
Fix getendpoints command for compound keys containing ':'

### LINKED ISSUE #16596: storage_service/get_natural_endpoints has no way to pass a key containing a colon character
As noted by @KrzaQ:
> How do I use nodetool getendpoints with compound keys? The internet advice seems to be pass the key separated by colon (e.g. nodetool getendpoints mykeyspace superheroes "peter:parker" ), but what do I do if the key itself contains colons?
In my case - audit.audit_log, one of the columns is of type timestamp, so a value could be 2023-12-31 00:00:00.000000+0000 .
I tried following the java code for the tool, but no luck yet.

To enable support at the jmx/nodetool level (or scylla-nodetool), the scylla api needs to support a way to pass key values containing `:`, otherwise they are recognized as composite keys, with the column as key delimiter.

Since the key is passed over an http-based interface I suggest to allow encoding `:` characters using the standard http encoding as `%3A` substrings (`seastar::http::internal::url_decode` can be used to decode such strings).

### PR DESCRIPTION
**Pull request by tarasveretilnyk**
Before, the `nodetool getendpoints` expected the key as one string separated by : (for example 1:val:ue). This caused errors if any part of the key had a colon because it was unclear whether a colon was a separator or part of the key.

This change adds a new API endpoint, `/storage_service/natural_endpoints/v2/{keyspace}`, which accepts composite partition keys as multiple key_component query parameters (e.g., ?key_component=1&key_component=val:ue). The `nodetool getendpoints` command was updated to support a new `--key-components` option, allowing users to pass key components as an array. The client and test infrastructure were extended to support multiple values for a query parameter, and tests were added to verify correct behavior with composite keys.

The previous method of passing partition keys as colon-separated strings is preserved for backward compatibility.

Backport is not required, since this change relies on recent Seastar updates

Fixes #16596

### CODE REVIEW

**Comment by tarasveretilnyk** [comment]
Note: These changes will break the existing API. Please let me know if we need to support the previous API version, so I can prepare and upload a patch accordingly.

**Comment by mykaul** [comment]
> Backport is not required

Not required, but why wouldn't we backport such a fix?

**Comment by tarasveretilnyk** [comment]
> > Backport is not required
> 
> Not required, but why wouldn't we backport such a fix?

Because this fix requires recent seastar patch(https://github.com/scylladb/seastar/pull/2872/commits/46b66ec615e194b9b022cbd53b08e1e00e8f908c)

**Comment by denesb** [comment]
> > > Backport is not required
> > 
> > 
> > Not required, but why wouldn't we backport such a fix?
> 
> Because this fix requires recent seastar patch([scylladb/seastar@46b66ec](https://github.com/scylladb/seastar/commit/46b66ec615e194b9b022cbd53b08e1e00e8f908c))

Requiring a seastar patch on its own is not automatic exclusion for backport. We have done it before. We use the same criteria for seastar.git patch backport that we use for scylladb.git ones: what is the risk/benefit ratio? If it is reasonable, we can backport it.

**Comment by tarasveretilnyk** [comment]
> > > > Backport is not required
> > > 
> > > 
> > > Not required, but why wouldn't we backport such a fix?
> > 
> > 
> > Because this fix requires recent seastar patch([scylladb/seastar@46b66ec](https://github.com/scylladb/seastar/commit/46b66ec615e194b9b022cbd53b08e1e00e8f908c))
> 
> Requiring a seastar patch on its own is not automatic exclusion for backport. We have done it before. We use the same criteria for seastar.git patch backport that we use for scylladb.git ones: what is the risk/benefit ratio? If it is reasonable, we can backport it.

I'm not sure whether it's worth backporting or not - it depends on how frequently users encounter these issues. However, the fix for non-composite partition keys has already been merged (#24829) and backported, so that probably fixes most of the problems.
Perhaps @mykaul might have more insight.

File: keys/keys.hh [hunk 1]
```diff
@@ -704,6 +704,8 @@ public:
      */
     static partition_key from_nodetool_style_string(const schema_ptr s, const sstring& key);
 
+    static partition_key from_vector(const schema_ptr s, const std::vector<sstring>& components);
```
Comment (denesb) [inline keys/keys.hh]: I think this needs a better name, that communicates that it takes a vector of human readable string representation of the key. Adding `nodetool` to the name to communicate that this is avariant of the above overload would be good too.

File: tools/scylla-nodetool.cc [hunk 2]
```diff
@@ -4033,7 +4033,7 @@ For more information, see: {}"
                 {
                     typed_option<sstring>("keyspace", "The keyspace to query", 1),
                     typed_option<sstring>("table", "The table to query", 1),
-                    typed_option<sstring>("key", "The partition key for which we need to find the endpoint", 1),
+                    typed_option<std::vector<sstring>>("key", "List of components of the key for which we need to find the endpoint", -1),
```
Comment (denesb) [inline tools/scylla-nodetool.cc]: This is going to break everybody's muscle reflexes (and scripts). I think we need a new param name for the list syntax and keep the old one, with maybe e deprecation warning.

File: api/api-doc/storage_service.json [hunk 3]
```diff
@@ -584,10 +584,10 @@
                   },
                   {
                      "name":"key",
-                     "description":"key for which we need to find the endpoint return value - the endpoint responsible for this key",
+                     "description":"List of components of the key for which we need to find the endpoint",
                      "required":true,
-                     "allowMultiple":false,
-                     "type":"string",
+                     "allowMultiple":true,
+                     "type":"array",
```
Comment (denesb) [inline api/api-doc/storage_service.json]: We need to keep supporting the old syntax as-is, as this is public API. Maybe we need a new endpoint or (if we can get away with it) just a new param to the existing one.

**Comment by avikivity** [comment]
> > > > > Backport is not required
> > > > 
> > > > 
> > > > Not required, but why wouldn't we backport such a fix?
> > > 
> > > 
> > > Because this fix requires recent seastar patch([scylladb/seastar@46b66ec](https://github.com/scylladb/seastar/commit/46b66ec615e194b9b022cbd53b08e1e00e8f908c))
> > 
> > 
> > Requiring a seastar patch on its own is not automatic exclusion for backport. We have done it before. We use the same criteria for seastar.git patch backport that we use for scylladb.git ones: what is the risk/benefit ratio? If it is reasonable, we can backport it.
> 
> I'm not sure whether it's worth backporting or not - it depends on how frequently users encounter these issues. However, the fix for non-composite partition keys has already been merged (#24829) and backported, so that probably fixes most of the problems. Perhaps @mykaul might have more insight.

I don't think it's worth backporting. We survived for many years without it.

File: api/api-doc/storage_service.json (hunk 3 above)
Comment (avikivity) [reply api/api-doc/storage_service.json]: A new endpoint is fine, if a parameter type changed.

**Comment by tarasveretilnyk** [comment]
v2: Rebased and added new endpoint that accepts partition key by parts(Unfortunately I forgot to split rebase and my code into 2 separate versions)  
v3: Fixed error in documentation
v4: Corrected "key" nodetool param type

File: tools/scylla-nodetool.cc (hunk 2 above)
Comment (tarasveretilnyk) [reply tools/scylla-nodetool.cc]: Fixed in v2

File: keys/keys.hh (hunk 1 above)
Comment (tarasveretilnyk) [reply keys/keys.hh]: Fixed in v2. I'm not sure whether it worth adding `nodetool` to the prefix. It accept just list of components. For me, it doesn't seem to be related to specific nodetool format.

File: api/api-doc/storage_service.json (hunk 3 above)
Comment (tarasveretilnyk) [reply api/api-doc/storage_service.json]: I also believe the new endpoint is better. Adding another query parameter to specify the key by components would have required making both parameters optional and handling them manually in the API handler, which could introduce additional confusion for users. Resolved in v2.

File: tools/scylla-nodetool.cc [hunk 4]
```diff
@@ -4034,6 +4049,7 @@ For more information, see: {}"
                     typed_option<sstring>("keyspace", "The keyspace to query", 1),
                     typed_option<sstring>("table", "The table to query", 1),
                     typed_option<sstring>("key", "The partition key for which we need to find the endpoint", 1),
+                    typed_option<std::vector<sstring>>("key-components", "List of components of the key for which we need to find the endpoint", -1),
```
Comment (denesb) [inline tools/scylla-nodetool.cc:4053]: Is this how this looks like when invoked?
```
nodetool getendpoints --key-components comp1 --key-components comp2`
```
If so, maybe better to use singular (`--key-component`).

File: api/api-doc/storage_service.json [hunk 5]
```diff
@@ -594,6 +594,50 @@
             }
          ]
       },
+      {
+         "path": "/storage_service/natural_endpoints/v2/{keyspace}",
```
Comment (denesb) [inline api/api-doc/storage_service.json:598]: Not sure about this name, but don't have any better idea myself.

**Review by denesb — COMMENTED** [review]
Please also add a test to `test/nodetool`.

File: tools/scylla-nodetool.cc (hunk 4 above)
Comment (tarasveretilnyk) [reply tools/scylla-nodetool.cc:4053]: You can specify like you wrote. There also exists an alternative way:
`--key-components={"part1", "part2"}`

Comment (denesb) [reply tools/scylla-nodetool.cc:4053]: I have never seen this with boost options, interesting. I think most people will expect to use the above syntax. In any case, I'm fine with leaving the name in plural.

**Comment by tarasveretilnyk** [comment]
v5: Added test for new nodetool param
Added support of multiple query parameters to rest_api_mock
Avoid moving params when setting request_query_params in scylla_rest_client::do_request, as they are still needed for logging and request struct is also moved later.

**Review by denesb — APPROVED** [review]
Looks good, I will queue this, but please follow-up with another PR which improves the documentation, we need more detail on the new param, than just "alternative to key". We also need examples on how to use this new parameter.
