### PR TITLE
sstables: Fix use-after-free on page cache buffer when parsing promoted index entries across pages

### LINKED ISSUE #20766: SStable's clustering key index lookup may yield incorrect position
Affects scylla version >= 4.6.0

When this bug is triggered, an sstable read may use an incorrect index block. There will be no parsing errors. This may manifest as missing data which actually exists. That's the case if we jump to a position which is after the key. If we're jumping to an earlier position, we will still find the row, it will just take longer.

Clustering key index lookup is based on the index file page cache. We do a binary search within the index, which involves parsing index blocks touched by the algorithm. Index file pages are 4 KB chunks which are stored in LSA.   

To parse the first key of the block, we reuse `clustering_parser`, which is also used when parsing the data file. The parser is stateful and accepts consecutive chunks as `temporary_buffer`s. The parser is supposed to keep its state across chunks.

In b1b5bda848c0624a3e7e10a51c1a155421d2fdfe, the parser was changed to keep shared fragments of the buffer passed to the parser in its internal state (across pages) rather than copy the fragments into a new buffer. This is problematic when buffers come from page cache because LSA buffers may be moved around or evicted. So the temporary_buffer which is a view on the LSA buffer is valid only around the duration of a single consume() call to the parser:

```c++
 template <typename Consumer>
    future<> consume_stream(cached_file::stream& s, Consumer& c) {
        return repeat([&] {
            return s.next_page_view().then([&] (cached_file::page_view&& page) {
                if (!page) {
                    on_internal_error(sstlog, "End of stream while parsing");
                }
                return _as(_cached_file.region(), [&] {
                    auto buf = page.get_buf();
                    return stop_iteration(c.consume(buf) == data_consumer::read_status::ready);
                });
            });
        });
    }
```

If the blob which is parsed (e.g. variable-length clustering key component) spans pages, the fragments stored in the parser may be invalidated before the component is fully parsed. As a result, the parsed clustering key may have incorrect component values. This never causes parsing errors because the "length" field is always parsed from the current buffer, which is valid, and component parsing will end at the right place in the next (valid) buffer. 

The problematic path for clustering_key parsing is the one which calls `primitive_consumer::read_bytes()`, which is called for example for `text` components. Fixed-size components are not parsed like this, they store the intermediate state by copying data. 

```c++
    inline read_status read_bytes(temporary_buffer<char>& data, uint32_t len, fragmented_temporary_buffer& where) {
        if (data.size() >= len) {
            auto fragments = std::move(where).release();
            fragments.clear();
            fragments.push_back(data.share(0, len));
            where = fragmented_temporary_buffer(std::move(fragments), len);
            data.trim_front(len);
            return read_status::ready;
        } else {
            // copy what we have so far, read the rest later
            _read_bytes.clear();
            _read_bytes.push_back(data.share());

// ^^ data.share() is problematic, stores a view to the buffer which may be invalidated.

            _read_bytes_len = len;
            _read_bytes_where = &where;
            _pos = data.size();
            data.trim(0);
            _prestate = prestate::READING_BYTES;
            return read_status::waiting;
        }
    }
``` 

This may cause incorrect clustering keys to be parsed when doing binary search in the index, diverting the search to an incorrect block. The incorrect parsing has a scope of a single read because parsed blocks are cached within the reader. So later readers will not be affected. It is likely that the next parsing will not hit the problem for the same key, because both pages will be hot in cache, and the probability that buffers will be invalidated across pages is low. 

The problem is more likely to happen with larger indexes. If the index fits within 32KB, all its pages will be hot in cache due to read-ahead done to read the partition index entry. If pages are hot, they are unlikely to be invalidated during parsing because they are recently accessed and preemption when parsing across pages is unlikely. Also, most memory allocation is done when parsing the first page so LSA movement is unlikely.

Reducing "column-index-size-in-kb" makes the problem more likely because it makes the index larger, and the risk of page cache misses is higher.

Larger clustering keys make the problem more likely, because page crossing is more likely.

### PR DESCRIPTION
**Pull request by tgrabiec**
This fixes a use-after-free bug when parsing clustering key across
pages.

Also includes a fix for allocating section retry, which is potentially not safe (not in practice yet).

Details of the first problem:

Clustering key index lookup is based on the index file page cache. We
do a binary search within the index, which involves parsing index
blocks touched by the algorithm. Index file pages are 4 KB chunks
which are stored in LSA.

To parse the first key of the block, we reuse clustering_parser, which
is also used when parsing the data file. The parser is stateful and
accepts consecutive chunks as temporary_buffers. The parser is
supposed to keep its state across chunks.

In 93482439, the promoted index cursor was optimized to avoid 
fully page copy when parsing index blocks. Instead, parser is
given a temporary_buffer which is a view on the page.

A bit earlier, in b1b5bda, the parser was changed to keep shared 
fragments of the buffer passed to the parser in its internal state (across pages)
rather than copy the fragments into a new buffer. This is problematic 
when buffers come from page cache because LSA buffers may be moved
around or evicted. So the temporary_buffer which is a view on the LSA
buffer is valid only around the duration of a single consume() call to
the parser.

If the blob which is parsed (e.g. variable-length clustering key
component) spans pages, the fragments stored in the parser may be
invalidated before the component is fully parsed. As a result, the
parsed clustering key may have incorrect component values. This never
causes parsing errors because the "length" field is always parsed from
the current buffer, which is valid, and component parsing will end at
the right place in the next (valid) buffer.

The problematic path for clustering_key parsing is the one which calls
primitive_consumer::read_bytes(), which is called for example for text
components. Fixed-size components are not parsed like this, they store
the intermediate state by copying data.

This may cause incorrect clustering keys to be parsed when doing
binary search in the index, diverting the search to an incorrect
block.

Details of the solution:

We adapt page_view to a temporary_buffer-like API. For this, a new concept 
is introduced called ContiguousSharedBuffer. We also change parsers so that
they can be templated on the type of the buffer they work with (page_view vs
temporary_buffer). This way we don't introduce indirection to existing algorithms.

We use page_view instead of temporary_buffer in the promoted
index parser which works with page cache buffers. page_view can be safely
shared via share() and stored across allocating sections. It keeps hold to the
LSA buffer even across allocating sections by the means of cached_file::page_ptr.

Fixes #20766

### CODE REVIEW

**Comment by vladzcloudius** [comment]
> This fixes a use-after-free bug when parsing clustering key across pages.
> 
> Also includes a fix for allocating section retry, which is potentially not safe (not in practice yet).
> 
> Details of the first problem:
> 
> Clustering key index lookup is based on the index file page cache. We do a binary search within the index, which involves parsing index blocks touched by the algorithm. Index file pages are 4 KB chunks which are stored in LSA.
> 
> To parse the first key of the block, we reuse clustering_parser, which is also used when parsing the data file. The parser is stateful and accepts consecutive chunks as temporary_buffers. The parser is supposed to keep its state across chunks.
> 
> In [b1b5bda](https://github.com/scylladb/scylladb/commit/b1b5bda848c0624a3e7e10a51c1a155421d2fdfe), the parser was changed to keep shared fragments of the buffer passed to the parser in its internal state (across pages) rather than copy the fragments into a new buffer. This is problematic when buffers come from page cache because LSA buffers may be moved around or evicted. So the temporary_buffer which is a view on the LSA buffer is valid only around the duration of a single consume() call to the parser.
> 
> If the blob which is parsed (e.g. variable-length clustering key component) spans pages, the fragments stored in the parser may be invalidated before the component is fully parsed. As a result, the parsed clustering key may have incorrect component values. This never causes parsing errors because the "length" field is always parsed from the current buffer, which is valid, and component parsing will end at the right place in the next (valid) buffer.
> 
> The problematic path for clustering_key parsing is the one which calls primitive_consumer::read_bytes(), which is called for example for text components. Fixed-size components are not parsed like this, they store the intermediate state by copying data.
> 
> This may cause incorrect clustering keys to be parsed when doing binary search in the index, diverting the search to an incorrect block.
> 
> Details of the solution:
> 
> We adapt page_view to a temporary_buffer-like API. For this, a new concept is introduced called ContiguousSharedBuffer. We also change parsers so that they can be templated on the type of the buffer they work with (page_view vs temporary_buffer). This way we don't introduce indirection to existing algorithms.
> 
> We use page_view instead of temporary_buffer in the promoted index parser which works with page cache buffers. page_view can be safely shared via share() and stored across allocating sections. It keeps hold to the LSA buffer even across allocating sections by the means of cached_file::page_ptr.
> 
> Fixes #20766

Amazing! Thanks a lot for quickly developing this, @tgrabiec !

File: test/boost/index_reader_test.cc [hunk 1]
```diff
@@ -46,3 +47,95 @@ SEASTAR_TEST_CASE(test_abort_during_index_read) {
...
+
+                testlog.debug("start : {}", *block->start);
+                testlog.debug("end   : {}", *block->end);
+                BOOST_REQUIRE(eq(*block->start, pos));
+                BOOST_REQUIRE(eq(*block->end, pos));
+                if (prev_offset) {
+                    BOOST_REQUIRE_LT(*prev_offset, block->data_file_offset);
+                }
+            }
+            prev_block_offset = block_offset;
```
Comment (michoecho) [inline test/boost/index_reader_test.cc:135]: This assignment doesn't do anything, `prev_block_offset` dies immediately after it.

File: utils/contiguous_shared_buffer.hh [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+    && std::default_initializable<T>
+    && requires(T& obj, size_t pos, size_t len) {
+
+        // Creates a new buffer that shares the memory of the original buffer.
+        // The lifetime of the new buffer is independent of the original buffer.
+        { obj.share() } -> std::same_as<T>;
+
+        // Like share() but the new buffer represents a sub-range of the original buffer.
+        { obj.share(pos, len) } -> std::same_as<T>;
+
```
Comment (avikivity) [inline utils/contiguous_shared_buffer.hh:19]: Should we remove share() from the buffer provided by the cache, since it's unsafe?

**Comment by avikivity** [comment]
Should we change page_view not to return a temporary_buffer, since it violates its contract, but instead std::span\<const char>? Or perhaps a wrapper around std::span that makes it similar to temporary_buffer (but no share?)

File: utils/cached_file.hh [hunk 3]
```diff
@@ -208,26 +218,84 @@ public:
...
+        }
+
         // The returned buffer is valid only until the LSA region associated with cached_file invalidates references.
         temporary_buffer<char> get_buf() {
             auto buf = _page->get_buf_weak();
-            buf.trim(_size);
             buf.trim_front(_offset);
+            buf.trim(_size);
             return buf;
         }
```
Comment (michoecho) [inline utils/cached_file.hh:254]: `page_view::get_buf()` and `cached_page::get_buf_weak()` are unused after your series. And we don't want to keep them, because they are unsafe. Remove them.

**Review by michoecho — CHANGES_REQUESTED** [review]
Looks fine. Left some minor comments.

**Comment by michoecho** [comment]
> Should we change page_view not to return a temporary_buffer, since it violates its contract, but instead std::span<const char>? Or perhaps a wrapper around std::span that makes it similar to temporary_buffer (but no share?)

@avikivity It already does that. After this series, `page_view` doesn't return a `temporary_buffer` anymore. That interface only existed for use with the promoted index parser, which needed a `temporary_buffer`. Now that the parser can be used directly with `page_view`, it accesses its contents via `page_view::begin()`, which gets the current pointer to the LSA buffer from its underlying `cached_page`.

The dangerous function `temporary_buffer<char> page_view::get_buf()` still exists, but only because @tgrabiec forgot to remove it — it's unused after this series.

(As for whether `std::span<const char> view()` would be better than `const char* begin()` + `size_t size()`, that's a different question).

File: utils/contiguous_shared_buffer.hh (hunk 2 above)
Comment (michoecho) [reply utils/contiguous_shared_buffer.hh:19]: This `share` is safe. The shareable thing is `page_view` itself, which acts as a specialized `shared_ptr` to the underlying `cached_page` object (allocated in the standard allocator), which holds the pointer (updated on LSA migrations) to the actual LSA data.

It's fine to store and share the `page_view`. You only can't keep the `const char*` it returns (via `page_view::begin()`) across LSA reclaim points — after every reclaim point you have to get the current value via `begin()`.

**Comment by avikivity** [comment]
> (As for whether std::span<const char> view() would be better than const char* begin() + size_t size(), that's a different question).

They're functionally equivalent, no need to bother for such a leaf interface.

File: utils/contiguous_shared_buffer.hh (hunk 2 above)
Comment (tgrabiec) [reply utils/contiguous_shared_buffer.hh:19]: share() for page_view is safe, because it returns another page_view. What's unsafe is share() on temporary_buffer which is a view of some snapshot of page_view - that gets invalidated by LSA moves. page_view is not invalidated by moves, it follows to buffer.

That's the approach taken here, to keep share() safe for both, by passing page_view directly to parsers.

**Comment by tgrabiec** [comment]
> Should we change page_view not to return a temporary_buffer, since it violates its contract, but instead std::span<const char>? Or perhaps a wrapper around std::span that makes it similar to temporary_buffer (but no share?)

Yes. It's unused after the series so I can drop it.

File: utils/contiguous_shared_buffer.hh [hunk 4]
```diff
@@ -0,0 +1,32 @@
+#pragma once
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply utils/contiguous_shared_buffer.hh:1]: Yes

File: test/boost/cached_file_test.cc [hunk 5]
```diff
@@ -453,3 +453,50 @@ SEASTAR_THREAD_TEST_CASE(test_invalidation) {
...
     BOOST_REQUIRE_EQUAL(0, metrics.page_hits);
 }
+
+SEASTAR_THREAD_TEST_CASE(test_page_view_as_contiguous_shared_buffer) {
+    auto page_size = cached_file::page_size;
+    test_file tf = make_test_file(page_size);
+
+    cached_file_stats metrics;
+    logalloc::region region;
+    cached_file cf(tf.f, metrics, cf_lru, region, page_size * 2);
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply test/boost/cached_file_test.cc:463]: No, it's a copy-paste error.

**Comment by nyh** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11942/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11942/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/cached_file_test 🔹 boost/index_reader_test ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11942/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/819/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/3877/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/11895/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11942/)
> #### Build Details:
> 
>     * Duration: 7 hr 9 min
> 
>     * Builder: i-020f24fc925befc64 (m5ad.8xlarge)

Looks like https://github.com/scylladb/scylladb/issues/20503

File: utils/cached_file.hh (hunk 3 above)
Comment (tgrabiec) [reply utils/cached_file.hh:254]: Yes.

**Comment by tgrabiec** [comment]
In V2:
  - dropped now unused and unsafe page_view::get_buf() and cached_page::get_buf_weak()
  - added missing copyright to contiguous_shared_buffer.hh
  - Fixed now stale comment reference to temporary_buffer in generic basic_fragmented_buffer
  - Fix misalignment of cached file size in the new cached_file_test test case  
  - Fixed bisectability issue
  - Fixed pointless assignment in index_reader_test.cc
