### PR TITLE
Do not update topology on address change

### LINKED ISSUE #22293: a node cannot restart after crashing while another node was joining
The scenario:
- node A is bootstrapping, the topology is in the `write_both_read_new` state,
- node B crashes,
- node A finishes bootstrapping,
- node B tries to restart but it can't, it keeps crashing on:

```cpp
} else if (_topology_state_machine._topology.tstate == topology::transition_state::write_both_read_new) {
    on_internal_error(rtlogger, format("Bootstrapping node {} does not have IP mapping but the topology is in the write_both_read_new state", id));
}
```

Here is a reproducer:
```python
import asyncio
import logging
import pytest

from test.pylib.manager_client import ManagerClient
logger = logging.getLogger(__name__)


@pytest.mark.asyncio
async def test_reproducer(manager: ManagerClient):
    coordinator = await manager.server_add()
    servers = [coordinator] + await manager.servers_add(2)

    coordinator_log = await manager.server_open_log(coordinator.server_id)
    await manager.api.enable_injection(coordinator.ip_addr, 'delay_node_bootstrap', one_shot=False)

    new_server = await manager.server_add(start=False)
    task = asyncio.create_task(manager.server_start(new_server.server_id))

    await coordinator_log.wait_for("delay_node_bootstrap: waiting for message")

    await manager.server_stop(servers[1].server_id)

    await manager.api.message_injection(coordinator.ip_addr, 'delay_node_bootstrap')

    await task

    # Restarting node 1 will keep crashing.
    await manager.server_start(servers[1].server_id, expected_error='does not have IP mapping')
    await manager.server_start(servers[1].server_id, expected_error='does not have IP mapping')
```

AFAIK, we only test crashes of the topology coordinator and transitioning nodes. We don't test crashes of other normal nodes at all. So, apart from fixing this particular failure, it would be good to investigate or even test other cases (different topology operations, different transition states).

### PR DESCRIPTION
**Pull request by gleb-cloudius**
Since now topology does not contain ip addresses there is no need to
create topology on an ip address change. Only peers table has to be
updated. The series factors out peers table update code from
sync_raft_topology_nodes() and calls it on topology and ip address
updates. As a side effect it fixes #22293 since now topology loading
does not require IP do be present, so the assert that is triggered in
this bug is removed.

Fixes: scylladb/scylladb#22293

### CODE REVIEW

**Comment by gleb-cloudius** [comment]
https://github.com/scylladb/scylladb/issues/15677

File: service/storage_service.cc [hunk 1]
```diff
@@ -596,41 +611,60 @@ future<storage_service::nodes_to_notify_after_sync> storage_service::sync_raft_t
...
+        sys_ks_futures.push_back(raft_topology_update_ip(*target_node, ip, &nodes_to_notify));
     } else {
-        sys_ks_futures.reserve(t.left_nodes.size() + t.normal_nodes.size() + t.transition_nodes.size());
         for (const auto& id: t.left_nodes) {
-            co_await process_left_node(id);
+            locator::host_id host_id{id.uuid()};
+            auto ip = _address_map.find(host_id);
+            co_await process_left_node(id, host_id, ip);
+            if (ip) {
+                sys_ks_futures.push_back(raft_topology_update_ip(host_id, *ip, nullptr));
```
Comment (kbr-scylla) [inline service/storage_service.cc]: Didn't previous version of the code notify in this case?
It would call `process_left_node(id)` which would call `remove_ip(..., true)` (`notify = true`) if IP was found (which in this case, it was)

**Review by kbr-scylla — COMMENTED** [review]
Can you run the dtest `pushed_notifications_test.py` against the current version of this PR?

**Comment by kbr-scylla** [comment]
> Can you run the dtest pushed_notifications_test.py against the current version of this PR?


Nvm, I see it's a gating test

File: service/storage_service.cc (hunk 1 above)
Comment (kbr-scylla) [reply service/storage_service.cc]: Hmm, maybe even if it did, it was a mistake; would we notify about the same set of left nodes every time we refreshed topology?

Or perhaps it would eventually stop once IP is gone. But then I wonder if there was a chance that we never sent any notification.


The correct thing to do would be probably to ensure that exactly once notification is sent, but I dunno if that can be done.

We need better tests for notifications...

Anyway perhaps here it should depend on whether `prev_normal` contained the node, I'm not sure

Comment (gleb-cloudius) [reply service/storage_service.cc]: process_left_node did not change. It still notifies about left node. raft_topology_update_ip only notifies about joining nodes.

Comment (kbr-scylla) [reply service/storage_service.cc]: Ahhh ok. I got confused.
Would be more clear then if it took only joined set pointer, not the structure which contains both joined and left.
But it's a minor thing, not a blocker

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
fixed title

**Comment by kbr-scylla** [comment]
Qd

**Comment by kbr-scylla** [comment]
> [scylla_gdb.run.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14785/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___scylla_gdb_run_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+scylla_gdb.run.release.3)

Looks like https://github.com/scylladb/scylladb/issues/22501
