### PR TITLE
Do not access owned_ranges_ptr across shards in update_sstable_cleanup_state

### LINKED ISSUE #13631: cross-shard access to shared pointer from distributed_loader collect_all_shared_sstables
Seen after f1bbf705f9b6faa406baac04f418a93b09a53c19 in debug mode
`Merge 'Cleanup sstables in resharding and other compaction types' from Benny Halevy`

For example, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/180/artifact/logs-full.debug.011/1681911360731_compaction_additional_test.py%3A%3ATestCompactionAdditional%3A%3Atest_refresh_and_restart_after_compaction_strategy_change%5BLeveledCompactionStrategy-TimeWindowCompactionStrategy%5D/node1.log
```
Scylla version 5.3.0~dev-0.20230419.c501163f955e with build-id 3b61143e107d9a2c9f01e3709c23dfa64e14dfc8 starting ...

INFO  2023-04-19 13:35:48,336 [shard 0] sstables_loader - Loading new SSTables for keyspace=keyspace1, table=standard1, load_and_stream=false, primary_replica_only=false
ERROR 2023-04-19 13:35:58,099 [shard 1] seastar - shared_ptr accessed on non-owner cpu, at: 0xd3a3e50 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x550279c /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x55024f7 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x5504849 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x55052bf /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x44076f0 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x440823e 0xd4e7d05 0xe12b30b 0xe12ad52 0xef89ebd 0xef89c21 0xef899d0 0xef89827 0xef896de 0xef89360 0xdc146cd 0xdc145f0 0xdc1450f 0xdc14374 0xdc140e5 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x463b5c8 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x464369e /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x46476e0 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473c2a7 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473af00 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473adf0 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473a50c /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x44129e8 /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x8b12c /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x10cbbf
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>, seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >&&)#1}, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 1.
Backtrace:
  0xd3a3e50
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x47c702c
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x47c6c83
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x4619999
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x46491d5
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473a119
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473a34e
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473a19a
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x3cb1f
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x8ce5b
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x3ca75
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x267fb
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x4408248
  0xd4e7d05
  0xe12b30b
  0xe12ad52
  0xef89ebd
  0xef89c21
  0xef899d0
  0xef89827
  0xef896de
  0xef89360
  0xdc146cd
  0xdc145f0
  0xdc1450f
  0xdc14374
  0xdc140e5
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x463b5c8
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x464369e
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x46476e0
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473c2a7
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473af00
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473adf0
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x473a50c
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libseastar.so+0x44129e8
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x8b12c
  /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/c501163f955e8f665211fb1456f92fcedf07dd3d/libreloc/libc.so.6+0x10cbbf
```

Decoded:
```
[Backtrace #0]
__interceptor_backtrace.part.0 at ??:?
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:60
seastar::current_backtrace_tasklocal() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:170
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/debug/seastar/./seastar/src/core/on_internal_error.cc:38
seastar::on_fatal_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./seastar/src/core/on_internal_error.cc:67
seastar::debug_shared_ptr_counter_type::check() const at ././seastar/include/seastar/core/shared_ptr_debug_helper.hh:68
 (inlined by) seastar::debug_shared_ptr_counter_type::operator++() at ././seastar/include/seastar/core/shared_ptr_debug_helper.hh:48
operator() at ./replica/distributed_loader.cc:170
seastar::future<void> std::__invoke_impl<seastar::future<void>, replica::collect_all_shared_sstables(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > const>)::$_4::operator()(sstables::sstable_directory&) const::{lambda(seastar::lw_shared_ptr<sstables::sstable>)#1}&, seastar::lw_shared_ptr<sstables::sstable> >(std::__invoke_other, replica::collect_all_shared_sstables(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > const>)::$_4::operator()(sstables::sstable_directory&) const::{lambda(seastar::lw_shared_ptr<sstables::sstable>)#1}&, seastar::lw_shared_ptr<sstables::sstable>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, replica::collect_all_shared_sstables(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > const>)::$_4::operator()(sstables::sstable_directory&) const::{lambda(seastar::lw_shared_ptr<sstables::sstable>)#1}&, seastar::lw_shared_ptr<sstables::sstable> >, std::enable_if>::type std::__invoke_r<seastar::future<void>, replica::collect_all_shared_sstables(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > const>)::$_4::operator()(sstables::sstable_directory&) const::{lambda(seastar::lw_shared_ptr<sstables::sstable>)#1}&, seastar::lw_shared_ptr<sstables::sstable> >(seastar::future<void>&&, (replica::collect_all_shared_sstables(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > const>)::$_4::operator()(sstables::sstable_directory&) const::{lambda(seastar::lw_shared_ptr<sstables::sstable>)#1}&)...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>), replica::collect_all_shared_sstables(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::lw_shared_ptr<std::vector<nonwrapping_interval<dht::token>, std::allocator<nonwrapping_interval<dht::token> > > const>)::$_4::operator()(sstables::sstable_directory&) const::{lambda(seastar::lw_shared_ptr<sstables::sstable>)#1}>::_M_invoke(std::_Any_data const&, seastar::lw_shared_ptr<sstables::sstable>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290
std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>::operator()(seastar::lw_shared_ptr<sstables::sstable>) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591
operator() at ./sstables/sstable_directory.cc:425
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}>(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&) at ././seastar/include/seastar/core/future.hh:1999
 (inlined by) auto seastar::futurize_invoke<sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}>(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&) at ././seastar/include/seastar/core/future.hh:2030
operator()<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > at ././seastar/include/seastar/core/semaphore.hh:717
seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::with_semaphore<seastar::semaphore_default_exception_factory, sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}, std::chrono::_V2::steady_clock>(seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&, unsigned long, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(auto:1)#1}&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}>&&) at ././seastar/include/seastar/core/future.hh:1999
auto seastar::futurize_invoke<seastar::with_semaphore<seastar::semaphore_default_exception_factory, sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}, std::chrono::_V2::steady_clock>(seastar::basic_semaphore<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&, unsigned long, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(auto:1)#1}&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, sstables::sstable_directory::parallel_for_each_restricted<std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)> >(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&&)::{lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1}::operator()(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)::{lambda(auto:1&)#1}::operator()<seastar::lw_shared_ptr<sstables::sstable> >({lambda(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >&, std::function<seastar::future<void> (seastar::lw_shared_ptr<sstables::sstable>)>&)#1})::{lambda()#1}>&&) at ././seastar/include/seastar/core/future.hh:2030
 (inlined by) operator()<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> > at ././seastar/include/seastar/core/future.hh:1403
 (inlined by) _ZN7seastar20noncopyable_functionIFNS_6futureIvEEONS_15semaphore_unitsINS_35semaphore_default_exception_factoryENSt6chrono3_V212steady_clockEEEEE17direct_vtable_forIZNS1_IS8_E4thenIZNS_14with_semaphoreIS4_ZZZN8sstables17sstable_directory28parallel_for_each_restrictedIRSt6vectorINS_13lw_shared_ptrINSG_7sstableEEESaISM_EESt8functionIFS2_SM_EEEES2_OT_OT0_ENUlSP_RSS_E_clESP_SX_ENUlRST_E_clISM_EEDaSZ_EUlvE_S7_EENS_8futurizeINSt13invoke_resultISV_JEE4typeEE4typeERNS_15basic_semaphoreIST_T1_EEmSW_EUlST_E_S2_EESV_SU_EUlDpOT_E_E4callEPKSB_S9_ at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>::operator()(seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&) const at ././seastar/include/seastar/util/noncopyable_function.hh:210
seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >(std::__invoke_other, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
 (inlined by) std::__invoke_result<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >::type std::__invoke<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >(seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:96
 (inlined by) std::invoke_result<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >::type std::invoke<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >(seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/functional:110
 (inlined by) auto seastar::internal::future_invoke<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >(seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&) at ././seastar/include/seastar/core/future.hh:1155
operator() at ././seastar/include/seastar/core/future.hh:1455
 (inlined by) void seastar::futurize<seastar::future<void> >::satisfy_with_result_of<seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&&) at ././seastar/include/seastar/core/future.hh:1984
operator() at ././seastar/include/seastar/core/future.hh:1451
seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>, seastar::future<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock>&&)>&, seastar::future_state<seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >&&)#1}, seastar::semaphore_units<seastar::semaphore_default_exception_factory, std::chrono::_V2::steady_clock> >::run_and_dispose() at ././seastar/include/seastar/core/future.hh:742
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/debug/seastar/./seastar/src/core/reactor.cc:2557
seastar::reactor::run_some_tasks() at ./build/debug/seastar/./seastar/src/core/reactor.cc:3020
seastar::reactor::do_run() at ./build/debug/seastar/./seastar/src/core/reactor.cc:3189
operator() at ./build/debug/seastar/./seastar/src/core/reactor.cc:4393
void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_97&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_97&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_97&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_97&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_97&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:111
std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_97>::_M_invoke(std::_Any_data const&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290
seastar::posix_thread::start_routine(void*) at ./build/debug/seastar/./seastar/src/core/posix.cc:73
/data/scylla-s3-reloc.cache/by-build-id/3b61143e107d9a2c9f01e3709c23dfa64e14dfc8/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=81daba31ee66dbd63efdc4252a872949d874d136, for GNU/Linux 3.2.0, not stripped
```

### PR DESCRIPTION
**Pull request by bhalevy**
This series fixes a few issues caused by f1bbf705f9b6faa406baac04f418a93b09a53c19
(f1bbf705f9b6faa406baac04f418a93b09a53c19):

- table, compaction_manager: prevent cross shard access to owned_ranges_ptr
  - Fixes #13631 
- distributed_loader: distribute_reshard_jobs: pick one of the sstable shard owners
- compaction: make_partition_filter: do not assert shard ownership
  - allow the filtering reader now used during resharding to process tokens owned by other shards

### CODE REVIEW

File: replica/distributed_loader.cc [hunk 1]
```diff
@@ -206,9 +206,15 @@ distribute_reshard_jobs(sstables::sstable_directory::sstable_open_info_vector so
...
-        shard_it->info_vec.push_back(std::move(info));
+        // Choose the stable shard owner with the smallest amount of accumulated work.
+        // Note that for sstables that need cleanup via resharding, owners may contain
+        // a single shard.
+        auto shard_it = boost::min_element(info.owners, [&] (const shard_id& lhs, const shard_id& rhs) {
+            return destinations[lhs].total_size_smaller(destinations[rhs]);
+        });
+        auto& dest = destinations[*shard_it];
+        dest.uncompressed_data_size += info.uncompressed_data_size;
+        dest.info_vec.push_back(std::move(info));
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply replica/distributed_loader.cc:217]: original code considered all shards: `boost::min_element(destinations`
while new code considers only the sstable's shard owners: `boost::min_element(info.owners`

[the remark this answers is not in the document]
Comment (denesb) [reply replica/distributed_loader.cc:217]: Right, I knew I was missing something.

**Review by denesb — APPROVED** [review]

File: replica/table.cc [hunk 2]
```diff
@@ -2825,10 +2825,16 @@ table::as_data_dictionary() const {
...
     auto& cg = compaction_group_for_sstable(sst);
-    return get_compaction_manager().update_sstable_cleanup_state(cg.as_table_state(), sst, std::move(owned_ranges_ptr));
+    return get_compaction_manager().update_sstable_cleanup_state(cg.as_table_state(), sst, sorted_owned_ranges);
+}
+
+bool table::erase_sstable_cleanup_state(const sstables::shared_sstable& sst) {
+    // FIXME: it's possible that the sstable belongs to multiple compaction_groups
+    auto& cg = compaction_group_for_sstable(sst);
+    return get_compaction_manager().erase_sstable_cleanup_state(cg.as_table_state(), sst);
 }
```
Comment (raphaelsc) [inline replica/table.cc:2838]: I'd recommend moving this all to compaction_group. So a sstable has its cleanup state updated on insertion into any of the sstable sets. Likewise, has its state removed on removal from any set. Don't have to be done in this series, but let's keep it in mind.

File: compaction/compaction.cc [hunk 3]
```diff
@@ -625,11 +625,6 @@ class compaction {
 
     flat_mutation_reader_v2::filter make_partition_filter() const {
         return [this] (const dht::decorated_key& dk) {
-#ifdef SEASTAR_DEBUG
-            // sstables should never be shared with other shards at this point.
-            assert(dht::shard_of(*_schema, dk.token()) == this_shard_id());
-#endif
-
```
Comment (raphaelsc) [inline compaction/compaction.cc:632]: How did you spot it? Should have been caught in some of the tests running a debug-mode binary. But I don't think longevity tests do it. Navigating through test dir, I see we miss a table_test, perhaps we can start one with a cleanup test.

**Review by raphaelsc — APPROVED** [review]

File: compaction/compaction.cc (hunk 3 above)
Comment (bhalevy) [reply compaction/compaction.cc:632]: I ran a bunch of relevant dtests in debug mode.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please merge
