### PR TITLE
storage_service::merge_topology_snapshot: handle big mutations

### LINKED ISSUE #17545: Scale test (adding 40 nodes) failed by timeouts(nodes added to long) and errors on teardown: seastar::rpc::remote_verb_error (Mutation of 17696794 bytes is too large for the maximum size of 16777216)
Scylla version 5.5.0~dev-0.20240221.4be70bfc2bc7 with build-id be290d67e3f77a2c2c30c7de606fbca196424c97

Large scale test: [update_cluster_layout_tests.py::TestLargeScaleCluster::test_add_many_nodes_under_load](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/79/artifact/logs-full.release.001/1708686228808_update_cluster_layout_tests.py%3A%3ATestLargeScaleCluster%3A%3Atest_add_many_nodes_under_load) try to add 40 nodes. But looks like it failed by timeout because node25 bootstrapped too long and dtest found on teardown a lot of errors:
```
['ERROR 2024-02-23 10:55:47,702 [shard 0:strm] raft - [ae8ff257-e455-4ebe-913e-45bf24116628] Transferring snapshot to 7dde096b-b9f8-428f-9339-15288e5970ed failed with: seastar::rpc::remote_verb_error (Mutation of 17696794 bytes is too large for the maximum size of 16777216)', 'ERROR 2024-02-23 10:56:06,597 [shard 0:strm] raft - [ae8ff257-e455-4ebe-913e-45bf24116628] Transferring snapshot to 7dde096b-b9f8-428f-9339-15288e5970ed failed with: seastar::rpc::remote_verb_error (Mutation of 17696794 bytes is too large for the maximum size of 16777216)', 'ERROR 2024-02-23 10:53:28,396 [shard 0:strm] raft - [ae8ff257-e455-4ebe-913e-45bf24116628] Transferring snapshot to 7dde096b-b9f8-428f-9339-15288e5970ed failed with: seastar::rpc::remote_verb_error (Mutation of 17696794 bytes is too large for the maximum size of 16777216)'
```

Logs: https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/79/artifact/logs-full.release.001/

### PR DESCRIPTION
**Pull request by gusev-p**
The group0 state machine calls `merge_topology_snapshot` from `transfer_snapshot`. It feeds it with `raft_topology_snapshot` returned from `raft_pull_topology_snapshot`. This snapshot includes the entire `system.cdc_generations_v3` table. It can be huge and break the commitlog `max_record_size` limit.

The `system.cdc_generations_v3` is a single-partition table, so all the data is contained in one mutation object. To fit the commitlog limit we split this mutation into many smaller ones and apply them in separate `database::apply` calls. That means we give up the atomicity guarantee, but we actually don't need it for `system.cdc_generations_v3` and `system.topology_requests`.

This PR fixes the dtest `update_cluster_layout_tests.py::TestLargeScaleCluster::test_add_many_nodes_under_load`

fixes #17545

### CODE REVIEW

**Comment by kbr-scylla** [comment]
> That means we give up the atomicity guarantee, but we actually don't need it for system.cdc_generations_v3 and system.topology_requests.

Should explain why.

I understand why we don't need atomicity for `system.cdc_generations_v3` -- because the data is not used by anything unless pointed to by entry inside `system.topology`. So it's fine to apply `system.cdc_generations_v3` nonatomically, followed by applying `system.topology` atomically.

But what's the argument for `system.topology_requests`?

**Review by denesb — APPROVED** [review]
LGTM (I mostly reviewed the mutation splitting part). 2 minor comments only.

File: service/storage_service.cc [hunk 1]
```diff
@@ -698,28 +699,123 @@ future<> storage_service::topology_transition() {
     _topology_state_machine.event.broadcast();
 }
 
+namespace {
+    future<> split_mutation(mutation source, std::vector<mutation>& target, size_t max_size) {
```
[the remark this answers is not in the document]
Comment (gusev-p) [reply service/storage_service.cc:703]: > Why not return `future<std::vector<mutation>>` instead of output param?

It's more 'dependency inject-y'/'composable'  - e.g. we can send output mutations from several `split_mutation` calls into the same output vector, like we do here.

[the remark this answers is not in the document]
Comment (gusev-p) [reply service/storage_service.cc:703]: > Also, maybe this is worth putting somewhere accessible, so other code can use it if needed.

I would be glad to, but I haven’t found a suitable place. Separate `.hh/.cc`?

[the remark this answers is not in the document]
Comment (gusev-p) [reply service/storage_service.cc:703]: I'll put it into `mutation.hh/.cc`.

[the remark this answers is not in the document]
Comment (avikivity) [reply service/storage_service.cc:703]: I guess the best way would be to co_yield the mutations. This way it's clear it's an output parameter.

**Comment by gusev-p** [comment]
> Should explain why in commit messages.
> 
> I understand why we don't need atomicity for `system.cdc_generations_v3` -- because the data is not used by anything unless pointed to by entry inside `system.topology`. So it's fine to apply `system.cdc_generations_v3` nonatomically, followed by applying `system.topology` atomically.
> 
> But what's the argument for `system.topology_requests`?

I actually don't know/don't care. The original problem was with `system.cdc_generations_v3`, so I reverted the `system.topology_requests` part + added the arguments for `system.cdc_generations_v3`  to the commit message. The `system.topology_requests` shouldn't be big, as we see in [this log](https://github.com/scylladb/scylladb/issues/17545#issuecomment-1973414121).

File: service/storage_service.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply service/storage_service.cc:703]: e.g. seastar::experimental::generator

[the remark this answers is not in the document]
Comment (gusev-p) [reply service/storage_service.cc]: seems too fancy

**Comment by gusev-p** [comment]
new version:
  * extracted `split_mutation` into `mutation.hh/mutation.cc`;
  * reverted the `system.topology_requests` part, we only care about `system.cdc_generations_v3`;
  * improved the commit message.

[the changes](https://github.com/scylladb/scylladb/compare/d31eee9351bbfc6ad4e7346805ea313101e7ad67..b062da75f97b7d7108d882bc367a8a71fd00de53).

**Comment by avikivity** [comment]
There's no test for split_mutation.

Also, doesn't flat_mutation_reader do essentially the same?

**Comment by avikivity** [comment]
Is there a safety issue? If we crash, only part of the mutation will be replayed.

Maybe we need the ability for commitlog to commit partial records, rather than hack around it in upper layers.

**Comment by gusev-p** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7146/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7146/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7146/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/285/)
> 
> #### Build Details:
> * Duration: 4 hr 30 min
> * Builder: spider8.cloudius-systems.com

@yaronkaikov Why all the checks are green, but the CI still failed?

**Comment by gusev-p** [comment]
> There's no test for split_mutation.

What exactly are you proposing to test here? There is no inner complexity in this function, it's just wiring existing components together, the efficiency ratio of a unit test would be low. The `test_cdc_generation_data.py` adjusted in this PR checks the function generally works.

> Also, doesn't flat_mutation_reader do essentially the same?

I don't understand this.

> Is there a safety issue? If we crash, only part of the mutation will be replayed.

This is mentioned in the commit message:
> That means we give up the atomicity guarantee, but we
> actually don't need it for system.cdc_generations_v3.
> The cdc_generations_v3 data is not used in any way until
> it's referenced from the topology table. By applying the
> cdc_generations_v3 mutations before topology mutations
> we ensure that the lack of atomicity isn't a problem here.

The data in `cdc_generations_v3` is not used until it's referenced from `topology`. For them to be referenced from `topology` we need to successfully apply `topology` mutations, and we make applying `cdc_generations_v3` mutations a prerequisite for that by applying them before `topology` mutations.

> Maybe we need the ability for commitlog to commit partial records, rather than hack around it in upper layers.

This sounds like a big effort, we strive to stay focused on fixing issues for 6.0.

**Comment by denesb** [comment]
> * why not solve it closer to source? E.g. somewhere around system_keyspace::query_mutations where those huge mutations are generated. assuming that commitlog max mutations size will be typically the same across nodes (don't know if it's valid assumption - if not perhaps some cluster minimum could be maintained by raft)

I don't think `system_keyspace::query_mutations()` should make assumptions about what the mutations will be used for.

**Comment by kbr-scylla** [comment]
> why the problem is limited to cdc_generations_v3 ? To me looks like potentially it can happen with everything which is passed via raft.

It can happen whenever you apply a mutation in any context

> is the problem limited to snapshot code only?

no, for example with cdc_generations, the topology coordinator code that creates and writes the generation mutations for the first time takes care to split them into multiple commands if necessary (see `prepare_and_broadcast_cdc_generation_data` in topology_coordinator.cc). The snapshot code needed to be adjusted as well which this PR does.

**Comment by nuivall** [comment]
> > * why not solve it closer to source? E.g. somewhere around system_keyspace::query_mutations where those huge mutations are generated. assuming that commitlog max mutations size will be typically the same across nodes (don't know if it's valid assumption - if not perhaps some cluster minimum could be maintained by raft)
> 
> I don't think `system_keyspace::query_mutations()` should make assumptions about what the mutations will be used for.

It doesn't need to assume this implicitly but can have an option with max_size.

**Comment by avikivity** [comment]
> > There's no test for split_mutation.
> 
> What exactly are you proposing to test here? There is no inner complexity in this function, it's just wiring existing components together, the efficiency ratio of a unit test would be low. The `test_cdc_generation_data.py` adjusted in this PR checks the function generally works.
> 
> > Also, doesn't flat_mutation_reader do essentially the same?
> 
> I don't understand this.

make_flat_mutation_reader_from_mutations() is basically a splitter.


> 
> > Is there a safety issue? If we crash, only part of the mutation will be replayed.
> 
> This is mentioned in the commit message:
> 
> > That means we give up the atomicity guarantee, but we
> > actually don't need it for system.cdc_generations_v3.
> > The cdc_generations_v3 data is not used in any way until
> > it's referenced from the topology table. By applying the
> > cdc_generations_v3 mutations before topology mutations
> > we ensure that the lack of atomicity isn't a problem here.
> 
> The data in `cdc_generations_v3` is not used until it's referenced from `topology`. For them to be referenced from `topology` we need to successfully apply `topology` mutations, and we make applying `cdc_generations_v3` mutations a prerequisite for that by applying them before `topology` mutations.
> 
> > Maybe we need the ability for commitlog to commit partial records, rather than hack around it in upper layers.
> 
> This sounds like a big effort, we strive to stay focused on fixing issues for 6.0.

It's too ad hoc. We sacrifice good engineering principles in the name of rushing out a release, then never fix it up.

File: mutation/mutation.cc [hunk 2]
```diff
@@ -194,6 +196,71 @@ mutation reverse(mutation mut) {
...
 
+future<> split_mutation(mutation source, std::vector<mutation>& target, size_t max_size) {
+    class splitter {
+        const schema_ptr _schema;
+        std::vector<mutation>& _target;
+        std::optional<mutation_rebuilder_v2> _mut_builder;
+        size_t _size = 0;
+        const size_t _max_size;
+        void maybe_flush() {
+            if (_size >= _max_size) {
```
Comment (kbr-scylla) [inline mutation/mutation.cc:207]: Shouldn't we reset _size back to 0 after flushing?
I think this will cause us to start flushing after every row once we exceed _max_size for the first time.

**Comment by kbr-scylla** [comment]
> There is no inner complexity in this function, it's just wiring existing components together, the efficiency ratio of a unit test would be low.

Hard disagree. The code is not trivial and I need to think to understand it. Tests would be valuable.

File: mutation/mutation.cc [hunk 3]
```diff
@@ -194,6 +196,71 @@ mutation reverse(mutation mut) {
...
+        stop_iteration consume(static_row&& sr) {
+            _size += sr.memory_usage(*_schema);
+            _mut_builder->consume(std::move(sr));
+            maybe_flush();
+            return stop_iteration::no;
+        }
+        stop_iteration consume(clustering_row&& cr) {
+            _size += cr.memory_usage(*_schema);
+            _mut_builder->consume(std::move(cr));
+            maybe_flush();
```
Comment (kbr-scylla) [inline mutation/mutation.cc:234]: So we can open a partition, then flush, then consume partition end? How does that work?

File: service/storage_service.cc [hunk 4]
```diff
@@ -699,27 +699,58 @@ future<> storage_service::topology_transition() {
...
+        // The cdc_generations_v3 data is not used in any way until
+        // it's referenced from the topology table.
+        // By applying the cdc_generations_v3 mutations before topology mutations
+        // we ensure that the lack of atomicity isn't a problem here.
+        std::vector<future<>> futures;
+        futures.reserve(frozen_muts_to_apply.size());
+        for (const auto& m: frozen_muts_to_apply) {
+            futures.push_back(_db.local().apply(s, m, {}, db::commitlog::force_sync::no, db::no_timeout));
+        }
+        co_await when_all_succeed(futures.begin(), futures.end()).discard_result();
```
Comment (kbr-scylla) [inline service/storage_service.cc:732]: Aren't you reimplementing `parallel_for_each`?
(Also perhaps we should limit concurrency with `max_concurrent_for_each`)

File: service/storage_service.cc [hunk 5]
```diff
@@ -6179,6 +6179,24 @@ void storage_service::init_messaging_service(bool raft_topology_change_enabled)
                             rs->partitions(), std::back_inserter(cdc_generation_mutations), [s] (const partition& p) {
                         return canonical_mutation{p.mut().unfreeze(s)};
                     });
+
+                    // Copy mutations n times, where n is picked so that the memory size of all mutations
```
Comment (kbr-scylla) [inline service/storage_service.cc:6183]: I'd put the comment inside the injection so it's more clear when reading top-to-bottom that this is error injection specific logic.

**Review by kbr-scylla — CHANGES_REQUESTED** [review]

File: mutation/mutation.cc [hunk 6]
```diff
@@ -194,6 +196,71 @@ mutation reverse(mutation mut) {
     return *std::move(mut).consume(reverse_rebuilder, consume_in_reverse::yes).result;
 }
 
+future<> split_mutation(mutation source, std::vector<mutation>& target, size_t max_size) {
```
[the remark this answers is not in the document]
Comment (avikivity) [reply mutation/mutation.cc:199]: I'm sure we have >1 equivalents of split_mutation elsewhere.

**Comment by gusev-p** [comment]
> > I don't think that `query_mutations` is actually 'closer to the source', the problem now is with commitlog `max_entry_size`, and not all mutations from `query_mutations` are going to be submitted to the commitlog.
> 
> see [#17632 (comment)](https://github.com/scylladb/scylladb/pull/17632#issuecomment-1980541154)

I still don't see why `query_mutations` should care about the size of mutations it produces and how it's better than a separate method.

**Comment by nuivall** [comment]
> > > I don't think that `query_mutations` is actually 'closer to the source', the problem now is with commitlog `max_entry_size`, and not all mutations from `query_mutations` are going to be submitted to the commitlog.
> > 
> > 
> > see [#17632 (comment)](https://github.com/scylladb/scylladb/pull/17632#issuecomment-1980541154)
> 
> I still don't see why `query_mutations` should care about the size of mutations it produces and how it's better than a separate method.

I'm just trying to find some solution which would be a) relatively easy to implement b) would help fix other cases too.

Currently you modify only CDC.

(Also maybe it could spare some in memory copying).

As for a more theoretical reasoning: why first create too big mutations and then "fix" them later rather than request the right size at the beginning.

**Comment by avikivity** [comment]
I'm sure we'll have the same problem with system.tablets in large clusters. We need a systematic fix.

**Comment by denesb** [comment]
> As for a more theoretical reasoning: why first create too big mutations and then "fix" them later rather than request the right size at the beginning.

A generic producer of data like `query_mutations()` should not adapt to the particularities of any single end consumer. If we go down this route, producers like this start to accumulate all sorts of flags to tweak the output to the taste of different consumers. A much cleaner route is to add transforming stages to the pipeline, as Petr did in this PR. Or fix the end consumer (commitlog) to not be so picky (accept bigger mutations). This is a much better, generic solution, but it is more work.

File: mutation/mutation.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (gusev-p) [reply mutation/mutation.cc:199]: > I'm sure we have >1 equivalents of split_mutation elsewhere.

I couldn't find one with the required semantics (split by size of mutation in bytes). I asked @denesb and he proposed to create a new function.

**Comment by gusev-p** [comment]
> make_flat_mutation_reader_from_mutations() is basically a splitter.

It produces `mutation_fragment`-s. The new function adds a bytes limit to it, and it reconstructs output mutations, since we need mutation-in-mutations-out interface.

**Comment by gusev-p** [comment]
new version:
  * added test `random_mutation_generator`-based test for `split_mutation`;
  * use `max_concurrent_for_each`;
  * some small fixes in `split_mutation`.

@kbr-scylla

File: mutation/mutation.cc (hunk 3 above)
Comment (kbr-scylla) [reply mutation/mutation.cc]: Yeah I know -- but how does that address my question?

In fact good that you referenced the `flush()` definition, which has a comment above it:
```cpp
    // Might only be called between consume_new_partition()
    // and consume_end_of_partition().
```
so my suspicions appear to be valid. The code IIUC is `flush()`ing in the middle of a partition, which is incorrect.

Comment (kbr-scylla) [reply mutation/mutation.cc]: @denesb maybe we should have checks in debug mode that verify such preconditions in `mutation_rebuilder{_v2}`

Comment (gusev-p) [reply mutation/mutation.cc]: I don't know what you are talking about. We _are_ between `consume_new_partition` and `consume_end_of_partition`.

Comment (kbr-scylla) [reply mutation/mutation.cc]: Ok (－‸ლ) I misunderstood the code and the comment. Indeed it makes sense that we flush in the middle of a partition and not in between partitions, that's the whole point

File: mutation/mutation.cc [hunk 7]
```diff
@@ -194,6 +196,89 @@ mutation reverse(mutation mut) {
...
+    std::optional<partition_state> _state;
+    template <typename T>
+    stop_iteration consume_fragment(T&& fragment) {
+        const auto fragment_size = fragment.memory_usage(*_schema);
+        if (_state->size && _state->size + _state->empty_partition_size + fragment_size > _max_size) {
+            _target.emplace_back(_state->builder.flush());
+            // We could end up with an empty mutation if we consumed a range_tombstone_change
+            // and the next fragment exceeds the limit. The tombstone range may not have been
+            // closed yet and range_tombstone will not be created.
+            // This should be a rare case though, so just pop such mutation.
```
Comment (kbr-scylla) [inline mutation/mutation.cc:222]: What happens when we flush mutation in between range tombstone changes?

Won't we incorrectly "forget" the range tombstone i.e. it won't end up in any of the mutations we produce?

File: mutation/mutation.cc [hunk 8]
```diff
@@ -194,6 +196,89 @@ mutation reverse(mutation mut) {
...
+    }
+    stop_iteration consume(clustering_row&& cr) {
+        return consume_fragment(std::move(cr));
+    }
+    stop_iteration consume(range_tombstone_change&& rtc) {
+        return consume_fragment(std::move(rtc));
+    }
+    stop_iteration consume_end_of_partition() {
+        _state->builder.consume_end_of_partition();
+        if (auto mut_opt = _state->builder.consume_end_of_stream()) {
```
Comment (kbr-scylla) [inline mutation/mutation.cc:257]: Could we assert that `mut_opt` is always engaged? Since we just consumed end of partition --- logically a mutation should be present.

File: service/storage_service.cc [hunk 9]
```diff
@@ -721,27 +721,55 @@ future<> storage_service::topology_transition() {
...
+            frozen_muts_to_apply = freeze(muts_to_apply);
+        }
+
+        // Apply non-atomically so as not to hit the commitlog size limit.
+        // The cdc_generations_v3 data is not used in any way until
+        // it's referenced from the topology table.
+        // By applying the cdc_generations_v3 mutations before topology mutations
+        // we ensure that the lack of atomicity isn't a problem here.
+        co_await max_concurrent_for_each(frozen_muts_to_apply, 128, [&] (const frozen_mutation& m) -> future<> {
+            return _db.local().apply(s, m, {}, db::commitlog::force_sync::no, db::no_timeout);
```
Comment (kbr-scylla) [inline service/storage_service.cc:750]: Although it probably doesn't matter what `force_sync` you pass here (since the table uses schema commitlog), but using `force_sync::no` is confusing. (And we do need to sync.)

Comment (gusev-p) [reply service/storage_service.cc]: done

File: mutation/mutation.cc (hunk 8 above)
Comment (gusev-p) [reply mutation/mutation.cc]: done

**Comment by gusev-p** [comment]
new version:
  * use `force_sync::yes`;
  * add assert in `consume_end_of_partition`;

File: mutation/mutation.cc [hunk 10]
```diff
@@ -194,6 +196,89 @@ mutation reverse(mutation mut) {
...
+    stop_iteration consume(clustering_row&& cr) {
+        return consume_fragment(std::move(cr));
+    }
+    stop_iteration consume(range_tombstone_change&& rtc) {
+        return consume_fragment(std::move(rtc));
+    }
+    stop_iteration consume_end_of_partition() {
+        _state->builder.consume_end_of_partition();
+        auto mut_opt = _state->builder.consume_end_of_stream();
+        assert(mut_opt);
```
Comment (denesb) [inline mutation/mutation.cc:258]: Please avoid using asserts, they can bring down entire clusters. Use `on_internal_error()` instead.

**Review by denesb — APPROVED** [review]
Still LGTM, one assert to be exorcised.

File: mutation/mutation.cc (hunk 10 above)
Comment (gusev-p) [reply mutation/mutation.cc:258]: > they can bring down entire clusters

can you elaborate?

Comment (denesb) [reply mutation/mutation.cc:258]: We compile `assert()` into release builds and an `assert()` triggering will cause ScyllaDB to crash.
It is bad enough if this happens on a single node, but there has been cases where multiple nodes or entire clusters were brought down by `asserts()` triggering.
So asserts should be avoided as much as possible, and always prefer to use `on_internal_error()` instead.
Use `assert()` only to check invariants, the violation of which is unrecoverable and the node is not able to continue working correctly.

Comment (kbr-scylla) [reply mutation/mutation.cc:258]: but in this case there are corresponding `assert`s inside `builder`, and we can quickly infer that if those assertions pass then this assertion has to pass too.
(Need to double-check)

Comment (kbr-scylla) [reply mutation/mutation.cc:258]: Double checked, actually there's no such assert. (We're using `mutation_rebuilder_v2`, not `mutation_rebuilder` which has it)

The logic is correct I think, we only call `end_of_partition()` when we have an opened partition.

But I agree  `on_internal_error` would be better.

**Review by kbr-scylla — APPROVED** [review]
