### PR TITLE
truncate: don't fail on already waiting truncate for the same table

### LINKED ISSUE #22166: Truncate table operation failed with `code=1003 [Error during truncate] message="Error during truncate: exceptions::invalid_request_exception (Another global topology request is ongoing, please retry.` error
## Packages

Base Scylla version: `6.2.2-20241128.c6ef055e9c3b` with build-id `d4c2d158132fbb16ba24f21c443cbfb9f67401ea`
Target Scylla version (or git commit hash): `6.3.0~dev-20241226.3e22998dc131` with build-id `6e1de4e4527d9c6c1ab68f21d0cca6a8022cae06`

Kernel Version: `6.8.0-1019-aws`

## Issue description

- [] This issue is a regression.
- [X] It is unknown if this issue is a regression.
Issue might be a regression as it reproduced for the 1st time on weekly rolling upgrade test runs (on 2024-12-28), in the `rolling-upgrade-ami-arm-test` and `rolling-upgrade-ami-test` tests.

The test performs the following rolling upgrade sequence for the cluster of 4 nodes:
upgrade 1st node > upgrade 2nd node > rollback 2nd node > repair 1st node > upgrade the rolled back and remaining node (i.e. nodes 2 to 4)

Before the upgrade sequence, and after the upgrade/rollback of each node the test executes `fill_and_verify_db_data` routine to verify the test data.
After upgrade of the last node in the cluster the routine failed on executing truncate query.

The upgrade of the last node (node-2) ended at 08:18:58:
```
< t:2024-12-28 08:18:58,713 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-12-28 08:18:58.711: (InfoEvent Severity.NORMAL) period_type=not-set event_id=92ce0c39-e68c-49b6-a141-83d196b970cc: message=Upgrade Node rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2 ended
```

Truncate query was issued at 08:19:16:
```
< t:2024-12-28 08:19:16,072 f:common.py       l:1325 c:utils                p:DEBUG > Executing CQL 'TRUNCATE ks_no_range_ghost_test.users' ...
```

It failed at 08:20:16 with the error:
```
< t:2024-12-28 08:20:16,076 f:libevreactor.py l:371  c:cassandra.cluster    p:WARNING > Host 10.4.1.86:9042 error: Error during truncate.
< t:2024-12-28 08:20:16,079 f:libevreactor.py l:371  c:cassandra.cluster    p:WARNING > Host 10.4.2.124:9042 error: Error during truncate.
< t:2024-12-28 08:20:16,080 f:libevreactor.py l:371  c:cassandra.cluster    p:WARNING > Host 10.4.2.89:9042 error: Error during truncate.
< t:2024-12-28 08:20:16,081 f:libevreactor.py l:371  c:cassandra.cluster    p:WARNING > Host 10.4.3.111:9042 error: Error during truncate.
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > TRUNCATE ks_no_range_ghost_test.users < t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > TRUNCATE ks_no_range_ghost_test.users
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3268, in _run_db_queries
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     res = session.execute(item['queries'][i])
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1318, in execute_verbose
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     return execute_orig(*args, **kwargs)
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
< t:2024-12-28 08:20:16,082 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 10.4.1.86:9042 eu-west>: <Error from server: code=1003 [Error during truncate] message="Error during truncate: std::runtime_error (Timeout during TRUNCATE TABLE of ks_no_range_ghost_test.users)">, <Host: 10.4.2.124:9042 eu-west>: <Error from server: code=1003 [Error during truncate] message="Error during truncate: exceptions::invalid_request_exception (Another global topology request is ongoing, please retry.)">, <Host: 10.4.2.89:9042 eu-west>: <Error from server: code=1003 [Error during truncate] message="Error during truncate: exceptions::invalid_request_exception (Another global topology request is ongoing, please retry.)">, <Host: 10.4.3.111:9042 eu-west>: <Error from server: code=1003 [Error during truncate] message="Error during truncate: exceptions::invalid_request_exception (Another global topology request is ongoing, please retry.)">})
```

But even though the server error was returned, the truncate itself was reported as executed in system logs of all nodes:
```
❯ egrep -A2 '08:20.*Truncating ks_no_range_ghost_test.users' -ir db-cluster-c6a139d7/*/system.log
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1/system.log:Dec 28 08:20:34.404066 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1 scylla[19657]:  [shard 0:stmt] database - Truncating ks_no_range_ghost_test.users with auto-snapshot
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1/system.log-Dec 28 08:20:34.427357 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1 scylla[19657]:  [shard 6:comp] compaction - [Compact system.truncated 9c3fdcb0-c4f4-11ef-849e-4782acec28cd] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n6a_2ht0w20lppwlwtl80d-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n10_1zsvl20lppwlwtl80d-big-Data.db:level=0:origin=compaction]
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1/system.log-Dec 28 08:20:34.428070 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1 scylla[19657]:  [shard 0:stmt] database - Truncated ks_no_range_ghost_test.users
--
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2/system.log:Dec 28 08:20:34.405255 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2 scylla[19618]:  [shard 0:stmt] database - Truncating ks_no_range_ghost_test.users with auto-snapshot
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2/system.log-Dec 28 08:20:34.443096 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2 scylla[19618]:  [shard 6:comp] compaction - [Compact system.truncated 9c424db0-c4f4-11ef-b252-f1c08ac06ad9] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n6a_2klc02pmiaigxfiqqh-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n36_08scw2pmiaigxfiqqh-big-Data.db:level=0:origin=compaction]
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2/system.log-Dec 28 08:20:34.445701 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2 scylla[19618]:  [shard 0:stmt] database - Truncated ks_no_range_ghost_test.users
--
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3/system.log:Dec 28 08:20:34.403606 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3 scylla[17657]:  [shard 0:stmt] database - Truncating ks_no_range_ghost_test.users with auto-snapshot
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3/system.log-Dec 28 08:20:34.420099 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3 scylla[17657]:  [shard 6:comp] compaction - [Compact system.truncated 9c3ea430-c4f4-11ef-ba87-8b3e2e90c584] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n6a_2gb0g2u484w6qr2gzo-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n10_27y342u484w6qr2gzo-big-Data.db:level=0:origin=compaction]
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3/system.log-Dec 28 08:20:34.420387 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3 scylla[17657]:  [shard 0:stmt] database - Truncated ks_no_range_ghost_test.users
--
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4/system.log:Dec 28 08:20:34.404546 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4 scylla[24350]:  [shard 0:stmt] database - Truncating ks_no_range_ghost_test.users with auto-snapshot
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4/system.log-Dec 28 08:20:34.430042 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4 scylla[24350]:  [shard 6:comp] compaction - [Compact system.truncated 9c402ad0-c4f4-11ef-9b89-7f817b95d7cb] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n6a_2ig682d5et0wt2wbez-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3gmg_0n10_22dgw2d5et0wt2wbez-big-Data.db:level=0:origin=compaction]
db-cluster-c6a139d7/rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4/system.log-Dec 28 08:20:34.433196 rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4 scylla[24350]:  [shard 0:stmt] database - Truncated ks_no_range_ghost_test.users
```

## Impact

User gets server error about failed truncate table operation, yet on the servers the operation seems to be eventually executed.

## How frequently does it reproduce?

The issue reproduced in 2 tests for the 1st time in weekly runs, but one of the tests ([rolling-upgrade-ami-test](https://argus.scylladb.com/tests/scylla-cluster-tests/c6a139d7-d1f0-451a-a127-494a181856e0)) was re-executed and failed with the same error again.

## Installation details

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-c6a139d7-4 (34.253.210.174 | 10.4.2.124) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-c6a139d7-3 (34.253.170.35 | 10.4.3.111) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-c6a139d7-2 (3.252.234.131 | 10.4.1.86) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-c6a139d7-1 (34.245.191.157 | 10.4.2.89) (shards: 7)

OS / Image: `ami-04541afe5ffea0038` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `c6a139d7-d1f0-451a-a127-494a181856e0`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test method: `upgrade_test.UpgradeTest.test_rolling_upgrade`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f8670793e5a5e0b8dff7252b3d2147a4ecc7e1f7/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c6a139d7-d1f0-451a-a127-494a181856e0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c6a139d7-d1f0-451a-a127-494a181856e0)
- Show all stored logs command: `$ hydra investigate show-logs c6a139d7-d1f0-451a-a127-494a181856e0`

## Logs:
- **db-cluster-c6a139d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/db-cluster-c6a139d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/db-cluster-c6a139d7.tar.gz)
- **sct-runner-events-c6a139d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/sct-runner-events-c6a139d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/sct-runner-events-c6a139d7.tar.gz)
- **sct-c6a139d7.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/sct-c6a139d7.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/sct-c6a139d7.log.tar.gz)
- **loader-set-c6a139d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/loader-set-c6a139d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/loader-set-c6a139d7.tar.gz)
- **monitor-set-c6a139d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/monitor-set-c6a139d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/monitor-set-c6a139d7.tar.gz)
- **ssl-conf-c6a139d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/ssl-conf-c6a139d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c6a139d7-d1f0-451a-a127-494a181856e0/20241228_082156/ssl-conf-c6a139d7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/257/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=c6a139d7-d1f0-451a-a127-494a181856e0)
</details>

### PR DESCRIPTION
**Pull request by nodep**
Currently, we can not have more than one global topology operation at the same time. This means that we can not have concurrent truncate operations because truncate is implemented as a global topology operation.
    
Truncate excludes with other topology operations, and has to wait for those to complete before truncate starts executing. This can lead to truncate timeouts. In these cases the client retries the truncate operation, which will check for ongoing global topology operations, and will fail with
an "Another global topology request is ongoing, please retry." error.
    
This can be avoided by truncate checking if the ongoing global topology operation is a truncate running for the same table who's truncate has just been requested again. In this case, we can wait for the ongoing truncate to complete instead of immediately failing the operation, and
provide a better user experience.

This is an improvement, backport is not needed.

Closes #22166

### CODE REVIEW

**Comment by nodep** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14542/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14542/) **The following new/updated tests ran 100 times for each mode:** 🔹 topology_custom/test_truncate_with_tablets ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5979/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13989/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2861/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14542/)
> 
> #### Build Details:
> * Duration: 12 hr
> * Builder: i-0cb7e2bf508828e04 (m5ad.8xlarge)

#22243

File: service/storage_proxy.cc [hunk 1]
```diff
@@ -1096,14 +1096,28 @@ class storage_proxy::remote {
...
+                // and the client retried by issuing the same truncate again. In this case, instead of failing the request with
+                // an "Another global topology request is ongoing" error, we can wait for the already running request to complete.
+                if (*global_request == global_topology_request::truncate_table) {
+                    const utils::UUID& ongoing_global_request_id = *_topology_state_machine._topology.global_request_id;
+                    const auto topology_requests_entry = co_await _sys_ks.local().get_topology_request_entry(ongoing_global_request_id, true);
+                    if (topology_requests_entry.truncate_table_id == table_id) {
+                        global_request_id = ongoing_global_request_id;
+                        slogger.info("Ongoing TRUNCATE for table {}.{} (global request ID {}) detected; waiting for it to complete",
+                                            ks_name, cf_name, global_request_id);
+                        break;
```
Comment (tgrabiec) [inline service/storage_proxy.cc:1114]: This join is not really correct because truncate could be expected to drop writes which completed before truncate statement was executed. If you join with earlier truncate, writes which completed after earlier truncate started may not be dropped.

File: service/storage_proxy.cc [hunk 2]
```diff
@@ -1113,7 +1114,10 @@ class storage_proxy::remote {
                         break;
                     }
                 }
-                throw exceptions::invalid_request_exception("Another global topology request is ongoing, please retry.");
+                slogger.warn("Another global topology request ({}) is ongoing during attempt to TRUNCATE table {}.{}, please retry.",
+                                *global_request, ks_name, cf_name);
```
Comment (tgrabiec) [inline service/storage_proxy.cc:1118]: nit: "please retry" is fine when propagating failure to the client, but in the log it looks awkward since the log is not communicating with the user, it communicates what happened.

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: service/storage_proxy.cc [hunk 3]
```diff
@@ -456,17 +461,27 @@ class storage_proxy::remote {
...
-        _truncate_table_fiber = request_truncate_with_tablets(ks_name, cf_name).then_wrapped([sem] (auto f) {
+        truncate_fiber tf = request_truncate_with_tablets(ks_name, cf_name).then_wrapped([sem] (auto f) {
             if (f.failed()) {
                 sem->broken(f.get_exception());
             } else {
                 sem->signal(1);
             }
         });
+        truncate_fibers::iterator available_fiber { get_available_fiber() };
+        *available_fiber = std::move(tf);
```
[the remark this answers is not in the document]
Comment (nodep) [reply service/storage_proxy.cc:483]: Yes, you are right. I wanted to wait for truncates to complete and came up with the list, not realizing the gate approach is better. I will change that in the next version.

File: service/storage_proxy.cc (hunk 1 above)
Comment (nodep) [reply service/storage_proxy.cc:1114]: Yes, I see your point.
Maybe a workaround could be to only join an ongoing truncate if it is waiting and hasn't yet started executing (sending truncate RPCs).

Comment (tgrabiec) [reply service/storage_proxy.cc:1114]: Yes, we can only join with truncate which is still waiting in the queue and topology state machine hasn't picked it up yet as active transition.

Comment (nodep) [reply service/storage_proxy.cc:1114]: Do you think checking if `_topology_state_machine._topology.tstate` is empty is an acceptable way to check if truncate is already running? If not, what other way can you suggest?

Comment (tgrabiec) [reply service/storage_proxy.cc:1114]: It would be nice if we had `system.topology#active_request_id`, which is the request from `system.topology_requests` which is currently owning the state machine. 

I can see that `tstate` is indeed empty when truncate request is executing, which is a bug because `is_busy()` will return false even though the state machine is busy handling the global request. We should set a transition state before making any actions.

Comment (tgrabiec) [reply service/storage_proxy.cc:1114]: Also, on failover, the coordinator may choose a different action than the previously executing global request unless you set tstate.

Comment (tgrabiec) [reply service/storage_proxy.cc:1114]: If we set tstate for truncate, then we can check if the tstate is set to truncate transition.

Comment (gleb-cloudius) [reply service/storage_proxy.cc:1114]: > It would be nice if we had `system.topology#active_request_id`, which is the request from `system.topology_requests` which is currently owning the state machine.
> 
> I can see that `tstate` is indeed empty when truncate request is executing, which is a bug because `is_busy()` will return false even though the state machine is busy handling the global request. We should set a transition state before making any actions.

We should drop any use of `is_busy()` . Everything should go through the coordinator as a topology request.

We also need to implement a queue of global requests and having `system.topology#active_request_id` sound like a good idea too.

File: service/storage_proxy.cc (hunk 3 above)
[the remark this answers is not in the document]
Comment (nodep) [reply service/storage_proxy.cc]: I have implemented this with gates.

File: service/storage_proxy.cc (hunk 1 above)
Comment (nodep) [reply service/storage_proxy.cc]: #22452 has been merged, and I have implemented this on top of that change.

File: service/storage_proxy.cc (hunk 2 above)
Comment (nodep) [reply service/storage_proxy.cc:1110]: I've changed the comment on this message.

**Comment by nodep** [comment]
I have two failed checks on this PR and I don't understand why.

@tchaikov
The check fails on "License Header Check / Check License Headers" which, as far as I can tell checks for the existence of the `LicenseRef-ScyllaDB-Source-Available-1.0` string in the first 10 lines of new files. There are no news files in this PR, and both modified files contain the licence reference string. Maybe the checker got confused with the fact that `storage_proxy.cc` has this:
```
/*
 * SPDX-License-Identifier: (LicenseRef-ScyllaDB-Source-Available-1.0 and Apache-2.0)
 */
```
instead of just:
```
/*
 * SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0
 */
```

@yaronkaikov 
`PR Ready for Review on Label Removal / mark-ready` also fails. I think this check should only work on backport PRs, which this is not. Can you please, help?

Thank you both!

**Comment by yaronkaikov** [comment]
> I have two failed checks on this PR and I don't understand why.
> 
> @tchaikov The check fails on "License Header Check / Check License Headers" which, as far as I can tell checks for the existence of the `LicenseRef-ScyllaDB-Source-Available-1.0` string in the first 10 lines of new files. There are no news files in this PR, and both modified files contain the licence reference string. Maybe the checker got confused with the fact that `storage_proxy.cc` has this:
> 
> ```
> /*
>  * SPDX-License-Identifier: (LicenseRef-ScyllaDB-Source-Available-1.0 and Apache-2.0)
>  */
> ```
> 
> instead of just:
> 
> ```
> /*
>  * SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0
>  */
> ```
> 
> @yaronkaikov `PR Ready for Review on Label Removal / mark-ready` also fails. I think this check should only work on backport PRs, which this is not. Can you please, help?
> 

@nodep you need to rebase your branch since this fix is already in master
> Thank you both!

**Comment by nodep** [comment]
New in v3:
- Rebased to master to fix problems with CI

**Comment by nodep** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15180/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15180/) **The following new/updated tests ran 100 times for each mode:** 🔹 topology_custom/test_truncate_with_tablets ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6473/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14492/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3358/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15180/)
> 
> #### Failed Tests (6/39436):
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15180/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15180/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15180/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15180/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15180/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15180/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3)
> 
> #### Build Details:
> * Duration: 10 hr
> * Builder: i-07678fa3b120690bf (m5ad.12xlarge)

Already reported: #22799

**Comment by tchaikov** [comment]
> I have two failed checks on this PR and I don't understand why.
> 
> @tchaikov The check fails on "License Header Check / Check License Headers" which, as far as I can tell checks for the existence of the `LicenseRef-ScyllaDB-Source-Available-1.0` string in the first 10 lines of new files. There are no news files in this PR, and both modified files contain the licence reference string. Maybe the checker got confused with the fact that `storage_proxy.cc` has this:
> 
> ```
> /*
>  * SPDX-License-Identifier: (LicenseRef-ScyllaDB-Source-Available-1.0 and Apache-2.0)
>  */
> ```
> 
> instead of just:
> 
> ```
> /*
>  * SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0
>  */
> ```

@nodep hi Ferenc, sorry for the failure. as you noticed, the script just greps for "LicenseRef-ScyllaDB-Source-Available-1.0" string, so `storage_proxy.cc` is sane in this regard.

Previously the workflow failed, because i didn't take the case where no files were added into consideration. so i pass an empty string as the argument to `check-license.py`. since this is a required argument, the workflow failed because your pull request does not add new files. but this issue has been fixed.

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: service/storage_proxy.cc [hunk 4]
```diff
@@ -452,17 +453,18 @@ class storage_proxy::remote {
...
-            }
-        });
+        (void) seastar::with_gate(_truncate_gate, [=, this] () -> future<> {
+                    co_await request_truncate_with_tablets(ks_name, cf_name).then_wrapped([sem] (auto f) {
+                            if (f.failed()) {
+                                sem->broken(f.get_exception());
+                            } else {
+                                sem->signal(1);
+                            }
+                    });
```
[the remark this answers is not in the document]
Comment (nodep) [reply service/storage_proxy.cc]: Sorry about that. I've fixed it.

File: service/storage_proxy.cc [hunk 5]
```diff
@@ -452,17 +453,18 @@ class storage_proxy::remote {
...
-            if (f.failed()) {
-                sem->broken(f.get_exception());
-            } else {
-                sem->signal(1);
-            }
-        });
+        (void) seastar::with_gate(_truncate_gate, [=, this] () -> future<> {
+                    co_await request_truncate_with_tablets(ks_name, cf_name).then_wrapped([sem] (auto f) {
+                            if (f.failed()) {
+                                sem->broken(f.get_exception());
```
[the remark this answers is not in the document]
Comment (nodep) [reply service/storage_proxy.cc]: I've changed this to use `with_timeout()` instead of semaphores.

**Comment by nodep** [comment]
New in v4:
- Fixed indentation
- Now using `with_timeout()` instead of semaphores

File: service/storage_proxy.cc [hunk 6]
```diff
@@ -1074,14 +1074,33 @@ class storage_proxy::remote {
...
+            // Check if we already have a truncate queued for the same table. This can happen when a truncate has timed out
+            // and the client retried by issuing the same truncate again. In this case, instead of failing the request with
+            // an "Another global topology request is ongoing" error, we can wait for the already queued request to complete.
+            // Note that we can not do this for a truncate which the topology coordinator has already started processing,
+            // only for a truncate which is still waiting.
+            std::optional<global_topology_request>& global_request = _topology_state_machine._topology.global_request;
+            if (global_request.has_value()) {
+                if (*global_request == global_topology_request::truncate_table) {
+                    std::optional<topology::transition_state>& tstate = _topology_state_machine._topology.tstate;
+                    if (tstate.has_value() && *tstate != topology::transition_state::truncate_table) {
```
[the remark this answers is not in the document]
Comment (nodep) [reply service/storage_proxy.cc:1089]: Yes, you are right. It could happen after the end of the last request and before the beginning of the current, truncate request. I will change this to:

`!tstate || *tstate != topology::transition_state::truncate_table`

**Comment by nodep** [comment]
New in v5:
- Truncate is also waited if the current transition state is empty. This covers cases where the previous request has completed, but the coordinator has not yet started processing the truncate request.

**Comment by avikivity** [comment]
> New in v2:
> 
> * Only join a truncate request which is still waiting to be processed, fail if it is already being processed
> * Implement waiting on ongoing truncates to complete during shutdown with wait_gate() instead of a list of futures
> * Change the logging message text as requested

Unforuntately, the cover letter was not updated to reflect the changes.

**Comment by nodep** [comment]
I've added the missing info to the cover letter.
