### PR TITLE
sstables/storage_manager: fix race between object storage config update and keyspace creation

### LINKED ISSUE #28141: Updating object storage endpoints in config sometimes comes unseen
Seen once in #28113 validation

[logs](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/23503/artifact/testlog/x86_64/debug/failed_test/test_create_keyspace_after_config_update%5Bs3%5D.debug.2/stacktrace.txt)
```
manager = <test.pylib.manager_client.ManagerClient object at 0x7f99b52b7d90>
object_storage = [unknown] http://127.138.7.2:44337/testbucket

    @pytest.mark.asyncio
    async def test_create_keyspace_after_config_update(manager: ManagerClient, object_storage):
        server = await manager.server_add()
        cql = manager.get_cql()
    
        print('Trying to create a keyspace with an endpoint not configured in object_storage_endpoints should trip storage_manager::is_known_endpoint()')
        endpoint = 'http://a:456'
        replication_opts = format_tuples({'class': 'NetworkTopologyStrategy',
                                          'replication_factor': '1'})
        storage_opts = format_tuples(type=f'{object_storage.type}',
                                     endpoint=endpoint,
                                     bucket=object_storage.bucket_name)
    
        with pytest.raises(ConfigurationException):
            cql.execute((f'CREATE KEYSPACE random_ks WITH'
                          f' REPLICATION = {replication_opts} AND STORAGE = {storage_opts};'))
    
        print('Update config with a new endpoint and SIGHUP Scylla to reload configuration')
        new_endpoint = MinioServer.create_conf(endpoint, 'region')
        await manager.server_update_config(server.server_id, 'object_storage_endpoints', new_endpoint)
        await wait_for_config(manager, server, 'object_storage_endpoints', {endpoint: '{ "type": "s3", "aws_region": "region", "iam_role_arn": "" }'})
    
        print('Passing a known endpoint will make the CREATE KEYSPACE stmt to succeed')
>       cql.execute((f'CREATE KEYSPACE random_ks WITH'
                        f' REPLICATION = {replication_opts} AND STORAGE = {storage_opts};'))

test/cluster/object_store/test_basic.py:307: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2681: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Endpoint http://a:456 not configured">

cassandra/cluster.py:5056: ConfigurationException
```

endpoint was added to config, but wasn't seen by CQL

[scylla log](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/23503/artifact/testlog/x86_64/debug/failed_test/test_create_keyspace_after_config_update%5Bs3%5D.debug.2/scylla-119.log)
```
INFO  2026-01-13 21:09:29,754 [shard 0:main] init - serving
INFO  2026-01-13 21:09:29,754 [shard 0:main] init - Scylla version 2026.1.0~dev-0.20260113.3fe01850cf16 initialization completed.
INFO  2026-01-13 21:09:30,117 [shard 0:main] init - re-reading configuration file
INFO  2026-01-13 21:09:30,125 [shard 0:main] messaging_service - Reloaded {"conf/scylla.crt"}
INFO  2026-01-13 21:09:30,125 [shard 0:main] init - completed re-reading configuration file
INFO  2026-01-13 21:09:30,131 [shard 0:main] messaging_service - Reloaded {"conf/scylla.key", "conf/scyllacadb.pem"}
```

### PR DESCRIPTION
**Pull request by mitso23**
Previously, config_updater used a serialized_action to trigger update_config() when object_storage_endpoints changed. Because serialized_action::trigger() always schedules the action as a new reactor task (via semaphore::wait().then()), there was a window between the config value becoming visible to the REST API and update_config() actually running. This allowed a concurrent CREATE KEYSPACE to see the new endpoint via is_known_endpoint() before storage_manager had registered it in _object_storage_endpoints. 

Now config observers run synchronously in a reactor turn and must not suspend. Split the previous monolithic async update_config() coroutine  into two phases:    

- Sync (in the observer, never suspends): storage_manager::_object_storage_endpoints is updated in place; for already-instantiated clients, update_config_sync swaps the new config atomically                                                                                                                                                                                                             
- Async (per-client gate): background fibers finish the work that can't run in the observer — S3 refreshes credentials under _creds_sem; GCS drains and closes the replaced client.  

Config reloads triggered by SIGHUP are applied on shard 0 and then broadcast to all other shards. An rwlock has been also introduced to make sure that the configuration has been propagated to all cores. This guarantees that a client requesting a config via the REST API will see a consistent snapshot

Fixes: https://scylladb.atlassian.net/browse/SCYLLADB-757
Fixes: [28141](https://github.com/scylladb/scylladb/issues/28141)

### CODE REVIEW

File: sstables/sstables_manager.cc [hunk 1]
```diff
@@ -100,7 +100,7 @@ storage_manager::storage_manager(const db::config& cfg, config stm_cfg)
 
 future<> storage_manager::stop() {
     if (_config_updater) {
-        co_await _config_updater->action.join();
+        co_await std::exchange(_config_updater->pending_update, make_ready_future<>());
```
Comment (bhalevy) [inline sstables/sstables_manager.cc]: Have you considered `utils::phased_barrier`?

File: db/config.hh [hunk 2]
```diff
@@ -640,6 +642,17 @@ private:
     void maybe_in_workdir(named_value<string_list>&, const char*);
 
     std::shared_ptr<db::extensions> _extensions;
+
+    // Read-write lock used to synchronize config updates (SIGHUP reload +
+    // observer propagation) with REST API readers.
+    rwlock _config_update_lock;
```
Comment (bhalevy) [inline db/config.hh]: It would be good to nest this in a gate and return a tuple/struct with both a gate holder and the lock holder, and add a stop method that closes the gate to make sure no there are no background waiters when config is shut down.

File: sstables/sstables_manager.cc (hunk 1 above)
Comment (mitso23) [reply sstables/sstables_manager.cc]: I didn't know about this `utils::phased_barrier`. We have a simple constrain here that the configuration update will be invoked at most once. We don't expect to have multiple configuration updates, we send a single SIGHUP to reload the config.

File: db/config.hh (hunk 2 above)
Comment (mitso23) [reply db/config.hh]: We could do something like that, but that is more of an enhancement. The purpose of this task is to simply fix the race condition in the config update path, for the object storage.

Comment (bhalevy) [reply db/config.hh]: if the config update is async and yields how would pinning it to shard 0 help?

Comment (mitso23) [reply db/config.hh]: The rwlock lives on shard0 so we have to obtain the read lock from shard0. When a client queries for a config value, the rwlock guarantees that all config values have been propagated to all cores. After the call returns in our case it is safe to issue the create keyspace sql command on any shard.

File: api/config.cc [hunk 3]
```diff
@@ -82,15 +82,20 @@ void set_config(std::shared_ptr < api_registry_builder20 > rb, http_context& ctx
...
-    cs::find_config_id.set(r, [&cfg] (const_req r) {
-        auto id = r.get_path_param("id");
-        for (auto&& cfg_ref : cfg.values()) {
-            auto&& cfg = cfg_ref.get();
-            if (id == cfg.name()) {
-                return cfg.value_as_json();
+    cs::find_config_id.set(r, [&cfg] (std::unique_ptr<http::request> req) -> future<json::json_return_type> {
+        auto id = req->get_path_param("id");
+        // The config update rwlock lives on shard 0 (where the SIGHUP
+        // handler runs). Config is first updated on shard 0 and then broadcasted to all other shards
```
Comment (robertbindar) [inline api/config.cc]: can you please explain how the broadcasting part works? I don't see it here and it's not obvious.

File: sstables/sstables_manager.cc (hunk 1 above)
Comment (robertbindar) [inline sstables/sstables_manager.cc]: why is this needed?

File: test/cluster/object_store/test_basic.py [hunk 4]
```diff
@@ -286,12 +287,28 @@ async def test_create_keyspace_after_config_update(manager: ManagerClient, objec
...
+    else:
+        expected_conf = f'{{ "type": "gs", "credentials_file": "{ep["credentials_file"]}" }}'
+    await wait_for_config(manager, server, 'object_storage_endpoints', {ep['name']: expected_conf})
 
     print('Passing a known endpoint will make the CREATE KEYSPACE stmt to succeed')
     cql.execute((f'CREATE KEYSPACE random_ks WITH'
                     f' REPLICATION = {replication_opts} AND STORAGE = {storage_opts};'))
     
+    #FIXME: Extend this test to verify that a live object_storage_client is correctly reconfigured after a config update
+    # To do that reliably we need to make sure that configuration updates are fully synchronous.
```
Comment (robertbindar) [inline test/cluster/object_store/test_basic.py]: isnt wait_for_config a reliable enough mechanism to make sure that object_storage_client got reconfigured?

File: sstables/sstables_manager.cc (hunk 1 above)
Comment (mitso23) [reply sstables/sstables_manager.cc]: When we are shutting down, if there is a pending update in progress we need to wait for it to complete. With my current change, this can only happen if we have re-configured an existing endpoint (which is still an asynchronous operation). 

        auto [it, added] = _object_storage_endpoints.try_emplace(endpoint, e);
        if (!added) {
            if (it->second.client != nullptr) {
                co_await it->second.client->update_config(e);  --> updating config of existing client is still async
            }
            it->second.cfg = e;
        }
    }

    std::erase_if(_object_storage_endpoints, [&updates](const auto& e) {
        return !updates.contains(e.first);
    });

    co_return;
}`

File: test/cluster/object_store/test_basic.py (hunk 4 above)
Comment (mitso23) [reply test/cluster/object_store/test_basic.py]: No before my change this was not. The HTTP client returns the in-memory value from db::config. This on its own doesn't guaranteed that the config_update has run in storage_manager. Before my change the config_update was triggered by a serialized action that could yield before calling the function

File: api/config.cc (hunk 3 above)
Comment (mitso23) [reply api/config.cc]: The implementation is quite straightforward. It copies configuration values from shard 0 to all other shards and runs observers(might be async) that notify clients of any configuration changes.

Comment (robertbindar) [reply api/config.cc]: Can you point me to the part that actually does the copying from shard 0 to all the other shards?

File: sstables/sstables_manager.cc (hunk 1 above)
Comment (robertbindar) [reply sstables/sstables_manager.cc]: makes sense, thanks

File: test/cluster/object_store/test_basic.py (hunk 4 above)
Comment (robertbindar) [reply test/cluster/object_store/test_basic.py]: Ok, I see. What does the statements below are trying to test then? Trying to understand the chunk below in relation to the FIXME statement above.

Comment (mitso23) [reply test/cluster/object_store/test_basic.py]: So I have extended the test to use real object storage endpoints from Minio. Forcing the data to be flushed to disk creates an object storage client. The next step is to re-configure that existing client , for example change the region from aws_region1 to aws_region2. That will happen asynchronously by the code snippet pasted above. Before enabling this test we would need to do some work in the backend, maybe split config_update into 2 parts, sync and async. We need to think about it

File: api/config.cc (hunk 3 above)
Comment (mitso23) [reply api/config.cc]: Sure, it is in main.cc

> // Main work loop. Waits for either _stopping or _pending to be raised, and
    // re-reads the configuration file if _pending. We use a repeat loop here to
    // avoid having multiple reads of the configuration file happening in parallel
    // (this can cause an older read to overwrite the results of a younger read).
    future<> do_work() {
        return repeat([this] {
            return _cond.wait([this] { return _pending || _stopping; }).then([this] {
                return async([this] {
                    if (_stopping) {
                        return stop_iteration::yes;
                    } else if (_pending) {
                        _pending = false;
                        try {
                            startlog.info("re-reading configuration file");
                            auto lock = _cfg.lock_for_config_update().get();
                            read_config(_opts, _cfg).get();
                            _cfg.broadcast_to_all_shards().get();
                            startlog.info("completed re-reading configuration file");
                        } catch (...) {
                            startlog.error("failed to re-read configuration file: {}", std::current_exception());
                        }
                    }
                    return stop_iteration::no;
                });
            });
        });
    }

File: db/config.hh (hunk 2 above)
Comment (avikivity) [reply db/config.hh]: If we need both a gate and a lock, the primitives are lacking.

File: db/config.hh [hunk 5]
```diff
@@ -640,6 +642,17 @@ private:
...
+public:
+    future<rwlock::holder> lock_for_config_update() {
+        return _config_update_lock.hold_write_lock();
+    }
+    future<rwlock::holder> wait_for_config_update() {
+        return _config_update_lock.hold_read_lock();
```
Comment (avikivity) [inline db/config.hh]: Seems wrong that a function called wait returns a lock.+

File: api/config.cc [hunk 6]
```diff
@@ -82,15 +82,20 @@ void set_config(std::shared_ptr < api_registry_builder20 > rb, http_context& ctx
...
+        co_return co_await smp::submit_to(0, [&cfg, id = std::move(id)] () -> future<json::json_return_type> {
+            auto lock = co_await cfg.wait_for_config_update();
+            for (auto&& cfg_ref : cfg.values()) {
+                auto&& c = cfg_ref.get();
+                if (id == c.name()) {
+                    co_return c.value_as_json();
+                }
```
Comment (avikivity) [inline api/config.cc]: It's wrong for the locking to be done outside db/config.cc

File: db/config.hh (hunk 2 above)
Comment (bhalevy) [reply db/config.hh]: > If we need both a gate and a lock, the primitives are lacking.

It would be good if a rwlock could be closed similar to a gate to wait for all holders and prevent new ones (that would get a gate_closed_exception or similar if they try to acquire the lock)

File: db/config.hh (hunk 5 above)
Comment (mitso23) [reply db/config.hh]: I have removed this function. The logic to acquire the read lock is moved to db/config.cc

File: api/config.cc (hunk 6 above)
Comment (mitso23) [reply api/config.cc]: Moved the logic to db/config.cc, to keep the logic encapsulated

File: test/cluster/object_store/test_basic.py [hunk 7]
```diff
@@ -270,11 +270,12 @@ async def test_get_object_store_endpoints(manager: ManagerClient, config_with_fu
 
 @pytest.mark.asyncio
 async def test_create_keyspace_after_config_update(manager: ManagerClient, object_storage):
+    # Start server WITHOUT object storage endpoints initially
     server = await manager.server_add()
     cql = manager.get_cql()
 
     print('Trying to create a keyspace with an endpoint not configured in object_storage_endpoints should trip storage_manager::is_known_endpoint()')
-    endpoint = 'http://a:456'
+    endpoint = object_storage.address
```
Comment (xemul) [inline test/cluster/object_store/test_basic.py:299]: With that change, the above print message is not longer correct

File: test/cluster/object_store/test_basic.py [hunk 8]
```diff
@@ -286,12 +287,28 @@ async def test_create_keyspace_after_config_update(manager: ManagerClient, objec
                       f' REPLICATION = {replication_opts} AND STORAGE = {storage_opts};'))
 
     print('Update config with a new endpoint and SIGHUP Scylla to reload configuration')
-    new_endpoint = MinioServer.create_conf(endpoint, 'region')
-    await manager.server_update_config(server.server_id, 'object_storage_endpoints', new_endpoint)
-    await wait_for_config(manager, server, 'object_storage_endpoints', {endpoint: '{ "type": "s3", "aws_region": "region", "iam_role_arn": "" }'})
+    objconf = object_storage.create_endpoint_conf()
```
Comment (xemul) [inline test/cluster/object_store/test_basic.py:311]: But does the new config is actually created? Up above the config already uses object_storage.address, so what changes here?

File: db/config.hh [hunk 9]
```diff
@@ -173,6 +176,16 @@ public:
...
 
+    future<rwlock::holder> lock_for_config_update() {
+        return _config_update_lock.hold_write_lock();
+    };
+
+    // Look up a config entry by name and return its JSON representation.
+    // Runs on shard 0 under a read lock so the result is consistent with
+    // any in-progress SIGHUP reload + broadcast_to_all_shards() sequence.
+    // Returns std::nullopt if no config entry with the given name exists.
+    future<std::optional<json::json_return_type>> value_as_json_for_name(sstring name) const;
```
Comment (xemul) [inline db/config.hh]: Pulling json stuff to db/config.hh is not nice. Can this method return a value and the caller would then convert it to json?

File: test/cluster/object_store/test_basic.py (hunk 7 above)
Comment (mitso23) [reply test/cluster/object_store/test_basic.py:299]: It is still valid, if you look at line 274, server_add is being called with default config that doesn't include `object_storage_endpoints`. The assertion still works, we are not able to create the keyspace with object storage

File: test/cluster/object_store/test_basic.py (hunk 8 above)
Comment (mitso23) [reply test/cluster/object_store/test_basic.py:311]: See the comment above, server_add is called without `object_storage_endpoints`, so we need to update the config to a valid one here.

File: db/config.hh (hunk 9 above)
Comment (mitso23) [reply db/config.hh]: I think I tried and it was not possible. I will double check in the code

File: sstables/sstables_manager.cc [hunk 10]
```diff
@@ -173,10 +173,17 @@ std::vector<sstring> storage_manager::endpoints(sstring type) const noexcept {
...
+    : observer(cfg.object_storage_endpoints.observe([&sstm, &cfg] (const std::vector<db::object_storage_endpoint_param>&) {
+        // Call update_config directly in the current reactor turn so that
+        // _object_storage_endpoints is updated synchronously before the
+        // observer returns.  When no existing client needs reconfiguring
+        // (the common case on first load) update_config never suspends and
+        // completes inline, closing the race window that existed when a
+        // serialized_action was used.
+        // FIXME: split update_config into two parts, one that is executed
+        // synchronously and one that can run in the background
+        sstm._config_updater->pending_update = sstm.update_config(cfg);
```
Comment (xemul) [inline sstables/sstables_manager.cc]: It creates a race when sstm.update_config() is called, spawns a backgound client update, but then another HUP comes shortly and pending_update future is overwritten by a _new_ fiber. The serialized_action was there for a reason.

Also, the idiomatic way to spawn something in the bacground and wait for it on stop is to use gates.

Having sais that, so I sugges that storage_manager::update_config() is patched to be void-returning method, and if it needs to kick clients refresh, it does it with a) serialized_action to merge fast HUPs happening one after another b) gate not leave

File: db/config.hh (hunk 9 above)
Comment (mitso23) [reply db/config.hh]: It doesn't look like it is possible. Current value in `config_src`  is void* so it is pretty much type erased. 
We can only get the JSON representation through `config_type` which is also type erased. 

class config_type {
    std::string_view _name;
    std::function<json::json_return_type (const void*)> _to_json;  
private:
    template <typename NativeType>
    std::function<json::json_return_type (const void*)> make_to_json(json::json_return_type (*func)(const NativeType&)) {
        return [func] (const void* value) {
            return func(*static_cast<const NativeType*>(value));
        };
    }
public:
    template <typename NativeType>
    config_type(std::string_view name, json::json_return_type (*to_json)(const NativeType&)) : _name(name), _to_json(make_to_json(to_json)) {}
    std::string_view name() const { return _name; }
    json::json_return_type to_json(const void* value) const;
};


I can remove the `json_element.h` include and simply return an `sstring` which will hold the json encoded value.

File: sstables/sstables_manager.cc (hunk 10 above)
Comment (mitso23) [reply sstables/sstables_manager.cc]: That is why I have the `FIXME` there. We don't have currently any tests that update the config of an existing client. In all other cases the function is executed synchronously , so even in the extremely unlikely event we have multiple HUPs this should work. So I  would suggest doing this as a follow up. 

Alternatively what we can do is after the HUP we wait for the background tasks to finish. This will work because we are holding a lock now. Something like this 

try {
                            startlog.info("re-reading configuration file");
                            auto lock = _cfg.lock_for_config_update().get();
                            read_config(_opts, _cfg).get();
                            _cfg.broadcast_to_all_shards().get();
                            sstable_manager.wait_background_tasks.get();
                            startlog.info("completed re-reading configuration file");
                        } catch (...) {
                            startlog.error("failed to re-read configuration file: {}", std::current_exception());
                        }

File: test/cluster/object_store/test_basic.py (hunk 7 above)
Comment (robertbindar) [inline test/cluster/object_store/test_basic.py:299]: this still does what the comment say, correct? that is object_storage.address is not configured in scylla.yaml endpoints.

File: test/cluster/object_store/test_basic.py [hunk 11]
```diff
@@ -286,12 +287,53 @@ async def test_create_keyspace_after_config_update(manager: ManagerClient, objec
...
+    await manager.api.flush_keyspace(server.ip_addr, 'random_ks')
+    res = cql.execute(f"SELECT value FROM random_ks.test WHERE name = 'after_reconfig';")
+    assert res.one().value == 456, f'Unexpected value after reconfiguration flush: {res.one().value}'
+
+    print('Verify all data is intact')
+    rows = {r.name: r.value for r in cql.execute(f'SELECT * FROM random_ks.test;')}
+    assert rows == {'test_key': 123, 'after_reconfig': 456}, f'Unexpected table content: {rows}'
+
+    #This will ensure that cleanup of client is handled properly when we are terminating
+    await manager.server_restart(server.server_id)
```
Comment (robertbindar) [inline test/cluster/object_store/test_basic.py]: is this needed to make sure `storage_manager::stop` works alright?

File: db/config.cc [hunk 12]
```diff
@@ -1721,6 +1682,23 @@ void db::config::maybe_in_workdir(named_value<string_list>& tos, const char* sub
     }
 }
 
+future<std::optional<sstring>> db::config::value_as_json_string_for_name(sstring name) const {
```
Comment (robertbindar) [inline db/config.cc:1730]: Did Benny's concern here https://github.com/scylladb/scylladb/pull/28950#discussion_r2904749715 get resolved?

**Review by robertbindar — APPROVED** [review]
minor clarifying comments from my side, other than that, looks alright to me.

File: test/cluster/object_store/test_basic.py (hunk 11 above)
Comment (mitso23) [reply test/cluster/object_store/test_basic.py]: Yes If I am not mistaken, if scylla terminates without awaiting a future it will terminate or throw an exception.

File: test/cluster/object_store/test_basic.py (hunk 7 above)
Comment (mitso23) [reply test/cluster/object_store/test_basic.py:299]: yeap

File: db/config.cc (hunk 12 above)
Comment (mitso23) [reply db/config.cc:1730]: I am not sure to be honest if we want to use a gate, Avi seems to indicate that it might not make sense to use a gate and an rwlock. Maybe Pavel can break the tie.

File: utils/s3/client.cc [hunk 13]
```diff
@@ -130,14 +130,21 @@ client::client(std::string host, endpoint_config_ptr cfg, semaphore& mem, global
...
         .use_https = _cfg->use_https,
         .region = std::move(region),
         .role_arn = std::move(ira),
     };
     _cfg = make_lw_shared<endpoint_config>(std::move(new_cfg));
+    _creds_refresh_needed = true;
+}
+
+future<> client::post_config_update_cleanup() {
+    if (!std::exchange(_creds_refresh_needed, false)) {
```
Comment (xemul) [inline utils/s3/client.cc]: What does this bit protect us from?

File: sstables/sstables_manager.hh [hunk 14]
```diff
@@ -63,7 +64,7 @@ struct sstable_snapshot_metadata {
 
 class storage_manager : public peering_sharded_service<storage_manager> {
     struct config_updater {
-        serialized_action action;
+        serialized_action async_updater;
```
Comment (xemul) [inline sstables/sstables_manager.hh]: I think we no longer need this action. Just each client in its update_config_sync() sends the needed sleeping activity into background fiber holding some (client-local) gate. On client stop the gate should be closed, thus preventing any use-after free

File: db/config.cc (hunk 12 above)
Comment (bhalevy) [reply db/config.cc:1730]: I submitted https://github.com/scylladb/seastar/pull/3332 in the meanwhile so we can get close semantics with a rwlock.  Since the fixes a ci-stability issue, personally I think it's fine for the short term to go with an extra gate and then, once the seastar PR gets to scylla, replace the extra gate with direct close of the rwolock.

@avikivity how does that sound?

File: utils/s3/client.cc (hunk 13 above)
Comment (mitso23) [reply utils/s3/client.cc]: It makes the function idempotent. I am calling the `post_config_update_cleanup` for all existing clients in `config_updater`.

File: sstables/sstables_manager.hh (hunk 14 above)
Comment (mitso23) [reply sstables/sstables_manager.hh]: Well I did this based on your recommendation to use serialized action. For example if we get 5 SIGHUP, we only need to process 2 of those (first and last). Does the gate has this capability (I need to check) ?

File: db/config.hh (hunk 2 above)
Comment (mitso23) [reply db/config.hh]: @bhalevy I checked with AI, and in this instance, when going through the shutdown instance `rwlock` inside db::config outlives all its users

1. stop_config_api (line 1388) runs first — it unregisters the /config/{id} REST handler, so no new requests will hit value_as_json_string_for_name().
2. stop_http_server (line 964) runs next — it stops the HTTP server entirely, which drains any in-flight HTTP requests. After this returns, no HTTP handler can be executing.
3. stop_sighup_handler (line 843) runs later — it stops the SIGHUP handler, which is the only writer of the rwlock.
4. cfg (line 682) is destroyed last (outside app.run()), so the rwlock inside db::config outlives all its users.

File: db/config.cc (hunk 12 above)
Comment (mitso23) [reply db/config.cc:1730]: @bhalevy  see comment https://github.com/scylladb/scylladb/pull/28950#discussion_r3020781348

For this specific use case we don't need a gate

File: db/config.hh (hunk 2 above)
Comment (bhalevy) [reply db/config.hh]: @mitso23 so IIUC a gate is not required, right?

Comment (mitso23) [reply db/config.hh]: yes it is not required, `db::config` is alive for entire duration of `app.run()`. When `app.run()` returns all the deferred stops have already executed, so we are safe.

File: sstables/sstables_manager.hh (hunk 14 above)
Comment (mitso23) [reply sstables/sstables_manager.hh]: OK I see how a gate works. Will follow your suggestion

File: sstables/object_storage_client.cc [hunk 15]
```diff
@@ -277,20 +278,32 @@ class gs_client_wrapper : public sstables::object_storage_client {
...
+
+        // Spawn the async old-client close into a background fiber,
+        // gated so that close() waits for it to complete.
+        (void)seastar::try_with_gate(_config_update_gate, [old_client = std::move(old_client)] () mutable -> future<> {
+            co_await old_client->close();
+        }).handle_exception([] (std::exception_ptr ep) {
+            try {
+                std::rethrow_exception(ep);
+            } catch (const seastar::gate_closed_exception&) {
+            }
```
Comment (bhalevy) [inline sstables/object_storage_client.cc]: other exception types would be rethrown but not handled. It is an error since the future is abandoned, so we need to ignore all exceptions.
You should have a default catch clause and can print a warning about the ignored exception.

File: sstables/object_storage_client.cc [hunk 16]
```diff
@@ -277,20 +278,32 @@ class gs_client_wrapper : public sstables::object_storage_client {
...
             });
         }
 
     }
-    future<> update_config(const db::object_storage_endpoint_param& ep) override {
-        auto client = std::exchange(_client, make_gcs_client(ep, _memory));
-        co_await client->close();
+    void update_config_sync(const db::object_storage_endpoint_param& ep) override {
+        auto new_client = make_gcs_client(ep, _memory);
+        auto old_client = std::exchange(_client, std::move(new_client));
```
Comment (bhalevy) [inline sstables/object_storage_client.cc:317]: If the gate is already closed we should not create a new client.

How about just holding the gate on entry to this function so if it's already close it will throw gate_closed_exception.
With that you won't need the cumbersome try_with_gate below.

Comment (mitso23) [reply sstables/object_storage_client.cc:317]: I think what you are trying to say is that we **shouldn't** create a new client if the gate throws, right ?

Comment (bhalevy) [reply sstables/object_storage_client.cc:317]: right, of course. sorry about the typo.  fixed

File: sstables/object_storage_client.cc [hunk 17]
```diff
@@ -277,20 +282,41 @@ class gs_client_wrapper : public sstables::object_storage_client {
...
+
+        // Spawn the async old-client close into a background fiber,
+        // the holder keeps the gate open until the work completes.
+        // "this auto" turns the implicit this pointer into a by-value parameter,
+        // so the coroutine frame owns the lambda captures instead of holding
+        // a dangling pointer to the destroyed lambda temporary
+        // (see seastar/doc/lambda-coroutine-fiasco.md).
+        (void)[old_client = std::move(old_client), h = std::move(holder)] (this auto) -> future<> {
```
Comment (bhalevy) [inline sstables/object_storage_client.cc]: this turned out to be 10x overcomplicated then it should.
It's just `(void)old_client-close().handle_exception([old_client = std::move(old_client), h = std::move(holder)] (std::exception_ptr ex) { osclog.warn("Failed ... {}, ex); });`

File: sstables/object_storage_client.cc [hunk 18]
```diff
@@ -277,20 +282,41 @@ class gs_client_wrapper : public sstables::object_storage_client {
...
+                osclog.warn("Failed to close old GCS client during config update: {}", e.what());
+            } catch (...) {
+                osclog.warn("Failed to close old GCS client during config update: unknown exception");
+            }
+        }();
     }
     future<> close() override {
-        return _client->close();
+        co_await _config_update_gate.close();
+        co_await _client->close();
```
Comment (bhalevy) [inline sstables/object_storage_client.cc:329]: nit: if client close may fail, then the failure should be ignored here too. Can the failure always be handled in the client close method?

File: sstables/object_storage_client.cc (hunk 17 above)
Comment (mitso23) [reply sstables/object_storage_client.cc]: This is nice, passing the capture in handle_exception :)

Comment (mitso23) [reply sstables/object_storage_client.cc]: And hopefully this will fix my use after free issue that happens only in Jenkins

Comment (mitso23) [reply sstables/object_storage_client.cc]: This idiom doesn't seems to work, deduce this doesn't extend the lambda's lifetime.

File: sstables/object_storage_client.cc (hunk 18 above)
Comment (mitso23) [reply sstables/object_storage_client.cc:329]: There is generally no exception handling on the client side. Need to look into this, we can just handle it here, and just ignore it

File: sstables/object_storage_client.cc [hunk 19]
```diff
@@ -277,20 +283,38 @@ class gs_client_wrapper : public sstables::object_storage_client {
...
+        osclog.info("Updating GCS client config");
+
+        auto holder = _config_update_gate.hold();
+        auto new_client = make_gcs_client(ep, _memory);
+        auto old_client = std::exchange(_client, std::move(new_client));
+        (void)old_client->close()
+                .handle_exception([](std::exception_ptr ex) {
+                    osclog.error("Failed to close old GCS client during config update: {}", ex);
+                })
+                .finally([old_client = std::move(old_client), h = std::move(holder)] {
```
Comment (bhalevy) [inline sstables/object_storage_client.cc:322]: Capturing in handle_exception should have worked.  Maybe there is something else here.
I see that  lwe return a shared_ptr. Is it okay to close it while in use, or should it be closed only when it loses its last reference, before it is destoryed?

Comment (mitso23) [reply sstables/object_storage_client.cc:322]: That is something I need to investigate. I have added new tests that exercise this code path for the first time, so there might be pre existing bugs. There is a race condition that i can't reproduce locally but now I have a trace from address sanitizer from a failing test in Jenkins, that I can use to investigate

Comment (bhalevy) [reply sstables/object_storage_client.cc:322]: I looked at the existing code.  Unfortunately, it is incredibly convoluted.
I don't really understand how we keep track of the the s3 and gcp clients life times
to make sure that close() waits for all outstanding shared_ptr copies to be released, with or without config update. And how all this works with the wrapper objects that keep a shared_ptr client and a factory function for a shard_client.  Nice spaghetti dish :-/

File: sstables/object_storage_client.cc [hunk 20]
```diff
@@ -277,20 +283,38 @@ class gs_client_wrapper : public sstables::object_storage_client {
...
+                    osclog.info("Old GCS client cleanup done, use_count={}", old_client.use_count());
```
Comment (bhalevy) [inline sstables/object_storage_client.cc:323]: this shouldn't be logged in info level, debug seems more appropriate.

File: sstables/sstables_manager.cc [hunk 21]
```diff
@@ -99,45 +100,13 @@ storage_manager::storage_manager(const db::config& cfg, config stm_cfg)
...
-    if (_config_updater) {
-        co_await _config_updater->action.join();
-    }
-
-    for (auto ep : _object_storage_endpoints) {
-        if (ep.second.client != nullptr) {
-            co_await ep.second.client->close();
+    for (auto& [name, ep] : _object_storage_endpoints) {
+        if (ep.client != nullptr) {
+            co_await ep.client->close();
```
Comment (bhalevy) [inline sstables/sstables_manager.cc]: nit: this hunk has no functional change, right?
If so, let's revert it since there is enough code churn already

File: sstables/sstables_manager.cc [hunk 22]
```diff
@@ -173,18 +142,45 @@ std::vector<sstring> storage_manager::endpoints(sstring type) const noexcept {
 }
 
 storage_manager::config_updater::config_updater(const db::config& cfg, storage_manager& sstm)
-    : action([&sstm, &cfg] () mutable {
-        return sstm.update_config(cfg);
-    })
-    , observer(cfg.object_storage_endpoints.observe(action.make_observer()))
+    : observer(cfg.object_storage_endpoints.observe([&sstm, &cfg] (const std::vector<db::object_storage_endpoint_param>&) {
```
Comment (bhalevy) [inline sstables/sstables_manager.cc:145]: why not rename `storage_manager::update_config` to `storage_manager::update_config_sync`?
it will be clearer to see the transformation from the async config updater to the synchronous one.

File: utils/s3/client.cc [hunk 23]
```diff
@@ -120,18 +130,33 @@ client::client(std::string host, endpoint_config_ptr cfg, semaphore& mem, global
...
     };
     _cfg = make_lw_shared<endpoint_config>(std::move(new_cfg));
-    auto units = co_await get_units(_creds_sem, 1);
-    _creds_provider_chain.invalidate_credentials();
-    _credentials = {};
-    _creds_update_timer.rearm(lowres_clock::now());
+
+    (void)get_units(_creds_sem, 1).then_wrapped([this, h = std::move(holder)](future<semaphore_units<>> f) {
+        try {
+            s3l.info("Invalidating credentials");
```
Comment (bhalevy) [inline utils/s3/client.cc:140]: nit: not sure if this (and other) log messages should be in info or debug level.  In any case, the message should be state that this is part of config_update, not the regular creds invalidation.

File: utils/s3/client.cc [hunk 24]
```diff
@@ -1788,6 +1811,9 @@ file client::make_readable_file(sstring object_name, seastar::abort_source* as)
 }
 
 future<> client::close() {
+    s3l.info("Closing S3 client...");
```
Comment (bhalevy) [inline utils/s3/client.cc:1818]: ditto, debug level seems more appropriate here and below.

File: sstables/object_storage_client.cc (hunk 19 above)
Comment (bhalevy) [reply sstables/object_storage_client.cc:322]: @mitso23 I think that the heap-use-after free might have been caused by using a coroutine lambda asynchronously, since coroutine lambdas lose their captures when they need to yield (see https://github.com/scylladb/seastar/blob/master/doc/lambda-coroutine-fiasco.md)

So, with the following:
```c++
        (void)[old_client = std::move(old_client), h = std::move(holder)] (this auto) -> future<> {
            try {
                co_await old_client->close();
            } catch (const std::exception& e) {
                osclog.warn("Failed to close old GCS client during config update: {}", e.what());
            } catch (...) {
                osclog.warn("Failed to close old GCS client during config update: unknown exception");
            }
        }();
```

if `old_client->close()` does not return a ready future, the coroutine lambda is destroyed, losing the capture of the `old_client` shared_ptr.

Edit: I see that the coroutine lambda accepted `this auto` as a parameter so it should have worked.
It'd be interesting to see what exactly cause the use-after-free in previous versions, but it seems to be gone in the latest version so I wouldn't block this PR on that.

Comment (bhalevy) [reply sstables/object_storage_client.cc:322]: So using just `handle_exception`, or alternatively `then_wrapped` continuation, if you want to distinguish between the failure and success paths, without `.finally` should work fine.

Comment (mitso23) [reply sstables/object_storage_client.cc:322]: No unfortunately the use after free still occurs, even with the existing code. I have just disabled my newly added test for GC cleint (do not update the config of a live client)

Comment (mitso23) [reply sstables/object_storage_client.cc:322]: > I looked at the existing code. Unfortunately, it is incredibly convoluted. I don't really understand how we keep track of the the s3 and gcp clients life times to make sure that close() waits for all outstanding shared_ptr copies to be released, with or without config update. And how all this works with the wrapper objects that keep a shared_ptr client and a factory function for a shard_client. Nice spaghetti dish :-/

It is very convoluted, and I think the problem is that it might unsafe to close the client, while there are still some pending operations on the client.

File: utils/s3/client.cc (hunk 23 above)
Comment (mitso23) [reply utils/s3/client.cc:140]: This is very infrequent event, so we can log it at info level, but I can improve the message. Might happen once, if ever

File: utils/s3/client.cc (hunk 24 above)
Comment (mitso23) [reply utils/s3/client.cc:1818]: This is called very infrequently, so I think we can keep it at info level, very helpful when scylla shuts down, or configuration changes

File: sstables/object_storage_client.cc (hunk 19 above)
Comment (bhalevy) [reply sstables/object_storage_client.cc:322]: > No unfortunately the use after free still occurs, even with the existing code. I have just disabled my newly added test for GC cleint (do not update the config of a live client)

@mitso23 can you please try https://github.com/bhalevy/scylla/commit/41b8e11db4f74779a6ae2cca86aa514c9629cc51 ?

**Comment by bhalevy** [comment]
@mitso23 branch needs rebasing and I had a couple of minor comments still.
Let's try to merge this this week before 2026.2 is cut

File: sstables/sstables_manager.cc (hunk 21 above)
Comment (mitso23) [reply sstables/sstables_manager.cc]: I will revert it yes, this has no functional changes

**Comment by mitso23** [comment]
> @mitso23 branch needs rebasing and I had a couple of minor comments still. Let's try to merge this this week before 2026.2 is cut

OK, I will go through you latest comments, rebase, and we should be able to merge this. I will create a separate JIRA to address the use after free that we observed with GC client, it is a pre-existing issue that was uncovered after the addition of new tests (Pavel is OK with that). This is an edge case anyway, live update of an existing config (GC client) might never be required so I think it is low priority anyway

File: sstables/object_storage_client.cc (hunk 19 above)
Comment (mitso23) [reply sstables/object_storage_client.cc:322]: I have created a new issue for the GC client race condition, https://scylladb.atlassian.net/browse/SCYLLADB-1559

We are currently skipping the part of the test that does a live config update. This is low priority issue, and before attempting a fix, we need to reproduce this locally using error injection, at the moment the issue happens only in Jenkins (I assume that writing sstables to disk is slower).

Comment (bhalevy) [reply sstables/object_storage_client.cc:322]: Can we simulate high latency also with the object storage mock-ups?

Comment (mitso23) [reply sstables/object_storage_client.cc:322]: I don't fully understand the question. Do you mean run performance test against minio with latte ?

Comment (bhalevy) [reply sstables/object_storage_client.cc:322]: That's one use case, but it can also be used to stress timing-related issues (though error injection for reproducing races suck as this one is better).

**Review by bhalevy — APPROVED** [review]

**Comment by robertbindar** [comment]
Backporting to 2026.1 as I'm hitting the race in https://jenkins.scylladb.com/job/scylla-2026.1/job/scylla-ci/460/ from https://github.com/scylladb/scylladb/pull/31416
