### PR TITLE
cql:  allow SUM() aggregations which result in a NaN

### LINKED ISSUE #13551: sum() of +inf and -inf results in error instead of NaN (dtest failure test_cast_varint)
Seen consistently since https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/229/testReport/cql_cast_test/TestCQLCast/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_cast_varint/
Scylla version c65bd01174c1
```
self = <cql_cast_test.TestCQLCast object at 0x7f240783f8d0>

    def test_cast_varint(self):
        """Function performs positive tests CAST scalar function for varint type"""
        test_from = ['varint']
>       self._test_run(test_from, TestData.POSITIVE_VALUES)

cql_cast_test.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cql_cast_test.py:229: in _test_run
    self._test_one_type(from_type, data_dict, exclude, column_name, table_name, success, fail,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cql_cast_test.TestCQLCast object at 0x7f240783f8d0>
from_type = 'varint'
data_dict = {'ascii': [["'045asciitext'", {'cast': {'text': '045asciitext', 'varchar': '045asciitext'}, 'max': {'text': 'abcdefj',...900-01-01 00:00:00.000000+0000'}}], ["'2458-12-13'", {'cast': {'timestamp': '2458-12-13 00:00:00.000000+0000'}}]], ...}
exclude = True, column_name = 'varint_clmn', table_name = 'cast_varint_test'
success = 0, fail = 0, test_types = None, test_to = None, compare_error = False

    def _test_one_type(self, from_type, data_dict, exclude, column_name, table_name, success, fail, test_types=None,
                       test_to=None, compare_error=None):
        for row_id, exp_results in enumerate(data_dict[from_type]):
            for test, test_exp_result in exp_results[1].items():
                # If asked exclude tests with name started with "#"
                # test_commented = False
                if exclude and test.startswith('#'):
                    continue
                test_commented = self.is_commented(exclude, test)
                test = test.replace('#', '')
    
                if (test_types and test in test_types) or not test_types:
                    for to_type, exp_result in test_exp_result.items():
                        # If asked exclude tests with name started with "#"
                        # type_commented = False
                        if exclude and to_type.startswith('#'):
                            continue
                        type_commented = self.is_commented(exclude, to_type)
                        to_type = to_type.replace('#', '')
    
                        if exp_result and (not test_to or (test_to and to_type in test_to)) \
                                and (exclude or (not exclude and (type_commented or test_commented))):
                            actual_result, err = self._test_execute(self.TESTS[test][0], column_name, to_type, row_id,
                                                                    table_name, from_type, test, exp_results=exp_results[0])
    
                            actual_result = actual_result.split('\n')[3].strip() \
                                if not compare_error and actual_result else err if compare_error else ''
>                           assert actual_result == str(exp_result), "casting from type {} to type {}: expected {} but got {}".format(
                                from_type, to_type, exp_result, actual_result)
E                           AssertionError: casting from type varint to type float: expected NaN but got 
E                           assert '' == 'NaN'
E                             - NaN

cql_cast_test.py:274: AssertionError
```

### PR DESCRIPTION
**Pull request by nyh**
This short PR fixes a bug in SUM() aggregation where if the data contains +Inf and -Inf the returned sum should be NaN but we returned an error instead. This is a recent regression uncovered by a dtest (see issue #13551), but in the first patch we add additional tests in the cql-pytest framework which reproduce this bug and explore various other areas (wrongly) implicated by the failing dtest.

Fixes #13551

### CODE REVIEW

File: cql3/functions/aggregate_fcts.cc [hunk 1]
```diff
@@ -143,11 +143,26 @@ make_internal_scalar_function(sstring name, null_handler nullhandler, Lambda fun
...
+template<> bool is_same(const double& t1, const double& t2) {
+    return std::isnan(t1) ? std::isnan(t2) : t1 == t2;
+}
+
 template<typename NarrowT, typename WideT>
 NarrowT
 narrow(WideT acc) {
     NarrowT ret = static_cast<NarrowT>(acc);
-    if (static_cast<WideT>(ret) != acc) {
+    if (!is_same(static_cast<WideT>(ret), acc)) {
```
Comment (avikivity) [inline cql3/functions/aggregate_fcts.cc:165]: IMO we should just check if NarrowT == WideT. If the two types are different, then t1 == t2 will fail on the least significant digits.

The correct check for float types is not t1 == t2, but t1 != inf && t2 == inf, indicating an overflow. Or maybe we don't need to check anything, since inf is a reasonable result for overflow, better than failing the query.

**Comment by nyh** [comment]
Pushed new version with the alternative workaround suggested by Avi - narrow will avoid the spurious check when the accumulator and result types are identical, and in particular in the floating-point case where they are indeed identical.

**Review by denesb — APPROVED** [review]
