### PR TITLE
sstables: fix some mixups between the writer's schema and the sstable's schema

### LINKED ISSUE #16065: sstable - writer fails/crashes if schema is altered during the write operation
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

There is a sequence of nemeses during longevity-150gb-asymmetric-cluster-12h-test which not failed actually, but produced errors during their run.

The main problematic nemesis is MgmtRestore during which we got following errors:

```
2023-11-11 11:21:45.080: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=a46d1e86-265b-4b66-aec3-5e64ed63da42 during_nemesis=MgmtRestore: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=662 node=Node longevity-50gb-12h-master-loader-node-df57e125-1 [54.154.200.67 | 10.4.8.30] (seed: False)
java.io.IOException: Operation x10 on key(s) [31383334393132383431]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 0 alive)
...
2023-11-11 11:22:36.841: (CassandraStressEvent Severity.ERROR) period_type=end event_id=a46d1e86-265b-4b66-aec3-5e64ed63da42 during_nemesis=MgmtRestore duration=1m2s: node=Node longevity-50gb-12h-master-loader-node-df57e125-1 [54.154.200.67 | 10.4.8.30] (seed: False)
stress_cmd=cassandra-stress read cl=QUORUM n=5242880 -schema 'keyspace=5gb_sizetiered_5_2 replication(strategy=NetworkTopologyStrategy,replication_factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native  -rate threads=50 -col 'size=FIXED(64) n=FIXED(16)' -pop seq=1..5242880
errors:
Stress command completed with bad status 1: WARN  11:21:41,820 Error while computing token map for keyspace 5gb_sizetiered_5_2 with datacenter u
``` 

This problem is tracked here: https://github.com/scylladb/scylla-manager/issues/3525

But in the last run (https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-150gb-asymmetric-cluster-12h-test/28/) we got additional error during consequent ModifyTable nemesis:

```
2023-11-11 23:52:25.693 <2023-11-11 23:52:25.627>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=1adb6f8a-6998-4c5f-8274-308c87b2b574: type=RUNTIME_ERROR regex=std::runtime_error line_number=60146 node=longevity-50gb-12h-master-db-node-df57e125-3
2023-11-11T23:52:25.627+00:00 longevity-50gb-12h-master-db-node-df57e125-3      !ERR | scylla[35229]:  [shard  9:comp] sstable - writer failed to close file: std::runtime_error (compress is not supported)
```

This looks like a regression from `5.5.0~dev-20231027.227136ddf54f` but there is a difference in nemeses targets: in `5.5.0~dev-20231108.a4aeef2eb0aa` run the target is the same (node-1) but in `5.5.0~dev-20231027.227136ddf54f` MgmtRestore targeted at node-4 and ModifyTable 
at node-6

## Installation details

Kernel Version: 5.15.0-1049-aws
Scylla version (or git commit hash): `5.5.0~dev-20231108.a4aeef2eb0aa` with build-id `6c90f896983cf138cd171d49f9d406876333f910`

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-df57e125-6 (34.242.221.56 | 10.4.8.195) (shards: 14)
- longevity-50gb-12h-master-db-node-df57e125-5 (54.74.150.110 | 10.4.11.122) (shards: 8)
- longevity-50gb-12h-master-db-node-df57e125-4 (34.242.136.68 | 10.4.8.97) (shards: 10)
- longevity-50gb-12h-master-db-node-df57e125-3 (3.252.147.7 | 10.4.8.72) (shards: 14)
- longevity-50gb-12h-master-db-node-df57e125-2 (52.209.113.142 | 10.4.11.192) (shards: 14)
- longevity-50gb-12h-master-db-node-df57e125-1 (63.33.65.56 | 10.4.9.54) (shards: 8)

OS / Image: `ami-0c5cf87017b2b6cb8` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `df57e125-db71-4926-87d5-1867de178e42`
Test name: `scylla-master/longevity/longevity-150gb-asymmetric-cluster-12h-test`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f6ce1209c6304330f85ffd16f12942c84db7d0d/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor df57e125-db71-4926-87d5-1867de178e42`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=df57e125-db71-4926-87d5-1867de178e42)
- Show all stored logs command: `$ hydra investigate show-logs df57e125-db71-4926-87d5-1867de178e42`

## Logs:
- **db-cluster-df57e125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/db-cluster-df57e125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/db-cluster-df57e125.tar.gz)
- **sct-runner-events-df57e125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/sct-runner-events-df57e125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/sct-runner-events-df57e125.tar.gz)
- **sct-df57e125.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/sct-df57e125.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/sct-df57e125.log.tar.gz)
- **loader-set-df57e125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/loader-set-df57e125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/loader-set-df57e125.tar.gz)
- **monitor-set-df57e125.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/monitor-set-df57e125.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/df57e125-db71-4926-87d5-1867de178e42/20231112_051546/monitor-set-df57e125.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-150gb-asymmetric-cluster-12h-test/28/)
[Argus](https://argus.scylladb.com/test/6a3a708c-caa0-439f-84cd-736b40b517e3/runs?additionalRuns[]=df57e125-db71-4926-87d5-1867de178e42)
</details>

### PR DESCRIPTION
**Pull request by michoecho**
There are two schemas associated with a sstable writer:
the sstable's schema (i.e. the schema of the table at the time when the
sstable object was created), and the writer's schema (equal to the schema
of the reader which is feeding into the writer).

It's easy to mix up the two and break something as a result.

The writer's schema is needed to correctly interpret and serialize the data
passing through the writer, and to populate the on-disk metadata about the
on-disk schema.

The sstables's schema is used to configure some parameters for newly created
sstable, such as bloom filter false positive ratio, or compression.

This series fixes the known mixups between the two — when setting up compression,
and when setting up the bloom filters. 

Fixes #16065

The bug is present in all supported versions, so the patch has to be backported to all of them.

### CODE REVIEW

File: sstables/sstables.cc [hunk 1]
```diff
@@ -1415,10 +1416,13 @@ void sstable::maybe_rebuild_filter_from_index(uint64_t num_partitions, sstring o
         return;
     }
 
+    auto old_filter_ptr = dynamic_cast<utils::filter::bloom_filter*>(_components->filter.get());
+    assert(old_filter_ptr);
+
```
Comment (avikivity) [inline sstables/sstables.cc:1421]: Isn't it better to have on_internal_error here? Crash in test, throw (and maybe recover) in production.

**Comment by avikivity** [comment]
Looks good.

File: sstables/sstables.cc (hunk 1 above)
Comment (michoecho) [reply sstables/sstables.cc:1421]: I leave the decision to you. It's a tradeoff between potentially losing more availability than needed, and potentially continuing to run the program in an uncertain state (and not getting a coredump from it). What we value more is arbitrary.

Do you want an `on_internal_error` here?

Comment (avikivity) [reply sstables/sstables.cc:1421]: I think there's a good chance the system will recover. At least, the operator will be able to take the node down and restart it with fresh schema. So I do want an on_internal_error here.

It reduces our ability to find the bug quickly, but also reduces the chance of a coordinated crash in multiple nodes.

Comment (michoecho) [reply sstables/sstables.cc]: Done. Take a look at commit `sstables: for i_filter downcasts...` again.

**Review by tgrabiec — APPROVED** [review]

**Comment by michoecho** [comment]
Pinging for merge.

**Comment by mykaul** [comment]
> Pinging for merge.

@scylladb/scylla-maint - please consider merging - it fixes failures we've seen in multiple SCT runs (on 5.5, 5.4rc1, 2024.1.7 and others)

**Comment by michoecho** [comment]
> > Pinging for merge.
> 
> @scylladb/scylla-maint - please consider merging - it fixes failures we've seen in multiple SCT runs (on 5.5, 5.4rc1, 2024.1.7 and others)

And more importantly, we saw them in the field.

**Comment by mykaul** [comment]
> > > Pinging for merge.
> > 
> > 
> > @scylladb/scylla-maint - please consider merging - it fixes failures we've seen in multiple SCT runs (on 5.5, 5.4rc1, 2024.1.7 and others)
> 
> And more importantly, we saw them in the field.

Indeed. That was 'and others' above.

File: sstables/mx/writer.cc [hunk 2]
```diff
@@ -1466,7 +1466,7 @@ void writer::consume_end_of_stream() {
 
     _sst._components->statistics.contents[metadata_type::Serialization] = std::make_unique<serialization_header>(std::move(_sst_schema.header));
     seal_statistics(_sst.get_version(), _sst._components->statistics, _collector,
-        _sst._schema->get_partitioner().name(), _schema.bloom_filter_fp_chance(),
+        _sst._schema->get_partitioner().name(), _sst._schema->bloom_filter_fp_chance(),
         _sst._schema, _sst.get_first_decorated_key(), _sst.get_last_decorated_key(), _enc_stats);
```
[the remark this answers is not in the document]
Comment (raphaelsc) [reply sstables/mx/writer.cc:1470]: But it's good that you minimized the amount of changes == decreased chance of surprises when this get backported.

[the remark this answers is not in the document]
Comment (michoecho) [reply sstables/mx/writer.cc:1470]: The only reason I see for having a separate schema for sstables and for writers is that it allows for applying some sstable-specific schema changes faster. For example, it allows you to change bloom filter config or compression (or encryption?) config in the middle of a long streaming or compaction session, and it will be applied to newly-created sstable in that session. I have no idea how useful is that.

(But I should be the one asking you about this. It has been this way for longer than I've been a programmer).

[the remark this answers is not in the document]
Comment (raphaelsc) [reply sstables/mx/writer.cc:1470]: > The only reason I see for having a separate schema for sstables and for writers is that it allows for applying some sstable-specific schema changes faster. For example, it allows you to change bloom filter config or compression (or encryption?) config in the middle of a long streaming or compaction session, and it will be applied to newly-created sstable in that session. I have no idea how useful is that.
> 

My memory doesn't serve me well anymore. Reading streaming consumer, possibly the reason is that we want writer to use same schema of the reader, as columns might be dropped / added. So I think it's for correctness :-)

**Comment by avikivity** [comment]
Agree it should bypass the merge freeze.
