### PR TITLE
cql: process LIMIT for GROUP BY select queries

### LINKED ISSUE #5361: LIMIT doesn't work when using GROUP BY
as part of the effort to cover tests for #2206 , imported tests from C*, and this combination of commands doesn't work, it doesn't fail, but it ignores the LIMIT command:

```
cqlsh:test_paging_with_group_by> SELECT a, b, e, count(b), max(e) FROM test GROUP BY a, b LIMIT 2 ;

 a | b | e  | system.count(b) | system.max(e)
---+---+----+-----------------+---------------
 1 | 2 |  6 |               2 |            12
 1 | 4 | 12 |               2 |            24
 2 | 2 |  6 |               1 |             6
 2 | 4 | 12 |               1 |            12
 4 | 8 | 24 |               1 |            24

(5 rows)
cqlsh:test_paging_with_group_by> DESCRIBE test

CREATE TABLE test_paging_with_group_by.test (
    a int,
    b int,
    c int,
    d int,
    e int,
    PRIMARY KEY (a, b, c, d)
) WITH CLUSTERING ORDER BY (b ASC, c ASC, d ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh:test_paging_with_group_by> DESCRIBE KEYSPACE test_paging_with_group_by 

CREATE KEYSPACE test_paging_with_group_by WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;

CREATE TABLE test_paging_with_group_by.test (
    a int,
    b int,
    c int,
    d int,
    e int,
    PRIMARY KEY (a, b, c, d)
) WITH CLUSTERING ORDER BY (b ASC, c ASC, d ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

### LINKED ISSUE #5362: LIMIT is not doing it right when using GROUP BY
as mentioned on #5361 , this is an effort for testing #2206 , and LIMIT is not behaving as expected (and not accordingly with C*):

```
cqlsh:test_paging_with_group_by> PAGING 1000
Page size: 1000
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 4;

 a | b | c | d
---+---+---+---
 1 | 2 | 1 | 3
 1 | 4 | 2 | 6

(2 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 5;

 a | b | c | d
---+---+---+---
 1 | 2 | 1 | 3
 1 | 4 | 2 | 6
 2 | 2 | 3 | 3

(3 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 3;

 a | b | c | d
---+---+---+---
 1 | 2 | 1 | 3
 1 | 4 | 2 | 6

(2 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 8;

 a | b | c | d
---+---+---+----
 1 | 2 | 1 |  3
 1 | 4 | 2 |  6
 2 | 2 | 3 |  3
 2 | 4 | 3 |  6
 4 | 8 | 2 | 12

(5 rows)
```

### LINKED ISSUE #17237: Limit broken with Group By in Scylla 5.4
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.2
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=1 cores=32 hyperthreading= memory=768GB
Disks: (SSD/HDD, count) NVMe, 9x, RAID-0

After upgrading from Scylla 5.2.14 to 5.4.2, `group by` queries with `limit` stopped limiting the results. I have been able to reproduce the issue with the following `cql`:

```
create table grouping (
  a int,
  b int,
  c text,
  PRIMARY KEY (a, b)
) WITH CLUSTERING ORDER BY (b ASC);
insert into grouping (a,b,c) values (1,2,'testing');
insert into grouping (a,b,c) values (1,3,'three');
insert into grouping (a,b,c) values (2,-1,'negative');
select * from grouping group by a limit 1;
```

Before the upgrade to 5.4.2, the snippet above would give the following results:

```
 a | b | c
---+---+---------
 1 | 2 | testing
```

After the upgrade, it gives the following:

```
 a | b  | c
---+----+----------
 1 |  2 |  testing
 2 | -1 | negative
```

I would expect the functionality of the `limit` statement to remain the same between versions (and have the `select` statement above produce a single output row).

### PR DESCRIPTION
**Pull request by KrzaQ**
This change fixes #17237, fixes #5361 and fixes #5362 by passing the limit value down the call chain in cql3. A test is also added.

fixes #17237
fixes #5361
fixes #5362

The regression happened in 5.4 as we changed the way GROUP BY is processed in 432cb02 - to force aggregation when it is used. The LIMIT value was not passed to aggregations and thus we failed to adhere to it.

W want to backport this fix to 5.4 and 6.0 to have continuous correct results for the test case from #17237

This patch consists of 4 commits:
- fa4225ea0fac2057b7a9976f57dc06bcbd900cd4 - cql3: respect the user-defined page size in aggregate queries - a precondition for this patch to be implementable
- 8fbe69e74dca16ed8832d9a90489ca47ba271d0b - cql3/select_statement: simplify the get_limit function - the `do_get_limit()` function did a lot of legwork that should not be associated with it. This change makes it trivial and makes its callers do additional checks (for unset guards, or for an aggregate query)
- 162828194a2b88c22fbee335894ff045dcc943c9 - cql3: process LIMIT for GROUP BY queries - pass the limit value down the chain and make use of it. This is the actual fix to #17237 
- b3dc6de6d6cda8f5c09b01463bb52f827a6a00b4 - test/cql-pytest: Add test for GROUP BY queries with LIMIT - tests

### CODE REVIEW

**Comment by ptrsmrn** [comment]
The format of the envelope is usually:
> ... description...
> 
> Fixes: https://github.com/scylladb/scylladb/issues/17237

File: cql3/statements/select_statement.cc [hunk 1]
```diff
@@ -462,7 +462,13 @@ select_statement::execute_without_checking_exception_message_aggregate_or_paged(
             state, options, command, std::move(key_ranges), _restrictions_need_filtering ? _restrictions : nullptr);
 
     if (aggregate || nonpaged_filtering) {
-        auto builder = cql3::selection::result_set_builder(*_selection, now, *_group_by_cell_indices);
+        std::optional<uint64_t> limit;
+        if (_limit) {
+            auto x = expr::evaluate(*_limit, options);
+            auto l = x.view().validate_and_deserialize<int32_t>(*int32_type);
```
Comment (ptrsmrn) [inline cql3/statements/select_statement.cc:468]: `limit` is defined as `uint64_t` but is being deserialized to `int32_t`, is that ok?
I mean, I don't expect negative values in limit, I also don't expect it to be such a huge number to cause an overflow, but one, you never know, two, sanitizers may fail this piece of code.

File: test/cql-pytest/test_group_by_limit.py [hunk 2]
```diff
@@ -0,0 +1,64 @@
+#
+# Copyright (C) 2022-present ScyllaDB
+#
+# SPDX-License-Identifier: AGPL-3.0-or-later
+#
+import asyncio
+import time
+import pytest
+import logging
+from cassandra.protocol import InvalidRequest, ReadFailure                         # type: ignore
```
Comment (ptrsmrn) [inline test/cql-pytest/test_group_by_limit.py:10]: What this `# type: ignore` does an is it needed?

File: test/cql-pytest/test_group_by_limit.py [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+from cassandra.query import SimpleStatement                                        # type: ignore
+
+
+logger = logging.getLogger(__name__)
+
+@pytest.mark.asyncio
+async def test_add_index(cql):
+    assert cql is not None
+    cql.execute("create keyspace ks with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};")
```
Comment (ptrsmrn) [inline test/cql-pytest/test_group_by_limit.py:19]: Please switch to NetworkTopology and use named DC, we want to migrate away and do not test SimpleStrategy + replication_factor tag is most likely going to be abandoned when switching to tablets.

File: test/cql-pytest/test_group_by_limit.py [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+    cql.set_keyspace("ks")
+    cql.execute("""create table grouping (
+        a int,
+        b int,
+        c int,
+        PRIMARY KEY (a, b)
```
Comment (ptrsmrn) [inline test/cql-pytest/test_group_by_limit.py:25]: The words case is mixed, sometimes CQL keywords are small letters, sometimes capital letters, please keep everything upper case for simplicity.

File: test/cql-pytest/test_group_by_limit.py [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+import pytest
+import logging
+from cassandra.protocol import InvalidRequest, ReadFailure                         # type: ignore
+from cassandra.query import SimpleStatement                                        # type: ignore
+
+
+logger = logging.getLogger(__name__)
+
+@pytest.mark.asyncio
+async def test_add_index(cql):
```
Comment (ptrsmrn) [inline test/cql-pytest/test_group_by_limit.py:17]: I guess the name was copy-pasted from some other test and needs to be adjusted.

Comment (ptrsmrn) [reply test/cql-pytest/test_group_by_limit.py:17]: Also, please provide an in-source description of what the test does, it's not immediately apparent why choosing some prime numbers etc. Ideally you'd wrap parts of the code into well-named functions/malbdas.

File: test/cql-pytest/test_group_by_limit.py [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+
+    assert len(ret) == 1    
+    assert ret.pop()[0] in [29, 31, 37, 41]
+
+    ret = set(cql.execute("select COUNT(*) from grouping group by a"))
+
+    assert len(ret) == 4
+    assert set([29, 31, 37, 41]) == set([x[0] for x in ret])
+
+    ret = set(cql.execute("select COUNT(*) from grouping group by a limit 1"))
```
Comment (ptrsmrn) [inline test/cql-pytest/test_group_by_limit.py:58]: how about trying `limit` with other value than `1`?

Comment (ptrsmrn) [reply test/cql-pytest/test_group_by_limit.py:58]: Maybe in a loop starting from 1 to N? Where N = all records. Is `limit 0` a valid option?

File: test/cql-pytest/test_group_by_limit.py (hunk 3 above)
Comment (nyh) [reply test/cql-pytest/test_group_by_limit.py:19]: You don't need to do ANY OF THAT. This test doesn't need its own keyspace and can use the existing keyspace. Please take a look at existing cql-pytest tests and read test/cql-pytest/README.md to get a feel for this test framework, which focuses on quick tests that not only don't need to create a cluster for each test, it almost never needs to create a keyspace and often not even a table for each test (and several test can share the same table).

**Review by nyh — CHANGES_REQUESTED** [review]

**Comment by nyh** [comment]
> @nyh I removed the separate test file, added a test case and removed a four xfail marks.

Thanks! I'll review this PR later. But in parallel, please consider also the other tests and dtests I mentioned in https://github.com/scylladb/scylladb/issues/5361#issuecomment-1459989637, and whether or not this PR also Fixes https://github.com/scylladb/scylladb/issues/5361 - and if not why not and what remains and why.

**Comment by mykaul** [comment]
> No backport seems necessary.

@KrzaQ - why not?

**Comment by nyh** [comment]
> > No backport seems necessary.
> 
> @KrzaQ - why not?

I think that actually a backport to 5.4 and 6.0 is very important - this is a 5.4 regression, and the whole point was to undo the regression. It's sad we didn't fix it faster, but we definitely need to fix it in 6.0 and better also do it in new releases to 5.4.

A backport to 5.2 is not needed because: 1. the regression part wasn't in 5.2, and, 2. although it probably does solve additional problems that existed in 5.2 - see https://github.com/scylladb/scylladb/issues/5361 - these are old news and 5.2 is on its way out so we shouldn't matter.

**Comment by nyh** [comment]
> This change fixes #17237 by passing the limit value down the call chain in cql3. A test is also added.

Please consider lengthening this description of what was the bug that is being fixed by this PR. You should summarize what was the old bug (a combination of LIMIT, GROUP BY and aggregation? please give an example what used to break and how), and what is the new regression in 5.4 (LIMIT + GROUP BY queries that didn't have aggregation now have aggregation internally and started to break).

Without explaining this, readers of this PR will not be able to appreciate what exactly was being fixed here, how serious it was, and whether a backport is important or not. Sure, they can go into the issue you link and start to read all the comments, but we usually expect the author of the PR to do this work for us - and summarize the important parts of the issue that is being fixed without other people needing to read dozens of comments to understand this on their own.


> 
> No backport seems necessary.

**Comment by nyh** [comment]
IIUC, what never worked was the combination of the **three** features: limit, group by and aggregation. The combination of just the first two features did work correctly and regressed in 5.4, when we started fo use aggregation internally to implement GROUP BY.
So users of the combination of just two features did see something which used to work stop working.

**Comment by nyh** [comment]
@KrzaQ now you can see above which dtests got "broken" by this patch and will need to be fixed before we can merge this PR :-(
Note that I put "broken" in quotes - as I noted elsewhere, I believe that we actually took correct dtests from Cassandra, and when they failed on Scylla, we modified the tests to accept the incorrect situation (with a comment referring to https://github.com/scylladb/scylladb/issues/5361)... This mess will need to be undone. I propose the following:
1. Update those dtests to be correct and not to enshrine the wrongness of #5361.
2. Verify that the fixed tests for correctly with your patch.
3. Add a "requires 5361" tag to these tests, so they will be skipped before 5361 is fixed.

After we do those changes to dtest, the tests in this PR will start passing (easy, all the failing tests will be skipped...), but more importantly - when we close 5361 they will stop being skipped, and will pass (this is why you need to check that they would pass, in advance).

File: test/cql-pytest/test_group_by.py [hunk 7]
```diff
@@ -38,13 +38,47 @@ def test_group_by_partition(cql, table1):
...
+        for i in range(1,4):
+            query_result = set(map(lambda x: x[0], cql.execute(f'SELECT a FROM {table} GROUP BY a LIMIT {i}')))
+            # We should get only {i} rows, one of the partition keys
+            assert len(query_result) == i
+            assert query_result.issubset({29, 31, 37, 41})
+        # COUNT should return proper count values (e.g. 29 for partition key 29)
+        query_result = list(cql.execute(f'SELECT COUNT(a) FROM {table} GROUP BY a'))
+        # We should get 4 rows, one for each partition key
+        assert len(query_result) == 4
+        assert {29, 31, 37, 41} == set(map(lambda x: x[0], query_result))
```
Comment (nyh) [inline test/cql-pytest/test_group_by.py:74]: The more pythonic (and nicer) syntax of this lambda thing is "list comprehension":

```python
assert {29, 31, 37, 41} == {x[0] for x in query_result}
```

Comment (nyh) [inline test/cql-pytest/test_group_by.py:74]: Nitpick: the fact that you used exactly the same count and partition key somewhat lowers the power of this test, because if the code mistakenly returns the partition key instead of the count, your test misses that!

File: cql3/statements/select_statement.cc (hunk 1 above)
Comment (avikivity) [reply cql3/statements/select_statement.cc:468]: Fail the query on a negative limit. Perhaps we should also fail on limit = 0.

File: test/cql-pytest/test_group_by.py [hunk 8]
```diff
@@ -38,13 +38,47 @@ def test_group_by_partition(cql, table1):
...
+        # Adding a LIMIT should be honored.
+        for i in range(1,4):
+            query_result = set(map(lambda x: x[0], cql.execute(f'SELECT COUNT(a) FROM {table} GROUP BY a LIMIT {i}')))
```
Comment (nyh) [inline test/cql-pytest/test_group_by.py:77]: Again, list comprehension is nicer.
If your test uses the name "query_result" twice please consider reducing the confusion by not using two different types (in one of them you put the list, the other is a set, it's just confusing for readers).

File: cql3/statements/select_statement.cc (hunk 1 above)
Comment (avikivity) [reply cql3/statements/select_statement.cc:468]:
```
avi=# select * from t1 limit 2;
 x | y 
---+---
 1 |  
 5 | 4
(2 rows)

avi=# select * from t1 limit -1;
ERROR:  LIMIT must not be negative
avi=# select * from t1 limit 0;
 x | y 
---+---
(0 rows)
```

Comment (avikivity) [reply cql3/statements/select_statement.cc:468]: There's a get_limit() function that does this correctly.

Comment (avikivity) [reply cql3/statements/select_statement.cc:468]: and, in fact, do_execute() already calls it.

**Review by nyh — CHANGES_REQUESTED** [review]
In addiition to the specific comments I left, please make more definite statement which issues this PR fixes. For example, does it, or does it not, fix #5361? If it does say that (not that maybe it fixes). But also "git grep" "#5361" in the cql-pytest directory (including subdirectories) and make sure **all** tests labeled with that issue got fixed. If they didn't, we need to know why and think what to do (if a small part of the issue remains, maybe we need a new issue to replace it). In any case, please explain in the commit message what you did and which issues were fixed (not "maybe" fixed) and that you made sure to look at all tests referring to those issues.

File: cql3/statements/select_statement.cc (hunk 1 above)
Comment (nyh) [reply cql3/statements/select_statement.cc:468]: Exactly, I mentioned select_statement::get_limit() in my comment above, and it does all the right conversions and checks. I also said I assume we already call it, so I wonder why we found ourselves needing to call it again.

Comment (nyh) [reply cql3/statements/select_statement.cc:468]: What do you mean it doesn't yield the limit value? What does it return? It seems you copied most of its code already (and then forgot you copied the right type ;-)), so it should work...

Comment (avikivity) [reply cql3/statements/select_statement.cc:468]: btw, what happens when paging? If the limit is N and we return R<N rows, the new limit should be N-R.

query_pager deals with it, but the logic is so complicated, I wasn't able to make sense of it.

**Comment by kostja** [comment]
@KrzaQ please fix the limit to consistently int64 data type in a pre-requisite patch. Please add a test for min and max values allowed for the limit clause. 
Please add a test for DISTINCT.
It seems PER PARTITION LIMIT and LIMIT are allowed to go together, please add a test they work correctly.
Can I have PER PARTITION LIMIT 0 ? In that case, is it considered an existing group which impacts the LIMIT? 

Please have a test that adds BYPASS CACHE. 

The fix itself should work on the builder level, stopping the production of the result set as soon as the limit is reached. Your fix, as it was rightfully pointed out, likely won't work with paging. BTW, you could add a test for paging in our testing framework. Please use a smallish page size - like 1, 2, 5 rows per page (default_fetch_size). 

Overall @nyh I think there is not much point to tidy up the style unless there is a fix that is having a proper computational complexity.

**Review by kostja — CHANGES_REQUESTED** [review]
Please explain in the commit comment how the current group by is execution, on the algorithmic level, and how your fix is addressing the limit problem. 

Something along the following lines:

In ScyllaDB, using GROUP BY is restricted only to grouping over the primary key parts, actually even a prefix of the primary key. This simplifies the group by implementation, since only a single partition can be an input of the group, and as long as we can fully get the single partition data from a node before switching to the next partition, we can process one group at a time.

The query itself is not parallelized and is executed on a single coordinator which then directs the affected nodes to stream partitions to it. Therefore, there is only one place where we need to apply the limit.

The rows are streamed into the <> class, in which the group is built, and when an aggregate row is produced, it is appended to an instance of <> class. The result set does not need to be fully materialized before it is sent to the client, since ORDER BY over non-primary key columns is also not allowed. 

The issue with the code was tha tthe limit clause was simply not passed to the execution layer and hence not taken into account by it.

The fix is to properly pass the limit to the execution layer and abort group materialization early, as soon as enough groups were built and sent to the client. (your fix currently doesn't do that).

**Comment by nyh** [comment]
> @KrzaQ please fix the limit to consistently int64 data type in a pre-requisite patch. Please add a test for min and max values allowed for the limit clause.

Please consider why you want to change this aspect of the code. Does Cassandra allow more than 32 bit limits? Do we want to allow it? I agree we can change it, but I think it should be a completely separate PR, with its own justification.

> Please add a test for DISTINCT. It seems PER PARTITION LIMIT and LIMIT are allowed to go together, please add a test they work correctly. Can I have PER PARTITION LIMIT 0 ? In that case, is it considered an existing group which impacts the LIMIT?

Before you start writing more tests please look at which tests we already have. In particular, we know that like there are  two known bugs of aggregations+group by+limit that this patch is fixing (#5631 and #5632), there are similar bugs for PER PARTITION LIMIT (#5363) and we also have tests for this in test/cql-pytest/test_group_by.py. We need to fix all these bugs - but not necessarily in the same PR.

We also have tests for both PER PARTITION LIMIT and LIMIT in the same query, I don't remember if together with aggregation and group by. Please try searching before writing more tests, but it's possible that tests for some cases are missing and should be added.

> Please have a test that adds BYPASS CACHE.

We shouldn't add additional confounding variables to tests just because we can. Why would BYPASS CACHE make any difference to code in **this** level? This code assumes that the reading of the data is correct.

> The fix itself should work on the builder level, stopping the production of the result set as soon as the limit is reached. Your fix, as it was rightfully pointed out, likely won't work with paging. BTW, you could add a test for paging in our testing framework. Please use a smallish page size - like 1, 2, 5 rows per page (default_fetch_size).

We have many tests with paging, grep "fetch_size" in test/cql-pytest. Obviously you need to check paging together with the weird combination that you're doing (e.g., we have several xfailing tests for secondary-index scans that have problems with paging).

> Overall @nyh I think there is not much point to tidy up the style unless there is a fix that is having a proper computational complexity.

I don't think my comments amounted to being about "tidying up the style".

**Comment by kostja** [comment]
> > @KrzaQ please fix the limit to consistently int64 data type in a pre-requisite patch. Please add a test for min and max values allowed for the limit clause.
> 
> Please consider why you want to change this aspect of the code. Does Cassandra allow more than 32 bit limits? Do we want to allow it? I agree we can change it, but I think it should be a completely separate PR, with its own justification.

I agree about a separate PR. I agree we should not allow 64 bit limits. But we should consistently use 64-bit type going forward. 64-bit type can safely store a 32-bit limit and that would resolve ambiguity about which type to use and whether or not the used type is chosen safely.

**Comment by kostja** [comment]
> > Please add a test for DISTINCT. It seems PER PARTITION LIMIT and LIMIT are allowed to go together, please add a test they work correctly. Can I have PER PARTITION LIMIT 0 ? In that case, is it considered an existing group which impacts the LIMIT?
> 
> Before you start writing more tests please look at which tests we already have. In particular, we know that like there are two known bugs of aggregations+group by+limit that this patch is fixing (#5631 and #5632), there are similar bugs for PER PARTITION LIMIT (#5363) and we also have tests for this in test/cql-pytest/test_group_by.py. We need to fix all these bugs - but not necessarily in the same PR.

Ouch. OK, given per partition row limit + group by are broken, this can be moved out. 


> 
> We also have tests for both PER PARTITION LIMIT and LIMIT in the same query, I don't remember if together with aggregation and group by. Please try searching before writing more tests, but it's possible that tests for some cases are missing and should be added.
> 
> > Please have a test that adds BYPASS CACHE.
> 
> We shouldn't add additional confounding variables to tests just because we can. Why would BYPASS CACHE make any difference to code in **this** level? This code assumes that the reading of the data is correct.

If you can point at another test which tests BYPASS CACHE + LIMIT + GROUP BY, then perhaps we could make such assumption. Otherwise we shouldn't, any combination of features needs to have functional coverage.

> > Overall @nyh I think there is not much point to tidy up the style unless there is a fix that is having a proper computational complexity.
> I don't think my comments amounted to being about "tidying up the style".

I agree, but some of them were, and my point is that there @KrzaQ should not spend time addressing those before the larger issue (how the patch implements the limit - during or after materialization) is addressed.

**Comment by nyh** [comment]
> Overall @nyh I think there is not much point to tidy up the style unless there is a fix that is having a proper computational complexity.

Please note that although some of my comments were about "style", none of them were about the style of code where I had doubts about (does paging work? etc.) but about the style of the tests - which 1. will remain even if the code itself is improved, 2. since he'll probably need to write more tests, any comments I make about the tests will be relevant also to the new tests.

In general, the logic of LIMIT, GROUP BY, paging and friends is some of the most convoluted code we have and it's very hard to fix correctly and you need to understand well what's going on and which tests to write before doing it, and if you don't do this step properly, you are likely to produce an incorrect fix. A good example is https://github.com/scylladb/scylladb/issues/10649, about a combination LIMIT, filtering and secondary index. I very quickly hacked a fix, but before publishing it I wrote additional tests for more elaborate cases and discovered that while my fix was fixing the first test I wrote, it wasn't fixing other tests.

**Comment by nyh** [comment]
> If you can point at another test which tests BYPASS CACHE + LIMIT + GROUP BY, then perhaps we could make such assumption. Otherwise we shouldn't, any combination of features needs to have functional coverage.

If you want to argue for combining **BYPASS CACHE** with those other features (LIMIT, GROUP BY, etc.) in the same test, what you need to convince me that there is relevant and direct interaction between the two features. After all, someone can also claim that we need to check the LIMIT feature both on iouring and epoll, because after all, the query reads the data from disk, and the IO implementation is slightly different for these two polling mechanism. If the modified LIMIT code ends up being directly related to the cache vs. memtable vs. sstable code, then I agree, but I don't see this right now (as far as I understand).

I agree that other features, namely, 1. LIMIT, 2. PER PARTITION LIMIT, 3. paging, 4. GROUP BY, 5. aggregation, 6. secondary index, are all very strongly intertwined and you can get various combinations of those features in one query and they can break each other, and this is why we already have tests for many of  these features combined together (I wrote many of them myself, and translated many others from Cassandra, and I think we also have some in C++), but it is quite likely I missed some combinations. I just don't get yet how BYPASS CACHE is part of this story, but maybe you can convince me.

In general, I believe that testing **irrelevant** things is not a victimless crime - when a test checks irrelevant things, it takes away the attention of both the original developer and the reviewers, and they are more likely to miss the fact that the test is missing important things. I've seen this many times in the past with dtest, where so much effort was put into writing a test that uses some new feature X in parallel with adding nodes and huge number of rows and materialized views and god knows what, that actually much of the specific functionality introduced in the new feature was not covered, and the corner cases of the new feature were not covered.

File: cql3/statements/select_statement.cc (hunk 1 above)
Comment (kostja) [reply cql3/statements/select_statement.cc:468]: I see no generic reason why it would be unacceptable. It seems to linger from ancient times. 
Let's git blame this fragment to make sure it's not been added intentionally for any specific reason that is still relevant, try to remove it and see what tests fail.

**Comment by kostja** [comment]
> I would like to limit the scope of this fix as much as possible and close the ticket(s) referenced in the top message.
> 
> My understanding is as follows:
> 
> 1. Create a separate PR to change the limit value type to `int64_t`, while limiting it to 31 bit values
> 2. Move the limitation to the materialization phase. I'm concerned about this, because when I attempted it the last time, `SELECT COUNT(x) FROM table GROUP BY x LIMIT 1` returned incorrect values. But I understand it was a quality of implementation issue on my end.
> 3. Add tests for more cases (if they're not covered already), splitting them into more test cases, specifically:
>    
>    * DISTINCT
>    * BYPASS CACHE
>    * Do not test PER PARTITION LIMIT, because [PER PARTITION LIMIT doesn't work right when using GROUP BY #5363](https://github.com/scylladb/scylladb/issues/5363)
> 4. Address comments to the existing tests
> 
> Personally, I would like to mark tests that would've failed prior to this patch and keep failing not as `xfail` and leave for the future to avoid scope creep, which I'm feeling is already happening.

I am always happy when correct patches get merged. The biggest correctness concern about this patch is whether or not it works with paging. If it doesn't, you'll *have* to switch to do 2. to address that. I suggest you focus on testing this first. With that issue resolved, I'm entirely OK if my comments are addressed separately.

**Comment by nyh** [comment]
> Personally, I would like to mark tests that would've failed prior to this patch and keep failing not as `xfail` and leave for the future to avoid scope creep, which I'm feeling is already happening.

I don't understand what you mean... If any of the existing tests that have https://github.com/scylladb/scylladb/issues/17237, https://github.com/scylladb/scylladb/issues/5361 and https://github.com/scylladb/scylladb/issues/5362 listed in comments and/or xfail reasons continue to fail after your patch, it means that either 1. your patch is wrong, or 2. one of these tests checks something beyond the original problem. In either case, you'll need to do something: In case 1 you'll need to rethink your solution, in case 2 you'll need to understand exactly what remains broken, and open a new issue about it (and change the comments in the still-failing test, etc.).

> Add tests for more cases (if they're not covered already), splitting them into more test cases, specifically:   DISTINCT    BYPASS CACHE

Please spend some time reading the existing tests and what they cover, both in test/cql-pytest and test/cql-pytest/cassandra_tests - they are highly commented and already cover a lot of cases that I encountered the last time I was debugging issues in this area. Just to add another example I didn't mention previously, test_distinct.py contains a lot of tests for DISTINCT (which you mentioned above) with LIMIT, GROUP BY, COUNT and LIMIT. One test is even xfailing because of #5361 and will hopefully be fixed by your patch.

The story about BYPASS CACHE - sorry, I still don't understand how it's relevant, and it looks like it adds only confusion to this discussion.

**Comment by avikivity** [comment]
> I would like to limit the scope of this fix as much as possible and close the ticket(s) referenced in the top message.
> 
> My understanding is as follows:
> 
> 1. Create a separate PR to change the limit value type to `int64_t`, while limiting it to 31 bit values

You can't change that, it's exported to clients in prepared statements.

LIMIT > 2^31 is not practical anyway. Typical values are < 1000.

> 2. Move the limitation to the materialization phase. I'm concerned about this, because when I attempted it the last time, `SELECT COUNT(x) FROM table GROUP BY x LIMIT 1` returned incorrect values. But I understand it was a quality of implementation issue on my end.
> 3. Add tests for more cases (if they're not covered already), splitting them into more test cases, specifically:
>    
>    * DISTINCT
>    * BYPASS CACHE
>    * Do not test PER PARTITION LIMIT, because [PER PARTITION LIMIT doesn't work right when using GROUP BY #5363](https://github.com/scylladb/scylladb/issues/5363)
> 4. Address comments to the existing tests
> 
> Personally, I would like to mark tests that would've failed prior to this patch and keep failing not as `xfail` and leave for the future to avoid scope creep, which I'm feeling is already happening.

LIMIT has interaction with paging. Test is with page size < limit.

**Comment by nyh** [comment]
> If I were to add a new test (not covered by current test cases) and it failed, and it also failed without this patchset, I would not want to bring it under the scope of this PR.

If you create a new test that **fails**, then it depends:
1. If it has nothing to do with this PR (e.g., you found a new bug in SELECT DISTINCT that has nothing to do with GROUP BY's support for aggregation), definitely this can be a separate PR (and, you should open an issue!)
2. If you thought of a new test case that is directly relevant to this PR, for example LIMIT+GROUP BY but with paging, and it fails, then it means your patch is wrong and only happened to work in the specific tests we had. What's the point of leaving this test (and a fix...) out of this PR?

There's something I want to clarify:

The reason why this fix became very important after we neglected #5361 for so many years is that @avikivity's change to use aggregation in any GROUP BY query suddenly made it important. If we wanted a quick fix without fixing aggregation, perhaps the "quick" way to fix it would have been to somehow (I'm not even sure if it's possible) undo Avi's change, and make aggregation-less requests remain free of aggregation. But as long as we do have these aggregations, we need to fix the bugs in aggregation, all the bugs which can break the GROUP BY-without-aggregation which used to work but now uses aggregation.

File: cql3/selection/selection.cc [hunk 9]
```diff
@@ -577,8 +579,10 @@ void result_set_builder::flush_selectors() {
         // handled by process_current_row
         return;
     }
-    _result_set->add_row(_selectors->get_output_row());
-    _selectors->reset();
+    if (!_limit || _result_set->size() < *_limit) {
```
Comment (kostja) [inline cql3/selection/selection.cc:582]: This is better now, but I still don't get how does your patch short-cut fetching the data from the nodes once limit is reached? I see that this patch does produce a correct result set, but it doesn't stop the readers, since the result set builder will continue munching the input just will be sending it to /dev/null thanks to this change after generating LIMIT rows. But the goal is also to short-cut the execution and return the result set immediately.

File: test/cql-pytest/test_group_by.py [hunk 10]
```diff
@@ -38,13 +38,47 @@ def test_group_by_partition(cql, table1):
...
+            # We should get only {i} rows, one of the partition keys
+            assert len(query_result) == i
+            assert query_result.issubset({29, 31, 37, 41})
+
```
Comment (kostja) [inline test/cql-pytest/test_group_by.py:81]: @KrzaQ I thought you'd add a test for selection with paging; did you find an existing one?

**Comment by nyh** [comment]
> This change fixes #17237, #5361 and #5362 by passing the limit value down the call chain in cql3.

I'm not sure github understands this syntax. To be safer (?) maybe you should add a separate fixes string for each issue (usually on a separate line each).

**Comment by ptrsmrn** [comment]
> I don't understand. It shows the proper issues to me when I hover.

E.g. https://github.com/scylladb/scylladb/issues/17237 has your PR linked to it (attached pic), but https://github.com/scylladb/scylladb/issues/5361 doesn't. Ideally all issues fixed by this PR would have it linked.
image

File: test/cql-pytest/test_group_by.py (hunk 10 above)
Comment (kostja) [reply test/cql-pytest/test_group_by.py:81]: My concern is that the test you're referencing is a single -node test, and in your added test you install multiple nodes. It's worth having an extra test which uses paging + multiple nodes given the cost of setting up a multi-node cluster is high.

**Comment by avikivity** [comment]
> I don't understand. It shows the proper issues to me when I hover.

Please use a separate Fixes line for each issue, we have automation parsing it and it doesn't appreciate creativity.

File: cql3/selection/selection.hh [hunk 11]
```diff
@@ -172,6 +172,7 @@ private:
     std::unique_ptr<result_set> _result_set;
     std::unique_ptr<selectors> _selectors;
     const std::vector<size_t> _group_by_cell_indices; ///< Indices in \c current of cells holding GROUP BY values.
+    const std::optional<uint64_t> _limit; ///< Maximum number of rows to return.
```
Comment (avikivity) [inline cql3/selection/selection.hh:175]: We may way well drop the optional and set the limit to numeric_limit::max() if it's  not specified.

File: cql3/statements/select_statement.cc (hunk 1 above)
Comment (avikivity) [reply cql3/statements/select_statement.cc:468]: I think the fragility with LIMIT is due to:
 - where it's applied: as rows are read, after filtering, or after aggregation? (should be the latter)
 - how it's passed around to the client and back during paging

Comment (avikivity) [reply cql3/statements/select_statement.cc:468]: It's not good to have yet another way to compute the limit.

Maybe you can change the condition in do_get_limit() to more exactly match the circumstances for your fix, and add a comment to explain it.

**Review by nyh — CHANGES_REQUESTED** [review]

**Comment by kostja** [comment]
* nyh ***@***.***> [24/06/19 23:31]:
> -    _result_set->add_row(_selectors->get_output_row());
> -    _selectors->reset();
> +    if (!_limit || _result_set->size() < *_limit) {
> 
> If I understand correctly, this patch changes some very generic
> code that isn't at all specific to GROUP BY or aggregation.
> Basically it allows the low-level code to just read 1000 rows
> instead of the requested LIMIT=10 and then, as a post-processing
> stage, it will drop all of them after the first 10. Which makes
> sense, but I thought we already had this post-processing stage
> somewhere, didn't we? I'm worried that maybe you are sweeping
> the bug under the carpet, and maybe in this - or completely
> different case - we might be be doing a lot of work we don't
> need to do and then dropping and everything looks correct but it
> isn't. Moreover, we can hide LIMIT-related bugs in other code -
> not just GROUP BY or aggregation - in this way, which is kind of
> scary.
> It is **possible** we have no other option in some cases - that
> in some cases we have no choice but to read too much and then
> cut the results. We actually already do this in some cases
> (e.g., "IN" queries) IIRC. But the question is whether we really
> need to do this for aggregations (issues 5361 and 5362), and
> even more definitely - for the silly do-nothing aggregation we
> added in 17237.

I believe you're misreading the patch. It needs to stop early both
the aggregation pipeline and the paging. You'r elooking at the
paging side of the things, but the aggregation pipeline is
chekcing the limit as well. This is what I asked for in one of the
earlier reviews.


-- 
Konstantin Osipov, Moscow, Russia

**Comment by nyh** [comment]
> I believe you're misreading the patch. It needs to stop early both the aggregation pipeline and the paging. You'r elooking at the paging side of the things, but the aggregation pipeline is chekcing the limit as well. This is what I asked for in one of the earlier reviews.

I'm afraid I still I don't understand. Where is the change to the "aggregation pipeline"?
What I see is changes to the generic "result_set_builder" code, which unless I'm missing something is used in every case, not just group by, aggregation, and so on.

**Comment by kostja** [comment]
> > I believe you're misreading the patch. It needs to stop early both the aggregation pipeline and the paging. You'r elooking at the paging side of the things, but the aggregation pipeline is chekcing the limit as well. This is what I asked for in one of the earlier reviews.
> 
> I'm afraid I still I don't understand. Where is the change to the "aggregation pipeline"? What I see is changes to the generic "result_set_builder" code, which unless I'm missing something is used in every case, not just group by, aggregation, and so on.

Yes, result set builder is the class doing the aggregation, so it stops generating new rows once it's built LIMIT rows.

**Comment by nyh** [comment]
> Yes, result set builder is the class doing the aggregation, so it stops generating new rows once it's built LIMIT rows.

I know that, but worried me is that before we had this regression, namely before GROUP BY started to use that do-nothing "aggregation", something implemented the LIMIT correctly. Where was that limit imposed and how did we lose it? I don't want the lower level to need to read 1 MB of rows of a partition (our hard-coded limit) and then return the first 10 rows (if LIMIT=10), if there's a way not to do this. Note that I might be missing something important - I feel very rusty in understanding this code.

**Comment by kostja** [comment]
* nyh ***@***.***> [24/06/20 00:48]:
> I know that, but worried me is that before we had this
> regression, namely before GROUP BY started to use that
> do-nothing "aggregation", something implemented the LIMIT
> correctly. Where was that limit imposed and how did we lose it?
> I don't want the lower level to need to read 1 MB of rows of a
> partition (our hard-coded limit) and then return the first 10
> rows (if LIMIT=10), if there's a way not to do this. Note that I
> might be missing something important - I feel very rusty in
> understanding this code.

If aggregation is in place you can't know how many rows you may
need to read from the partition, paging or not, to satisfy the
limit. Depending on the number of duplicates in a group you may
have 1 or a million rows collapsing into a single aggregate row. 

We could of course make an extrapolation based on statistical
data, which we don't collect, so ... our best bet is to read rows
with paging and stop the pipeline as soon as limit is reached.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by nyh** [comment]
> If aggregation is in place you can't know how many rows you may need to read from the partition, paging or not, to satisfy the limit.

This is a good point. 
I am still puzzled how this worked before the regression. Somehow the LIMIT did work correctly when GROUP BY had its own implementation that didn't use aggregation. How did it work?

**Comment by nyh** [comment]
Anyway, @kostja @KrzaQ the main reason why I marked this version of the PR "request changes" wasn't that I'm sure there is a specific bug, but that I didn't feel sure that the statement "mark several older failing tests as passing now" claimed that **all** tests related to LIMIT started to pass, and if not, why not.

I think I want to spend some time today to prepare a new test file, dedicated to LIMIT and all its edge cases that I can consider, and see what is missing from those tests that we already have, and then we'll see if the new patch really solves all the LIMIT problems (without secondary index) or if there's a bug, maybe causes new problems.

**Comment by nyh** [comment]
I just realized something very surprising: If you look at test_group_by.py, the tests test_group_by_clustering_prefix_with_limit and test_group_by_clustering_prefix_with_pplimit claim that when these tests were written and https://github.com/scylladb/scylladb/issues/5362 and https://github.com/scylladb/scylladb/issues/5363 were opened, LIMIT (and PER PARTITION LIMIT) could return **fewer** rows than the LIMIT.

But today, this isn't the case! These failing tests all fail by returning **more** than the LIMIT rows, not fewer!

I don't know how or when this was changed. Very very strange.
But it explains how your patch - which IIUC just truncates the result set at positition "LIMIT" - solves these bugs. It couldn't have possible solved a bug that returned too few results, but it seems these bugs no longer exist. Very strange.

File: test/cql-pytest/test_group_by.py (hunk 10 above)
Comment (nyh) [reply test/cql-pytest/test_group_by.py:81]: @KrzaQ I looked at the test you referenced (a test translated from Cassandra unit tests), and although the test is called testSelectCountPaging, its actual code doesn't do any paging! It uses a secondary index, to further complicate things, but it doesn't do paging. It also refers to https://issues.apache.org/jira/browse/CASSANDRA-6579, which has nothing to do with paging.

I'll send a PR in a few minutes with additional tests, including one with paging.

@kostja, yes, all those tests are single node. In theory they can miss bugs that have to do with how reconciliation happens on a coordinator, or how a coordinator sends a request with a LIMIT to replicas. That's an interesting thing to check: E.g., what happens if two replicas have slightly different rows, and I run on a coordinator a SELECT with LIMIT 10, is it possible that each of the different nodes returns a different set of 10 results and together more than 10 results are created? Is the opposite possible - one replica returns 10 results but because of a tombstone from another replica, the final results will be fewer than 10? It's definitely worthwhile writing new tests for these things in the topology framework. But it doesn't replace the single-node tests.

P.S. The idea that "the cost of setting up a multi-node cluster is high" hurt dtest considerably, and now hurts the topology framework. We should be able to create a 3-node cluster once, and run hundreds of tests on it. Just like in the 1-node tests in cql-pytest. https://github.com/scylladb/scylladb/issues/16478 should be done to make all of this efficient.

**Comment by nyh** [comment]
I added in https://github.com/scylladb/scylladb/pull/19392 additional tests for LIMIT - some basic ones and one involving LIMIT, GROUP BY and paging, please test your patch with them as well.

The more I look into the new version of your patch - significantly simplified over the previous versions - the less I can argue with it and the more I think it is correct. The strange thing is: It seems that although #5362 originally reported TOO FEW results (this is how it differered from #5361, if I remember correctly), today this is no longer the case and we get too many results, and your new code truncates it so it won't return too many. This is lucky, because your new code couldn't fix any bug that involved returning too _few_ rows. 

I'm still worried that it can hide performance bugs - e.g., imagine a simple "SELECT ... LIMIT 10" reading 1MB of data instead of just 10 rows, and we won't notice it, because your new code will take the 1MB of results and trim everything after the first 10. But I guess we should write tests for this (perhaps using metrics of some sort), and then we won't have such bugs.

**Comment by nyh** [comment]
> > I added in #19392 additional tests for LIMIT - some basic ones and one involving LIMIT, GROUP BY and paging, please test your patch with them as well.
> > @nyh It seems my fix fails this test, though I don't understand it. It fails on this line:
> 
> ```python
> assert len(r.current_rows) == page_size
> ```
> 
> Removing it makes the test pass.
> 
> After adding a few logs, I see the following:
> 
> > WARNING  test_group_by:test_group_by.py:129 page_size: 1, current_rows: 1, limit: 1
> > WARNING  test_group_by:test_group_by.py:129 page_size: 1, current_rows: 2, limit: 2
> > WARNING  test_group_by:test_group_by.py:129 page_size: 1, current_rows: 3, limit: 3
> 
> Does this mean we should consider #5362 as not fixed?

Although https://github.com/scylladb/scylladb/issues/5362 has the word "paging" in its text, it was actually about LIMIT, not paging. Nevertheless my new tests, and apparently also the dtests that now fail, also checked **paging** in addition to LIMIT. Specifically, if you ask for LIMIT 3 but set paging (fetch_size) to 1, you should get three pages of one result each - you shouldn't get a single page of 3 results (which is what happened in your code).

The goal of my test is to verify two things:
1. The first page when fetch_size=1 and limit=3 should be of size 1, not 3.
2. If we continue to fetch 3 results in three pages, the read will then end (because of limit=3). We can't start counting the limit afresh on every page!

These, especially the second point, verify that when we implemented LIMIT in this patch, we didn't do it incorrectly.

Conceivably, we could say that we fixed 5362 - and then open a new issue that just the paging remains broken. But in my opinion, this failure suggests that something in your solution is wrong and it should be fixed now, before merging.

**Comment by nyh** [comment]
By the way, @KrzaQ completely unrelated to this PR, yesterday I stumbled across your https://dev.krzaq.cc/post/you-dont-need-a-stateful-deleter-in-your-unique_ptr-usually/ and it was very helpful for writing https://github.com/cloudius-systems/osv/commit/8340a406e4f969b83881a9181ca259258bdb197c. I used a unique_ptr Deleter in the past, but obviously did it wrong, and the class way you recommended was so much better!

**Comment by avikivity** [comment]
> @scylladb/scylla-maint now that the dtests have been updated, the CI is green.

Well done. This is not an easy bug.

File: cql3/selection/selection.cc [hunk 12]
```diff
@@ -503,10 +503,12 @@ selection::collect_metadata(const schema& schema, const std::vector<prepared_sel
 }
 
 result_set_builder::result_set_builder(const selection& s, gc_clock::time_point now,
-                                       std::vector<size_t> group_by_cell_indices)
+                                       std::vector<size_t> group_by_cell_indices,
+                                       std::optional<uint64_t> limit)
```
Comment (avikivity) [inline cql3/selection/selection.cc:507]: You could send numeric_limits::max here and avoid the optional and some complexity.

Comment (avikivity) [reply cql3/selection/selection.cc:507]: Wait I already made this comment. I'm so repeatable.

File: cql3/statements/select_statement.cc [hunk 13]
```diff
@@ -462,8 +468,15 @@ select_statement::execute_without_checking_exception_message_aggregate_or_paged(
             state, options, command, std::move(key_ranges), _restrictions_need_filtering ? _restrictions : nullptr);
 
     if (aggregate || nonpaged_filtering) {
-        auto builder = cql3::selection::result_set_builder(*_selection, now, *_group_by_cell_indices);
-        coordinator_result<void> result_void = co_await utils::result_do_until([&p] {return p->is_exhausted();},
+        std::optional<uint64_t> limit;
+        if (_limit) {
+            limit = get_limit_impl(options, _limit);
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:472]: I still don't like this double-evaluation. We should evaluate the limit in one place, not several, and pass it around.

File: cql3/selection/selection.cc (hunk 12 above)
Comment (ptrsmrn) [reply cql3/selection/selection.cc]: Checking for `numeric_limits::max` obscures the logic, whereas `std::optional` clearly states what to expect, do we really need this micro-optimization? "Premature optimization..."

File: cql3/statements/select_statement.cc (hunk 13 above)
Comment (avikivity) [reply cql3/statements/select_statement.cc]: Why "cache"? Evaluate the limit at the beginning and pass it around? If there something convoluted in the control flow?

I don't object to the double evaluation due to performance (this isn't a hot path), but due to cleanliness.

File: test/cql-pytest/test_group_by.py [hunk 14]
```diff
@@ -73,8 +106,6 @@ def test_group_by_clustering_prefix(cql, table1):
     assert [(0,0,0,1), (0,1,0,3)] == list(cql.execute(f'SELECT p,c1,c2,v FROM {table1} WHERE p=0 GROUP BY p,c1'))
 
 # Adding a LIMIT should be honored.
```
Comment (nyh) [inline test/cql-pytest/test_group_by.py:108]: Again, please don't remove the "Reproduces" comments - they are important!
Just yesterday we had a presentation from @xtrey who said this was one of the things he wanted to achieve with Allure (as you can see here, Allure isn't needed for tests to say what they reproduce in a comment).

File: test/cql-pytest/test_group_by.py [hunk 15]
```diff
@@ -147,9 +178,6 @@ def test_group_by_count(cql, table1):
     assert {(0,0,0,1), (0,0,1,1), (0,1,0,1), (0,1,1,1), (1,0,0,1), (1,0,1,1), (1,1,0,1), (1,1,1,1)} == set(cql.execute(f'SELECT p,c1,c2,count(*) FROM {table1} GROUP BY p,c1,c2'))
 
 # Adding a LIMIT should be honored.
-# Reproduces #5361 - more results than the limit were generated (seems the
-# limit was outright ignored).
-@pytest.mark.xfail(reason="issue #5361")
```
Comment (nyh) [inline test/cql-pytest/test_group_by.py:152]: Again, please don't remove the comment - just remove the xfail line.

File: test/cql-pytest/test_group_by.py [hunk 16]
```diff
@@ -184,9 +212,6 @@ def test_group_by_v_and_sum(cql, table1):
     assert {(0,1,1), (0,2,2), (0,3,3), (0,4,4), (1,5,5), (1,6,6), (1,7,7), (1,8,8)} == set(cql.execute(f'SELECT p,v,sum(v) FROM {table1} GROUP BY p,c1,c2'))
 
 # Adding a LIMIT should be honored.
-# Reproduces #5361 - more results than the limit were generated (seems the
-# limit was outright ignored).
```
Comment (nyh) [inline test/cql-pytest/test_group_by.py:188]: Again please don't remove the comment.

File: cql3/statements/select_statement.cc [hunk 17]
```diff
@@ -399,14 +399,13 @@ select_statement::do_execute(query_processor& qp,
...
-    // If we user provided a page_size we'll use that to page internally (because why not), otherwise we use our default
-    // Note that if there are some nodes in the cluster with a version less than 2.0, we can't use paging (CASSANDRA-6707).
+    // An aggregation query may not be paged for the user, but we always page it internally to avoid OOM.
+    // If the user provided a page_size we'll use that to page internally (because why not), otherwise we use our default
     // Also note: all GROUP BY queries are considered aggregation.
     const bool aggregate = _selection->is_aggregate() || has_group_by();
     const bool nonpaged_filtering = _restrictions_need_filtering && page_size <= 0;
     if (aggregate || nonpaged_filtering) {
-        page_size = internal_paging_size;
+        page_size = page_size <= 0 ? internal_paging_size : std::min(page_size, internal_paging_size);
```
Comment (nyh) [inline cql3/statements/select_statement.cc:408]: The commit message doesn't say what this change fixes. I think you should mention in the commit message the test I added recently added that doesn't work without this fix.
Also, if you want this series to be perfectly bisectable (i.e., pass all tests between each patch in the series), you'll need to move this patch before the previous patch - because between these two patches, my test would fail.

**Review by nyh — CHANGES_REQUESTED** [review]
Looks good (thanks!), but I have a few final requests.

File: test/cql-pytest/test_group_by.py (hunk 14 above)
Comment (xtrey) [reply test/cql-pytest/test_group_by.py:108]: Unfortunately, this comment is not visible on the test results page, where it will provide more value.

**Comment by avikivity** [comment]
> I'm not sure what to do, clang-tidy seems to have failed on a file that has not been changed by me. I haven't rebased on the newest master either.

@tchaikov please help

**Comment by tchaikov** [comment]
> > I'm not sure what to do, clang-tidy seems to have failed on a file that has not been changed by me. I haven't rebased on the newest master either.
> 
> @tchaikov please help

ack. i am on it.

**Comment by ptrsmrn** [comment]
> > > I'm not sure what to do, clang-tidy seems to have failed on a file that has not been changed by me. I haven't rebased on the newest master either.
> > 
> > 
> > @tchaikov please help
> 
> ack. i am on it.

@tchaikov you may also get some inspiration out of https://github.com/scylladb/scylladb/pull/19518#issuecomment-2211005075 - basically it failed in the same way.

**Comment by tchaikov** [comment]
> > > > I'm not sure what to do, clang-tidy seems to have failed on a file that has not been changed by me. I haven't rebased on the newest master either.
> > > 
> > > 
> > > @tchaikov please help
> > 
> > 
> > ack. i am on it.
> 
> @tchaikov you may also get some inspiration out of [#19518 (comment)](https://github.com/scylladb/scylladb/pull/19518#issuecomment-2211005075) - basically it failed in the same way.

thanks. just sent a PR at #19628.

File: cql3/selection/selection.cc [hunk 18]
```diff
@@ -503,10 +503,12 @@ selection::collect_metadata(const schema& schema, const std::vector<prepared_sel
 }
 
 result_set_builder::result_set_builder(const selection& s, gc_clock::time_point now,
-                                       std::vector<size_t> group_by_cell_indices)
+                                       std::vector<size_t> group_by_cell_indices,
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/selection/selection.cc:506]: Please answer @nyh here

File: cql3/statements/select_statement.cc [hunk 19]
```diff
@@ -461,8 +467,12 @@ select_statement::execute_without_checking_exception_message_aggregate_or_paged(
             state, options, command, std::move(key_ranges), _restrictions_need_filtering ? _restrictions : nullptr);
 
     if (aggregate || nonpaged_filtering) {
-        auto builder = cql3::selection::result_set_builder(*_selection, now, *_group_by_cell_indices);
-        coordinator_result<void> result_void = co_await utils::result_do_until([&p] {return p->is_exhausted();},
+        uint64_t limit = _limit ? get_limit_impl(options, *_limit) : std::numeric_limits<uint64_t>::max();
+        auto builder = cql3::selection::result_set_builder(*_selection, now, *_group_by_cell_indices, limit);
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:471]: You still haven't explained why we need to evaluate the limit again. I see it's already evaluated in select_statement::do_execute(). 

I'm also confused (independently of the patch) about the too many places the limit goes into. select_statement::do_execute() embeds the limit into read_command. But if we're aggregating, we need to apply the limit to the aggregated result, not to the input rows.

Comment (avikivity) [reply cql3/statements/select_statement.cc:471]: Wait I know why. get_limit() doesn't just get the limit, it does something else if is_aggregate.

Comment (avikivity) [reply cql3/statements/select_statement.cc:471]: Here's a better solution:
1. break out the extra checks in get_limit() and add them to the callers.
2. Refine the extra checks at the right callers. For example, we can have two variables: inner_loop_limit and outer_loop_limit. For aggregation, we'd set outer_loop_limit to the LIMIT, otherwise inner_loop_limit.

Why it's better: instead of having multiple layers of get_limit() functions with no explanation, and a get_limit() that is not simple to understand (because it does another calculation), we have a trivial get_limit() and each caller gets to choose what it does with it.

**Comment by ptrsmrn** [comment]
> @scylladb/scylla-maint please take a further look. The CI is green.

@scylladb/scylla-maint ping

**Comment by avikivity** [comment]
Sorry, looking now.

File: cql3/statements/select_statement.cc (hunk 19 above)
Comment (avikivity) [reply cql3/statements/select_statement.cc:485]: get_limit_with_default_and_unset_guard() still has `|| is_aggregate()`. So it's returning the wrong answer and expecting the caller to know which get_limit() variant to call.

The is_aggregate() call should move to the call sites.

See below (not even compile tested)

```diff
diff --git a/cql3/statements/select_statement.cc b/cql3/statements/select_statement.cc
index 2e29bac1de..1295f591d6 100644
--- a/cql3/statements/select_statement.cc
+++ b/cql3/statements/select_statement.cc
@@ -356,11 +356,18 @@ select_statement::do_execute(query_processor& qp,
 
     auto cl = options.get_consistency();
 
     validate_for_read(cl);
 
-    uint64_t limit = get_limit(options);
+    uint64_t inner_loop_limit = get_limit(options);
+    uint64_t outer_loop_limit = inner_loop_limit; // If we don't aggregate, the outer loop and the inner loop are the same loop
+
+    if (is_aggregate() || needs_post_query_ordering() /* ?? */) {
+        // If we have an outer loop, LIMIT applies to the outer loop.
+        inner_loop_limit = std::numeric_limits<uint64_t>::max();
+    }
+
     auto now = gc_clock::now();
 
     _stats.filtered_reads += _restrictions_need_filtering;
 
     const source_selector src_sel = state.get_client_state().is_internal()
@@ -378,11 +385,11 @@ select_statement::do_execute(query_processor& qp,
             _schema->id(),
             _schema->version(),
             std::move(slice),
             max_result_size,
             query::tombstone_limit(qp.proxy().get_tombstone_limit()),
-            query::row_limit(limit),
+            query::row_limit(inner_loop_limit),
             query::partition_limit(query::max_partitions),
             now,
             tracing::make_trace_info(state.get_trace_state()),
             query_id::create_null_id(),
             query::is_first_page::no,
@@ -436,11 +443,11 @@ select_statement::do_execute(query_processor& qp,
     if (!aggregate && !_restrictions_need_filtering && (page_size <= 0
             || !service::pager::query_pagers::may_need_paging(*_schema, page_size,
                     *command, key_ranges))) {
         f = execute_without_checking_exception_message_non_aggregate_unpaged(qp, command, std::move(key_ranges), state, options, now);
     } else {
-        f = execute_without_checking_exception_message_aggregate_or_paged(qp, command, std::move(key_ranges), state, options, now, page_size, aggregate, nonpaged_filtering);
+        f = execute_without_checking_exception_message_aggregate_or_paged(qp, command, std::move(key_ranges), state, options, now, page_size, aggregate, nonpaged_filtering, outer_loop_limit);
     }
 
     if (!tablet_info.has_value()) {
         return f;
     }
@@ -452,19 +459,19 @@ select_statement::do_execute(query_processor& qp,
 }
 
 future<::shared_ptr<cql_transport::messages::result_message>>
 select_statement::execute_without_checking_exception_message_aggregate_or_paged(query_processor& qp,
         lw_shared_ptr<query::read_command> command, dht::partition_range_vector&& key_ranges, service::query_state& state,
-        const query_options& options, gc_clock::time_point now, int32_t page_size, bool aggregate, bool nonpaged_filtering) const {
+        const query_options& options, gc_clock::time_point now, int32_t page_size, bool aggregate, bool nonpaged_filtering, uint64_t outer_loop_limit) const {
     command->slice.options.set<query::partition_slice::option::allow_short_read>();
     auto timeout_duration = get_timeout(state.get_client_state(), options);
     auto timeout = db::timeout_clock::now() + timeout_duration;
     auto p = service::pager::query_pagers::pager(qp.proxy(), _schema, _selection,
             state, options, command, std::move(key_ranges), _restrictions_need_filtering ? _restrictions : nullptr);
 
     if (aggregate || nonpaged_filtering) {
-        auto builder = cql3::selection::result_set_builder(*_selection, now, *_group_by_cell_indices);
+        auto builder = cql3::selection::result_set_builder(*_selection, now, *_group_by_cell_indices, outer_loop_limit);
         coordinator_result<void> result_void = co_await utils::result_do_until([&p] {return p->is_exhausted();},
                 [&p, &builder, page_size, now, timeout] {
                     return p->fetch_page_result(builder, page_size, now, timeout);
                 }
         );
```

File: cql3/statements/select_statement.cc [hunk 20]
```diff
@@ -283,31 +283,48 @@ select_statement::make_partition_slice(const query_options& options) const
...
         if (l <= 0) {
-            throw exceptions::invalid_request_exception("LIMIT must be strictly positive");
+            return bo::failure(exceptions::invalid_request_exception("LIMIT must be strictly positive"));
         }
-        return l;
+        return bo::success(l);
     } catch (const marshal_exception& e) {
-        throw exceptions::invalid_request_exception("Invalid limit value");
+        return bo::failure(exceptions::invalid_request_exception("Invalid limit value"));
+    } catch (const exceptions::invalid_request_exception& e) {
```
Comment (nyh) [inline cql3/statements/select_statement.cc:311]: What in the try code above can throw this exception?

File: cql3/statements/select_statement.cc [hunk 21]
```diff
@@ -283,31 +283,48 @@ select_statement::make_partition_slice(const query_options& options) const
...
+        return bo::failure(e);
+    }
+}
+
```
Comment (nyh) [inline cql3/statements/select_statement.cc:315]: This function is called "with_default" but it doesn't have a default parameter... So what does "with_default" mean?
Also, from the function's name I assumed get_limit_with_default_and_unset_guard() a variant of get_limit(). Now I understand it isn't - it doesn't call get_limit() itself, and is actually some sort of wrapper to the output of get_limit() you have to run and pass it. The result looks very confusing, at least to me (maybe if I started the review with reading a commit message explaining the goal of all of this, I would feel less confused? But I think something's wrong with the naming.)

File: cql3/statements/select_statement.cc [hunk 22]
```diff
@@ -283,31 +283,48 @@ select_statement::make_partition_slice(const query_options& options) const
...
+uint64_t select_statement::get_limit_with_default_and_unset_guard(const get_limit_result& limit, const query_options& options) const {
+    if (!limit.has_value() || _limit_unset_guard.is_unset(options) || _selection->is_aggregate()) {
+        return query::max_rows;
+    }
+    return limit.value();
+}
+
+uint64_t select_statement::get_per_partition_limit_with_default_and_unset_guard(const get_limit_result& limit, const query_options& options) const {
```
Comment (nyh) [inline cql3/statements/select_statement.cc:323]: This function confused me the most. It doesn't "get per partition limit", actually it usually the limit passed to it as a parameter (which is LIMIT not PER PARTITION LIMIT, right?) and only if unset, it returns query::partition_max_rows, which unless I'm missing something, is just a constant maximum uint64_t, nothing to do with partition limit.

**Review by nyh — CHANGES_REQUESTED** [review]
I couldn't understand the second patch at all - the changes to the get_limit() function completely confused me, and obscured what functionality changes were being done.

In the third patch, I asked before and have to ask again: Please make in the commit message explicit statements like "all tests for issue #5361 now pass so their xfail mark is removed" or if for some issue #XYZ there actually remain some failing tests please explain why (and you can't leave an issue claiming it xfails because of #XYZ and close #XYZ, so if that happens you need to change the xfail reason).

As it stands you just say "mark several older failing tests as passing now". That doesn't explain to me how you decided in the cover letter to mark three issues as being fixed.  Presumably **all** the previously-failings tests for these three issues now pass, but you didn't say that.

File: cql3/statements/select_statement.cc [hunk 23]
```diff
@@ -283,31 +283,48 @@ select_statement::make_partition_slice(const query_options& options) const
         std::reverse(bounds.begin(), bounds.end());
         ++_stats.reverse_queries;
     }
+
+    const uint64_t per_partition_limit = get_per_partition_limit_with_default_and_unset_guard(
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/statements/select_statement.cc:287]: Yes, a separate patch for limit refactoring with its own explanation is needed.

**Comment by mykaul** [comment]
> @scylladb/scylla-maint Please check, the CI is green.

@KrzaQ - please resolve all conversations if possible / completed.

File: cql3/statements/select_statement.cc [hunk 24]
```diff
@@ -283,33 +283,45 @@ select_statement::make_partition_slice(const query_options& options) const
...
     }
 }
 
+uint64_t select_statement::get_inner_loop_limit(const select_statement::get_limit_result& limit, const query_options& options,
+    const expr::unset_bind_variable_guard& unset_guard, bool is_aggregate, uint64_t default_value)
+{
+    if (!limit.has_value() || unset_guard.is_unset(options) || is_aggregate) {
+        return default_value;
+    }
+    return limit.value();
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:322]: I don't think you need to pass options/unset_guard/default_value here. get_limit() substitutes max_rows if not specified, which is equal to default_value in all cases.

In one case you pass query::partition_max_rows rather than query::max_rows. The question is whether they is accidentally equal or conceptually equal. I think they are conceptually equal (basically in both cases signifying an infinite amount). Maybe the reason we have two is 45215746fe6c013047b69aa651eb1a203a8c4185.

So you can simplify it to check only is_aggregate.

File: cql3/statements/select_statement.cc [hunk 25]
```diff
@@ -283,33 +283,45 @@ select_statement::make_partition_slice(const query_options& options) const
...
+}
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:323]: What's the point of using bo::result if you throw the exception here again?

File: cql3/statements/select_statement.cc [hunk 26]
```diff
@@ -437,7 +450,9 @@ select_statement::do_execute(query_processor& qp,
                     *command, key_ranges))) {
         f = execute_without_checking_exception_message_non_aggregate_unpaged(qp, command, std::move(key_ranges), state, options, now);
     } else {
-        f = execute_without_checking_exception_message_aggregate_or_paged(qp, command, std::move(key_ranges), state, options, now, page_size, aggregate, nonpaged_filtering);
+        f = execute_without_checking_exception_message_aggregate_or_paged(qp, command,
+            std::move(key_ranges), state, options, now, page_size, aggregate,
+            nonpaged_filtering, parsed_limit.has_value() ? parsed_limit.value() : query::max_rows);
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:455]: Strictly speaking, doesn't this belong in the next patch? This patch makes the inner loop limits explicit. This part of the patch is about passing the outer loop limit.
