### PR TITLE
commitlog_test::test_commitlog_reader: handle segment_truncation

### LINKED ISSUE #16312: [aarch64, debug] test_commitlog_reader failed
`[aarch64] boost  debug  [ FAIL ] boost.commitlog_test.test_commitlog_reader.1` failed 
with ERROR:
```
[Exception] - db::commitlog::segment_truncation: Segment truncation at 1048576
 == [File] - test/boost/commitlog_test.cc
 == [Line] - 360
```
link to the test failure:
https://jenkins.scylladb.com/job/scylla-master/job/next/6902/testReport/boost/commitlog_test/test_commitlog_reader_2/

link to the full log failure:
https://jenkins.scylladb.com/job/scylla-master/job/next/6902/artifact/testlog/aarch64/debug/boost.commitlog_test.test_commitlog_reader.1.log
```
=== TEST.PY STARTING TEST boost.commitlog_test.test_commitlog_reader.1 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/next/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
build/debug/test/boost/commitlog_test --run_test=test_commitlog_reader --report_level=no --logger=HRF,test_suite:XML,test_suite,/scylladir/testlog/aarch64/debug/xml/boost.commitlog_test.test_commitlog_reader.1.xunit.xml --catch_system_errors=no --color_output=false -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100
=== TEST.PY TEST boost.commitlog_test.test_commitlog_reader.1 OUTPUT ===
Running 1 test case...
Entering test module "Master Test Suite"
test/boost/commitlog_test.cc(79): Test case "test_create_commitlog" is skipped because disabled
test/boost/commitlog_test.cc(91): Test case "test_commitlog_written_to_disk_batch" is skipped because disabled
test/boost/commitlog_test.cc(107): Test case "test_commitlog_written_to_disk_sync" is skipped because disabled
test/boost/commitlog_test.cc(122): Test case "test_commitlog_written_to_disk_no_sync" is skipped because disabled
test/boost/commitlog_test.cc(137): Test case "test_commitlog_written_to_disk_periodic" is skipped because disabled
test/boost/commitlog_test.cc(156): Test case "test_commitlog_new_segment" is skipped because disabled
test/boost/commitlog_test.cc(191): Test case "test_commitlog_discard_completed_segments" is skipped because disabled
test/boost/commitlog_test.cc(255): Test case "test_equal_record_limit" is skipped because disabled
test/boost/commitlog_test.cc(266): Test case "test_exceed_record_limit" is skipped because disabled
test/boost/commitlog_test.cc(283): Test case "test_commitlog_closed" is skipped because disabled
test/boost/commitlog_test.cc(298): Test case "test_commitlog_delete_when_over_disk_limit" is skipped because disabled
test/boost/commitlog_test.cc(352): Entering test case "test_commitlog_reader"
WARNING: debug mode. Not for benchmarking or production
WARN  2023-12-06 12:36:28,323 seastar - Seastar compiled with default allocator, --memory option won't take effect
WARN  2023-12-06 12:36:28,356 seastar - Could not read cgroups v2 file (memory.max).
INFO  2023-12-06 12:36:28,358 seastar - Reactor backend: linux-aio
INFO  2023-12-06 12:36:28,360 [shard 0:n/a ] seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
random-seed=2964829398
unknown location(0): fatal error: in "test_commitlog_reader": db::commitlog::segment_truncation: Segment truncation at 1048576
test/boost/commitlog_test.cc(360): last checkpoint
test/boost/commitlog_test.cc(352): Leaving test case "test_commitlog_reader"; testing time: 27967073us
test/boost/commitlog_test.cc(434): Test case "test_commitlog_entry_corruption" is skipped because disabled
test/boost/commitlog_test.cc(474): Test case "test_commitlog_chunk_corruption" is skipped because disabled
test/boost/commitlog_test.cc(515): Test case "test_commitlog_chunk_corruption2" is skipped because disabled
test/boost/commitlog_test.cc(563): Test case "test_commitlog_chunk_corruption3" is skipped because disabled
test/boost/commitlog_test.cc(623): Test case "test_commitlog_replay_single_large_mutation" is skipped because disabled
test/boost/commitlog_test.cc(684): Test case "test_commitlog_replay_large_mutations" is skipped because disabled
test/boost/commitlog_test.cc(750): Test case "test_commitlog_chunk_truncation" is skipped because disabled
test/boost/commitlog_test.cc(824): Test case "test_commitlog_reader_produce_exception" is skipped because disabled
test/boost/commitlog_test.cc(862): Test case "test_commitlog_counters" is skipped because disabled
test/boost/commitlog_test.cc(917): Test case "test_commitlog_replay_invalid_key" is skipped because disabled
test/boost/commitlog_test.cc(974): Test case "test_commitlog_add_entries" is skipped because disabled
test/boost/commitlog_test.cc(1036): Test case "test_commitlog_new_segment_odsync" is skipped because disabled
test/boost/commitlog_test.cc(1068): Test case "test_commitlog_deadlock_in_recycle" is skipped because disabled
test/boost/commitlog_test.cc(1143): Test case "test_commitlog_shutdown_during_wait" is skipped because disabled
test/boost/commitlog_test.cc(1210): Test case "test_commitlog_deadlock_with_flush_threshold" is skipped because disabled
test/boost/commitlog_test.cc(1348): Test case "test_commitlog_exceptions_in_allocate_ex" is skipped because disabled
test/boost/commitlog_test.cc(1358): Test case "test_commitlog_exceptions_in_allocate_ex_deleted_file_no_recycle" is skipped because disabled
test/boost/commitlog_test.cc(1364): Test case "test_commitlog_segment_descriptor" is skipped because disabled
test/boost/commitlog_test.cc(1405): Test case "test_delete_recycled_segment_removes_size" is skipped because disabled
Leaving test module "Master Test Suite"; testing time: 27967735us
=== TEST.PY SUMMARY START ===
Test exited with code 201

=== TEST.PY SUMMARY END ===
```

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #16312
    
This test replays a segment before it might be closed or even fully flushed, thus it can (with the new semantics) generate a segment_truncation exception if hitting eof earlier than expected. (Note: test does not use pre-allocated segments).

(First patch makes the test coroutinized to make for a nicer, easier fix change.

### CODE REVIEW

File: test/boost/commitlog_test.cc [hunk 1]
```diff
@@ -352,15 +352,21 @@ SEASTAR_TEST_CASE(test_commitlog_delete_when_over_disk_limit) {
...
+                auto str = to_sstring_view(in.read_bytes_view(buf.size_bytes(), linearization_buffer));
+                BOOST_CHECK_EQUAL(str, "hej bubba cow");
+                count++;
+                co_return;
+            });
+        } catch (commitlog::segment_truncation&) {
+            // ok. this does not ensure to have fully synced segments
+            // before reading them in all code paths. We can end up
+            // hitting (premature) eof or even half-written page.
+        }
```
Comment (avikivity) [inline test/boost/commitlog_test.cc:369]: So, if read_log_path() is changed to always throw segment_truncation, the test will pass.

What are we testing here? We need to check that we read the data that we wrote, not that we obey some protocol.

Comment (elcallio) [reply test/boost/commitlog_test.cc:369]: No, if we get truncation, we accept it as a segment stop marker. Note the data check in the replay callback + the "count" var being incremented. The code after this will verify this var has the correct value (i,e. replayed all entries we expected.

Comment (avikivity) [reply test/boost/commitlog_test.cc:369]: ok
