### PR TITLE
Fix bootstrap "wait for UP/NORMAL nodes" to handle ignored nodes, recently replaced nodes, and recently changed IPs

### LINKED ISSUE #14468: test_decommission_after_changing_node_ip: node4 fails to start when stale ip address of node3 appears as DOWN, status=shutdown
Seen first in https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/290/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split010___test_decommission_after_changing_node_ip/
```
RuntimeError: The process is dead, returncode=1
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-daily-release/290/artifact/logs-full.release.010/1688093180144_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_decommission_after_changing_node_ip/node4.log
```
Scylla version 5.4.0~dev-0.20230630.ff386e7a445d with build-id 228b9c341f6b5404947f4a2020d4a25eeaacebbe starting ...

INFO  2023-06-30 02:45:44,589 [shard 0] init - seeds={127.0.96.1, 127.0.96.2, 127.0.96.4, 127.0.96.33}, listen_address=127.0.96.4, broadcast_address=127.0.96.4

INFO  2023-06-30 02:45:44,675 [shard 0] storage_service - Starting up server gossip
INFO  2023-06-30 02:45:44,683 [shard 0] compaction - [Compact system.local 35def3b0-16f0-11ee-a3e4-02af61fe3371] Compacting [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-0iu1ozg8/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-2-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-0iu1ozg8/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-4-big-Data.db:level=0:origin=memtable]
INFO  2023-06-30 02:45:44,683 [shard 0] gossip - failure_detector_loop: Started main loop
INFO  2023-06-30 02:45:44,683 [shard 0] gossip - Waiting for 2 live nodes to show up in gossip, currently 1 present...
INFO  2023-06-30 02:45:44,693 [shard 0] compaction - [Compact system.local 35def3b0-16f0-11ee-a3e4-02af61fe3371] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-0iu1ozg8/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-6-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 7ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-06-30 02:45:46,131 [shard 0] storage_service - Set host_id=97569d56-628c-4485-b0e6-1c68c40c537f to be owned by node=127.0.96.1
INFO  2023-06-30 02:45:46,132 [shard 0] gossip - InetAddress 127.0.96.33 is now DOWN, status = LEFT
WARN  2023-06-30 02:45:46,132 [shard 0] gossip - Fail to send EchoMessage to 127.0.96.3: seastar::rpc::closed_error (connection is closed)
INFO  2023-06-30 02:45:46,132 [shard 0] gossip - InetAddress 127.0.96.1 is now UP, status = NORMAL
INFO  2023-06-30 02:45:46,132 [shard 0] gossip - InetAddress 127.0.96.2 is now UP, status = NORMAL
INFO  2023-06-30 02:45:46,133 [shard 0] gossip - Node 127.0.96.33 will be removed from gossip at [2023-07-03 02:45:19]: (expire = 1688352319445716595, now = 1688093146132961662, diff = 259173 seconds)
INFO  2023-06-30 02:45:46,133 [shard 0] storage_service - Removing tokens {1957138825282075456, 538228788046155918, 1441663362887118471, 2009889732205232147, 1285921624202456720, 2299813546280369809, 1147922929401656711, 3437689283141886193, 1093939752358477342, -95578895009921325, -933537828167744695, -4822175528068997885, -9064814390348450199, -2838398123611190415, -8865697753194005691, -8641240172602522619, -8527192015627880935, -8455721658642346121, -1602885157652809629, -826999321362664251, -8004313790603409879, -7983704426324750105, 6745400184375170269, 1897403336345133737, -7785637751534354940, 6402350960772843634, -9131862161278302934, 7015699157901876878, -7507635517787229617, -7872263450865226137, -2398561151223758453, -2757858320304448776, -7135017416280759518, 762591318120088757, -7036247732884944684, -4706718406784561136, 772993406584974221, -6901710291266973174, -6873621148550053390, -131764165975166161, -6467486352483923794, -8723719628383537842, -7239257021703251755, -8876209735699572524, -6300796970024261941, -633462019235493849, -6310403927118869660, -1431497748581863464, 3697526867126198196, 4923690827301917877, 8112265936827023660, -6277863917912802240, -6623626227015086286, -6263567382473675505, 2044340043996898806, -1684759488608644447, 4219519608993832438, 622262989057717658, -6132029616733649227, -2863638381489490074, -6093224496148114428, -7168585208466197697, 82753073108884114, -5933252256733306442, -5452048513549809665, 3547905835448042745, -5895694438770948515, 7045113366380893923, -6640938570355561189, -5660282275830501698, -3728555925078188231, -4034527578391978588, -5233014222012667101, -8844096475636041617, -2839352313897520511, -917431164596666618, 3618597186644201391, 1638066742741535716, -5023041224884994968, -2616649082261222559, -2415888436872385330, -2940916223950425714, -8994438244973781987, -833074952334662081, -4426602942396513532, 649128337838919561, 7775225799600157744, 1580061385397170636, -2402418775007732133, -7427857065668640033, -1049799291451885300, -2550242859911733562, 5198876569107239321, -8301793316585325178, 5554285130267436886, -8058007130247916491, -4088885882961805256, -7332104044879353661, -1732367245764070833, -5214440851373603397, -4028381155067564419, 741098824345071851, -2076353771709165172, 2095974798297043788, 3679342026564125770, -637331905247054159, -42107836694803384, 6736375668058457916, -231760654102333982, 4133801035329363389, -129951755050233280, -1712843812334547699, -2812010428323279743, -8972822811092831737, -5934804369128314387, -1911244404117897093, 7399718564801560588, -426914257413052499, 1951602158941318813, -2310239841370092592, -5096146377327979133, -5353838904714672202, 7416808377702594272, -2762853363408437030, -1987318027109743947, -2698847702965464001, -2389636933915703465, -1642036105268827801, 729012831382377832, 4192467494245733578, 453328910274435383, 4604210925835301206, -4861600011407716479, -8866456080701519922, 4710686227407048955, 4060438571529584411, 8082128952710491799, -8917743902008465042, 4830388162512167990, 5405228356480841250, 3896618241085296806, 7483054753003347861, 4848712762403721656, 8155890873069566919, 6050126936624620059, 8143687424717096518, 5099342403467628764, 8193264499918054230, 8364320176004023673, 7464679094141006861, 2369583153774542736, 4661971083725460006, 6557277420237977594, 8907558311654534023, 4255593540650591036, 4697507652786315355, 8795941309877878551, 5544435872844200824, 994944297945037712, 8674029532381474478, 8938215158385744024, 9175241447091780067, 8319752497800048455, 9098428809063992811, 7083019289871699050, 6392147032912275551, 959369937171193663, 775223285155485749, 6969946619945396669, -239385818321278898, 7867023678609882900, 8485756174775015178, 653524404411507543, 2712519592800561458, 784408449538585673, 7516305215489330783, 5284849260795346378, 4542935427815921456, 7491143762287671218, 5179321468636036249, -2958423916817125021, 8621454108457851488, 5343972147310513540, 7050409196988331169, 6241621443978259740, 5691844199512967388, 743728028477351888, 8410411973934585175, 6021480115957511646, -3856883873430924609, -7280028224051135209, 8185743236066043166, 4819273962897017308, 5059145346103373931, 5661813372786345482, 5599681698548794203, 6932747168268650376, 6400515060487972645, 785000777408566651, 8595379441425988714, 4145778381949139232, 3999909828137760869, 6405837028323423354, 3817823138014204958, 5053716988947964343, 2101315427911447873, -4806749523356533582, -132972332550087561, -5353424467192232738, -8802576457060150269, -3474097763156463305, 9009209169705780290, 7802793542092058234, 2662779670492735497, 3691097620139590768, 6513610463854070484, 6471493476659702419, 3650193360811123081, 3001254928584914018, 3499840302063501290, 6779972895102656116, 3131683082988308425, 3031653570599157564, 4892084020860236578, 2497511531750475769, 285759181479020292, 247802566240022100, 2284461744151074821, 8207089875905276412, -3411577389189401767, 2411677680261672874, 7324966747666123341, 2377271546849325331, 2319710447218706879, 2194167096131029618, 7258249247273455641, -5125548559804459378, -4212817902181982644, -4997823109883866192, -9119142511799409952, -3973719466666207470, -2050716514012087603, 5878268823371831765, -5038661372228412283, -6264926153255382601, 5237492490607863914, 9162069553344955750, -3338928958552776636, -4485975510199365998, -3289713503100616853, 3340398587603137395, 3269564000274247296, -3109033788701436529, 8147309304491324864, -4879276416205021178, -5513812679592304083} for 127.0.96.33
INFO  2023-06-30 02:45:46,133 [shard 0] gossip - removed 127.0.96.33 from _seeds, updated _seeds list = {127.0.96.1, 127.0.96.2}
INFO  2023-06-30 02:45:46,134 [shard 0] storage_service - Set host_id=bd2c8d8d-3751-4491-9b96-ac414b747fa7 to be owned by node=127.0.96.2
INFO  2023-06-30 02:45:46,136 [shard 0] storage_service - Skip to set host_id=ed379b1a-c563-44be-acf0-28ccd6ca7096 to be owned by node=127.0.96.3, because the node is removed from the cluster, nodes {127.0.96.3, 127.0.96.33} used to own the host_id
INFO  2023-06-30 02:45:46,137 [shard 0] gossip - InetAddress 127.0.96.3 is now DOWN, status = shutdown
INFO  2023-06-30 02:45:46,139 [shard 0] migration_manager - Requesting schema pull from 127.0.96.1:0
INFO  2023-06-30 02:45:46,139 [shard 0] migration_manager - Pulling schema from 127.0.96.1:0
INFO  2023-06-30 02:45:46,140 [shard 0] migration_manager - Requesting schema pull from 127.0.96.2:0
INFO  2023-06-30 02:45:46,140 [shard 0] migration_manager - Pulling schema from 127.0.96.2:0
INFO  2023-06-30 02:45:46,142 [shard 0] gossip - Live nodes seen in gossip: {127.0.96.1, 127.0.96.2, 127.0.96.4}
INFO  2023-06-30 02:45:46,142 [shard 0] storage_service - Check node=127.0.96.3, status=shutdown
INFO  2023-06-30 02:45:46,142 [shard 0] storage_service - Check node=127.0.96.33, status=LEFT
INFO  2023-06-30 02:45:46,142 [shard 0] storage_service - Check node=127.0.96.2, status=NORMAL
INFO  2023-06-30 02:45:46,142 [shard 0] storage_service - Check node=127.0.96.1, status=NORMAL
INFO  2023-06-30 02:45:46,142 [shard 0] storage_service - Check node=127.0.96.4, status=UNKNOWN
INFO  2023-06-30 02:45:46,142 [shard 0] storage_service - Started waiting for normal state handler for nodes {127.0.96.1, 127.0.96.2, 127.0.96.3}

INFO  2023-06-30 02:46:16,245 [shard 0] init - Shutting down group 0 service
...
ERROR 2023-06-30 02:46:16,771 [shard 0] init - Startup failed: std::runtime_error (Failed to mark node as alive in 30000 ms, nodes={127.0.96.1, 127.0.96.2, 127.0.96.3}, live_nodes={127.0.96.1, 127.0.96.2})
```

### LINKED ISSUE #14487: test_ignore_dead_nodes_for_replace_option: Startup failed: std::runtime_error (Failed to parse node list: {127.0.55.6, 127.0.55.7}: invalid node=127.0.55.6: std::runtime_error (Host inet address 127.0.55.6 not found in the cluster))
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/294/artifact/logs-full.release.019/1688369920023_repair_based_node_operations_test.py%3A%3ATestRepairBasedNodeOperations%3A%3Atest_ignore_dead_nodes_for_replace_option/node8.log
```
Scylla version 5.4.0~dev-0.20230703.1ab2bb69b8a6 with build-id 1054adfa55f238441c3044e6213fd02d31d43279 starting ...
command used: "/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-nvlixxhx/test/node8/bin/scylla --options-file /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-nvlixxhx/test/node8/conf/scylla.yaml --log-to-stdout 1 --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --enable-repair-based-node-ops true --ignore-dead-nodes-for-replace 127.0.55.6,127.0.55.7 --api-address 127.0.55.8 --collectd-hostname d332c648e72c.node8 --smp 2 --memory 1024M --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.55.8 --replace-node-first-boot d97b63b2-72f5-4640-bba8-893420adf609 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --commitlog-use-o-dsync 0 --max-networking-io-control-blocks 1000"
parsed command line options: [options-file: /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-nvlixxhx/test/node8/conf/scylla.yaml, log-to-stdout, (positional) 1, abort-on-seastar-bad-alloc, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, enable-repair-based-node-ops: true, ignore-dead-nodes-for-replace: 127.0.55.6,127.0.55.7, api-address: 127.0.55.8, collectd-hostname, (positional) d332c648e72c.node8, smp, (positional) 2, memory, (positional) 1024M, developer-mode: true, default-log-level, (positional) info, collectd, (positional) 0, overprovisioned, prometheus-address: 127.0.55.8, replace-node-first-boot: d97b63b2-72f5-4640-bba8-893420adf609, unsafe-bypass-fsync, (positional) 1, kernel-page-cache, (positional) 1, commitlog-use-o-dsync: 0, max-networking-io-control-blocks, (positional) 1000]

INFO  2023-07-03 07:38:26,583 [shard 0] init - seeds={127.0.55.1, 127.0.55.2, 127.0.55.3, 127.0.55.4, 127.0.55.5, 127.0.55.6, 127.0.55.7}, listen_address=127.0.55.8, broadcast_address=127.0.55.8

INFO  2023-07-03 07:38:26,662 [shard 0] storage_service - entering STARTING mode
INFO  2023-07-03 07:38:26,662 [shard 0] storage_service - Loading persisted ring state
INFO  2023-07-03 07:38:26,664 [shard 0] storage_service - initial_contact_nodes={127.0.55.7, 127.0.55.6, 127.0.55.5, 127.0.55.4, 127.0.55.3, 127.0.55.2, 127.0.55.1}, loaded_endpoints={}, loaded_peer_features=0
INFO  2023-07-03 07:38:26,664 [shard 0] storage_service - Gathering node replacement information for d97b63b2-72f5-4640-bba8-893420adf609/0000:0000:0000:0000:0000:0000:0000:0000
INFO  2023-07-03 07:38:26,664 [shard 0] storage_service - Checking remote features with gossip
INFO  2023-07-03 07:38:26,664 [shard 0] gossip - Gossip shadow round started with nodes={127.0.55.7, 127.0.55.6, 127.0.55.5, 127.0.55.4, 127.0.55.3, 127.0.55.2, 127.0.55.1}
WARN  2023-07-03 07:38:26,665 [shard 0] gossip - Node 127.0.55.7 is down for get_endpoint_states verb
WARN  2023-07-03 07:38:26,665 [shard 0] gossip - Node 127.0.55.6 is down for get_endpoint_states verb
WARN  2023-07-03 07:38:26,665 [shard 0] gossip - Node 127.0.55.5 is down for get_endpoint_states verb
INFO  2023-07-03 07:38:26,666 [shard 0] gossip - Gossip shadow round finished with nodes_talked={127.0.55.2, 127.0.55.1, 127.0.55.3, 127.0.55.4}
INFO  2023-07-03 07:38:26,666 [shard 0] gossip - Feature check passed. Local node 127.0.55.8 features = {AGGREGATE_STORAGE_OPTIONS, ALTERNATOR_TTL, CDC, CDC_GENERATIONS_V2, COLLECTION_INDEXING, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_FOR_NULL_VALUES, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, EMPTY_REPLICA_PAGES, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_COLLECTION_DETECTION, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, MD_SSTABLE_FORMAT, ME_SSTABLE_FORMAT, NONFROZEN_UDTS, PARALLELIZED_AGGREGATION, PER_TABLE_CACHING, PER_TABLE_PARTITIONERS, RANGE_SCAN_DATA_VARIANT, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_COMMITLOG, SCHEMA_TABLES_V3, SECONDARY_INDEXES_ON_STATIC_COLUMNS, SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT, STREAM_WITH_RPC_STREAM, TOMBSTONE_GC_OPTIONS, TRUNCATION_TABLE, TYPED_ERRORS_IN_READ_RPC, UDA, UDA_NATIVE_PARALLELIZED_AGGREGATION, UNBOUNDED_RANGE_TOMBSTONES, UUID_SSTABLE_IDENTIFIERS, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}, Remote common_features = {AGGREGATE_STORAGE_OPTIONS, ALTERNATOR_TTL, CDC, CDC_GENERATIONS_V2, COLLECTION_INDEXING, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_FOR_NULL_VALUES, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, EMPTY_REPLICA_PAGES, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_COLLECTION_DETECTION, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, MD_SSTABLE_FORMAT, ME_SSTABLE_FORMAT, NONFROZEN_UDTS, PARALLELIZED_AGGREGATION, PER_TABLE_CACHING, PER_TABLE_PARTITIONERS, RANGE_SCAN_DATA_VARIANT, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_COMMITLOG, SCHEMA_TABLES_V3, SECONDARY_INDEXES_ON_STATIC_COLUMNS, SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT, STREAM_WITH_RPC_STREAM, TOMBSTONE_GC_OPTIONS, TRUNCATION_TABLE, TYPED_ERRORS_IN_READ_RPC, UDA, UDA_NATIVE_PARALLELIZED_AGGREGATION, UNBOUNDED_RANGE_TOMBSTONES, UUID_SSTABLE_IDENTIFIERS, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}
INFO  2023-07-03 07:38:26,666 [shard 0] storage_service - Host 189dd9bb-d950-446c-b527-a544925bc828/127.0.55.8 is replacing d97b63b2-72f5-4640-bba8-893420adf609/127.0.55.5
INFO  2023-07-03 07:38:26,666 [shard 0] storage_service - Replacing a node with a different IP address, my address=127.0.55.8, node being replaced=127.0.55.5
INFO  2023-07-03 07:38:26,666 [shard 0] storage_service - Save advertised features list in the 'system.local' table
INFO  2023-07-03 07:38:26,669 [shard 0] schema_tables - Schema version changed to 59adb24e-f3cd-3e02-97f0-5b395827453f
INFO  2023-07-03 07:38:26,669 [shard 0] storage_service - Starting up server gossip
INFO  2023-07-03 07:38:26,676 [shard 0] compaction - [Compact system.local 98dfab40-1974-11ee-8f2d-ec009dbc2650] Compacting [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-nvlixxhx/test/node8/data/system/local-7ad54392bcdd35a684174e047860b377/mc-2-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-nvlixxhx/test/node8/data/system/local-7ad54392bcdd35a684174e047860b377/mc-4-big-Data.db:level=0:origin=memtable]
INFO  2023-07-03 07:38:26,677 [shard 0] gossip - failure_detector_loop: Started main loop
INFO  2023-07-03 07:38:26,677 [shard 0] gossip - Waiting for 2 live nodes to show up in gossip, currently 1 present...
INFO  2023-07-03 07:38:26,686 [shard 0] compaction - [Compact system.local 98dfab40-1974-11ee-8f2d-ec009dbc2650] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-nvlixxhx/test/node8/data/system/local-7ad54392bcdd35a684174e047860b377/mc-6-big-Data.db:level=0]. 13kB to 7kB (~55% of original) in 6ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-07-03 07:38:27,988 [shard 0] storage_service - Set host_id=9137e227-94f4-449e-a6c6-dceed01cff99 to be owned by node=127.0.55.4
WARN  2023-07-03 07:38:27,990 [shard 0] gossip - Fail to send EchoMessage to 127.0.55.5: seastar::rpc::closed_error (connection is closed)
WARN  2023-07-03 07:38:27,990 [shard 0] gossip - Fail to send EchoMessage to 127.0.55.6: seastar::rpc::closed_error (connection is closed)
WARN  2023-07-03 07:38:27,990 [shard 0] gossip - Fail to send EchoMessage to 127.0.55.7: seastar::rpc::closed_error (connection is closed)
INFO  2023-07-03 07:38:27,990 [shard 0] gossip - InetAddress 127.0.55.4 is now UP, status = NORMAL
INFO  2023-07-03 07:38:27,990 [shard 0] gossip - InetAddress 127.0.55.3 is now UP, status = NORMAL
INFO  2023-07-03 07:38:27,990 [shard 0] gossip - InetAddress 127.0.55.1 is now UP, status = NORMAL
INFO  2023-07-03 07:38:27,990 [shard 0] gossip - InetAddress 127.0.55.2 is now UP, status = NORMAL
INFO  2023-07-03 07:38:27,991 [shard 0] storage_service - Set host_id=c6089c7e-809f-447e-a2c8-91009de372e2 to be owned by node=127.0.55.3
INFO  2023-07-03 07:38:27,993 [shard 0] storage_service - Set host_id=66e3c3ad-d16d-469c-98e2-6c3ff5f8aaf8 to be owned by node=127.0.55.1
INFO  2023-07-03 07:38:27,994 [shard 0] gossip - Live nodes seen in gossip: {127.0.55.1, 127.0.55.2, 127.0.55.3, 127.0.55.4, 127.0.55.8}

==> [BH] it looks like the exception happened here

INFO  2023-07-03 07:38:27,995 [shard 0] init - Shutting down group 0 service
...
INFO  2023-07-03 07:38:27,997 [shard 0] storage_service - Set host_id=ec4c0157-1523-4a1d-8aeb-e56e685e507a to be owned by node=127.0.55.6

==> [BH] handle_state_normal happens in parallel to storage_service::join_token_ring

...
INFO  2023-07-03 07:38:28,026 [shard 0] gossip - InetAddress 127.0.55.6 is now DOWN, status = shutdown
...
ERROR 2023-07-03 07:38:36,614 [shard 0] init - Startup failed: std::runtime_error (Failed to parse node list: {127.0.55.6, 127.0.55.7}: invalid node=127.0.55.6: std::runtime_error (Host inet address 127.0.55.6 not found in the cluster))
```

This looks like another fallout from 50e8ec77c6332b759a1e13125771524d26b7af34.

I think that in https://github.com/scylladb/scylladb/blob/50e8ec77c6332b759a1e13125771524d26b7af34/service/storage_service.cc#L1954-L1959

`wait_for_live_nodes_to_show_up(2)` doesn't ensure that the nodes in the ignore list (that are given by ip address in this test) have their host_id set up by https://github.com/scylladb/scylladb/blob/50e8ec77c6332b759a1e13125771524d26b7af34/service/storage_service.cc#L2496-L2497

### PR DESCRIPTION
**Pull request by kbr-scylla**
Before this PR, the `wait_for_normal_state_handled_on_boot` would
wait for a static set of nodes (`sync_nodes`), calculated using the
`get_nodes_to_sync_with` function and `parse_node_list`; the latter was
used to obtain a list of "nodes to ignore" (for replace operation) and
translate them, using `token_metadata`, from IP addresses to Host IDs
and vice versa. `sync_nodes` was also used in `_gossiper.wait_alive` call
which we do after `wait_for_normal_state_handled_on_boot`.

Recently we started doing these calculations and this wait very early in
the boot procedure - immediately after we start gossiping
(50e8ec77c6332b759a1e13125771524d26b7af34).

Unfortunately, as always with gossiper, there are complications.
In #14468 and #14487 two problems were detected:
- Gossiper may contain obsolete entries for nodes which were recently
  replaced or changed their IPs. These entries are still using status
  `NORMAL` or `shutdown` (which is treated like `NORMAL`, e.g.
  `handle_state_normal` is also called for it). The
  `_gossiper.wait_alive` call would wait for those entries too and
  eventually time out.
- Furthermore, by the time we call `parse_node_list`, `token_metadata`
  may not be populated yet, which is required to do the IP<->Host ID
  translations -- and populating `token_metadata` happens inside
  `handle_state_normal`, so we have a chicken-and-egg problem here.

It turns out that we don't need to calculate `sync_nodes` (and
hence `ignore_nodes`) in order to wait for NORMAL state handlers. We
can wait for handlers to finish for *any* `NORMAL`/`shutdown` entries
appearing in gossiper, even those that correspond to dead/ignored
nodes and obsolete IPs.  `handle_state_normal` is called, and
eventually finishes, for all of them.
`wait_for_normal_state_handled_on_boot` no longer receives a set of
nodes as parameter and is modified appropriately, it's now calculating
the necessary set of nodes on each retry (the set may shrink while
we're waiting, e.g. because an entry corresponding to a node that was
replaced is garbage-collected from gossiper state).

Thanks to this, we can now put the `sync_nodes` calculation (which is
still necessary for `_gossiper.wait_alive`), and hence the
`parse_node_list` call, *after* we wait for NORMAL state handlers,
solving the chickend-and-egg problem.

This addresses the immediate failure described in #14487, but the test
would still fail. That's because `_gossiper.wait_alive` may still receive
a too large set of nodes -- we may still include obsolete IPs or entries
corresponding to replaced nodes in the `sync_nodes` set.

We need a better way to calculate `sync_nodes` which detects ignores
obsolete IPs and nodes that are already gone but just weren't
garbage-collected from gossiper state yet.

In fact such a method was already introduced in the past:
ca61d88764f234851c95a26123dbe72abd28ed4b
but it wasn't used everywhere. There, we use `token_metadata` in which
collisions between Host IDs and tokens are resolved, so it contains only
entries that correspond to the "real" current set of NORMAL nodes.

We use this method to calculate the set of nodes passed to
`_gossiper.wait_alive`.

We also introduce regression tests with necessary extensions
to the test framework.

Fixes #14468
Fixes #14487

### CODE REVIEW

**Comment by kbr-scylla** [comment]
Note: the newly added `test_boot_after_ip_change` is flaky because of https://github.com/scylladb/scylladb/pull/14329 -- I'll need to merge that PR before we can merge this one.

**Comment by kbr-scylla** [comment]
I'm running update_cluster_layout_tests.py replace_address_test.py repair_based_node_operations_test.py -m 'dtest_full and not dtest_long'. Many tests have already passed, but there are lots of tests there...

I also ran each of the two regression tests that I added 100 times in dev mode (with https://github.com/scylladb/scylladb/pull/14329 cherry-picked to remove flakiness of the IP change test).

**Comment by kbr-scylla** [comment]
> CI state FAILURE - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2247/

That's the flakiness I described here https://github.com/scylladb/scylladb/pull/14507#issuecomment-1620545297

**Comment by kbr-scylla** [comment]
I queued https://github.com/scylladb/scylladb/pull/14329 and rebased this PR onto `next`.

**Comment by kbr-scylla** [comment]
> I'm running update_cluster_layout_tests.py replace_address_test.py repair_based_node_operations_test.py -m 'dtest_full and not dtest_long'.
Finished: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/1805/

**Comment by kbr-scylla** [comment]
@asias @bhalevy @tgrabiec please review

File: service/storage_service.cc [hunk 1]
```diff
@@ -5706,21 +5707,44 @@ bool storage_service::is_normal_state_handled_on_boot(gms::inet_address node) {
...
+        slogger.log(log_level::info, rate_limit, "Normal state handlers not yet finished for nodes {}",
+                    fmt_nodes_with_statuses(boost::make_iterator_range(it, eps.end())));
+
+        co_await sleep_abortable(std::chrono::milliseconds{100}, _abort_source);
     }
-    slogger.info("Finished waiting for normal state handler for nodes {}", nodes);
-    co_return;
+
+    slogger.info("Finished waiting for normal state handlers; endpoints observed in gossip: {}",
+                 fmt_nodes_with_statuses(_gossiper.get_endpoints()));
```
Comment (bhalevy) [inline service/storage_service.cc:5743]: `_gossiper.get_endpoints()` may not represent the actual nodes we waited for.
I'm not sure if that's intended or not.
Maybe you want to keep `eps` outside the loop and print it here.

File: service/storage_service.cc [hunk 2]
```diff
@@ -1958,26 +1958,37 @@ future<> storage_service::join_token_ring(cdc::generation_service& cdc_gen_servi
...
+        auto& tm = get_token_metadata();
+        auto ignore_nodes = ri
+                ? parse_node_list(_db.local().get_config().ignore_dead_nodes_for_replace(), tm)
+                // TODO: specify ignore_nodes for bootstrap
+                : std::unordered_set<gms::inet_address>{};
+
+        std::vector<gms::inet_address> sync_nodes;
+        tm.get_topology().for_each_node([&] (const locator::node* np) {
+            auto ep = np->endpoint();
+            if (!ignore_nodes.contains(ep) && (!ri || ep != ri->address)) {
```
Comment (bhalevy) [inline service/storage_service.cc:1984]: very good.
as a follow up we can change `parse_node_list` to return a list of `host_id`s and compare `host_id`s here instead of ip addresses, as they are available in `locator::node` and in `replacement_info`.

**Comment by bhalevy** [comment]
Looks good to me overall.

I wonder if it also solves https://github.com/scylladb/scylladb/issues/13775
@kbr-scylla can you please check that?
If it does, we should add the scenario described there to our regression unit tests

**Comment by kbr-scylla** [comment]
@bhalevy unfortunately it doesn't.
The exception described in https://github.com/scylladb/scylladb/issues/13775 comes from `prepare_replacement_info`, which is called before we even start gossiping. It uses information from the shadow round directly.

I guess it regressed when we started reusing Host ID of replaced node.

A potential fix would be to resolve the Host ID conflict inside `prepare_replacement_info` based on generation numbers, the same as we do when calculating `token_metadata`. But it's outside this PR's scope.

File: service/storage_service.cc (hunk 1 above)
Comment (kbr-scylla) [reply service/storage_service.cc:5743]: > _gossiper.get_endpoints() may not represent the actual nodes we waited for.

I wanted to print *all* nodes present in gossiper at the time we waited.

>  Maybe you want to keep eps outside the loop and print it here.

Right. It should be the same as `_gossiper.get_endpoints()` because there's no yield between the `break` and this print, but a better solution would be to keep `eps`. I'll send a v2

**Comment by kbr-scylla** [comment]
v2:
- keep `eps` outside the loop in `wait_for_normal_state_handled_on_boot`

Diff: https://github.com/scylladb/scylladb/compare/d53c7f00b6eda1823f918ca69c09d5cd34b69d5d..431a8f85911841e47b5b937f57160e0340d970b4

**Review by bhalevy — APPROVED** [review]

**Comment by kbr-scylla** [comment]
@tgrabiec please review/merge

**Comment by kbr-scylla** [comment]
@tgrabiec ping
