### PR TITLE
replica: Fix split compaction when tablet boundaries change

### LINKED ISSUE #24153: token_group_based_splitting_mutation_writer - Token group id cannot go backwards, current=0, previous=1
On top of latest scylla.git master 2ceecc9d2a098b5a58c75be2d17550f8974545af,  I saw the following error with the attached pytest reproducer. 

```
DEBUG 2025-05-14 13:37:41,183 [shard 0:main] table - Sealing active memtable of system.raft, partitions: 1, occupancy: 6.06%, 7937 / 131072 [B]
DEBUG 2025-05-14 13:37:41,183 [shard 0:main] table - seal_active_memtable: adding memtable
DEBUG 2025-05-14 13:37:41,183 [shard 0:main] table - system.raft new sstable generation 3gq9_0fmt_1381c2weq3fv5ah9na
DEBUG 2025-05-14 13:37:41,183 [shard 0:main] table - Flushing to /home/asias/src/cloudius-systems/scylla/testlog/dev/scylla-1/data/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gq9_0fmt_1381c2weq3fv5ah9na-big-Data.db
DEBUG 2025-05-14 13:37:41,183 [shard 0:main] table - Flushing to /home/asias/src/cloudius-systems/scylla/testlog/dev/scylla-1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-3gq9_0fmt_11ib42weq3fv5ah9na-big-Data.db done
DEBUG 2025-05-14 13:37:41,183 [shard 0:main] table - Memtable for system.peers replaced, into 1 sstables
INFO  2025-05-14 13:37:41,183 [shard 0:comp] compaction - [Compact system.peers 8d88ecf1-3085-11f0-beb7-2531ac857916] Compacting [/home/asias/src/cloudius-systems/scylla/testlog/dev/scylla-1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-3gq9_0fms_0yq012weq3fv5ah9na-big-Data.db:level=0:origin=compaction,/home/asias/src/cloudius-systems/scylla/testlog/dev/scylla-1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-3gq9_0fmt_11ib42weq3fv5ah9na-big-Data.db:level=0:origin=memtable]
DEBUG 2025-05-14 13:37:41,183 [shard 0: gms] raft_topology - reload raft topology state
ERROR 2025-05-14 13:37:41,184 [shard 0:strm] token_group_based_splitting_mutation_writer - Token group id cannot go backwards, current=0, previous=1, at: /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x58d95e /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x58dc00 /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x58df08 /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x3bf137 0x2eefeff 0x2eefbf1 0x2eef8d8 0x2eee3bf 0x12fb95a /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x40d0c3 /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x40e45a /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x40f5c7 /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x40ea78 /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x37e90a /home/asias/src/cloudius-systems/scylla/build/dev/seastar/libseastar.so+0x37db29 0x1284037 0x128291e /lib64/libc.so.6+0x3247 /lib64/libc.so.6+0x330a 0x1281264
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::(anonymous namespace)::thread_wake_task
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>, seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>, seastar::future<sstables::compaction_result> >(seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)> >(seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state
```
This can be reproduced pretty easily with:

```
./test.py --save-log-on-success -s --repeat 50 --mode dev -v cluster/test_tablet_repair_scheduler::test_tablet_incremental_repair_with_split_and_merge 
```

logs:
[pytest.log.tar.gz](https://github.com/user-attachments/files/20200980/pytest.log.tar.gz)

reproducer patch:
[0001-test_split_merge_error.zip](https://github.com/user-attachments/files/20200993/0001-test_split_merge_error.zip)

I am not sure if this is related to the error inject hack to trigger split and merge forcefully. 

```
--- a/service/tablet_allocator.cc
+++ b/service/tablet_allocator.cc
@@ -1285,6 +1285,15 @@ class load_balancer {
                 maybe_apply({table_plan.current_tablet_count, "current count"});
             }
 
+            if (utils::get_local_injector().enter("tablet_force_tablet_count_increase")) {
+                lblogger.info("HJ2: Table {} ({}.{}) current_tablet_count={}", table, s->ks_name(), s->cf_name(), tablet_count);
+                target_tablet_count = {tablet_count * 2, "force_tablet_count_increase"};
+            } else if (utils::get_local_injector().enter("tablet_force_tablet_count_decrease")) {
+                lblogger.info("HJ3: Table {} ({}.{}) current_tablet_count={}", table, s->ks_name(), s->cf_name(), tablet_count);
+                auto size = std::max(size_t(1), tablet_count / 2);
+                target_tablet_count = {size, "force_tablet_count_decrease"};
+            }
+
```

### PR DESCRIPTION
**Pull request by raphaelsc**
Consider the following:
1) balancer emits split decision
2) split compaction starts
3) split decision is revoked
4) emits merge decision
5) completes merge, before compaction in step 2 finishes

After last step, split compaction initiated in step 2 can fail because it works with the global tablet map, rather than the map when the compaction started. With the global state changing under its feet, on merge, the mutation splitting writer will think it's going backwards since sibling tablets are merged.

This problem was also seen when running load-and-stream, where split initiated by the sstable writer failed, split completed, and the unsplit sstable is left in the table dir, causing problems in the restart.

To fix this, let's make split compaction always work with the state when it started, not a global state.

Fixes #24153.

All 2025.* versions are vulnerable, so fix must be backported to them.

### CODE REVIEW

File: replica/table.cc [hunk 1]
```diff
@@ -1108,16 +1108,21 @@ bool table::all_storage_groups_split() {
     return _sg_manager->all_storage_groups_split();
 }
 
-sstables::compaction_type_options::split tablet_storage_group_manager::split_compaction_options() const noexcept {
-    return {[this](dht::token t) {
+future<sstables::compaction_type_options::split> tablet_storage_group_manager::split_compaction_options() const noexcept {
```
Comment (bhalevy) [inline replica/table.cc:1111]: Let's refactor this patch and make `split_compaction_options()` async as a technical preparation patch, to reduce the churn in the next patch.

File: test/cluster/test_tablets2.py [hunk 2]
```diff
@@ -1632,3 +1632,72 @@ async def force_minor_compaction():
...
+@skip_mode('release', 'error injections are not supported in release mode')
+async def test_split_correctness_on_tablet_count_change(manager: ManagerClient):
+    logger.info('Bootstrapping cluster')
+    cfg = { 'enable_tablets': True,
+            'tablet_load_stats_refresh_interval_in_seconds': 1
+            }
+    cmdline = [
+        '--logger-log-level', 'load_balancer=debug',
+        '--logger-log-level', 'debug_error_injection=debug',
+        '--smp', '1',
```
Comment (bhalevy) [inline test/cluster/test_tablets2.py]: why `--smp 1`?
doesn't it weaken the test?

File: test/cluster/test_tablets2.py [hunk 3]
```diff
@@ -1632,3 +1632,72 @@ async def force_minor_compaction():
...
+
+    logger.info(f'server_id = {server.server_id}')
+
+    cql = manager.get_cql()
+
+    await manager.api.disable_tablet_balancing(server.ip_addr)
+
+    inital_tablets = 2
+
+    async with new_test_keyspace(manager, f"WITH replication = {{'class': 'NetworkTopologyStrategy', 'replication_factor': 1}} AND tablets = {{'initial': {inital_tablets}}}") as ks:
```
Comment (bhalevy) [inline test/cluster/test_tablets2.py]: please use the modern, per-table `tablets = {{ 'min_tablet_count': {initial_tablets} }}` option

File: test/cluster/test_tablets2.py [hunk 4]
```diff
@@ -1632,3 +1632,72 @@ async def force_minor_compaction():
...
+        # insert data
+        pks = range(256)
+        await asyncio.gather(*[cql.run_async(f"INSERT INTO {ks}.test (pk, c) VALUES ({k}, {k});") for k in pks])
+
+        # flush the table
+        await manager.api.flush_keyspace(server.ip_addr, ks)
+
+        # force split on the test table
+        expected_tablet_count = 4
+        await cql.run_async(f"ALTER KEYSPACE {ks} WITH tablets = {{'initial': {expected_tablet_count}}}")
```
Comment (bhalevy) [inline test/cluster/test_tablets2.py]: please alter the table min_tablet_count option instead.

File: test/cluster/test_tablets2.py [hunk 5]
```diff
@@ -1632,3 +1632,72 @@ async def force_minor_compaction():
...
+        await manager.api.enable_injection(server.ip_addr, "splitting_mutation_writer_switch_wait", one_shot=True)
+        await manager.api.enable_tablet_balancing(server.ip_addr)
+
+        await log.wait_for('Emitting resize decision of type split', from_mark=log_mark)
+        await log.wait_for('splitting_mutation_writer_switch_wait: waiting', from_mark=log_mark)
+
+        await manager.api.enable_injection(server.ip_addr, "merge_completion_fiber", one_shot=True)
+
+        expected_tablet_count = 1
+        await cql.run_async(f"ALTER KEYSPACE {ks} WITH tablets = {{'initial': {expected_tablet_count}}}")
```
Comment (bhalevy) [inline test/cluster/test_tablets2.py]: ditto

File: test/cluster/test_tablets2.py (hunk 2 above)
Comment (raphaelsc) [reply test/cluster/test_tablets2.py]: It (using smp > 1) interacts badly with the error injection, since the split task that was paused might be migrated within the node, causing the test to hang. So it was a necessity.

Comment (bhalevy) [reply test/cluster/test_tablets2.py]: So please add a comment in the code justifying it, for the next developer to touch it :)

File: replica/table.cc (hunk 1 above)
Comment (raphaelsc) [reply replica/table.cc:1111]: Sure.

File: test/cluster/test_tablets2.py (hunk 2 above)
Comment (raphaelsc) [reply test/cluster/test_tablets2.py]: Sure :-)

**Comment by yaronkaikov** [comment]
> #### 🟢 CI State: SUCCESS
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider4.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider4.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)
> 🔹 cluster/test_tablets2	✅	spider4.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider6.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider6.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)
> 🔹 cluster/test_tablets2	✅	spider6.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider7.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider7.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)
> 🔹 cluster/test_tablets2	✅	spider7.cloudius-systems.com
> dtest	[dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/10084/)	✅	
> [dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/18189/)	✅	
> [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/6836/)	✅	
> #### Build Details:
> * Duration: 4 hr 59 min

@raphaelsc Although  the CI reported as passed, we see in the actual job there is a failure, we are investing this to understand this issue, but FYI, so this will not be queue

**Comment by raphaelsc** [comment]
> > #### 🟢 CI State: SUCCESS
> > Mode	Stage	Status	Node
> > [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider9.cloudius-systems.com
> > dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider4.cloudius-systems.com
> > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider4.cloudius-systems.com
> > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)
> > 🔹 cluster/test_tablets2	✅	spider4.cloudius-systems.com
> > release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider6.cloudius-systems.com
> > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider6.cloudius-systems.com
> > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)
> > 🔹 cluster/test_tablets2	✅	spider6.cloudius-systems.com
> > debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider7.cloudius-systems.com
> > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)	✅	spider7.cloudius-systems.com
> > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19284/)
> > 🔹 cluster/test_tablets2	✅	spider7.cloudius-systems.com
> > dtest	[dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/10084/)	✅
> > [dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/18189/)	✅
> > [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/6836/)	✅
> > #### Build Details:
> > 
> > * Duration: 4 hr 59 min
> 
> @raphaelsc Although the CI reported as passed, we see in the actual job there is a failure, we are investing this to understand this issue, but FYI, so this will not be queue

https://github.com/scylladb/scylladb/issues/25733

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)	✅	i-02a3c238a4fbc4cc0
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)	✅	i-02a3c238a4fbc4cc0
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)
> 🔹 cluster/test_tablets2	✅	i-02a3c238a4fbc4cc0
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)	❌	i-0e21c77b80bad5a1f
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)	✅	i-08fff2e9c7b638caa
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19350/)	❌	i-08fff2e9c7b638caa
> #### Build Details:
> * Duration: 2 hr 54 min

@yaronkaikov it seems both (last two ones) were aborted.

**Comment by yaronkaikov** [comment]
This ci is from 2 days ago. There was a configuration issue with our asg in Aws 

Please rerun ci

**Comment by raphaelsc** [comment]
@tgrabiec please review it too

**Comment by raphaelsc** [comment]
> @tgrabiec please review it too

ping

File: replica/table.cc [hunk 6]
```diff
@@ -1147,7 +1147,7 @@ future<> tablet_storage_group_manager::maybe_split_compaction_group_of(size_t id
                                           idx, schema()->ks_name(), schema()->cf_name()));
     }
 
-    return sg->split(split_compaction_options(), tablet_split_task_info);
+    co_return co_await sg->split(co_await split_compaction_options(), tablet_split_task_info);
```
Comment (tgrabiec) [inline replica/table.cc:1155]: What guarantees that `sg` reference is stable? That is, _storage_groups is not modified betwee `co_await` on `split_compaction_options()` and dereference of `sg`?

File: locator/tablets.hh [hunk 7]
```diff
@@ -664,6 +664,8 @@ private:
 public:
     bool balancing_enabled() const { return _balancing_enabled; }
     const tablet_map& get_tablet_map(table_id id) const;
+    // Gets new foreign ptr with shared ownership of tablet metadata.
```
Comment (tgrabiec) [inline locator/tablets.hh]: You mean shared ownership of tablet_map? tablet_metadata is not owned by this pointer.

File: replica/table.cc (hunk 6 above)
Comment (raphaelsc) [reply replica/table.cc:1155]: you're right better copy it here.

File: locator/tablets.hh (hunk 7 above)
Comment (raphaelsc) [reply locator/tablets.hh]: Will rephase for clarity.

**Comment by raphaelsc** [comment]
v2: 
- fixed potential dangling reference of storage group
- rephrased description of new get_tablet_map_ptr()

File: locator/tablets.cc [hunk 8]
```diff
@@ -284,6 +284,15 @@ const tablet_map& tablet_metadata::get_tablet_map(table_id id) const {
     }
 }
 
+future<tablet_metadata::tablet_map_ptr> tablet_metadata::get_tablet_map_ptr(table_id id) const {
+    try {
+        // lightweight since it only copies the shared ptr, not the map itself.
+        co_return co_await _tablets.at(id).copy();
+    } catch (const std::out_of_range&) {
+        throw_with_backtrace<no_such_tablet_map>(id);
```
Comment (avikivity) [inline locator/tablets.cc:292]: Shouldn't we cancel the split compaction if tablet split is cancelled?

Comment (raphaelsc) [reply locator/tablets.cc:292]: > Shouldn't we cancel the split compaction if tablet split is cancelled?

I don't think cancelling split is a guarantee because it happens in background, and a merge can still happen while the job is being cancelled. So I decided to make split stable first, fixing the problem observed, and later we implement split cancelling properly, which will cancel all split jobs in background since the reaction to token metadata changes happens in a non futurized path. At the end of the day, we'd have both fixes, I implemented this one first.

**Review by tgrabiec — APPROVED** [review]

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint please help queueing

**Comment by bhalevy** [comment]
> @scylladb/scylla-maint please help queueing

@raphaelsc github reports failed unit tests
e.g. https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/19604/testReport/junit/cluster.dtest.commitlog_test/TestCommitLog/dev___test_py___dev___test_one_big_mutation_corrupted_on_startup_dev_1/
```
AssertionError: assert not [('WARN  2025-09-07 12:43:46,174 [shard 0:  mt] large_data - Writing large row test_ks/big_commitlog:  (20971847 bytes) to me-3gth_0r0y_0yia82o8b5w0t2yvd2-big-Data.db\n', <re.Match object; span=(45, 97), match='large_data - Writing large row test_ks/big_commit>)]
 +  where [('WARN  2025-09-07 12:43:46,174 [shard 0:  mt] large_data - Writing large row test_ks/big_commitlog:  (20971847 bytes) to me-3gth_0r0y_0yia82o8b5w0t2yvd2-big-Data.db\n', <re.Match object; span=(45, 97), match='large_data - Writing large row test_ks/big_commit>)] = grep_log('large_data - Writing large row test_ks/big_commitlog')
 +    where grep_log = <ScyllaNode name=1767 dc=dc1 rack=rack1>.grep_log
```

This is https://github.com/scylladb/scylladb/issues/25627#issuecomment-3267360188, respinned CI.

File: locator/tablets.cc (hunk 8 above)
Comment (avikivity) [reply locator/tablets.cc:292]: Cancel and wait, of course.
