### PR TITLE
service: storage_proxy: make hint write handlers cancellable

### LINKED ISSUE #8079: cql_tracing_test.TestCqlTracing.tracing_startup_test hangs on shutdown in dtest debug
Regression started at https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/721/artifact/logs-debug.2/1612888868753_cql_tracing_test.TestCqlTracing.tracing_startup_test/node2.log
```
INFO  2021-02-09 16:26:10,988 [shard 0] compaction_manager - Asked to stop
INFO  2021-02-09 16:26:10,989 [shard 0] compaction_manager - Stopping 0 ongoing compactions
INFO  2021-02-09 16:26:10,989 [shard 0] init - Signal received; shutting down
INFO  2021-02-09 16:26:10,989 [shard 0] init - Shutting down redis service
INFO  2021-02-09 16:26:10,989 [shard 0] init - Shutting down redis service was successful
INFO  2021-02-09 16:26:10,990 [shard 0] init - Shutting down view builder
INFO  2021-02-09 16:26:10,990 [shard 0] view - Stopping view builder
INFO  2021-02-09 16:26:11,007 [shard 1] compaction_manager - Asked to stop
INFO  2021-02-09 16:26:11,008 [shard 1] compaction_manager - Stopping 0 ongoing compactions
INFO  2021-02-09 16:26:11,028 [shard 0] compaction_manager - Stopped
INFO  2021-02-09 16:26:11,030 [shard 1] view - Stopping view builder
INFO  2021-02-09 16:26:11,087 [shard 1] compaction_manager - Stopped
INFO  2021-02-09 16:26:11,210 [shard 0] storage_service - Node 127.0.12.1 state jump to normal
INFO  2021-02-09 16:26:11,326 [shard 0] init - Shutting down view builder was successful
INFO  2021-02-09 16:26:11,326 [shard 0] init - Shutting down local storage
INFO  2021-02-09 16:26:11,329 [shard 0] storage_service - Drain on shutdown: starts
INFO  2021-02-09 16:26:11,331 [shard 0] storage_service - Stop transport: starts
INFO  2021-02-09 16:26:11,332 [shard 0] storage_service - Shutting down native transport
INFO  2021-02-09 16:26:11,817 [shard 0] cql_server_controller - CQL server stopped
INFO  2021-02-09 16:26:11,832 [shard 0] storage_service - Shutting down native transport was successful
INFO  2021-02-09 16:26:11,832 [shard 0] storage_service - Shutting down rpc server
INFO  2021-02-09 16:26:11,884 [shard 0] thrift_controller - Thrift server stopped
INFO  2021-02-09 16:26:11,936 [shard 0] storage_service - Shutting down rpc server was successful
INFO  2021-02-09 16:26:11,936 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2021-02-09 16:26:11,938 [shard 0] gossip - My status = NORMAL
INFO  2021-02-09 16:26:11,938 [shard 0] gossip - Announcing shutdown
INFO  2021-02-09 16:26:12,027 [shard 0] storage_service - Node 127.0.12.2 state jump to normal
INFO  2021-02-09 16:26:14,386 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2021-02-09 16:26:14,386 [shard 0] gossip - Disable and wait for gossip loop finished
INFO  2021-02-09 16:26:14,400 [shard 0] gossip - Gossip is now stopped
INFO  2021-02-09 16:26:14,401 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2021-02-09 16:26:14,462 [shard 0] storage_service - messaging_service stopped
INFO  2021-02-09 16:26:14,462 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2021-02-09 16:26:14,463 [shard 0] storage_service - stream_manager stopped
INFO  2021-02-09 16:26:14,463 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2021-02-09 16:26:14,463 [shard 0] storage_service - Stop transport: done
INFO  2021-02-09 16:26:14,463 [shard 0] storage_service - Drain on shutdown: stop_transport done
INFO  2021-02-09 16:26:14,464 [shard 0] tracing - Asked to shut down
INFO  2021-02-09 16:26:14,470 [shard 1] tracing - Asked to shut down
INFO  2021-02-09 16:26:14,475 [shard 0] tracing - Tracing is down
INFO  2021-02-09 16:26:15,465 [shard 1] tracing - Tracing is down
INFO  2021-02-09 16:26:15,467 [shard 0] storage_service - Drain on shutdown: tracing is stopped
INFO  2021-02-09 16:26:15,468 [shard 0] storage_service - Drain on shutdown: system distributed keyspace stopped
INFO  2021-02-09 16:26:15,470 [shard 0] hints_manager - Asked to stop
INFO  2021-02-09 16:26:15,470 [shard 0] hints_manager - Asked to stop
INFO  2021-02-09 16:26:15,470 [shard 0] hints_manager - Stopped
INFO  2021-02-09 16:26:15,470 [shard 0] hints_manager - Stopped
INFO  2021-02-09 16:26:15,472 [shard 1] hints_manager - Asked to stop
INFO  2021-02-09 16:26:15,473 [shard 1] hints_manager - Asked to stop
INFO  2021-02-09 16:26:15,475 [shard 1] hints_manager - Stopped
```

Scylla version c16e4a04239798c41fa140c14eabb250b5422983
Last passed at e1261d10f17c2d219f159c01ddf7fd2b122f9d6a
`git log --oneline e1261d10f17c2d219f159c01ddf7fd2b122f9d6a..c16e4a04239798c41fa140c14eabb250b5422983`
c16e4a042 migration_manager: Propagate schema changes with reads like we do on writes
4082f57ed Merge 'Make commitlog disk limit a hard limit.' from Calle Wilund
af2d1fa0d Update abseil submodule
b9a5aff7a distributed_loader: drop execute_futures function
a05adb853 database: Remove global storage proxy reference
8490c9ff6 transport: Remove global storage service reference
4498bb0a4 API: Fix aggregation in column_familiy
4be718ebf commitlog: Force earlier cycle/flush iff segment reserve is empty
be8c359a6 commitlog: Make segment allocation wait iff disk usage > max
ab55a1b4e commitlog: Do partial (memtable) flushing based on threshold
7c84b16cd commitlog: Make flush threshold configurable
c3d95811d table: Add a flush RP mark to table, and shortcut if not above

### PR DESCRIPTION
**Pull request by kbr-scylla**
The `view_update_write_response_handler` class, which is a subclass of
`abstract_write_response_handler`, was created for a single purpose:
to make it possible to cancel a handler for a view update write,
which means we stop waiting for a response to the write, timing out
the handler immediately. This was done to solve issue with node
shutdown hanging because it was waiting for a view update to finish;
view updates were configured with 5 minute timeout. See #3966, #4028.

Now we're having a similar problem with hint updates causing shutdown
to hang in tests (#8079).

`view_update_write_response_handler` implements cancelling by adding
itself to an intrusive list which we then iterate over to timeout each
handler when we shutdown or when gossiper notifies `storage_proxy`
that a node is down.

To make it possible to reuse this algorithm for other handlers, move
the functionality into `abstract_write_response_handler`. We inherit
from `bi::list_base_hook` so it introduces small memory overhead to
each write handler (2 pointers) which was only present for view update
handlers before. But those handlers are already quite large, the
overhead is small compared to their size.

Use this new functionality to also cancel hint write handlers when we
shutdown. This fixes #8079.

### CODE REVIEW

**Comment by avikivity** [comment]
The series looks good, but why the name "retirable"? it looks more like aborting or cancelling a write.

Thinking a bit more, why do we need to cancel hint writes? They only depend on the local disk and so they should complete in a reasonable amount of time. View updates depend on other nodes, and so we don't have any way to know how soon they will complete.

**Comment by kbr-scylla** [comment]
> The series looks good, but why the name "retirable"? it looks more like aborting or cancelling a write.

Hm, I don't know where I got the name from. I recall seeing it in the context of cancelling view writes and reusing it. But now I cannot find the source.

I'll rename it to "abortable" or "cancellable".

> Thinking a bit more, why do we need to cancel hint writes? They only depend on the local disk and so they should complete in a reasonable amount of time. View updates depend on other nodes, and so we don't have any way to know how soon they will complete.

A hint is first written locally to disk and later it is sent out to a remote replica. What caused the shutdown hangs that this PR fixes is the sending out to remote replica part. This is what the series cancels, not the write-to-disk part.

**Comment by nyh** [comment]
> Hm, I don't know where I got the name from. I recall seeing it in the context of cancelling view writes and reusing it. But now I cannot find the source.

Piotr Sarna explained the word (after it was already in use) in commit fc8ffe08b9fded9d7fc789a4fd125e3fd1bb5d22.

I think (but don't really remember) that one of issues of using the word "abort" is that we're not really aborting a request - it was already sent and we have no idea what happened to it - we just stop waiting for it and forget about it.

But I don't have any particular like or dislike to any of these words. I think it's even more important to have a comment explaining what the class does - no matter which word you use in its name it will be hard to guess what this class does.

**Comment by kbr-scylla** [comment]
> I think (but don't really remember) that one of issues of using the word "abort" is that we're not really aborting a request - it was already sent and we have no idea what happened to it - we just stop waiting for it and forget about it.

We're using the work "cancel" in Seastar, there's `rpc::cancellable`. You can cancel an ongoing RPC call, and of course you may do it after the message is out, you just cancel waiting for the response in that case. So maybe let's use "cancel", it's consistent with the existing Seastar terminology.

**Comment by kbr-scylla** [comment]
v2:
- use the words "cancel"/"cancellable" instead of "retire"/"retirable"
- add comment at definition of `cancellable_write_handlers_list`

**Comment by avikivity** [comment]
"retire" often means "complete after the visible effects are there". For example, a write completes from the user's point of view after CL is reached, but retires after all replicas acknowledge or timeout.

**Comment by avikivity** [comment]
> 
> > Thinking a bit more, why do we need to cancel hint writes? They only depend on the local disk and so they should complete in a reasonable amount of time. View updates depend on other nodes, and so we don't have any way to know how soon they will complete.
> 
> A hint is first written locally to disk and later it is sent out to a remote replica. What caused the shutdown hangs that this PR fixes is the sending out to remote replica part. This is what the series cancels, not the write-to-disk part.


That's sensible.

**Comment by kbr-scylla** [comment]
> CI state FAILURE - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1534/

@benipeled could you take a look?
```
11:15:03  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: a73c4822-b903-46c1-9fe1-228712c4b058
11:15:03  java.lang.NoSuchMethodError: No such DSL method 'runOrDryRunSh' found among steps [addBadge, addEmbeddableBadgeConfiguration, addErrorBadge, addHtmlBadge, addInfoBadge, addShortText, addWarningBadge, ansiColor, archive, azureKeyVault, bat, build, cache, catchError, checkout, compareVersions, createSummary, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, dockerNode, ec2, echo, emailext, emailextrecipients, envVarsForTool, error, exws, exwsAllocate, fileExists, findFiles, getContext, git, httpRequest, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, lock, mail, milestone, node, nodesByLabel, parallel, powershell, prependToFile, properties, publishChecks, publishHTML, publishIssues, pwd, pwsh, readCSV, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, recordCoverage, recordIssues, removeBadges, removeHtmlBadges, removeSummaries, resolveScm, retry, scanForIssues, script, sh, sha1, sha256, slackSend, slackUploadFile, slackUserIdFromEmail, slackUserIdsFromCommitters, sleep, splitTests, sshagent, stage, stash, step, tar, tee, throttle, timeout, timestamps, tm, tool, touch, unarchive, unstable, unstash, untar, unzip, validateDeclarativePipeline, verifySha1, verifySha256, waitForBuild, waitUntil, warnError, withAzureKeyvault, withChecks, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, withFolderProperties, wrap, writeCSV, writeFile, writeJSON, writeMavenPom, writeYaml, ws, xunit, zip] or symbols [AUnit, BoostTest, CTest, CUnit, Check, CppTest, CppUnit, Custom, FPCUnit, GenericTrigger, GitUsernamePassword, GoogleTest, JUnit, MSTest, MbUnit, NUnit2, NUnit3, PHPUnit, PVSStudio, QtTest, UnitTest, Valgrind, acuCobol, agent, ajc, all, allBranchesSame, allOf, always, analysisParser, androidLintParser, ansibleLint, ant, antFromApache, antOutcome, antPath, antTarget, any, anyOf, apiToken, apiTokenProperty, aquaScanner, arbitraryFileCache, architecture, archiveArtifacts, armCc, artifactManager, assembla, attach, authorInChangelog, authorizationMatrix, aws, axivion, axivionSuite, azureCLI, azureDownload, azureKeyVault, azureServicePrincipal, azureStorage, azureUpload, azureVMCloudRetentionStrategy, batchFile, bitbucket, bitbucketBranchDiscovery, bitbucketBuildStatusNotifications, bitbucketForkDiscovery, bitbucketPublicRepoPullRequestFilter, bitbucketPullRequestDiscovery, bitbucketServer, bitbucketSshCheckout, bitbucketTagDiscovery, bitbucketTrustEveryone, bitbucketTrustNobody, bitbucketTrustProject, bitbucketTrustTeam, bitbucketWebhookConfiguration, bitbucketWebhookRegistration, bluepearl, booleanParam, brakeman, branch, brokenBuildSuspects, brokenTestsSuspects, browser, buckminster, buildAllBranches, buildAnyBranches, buildButton, buildChangeRequests, buildDiscarder, buildDiscarders, buildNamedBranches, buildNoneBranches, buildParameter, buildRegularBranches, buildRetention, buildSelector, buildSingleRevisionOnly, buildTags, buildUser, buildUserVars, buildingTag, builtInNode, cadence, cargo, caseInsensitive, caseSensitive, ccm, certificate, cgit, changeRequest, changelog, changelogBase, changelogToBranch, changeset, checkStyle, checkoutOption, checkoutToSubdirectory, choice, choiceParam, clair, clang, clangAnalyzer, clangTidy, cleanAfterCheckout, cleanBeforeCheckout, cleanWs, clock, cloneOption, cmake, cobertura, coberturaAdapter, coberturaReportAdapter, codeAnalysis, codeChecker, codeGeneratorParser, codeNarc, command, compressBuildLog, configFile, configFileProvider, contributor, coolflux, copyArtifactPermission, copyArtifacts, copyartifact, count, coverageTotalsColumn, cpd, cppCheck, cppLint, credentials, cron, crumb, cssLint, culprits, dart, defaultFolderConfiguration, defaultView, demand, detekt, developers, diabC, disableConcurrentBuilds, disableRestartFromStage, disableResume, discoverOtherRefs, discoverOtherRefsTrait, discoverReferenceBuild, docFx, docker, dockerCert, dockerLint, dockerServer, dockerTool, dockerfile, downstream, doxygen, drMemory, dscanner, dumb, dupFinder, durabilityHint, eclipse, email-ext, embUnit, embeddedEngineerParser, envInject, envVars, envVarsFilter, environment, equals, erlc, errorProne, esLint, exact, excludeCategory, excludeFile, excludeMessage, excludeModule, excludeNamespace, excludePackage, excludeType, experimentalFlags, expression, extendedEmailPublisher, exwsGlobalConfigurationDiskPools, exwsGlobalConfigurationTemplates, exwsNodeConfigurationDiskPools, failed, fastestReadSpeed, fastestWriteSpeed, file, fileParam, filePath, findBugs, fingerprint, fingerprints, fisheye, flake8, flawfinder, flexSdk, frameOptions, freeStyle, freeStyleJob, fromDocker, fromScm, fromSource, fxcop, gcc, gcc3, gcc4, gendarme, ghsMulti, git, gitBranchDiscovery, gitHooks, gitHubBranchDiscovery, gitHubBranchHeadAuthority, gitHubExcludeArchivedRepositories, gitHubExcludeForkedRepositories, gitHubExcludePrivateRepositories, gitHubExcludePublicRepositories, gitHubForkDiscovery, gitHubIgnoreDraftPullRequestFilter, gitHubPullRequestDiscovery, gitHubSshCheckout, gitHubTagDiscovery, gitHubTopicsFilter, gitHubTrustContributors, gitHubTrustEveryone, gitHubTrustNobody, gitHubTrustPermissions, gitLab, gitList, gitParameter, gitSCM, gitTagDiscovery, gitTool, gitUsernamePassword, gitWeb, gitblit, github, githubAccessToken, githubProjectProperty, githubPush, gitiles, globalConfigFiles, gnat, gnuFortran, go, goLint, goVet, gogs, googleStorageBucketLifecycle, googleStorageBuildLogUpload, googleStorageDownload, googleStorageUpload, groovyScript, gtester, hadoLint, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, iar, iarCstat, ibLinter, ideaInspection, ignoreOnPush, inbound, includeCategory, includeFile, includeMessage, includeModule, includeNamespace, includePackage, includeType, infer, inheriting, inheritingGlobal, installSource, instances, intel, invalids, isRestartedRun, issueCommentTrigger, issues, istanbulCobertura, istanbulCoberturaAdapter, jacoco, jacocoAdapter, java, javaDoc, javadoc, jcReport, jcloudsOneOffAgent, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobBuildDiscarder, jobConfigHistory, jobName, jsHint, jsLint, junitParser, junitTestResultStorage, kiln, klocWork, kotlin, ktLint, label, lastCompleted, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, lastSuccessful, lastWithArtifacts, latestSavedBuild, legacy, legacySCM, lfs, list, local, localBranch, localBranchTrait, location, logParser, logRotator, loggedInUsersCanDoAnything, mailer, masterBuild, maven, maven3Mojos, mavenConsole, mavenErrors, mavenGlobalConfig, mavenMojos, mavenWarnings, metrowerksCodeWarrior, mineRepository, modelsim, modernSCM, mostUsableSpace, msBuild, multibranch, myPy, myView, nagFortran, namedBranchesDifferent, newContainerPerStage, node, nodeProperties, nonInheriting, none, nonresumable, not, oelintAdv, organizationFolder, otDockerLint, overrideIndexTriggers, owaspDependencyCheck, paneStatus, parallelsAlwaysFailFast, parameterizedCron, parameters, passed, password, pattern, pcLint, pep8, perBuildTag, perforce, perfpublisher, perlCritic, permalink, permanent, phabricator, php, phpCodeSniffer, phpStan, pipeline, pipeline-model, pipeline-model-docker, pipelineTriggers, pit, plainText, plugin, pmdParser, pollSCM, polyspaceParser, prefast, preserveStashes, previous, prismConfiguration, projectNamingStrategy, protoLint, proxy, pruneStaleBranch, pruneStaleTag, pruneTags, publishCoverage, pullRequestReview, puppetLint, pyDocStyle, pyLint, qacSourceCodeAnalyser, qtTranslation, queueItemAuthenticator, quietPeriod, rateLimit, rateLimitBuilds, recipients, recordCoverage, recordIssues, redmine, refSpecs, regex, remoteName, requestor, resharperInspectCode, resourceRoot, retainOnlyVariables, revApi, rfLint, rhodeCode, robocopy, ruboCop, rule, run, runParam, s3CopyArtifact, s3Upload, sSHLauncher, sarif, scala, schedule, scmGit, scmRetryCount, scriptApproval, scriptApprovalLink, search, security, separator, shell, simian, simpleBuildDiscarder, simulinkCheckParser, skipDefaultCheckout, skipStagesAfterUnstable, skipped, slackNotifier, slave, sonarQube, sourceFiles, sourceRegexFilter, sourceWildcardFilter, sparseCheckoutPaths, specific, sphinxBuild, spotBugs, ssh, sshPublicKey, sshUserPrivateKey, standard, status, string, stringParam, styleCop, styleLint, submodule, submoduleOption, sunC, suppressAutomaticTriggering, suppressFolderAutomaticTriggering, swapSpace, swiftLint, tag, tagList, taskScanner, taskingVx, teamFoundation, teamSlugFilter, testResultsAggregator, text, textParam, throttleJobProperty, tiCss, time, timestamper, timestamperConfig, timezone, tmpSpace, tnsdl, toolLocation, triggeredBy, trivy, tsLint, unsecured, untrusted, upstream, upstreamDevelopers, userIdentity, userSeed, usernameColonPassword, usernamePassword, veracodePipelineScanner, viewgit, viewsTabBar, warningsParsers, warningsPlugin, weather, wildcards, withAnt, withFolderProperties, withJclouds, workspace, x509ClientCert, xUnitDotNet, xlc, xmlLint, yamlLint, yuiCompressor, zip, zptLint] or globals [currentBuild, docker, env, manager, params, pipeline, scm]
```

**Comment by kbr-scylla** [comment]
One thing I was a bit worried about is adding the `list_base_hook` to all write handlers, but given how heavy the class already is:
```cpp
    storage_proxy::response_id_type _id;
    promise<result<>> _ready; // available when cl is achieved
    shared_ptr<storage_proxy> _proxy;
    locator::effective_replication_map_ptr _effective_replication_map_ptr;
    tracing::trace_state_ptr _trace_state;
    db::consistency_level _cl;
    size_t _total_block_for = 0;
    db::write_type _type;
    std::unique_ptr<mutation_holder> _mutation_holder;
    inet_address_vector_replica_set _targets; // who we sent this mutation to
    // added dead_endpoints as a memeber here as well. This to be able to carry the info across
    // calls in helper methods in a convinient way. Since we hope this will be empty most of the time
    // it should not be a huge burden. (flw)
    inet_address_vector_topology_change _dead_endpoints;
    size_t _cl_acks = 0;
    bool _cl_achieved = false;
    bool _throttled = false;
    error _error = error::NONE;
    std::optional<sstring> _message;
    size_t _failed = 0; // only failures that may impact consistency
    size_t _all_failures = 0; // total amount of failures
    size_t _total_endpoints = 0;
    storage_proxy::write_stats& _stats;
    lw_shared_ptr<cdc::operation_result_tracker> _cdc_operation_result_tracker;
    timer<storage_proxy::clock_type> _expire_timer;
    service_permit _permit; // holds admission permit until operation completes
    db::per_partition_rate_limit::info _rate_limit_info;
```
I concluded that "it's fine".

File: service/storage_proxy.cc [hunk 1]
```diff
@@ -1165,7 +1165,9 @@ class cas_mutation : public mutation_holder {
     };
 };
 
-class abstract_write_response_handler : public seastar::enable_shared_from_this<abstract_write_response_handler> {
+using is_cancellable = bool_class<struct cancellable_tag>;
+
```
Comment (avikivity) [inline service/storage_proxy.cc]: This raises the question: should we cancel all outstanding writes, not just hints? Nothing guarantees that regular writes don't have long timeouts too. But that's outside the scope of the series.

File: service/storage_proxy.cc [hunk 2]
```diff
@@ -1488,33 +1501,16 @@ class write_response_handler : public abstract_write_response_handler {
...
-            storage_proxy::write_stats& stats, service_permit permit, db::per_partition_rate_limit::info rate_limit_info):
-                write_response_handler(p, std::move(ermp), cl, db::write_type::VIEW, std::move(mh),
-                        std::move(targets), pending_endpoints, std::move(dead_endpoints), std::move(tr_state), stats, std::move(permit), rate_limit_info) {
-        register_in_intrusive_list(*p);
-    }
-    ~view_update_write_response_handler();
-private:
-    void register_in_intrusive_list(storage_proxy& p);
-};
-
```
Comment (avikivity) [inline service/storage_proxy.cc:1514]: @gleb-cloudius we should consolidate all the *write_response_handler:s into a single class with no virtual functions. They're just adding complexity.

**Review by avikivity — APPROVED** [review]

**Review by avikivity — APPROVED** [review]

File: service/storage_proxy.cc (hunk 1 above)
Comment (kbr-scylla) [reply service/storage_proxy.cc]: One reason not to do that is user experience. If we're shutting down gracefully, then for example any regular QUORUM read that has been already routed to this replica should finish normally. If we cancelled it then the coordinator will have to do a speculative retry which would increase latency or worse, the read will fail.

Comment (avikivity) [reply service/storage_proxy.cc]: Yes. We should drain requests that are being waited on. But should we wait for requests that were acknowledged but are still active? Probably it doesn't matter that we do, since if the remote node is down, it will be detected and the request will complete.

Why doesn't this happen for hints?

File: service/storage_proxy.cc (hunk 2 above)
Comment (gleb-cloudius) [reply service/storage_proxy.cc:1514]: They encapsulate different ways in which different CLs are handled. Differences are no huge indeed, but still will have to be replaced by switches on a CL type.

File: service/storage_proxy.cc (hunk 1 above)
Comment (kbr-scylla) [reply service/storage_proxy.cc]: > Why doesn't this happen for hints?

You mean detecting that a node is down and cancelling the hint write? It does after this PR
```cpp
void storage_proxy::on_down(const gms::inet_address& endpoint) {
    return cancel_write_handlers([endpoint] (const abstract_write_response_handler& handler) {
        const auto& targets = handler.get_targets();
        return boost::find(targets, endpoint) != targets.end();
    });
};

```

**Comment by kbr-scylla** [comment]
@avikivity should we wait for one more review, or do you think it's ready for merging?

File: service/storage_proxy.cc (hunk 2 above)
Comment (avikivity) [reply service/storage_proxy.cc:1514]: Yes, but we can abstract it on a in a different that has less repetition.

File: service/storage_proxy.cc (hunk 1 above)
Comment (avikivity) [reply service/storage_proxy.cc]: I was confused. The patch generalizes the cancel functionality from view handlers to all write handlers, and enables it for hint handlers. Too many similar things.

**Comment by avikivity** [comment]
> @avikivity should we wait for one more review, or do you think it's ready for merging?

I see I already approved it twice.

But let's wait for next to promote, it's suffering again.
