### PR TITLE
compaction: upgrade: handle keyspaces that use tablets

### LINKED ISSUE #16848: Upgrade sstables is not tablets aware (database - Tried to obtain per-keyspace effective replication map of ks but it's per-table)
Stepped on by e.g. https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/110, test_migrate_sstable_with_cell_tombstone test cases (maybe more)

```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:97
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:148
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:181
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:51
 (inlined by) seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:55
replica::keyspace::get_effective_replication_map() const at ./replica/database.cc:414
 (inlined by) replica::database::get_keyspace_local_ranges(seastar::basic_sstring<char, unsigned int, 15u, true>) at ./replica/database.cc:2592
compaction::table_upgrade_sstables_compaction_task_impl::run() at ./compaction/task_manager_module.cc:509
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/coroutine:240
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:125
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2666
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3129
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3305
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3188
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ./main.cc:670
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
main at ./main.cc:2085
/data/scylla-s3-reloc.cache/by-build-id/d8bfecc2b8e4a591dfb30d01e5bfd664f7e7a9ef/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7026fe8c129a523e07856d7c96306663ceab6e24, for GNU/Linux 3.2.0, not stripped

__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?

```

### PR DESCRIPTION
**Pull request by lkshminarayanan**
Tables in keyspaces governed by replication strategy that uses tablets, have separate effective_replication_maps. Update the upgrade compaction task to handle this when getting owned key ranges for a keyspace.

Fixes #16848

### CODE REVIEW

**Comment by lkshminarayanan** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6651/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6651/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7885/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6651/)
> 
> #### Failed Tests (2/24652):
> * [test_login_message_after_half_of_the_cluster_is_down](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6651/testReport/junit/%28root%29/test_password_login_message/Tests___Unit_Tests___test_login_message_after_half_of_the_cluster_is_down) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_login_message_after_half_of_the_cluster_is_down)

https://github.com/scylladb/scylladb/issues/17298

> * [auth_cluster.test_password_login_message.debug.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6651/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___auth_cluster_test_password_login_message_debug_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+auth_cluster.test_password_login_message.debug.3)

https://github.com/scylladb/scylladb/issues/17041

> 
> #### Build Details:
> * Duration: 1 hr 44 min
> * Builder: spider3.cloudius-systems.com

File: replica/database.cc [hunk 1]
```diff
@@ -2583,8 +2583,13 @@ const sstring& database::get_snitch_name() const {
 }
 
 dht::token_range_vector database::get_keyspace_local_ranges(sstring ks) {
+    const auto& keyspace = find_keyspace(ks);
+    if (keyspace.get_replication_strategy().is_per_table()) {
+        // return an empty range if each tables have their own effective_replication_map
+        return dht::token_range_vector();
+    }
```
Comment (raphaelsc) [inline replica/database.cc:2590]: we should encode the inability of retrieving keyspace's local ranges with optional. empty meaning not available is dangerous. 

maybe we can have two interfaces, 

dht::token_range_vector database::get_keyspace_local_ranges(sstring ks);

that will throw, as today, if replication strategy is not vnode based.

and 

std::optional<dht::token_range_vector> database::maybe_get_keyspace_local_ranges(sstring ks);

which returns nullopt if replication strategy is per table.

then we patch sstable upgrade to use the one above.

Comment (denesb) [reply replica/database.cc:2590]: Yes, as-is this is dangerous. I think we should change this method to throw an exception and adjust callers to not call it if the keyspace uses tablets.

Comment (lkshminarayanan) [reply replica/database.cc:2599]: @raphaelsc I have updated the code like you have suggested. Is this enough or should we go all the way and make `owned_ranges_ptr` optional for the entire call chain?

Comment (lkshminarayanan) [reply replica/database.cc:2599]: @denesb `get_keyspace_local_ranges` in its current implementation  internally calls `get_vnode_effective_replication_map` and it already throws an exception for keyspaces using tablets.

Comment (raphaelsc) [reply replica/database.cc:2599]: I think this new version is good. @denesb a good reason for maybe_get_keyspace_local_ranges() is that compaction layer doesn't have to be aware of replication layer. as far as it's concerned, it only wants to know if per-keyspace ranges is available on behalf of a table. The series look good to me.

**Review by denesb — APPROVED** [review]

File: replica/database.cc (hunk 1 above)
Comment (denesb) [reply replica/database.cc:2599]: Right, argree.

File: replica/database.cc [hunk 2]
```diff
@@ -2591,6 +2591,16 @@ dht::token_range_vector database::get_keyspace_local_ranges(sstring ks) {
...
 
+std::optional<dht::token_range_vector> database::maybe_get_keyspace_local_ranges(sstring ks) {
+    const auto& keyspace = find_keyspace(ks);
+    if (keyspace.get_replication_strategy().is_per_table()) {
+        // return nullopt if each tables have their own effective_replication_map
+        return std::nullopt;
+    }
+    auto my_address = get_token_metadata().get_topology().my_address();
+    return find_keyspace(ks).get_vnode_effective_replication_map()->get_ranges(my_address);
+}
```
Comment (raphaelsc) [inline replica/database.cc:2602]: nit, you already found keyspace above, you don't have to do it again.

Comment (lkshminarayanan) [reply replica/database.cc:2602]: Ack. Fixed it with a new version.
