### PR TITLE
tablets: Fix race between repair and split

### LINKED ISSUE #19378: Race between tablet split and repair
Consider the following:

```
T
0   split prepare starts
1                               repair starts
2   split prepare finishes
3                               repair adds unsplit sstables
4                               repair ends
5   split executes
```

1) If repair starts *during* 'split prepare', prepare can wait on unsplit sstables being written. But it can theoretically happen *no* sstable is being written (by repair) on this shard now, but it will soon after 'split prepare finishes'.

2) If repair starts *after* 'split prepare' and *before* 'split execution', prepare already completed and will miss unsplit sstables.

Requirement: We want split of tablets to happen in parallel to migration / repair / load-and-stream / whatever.

What we could do is to serialize 'split prepare finish' with e.g. repair. But maybe we'd need repair to move to group0 state, such that replicas can verify that no global write process is ongoing, before marking themselves as 'split prepared'.

### LINKED ISSUE #19416: Drop table during repair with LCS cause all nodes to aborting with coredumps
## Packages

Scylla version: `6.1.0~dev-20240614.bbb424a757ea` with build-id `740e6faf0c3442c27f4aa03f90efc79562caac60`

Kernel Version: `5.15.0-1063-aws`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Nemesis no_corrupt_repair was running during this job. Cluster has asymmetric shard configuration per node.
Basic payload with cs use CS=`LeveledCompactionStrategy` . The nemesis create several new keyspaces with a table, run nodetool repair and in parallel drop created tables.

When drop table was executed and repair was still running, node 3 was aborted with coredump, and then rest of the nodes starting to aborting with coredump.

```
2024-06-15T04:44:15.432+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] database - Dropping drop_table_during_repair_ks_7.standard1 with auto-snapshot
2024-06-15T04:44:15.432+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] database - Truncating drop_table_during_repair_ks_7.standard1 with auto-snapshot
2024-06-15T04:44:16.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3   !NOTICE | sudo[9215]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/coredumpctl -q --json=short
2024-06-15T04:44:16.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | sudo[9215]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
2024-06-15T04:44:16.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | sudo[9215]: pam_unix(sudo:session): session closed for user root
2024-06-15T04:44:16.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard 10:comp] compaction - [Compact keyspace1.standard1 e74bf120-2ad1-11ef-9ca7-75c6ce285e96] Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0d5k_59gzk2drfcr6scaweu-big-Data.db:level=1,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0d5o_012kw2drfcr6scaweu-big-Data.db:level=1,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0d5p_1pasg2drfcr6scaweu-big-Data.db:level=1,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0d5q_3dba82drfcr6scaweu-big-Data.db:level=1]. 662MB to 662MB (~100% of original) in 7018ms = 94MB/s. ~614144 total partitions merged to 613868.
2024-06-15T04:44:16.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard 10:comp] compaction - [Compact keyspace1.standard1 eb7cf0a0-2ad1-11ef-9ca7-75c6ce285e96] Compacting [/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cv9_2wt5c2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cuy_1daow2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0d0f_5uh5s2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cun_142wg2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cv5_0apsw2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cuj_38dtc2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cvc_54yy82drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cuu_3elkw2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cv1_33gcg2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cuq_5djlc2drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0cug_0cfj42drfcr6scaweu-big-Data.db:level=2:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-e00236602ac511ef81088b4a92e75f42/md-3gh0_0d5q_3dba82drfcr6scaweu-big-Data.db:level=1:origin=compaction]
2024-06-15T04:44:17.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  7:comp] compaction - [Compact system.truncated ec000351-2ad1-11ef-80e6-75c7ce285e96] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_43w2o1ykfqkdfznseu-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_47bj41ykfqkdfznseu-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d0t_5jjn41ykfqkdfznseu-big-Data.db:level=0:origin=compaction]
2024-06-15T04:44:17.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] database - Truncated drop_table_during_repair_ks_7.standard1
2024-06-15T04:44:17.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table drop_table_during_repair_ks_7.standard1 compaction_group=7 due to table removal
....
2024-06-15T04:44:17.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] schema_tables - Tablet metadata changed
2024-06-15T04:44:17.182+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] migration_manager - Gossiping my schema version eaf711ec-2ad1-11ef-e8e4-0f646d782eef
2024-06-15T04:44:17.183+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] schema_tables - Schema version changed to eaf711ec-2ad1-11ef-e8e4-0f646d782eef
2024-06-15T04:44:17.183+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] storage_service - All compaction groups of table e0023660-2ac5-11ef-8108-8b4a92e75f42 are split ready.
2024-06-15T04:44:17.183+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  7:comp] compaction - [Compact system.truncated ec000351-2ad1-11ef-80e6-75c7ce285e96] Compacted 3 sstables to [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_4mr341ykfqkdfznseu-big-Data.db:level=0]. 91kB to 82kB (~90% of original) in 85ms = 1MB/s. ~384 total partitions merged to 3.
2024-06-15T04:44:17.183+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  7:comp] compaction - [Compact system.truncated ec111a50-2ad1-11ef-80e6-75c7ce285e96] Compacting [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_4a3u81ykfqkdfznseu-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_4fw681ykfqkdfznseu-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_4loi81ykfqkdfznseu-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_4cw5c1ykfqkdfznseu-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-3gh0_0d5s_4i91s1ykfqkdfznseu-big-Data.db:level=0:origin=memtable]
....
2024-06-15T04:44:30.931+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  2:strm] repair - repair[5c9c8c6b-70f7-4376-b4c9-9717c8a8e62c]: stats: repair_reason=repair, keyspace=keyspace1, tables=["standard1"], ranges_nr=1, round_nr=482, round_nr_fast_path_already_synced=168, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=314, rpc_call_nr=2025, tx_hashes_nr=3876, rx_hashes_nr=11021865, duration=177.67087 seconds, tx_row_nr=52305, rx_row_nr=3876, tx_row_bytes=67159620, rx_row_bytes=9941940, row_from_disk_bytes={10.4.8.208: 16133831076, 10.4.8.211: 16069904568, 10.4.8.78: 16130470848}, row_from_disk_nr={10.4.8.208: 12565289, 10.4.8.211: 12515502, 10.4.8.78: 12562672}, row_from_disk_bytes_per_sec={10.4.8.208: 86.60069, 10.4.8.211: 86.25756, 10.4.8.78: 86.58266} MiB/s, row_from_disk_rows_per_sec={10.4.8.208: 70722.28, 10.4.8.211: 70442.06, 10.4.8.78: 70707.555} Rows/s, tx_row_nr_peer={10.4.8.208: 1259, 10.4.8.211: 51046}, rx_row_nr_peer={10.4.8.208: 3874, 10.4.8.211: 2}
2024-06-15T04:44:30.931+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  2:strm] repair - repair[5c9c8c6b-70f7-4376-b4c9-9717c8a8e62c]: completed successfully, keyspace=keyspace1
2024-06-15T04:44:30.931+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] repair - repair[5c9c8c6b-70f7-4376-b4c9-9717c8a8e62c]: Finished user-requested repair for tablet keyspace=keyspace1 tables=["standard1"] repair_id=7 tablets_repaired=15 duration=746.734s
2024-06-15T04:44:30.931+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] repair - repair[5c9c8c6b-70f7-4376-b4c9-9717c8a8e62c]: Started to shutdown off-strategy compaction updater
2024-06-15T04:44:30.931+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] repair - repair[5c9c8c6b-70f7-4376-b4c9-9717c8a8e62c]: Finished to shutdown off-strategy compaction updater
2024-06-15T04:44:30.931+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] repair - repair[5c9c8c6b-70f7-4376-b4c9-9717c8a8e62c]: completed successfully
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3  !WARNING | scylla[7526]:  [shard  0:strm] token_metadata - topology version 145 held for 746.694 [s] past expiry, released at: 0x64926fe 0x6492d10 0x6492ff8 0x3ff3ada 0x3fe3536 0x3f8db8a 0x44a8fc7 0x4a80df4 0x5f899ff 0x5f8affa 0x5f8c277 0x5f8b5e8 0x5f19587 0x5f1874c 0x13de7a8 0x13e01f0 0x13dcd79 /opt/scylladb/libreloc/libc.so.6+0x27b89 /opt/scylladb/libreloc/libc.so.6+0x27c4a 0x13da164
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, tasks::task_manager::task::start()::$_1, seastar::future<void>::then_wrapped_nrvo<void, tasks::task_manager::task::start()::$_1>(tasks::task_manager::task::start()::$_1&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, tasks::task_manager::task::start()::$_1&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] raft_topology - updating topology state: advance fence version to 146
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] storage_service - All compaction groups of table e0023660-2ac5-11ef-8108-8b4a92e75f42 are split ready.
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Examining DC eu-west (shuffle=false, balancing=true)
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Node 46190324-a87f-44d5-b525-3424c2654d98: rack=1c avg_load=3.9166666666666665, tablets=47, shards=12, state=normal
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Node 6f0a697b-bc69-4487-a7ad-4ec25db19db5: rack=1c avg_load=3.9166666666666665, tablets=47, shards=12, state=normal
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Node cc017b26-9c53-4894-a6a8-a6a8ef74d4d0: rack=1c avg_load=3.1818181818181817, tablets=35, shards=11, state=normal
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Node d8de757e-3c60-4f81-9e66-c63d94e6320b: rack=1c avg_load=3.9166666666666665, tablets=47, shards=12, state=normal
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - target node: cc017b26-9c53-4894-a6a8-a6a8ef74d4d0, avg_load: 3.1818181818181817, max: 3.9166666666666665
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Prepared 6 migrations in DC eu-west
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Table fab10730-2ace-11ef-a9b1-309849b87d65 with tablet_count=16 has an average tablet size of 287967
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Table 33517cf0-2acf-11ef-ace5-f5624bea11f2 with tablet_count=16 has an average tablet size of 194306
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Table e0023660-2ac5-11ef-8108-8b4a92e75f42 with tablet_count=16 has an average tablet size of 13475077228
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Finalizing resize decision for table e0023660-2ac5-11ef-8108-8b4a92e75f42 as all replicas agree on sequence number 3
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Prepared 7 migration plans, out of which there were 6 tablet migration(s) and 1 resize decision(s)
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] load_balancer - Split tablets for table e0023660-2ac5-11ef-8108-8b4a92e75f42, increasing tablet count from 16 to 32
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] raft_topology - updating topology state: Finished tablet split finalization
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0:strm] repair - repair[b0690c8d-9b9b-42d3-a707-5d8de11c4def]: starting user-requested repair for keyspace system_traces, repair id 8, options {"trace": "false", "primaryRange": "false", "jobThreads": "1", "incremental": "false", "parallelism": "parallel"}
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:  [shard  0: gms] table - Detected tablet split for table keyspace1.standard1, increasing from 16 to 32 tablets
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3      !ERR | scylla[7526]:  [shard  6: gms] table - Found that storage of group 3 for table e0023660-2ac5-11ef-8108-8b4a92e75f42 wasn't split correctly, therefore groups cannot be remapped with the new tablet count., at: 0x64926fe 0x6492d10 0x6492ff8 0x5f4a967 0x1c4da2b 0x1c4f839 0x1c50ca8 0x41b84f6 0x41b801b 0x41b4795 0x5f899ff 0x5f8affa 0x5f8c277 0x5fb0140 0x5f4b69a /opt/scylladb/libreloc/libc.so.6+0x8c946 /opt/scylladb/libreloc/libc.so.6+0x11296f
   --------
   seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]: Aborting on shard 6, in scheduling group gossip.
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]: Backtrace:
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5f793c8
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5fafb41
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   /opt/scylladb/libreloc/libc.so.6+0x3dbaf
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   /opt/scylladb/libreloc/libc.so.6+0x8e883
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   /opt/scylladb/libreloc/libc.so.6+0x3dafd
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   /opt/scylladb/libreloc/libc.so.6+0x2687e
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5f4a9e7
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x1c4da2b
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x1c4f839
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x1c50ca8
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x41b84f6
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x41b801b
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x41b4795
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5f899ff
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5f8affa
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5f8c277
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5fb0140
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   0x5f4b69a
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   /opt/scylladb/libreloc/libc.so.6+0x8c946
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:   /opt/scylladb/libreloc/libc.so.6+0x11296f
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3      !ERR | scylla[7526]:  [shard  0: gms] table - Found that storage of group 0 for table e0023660-2ac5-11ef-8108-8b4a92e75f42 wasn't split correctly, therefore groups cannot be remapped with the new tablet count., at: 0x64926fe 0x6492d10 0x6492ff8 0x5f4a967 0x1c4da2b 0x1c4f839 0x1c50ca8 0x422fab0 0x144edba 0x5f899ff 0x5f8affa 0x5f8c277 0x5f8b5e8 0x5f19587 0x5f1874c 0x13de7a8 0x13e01f0 0x13dcd79 /opt/scylladb/libreloc/libc.so.6+0x27b89 /opt/scylladb/libreloc/libc.so.6+0x27c4a 0x13da164
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::smp::submit_to<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&)::{lambda()#1}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::smp::submit_to<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&)::{lambda()#1}, false> >(seastar::future<void>::finally_body<seastar::smp::submit_to<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&)::{lambda()#1}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::smp::submit_to<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, auto:1&&)::{lambda()#1}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3      !ERR | scylla[7526]:  [shard  1: gms] table - Found that storage of group 7 for table e0023660-2ac5-11ef-8108-8b4a92e75f42 wasn't split correctly, therefore groups cannot be remapped with the new tablet count., at: 0x64926fe 0x6492d10 0x6492ff8 0x5f4a967 0x1c4da2b 0x1c4f839 0x1c50ca8 0x41b84f6 0x41b801b 0x41b4795 0x5f899ff 0x5f8affa 0x5f8c277 0x5fb0140 0x5f4b69a /opt/scylladb/libreloc/libc.so.6+0x8c946 /opt/scylladb/libreloc/libc.so.6+0x11296f
   --------
   seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3      !ERR | scylla[7526]:  [shard  5: gms] table - Found that storage of group 6 for table e0023660-2ac5-11ef-8108-8b4a92e75f42 wasn't split correctly, therefore groups cannot be remapped with the new tablet count., at: 0x64926fe 0x6492d10 0x6492ff8 0x5f4a967 0x1c4da2b 0x1c4f839 0x1c50ca8 0x41b84f6 0x41b801b 0x41b4795 0x5f899ff 0x5f8affa 0x5f8c277 0x5fb0140 0x5f4b69a /opt/scylladb/libreloc/libc.so.6+0x8c946 /opt/scylladb/libreloc/libc.so.6+0x11296f
   --------
   seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>
2024-06-15T04:44:30.933+00:00 longevity-50gb-12h-master-db-node-7a68d028-3      !ERR | scylla[7526]:  [shard  7: gms] table - Found that storage of group 15 for table e0023660-2ac5-11ef-8108-8b4a92e75f42 wasn't split correctly, therefore groups cannot be remapped with the new tablet count., at: 0x64926fe 0x6492d10 0x6492ff8 0x5f4a967 0x1c4da2b 0x1c4f839 0x1c50ca8 0x422fab0 0x144edba 0x5f899ff 0x5f8affa 0x5f8c277 0x5fb0140 0x5f4b69a /opt/scylladb/libreloc/libc.so.6+0x8c946 /opt/scylladb/libreloc/libc.so.6+0x11296f
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}, seastar::future<void>::then_wrapped_nrvo<void, seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}>(seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
....
```

Decoded backtrace:
```
2024-06-15T04:44:30.932+00:00 longevity-50gb-12h-master-db-node-7a68d028-3     !INFO | scylla[7526]:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:826
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:859
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:871
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:4078
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4054
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:4050
/data/scylla-s3-reloc.cache/by-build-id/740e6faf0c3442c27f4aa03f90efc79562caac60/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9148cab1b932d44ef70e306e9c02ee38d06cad51, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:57
replica::tablet_storage_group_manager::handle_tablet_split_completion(locator::tablet_map const&, locator::tablet_map const&) at ./replica/table.cc:2107
replica::tablet_storage_group_manager::update_effective_replication_map(locator::effective_replication_map const&, seastar::noncopyable_function<void ()>) at ./replica/table.cc:2150
replica::table::update_effective_replication_map(seastar::shared_ptr<locator::effective_replication_map const>) at ./replica/table.cc:2197
operator() at ./service/storage_service.cc:3059
seastar::future<void> std::__invoke_impl<seastar::future<void>, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&>(std::__invoke_other, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::__invoke_result<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&>::type std::__invoke<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&>(service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, std::tuple<service::storage_service&>, 0ul>(service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, std::tuple<service::storage_service&>&&, std::integer_sequence<unsigned long, 0ul>) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/tuple:2288
 (inlined by) decltype(auto) std::apply<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, std::tuple<service::storage_service&> >(service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, std::tuple<service::storage_service&>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/tuple:2299
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::apply<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&>(service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, std::tuple<service::storage_service&>&&) at ././seastar/include/seastar/core/future.hh:2000
 (inlined by) auto seastar::futurize_apply<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, service::storage_service&>(service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3&, std::tuple<service::storage_service&>&&) at ././seastar/include/seastar/core/future.hh:2075
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:766
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}>(std::__invoke_other, seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::__invoke_result<seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}>::type std::__invoke<seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}>(seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}, std::tuple<>>(seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/tuple:2288
 (inlined by) decltype(auto) std::apply<seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}, std::tuple<> >(seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&)::{lambda()#1}&&, std::tuple<>&&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/tuple:2299
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:765
 (inlined by) seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}&, service::storage_service&>(std::__invoke_other, seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}&, service::storage_service&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}&, service::storage_service&>, seastar::future<void> >::type std::__invoke_r<seastar::future<void>, seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}&, service::storage_service&>(std::enable_if&&, (seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}&)...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:114
 (inlined by) std::_Function_handler<seastar::future<void> (service::storage_service&), seastar::sharded<service::storage_service>::invoke_on_all<service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3>(seastar::smp_submit_to_options, service::storage_service::replicate_to_all_cores(seastar::lw_shared_ptr<locator::token_metadata>)::$_3)::{lambda(service::storage_service&)#1}>::_M_invoke(std::_Any_data const&, service::storage_service&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<seastar::future<void> (service::storage_service&)>::operator()(service::storage_service&) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) operator() at ././seastar/include/seastar/core/sharded.hh:747
 (inlined by) seastar::future<void> seastar::futurize<seastar::future<void> >::invoke<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:2032
 (inlined by) seastar::smp_message_queue::async_work_item<seastar::sharded<service::storage_service>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (service::storage_service&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose() at ././seastar/include/seastar/core/smp.hh:249
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2696
seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3159
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3327
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4570
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:90
start_thread at ??:?
__clone3 at :?


```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-7a68d028-4 (3.249.70.79 | 10.4.8.211) (shards: 12)
- longevity-50gb-12h-master-db-node-7a68d028-3 (54.74.203.240 | 10.4.8.78) (shards: 12)
- longevity-50gb-12h-master-db-node-7a68d028-2 (54.171.112.2 | 10.4.8.208) (shards: 12)
- longevity-50gb-12h-master-db-node-7a68d028-1 (52.51.5.122 | 10.4.8.109) (shards: 11)

OS / Image: `ami-00405e229e14d65e0` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `7a68d028-e08d-43df-bf7c-07f9f861a848`
Test name: `scylla-master/tier1/longevity-150gb-asymmetric-cluster-12h-test`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ef159f51300dcee27f8840519da803dabe1d54ef/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7a68d028-e08d-43df-bf7c-07f9f861a848`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7a68d028-e08d-43df-bf7c-07f9f861a848)
- Show all stored logs command: `$ hydra investigate show-logs 7a68d028-e08d-43df-bf7c-07f9f861a848`

## Logs:
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-2-2024-06-15_04-56-10.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9247.1718427109000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9247.1718427109000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9247.1718427109000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9247.1718427109000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-1-2024-06-15_04-56-23.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10159.1718427120000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10159.1718427120000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10159.1718427120000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10159.1718427120000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_04-58-16.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.9881.1718427237000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.9881.1718427237000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.9881.1718427237000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.9881.1718427237000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_04-58-35.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9483.1718427258000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9483.1718427258000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9483.1718427258000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9483.1718427258000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-1-2024-06-15_04-58-56.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10347.1718427270000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10347.1718427270000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10347.1718427270000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10347.1718427270000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_05-02-57.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10257.1718427518000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10257.1718427518000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10257.1718427518000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10257.1718427518000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-03-22.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9747.1718427538000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9747.1718427538000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9747.1718427538000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.9747.1718427538000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-2-2024-06-15_05-03-35.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9719.1718427548000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9719.1718427548000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9719.1718427548000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.9719.1718427548000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-1-2024-06-15_05-04-07.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10619.1718427585000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10619.1718427585000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10619.1718427585000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10619.1718427585000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_05-05-31.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10420.1718427660000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10420.1718427660000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10420.1718427660000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10420.1718427660000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-1-2024-06-15_05-06-40.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10816.1718427731000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10816.1718427731000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10816.1718427731000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.10816.1718427731000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-08-03.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10051.1718427826000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10051.1718427826000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10051.1718427826000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10051.1718427826000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_05-08-03.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10581.1718427814000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10581.1718427814000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10581.1718427814000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10581.1718427814000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-2-2024-06-15_05-08-30.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10022.1718427842000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10022.1718427842000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10022.1718427842000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10022.1718427842000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-10-33.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10241.1718427968000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10241.1718427968000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10241.1718427968000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10241.1718427968000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-1-2024-06-15_05-11-50.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11104.1718428046000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11104.1718428046000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11104.1718428046000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11104.1718428046000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_05-12-45.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10853.1718428106000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10853.1718428106000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10853.1718428106000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.10853.1718428106000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-2-2024-06-15_05-13-23.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10335.1718428137000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10335.1718428137000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10335.1718428137000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10335.1718428137000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-1-2024-06-15_05-14-22.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11266.1718428192000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11266.1718428192000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11266.1718428192000000/core.scylla.112.e1d48ee798f347bbb8c2ac2af539d7ba.11266.1718428192000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-15-19.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10505.1718428255000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10505.1718428255000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10505.1718428255000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10505.1718428255000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_05-15-19.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11013.1718428248000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11013.1718428248000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11013.1718428248000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11013.1718428248000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-17-37.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10672.1718428398000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10672.1718428398000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10672.1718428398000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10672.1718428398000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-3-2024-06-15_05-17-39.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11190.1718428400000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11190.1718428400000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11190.1718428400000000/core.scylla.112.ef5f457521c9465db4dba85819711dbb.11190.1718428400000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-2-2024-06-15_05-17-49.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10640.1718428431000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10640.1718428431000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10640.1718428431000000/core.scylla.112.6f00907f6f264d2986cb3eab8d1749ed.10640.1718428431000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-19-48.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10837.1718428544000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10837.1718428544000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10837.1718428544000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10837.1718428544000000.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-7a68d028-4-2024-06-15_05-22-09.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10983.1718428691000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10983.1718428691000000.gz](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10983.1718428691000000/core.scylla.112.b4d10a34e2804bb787a0311a1a6271a4.10983.1718428691000000.gz)
- **db-cluster-7a68d028.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/db-cluster-7a68d028.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/db-cluster-7a68d028.tar.gz)
- **sct-runner-events-7a68d028.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/sct-runner-events-7a68d028.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/sct-runner-events-7a68d028.tar.gz)
- **sct-7a68d028.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/sct-7a68d028.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/sct-7a68d028.log.tar.gz)
- **loader-set-7a68d028.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/loader-set-7a68d028.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/loader-set-7a68d028.tar.gz)
- **monitor-set-7a68d028.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/monitor-set-7a68d028.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7a68d028-e08d-43df-bf7c-07f9f861a848/20240615_053037/monitor-set-7a68d028.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-150gb-asymmetric-cluster-12h-test/20/)
[Argus](https://argus.scylladb.com/test/7f604213-5cad-4418-921e-1ca98918071c/runs?additionalRuns[]=7a68d028-e08d-43df-bf7c-07f9f861a848)
</details>

### PR DESCRIPTION
**Pull request by raphaelsc**
Consider the following:

```
T
0   split prepare starts
1                               repair starts
2   split prepare finishes
3                               repair adds unsplit sstables
4                               repair ends
5   split executes
```

If repair produces sstable after split prepare phase, the replica will not split that sstable later, as prepare phase is considered completed already. That causes split execution to fail as replicas weren't really prepared. This also can be triggered with load-and-stream which shares the same write (consumer) path.

The approach to fix this is the same employed to prevent a race between split and migration. If migration happens during prepare phase, it can happen source misses the split request, but the tablet will still be split on the destination (if needed). Similarly, the repair writer becomes responsible for splitting the data if underlying table is in split mode. That's implemented in replica::table for correctness, so if node crashes, the new sstable missing split is still split before added to the set.

Fixes #19378.
Fixes #19416.

**Please replace this line with justification for the backport/\* labels added to this PR**

### CODE REVIEW

**Comment by raphaelsc** [comment]
marking it as RFC since I want to agree on the direction first. reviewers, please take a look at FIXME comment in streaming/consumer.cc

**Comment by raphaelsc** [comment]
@asias @tgrabiec please let me know what you think, please take a look at added FIXME, it describes the actual direction I am willing to take.

**Comment by raphaelsc** [comment]
@tgrabiec ping.

File: streaming/consumer.cc [hunk 1]
```diff
@@ -65,6 +65,12 @@ std::function<future<> (mutation_reader)> make_streaming_consumer(sstring origin
                         cf->enable_off_strategy_trigger();
                     }
                     return cf->add_sstable_and_update_cache(sst, offstrategy);
+                }).then([cf, sst] {
+                    // Streaming writer waits on split of newly added sstable if underlying table is in split mode.
+                    // FIXME: it's not safe to split after sstable was added, as a failure to split means split execute can happen later if
+                    //  the process that originated it give up due to the error. I think we need to wire the mutation splitter (consumer) instead,
+                    //  such that incoming data is split on the fly, and split sstables are added if in split mode.
+                    return cf->maybe_split_compaction_group_of(sst);
```
Comment (tgrabiec) [inline streaming/consumer.cc:73]: Yes, it's unsafe to rely on this call here. Can we hide this in add_sstable_and_update_cache(), which will add sstables only after they are split?

Splitting on the fly is good, but it's just an optimization. Preparing could start after we already started writing an unsplit sstable, and we need to handle attaching of this unsplit sstable.

Comment (asias) [reply streaming/consumer.cc:73]: I guess we should always check if the sstable to be added needs split whenever a sstable is added. Such check is cheap since we can check the [min_token, max_token] range of the sstable.

Comment (raphaelsc) [reply streaming/consumer.cc:73]: I am worried that without 'splitting on the fly', a restart of this node could cause repair failure, the sstable would be loaded into the set, and split execute can then happen and find that sstable unsplit. But I think that can be definitely handled by doing it inside add_sstable_and_update_cache() during boot. So a SSTable is only added if it satisfies the split requirement. Will proceed with the change.

Comment (raphaelsc) [reply streaming/consumer.cc:73]: > I guess we should always check if the sstable to be added needs split whenever a sstable is added. Such check is cheap since we can check the [min_token, max_token] range of the sstable.

Yeah, that's correct.

**Comment by raphaelsc** [comment]
v2: if a new sstable needs split, it will be split before being added to the sstable set.

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10818/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10818/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/sstable_compaction_test 🔹 topology_experimental_raft/test_tablets
> 
> #### Failed Tests (1/6912):
> * [test_tablet_split[foreach_compaction_group_wait].dev.9](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/10818/testReport/junit/%28root%29/test_tablets/test_tablet_split_foreach_compaction_group_wait__dev_9) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_split%5Bforeach_compaction_group_wait%5D.dev.9)
> 
> #### Build Details:
> * Duration: 2 hr 46 min
> * Builder: spider1.cloudius-systems.com

```
ERROR 2024-08-08 01:27:46,631 [shard 0:strm] cache - Fatal error during cache update: std::out_of_range (Compaction state for table [0x600004e30a00] not found), at: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x554d8e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x5553b0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x5556b8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a089e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a0a57 0x15c6730 0x1030127 0x15c63a8 0x1263ae4 0x15c1660 0x15c13cd 0x1399b75 0x14067b0 0x18d1666 0x18e4537 0x185332b 0x18512e3 0x184b7a5 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x453c23
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>, seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>, seastar::future<sstables::compaction_result> >(seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::noncopyable_function<seastar::future<sstables::compaction_result> ()>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)>, seastar::future<sstables::compaction_result>::then_wrapped_nrvo<seastar::future<sstables::compaction_result>, seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)> >(seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<sstables::compaction_result>&&, seastar::noncopyable_function<seastar::future<sstables::compaction_result> (seastar::future<sstables::compaction_result>&&)>&, seastar::future_state<sstables::compaction_result>&&)#1}, sstables::compaction_result>
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<sstables::compaction_result>::promise_type
   --------
   seastar::internal::coroutine_traits_base<std::optional<sstables::compaction_stats> >::promise_type
   --------
   seastar::shared_future<std::optional<sstables::compaction_stats> >::shared_state
Aborting on shard 0, in scheduling group streaming.
```

seems the problem being fixed here https://github.com/scylladb/scylladb/pull/19987, will replay...

**Comment by mykaul** [comment]
@raphaelsc - please resolve conflicts.

**Comment by raphaelsc** [comment]
v3: rebased on top of fix https://github.com/scylladb/scylladb/pull/19987, and resolved conflicts.

**Comment by raphaelsc** [comment]
@tgrabiec please take a look again.

File: replica/table.cc [hunk 2]
```diff
@@ -860,7 +864,13 @@ future<> storage_group::split(sstables::compaction_type_options::split opt) {
         co_return;
     }
 
+    if (_main_cg->empty()) {
+        co_return;
+    }
+    auto holder = _main_cg->async_gate().hold();
     co_await _main_cg->flush();
+    // Waits on sstables produced by repair to be integrated into main set; off-strategy is usually a no-op with tablets.
+    co_await _main_cg->get_compaction_manager().perform_offstrategy(_main_cg->as_table_state(), tasks::task_info{});
```
Comment (tgrabiec) [inline replica/table.cc:873]: Why is it necessary?

If it is, then it seems we should do it even if _main_cg->empty().

File: replica/table.cc [hunk 3]
```diff
@@ -937,11 +947,27 @@ future<> tablet_storage_group_manager::maybe_split_compaction_group_of(size_t id
...
 
+future<std::vector<sstables::shared_sstable>>
+tablet_storage_group_manager::maybe_split_sstable(const sstables::shared_sstable& sst) {
+    if (!tablet_map().needs_split()) {
+        co_return std::vector<sstables::shared_sstable>{sst};
+    }
+
+    auto& cg = compaction_group_for_sstable(sst);
+    auto holder = cg.async_gate().hold();
+    co_return co_await _t.get_compaction_manager().maybe_split_sstable(sst, cg.as_table_state(), split_compaction_options());
```
Comment (tgrabiec) [inline replica/table.cc:958]: How do we ensure that tablet_map doesn't change (split is not finalized) during split?

File: replica/table.cc (hunk 2 above)
Comment (raphaelsc) [reply replica/table.cc:873]: let's say repair produced sstable with twcs, they're placed into maintenance set, and off-strategy which integrates into main one, hasn't started yet. This call guarantee that off-strategy start before split, since split works only on main set. Any new sstable produced thereafter is guaranteed to be split either it will be added to main or maintenance set.

_main_cg->empty() means maintenance and main are empty, so there's nothing to be split.

File: replica/table.cc (hunk 3 above)
Comment (raphaelsc) [reply replica/table.cc:958]: split prepare -> repair -> split execute

repair coordinator holds erm, so under normal scenario this split happening in the context of repair cannot race with split finalization.

On restart, we'll split when adding sstable, before node is online.

If coordinator crashes, erm is released, and then we can have this split racing with finalization.

Theoretically we also have this race between repair and migration right? since there's a small window between sealing a sstable and adding it to the set. If coordinator crashes, the underlying tablet can be migrated away, before the sealed sstable is added to the set.

Do we need replica to also hold erm when adding sstable to the set?

Ah we do hold erm during repair writer, so I think we're safe.

```
void repair_writer_impl::create_writer(lw_shared_ptr<repair_writer> w) {
    if (_writer_done) {
        return;
    }
    replica::table& t = _db.local().find_column_family(_schema->id());
    rlogger.debug("repair_writer: keyspace={}, table={}, estimated_partitions={}", w->schema()->ks_name(), w->schema()->cf_name(), w->get_estimated_partitions());
    service::frozen_topology_guard topo_guard = service::null_topology_guard; // FIXME: propagate
    // The sharder is valid only when the erm is valid. Keep a reference of the erm to keep the sharder valid.
    auto erm = t.get_effective_replication_map();
    auto& sharder = erm->get_sharder(*(w->schema()));
    _writer_done = mutation_writer::distribute_reader_and_consume_on_shards(_schema, sharder, std::move(_queue_reader),
            streaming::make_streaming_consumer(sstables::repair_origin, _db, _view_builder, w->get_estimated_partitions(), _reason, is_offstrategy_supported(_reason), topo_guard),
    t.stream_in_progress()).then([w, erm] (uint64_t partitions) {
```

Do you want me to redundantly hold erm during split_sstable() to enforce the requirement? Or perhaps document it.

File: replica/table.cc (hunk 2 above)
Comment (tgrabiec) [reply replica/table.cc:873]: > _main_cg->empty() means maintenance and main are empty, so there's nothing to be split.

So _main_cg includes maintenance, we're fine then.

File: replica/table.cc (hunk 3 above)
Comment (raphaelsc) [reply replica/table.cc:958]: @tgrabiec please let me know if my answer above satisfy you. like I explained, maybe_split_sstable() only happens in the context of repair / streaming, which holds the erm. on a hard reboot, we're able to continue the work before the sstable is loaded into the sstable set, and also before the node starts the messaging and group0 service.

Comment (tgrabiec) [reply replica/table.cc:958]: > Theoretically we also have this race between repair and migration right? since there's a small window between sealing a sstable and adding it to the set. If coordinator crashes, the underlying tablet can be migrated away, before the sealed sstable is added to the set.

This race is supposed to be fixed by using a `topology_guard` on the writer-side. We do use it, but it's armed only for streaming when doing a migration, for repair we pass a null guard around. 

> Ah we do hold erm during repair writer, so I think we're safe.

I think holding erm is not enough, since it can escape the barrier in split finalization:

1. handle_tablet_split_finalization() calls the barrier to wait for erm-holders. Barrier completes.
2. create_writer() takes erm, version=0, pre-split
4. handle_tablet_split_finalization() commits the split, all replicas change current erm to post-split
5. repair writer tries to add sstable, sees that need split is false, adds an sstable which crosses tablet boundary

We could protect against this by always checking if the sstable we try to add crosses the tablet boundary, and keep splitting it until it doesn't and atomically add it to the group. Then at least the invariant about non-overlapping would be satisfied based on local reasoning about the state of the local compaction groups, we wouldn't rely on any global reasoning about synchronization. This is more robust, because global synchronization is harder to prove.

Comment (tgrabiec) [reply replica/table.cc:958]: I think this can be addressed as a follow up so I queued the PR.

Comment (raphaelsc) [reply replica/table.cc:958]: "This race is supposed to be fixed by using a topology_guard on the writer-side. We do use it, but it's armed only for streaming when doing a migration, for repair we pass a null guard around." Why don't we do the same for repair? What's the downside?

Split compaction happens today with assumption of tablet count stability, it also spans a single tablet. If we go this direction, it might have to work with a snapshot. Will we have this problem you mentioned once we move repair to state machine?

Comment (raphaelsc) [reply replica/table.cc:958]: "2. create_writer() takes erm, version=0, pre-split"

but before step 2, won't we have repair coordinator waiting for coordinator to be quiesced? And if repair doesn't go through the coordinator, doesn't it mean it's also susceptible to other races for example with migration? since it can produce a sstable in a node to a tablet that was migrated away?

Comment (raphaelsc) [reply replica/table.cc:958]: we wouldn't silently add the sstable that overlaps 2 tablets, the same way we won't add a sstable silently if the tablet was migrated away. both scenarios result in a failure, and if that happen, it means a coordination side problem, right? for example, manager didn't disable balancing temporarily if it skipped repair coordinator somehow.

Comment (tgrabiec) [reply replica/table.cc:958]: >> "This race is supposed to be fixed by using a topology_guard on the writer-side. We do use it, but it's armed only for streaming when doing a migration, for repair we pass a null guard around." 
> Why don't we do the same for repair? What's the downside?

To arm topology_guard we need a valid session, which is currently propagated via group0, stored in tablet table. Moving repair to tablet transition state would naturally fit into this, otherwise we'd have to invent a new way to propagate and invalidate sessions, which will be difficult to do correctly without moving repair to tablet scheduler because when the repair coordinator dies, there is noone who would invalidate the session before erm is released. When repair is a transition, it will null the session field in system.tablet before transition ends, so before we move to a different transition on the tablet (including split finalization).   

> 
> Split compaction happens today with assumption of tablet count stability, it also spans a single tablet. If we go this direction, it might have to work with a snapshot. Will we have this problem you mentioned once we move repair to state machine?

No, if we move repair to state machine then we won't have this problem.

Comment (tgrabiec) [reply replica/table.cc:958]: > "2. create_writer() takes erm, version=0, pre-split"
> 
> but before step 2, won't we have repair coordinator waiting for coordinator to be quiesced? And if repair doesn't go through the coordinator, doesn't it mean it's also susceptible to other races for example with migration? since it can produce a sstable in a node to a tablet that was migrated away?

This scenario assumes the current implementation of repair. Yes, we're susceptible to other races. But there may be different severity level to them. If tablet was migrated away, the sstable will fail to attach because there is no compaction group. If it happens before cleanup, we don't care about losing the data because it belongs to a failed repair. Violating the invariant that sstables don't overlap tablet boundaries is more severe.
