### PR TITLE
Prevent stalls in query_partition_key_range_concurrent

### LINKED ISSUE #14008: Constant Errors with Reactor Stalled on new Node -- Constant High Load
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.1.5
Cluster size: 3x4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Bare Metal
Hardware: sockets=1 cores=96 hyperthreading=yes memory=768GB
Disks: (SSD/HDD, count) 8x NVMe, RAID-0

After adding a node to my cluster, I have been consistently getting messages like the following in syslog:

```
Reactor stalled for 130 ms on shard 0. Backtrace: 0x4d2dd02 0x4d2c960 0x4d2dc10 0x7f245c4f8a1f 0x50095bf 0x2e44f67 0x301c36b 0x301caf3 0x300bfd0 0x300be2e 0x252ca8f 0x261828e 0x261973c 0x4d3d4f4 0x4d3e8d7 0x4d3db2c 0x4ce3a68 0x4ce2f41 0x1032b76 0x103015a 0x27b74 0x102f02d
```

The CPU load on this server has remained high even after the join completed, with these messages occurring every few seconds. This is the same server for which I had the issues mentioned in #13439, and I ended up modifying the contents of `io_properties.yaml`. The values I put in there reflect the results I got on this hardware with the `fio` tool.

Here is the decoded backtrace:

```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:774
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:793
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1368
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1110
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1127
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1351
?? ??:0
seastar::operator<<(std::ostream&, seastar::ipv6_addr const&) at ./build/release/seastar/./seastar/src/net/inet_address.cc:350
std::hash<gms::inet_address>::operator()(gms::inet_address) const at ././gms/inet_address.hh:89
 (inlined by) std::__detail::_Hash_code_base<gms::inet_address, std::pair<gms::inet_address const, gms::endpoint_state>, std::__detail::_Select1st, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>::_M_hash_code(gms::inet_address const&) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:1219
 (inlined by) std::_Hashtable<gms::inet_address, std::pair<gms::inet_address const, gms::endpoint_state>, std::allocator<std::pair<gms::inet_address const, gms::endpoint_state> >, std::__detail::_Select1st, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(gms::inet_address const&) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable.h:1608
 (inlined by) std::unordered_map<gms::inet_address, gms::endpoint_state, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, gms::endpoint_state> > >::find(gms::inet_address const&) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unordered_map.h:880
 (inlined by) gms::gossiper::get_endpoint_state_for_endpoint_ptr(gms::inet_address) const at ./gms/gossiper.cc:1335
 (inlined by) gms::gossiper::get_application_state_ptr(gms::inet_address, gms::application_state) const at ./gms/gossiper.cc:2251
locator::production_snitch_base::get_endpoint_info(gms::inet_address, gms::application_state) at ./locator/production_snitch_base.cc:63
 (inlined by) locator::production_snitch_base::get_endpoint_info(gms::inet_address, gms::application_state, seastar::basic_sstring<char, unsigned int, 15u, true> const&) at ./locator/production_snitch_base.cc:69
locator::production_snitch_base::get_datacenter(gms::inet_address) at ./locator/production_snitch_base.cc:52
locator::snitch_base::compare_endpoints(gms::inet_address&, gms::inet_address&, gms::inet_address&) at ./locator/snitch_base.cc:54
operator() at ./locator/snitch_base.cc:33
 (inlined by) bool __gnu_cxx::__ops::_Val_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0>::operator()<gms::inet_address, gms::inet_address*>(gms::inet_address&, gms::inet_address*) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/predefined_ops.h:240
 (inlined by) void std::__unguarded_linear_insert<gms::inet_address*, __gnu_cxx::__ops::_Val_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0> >(gms::inet_address*, __gnu_cxx::__ops::_Val_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1806
 (inlined by) void std::__insertion_sort<gms::inet_address*, __gnu_cxx::__ops::_Iter_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0> >(gms::inet_address*, gms::inet_address*, __gnu_cxx::__ops::_Iter_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1834
 (inlined by) void std::__final_insertion_sort<gms::inet_address*, __gnu_cxx::__ops::_Iter_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0> >(gms::inet_address*, gms::inet_address*, __gnu_cxx::__ops::_Iter_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1871
 (inlined by) void std::__sort<gms::inet_address*, __gnu_cxx::__ops::_Iter_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0> >(gms::inet_address*, gms::inet_address*, __gnu_cxx::__ops::_Iter_comp_iter<locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1957
 (inlined by) void std::sort<gms::inet_address*, locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0>(gms::inet_address*, gms::inet_address*, locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&)::$_0) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:4875
 (inlined by) locator::snitch_base::sort_by_proximity(gms::inet_address, utils::small_vector<gms::inet_address, 3ul>&) at ./locator/snitch_base.cc:30
service::storage_proxy::sort_endpoints_by_proximity(utils::small_vector<gms::inet_address, 3ul>&) at ./service/storage_proxy.cc:5027
 (inlined by) service::storage_proxy::get_live_sorted_endpoints(replica::keyspace&, dht::token const&) const at ./service/storage_proxy.cc:5037
 (inlined by) service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit) at ./service/storage_proxy.cc:4447
operator() at ./service/storage_proxy.cc:4585
seastar::future<boost::outcome_v2::basic_result<service::query_partition_key_range_concurrent_result, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> > seastar::futurize<seastar::future<boost::outcome_v2::basic_result<service::query_partition_key_range_concurrent_result, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> > >::invoke<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}&, seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >(service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}&, seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&) at ././seastar/include/seastar/core/future.hh:2149
 (inlined by) auto seastar::futurize_invoke<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}&, seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >(service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}&, seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&) at ././seastar/include/seastar/core/future.hh:2180
 (inlined by) utils::internal::result_wrapped_call_traits<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy>, false>::invoke_with_value({lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}&, utils::exception_container_throw_policy&&) at ././utils/result_combinators.hh:73
 (inlined by) auto utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>::operator()<boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy> >(boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy>) at ././utils/result_combinators.hh:124
 (inlined by) seastar::future<boost::outcome_v2::basic_result<service::query_partition_key_range_concurrent_result, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> > std::__invoke_impl<seastar::future<boost::outcome_v2::basic_result<service::query_partition_key_range_concurrent_result, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> >, utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> >(std::__invoke_other, utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::__invoke_result<utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy> >::type std::__invoke<utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy> >(std::__invoke_result&&, (utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&)...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
 (inlined by) std::invoke_result<utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy> >::type std::invoke<utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy> >(std::invoke_result&&, (utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&)...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:97
 (inlined by) auto seastar::internal::future_invoke<utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy> >(utils::internal::result_wrapper<service::storage_proxy::query_partition_key_range_concurrent(std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, std::allocator<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >&&, seastar::lw_shared_ptr<query::read_command>, db::consistency_level, query_ranges_to_vnodes_generator&&, int, tracing::trace_state_ptr, unsigned long, unsigned int, std::unordered_map<nonwrapping_interval<dht::token>, std::vector<utils::UUID, std::allocator<utils::UUID> >, std::hash<nonwrapping_interval<dht::token> >, std::equal_to<nonwrapping_interval<dht::token> >, std::allocator<std::pair<nonwrapping_interval<dht::token> const, std::vector<utils::UUID, std::allocator<utils::UUID> > > > >, service_permit)::$_42::operator()() const::{lambda(seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >&&)#1}, false>&, boost::outcome_v2::basic_result<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> >, utils::exception_container<exceptions::mutation_write_timeout_exception, utils::exception_container::read_timeout_exception, utils::exception_container::read_failure_exception, utils::exception_container::rate_limit_exception>, utils::exception_container_throw_policy>&&) at ././seastar/include/seastar/core/future.hh:1225
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1596
 (inlined by) _ZN7seastar8futurizeINS_6futureIN5boost10outcome_v212basic_resultIN7service43query_partition_key_range_concurrent_resultEN5utils19exception_containerIJN10exceptions32mutation_write_timeout_exceptionENS9_22read_timeout_exceptionENS9_22read_failure_exceptionENS9_20rate_limit_exceptionEEEENS7_32exception_container_throw_policyEEEEEE22satisfy_with_result_ofIZZNS1_INS4_INS_11foreign_ptrINS_13lw_shared_ptrIN5query6resultEEEEESE_SF_EEE14then_impl_nrvoINS7_8internal14result_wrapperIZZNS5_13storage_proxy36query_partition_key_range_concurrentENSt6chrono10time_pointINS_12lowres_clockENSW_8durationIlSt5ratioILl1ELl1000000000EEEEEEOSt6vectorISP_SaISP_EENSL_INSM_12read_commandEEEN2db17consistency_levelEO32query_ranges_to_vnodes_generatoriN7tracing15trace_state_ptrEmjSt13unordered_mapI20nonwrapping_intervalIN3dht5tokenEES14_INS7_4UUIDESaIS1L_EESt4hashIS1K_ESt8equal_toIS1K_ESaISt4pairIKS1K_S1N_EEE14service_permitENK4$_42clEvEUlOSP_E_Lb0EEESH_EET0_OT_ENKUlONS_8internal22promise_base_with_typeISG_EERS21_ONS_12future_stateISQ_EEE_clES28_S29_S2C_EUlvE_EEvS28_S24_ at ././seastar/include/seastar/core/future.hh:2134
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1589
 (inlined by) _ZN7seastar12continuationINS_8internal22promise_base_with_typeIN5boost10outcome_v212basic_resultIN7service43query_partition_key_range_concurrent_resultEN5utils19exception_containerIJN10exceptions32mutation_write_timeout_exceptionENSA_22read_timeout_exceptionENSA_22read_failure_exceptionENSA_20rate_limit_exceptionEEEENS8_32exception_container_throw_policyEEEEENS8_8internal14result_wrapperIZZNS6_13storage_proxy36query_partition_key_range_concurrentENSt6chrono10time_pointINS_12lowres_clockENSM_8durationIlSt5ratioILl1ELl1000000000EEEEEEOSt6vectorINS_11foreign_ptrINS_13lw_shared_ptrIN5query6resultEEEEESaIS10_EENSW_INSX_12read_commandEEEN2db17consistency_levelEO32query_ranges_to_vnodes_generatoriN7tracing15trace_state_ptrEmjSt13unordered_mapI20nonwrapping_intervalIN3dht5tokenEESU_INS8_4UUIDESaIS1H_EESt4hashIS1G_ESt8equal_toIS1G_ESaISt4pairIKS1G_S1J_EEE14service_permitENK4$_42clEvEUlOS10_E_Lb0EEEZNS_6futureINS5_IS10_SF_SG_EEE14then_impl_nrvoIS1X_NS1Y_ISH_EEEET0_OT_EUlOSI_RS1X_ONS_12future_stateIS1Z_EEE_S1Z_E15run_and_disposeEv at ././seastar/include/seastar/core/future.hh:781
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2345
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2921
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2804
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:555
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) main at ./main.cc:1711
?? ??:0
_start at ??:?
```

### PR DESCRIPTION
**Pull request by bhalevy**
Prevent stalls caused by query_partition_key_range_concurrent
nested calls when it never yields.

Fixes #14008

### CODE REVIEW

File: service/storage_proxy.cc [hunk 1]
```diff
@@ -5527,10 +5527,10 @@ bool storage_proxy::is_worth_merging_for_range_query(
 future<result<query_partition_key_range_concurrent_result>>
 storage_proxy::query_partition_key_range_concurrent(storage_proxy::clock_type::time_point timeout,
         locator::effective_replication_map_ptr erm,
-        std::vector<foreign_ptr<lw_shared_ptr<query::result>>>&& results,
+        std::vector<foreign_ptr<lw_shared_ptr<query::result>>>& results,
```
Comment (avikivity) [inline service/storage_proxy.cc:5530]: It's not really needed. The caller holds the variable ready.

It's clearer to convert this to a value parameter. To track the lifetime, you don't need to go up to the caller, instead you see it's safe here.

btw after all this we can probably merge the caller and callee.

**Comment by avikivity** [comment]
The change is unsatisfying - it leaves the function a mix of coroutines and continuations. Further, it converts tail recursion to non-tail-recursion, so now there's a long trail of coroutines in memory awaiting the last call. The recursion should be converted to iteration.

**Comment by bhalevy** [comment]
In v2 ([6614ae2](https://github.com/scylladb/scylladb/commit/6614ae2f30a6f0563d54fc6e9895b3c09739a965)):
- turn tail-recursion into iteration

I didn't fold `query_partition_key_range_concurrent` into `query_partition_key_range` since:
a. It's out of scope for this fix
b. It makes the code complex and I'm not sure that saving the extra coroutine is worth it.

I'll see if there's and visible performance benefit to that and submit a new PR if there is one.

**Comment by avikivity** [comment]
> In v2 ([6614ae2](https://github.com/scylladb/scylladb/commit/6614ae2f30a6f0563d54fc6e9895b3c09739a965)):
> 
> * turn tail-recursion into iteration
> 
> I didn't fold `query_partition_key_range_concurrent` into `query_partition_key_range` since: a. It's out of scope for this fix b. It makes the code complex and I'm not sure that saving the extra coroutine is worth it.


The idea behind the suggestion was to simplify. If it doesn't work, then it doesn't work.

> 
> I'll see if there's and visible performance benefit to that and submit a new PR if there is one.


It will save an allocation, but it will be invisible. Scans have tons of allocations.

File: service/storage_proxy.cc [hunk 2]
```diff
@@ -5694,27 +5695,19 @@ storage_proxy::query_partition_key_range_concurrent(storage_proxy::clock_type::t
...
-            remaining_partition_count,
-            trace_state = std::move(trace_state),
-            preferred_replicas = std::move(preferred_replicas),
-            ranges_per_exec = std::move(ranges_per_exec),
-            permit = std::move(permit)] (foreign_ptr<lw_shared_ptr<query::result>>&& result) mutable {
+    if (!wrapped_result) {
+        auto error = bo::failure(std::move(wrapped_result).assume_error()).error();
+        auto ex = error.as_exception_future().get_exception();
+        p->handle_read_error(std::move(error), true);
+        co_return coroutine::return_exception_ptr(std::move(ex));
```
Comment (avikivity) [inline service/storage_proxy.cc]: I'm sure this could be improved. Since this function returns a `result<>`, it could be propagated.

But, let's not mix the improvement with this series.

File: service/storage_proxy.cc [hunk 3]
```diff
@@ -5694,27 +5695,19 @@ storage_proxy::query_partition_key_range_concurrent(storage_proxy::clock_type::t
...
+    }
+
+        // FIXME: indentation
+        foreign_ptr<lw_shared_ptr<query::result>> result = std::move(wrapped_result).value();
```
Comment (avikivity) [inline service/storage_proxy.cc:5711]: You could have used assume_value() since you know it's not an error. But it doesn't matter here.

File: service/storage_proxy.cc [hunk 4]
```diff
@@ -5690,6 +5690,8 @@ storage_proxy::query_partition_key_range_concurrent(storage_proxy::clock_type::t
 
             exec.push_back(::make_shared<never_speculating_read_executor>(schema, cf.shared_from_this(), p, erm, cmd, std::move(range), cl, std::move(filtered_endpoints), trace_state, permit, std::monostate()));
             ranges_per_exec.emplace(exec.back().get(), std::move(merged_ranges));
+
+            co_await coroutine::maybe_yield();
```
Comment (avikivity) [inline service/storage_proxy.cc:5694]: I don't know if this is enough to fix the stall.  Note there is another loop on `i` above, so if we spend most of our iteration time there, we won't hit the maybe_yield here.

With 3 nodes it's likely everything was contiguous with RF=3.

File: service/storage_proxy.cc [hunk 5]
```diff
@@ -14,6 +14,8 @@
 #include "partition_range_compat.hh"
```
Comment (avikivity) [inline service/storage_proxy.cc:14]: nit: missing ':' in subject of first patch

**Comment by avikivity** [comment]
Looks much better, and it makes visible that the patch may not be enough.

File: service/storage_proxy.cc (hunk 2 above)
Comment (bhalevy) [reply service/storage_proxy.cc]: I'd do that if it wasn't for the call to `handle_read_error`...

File: service/storage_proxy.cc (hunk 4 above)
Comment (bhalevy) [reply service/storage_proxy.cc:5694]: good point, I'll add one in the inner loop (that is execute only if the replication strategy does not `uses_tablets`).

**Comment by bhalevy** [comment]
In v3 ([77c354b](https://github.com/scylladb/scylladb/commit/77c354b7e585fb831021dfec670d8a63a56d9b11))
- rebased
- cleaned up patch subject
- cleaned up stray #include directives that were auto-added by the editor.
- change maybe_yield structure to have one in the outer loop and one in the inner-loop (and spaced apart so they's make sense if both are executed)

File: service/storage_proxy.cc (hunk 2 above)
Comment (bhalevy) [reply service/storage_proxy.cc]: Hmm, this isn't so bad:
```c++
            auto error = std::move(wrapped_result).assume_error();
            p->handle_read_error(error.clone(), true);
            co_return error;
```

testing...

File: service/storage_proxy.cc (hunk 4 above)
Comment (bhalevy) [reply service/storage_proxy.cc]: fixed in v3

**Comment by bhalevy** [comment]
In v4 ([e71e5d3](https://github.com/scylladb/scylladb/commit/e71e5d3fdab44b4b2867d18d21c08ccb4834c8e2)):
- query_partition_key_range_concurrent: do not return exception on error path, but rather copy the error `result` as per https://github.com/scylladb/scylladb/pull/14884#discussion_r1278615082.

File: service/storage_proxy.cc [hunk 6]
```diff
@@ -5573,6 +5573,8 @@ storage_proxy::query_partition_key_range_concurrent(storage_proxy::clock_type::t
             std::vector<dht::token_range> merged_ranges{to_token_range(range)};
```
Comment (denesb) [inline service/storage_proxy.cc:5573]: [commitlog]: The calls are not nested anymore.

**Comment by bhalevy** [comment]
updated changelog message
