### PR TITLE
token_range_vector: fragment

### LINKED ISSUE #3335: large allocation when loading SSTables
Saw this today:

```
[shard 0] seastar_memory - oversized allocation: 409600 bytes, please report: at   0x72458d
  0x72ad26
  0x72b284
  0x143a330
  0x13c4eaf
  0x13c9391
  0x593aa6
  0x593c61
  0x6567c7
  0x777a20
  0x51cbd8
  /lib64/libc.so.6+0x21009
  0x58d759
```

Maps to:

```
seastar::memory::cpu_pages::check_large_allocation(unsigned long) at /home/glauber/scylla/seastar/core/memory.cc:637
 (inlined by) seastar::memory::cpu_pages::allocate_large(unsigned int) at /home/glauber/scylla/seastar/core/memory.cc:643
 (inlined by) seastar::memory::allocate_large(unsigned long) at /home/glauber/scylla/seastar/core/memory.cc:1213
 (inlined by) seastar::memory::allocate(unsigned long) at /home/glauber/scylla/seastar/core/memory.cc:1263
operator new(unsigned long) at /home/glauber/scylla/seastar/core/memory.cc:1666
__gnu_cxx::new_allocator<nonwrapping_range<dht::ring_position> >::allocate(unsigned long, void const*) at /usr/include/c++/7/ext/new_allocator.h:111
 (inlined by) std::allocator_traits<std::allocator<nonwrapping_range<dht::ring_position> > >::allocate(std::allocator<nonwrapping_range<dht::ring_position> >&, unsigned long) at /usr/include/c++/7/bits/alloc_traits.h:436
 (inlined by) std::_Vector_base<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::_M_allocate(unsigned long) at /usr/include/c++/7/bits/stl_vector.h:172
 (inlined by) void std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::_M_realloc_insert<nonwrapping_range<dht::ring_position> >(__gnu_cxx::__normal_iterator<nonwrapping_range<dht::ring_position>*, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > >, nonwrapping_range<dht::ring_position>&&) at /usr/include/c++/7/bits/vector.tcc:406
nonwrapping_range<dht::ring_position>& std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::emplace_back<nonwrapping_range<dht::ring_position> >(nonwrapping_range<dht::ring_position>&&) at /usr/include/c++/7/bits/vector.tcc:105
 (inlined by) _M_range_initialize<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::sstable::compute_shards_for_this_sstable() const::<lambda(const sstables::disk_token_range&)>, nonwrapping_range<dht::ring_position> >, utils::chunked_vector<sstables::disk_token_range, 131072>::iterator_type<const sstables::disk_token_range>, boost::iterators::use_default, boost::iterators::use_default> > at /usr/include/c++/7/bits/stl_vector.h:1310
 (inlined by) _M_initialize_dispatch<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::sstable::compute_shards_for_this_sstable() const::<lambda(const sstables::disk_token_range&)>, nonwrapping_range<dht::ring_position> >, utils::chunked_vector<sstables::disk_token_range, 131072>::iterator_type<const sstables::disk_token_range>, boost::iterators::use_default, boost::iterators::use_default> > at /usr/include/c++/7/bits/stl_vector.h:1299
 (inlined by) vector<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::sstable::compute_shards_for_this_sstable() const::<lambda(const sstables::disk_token_range&)>, nonwrapping_range<dht::ring_position> >, utils::chunked_vector<sstables::disk_token_range, 131072>::iterator_type<const sstables::disk_token_range>, boost::iterators::use_default, boost::iterators::use_default> > at /usr/include/c++/7/bits/stl_vector.h:414
 (inlined by) copy_range<std::vector<nonwrapping_range<dht::ring_position> >, boost::range_detail::transformed_range<sstables::sstable::compute_shards_for_this_sstable() const::<lambda(const sstables::disk_token_range&)>, const utils::chunked_vector<sstables::disk_token_range, 131072> > > at /usr/include/boost/range/iterator_range_core.hpp:873
 (inlined by) sstables::sstable::compute_shards_for_this_sstable() const at /home/glauber/scylla/sstables/sstables.cc:3088
operator() at /home/glauber/scylla/sstables/sstables.cc:1355
 (inlined by) apply at /home/glauber/scylla/seastar/core/apply.hh:36
 (inlined by) apply<sstables::sstable::open_data()::<lambda()> > at /home/glauber/scylla/seastar/core/apply.hh:44
 (inlined by) do_void_futurize_apply_tuple<sstables::sstable::open_data()::<lambda()> > at /home/glauber/scylla/seastar/core/future.hh:1330
 (inlined by) apply<sstables::sstable::open_data()::<lambda()> > at /home/glauber/scylla/seastar/core/future.hh:1350
 (inlined by) operator()<seastar::future_state<> > at /home/glauber/scylla/seastar/core/future.hh:943
 (inlined by) run_and_dispose at /home/glauber/scylla/seastar/core/future.hh:413
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/glauber/scylla/seastar/core/reactor.cc:2523
seastar::reactor::run_some_tasks() at /home/glauber/scylla/seastar/core/reactor.cc:2936
seastar::reactor::run_some_tasks() at /usr/include/c++/7/chrono:377
 (inlined by) seastar::reactor::run() at /home/glauber/scylla/seastar/core/reactor.cc:3083
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /home/glauber/scylla/seastar/core/app-template.cc:180
main at /home/glauber/scylla/main.cc:760
```

### LINKED ISSUE #24115: seastar_memory - oversized allocation (locator::abstract_replication_strategy::get_pending_address_ranges)
## Packages

Scylla version: `2025.2.0~rc0-20250507.b3dbfaf27a47` with build-id `d114e5c155fb8f22ea5829e79c1f156f1c146b1c`

Kernel Version: `6.8.0-1028-aws`

## Issue description

Not sure about the sequence that led to such error message but before the warning message there are such logs entries:
```
2025-05-09T23:58:16.639+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:comp] compaction - [Compact system.cdc_generations_v3 798397c0-2d31-11f0-9e18-f331abc8d943] Compacted 2 sstables to [/var/lib/scylla/data/system/cdc_generations_v3-c697df3f55393ef5b003843be7ba1422/me-3gq4_1ul4_2a38w2ejveg1i6pykj-big-Data.db:level=0]. 486kB to 481kB (~98% of original) in 32ms = 15MB/s. ~256 total partitions merged to 1.
2025-05-09T23:58:16.639+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:comp] compaction - [Compact system.group0_history 7988eef0-2d31-11f0-9e18-f331abc8d943] Compacting [/var/lib/scylla/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-3gq4_1ul4_298ds2ejveg1i6pykj-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-7-big-Data.db:level=0:origin=memtable]
2025-05-09T23:58:16.639+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:comp] compaction - [Compact system.raft 79848220-2d31-11f0-9e18-f331abc8d943] Compacted 2 sstables to [/var/lib/scylla/data/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gq4_1ul4_2c0ow2ejveg1i6pykj-big-Data.db:level=0]. 1MB to 1MB (~99% of original) in 30ms = 64MB/s. ~256 total partitions merged to 1.
2025-05-09T23:58:16.639+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-3gq4_1ul4_2gy5t2ejveg1i6pykj-big-Filter.db: resizing bitset from 328 bytes to 8 bytes. sstable origin: compaction
2025-05-09T23:58:16.639+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:comp] compaction - [Compact system.group0_history 7988eef0-2d31-11f0-9e18-f331abc8d943] Compacted 2 sstables to [/var/lib/scylla/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-3gq4_1ul4_2gy5t2ejveg1i6pykj-big-Data.db:level=0]. 363kB to 358kB (~98% of original) in 19ms = 19MB/s. ~256 total partitions merged to 1.
2025-05-09T23:58:16.639+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0: gms] cdc - Started using generation (2025/05/09 23:59:21, 796bd202-2d31-11f0-e3f9-82ffe4d8cd70).
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:strm] group0_tombstone_gc_handler - Setting reconcile time to   1746835095 (min id=798a5402-2d31-11f0-9cf7-957e9d89b7ed)
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:strm] storage_service - entering BOOTSTRAP mode
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:strm] raft_topology - start streaming
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:strm] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={decommission ,bootstrap ,rebuild ,removenode ,replace}
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15  !WARNING | scylla[5707]:  [shard 0:strm] seastar_memory - oversized allocation: 147456 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at 0x23648ae 0x186af61 0x14cd488 0x562e6ac 0x180d53f 0x2bb5280 0x4644c08 0x464bf85 0x3b38fda 0x1a8bd5b 0x2f649f8 0x2f650a4 0x2f64b02 0x2f62c05 0x298cfa2 /opt/scylladb/libreloc/libc.so.6+0x3247 /opt/scylladb/libreloc/libc.so.6+0x330a 0x319a704
   --------
   seastar::internal::coroutine_traits_base<std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >::promise_type
   --------
   seastar::(anonymous namespace)::thread_wake_task
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0&&)::{lambda()#2}, seastar::future<void> >(repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0&&)::{lambda()#3}, false> >(seastar::future<void>::finally_body<seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::async<repair_service::bootstrap_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::shared_future<>::shared_state
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15     !INFO | scylla[5707]:  [shard 0:strm] repair - bootstrap_with_repair: started with keyspaces=["system_replicated_keys", "system_traces", "system_distributed", "system_distributed_everywhere", "system_auth"], nr_ranges_total=8656
```
and decoded:
```
2025-05-09T23:58:17.027+00:00 longevity-parallel-topology-schema--db-node-d8409aca-15  !WARNING | scylla[5707]:  [shard 0:strm] seastar_memory - oversized allocation: 147456 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&, bool) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:89
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:99
seastar::current_tasktrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:136
seastar::current_backtrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:169
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/memory.cc:848
seastar::memory::allocate_slowpath(unsigned long) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/memory.cc:911
std::__new_allocator<interval<dht::token> >::allocate(unsigned long, void const*) at ././seastar/src/core/memory.cc:1706
std::allocator<interval<dht::token> >::allocate(unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/allocator.h:196
 (inlined by) std::allocator_traits<std::allocator<interval<dht::token> > >::allocate(std::allocator<interval<dht::token> >&, unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/alloc_traits.h:515
 (inlined by) std::_Vector_base<interval<dht::token>, std::allocator<interval<dht::token> > >::_M_allocate(unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_vector.h:380
 (inlined by) void std::vector<interval<dht::token>, std::allocator<interval<dht::token> > >::_M_range_insert<__gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > > >(__gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >, __gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >, __gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >, std::forward_iterator_tag) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/vector.tcc:1013
__gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > > std::vector<interval<dht::token>, std::allocator<interval<dht::token> > >::insert<__gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >, void>(__gnu_cxx::__normal_iterator<interval<dht::token> const*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >, __gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >, __gnu_cxx::__normal_iterator<interval<dht::token>*, std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_vector.h:1488
 (inlined by) locator::abstract_replication_strategy::get_pending_address_ranges(seastar::lw_shared_ptr<locator::token_metadata const>, std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >, utils::tagged_uuid<locator::host_id_tag>, locator::endpoint_dc_rack) const at ././locator/abstract_replication_strategy.cc:346
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<std::vector<interval<dht::token>, std::allocator<interval<dht::token> > > >::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:80
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2635
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3156
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:273
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:754
main at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
/data/scylla-s3-reloc.cache/by-build-id/d114e5c155fb8f22ea5829e79c1f156f1c146b1c/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f83d43b9b4b0ed5c2bd0a1613bf33e08ee054c93, for GNU/Linux 3.2.0, not stripped

__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

## Impact
Seems like no direct impact

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-d8409aca-9 (34.206.35.244 | 10.12.8.249) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-8 (54.146.125.11 | 10.12.8.4) (shards: -1)
- longevity-parallel-topology-schema--db-node-d8409aca-7 (18.213.101.215 | 10.12.9.195) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-6 (34.192.94.24 | 10.12.9.42) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-5 (35.170.253.197 | 10.12.11.205) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-4 (3.232.101.87 | 10.12.10.158) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-3 (52.5.139.195 | 10.12.11.254) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-2 (34.206.219.135 | 10.12.10.180) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-16 (44.217.51.168 | 10.12.11.159) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-15 (52.7.221.103 | 10.12.8.149) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-14 (54.158.198.103 | 10.12.10.142) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-13 (52.205.67.234 | 10.12.10.131) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-12 (13.219.205.5 | 10.12.10.179) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-11 (54.221.6.183 | 10.12.11.101) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-10 (100.25.126.105 | 10.12.10.236) (shards: 7)
- longevity-parallel-topology-schema--db-node-d8409aca-1 (54.208.204.27 | 10.12.10.21) (shards: 7)

OS / Image: `ami-04a4ab24c03928444` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `d8409aca-8f2d-4e7d-a945-a2b2af06ff60`
Test name: `scylla-2025.2/tier1/longevity-schema-topology-changes-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/23703072de3808aba29ea1f64a9cdb3c3d13ca05/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d8409aca-8f2d-4e7d-a945-a2b2af06ff60`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d8409aca-8f2d-4e7d-a945-a2b2af06ff60)
- Show all stored logs command: `$ hydra investigate show-logs d8409aca-8f2d-4e7d-a945-a2b2af06ff60`

## Logs:
- **longevity-parallel-topology-schema--db-node-d8409aca-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-7-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-7-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-8-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-8-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-5-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-5-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-9** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-9-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-9-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-10-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-10-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-6-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-6-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-4-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-4-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-2-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-2-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-14** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-14-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-14-d8409aca.tar.zst)
- **longevity-parallel-topology-schema--db-node-d8409aca-13** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-13-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250509_204938/longevity-parallel-topology-schema--db-node-d8409aca-13-d8409aca.tar.zst)
- **db-cluster-d8409aca.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/db-cluster-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/db-cluster-d8409aca.tar.zst)
- **sct-runner-events-d8409aca.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/sct-runner-events-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/sct-runner-events-d8409aca.tar.zst)
- **sct-d8409aca.log.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/sct-d8409aca.log.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/sct-d8409aca.log.tar.zst)
- **loader-set-d8409aca.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/loader-set-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/loader-set-d8409aca.tar.zst)
- **monitor-set-d8409aca.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/monitor-set-d8409aca.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/20250510_093943/monitor-set-d8409aca.tar.zst)
- **builder-d8409aca.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/upload_20250510_094133/builder-d8409aca.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d8409aca-8f2d-4e7d-a945-a2b2af06ff60/upload_20250510_094133/builder-d8409aca.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-2025.2/job/tier1/job/longevity-schema-topology-changes-12h-test/2/)
[Argus](https://argus.scylladb.com/test/a1ad2b46-1d66-41c4-a924-1ca3c6b0ef84/runs?additionalRuns[]=d8409aca-8f2d-4e7d-a945-a2b2af06ff60)
</details>

### PR DESCRIPTION
**Pull request by avikivity**
token_range_vector is a sequence of intervals of tokens. It is used
to describe vnodes or token ranges owned by shards.

Since tokens are bloated (16 bytes instead of 8), and intervals are bloated
(40 byte of overhead instead of 8), and since we have plenty of token ranges,
such vectors can exceed our allocation unit of 128 kB and cause allocation stalls.

This series fixes that by first generalizing some helpers and then changing
token_range_vector to use chunked_vector.

Although this touches IDL, there is no compatibility problem since the encoding
for vector and chunked_vector are identical.

There is no performance concern since token_range_vector is never used on
any hot path (hot paths always contain a partition key).

Fixes #3335.
Fixes #24115.

No backport: minor performance fix that isn't a regression.

### CODE REVIEW

**Comment by avikivity** [comment]
Note: I plan to reduce interval's overhead separately. Improving token is much harder.

**Comment by avikivity** [comment]
> * Ensure that the generic Container type passed to this function supports the reserve() method, as this assumption may not hold for all container types and could lead to compilation issues.
> 
> ```
> ret.reserve(v.size() + 1);
> ```

Valid point. Since both vector and chunked_vector have reserve(), and this is only used in esoteric places, we can forgo making this even more generic until and if it is actually needed.

**Comment by raphaelsc** [comment]
I think it should fix #24156 too.

File: partition_range_compat.hh [hunk 1]
```diff
@@ -20,10 +20,10 @@ using wrapping_partition_range = wrapping_interval<dht::ring_position>;
...
 // unwraps a vector of wrapping ranges into a vector of nonwrapping ranges
 // if the vector happens to be sorted by the left bound, it remains sorted
-template <typename T, typename Comparator>
-std::vector<interval<T>>
-unwrap(std::vector<wrapping_interval<T>>&& v, Comparator&& cmp) {
-    std::vector<interval<T>> ret;
+template <template <typename> class Container, typename T, typename Comparator>
+Container<interval<T>>
+unwrap(Container<wrapping_interval<T>>&& v, Comparator&& cmp) {
+    Container<interval<T>> ret;
```
Comment (patjed41) [inline partition_range_compat.hh:26]: Should we constrain `Container` by suitable concepts (has `reserve`, has `emplace_back`, etc.)?

I'm always in doubt while reviewing code like this. The only guideline I found is in `docs/dev/review-checklist.md`:

```
## Templates

...

Template parameters should be constrained by C++ concepts, both as
code documentation, and to enable early error checking by the compiler.
```

According to this doc, we should always use concepts, but we often don't.

**Review by patjed41 — COMMENTED** [review]
Looks good, only one question

File: partition_range_compat.hh (hunk 1 above)
Comment (avikivity) [reply partition_range_compat.hh:26]: > Should we constrain `Container` by suitable concepts (has `reserve`, has `emplace_back`, etc.)?
> 
> I'm always in doubt while reviewing code like this. The only guideline I found is in `docs/dev/review-checklist.md`:
> 
> ```
> ## Templates
> 
> ...
> 
> Template parameters should be constrained by C++ concepts, both as
> code documentation, and to enable early error checking by the compiler.
> ```
> 
> According to this doc, we should always use concepts, but we often don't.

In general we can be more strict on library style code which we expect to be reused a lot, and end-user code which is less likely to be reused. While this is in a library, it's only used in 1-2 places.

However, it's better to actually fix the code than make excuses, so I'll add constraints.
