### PR TITLE
tablets global barrier: acknowledge barrier_and_drain from all nodes

### LINKED ISSUE #26375: Topology barrier will not wait for closed sessions to become unused if the drain part failed
Relevant code:

```c++
    future<group0_guard> global_token_metadata_barrier(group0_guard&& guard, std::unordered_set<raft::server_id> exclude_nodes = {}) {
        auto version = _topo_sm._topology.version;
        bool drain_failed = false;
        try {
            guard = co_await exec_global_command(std::move(guard), raft_topology_cmd::command::barrier_and_drain, exclude_nodes, drop_guard_and_retake::yes);
        } catch (...) {
            rtlogger.warn("drain rpc failed, proceed to fence old writes: {}", std::current_exception());
            drain_failed = true;
        }
        if (drain_failed) {
            guard = co_await start_operation();
        }
        topology_mutation_builder builder(guard.write_timestamp());
        // Other nodes are guaranteed to be drained on success only up to the version which was current
        // prior to barrier_and_drain RPCs were sent.
        builder.set_fence_version(version);
        auto reason = ::format("advance fence version to {}", version);
        co_await update_topology_state(std::move(guard), {builder.build()}, reason);
        guard = co_await start_operation();
        if (drain_failed) {
            // if drain failed need to wait for fence to be active on all nodes
            co_return co_await exec_global_command(std::move(guard), raft_topology_cmd::command::barrier, exclude_nodes, drop_guard_and_retake::yes);
        } else {
            co_return std::move(guard);
        }
    }
```

In the `drain_failed = true` path, the barrier may succeed even though we did not wait for closed session to be unused. This may leave aborted repair or streaming tasks running concurrently after tablet transition was aborted, and thus may run concurrently with the next transition.

No issue was observed in practice yet. Conditions are not very likely as they must involve a specific failure which manifests in command::barrier_and_drain but does not manifest in command::barrier

### LINKED ISSUE #26864: LWT with tablets: replica locks with fenced out coordinators
When an LWT coordinator is fenced out (topology coordinator global barrier proceeded with fencing after an unsuccessful `barrier_and_drain`) [the following scenario is possible](https://github.com/scylladb/scylladb/issues/26801#issuecomment-3469642809):
* an LWT X reached `paxos_state::accept`, the tablet is in "streaming", X acquired the replica lock on the old shard
* an LWT coordinator of X was fenced out and the tablet is pushed to "use_new" state
* a new LWT Y comes to the replica and locks the new shard -- doesn't exclude with X
* both X and Y write to the new shard without mutual exclusion

### PR DESCRIPTION
**Pull request by gusev-p**
Before this series, the `global_barrier` used during tablet migration did not guarantee that `barrier_and_drain` was acknowledged by tablet replicas. As a result, if a request coordinator was fenced out, stale requests from previous topology versions could still execute on replicas in parallel with new requests from incompatible topology versions. For example, stale requests from `tablet_transition_stage::streaming` could run concurrently with new requests from `tablet_transition_stage::use_new`. This caused several issues, including [#26864](https://github.com/scylladb/scylladb/issues/26864) and [#26375](https://github.com/scylladb/scylladb/issues/26375).

This PR fixes the problem in two steps:
* Replicas now hold an erm strong pointer while handling RPCs from coordinators.
* The tablet barrier is updated to require `barrier_and_drain` acknowledgments from all nodes.

A description of alternative solutions and various tradeoffs can be found in [this document](https://docs.google.com/document/d/1tpDtPOsrGaZGBYkdwOKApQv4eMzrBydMM1GaYYmaPgg/edit?pli=1&tab=t.0#heading=h.vidfy0hrz5j7).

[A previous attempt on this changes](https://github.com/scylladb/scylladb/pull/27185).

Fixes: https://github.com/scylladb/scylladb/issues/26864
Fixes: https://github.com/scylladb/scylladb/issues/26375

backport: needs backport to 2025.4 (fixes #26864 for tablets LWT)

### CODE REVIEW

**Comment by gusev-p** [comment]
Have no idea what's the problem with the CI

**Comment by gusev-p** [comment]
@scylladbbot trigger-ci

**Comment by mykaul** [comment]
> Have no idea what's the problem with the CI

```
ImportError: Error importing plugin "test.pylib.runner": cannot import name 'universalasync_typed_wrap' from partially initialized module 'test.pylib.util' (most likely due to a circular import) (/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/util.py)
script returned exit code 1
```

**Comment by gusev-p** [comment]
> > Have no idea what's the problem with the CI
> 
> ```
> ImportError: Error importing plugin "test.pylib.runner": cannot import name 'universalasync_typed_wrap' from partially initialized module 'test.pylib.util' (most likely due to a circular import) (/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/util.py)
> script returned exit code 1
> ```

Where exactly did you find this? I see only an empty log in `Build.txt`

**Comment by gusev-p** [comment]
OK, it's somewhere in the middle of the console output. Would be more convenient to extract the important information somehow..

**Comment by mykaul** [comment]
> > > Have no idea what's the problem with the CI
> > 
> > 
> > ```
> > ImportError: Error importing plugin "test.pylib.runner": cannot import name 'universalasync_typed_wrap' from partially initialized module 'test.pylib.util' (most likely due to a circular import) (/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/util.py)
> > script returned exit code 1
> > ```
> 
> Where exactly did you find this? I see only an empty log in `Build.txt`

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22377/ -> 'Pipeline Overview' (https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22377/pipeline-overview/ ) - that's what I always do when CI fails with no information.

**Comment by gusev-p** [comment]
@tgrabiec ping

File: service/topology_coordinator.cc [hunk 1]
```diff
@@ -1180,7 +1180,11 @@ class topology_coordinator : public endpoint_lifecycle_subscriber {
 
     future<group0_guard> global_tablet_token_metadata_barrier(group0_guard guard) {
         // FIXME: Don't require all nodes to be up, only tablet replicas.
-        return global_token_metadata_barrier(std::move(guard), _topo_sm._topology.ignored_nodes);
```
Comment (tgrabiec) [inline service/topology_coordinator.cc:1243]: I'm not sure we can give up on fencing.

Requests may be in transit in RPC, and without fencing, you can materialize replica-side request at any later topology version.

**Comment by tgrabiec** [comment]
We should drive this forward.

File: service/topology_coordinator.cc (hunk 1 above)
Comment (tgrabiec) [reply service/topology_coordinator.cc:1243]: @gusev-p ^^

Comment (gusev-p) [reply service/topology_coordinator.cc:1243]: > Requests may be in transit in RPC, and without fencing, you can materialize replica-side request at any later topology version.

Right.

On the other hand, fencing has never protected us from stale replica mutations. Before this patch we ran `raft_topology_cmd::command::barrier` on all nodes iff we didn't acked `raft_topology_cmd::command::barrier_and_drain` on some nodes. If we successfully drained all nodes, we waited only for a quorum to ack fence_version increment, all other nodes could still be accepting new stale replica requests from already dead coordinators. Only the `command::barrier_and_drain` round from the next global barrier would put a hard stop on accepting new stale replica requests of the previous version.

More precisely, suppose topology version == x, then before this series the global_barrier(x) provided the following post-conditions:
  * there are no coordinators with versions < x
  * there are no replicas accepting new requests with versions < x - 1, but there could be arbitrary number of already running mutation requests with such versions.
  * a quorum of replicas doesn't allow new requests with versions < x, but there could be arbitrary number of already running mutation requests with such versions on those replicas
  * some replicas could still be accepting new requests with versions == x - 1

We can return the fencing back into the global barrier in its previous form -- write `fence_version` increment to a group0 quorum without additional barrier. This would change the post-conditions to the following:
  * there are no coordinators with versions < x
  * no replicas are currently executing requests with versions < x - 1 and no new such requsts are possible in the future
    * Why? The `barrier_and_drain` handler runs group0.read_barrier() first, which guarantees that new version and the previous `fence_version` are applied on all shards before we drain them. After that we drain all requests with versions < x ==> no current/future requests are possible with versions < x - 1 (the previous fence is set). Future stale requests with version x - 1 are sill possible (until the next global barrier).
  * a quorum of replicas doesn't allow new requests with versions < x, but there could be arbitrary number of already running mutation requests with version x - 1 on those replicas
  * some replicas could still be accepting new requests with versions == x - 1

These conditions are tricky because we want to avoid another round of `fence_and_drain` style RPCs after `fence_version` increment. These conditions should be enough since they guarantee there can't be replica requests with version difference more than 1. In particular, they preclude problems similar to [this LWT race](https://github.com/scylladb/scylladb/issues/26801#issuecomment-3469642809) -- by the time `use_new` request A comes there couldn't `streaming` requests, only `write_both_read_new` requests.

I'll update the code.

Comment (tgrabiec) [reply service/topology_coordinator.cc:1243]: > > Requests may be in transit in RPC, and without fencing, you can materialize replica-side request at any later topology version.
> 
> Right.
> 
> On the other hand, fencing has never protected us from stale replica mutations. Before this patch we ran `raft_topology_cmd::command::barrier` on all nodes iff we didn't acked `raft_topology_cmd::command::barrier_and_drain` on some nodes. If we successfully drained all nodes, we waited only for a quorum to ack fence_version increment, all other nodes could still be accepting new stale replica requests from already dead coordinators. Only the `command::barrier_and_drain` round from the next global barrier would put a hard stop on accepting new stale replica requests of the previous version.

Yes, sounds like a bug. 

And committing to group0 only guarantees that the local node (coordinator) sees the fence, other replicas may only have it in the log, but not applied yet.

> These conditions are tricky because we want to avoid another round of fence_and_drain style RPCs after fence_version increment. 

Why avoid it? It complicates reasoning about correctness, for no clear performance gain. Barriers are rare.

Comment (gusev-p) [reply service/topology_coordinator.cc:1243]: > Why avoid it? It complicates reasoning about correctness, for no clear performance gain. Barriers are rare.

I don't think they are that rare, tablet migration invokes a lot of them. The guarantees outlined above seem to be enough for correctness.

cc. @gleb-cloudius

Comment (gleb-cloudius) [reply service/topology_coordinator.cc:1243]: I am not sure what problems are you talking about and what exactly sounds like a bug. There idea was that barrier_and_drain waits for all requests on coordinator to complete, so there are no "live" requests with older version after that. There still can be mutation or read rpcs not waited by any live requests with older versions. Read rpcs are not a problem since they will be ignored (nobody waits for a reply). Write rpcs may write a stale data, but this should be handled during cleanup. A cleanup makes sure that the topology version on the specific node we are going to cleanup is up-to-date and then it waits for all old writes to complete before starting the cleanup.

Comment (gusev-p) [reply service/topology_coordinator.cc:1243]: @gleb-cloudius For tablets, we want to guarantee that at any given moment there are no replica requests whose topology versions differ by more than 1. Otherwise, issues like [this one](https://github.com/scylladb/scylladb/issues/26801#issuecomment-3469642809) are possible. 

Fencing does in fact guarantee this property, but the reasoning is not entirely obvious. Specifically, global_barrier() for version x ensures that there are no replica requests running with version x − 1. I described the postconditions of global_barrier() above.

**Comment by gusev-p** [comment]
@scylladbbot trigger-ci

File: service/topology_coordinator.cc [hunk 2]
```diff
@@ -1208,13 +1208,16 @@ class topology_coordinator : public endpoint_lifecycle_subscriber
...
-    future<group0_guard> global_token_metadata_barrier(group0_guard&& guard, std::unordered_set<raft::server_id> exclude_nodes = {}, bool* fenced = nullptr) {
+    future<group0_guard> global_token_metadata_barrier(group0_guard&& guard, std::unordered_set<raft::server_id> exclude_nodes = {}, bool* fenced = nullptr, bool drain_all_nodes = false) {
         auto version = _topo_sm._topology.version;
         bool drain_failed = false;
         try {
             guard = co_await exec_global_command(std::move(guard), raft_topology_cmd::command::barrier_and_drain, exclude_nodes, drop_guard_and_retake::yes);
         } catch (...) {
             rtlogger.warn("drain rpc failed, proceed to fence old writes: {}", std::current_exception());
+            if (drain_all_nodes) {
+                throw;
```
Comment (tgrabiec) [inline service/topology_coordinator.cc:1219]: If we throw, the log which says "proceed to fence old writes" will be misleading.

Comment (gusev-p) [reply service/topology_coordinator.cc:1219]: Is this the only problem? I can fix it in a follow-up. Could we merge as-is while the ci is green?

File: service/topology_coordinator.cc (hunk 1 above)
Comment (tgrabiec) [reply service/topology_coordinator.cc:1243]: > > Why avoid it? It complicates reasoning about correctness, for no clear performance gain. Barriers are rare.
> 
> I don't think they are that rare, tablet migration invokes a lot of them. The guarantees outlined above seem to be enough for correctness.

I think this contention point is orthogonal to this PR.

Do you think it's going to be a problem in practice if we wait for the fence? The barrier is shared by all tablets which need to call it. And during migration, streaming time will dominate over all stage transitions. Raft read barrier in the wait for fence is generally faster than draining because it doesn't wait for active request queue to drain.  

We're making it harder for ourselves to reason about correctness by weakening the barrier. Replica-side requests can now use 3 different stages instead of 2.

The section in topology-over-raft.md which starts with `The invariants of stages, which hold as soon as the stage is committed to group0:` needs to be updated to take into account weaker guarantees (e.g. precondition for "cleanup").

**Comment by tgrabiec** [comment]
Qd

File: service/topology_coordinator.cc (hunk 2 above)
Comment (tgrabiec) [reply service/topology_coordinator.cc:1219]: > Is this the only problem? I can fix it in a follow-up. Could we merge as-is while the ci is green?

Yes, follow-up is fine.

**Comment by patjed41** [comment]
@gusev-p I suspect we missed a backport to 2026.1 here. This PR is not in 2026.1, but you attempted backporting it to 2025.4 (closed because 2025.4 became EOL). Also, this PR was opened before 2026.1 was branched and merged after 2026.1 was branched.

I got here because of SCYLLADB-4282 -- stale topology exceptions happening only in 2026.1, precisely because `global_tablet_token_metadata_barrier` doesn't use `drain_all_nodes` in 2026.1.

**Comment by calebxyz** [comment]
@scylladb/releng @dani-tweig why does github-actions bot removes the backport lables here ?

**Comment by yaronkaikov** [comment]
> @gusev-p
> 
> PR body do not contain a Fixes reference to an issue and can not be backported please update PR body with a valid ref to an issue and add the backport label again.

because of this

**Comment by calebxyz** [comment]
> > @gusev-p
> > PR body do not contain a Fixes reference to an issue and can not be backported please update PR body with a valid ref to an issue and add the backport label again.
> 
> because of this

that is fixed

**Comment by calebxyz** [comment]
> oesn't use `drain_all_nodes`

so basically we just need a 2026.1 label here

**Comment by patjed41** [comment]
> so basically we just need a 2026.1 label here

Yes, this PR is in 2026.2+

**Comment by patjed41** [comment]
@yaronkaikov The cover letter contains two "Fixes:". Why is the bot complaining?

@gusev-p Can you submit the 2026.1 backport manually? I don't know if and when this bot will be fixed.

**Comment by gusev-p** [comment]
> @yaronkaikov The cover letter contains two "Fixes:". Why is the bot complaining?
> 
> @gusev-p Can you submit the 2026.1 backport manually? I don't know if and when this bot will be fixed.

Will do later, deep in the tablet migration now
