### PR TITLE
alternator: fix isolation of concurrent modifications to tags

### LINKED ISSUE #6389: Alternator: concurrent TagResource from multiple nodes may race
Tags are stored in a schema table (`system_schema.tables.extensions['tags']`).
This means means that concurrent adding of tags for a single table on more than a single node may result in a race, until Scylla schema agreement is reimplemented to avoid them, or we use some other mechanism to serialize the operation.

### PR DESCRIPTION
**Pull request by nyh**
Alternator's implementation of TagResource, UntagResource and UpdateTimeToLive (the latter uses tags to store the TTL configuration) was unsafe for concurrent modifications - some of these modifications may be lost. This short series fixes the bug, and also adds (in the last patch) a test that reproduces the bug and verifies that it's fixed.

The cause of the incorrect isolation was that we separately read the old tags and wrote the modified tags. In this series we introduce a new function, `modify_tags()` which can do both under one lock, so concurrent tag operations are serialized and therefore isolated as expected.

Fixes #6389.

### CODE REVIEW

**Comment by nyh** [comment]
@avikivity please review at least the first patch, which exposes the storage_proxy held by migration_manager. What I really needed (in the second patch) was for code that has a migration_manager to have access to the data_dictionary, and storage_proxy was a convenient way to get it - but I wonder if you can think of a better way.

File: service/migration_manager.hh [hunk 1]
```diff
@@ -80,6 +80,8 @@ public:
 
     migration_notifier& get_notifier() { return _notifier; }
     const migration_notifier& get_notifier() const { return _notifier; }
+    service::storage_proxy& get_storage_proxy() { return _storage_proxy; }
```
Comment (nuivall) [inline service/migration_manager.hh:83]: I just wonder is adding a getter good candidate for separate commit? There is no regression risk, it won't make sense to backport, can't be seen how it will be used in the future. Perhaps there is some reason I am not aware of.

File: alternator/executor.cc [hunk 2]
```diff
@@ -774,16 +774,16 @@ future<executor::request_return_type> executor::tag_resource(client_state& clien
         co_return api_error::access_denied("Incorrect resource identifier");
     }
     schema_ptr schema = get_table_from_arn(_proxy, rjson::to_string_view(*arn));
```
Comment (nuivall) [inline alternator/executor.cc:776]: just cosmetics, schema_ptr schema could be now called closer to it's usage (e.g. after 2 ifs below)

btw is `schema` needed here at all, I'd think there is some other way to just get ks and cf

File: db/tags/utils.cc [hunk 3]
```diff
@@ -53,4 +55,32 @@ future<> update_tags(service::migration_manager& mm, schema_ptr schema, std::map
...
+            // to modify the tags, we must make a copy.
+            tags = *tags_ptr;
+        }
+        modify(tags);
+        schema_builder builder(s);
+        builder.add_extension(tags_extension::NAME, ::make_shared<tags_extension>(tags));
+
+        auto m = co_await mm.prepare_column_family_update_announcement(builder.build(), false, std::vector<view_ptr>(), group0_guard.write_timestamp());
+
+        co_await mm.announce(std::move(m), std::move(group0_guard));
```
Comment (nuivall) [inline db/tags/utils.cc]: I see a lot of usages of mm.announce together with co_return, I started to wonder, does it make any difference. Just double checking, if  exceptional future is awaited (co_await) it will throw, right?

File: db/tags/utils.cc [hunk 4]
```diff
@@ -53,4 +55,32 @@ future<> update_tags(service::migration_manager& mm, schema_ptr schema, std::map
...
+        if (tags_ptr) {
+            // tags_ptr is a constant pointer to schema data. To allow func()
+            // to modify the tags, we must make a copy.
+            tags = *tags_ptr;
+        }
+        modify(tags);
+        schema_builder builder(s);
+        builder.add_extension(tags_extension::NAME, ::make_shared<tags_extension>(tags));
+
+        auto m = co_await mm.prepare_column_family_update_announcement(builder.build(), false, std::vector<view_ptr>(), group0_guard.write_timestamp());
```
Comment (nuivall) [inline db/tags/utils.cc:65]: just a note as I don't know this code at all but I see almost everywhere timestamp is generated immediately after start_group0_operation()

**Review by nuivall — APPROVED** [review]

File: service/migration_manager.hh (hunk 1 above)
Comment (nyh) [reply service/migration_manager.hh:83]: It's a separate commit because I think it deserves a separate review - the commit message explains where  I plan to use it, but I want somebody who is more active in the "get rid of globals" effort (perhaps @avikivity) to see if this is perhaps a step in the wrong direction, or fine.

I thought that if I put these two lines in the middle of the larger patch that actually use this method, it will be easy to miss I modified migration_manager.hh.

File: db/tags/utils.cc (hunk 4 above)
Comment (nyh) [reply db/tags/utils.cc:65]: I'm not sure I understand your question, so tell me if I don't answer it:
The idea of this "group0_guard" is that the entire schema read-modify-write operation will be done as one atomic operation. The schema modification will have a timestamp - and it was indeed chosen above when group0_guard was created. It doesn't matter if a few milliseconds (or whatever) passed since this time.
So I think this code is correct. Did you see something different "almost everywhere"?

File: db/tags/utils.cc (hunk 3 above)
Comment (nyh) [reply db/tags/utils.cc]: Yes, mm.announce returns an exceptional future, co_await would throw a real exception. We need to handle this exception by the way, but this is an issue I want to handle later (https://github.com/scylladb/scylladb/issues/13152).

Since migration_manager::announce returns a `future<>` I don't understand how `co_return co_await mm.announce` can differ from `co_await mm.announce`, but tell me if you think I'm wrong there.

File: alternator/executor.cc (hunk 2 above)
Comment (nyh) [reply alternator/executor.cc:776]: The order also determines which order we do error checking - if the request has a bad ARN and also bad tags, which error we show first. I didn't want to change this in the patch.

You're right that the schema is not needed, but this is what get_table_from_arn() currently returns after it gets ks and cf. Since get_table_from_arn() is used in additional places, I though it will be simpler to leave this one function that returns schema.

File: db/tags/utils.cc (hunk 3 above)
Comment (nuivall) [reply db/tags/utils.cc]: so it's two of us, as I also couldn't figure the difference

File: db/tags/utils.cc (hunk 4 above)
Comment (nuivall) [reply db/tags/utils.cc:65]: it's ok, just it was usually called sooner, I asked just in case of some "edge" case (I was thinking maybe yielding could break it or something)

File: service/migration_manager.hh (hunk 1 above)
Comment (nuivall) [reply service/migration_manager.hh:83]: ok

**Comment by nyh** [comment]
@scylladb/scylla-maint please consider merging. It was reviewed by @nuivall.

I hoped that @avikivity could look at the first patch in the series and think if he's against exposing the storage_proxy held by migration_manager, or maybe he has a better idea how I can get a data_dictionary from an existing migration_manager. But someone else can look at that too.

File: service/migration_manager.hh [hunk 5]
```diff
@@ -80,6 +80,8 @@ public:
...
+    const service::storage_proxy& get_storage_proxy() const { return _storage_proxy; }
```
Comment (denesb) [inline service/migration_manager.hh:84]: @xemul as the person who is untangling our dependency mess, is this getter fine?

Comment (nyh) [reply service/migration_manager.hh:84]: @xemul, in case I didn't explain the raison d'etre of this new getter well enough in the commit message, I'll try again here: What happens is that I have code that gets a `migration_manager` and needs a `data_dictionary`. The migration_manager doesn't have a data_dictionary in it, but when its implementation needs one it uses the `storage_proxy` it holds and there is a data_dictionary in it. As a **user** of migration_manager, I now want to do exactly the same, and this is why I needed this getter.
If you think there's a better way for a holder of migration_manager to find a data_dictionary, I can use that way as well.

Comment (xemul) [reply service/migration_manager.hh:84]: >  No, that's the entire point of this PR - we need the modify_tags operation to be atomic when facing concurrent schema operations, so it can't take the "schema" object which was fixed when got it (and might be outdated if a parallel schema change happened!), we needs to get the current schema for the given ks/cf after taking the schema-modification lock. So we need a data_dictionary.

I see

> As I noted above, mm also needs, internally a data_dictionary, and it uses exactly the same trick I used (get the data_dictionary from the storage proxy it holds). But here I need it in code using mm, not inside mm...

Well. I've no objections against exporting proxy from mm other than described above. I guess it's an overcompensation since the times I met some long chain to get ... db::config? from. It was like `auto& cfg = storage_sevice.get_query_processor().local().proxy().local().get_db().local().get_config()`. Apparently this chain accumulated over time just because there was a way to get closer to the config by using exporter from different services.

Last chance not to export proxy from mm -- how about passing `noncopyable_function<schema_ptr()> get_schema` as an argument instead of `sstring ks, sstring cf` pair? The caller is executor which can initialize this argument with lambda and `sharded<storage_proxy>&` capture to get data-dictionary from.

Comment (nyh) [reply service/migration_manager.hh:84]: The function trick is not only "ugly" (what a bizarre API this would be...) I'm worried it will be difficult to do correctly because another important complication in this code is that the code needs to run the schema modification on a different core (always core 0), so the code (which you can see in this patch) automatically gets the right storage_proxy for core 0, but it doesn't get other things for core 0, even if executor had them. Maybe I could capture the sharded storage proxy (as you suggested) and use `local()` to use it on core 0, but this would be very ugly...

Another alternative thing I could do is not to have in migration_manager a getter for storage_proxy, but instead, a getter for data_dictionary (which is the only thing I needed anyway). The rationale can be that migration_manager already has various methods which take ks_name and cf_name, so it **must** have access to data_dictionary already, so if it must have such access, it might as well give its users access to it as well.

**Comment by nyh** [comment]
@xemul after the above discussion, is there something you'd like me to fix here, or is this fine and can be merged? Thanks.

File: service/migration_manager.hh (hunk 5 above)
Comment (avikivity) [reply service/migration_manager.hh:84]: I don't mind this change - it's usually easy to unravel it if it turns out it's wrong.

I agree it's better to pass the dependency directly.

**Comment by avikivity** [comment]
This should be reviewed by the raft people.

@kbr-scylla can we have a no-misuse-possible API like run_groupo_operation(noncopyable_function\<something>)?

File: test/alternator/test_tag.py [hunk 6]
```diff
@@ -291,3 +292,53 @@ def test_tag_lsi_gsi(table_lsi_gsi):
...
     with pytest.raises(ClientError, match='ValidationException.*ResourceArn'):
         table_lsi_gsi.meta.client.tag_resource(ResourceArn=lsi_arn, Tags=tags)
+
+# Test that if we concurrently add tags A and B to a table, both survive.
+# If the process of adding tag A involved reading the current tags, adding
+# A and then over-writing the tags back, if we did this for A and B
+# concurrently the risk is that both would read the state before both changes.
+# To solve this, Scylla needs to serialize tag modification. This test
+# is designed to fail if this serialization is missing.  Reproduces #6389
+@pytest.mark.veryslow
```
Comment (kbr-scylla) [inline test/alternator/test_tag.py:302]: @avikivity I recall you were against introducing tests that are not run in CI by default.

If the test takes only a few seconds, I'm for enabling it by default. There are other longer tests in the suite, this one will run concurrently with them so I think it's fine.

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
> @kbr-scylla can we have a no-misuse-possible API like run_groupo_operation(noncopyable_function<something>)?

Misuse would still be possible as Nadav explained.

>  Perhaps the run_group0_operation function should give the function a data_dictionary parameter, as the function would always need to use it to get the old schema if it wants to modify it. And also a migration_manager parameter, I guess.

Note that there are other use cases for group 0 - not just schema changes.
But maybe a specialized (named appropriately) `modify_schema_using_group0(function<future<>(migration_manager&, data_dictionary, ...)>)` or something.

File: test/alternator/test_tag.py (hunk 6 above)
Comment (nyh) [reply test/alternator/test_tag.py:302]: The entire Alternator test suite, 711 tests in 18,000 lines of code, takes today 28 second. So "a few seconds" isn't exactly fine.

I think we can reconsider this later. We talked in the past about having an option that runs longer tests only in some CI runs but every time a developer runs tests on their laptop, maybe we can use that idea.

Philosophically, there are several levels of testing, with increasing rigor:

1. I didn't bother to test, the code compiled!
2. Believe me, I tested myself.
3. Here is the test I ran, once. You can see what I forgot to test, and can also (maybe) run the same test code again a year from now.
4. Here is the test I ran, let's run it every day.

In this case I went with level 3, which is perhaps not as great as level 4, but still better than level 2 or 1 :-)

Comment (kbr-scylla) [reply test/alternator/test_tag.py:302]: I was referring to the entire "test.py suite", developers most often just run the whole test.py instead of specific sub-suites. Anyway, generally I agree with you.

**Comment by nyh** [comment]
Ping. There has been a lot of discussion and ideas floated around here, but we also have two "approve" votes and no one who explicitly "asked for changes" so maybe this version can be committed?

**Comment by denesb** [comment]
> Ping. There has been a lot of discussion and ideas floated around here, but we also have two "approve" votes and no one who explicitly "asked for changes" so maybe this version can be committed?

Queued.
