### PR TITLE
Synchronize incremental repair and tablet split

### LINKED ISSUE #26041: Aborting on shard 0 during scaleout + repair
[Argus](https://argus.scylladb.com/test/0e026075-906c-48c9-9a72-8b49ec1544ef/runs?additionalRuns[]=3374fbef-7f63-44be-a5f3-b15978eca34f)

Scylla version: `2025.4.0~dev-20250911.eae12c171709` with build-id `28e16e1ad69f4fe9545bac1d9258673ba2bcb04d`

Kernel Version: `6.14.0-1012-aws`

<details>
<summary>
Extra information
</summary>

## Installation details

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:

    - oos-test-feature--db-node-3374fbef-6 (176.34.157.231 | 10.4.0.174) (shards: 2)

    - oos-test-feature--db-node-3374fbef-5 (34.241.68.163 | 10.4.1.223) (shards: 2)

    - oos-test-feature--db-node-3374fbef-4 (34.244.161.78 | 10.4.1.63) (shards: 2)

    - oos-test-feature--db-node-3374fbef-3 (52.30.183.128 | 10.4.1.218) (shards: 2)

    - oos-test-feature--db-node-3374fbef-2 (3.250.193.66 | 10.4.2.43) (shards: 2)

    - oos-test-feature--db-node-3374fbef-1 (34.244.28.65 | 10.4.0.65) (shards: 2)

OS / Image: `ami-0e7f628479c108eed` (aws: undefined_region)

Test: `repair`
Test id: `3374fbef-7f63-44be-a5f3-b15978eca34f`
Test name: `scylla-staging/cezar/features/out-of-space-prevention/repair`

    Test method: `longevity_oos_test.LongevityOutOfSpaceTest.test_oos_repair`

Test config file(s):

- [longevity-out-of-space-prevention-repair.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/399cb20e32bd167e07960ce7423a1ada0b5c823e/test-cases/features/out-of-space-prevention/longevity-out-of-space-prevention-repair.yaml)

## Logs:

    - **[db-cluster-3374fbef.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/db-cluster-3374fbef.tar.zst/download)**

    - **[schema-logs-3374fbef.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/schema-logs-3374fbef.tar.zst/download)**

    - **[sct-runner-events-3374fbef.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/sct-runner-events-3374fbef.tar.zst/download)**

    - **[2025_09_12__10_09_11_179.sct-3374fbef.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/2025_09_12__10_09_11_179.sct-3374fbef.log.zst/download)**

    - **[2025_09_12__16_24_49_785.sct-3374fbef.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/2025_09_12__16_24_49_785.sct-3374fbef.log.zst/download)**

    - **[loader-set-3374fbef.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/loader-set-3374fbef.tar.zst/download)**

    - **[monitor-set-3374fbef.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/monitor-set-3374fbef.tar.zst/download)**

    - **[builder-3374fbef.log.tar.gz](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/3374fbef-7f63-44be-a5f3-b15978eca34f/log/builder-3374fbef.log.tar.gz/download)**

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/cezar/job/features/job/out-of-space-prevention/job/repair/66/)
</details>

Reproduced: [2025.4.0~dev-20250908.c4ed7dd814ae](https://argus.scylladb.com/tests/scylla-cluster-tests/763f2d4c-eab6-4975-97b8-d24c8d76fd84) and [2025.4.0~dev-20250907.040d6e224559](https://argus.scylladb.com/tests/scylla-cluster-tests/8eadfff2-aef7-47be-8d3e-5a2be6511555)
                            

### Scenario
Fill a cluster until critical disk utilization (98% utilization).
At 97%, start a repair task., which will not finish, due to critical disk utilization.
Scale out and wait for repair to finish.
At the point the error happens on node 4
After the node restart, scale out does not continue

Image

### Error

```
Sep 12 18:48:56.910421 oos-test-feature--db-node-3374fbef-4 scylla[12098]:  [shard 1:main] sstable - Host id a1feba55-7d3d-4a2a-a7d7-c0c58514e1c7 does not match local host id f914100f-8807-4236-8d4c-6345fe04144f while validating SSTable: /var/lib/scylla/data/keyspace2/standard1-3ed028308fe411f0965edaac2b317d79/me-3gtm_1drd_4jys62i6rsqbn8n2ek-big-Data.db. Load foreign SSTables via the upload dir instead.
Sep 12 18:54:47.125561 oos-test-feature--db-node-3374fbef-4 scylla[13168]:  [shard 0:main] table - Unable to load SSTable /var/lib/scylla/data/keyspace2/standard1-3ed028308fe411f0965edaac2b317d79/me-3gtm_1e91_5a44w2i8i2q23qa0nk-big-Data.db that belongs to tablets 22 and 23, at: 0x20d0899 0x20d0450 0x5966ff7 0x1b2334a 0x2658906 0x26a7a4c 0x26a7ebb 0x22086ee 0x221010d 0x2200f95 0x21fee48 0x22086ee 0x2204128 0x2202bc7 0x3f68468 0x1592c79 0x2b66ff8 0x2b66809 0x2b66262 0x247f1de 0x2b69112 /opt/scylladb/libreloc/libc.so.6+0x3574 /opt/scylladb/libreloc/libc.so.6+0x3627 0x32d96b4
                                                                              --------
                                                                              seastar::internal::coroutine_traits_base<void>::promise_type
                                                                              --------
                                                                              seastar::internal::coroutine_traits_base<void>::promise_type
                                                                              --------
                                                                              seastar::internal::coroutine_traits_base<void>::promise_type
                                                                              --------
                                                                              seastar::coroutine::parallel_for_each<replica::distributed_loader::populate_keyspace(seastar::sharded<replica::database>&, seastar::sharded<db::system_keyspace>&, replica::keyspace&, seastar::basic_sstring<char, unsigned int, 15u, true>)::$_0>
                                                                              --------
                                                                              seastar::internal::coroutine_traits_base<void>::promise_type
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::internal::complete_when_all<seastar::internal::extract_values_from_futures_vector<seastar::future<void> >, seastar::future<void> >(std::vector<seastar::future<void>, std::allocator<seastar::future<void> > >&&, std::vector<seastar::future<void>, std::allocator<seastar::future<void> > >::iterator)::{lambda(auto:1)#1}, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::internal::complete_when_all<seastar::internal::extract_values_from_futures_vector<seastar::future<void> >, seastar::future<void> >(std::vector<seastar::future<void>, std::allocator<seastar::future<void> > >&&, std::vector<seastar::future<void>, std::allocator<seastar::future<void> > >::iterator)::{lambda(auto:1)#1}>(seastar::internal::complete_when_all<seastar::internal::extract_values_from_futures_vector<seastar::future<void> >, seastar::future<void> >(std::vector<seastar::future<void>, std::allocator<seastar::future<void> > >&&, std::vector<seastar::future<void>, std::allocator<seastar::future<void> > >::iterator)::{lambda(auto:1)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::internal::complete_when_all<seastar::internal::extract_values_from_futures_vector<seastar::future<void> >, seastar::future<void> >(std::vector<auto:2, std::allocator<auto:2> >&&, std::vector<auto:2, std::allocator<auto:2> >::iterator)::{lambda(auto:1)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::discard_result()::{lambda((auto:1&&)...)#1}, seastar::future<void>::then_impl_nrvo<seastar::future<void>::discard_result()::{lambda((auto:1&&)...)#1}, seastar::future<void> >(seastar::future<void>::discard_result()::{lambda((auto:1&&)...)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::discard_result()::{lambda((auto:1&&)...)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                              --------
                                                                              seastar::(anonymous namespace)::thread_wake_task
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0&&)::{lambda()#2}, seastar::future<void> >(replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0&&)::{lambda()#3}, false> >(seastar::future<void>::finally_body<seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::async<replica::distributed_loader::init_non_system_keyspaces(seastar::sharded<replica::database>&, seastar::sharded<service::storage_proxy>&, seastar::sharded<db::system_keyspace>&)::$_0>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                              --------
                                                                              seastar::(anonymous namespace)::thread_wake_task
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<int> >(scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false> >(seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::future<int>::finally_body<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#3}, false>&, seastar::future_state<int>&&)#1}, int>
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>, seastar::future<int>::then_wrapped_nrvo<seastar::future<int>, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false> >(seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::future<int>::finally_body<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda()#2}, false>&, seastar::future_state<int>&&)#1}, int>
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<int>::then_impl_nrvo<seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}, seastar::future<void> >(seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&)::$_0::operator()()::{lambda(int)#1}&, seastar::future_state<int>&&)#1}, int>
                                                                              --------
                                                                              seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}, seastar::future<void>::then_wrapped_nrvo<void, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}>(seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::or_terminate()::{lambda(auto:1&&)#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]: Aborting on shard 0, in scheduling group main.
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]: Backtrace:
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x5984bfa
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x597d7b3
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x598317b
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x59a11aa
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   /opt/scylladb/libreloc/libc.so.6+0x1a06f
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   /opt/scylladb/libreloc/libc.so.6+0x73e9b
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   /opt/scylladb/libreloc/libc.so.6+0x19f3d
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   /opt/scylladb/libreloc/libc.so.6+0x16cf
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x1b23359
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2658906
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x26a7a4c
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x26a7ebb
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x22086ee
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x221010d
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2200f95
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x21fee48
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x22086ee
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2204128
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2202bc7
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x3f68468
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x1592c79
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2b66ff8
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2b66809
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2b66262
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x247f1de
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x2b69112
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   /opt/scylladb/libreloc/libc.so.6+0x3574
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   /opt/scylladb/libreloc/libc.so.6+0x3627
Sep 12 18:54:47.125954 oos-test-feature--db-node-3374fbef-4 scylla[13168]:   0x32d96b4
```

### Decoded backtrace
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&, bool) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:89
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:775
seastar::print_with_backtrace(char const*, bool, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:828
seastar::sigabrt_action(siginfo_t*, ucontext_t*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4120
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)(siginfo_t*, ucontext_t*))(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4049
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)(siginfo_t*, ucontext_t*))(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4044
/cache/28e16e1ad69f4fe9545bac1d9258673ba2bcb04d/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=48c4b9b1efb1df15da8e787f489128bf31893317, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:64
replica::tablet_storage_group_manager::compaction_group_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:1255
replica::table::compaction_group_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:1273
 (inlined by) replica::table::compaction_group_view_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:4358
compaction::shard_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:797
tasks::task_manager::task::start() at ././tasks/task_manager.cc:216
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36shard_reshaping_compaction_task_implEJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RN5utils11tagged_uuidINS_11task_id_tagEEERN8sstables17sstable_directoryERN7seastar7shardedIN7replica8databaseEEERNSH_12reshape_modeERSt8functionIFNSK_13lw_shared_ptrINSH_7sstableEEEjEERSS_IFbRKSV_EERmEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNSK_10shared_ptrIS1_EEDpOT0__XcvS17__fL0p_spclsr3stdE7forwardIS1A_EfL0p0_EERSt7same_asIS17_EEEENSK_6futureINS18_IS17_EEEENS_9task_infoES1C_ at ././tasks/task_manager.hh:366
compaction::table_reshaping_compaction_task_impl::run()::$_0::operator()(sstables::sstable_directory&) const at ././compaction/task_manager_module.cc:779
seastar::future<unsigned long> std::__invoke_impl<seastar::future<unsigned long>, compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>(std::__invoke_other, compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::__invoke_result<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>::type std::__invoke<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>(compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:98
 (inlined by) std::invoke_result<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>::type std::invoke<compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&>(compaction::table_reshaping_compaction_task_impl::run()::$_0 const&, sstables::sstable_directory&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/functional:122
 (inlined by) seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}::operator()() const at ././seastar/include/seastar/core/sharded.hh:457
 (inlined by) seastar::future<unsigned long> seastar::futurize<seastar::future<unsigned long> >::invoke<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&>(seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&) at ././seastar/include/seastar/core/future.hh:1959
 (inlined by) seastar::futurize<std::invoke_result<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::type>::type seastar::smp::submit_to<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::smp_submit_to_options, seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:372
 (inlined by) seastar::futurize<std::invoke_result<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::type>::type seastar::smp::submit_to<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>(unsigned int, seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}&&) at ././seastar/include/seastar/core/smp.hh:399
 (inlined by) seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const at ././seastar/include/seastar/core/sharded.hh:455
 (inlined by) seastar::future<unsigned long> seastar::futurize<seastar::future<unsigned long> >::invoke<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:1959
 (inlined by) auto seastar::futurize_invoke<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int>(seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:1990
 (inlined by) _ZN7seastar10map_reduceINSt6ranges9iota_viewIjjE9_IteratorEZNS_7shardedIN8sstables17sstable_directoryEE11map_reduce0IZN10compaction36table_reshaping_compaction_task_impl3runEvE3$_0mSt4plusImEEENS_6futureIT0_EET_SG_T1_EUljE_mSE_QrQSI_SG_SJ_T2__XdeppfL0p_XnefL0p_fL0p_RSt14convertible_toIbEXclfL0p0_defL0p_EQsr9is_futureIDTclfL0p0_defL0p_EEEE5valueXclfL0p2_clsr3stdE4movefL0p1_EcldtclfL0p0_defL0p_E3getEERSM_ISJ_EEEENSF_ISJ_EESI_SI_OSG_SJ_SL_ at ././seastar/include/seastar/core/map_reduce.hh:193
 (inlined by) seastar::future<unsigned long> seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>) at ././seastar/include/seastar/core/sharded.hh:460
 (inlined by) compaction::table_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:775
tasks::task_manager::task::start() at ././tasks/task_manager.cc:216
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36table_reshaping_compaction_task_implEJN7seastar13basic_sstringIcjLj15ELb1EEES7_RNS5_7shardedIN8sstables17sstable_directoryEEERNS8_IN7replica8databaseEEERNS9_12reshape_modeESt8functionIFNS5_13lw_shared_ptrINS9_7sstableEEEjEESJ_IFbRKSM_EEEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNS5_10shared_ptrIS1_EEDpOT0__XcvSV__fL0p_spclsr3stdE7forwardISY_EfL0p0_EERSt7same_asISV_EEEENS5_6futureINSW_ISV_EEEENS_9task_infoES10_ at ././tasks/task_manager.hh:366
replica::distributed_loader::reshape(seastar::sharded<sstables::sstable_directory>&, seastar::sharded<replica::database>&, sstables::reshape_mode, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, std::function<seastar::lw_shared_ptr<sstables::sstable> (unsigned int)>, std::function<bool (seastar::lw_shared_ptr<sstables::sstable> const&)>) at ././replica/distributed_loader.cc:121
replica::table_populator::populate_subdir(seastar::sharded<sstables::sstable_directory>&) at ././replica/distributed_loader.cc:420
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/coroutine:247
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ./build/release/seastar/./seastar/include/seastar/core/coroutine.hh:122
 (inlined by) seastar::reactor::task_queue::run_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2617
 (inlined by) seastar::reactor::task_queue_group::run_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3120
 (inlined by) seastar::reactor::task_queue_group::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3104
 (inlined by) seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3277
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3165
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:273
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:765
main at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:593
__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

### LINKED ISSUE #27414: Failure to attach sstables in streaming consumer leaves sealed sstables on disk
Streaming consumer looks roughly like this:

```c++
1:            auto guard = service::topology_guard(frozen_guard);
2:            co_await sst->write_components(...);
3:            co_await cf->add_sstable_and_update_cache(sst);
```

The sstable is sealed in `2`. If add_sstable_and_update_cache() fails in `3`, the streaming will be failed but we will leave the sstable on disk. It will not be visible in the database until the next node restart.

There are several problems with that:

1. Data resurrection. Later repair may succeed and compaction may garbage-collect tombstones. But compaction doesn't see the sstables left by failed streaming. After the abandoned sstable is picked up on restart, we'll have data resurrection. 

2. On tablet split, the node is supposed to ensure that all sstables are split before ACKing the split. If it doesn't see the sstables left on disk by failed streaming, it will not split them. This will cause failure to restart, because sstables will span tablet boundaries. 

To prevent that, we need to delete the sstable before busting the topology guard if attaching failed.

### PR DESCRIPTION
**Pull request by raphaelsc**
Split prepare can run concurrently with repair.

Consider this:

1) split prepare starts
2) incremental repair starts
3) split prepare finishes
4) incremental repair produces unsplit sstable
5) split is not happening on sstable produced by repair
        5.1) that sstable is not marked as repaired yet
        5.2) might belong to repairing set (has compaction disabled)
6) split executes
7) repairing or repaired set has unsplit sstable

If split was acked to coordinator (meaning prepare phase finished),
repair must make sure that all sstables produced by it are split.
It's not happening today with incremental repair because it disables
split on sstables belonging to repairing group. And there's a window
where sstables produced by repair belong to that group.

To solve the problem, we want the invariant where all sealed sstables
will be split.
To achieve this, streaming consumers are patched to produce unsealed
sstable, and the new variant add_new_sstable_and_update_cache() will
take care of splitting the sstable while it's unsealed.
If no split is needed, the new sstable will be sealed and attached.

This solution was also needed to interact nicely with out of space
prevention too. If disk usage is critical, split must not happen on
restart, and the invariant aforementioned allows for it, since any
unsplit sstable left unsealed will be discarded on restart.
The streaming consumer will fail if disk usage is critical too.

The reason interposer consumer doesn't fully solve the problem is
because incremental repair can start before split, and the sstable
being produced when split decision was emitted must be split before
attached. So we need a solution which covers both scenarios.

Fixes #26041.
Fixes #27414.

Should be backported to 2025.4 that contains incremental repair

### CODE REVIEW

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	✅	spider6.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	❌	spider6.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	✅	spider2.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	✅	spider2.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)
> 🔹 cluster/test_tablets2	✅	spider2.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	✅	spider3.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)	✅	spider3.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20890/)
> 🔹 cluster/test_tablets2	✅	spider3.cloudius-systems.com
> dtest	[dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/19629/)	✅	
> [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/11471/)	✅	
> [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/8162/)	✅	
> #### Failed Tests (2/80287):
> * [test_reject_split_compaction.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/20890/testReport/junit/storage/test_out_of_space_prevention/dev___test_py___dev___test_reject_split_compaction_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_reject_split_compaction.dev.2)
> * [test_reject_split_compaction.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/20890/testReport/junit/storage/test_out_of_space_prevention/dev___test_py___dev___test_reject_split_compaction_dev_2_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_reject_split_compaction.dev.2)
> 
> #### Build Details:
> * Duration: 5 hr 44 min
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

looks like infra issue: ERROR 2025-10-13 04:50:07,863 [shard 0:main] init - Failed owner and mode verification: std::runtime_error (Failed to get /scylladir/testlog/x86_64/dev/volumes/b4e82e21-f8c0-4ecc-9055-13f9e606d0bc/scylla-0/hints/1/.fuse_hidden0000001800000005 type.)

@scylladbbot trigger-ci

**Comment by raphaelsc** [comment]
@tgrabiec please take a look.

File: replica/compaction_group.hh [hunk 1]
```diff
@@ -434,6 +434,9 @@ public:
     virtual dht::token_range get_token_range_after_split(const dht::token&) const noexcept = 0;
 
     virtual lw_shared_ptr<sstables::sstable_set> make_sstable_set() const = 0;
+
+    virtual mutation_reader_consumer make_interposer_consumer(mutation_reader_consumer end_consumer) const = 0;
+    virtual uint64_t adjust_partition_estimate(uint64_t partition_estimation) const = 0;
 };
```
Comment (tgrabiec) [inline replica/compaction_group.hh:449]: What about this scenario (steps 1 and 2 swapped), where split prepare starts after the sstable writer. Is it handled?

```
1) incremental repair starts
2) split prepare starts
3) split prepare finishes
4) incremental repair produces unsplit sstable
5) split is not happening on sstable produced by repair
	5.1) that sstable is not marked as repaired yet
	5.2) might belong to repairing set (has compaction disabled)
6) split executes
7) repairing or repaired set has unsplit sstable

```

File: replica/table.cc [hunk 2]
```diff
@@ -915,6 +922,23 @@ class tablet_storage_group_manager final : public storage_group_manager {
...
+                co_return co_await mutation_writer::segregate_by_token_group(std::move(reader),
+                                                                             std::move(options.classifier),
+                                                                             std::move(end_consumer_));
+            };
+        }
+        return end_consumer;
+    }
+
+    uint64_t adjust_partition_estimate(uint64_t partition_estimation) const override {
+        return tablet_map().needs_split() ? std::max(partition_estimation / 2, uint64_t(1)) : partition_estimation;
```
Comment (tgrabiec) [inline replica/table.cc]: needs_split() can change from true to false during writing. We should check whether we created the interposer or not.

Comment (raphaelsc) [reply replica/table.cc]: As before, it relies on user adjusting estimation and creating consumer with no yielding in between. The estimation happens beforehand, not during the writing. Today, it is needs_split() but before the strategy changing in between (there's also a strategy specific interposer) could cause a similar effect. Invokes the need for documentation I think.

File: replica/compaction_group.hh (hunk 1 above)
Comment (raphaelsc) [reply replica/compaction_group.hh:449]: This is a very good point. It should be all handled if all the splitting remains within add_sstable_and_update_cache(). Today there's a contract between streaming consumer and add_sstable_and_update_cache() that the sstable feeded into latter is the same as the one loaded into the sstable set. That's because of view building (from staging) and incremental repair logic, which works on that sstable expecting it's not compacted until they're done with it. I will see what I can do, without having to change the interface of add_sstable_and_update_cache(). I wouldn't like to extract maybe_split_sstable() from it, since it will seem redundant with the interposer consumer. But to fix both problems, we need to make sure sstable is properly split before attaching it to the table.

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/20909/artifact/testlog/x86_64/debug/failed_test/test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode.debug.6/scylla-10.log
```
Scylla version 2026.1.0~dev-0.20251013.5d918a713892 with build-id 042865d3de56e1873ba89007381c43cda003f965 starting ...

ERROR 2025-10-14 00:16:57,958 [shard 0:main] init - Startup failed: seastar::internal::backtraced<locator::no_such_tablet_map> (Tablet map not found for table ee42a6a0-a879-11f0-b644-cd3389517952 Backtrace: 0x3be4f75 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x462d665 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x462d088 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x462ed31 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x463154f 0x94146aa 0x9413e86 0x9413ca5 0x93f38a2 0x93c6319 0x8bc020f 0x4f5b67e 0x4de149c 0x8ba59dc 0x8bbbd2b 0x8bbb859 0x8bdc2ee 0x3e38856 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3773066 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x377f80c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x377efd3 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x378453f /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3782786 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3297a85 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3294f30 0x3c8a042 0x3c8743f /lib64/libc.so.6+0x3574 /lib64/libc.so.6+0x3627 0x3b9c3e4
```

Decoded:
```
[Backtrace #0]
___interceptor_backtrace at /mnt/clang_build/llvm-project-x86_64/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4497
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&, bool) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:89
seastar::current_backtrace_tasklocal() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:99
seastar::current_tasktrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:136
seastar::current_backtrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:169
seastar::internal::backtraced<locator::no_such_tablet_map>::backtraced<seastar::internal::backtraced<locator::no_such_tablet_map>&>(seastar::internal::backtraced<locator::no_such_tablet_map>&) at ././seastar/include/seastar/util/backtrace.hh:247
std::__exception_ptr::exception_ptr std::make_exception_ptr<seastar::internal::backtraced<locator::no_such_tablet_map>>(seastar::internal::backtraced<locator::no_such_tablet_map>) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/exception_ptr.h:258
std::__exception_ptr::exception_ptr seastar::make_backtraced_exception_ptr<locator::no_such_tablet_map, utils::tagged_uuid<table_id_tag>&>(utils::tagged_uuid<table_id_tag>&) at ././seastar/include/seastar/util/backtrace.hh:276
void seastar::throw_with_backtrace<locator::no_such_tablet_map, utils::tagged_uuid<table_id_tag>&>(utils::tagged_uuid<table_id_tag>&) at ././seastar/include/seastar/util/backtrace.hh:293
locator::tablet_metadata::get_tablet_map(utils::tagged_uuid<table_id_tag>) const at ./locator/tablets.cc:283
db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0::operator()(utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>) const at ./db/view/view_building_worker.cc:312
 (inlined by) void std::__invoke_impl<void, db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0&, utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>>(std::__invoke_other, db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0&, utils::tagged_uuid<table_id_tag>&&, seastar::lw_shared_ptr<replica::table>&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::enable_if<is_invocable_r_v<void, db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0&, utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>>, void>::type std::__invoke_r<void, db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0&, utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>>(db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0&, utils::tagged_uuid<table_id_tag>&&, seastar::lw_shared_ptr<replica::table>&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:113
 (inlined by) std::_Function_handler<void (utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>), db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>)::$_0>::_M_invoke(std::_Any_data const&, utils::tagged_uuid<table_id_tag>&&, seastar::lw_shared_ptr<replica::table>&&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:292
std::function<void (utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>)>::operator()(utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>) const at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/std_function.h:593
replica::database::tables_metadata::for_each_table(std::function<void (utils::tagged_uuid<table_id_tag>, seastar::lw_shared_ptr<replica::table>)>) const at ./replica/database.cc:3243
db::view::view_building_worker::discover_local_staging_sstables(std::map<utils::tagged_uuid<table_id_tag>, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>, std::less<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::map<locator::tablet_replica, db::view::replica_tasks, std::less<locator::tablet_replica>, std::allocator<std::pair<locator::tablet_replica const, db::view::replica_tasks>>>>>>) at ./db/view/view_building_worker.cc:307
_ZZN2db4view20view_building_worker34discover_existing_staging_sstablesEvENK3$_1clIS1_EEN7seastar6futureISt13unordered_mapIN5utils11tagged_uuidI12table_id_tagEESt6vectorINS1_25staging_sstable_task_infoESaISC_EESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SE_EEEEERT_ at ./db/view/view_building_worker.cc:281
seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> std::__invoke_impl<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&>(std::__invoke_other, db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:63
 (inlined by) std::__invoke_result<db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&>::type std::__invoke<db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/invoke.h:98
 (inlined by) std::invoke_result<db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&>::type std::invoke<db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1 const&, db::view::view_building_worker&) at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/functional:122
 (inlined by) seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()::operator()() const at ././seastar/include/seastar/core/sharded.hh:457
 (inlined by) seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::futurize<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>>>::invoke<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()&>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1&&) at ././seastar/include/seastar/core/future.hh:2002
seastar::futurize<std::invoke_result<db::view::view_building_worker::discover_existing_staging_sstables()::$_1>::type>::type seastar::smp::submit_to<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()>(unsigned int, seastar::smp_submit_to_options, db::view::view_building_worker::discover_existing_staging_sstables()::$_1&&) at ././seastar/include/seastar/core/smp.hh:372
 (inlined by) seastar::futurize<std::invoke_result<db::view::view_building_worker::discover_existing_staging_sstables()::$_1>::type>::type seastar::smp::submit_to<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)::operator()(unsigned int) const::'lambda'()>(unsigned int, db::view::view_building_worker::discover_existing_staging_sstables()::$_1&&) at ././seastar/include/seastar/core/smp.hh:399
 (inlined by) seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)::operator()(unsigned int) const at ././seastar/include/seastar/core/sharded.hh:455
 (inlined by) seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::futurize<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>>>::invoke<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)&, unsigned int>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1&&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:2002
 (inlined by) auto seastar::futurize_invoke<seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int)&, unsigned int>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1&&, unsigned int&&) at ././seastar/include/seastar/core/future.hh:2033
 (inlined by) seastar::future<db::view::view_building_worker::discover_existing_staging_sstables()::$_2> seastar::map_reduce<std::ranges::iota_view<unsigned int, unsigned int>::_Iterator, seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2)::'lambda'(unsigned int), std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>&&, db::view::view_building_worker::discover_existing_staging_sstables()::$_2, T2) at ././seastar/include/seastar/core/map_reduce.hh:193
 (inlined by) seastar::future<std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>> seastar::sharded<db::view::view_building_worker>::map_reduce0<db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2>(db::view::view_building_worker::discover_existing_staging_sstables()::$_1, std::unordered_map<utils::tagged_uuid<table_id_tag>, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>, std::hash<utils::tagged_uuid<table_id_tag>>, std::equal_to<utils::tagged_uuid<table_id_tag>>, std::allocator<std::pair<utils::tagged_uuid<table_id_tag> const, std::vector<db::view::view_building_worker::staging_sstable_task_info, std::allocator<db::view::view_building_worker::staging_sstable_task_info>>>>>, db::view::view_building_worker::discover_existing_staging_sstables()::$_2) at ././seastar/include/seastar/core/sharded.hh:460
 (inlined by) db::view::view_building_worker::discover_existing_staging_sstables() (.resume) at ./db/view/view_building_worker.cc:280
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/coroutine:247
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:122
```

Looks like https://github.com/scylladb/scylladb/issues/26403

**Comment by bhalevy** [comment]
@scylladbbot trigger-ci

File: replica/table.cc (hunk 2 above)
Comment (tgrabiec) [reply replica/table.cc]: Ok. Yeah, documenting this assumption would be good in case the caller changes his mind.

**Comment by bhalevy** [comment]
@raphaelsc please resolve conflicts.
What's the next step here?

**Comment by tgrabiec** [comment]
> @raphaelsc please resolve conflicts. What's the next step here?

I think the approach needs a rework to cover all scenarios: https://github.com/scylladb/scylladb/pull/26528#discussion_r2426823358

**Comment by raphaelsc** [comment]
> > @raphaelsc please resolve conflicts. What's the next step here?
> 
> I think the approach needs a rework to cover all scenarios: [#26528 (comment)](https://github.com/scylladb/scylladb/pull/26528#discussion_r2426823358)

> What about this scenario (steps 1 and 2 swapped), where split prepare starts after the sstable writer. Is it handled?
> 
> ```
> 1) incremental repair starts
> 2) split prepare starts
> 3) split prepare finishes
> 4) incremental repair produces unsplit sstable
> 5) split is not happening on sstable produced by repair
> 	5.1) that sstable is not marked as repaired yet
> 	5.2) might belong to repairing set (has compaction disabled)
> 6) split executes
> 7) repairing or repaired set has unsplit sstable
> ```

Turns out this is not reproducible today since the sstables being repaired cannot be picked by split compaction (repairing sstables will be excluded by compaction but this is only an implementation detail, another implementation could still allow compaction on repairing). So split preparation phase only finishes when incremental repair finishes. So we indeed should go with the approach in add_sstable_and_update_cache() that will satisfy every possible condition.

**Comment by raphaelsc** [comment]
v2: made synchronization more robust by considering all variations of the scenario. that's done by always performing the splitting if needed right before adding the sstable into the table.

**Comment by bhalevy** [comment]
@raphaelsc 
```
	
compiling failure

./test/boost/sstable_test.hh:39:20: error: no viable conversion from returned value of type 'future>' to function return type 'future<(default) void>'
```

**Comment by raphaelsc** [comment]
@tgrabiec please review this new version

**Comment by raphaelsc** [comment]
@tgrabiec ping on this.

**Comment by raphaelsc** [comment]
@asias please review this too.

**Comment by asias** [comment]
> @asias please review this too.

I liked the approach in the new version. I will take another look. Thanks.

File: compaction/compaction.cc [hunk 3]
```diff
@@ -2222,6 +2222,31 @@ uint64_t compaction_descriptor::sstables_size() const {
...
+                                      sst->run_identifier(), compaction_type_options::make_split(opt.classifier));
+    desc.creator = [&t] (shard_id _) {
+        return t.make_sstable();
+    };
+    desc.replacer = [&] (compaction_completion_desc d) {
+        std::move(d.new_sstables.begin(), d.new_sstables.end(), std::back_inserter(ret));
+    };
+
+    co_await compact_sstables(std::move(desc), info, t, monitor);
+    co_await sst->unlink();
```
Comment (tgrabiec) [inline compaction/compaction.cc]: If we fail here, will the sstables be left on disk unattached?

File: replica/table.cc [hunk 4]
```diff
@@ -1135,7 +1135,7 @@ tablet_storage_group_manager::maybe_split_sstable(const sstables::shared_sstable
     auto holder = cg.async_gate().hold();
     auto& view = cg.view_for_sstable(sst);
     auto lock_holder = co_await _t.get_compaction_manager().get_incremental_repair_read_lock(view, "maybe_split_sstable");
-    co_return co_await _t.get_compaction_manager().maybe_split_sstable(sst, view, co_await split_compaction_options());
+    co_return co_await compaction::maybe_split_offline_sstable(sst, view, co_await split_compaction_options());
```
Comment (asias) [inline replica/table.cc]: The tablet_storage_group_manager::maybe_split_sstable is supposed to split only offline sst, right? If that's the case, it is better to rename tablet_storage_group_manager::maybe_split_sstable to maybe_split_new_sstable to make it clear that this splits the sstable that is not added to the system yet.

```
future<std::vector<sstables::shared_sstable>>
tablet_storage_group_manager::maybe_split_sstable(const sstables::shared_sstable& sst) {
    if (!tablet_map().needs_split()) {
        co_return std::vector<sstables::shared_sstable>{sst};
    }

    auto& cg = compaction_group_for_sstable(sst);
    auto holder = cg.async_gate().hold();
    auto& view = cg.view_for_sstable(sst);
    auto lock_holder = co_await _t.get_compaction_manager().get_incremental_repair_read_lock(view, "maybe_split_sstable");
    co_return co_await compaction::maybe_split_offline_sstable(sst, view, co_await split_compaction_options());
}

future<std::vector<sstables::shared_sstable>> table::maybe_split_new_sstable(const sstables::shared_sstable& sst) {
    auto holder = async_gate().hold();
    co_return co_await _sg_manager->maybe_split_sstable(sst);
} 
```

File: compaction/compaction.cc [hunk 5]
```diff
@@ -2222,6 +2222,39 @@ uint64_t compaction_descriptor::sstables_size() const {
...
+    auto desc = compaction_descriptor({ sst }, sst->get_sstable_level(), compaction_descriptor::default_max_sstable_bytes,
+                                      sst->run_identifier(), compaction_type_options::make_split(opt.classifier));
+    desc.creator = [&t, sst] (shard_id _) {
+        // NOTE: preserves the sstable state, since want the output to be on the same state as the original.
+        // For example, if base table has views, it's important that sstable produced by repair will be
+        // in the staging state.
+        auto new_sst = t.make_sstable(sst->state());
+        // Also preserves the repaired state, such that the new sstable will be excluded by compaction
+        // while being processed by repair.
+        new_sst->move_repaired_state_from(*sst);
```
Comment (asias) [inline compaction/compaction.cc]: Here, we are actually inheriting the repair state from the original sst. The state of the original sst are not changed or moved. Perhaps, copy_repair_state_from() ? Btw, we are copying the repairing state not repaired state, I guess it makes more sense to just to call it repair_state.

File: streaming/consumer.cc [hunk 6]
```diff
@@ -67,26 +67,37 @@ mutation_reader_consumer make_streaming_consumer(sstring origin,
...
+                    co_return co_await cf->add_sstable_and_update_cache(sst, offstrategy);
+                }).then([cf, s, sst, use_view_update_path, &vb, &vbw, sstable_list_to_mark_as_repaired, origin, repaired_at]
+                        (std::vector<sstables::shared_sstable> new_sstables) mutable -> future<> {
+                    auto new_sstables_ = std::move(new_sstables);
+                    auto table = cf;
+
+                    // The sstables added into the table might have been split, so the actual sstables added will be marked
+                    // as repairing on completion.
+                    if (repaired_at && sstables::repair_origin == origin && sstable_list_to_mark_as_repaired) {
+                        sstable_list_to_mark_as_repaired->insert(new_sstables_.begin(), new_sstables_.end());
```
Comment (asias) [inline streaming/consumer.cc]: Nice. We do not need to change incremental repair itself to make it work.

File: streaming/consumer.cc [hunk 7]
```diff
@@ -67,26 +67,37 @@ mutation_reader_consumer make_streaming_consumer(sstring origin,
...
-                        return vbw.local().register_staging_sstable_tasks({sst}, cf->schema()->id());
+                        co_return co_await vbw.local().register_staging_sstable_tasks(new_sstables_, table->schema()->id());
                     } else if (use_view_update_path == db::view::sstable_destination_decision::staging_directly_to_generator) {
-                        return vb.local().register_staging_sstable(sst, std::move(cf));
+                        co_await coroutine::parallel_for_each(new_sstables_, [&vb, &table] (sstables::shared_sstable sst) -> future<> {
+                            return vb.local().register_staging_sstable(sst, table);
+                        });
                     }
-                    return make_ready_future<>();
+                    co_return;
```
Comment (asias) [inline streaming/consumer.cc:104]: This co_return is not necessary.

File: test/cluster/test_tablets2.py [hunk 8]
```diff
@@ -1809,3 +1809,95 @@ def move_sstables_to_upload(table_dir: str):
...
+    servers = await manager.servers_add(2, cmdline=cmdline, config=cfg, auto_rack_dc="dc1")
+
+    cql = manager.get_cql()
+
+    await manager.api.disable_tablet_balancing(servers[0].ip_addr)
+
+    initial_tablets = 2
+
+    async with new_test_keyspace(manager, f"WITH replication = {{'class': 'NetworkTopologyStrategy', 'replication_factor': 2}}") as ks:
+        await manager.api.enable_injection(servers[0].ip_addr, "make_all_groups_compactible", one_shot=False)
```
Comment (asias) [inline test/cluster/test_tablets2.py]: I could not find this injection. 

```
[scylla]$ git grep make_all_groups_compactible
test/cluster/test_tablets2.py:        await manager.api.enable_injection(servers[0].ip_addr, "make_all_groups_compactible", one_shot=False)
```

File: test/cluster/test_tablets2.py [hunk 9]
```diff
@@ -1809,3 +1809,95 @@ def move_sstables_to_upload(table_dir: str):
...
+            await generate_repair_work()
+            await manager.api.tablet_repair(servers[0].ip_addr, ks, "test", token)
+
+        await manager.api.disable_injection(servers[0].ip_addr, "tablet_resize_finalization_postpone")
+
+        async def finished_splitting():
+            tablet_count = await get_tablet_count(manager, servers[0], ks, 'test')
+            return tablet_count >= expected_tablet_count or None
+        # Give enough time for split to happen in debug mode
+        await wait_for(finished_splitting, time.time() + 120)
```
Comment (asias) [inline test/cluster/test_tablets2.py:2069]: Should it be asyncio.wait_for()?

File: test/cluster/test_tablets2.py [hunk 10]
```diff
@@ -1809,3 +1809,95 @@ def move_sstables_to_upload(table_dir: str):
...
+
+        await manager.server_stop(servers[0].server_id)
+        await manager.server_start(servers[0].server_id)
+        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
+        await manager.servers_see_each_other(servers)
```
Comment (asias) [inline test/cluster/test_tablets2.py]: Why do we restart node1? What do we want to check here?

File: replica/table.cc (hunk 4 above)
Comment (raphaelsc) [reply replica/table.cc]: Done

File: compaction/compaction.cc (hunk 5 above)
Comment (raphaelsc) [reply compaction/compaction.cc]: the renaming makes sense, thanks.

File: test/cluster/test_tablets2.py (hunk 10 above)
Comment (raphaelsc) [reply test/cluster/test_tablets2.py]: we want to verify that no unsplit sstables were left on the table dir, which happened before the fix if streaming consumed failed and forgot to remove the sstable due to https://github.com/scylladb/scylladb/issues/26958

File: test/cluster/test_tablets2.py (hunk 8 above)
Comment (raphaelsc) [reply test/cluster/test_tablets2.py]: Oops, let me check if it's really needed.

**Comment by raphaelsc** [comment]
v3:
- rebased
- renamed maybe_split_sstable() to maybe_split_new_sstable()
- renamed move_repaired_state_from() to copy_repair_state_from()
- removed unused injection make_all_groups_compactible
- fixed compilation issue in test/boost/sstable_test.hh
/

**Comment by raphaelsc** [comment]
@tgrabiec please review again.

**Comment by raphaelsc** [comment]
@tgrabiec please re-review.

**Comment by yaronkaikov** [comment]
> #### 🟢 CI State: SUCCESS
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider14.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider14.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	spider14.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider17.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider17.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	spider17.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider15.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)	✅	spider15.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22114/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	spider15.cloudius-systems.com
> dtest	[dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/20841/)	✅	
> [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/9284/)	✅	
> [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/12597/)	✅	
> #### Build Details:
> * Duration: 6 hr 20 min

@raphaelsc This CI run has failed, the reason for the wrong status report is due to a bug we had in pkg (which already been solved). i am re-running the CI, you should get the real result once it's completed

**Comment by raphaelsc** [comment]
@asias please take a look again too.

**Comment by asias** [comment]
> @asias please take a look again too.

Looks good to me. Thanks!

**Comment by bhalevy** [comment]
@raphaelsc I see there are conflicts, please rebase, so we can get it in ASAP.

File: compaction/compaction_manager.cc [hunk 11]
```diff
@@ -416,7 +416,7 @@ future<compaction_result> compaction_task_executor::compact_sstables(compaction_
         descriptor.enable_garbage_collection(co_await sstable_set_for_tombstone_gc(t));
     }
     descriptor.creator = [&t] (shard_id) {
-        return t.make_sstable();
+        return t.make_sstable(sstables::sstable_state::normal);
```
Comment (tgrabiec) [inline compaction/compaction_manager.cc:421]: Should this be `staging` when `offstrategy` is true?

**Comment by raphaelsc** [comment]
> @raphaelsc I see there are conflicts, please rebase, so we can get it in ASAP.

done

File: compaction/compaction_manager.cc (hunk 11 above)
Comment (raphaelsc) [reply compaction/compaction_manager.cc:421]: no, because staging sstables aren't really eligible for compaction (includes off-strategy), see: 
https://github.com/scylladb/scylladb/blob/master/compaction/compaction_manager.cc#L1592
https://github.com/scylladb/scylladb/blob/master/compaction/compaction.cc#L117

Comment (raphaelsc) [reply compaction/compaction_manager.cc:421]: only this split on new sstable (not loaded yet) might rewrite it, and the only one with requirement to preserve the location. I think I should add a protection and fail other compaction type if any input isn't eligible, to be more future proof.

**Comment by Annamikhlin** [comment]
> #### 🟢 CI State: SUCCESS
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	i-0fb6560bf9c2d975a
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	i-0fb6560bf9c2d975a
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	i-0fb6560bf9c2d975a
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	i-0e7b8021e17b41a60
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	i-0e7b8021e17b41a60
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	i-0e7b8021e17b41a60
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	i-0be7fd8145d5dccd5
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)	✅	i-0be7fd8145d5dccd5
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	i-0be7fd8145d5dccd5
> dtest	[dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/20930/)	✅	
> [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/9384/)	✅	
> [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/12692/)	✅	
> #### Build Details:
> * Duration: 4 hr 47 min

seems we have an issue with the final CI report - cause the CI job failed on `test_out_of_space_prevention.test_node_restart_while_tablet_split` test on all the modes - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22187/ - cc:/ @yaronkaikov 

@tgrabiec / @denesb - could you please dequeue these commits, it is failing gating - https://jenkins.scylladb.com/job/scylla-master/job/next/9936/

**Comment by denesb** [comment]
Dequeued.

**Comment by raphaelsc** [comment]
@paszkow @bhalevy While investigating the failure in test_node_restart_while_tablet_split, I realized the test forbids split during critical disk utilization, but the thing is that splits on restart, and splits on new sstables e.g. generated by repair, must happen in order to maintain correctness. Preexisting sstables can have split postponed once controller disables compaction, but not new ones generated by external processes. We cannot simply ignore the need to split. It's not like regular compaction which is just an optimization.

**Comment by raphaelsc** [comment]
> @paszkow @bhalevy While investigating the failure in test_node_restart_while_tablet_split, I realized the test forbids split during critical disk utilization, but the thing is that splits on restart, and splits on new sstables e.g. generated by repair, must happen in order to maintain correctness. Preexisting sstables can have split postponed once controller disables compaction, but not new ones generated by external processes. We cannot simply ignore the need to split. It's not like regular compaction which is just an optimization.

@tgrabiec to avoid split on restart of sstables generated before split decision, we'd need to persist split_ready_seq_number in a system table. restart can bypass split if this table never communicated split readiness to coordinator on the current sequence number.

**Comment by bhalevy** [comment]
> @paszkow @bhalevy While investigating the failure in test_node_restart_while_tablet_split, I realized the test forbids split during critical disk utilization, but the thing is that splits on restart, and splits on new sstables e.g. generated by repair, must happen in order to maintain correctness. Preexisting sstables can have split postponed once controller disables compaction, but not new ones generated by external processes. We cannot simply ignore the need to split. It's not like regular compaction which is just an optimization.

I agree.  I'm not sure we have the resolution to decide which splits would be allowed and which wouldn't be.
It may be simpler just to allow any split compaction in critical disk utilization.

**Comment by raphaelsc** [comment]
> > @paszkow @bhalevy While investigating the failure in test_node_restart_while_tablet_split, I realized the test forbids split during critical disk utilization, but the thing is that splits on restart, and splits on new sstables e.g. generated by repair, must happen in order to maintain correctness. Preexisting sstables can have split postponed once controller disables compaction, but not new ones generated by external processes. We cannot simply ignore the need to split. It's not like regular compaction which is just an optimization.
> 
> I agree. I'm not sure we have the resolution to decide which splits would be allowed and which wouldn't be. It may be simpler just to allow any split compaction in critical disk utilization.

I could optimize this later, by persisting local sequence number, and re-loading it on restart. So we can say whether split prepara phase is still ongoing, and rely on splits happening on background when possible. But I think it's a work that can come later, since we're late in the release process, and we want to reduce bug risks.

**Comment by bhalevy** [comment]
> > > @paszkow @bhalevy While investigating the failure in test_node_restart_while_tablet_split, I realized the test forbids split during critical disk utilization, but the thing is that splits on restart, and splits on new sstables e.g. generated by repair, must happen in order to maintain correctness. Preexisting sstables can have split postponed once controller disables compaction, but not new ones generated by external processes. We cannot simply ignore the need to split. It's not like regular compaction which is just an optimization.
> > 
> > 
> > I agree. I'm not sure we have the resolution to decide which splits would be allowed and which wouldn't be. It may be simpler just to allow any split compaction in critical disk utilization.
> 
> I could optimize this later, by persisting local sequence number, and re-loading it on restart. So we can say whether split prepara phase is still ongoing, and rely on splits happening on background when possible. But I think it's a work that can come later, since we're late in the release process, and we want to reduce bug risks.

@raphaelsc can you please spell out the problematic sequence of events?
I'm worried that allowing split compaction during critical disk utilization could lead to actually running out of space.
And then what? How do we recover from that?
Why cannot we recover from split compaction failure due to OOS prevention?
Could we just fail repair in this case if the split was induced by repair / split synchronization, and maybe retry later, after scale out evicts capacity from the full nodes?

**Comment by tgrabiec** [comment]
> Could we just fail repair in this case if the split was induced by repair / split synchronization, and maybe retry later, after scale out evicts capacity from the full nodes?

We could fail repair when trying attach sstable and there's need for split, and critical utilization.

We still need to split those sstables on restart, since the node already ACKed the split, and it may be finalized anytime.
And if we require that sstables are split on restart, we add a new problem, that a restart may need to split all sstables if we're early in the split process. Raphael's proposal to store ACK locally mitigates that, because it allows us to recognize that we're early in the split process and don't really need to split sstables. We would still need to split them if we already ACKed, so we may need to split those late sstables produced by repair.

**Comment by tgrabiec** [comment]
We wouldn't have the restart problem if we maintained the invariant that sealed sstables on disk are always split if the split was ACKed. So instead of splitting after sealing, we would have to split them before sealing. 

That also solves another problem we encountered in production. If sstable attaching fails, we currently will just leave the sstable on disk, but not make it accessible to reads until the next restart. That can cause data resurrection issues when the node finally restarts. If split-on-attach fails, we'll run into the same problem.

To fix both issues:
  1. don't seal an sstable if it requires a split. Split it unsealed. Never seal the old one.
  2. We don't try to split sstables on restart.

Phase 2. We can get rid of the need to split on attach by changing the global split algorithm to have 2 prepare phases.

Old algorithm:
1. advertise split decision, seq=x
2. collect ACKs for seq=x
3. execute finalizing topology transition

New algorithm:
1. advertise split decision, seq=x, phase=prepare
2. collect ACKs for seq=x
3. execute a new "prepare" topology transition
3.1 barrier
3.2 set phase=prepare2, seq=(x+1) 
4. collect ACKs for seq=(x+1).
5. execute finalizing topology transition

The topology transition in step 3 ensures that repair or other processes which could generate sstables which didn't see the need for split, are finished. Any sstables produced by them will be split after nodes ACK seq=(x+1).

**Comment by tgrabiec** [comment]
If we're looking for a quick fix for https://github.com/scylladb/scylladb/issues/26041, we could:
1) check if sstable is properly split before sealing
2) fail repair if it's not (exception from the check above will kill it). 

Repair will be retried by the scheduler. Unsplit sstable is not left on disk, so no failure after restart.

Need to be synchronized with the split ACK, so that we don't ACK between checking and attaching the sstable.

**Comment by raphaelsc** [comment]
> If we're looking for a quick fix for #26041, we could:
> 
> 1. check if sstable is properly split before sealing
> 2. fail repair if it's not (exception from the check above will kill it).
> 
> Repair will be retried by the scheduler. Unsplit sstable is not left on disk, so no failure after restart.
> 
> Need to be synchronized with the split ACK, so that we don't ACK between checking and attaching the sstable.

what's the problem with ACKing between checking and attaching the sstable? the ACK happens on loaded sstables. 

the problem I see with this approach is that we're essentially preventing repair during split. any sstable generated by repair during split will be unsplit, so repair writer can never succeed. If so, isn't it better to serialize them?

why don't we remove split from add_sstable_and_update_cache()? and split inside streaming consumers, before sealing the sstable. if we cannot split because of out of space prevention, then we fail repair writer. I see no reason for failing repair when split can be performed.

**Comment by raphaelsc** [comment]
> > If we're looking for a quick fix for #26041, we could:
> > 
> > 1. check if sstable is properly split before sealing
> > 2. fail repair if it's not (exception from the check above will kill it).
> > 
> > Repair will be retried by the scheduler. Unsplit sstable is not left on disk, so no failure after restart.
> > Need to be synchronized with the split ACK, so that we don't ACK between checking and attaching the sstable.
> 
> what's the problem with ACKing between checking and attaching the sstable? the ACK happens on loaded sstables.
> 
> the problem I see with this approach is that we're essentially preventing repair during split. any sstable generated by repair during split will be unsplit, so repair writer can never succeed. If so, isn't it better to serialize them?
> 
> why don't we remove split from add_sstable_and_update_cache()? and split inside streaming consumers, before sealing the sstable. if we cannot split because of out of space prevention, then we fail repair writer. I see no reason for failing repair when split can be performed.

Tomek and I agreed on this, I am proceeding with it.

**Comment by tgrabiec** [comment]
> what's the problem with ACKing between checking and attaching the sstable? the ACK happens on loaded sstables.

We want the invariant that after ACK, all sealed sstables will be split. If check-and-attach is not atomic, this sequence is possible:
1. no split decision set. Unsplit sstable is checked, no need to split, sealed. 
2. split decision is set and ACKed
3. unsplit sstable is attached


> 
> the problem I see with this approach is that we're essentially preventing repair during split. any sstable generated by repair during split will be unsplit, so repair writer can never succeed. If so, isn't it better to serialize them?

If repair starts after split decision, the repair writer will produce split sstables. So we fail only repairs which started before split. Retry will succeed. Unless there's another split. Eventually splits should stop though. 

> 
> why don't we remove split from add_sstable_and_update_cache()? and split inside streaming consumers, before sealing the sstable. if we cannot split because of out of space prevention, then we fail repair writer. I see no reason for failing repair when split can be performed.

That's better, I was just suggesting a quick fix.

File: replica/table.cc [hunk 12]
```diff
@@ -1373,29 +1374,34 @@ table::do_add_sstable_and_update_cache(compaction_group& cg, sstables::shared_ss
...
 }
 
-future<>
+future<std::vector<sstables::shared_sstable>>
 table::do_add_sstable_and_update_cache(sstables::shared_sstable new_sst, sstables::offstrategy offstrategy, bool trigger_compaction) {
-    for (auto sst : co_await maybe_split_new_sstable(new_sst)) {
+    auto output = co_await maybe_split_new_sstable(new_sst);
+    for (auto sst : output) {
         auto& cg = compaction_group_for_sstable(sst);
         // Hold gate to make share compaction group is alive.
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply replica/table.cc]: Not introduced in this PR.

**Comment by tgrabiec** [comment]
I opened https://github.com/scylladb/scylladb/issues/27414 for the general problem of sstable attach failure.

**Comment by asias** [comment]
> We wouldn't have the restart problem if we maintained the invariant that sealed sstables on disk are always split if the split was ACKed. So instead of splitting after sealing, we would have to split them before sealing.
> 
> That also solves another problem we encountered in production. If sstable attaching fails, we currently will just leave the sstable on disk, but not make it accessible to reads until the next restart. That can cause data resurrection issues when the node finally restarts. If split-on-attach fails, we'll run into the same problem.
> 
> To fix both issues:
> 
> 1. don't seal an sstable if it requires a split. Split it unsealed. Never seal the old one.
> 2. We don't try to split sstables on restart.
> 
> Phase 2. We can get rid of the need to split on attach by changing the global split algorithm to have 2 prepare phases.
> 
> Old algorithm:
> 
> 1. advertise split decision, seq=x
> 2. collect ACKs for seq=x
> 3. execute finalizing topology transition
> 
> New algorithm:
> 
> 1. advertise split decision, seq=x, phase=prepare
> 2. collect ACKs for seq=x
> 3. execute a new "prepare" topology transition
>    3.1 barrier
>    3.2 set phase=prepare2, seq=(x+1)
> 4. collect ACKs for seq=(x+1).
> 5. execute finalizing topology transition
> 
> The topology transition in step 3 ensures that repair or other processes which could generate sstables which didn't see the need for split, are finished. Any sstables produced by them will be split after nodes ACK seq=(x+1).

IMO, split is getting way too complicated. It is hard and complicated to implement and reason about it in a way that half is serialized with the topology state machine while the other half is not. If we choose to make the split a sync operation that serialize with all the tablet operations like migration and repair. Things will be simplified significantly. It is not that bad if we forbid all the migrations or repairs during the split for the splitting table.

**Comment by bhalevy** [comment]
> > We wouldn't have the restart problem if we maintained the invariant that sealed sstables on disk are always split if the split was ACKed. So instead of splitting after sealing, we would have to split them before sealing.
> > That also solves another problem we encountered in production. If sstable attaching fails, we currently will just leave the sstable on disk, but not make it accessible to reads until the next restart. That can cause data resurrection issues when the node finally restarts. If split-on-attach fails, we'll run into the same problem.
> > To fix both issues:
> > 
> > 1. don't seal an sstable if it requires a split. Split it unsealed. Never seal the old one.
> > 2. We don't try to split sstables on restart.
> > 
> > Phase 2. We can get rid of the need to split on attach by changing the global split algorithm to have 2 prepare phases.
> > Old algorithm:
> > 
> > 1. advertise split decision, seq=x
> > 2. collect ACKs for seq=x
> > 3. execute finalizing topology transition
> > 
> > New algorithm:
> > 
> > 1. advertise split decision, seq=x, phase=prepare
> > 2. collect ACKs for seq=x
> > 3. execute a new "prepare" topology transition
> >    3.1 barrier
> >    3.2 set phase=prepare2, seq=(x+1)
> > 4. collect ACKs for seq=(x+1).
> > 5. execute finalizing topology transition
> > 
> > The topology transition in step 3 ensures that repair or other processes which could generate sstables which didn't see the need for split, are finished. Any sstables produced by them will be split after nodes ACK seq=(x+1).
> 
> IMO, split is getting way too complicated. It is hard and complicated to implement and reason about it in a way that half is serialized with the topology state machine while the other half is not. If we choose to make the split a sync operation that serialize with all the tablet operations like migration and repair. Things will be simplified significantly. It is not that bad if we forbid all the migrations or repairs during the split for the splitting table.

I think this could work if the split preparation is made a tablet-transition so it can be serialized *per-tablet*.

It is questionable if the split decision should be serialized globally.
We want all new sstables after split decision has been made to be segregated upon creation.
To avoid a big hiccup, we may want to serialize this step per-tablet as well.

**Comment by asias** [comment]
> > > We wouldn't have the restart problem if we maintained the invariant that sealed sstables on disk are always split if the split was ACKed. So instead of splitting after sealing, we would have to split them before sealing.
> > > That also solves another problem we encountered in production. If sstable attaching fails, we currently will just leave the sstable on disk, but not make it accessible to reads until the next restart. That can cause data resurrection issues when the node finally restarts. If split-on-attach fails, we'll run into the same problem.
> > > To fix both issues:
> > > 
> > > 1. don't seal an sstable if it requires a split. Split it unsealed. Never seal the old one.
> > > 2. We don't try to split sstables on restart.
> > > 
> > > Phase 2. We can get rid of the need to split on attach by changing the global split algorithm to have 2 prepare phases.
> > > Old algorithm:
> > > 
> > > 1. advertise split decision, seq=x
> > > 2. collect ACKs for seq=x
> > > 3. execute finalizing topology transition
> > > 
> > > New algorithm:
> > > 
> > > 1. advertise split decision, seq=x, phase=prepare
> > > 2. collect ACKs for seq=x
> > > 3. execute a new "prepare" topology transition
> > >    3.1 barrier
> > >    3.2 set phase=prepare2, seq=(x+1)
> > > 4. collect ACKs for seq=(x+1).
> > > 5. execute finalizing topology transition
> > > 
> > > The topology transition in step 3 ensures that repair or other processes which could generate sstables which didn't see the need for split, are finished. Any sstables produced by them will be split after nodes ACK seq=(x+1).
> > 
> > 
> > IMO, split is getting way too complicated. It is hard and complicated to implement and reason about it in a way that half is serialized with the topology state machine while the other half is not. If we choose to make the split a sync operation that serialize with all the tablet operations like migration and repair. Things will be simplified significantly. It is not that bad if we forbid all the migrations or repairs during the split for the splitting table.
> 
> I think this could work if the split preparation is made a tablet-transition so it can be serialized _per-tablet_.
> 
> It is questionable if the split decision should be serialized globally. We want all new sstables after split decision has been made to be segregated upon creation. To avoid a big hiccup, we may want to serialize this step per-tablet as well.

Yes, I think a new split tablet_transition_kind is good enough. 

```
enum class tablet_transition_kind {
    // Tablet replica is migrating from one shard to another.
    // The new replica is (tablet_transition_info::next - tablet_info::replicas).
    // The leaving replica is (tablet_info::replicas - tablet_transition_info::next).
    migration,

    // Like migration, but the new pending replica is on the same host as leaving replica.
    intranode_migration,

    // New tablet replica is replacing a dead one.
    // The new replica is (tablet_transition_info::next - tablet_info::replicas).
    // The leaving replica is (tablet_info::replicas - tablet_transition_info::next).
    rebuild,

    // Like rebuild, but instead of streaming data from all tablet replicas,
    // it repairs the tablet and streams data from one replica.
    rebuild_v2,

    // Repair the tablet replicas
    repair,

    // Split the sstables for tablet split
    split, 
};
```

This alone will serialize with most of  the tablet operations.

So, the new split algorithm looks like:

- Advertise split decision for a table
- New sstables by memtable flush, repair, migration, rebuild_v2 (under the hood repair + migration), will be split when written after the split decision. 
- The tablet_transition_kind::split tasks will be scheduled for each tablets in that table. This will split any existing sstables added to the system.  There will be no pending sstables produced by migration or repair when tablet_transition_kind::split task is running (it needs to wait for the previous migration or repair to finish). At the end of the tablet_transition_kind::split task, it reports that the tablet is ready for the split finalization (SPLIT_ACK). If the node is restarted during tablet_transition_kind::split, the split task will be rescheduled by the coordinator. 
- After this, other tablet_transition_kind can continue to be scheduled, while waiting for other tablets in the same table. 
- When all tablets of the table have SPLIT_ACK, executes the transition_state::tablet_resize_finalization. 

The tablet_transition_kind::split task can be aborted and rescheduled later in case a high priority task is needed, e.g., decommission a node ASAP. 

This will continue to work if we add more tablet operations like tablet_transition_kind::restore. No special synchronization is needed for individual operations.

**Comment by bhalevy** [comment]
We should fix this issue now on top of the existing infrastructure, for backporting purposes.
Looking forward, I think we should improve the design by using tablet transition(s) for split for proper serialization.

**Comment by avikivity** [comment]
We cannot serialize split with anything else. It's too time consuming.

We can have a replica-local function to help with synchronizing the finalization step, instead of coding the steps specially for every operation.

**Comment by avikivity** [comment]
If split is made per-tablet, then it's okay to make it an exclusive tablet state, since we can migrate other tablets while one is being split.

**Comment by raphaelsc** [comment]
> We should fix this issue now on top of the existing infrastructure, for backporting purposes. Looking forward, I think we should improve the design by using tablet transition(s) for split for proper serialization.

This is exactly how I am proceeding. I am ignoring major redesigns by now, but we should keep an eye on how to improve synchronization.

**Comment by asias** [comment]
> If split is made per-tablet, then it's okay to make it an exclusive tablet state, since we can migrate other tablets while one is being split.

See my proposal  above, https://github.com/scylladb/scylladb/pull/26528#issuecomment-3615074404, the tablet_transition_kind::split is per tablet, when one tablet is splitting, it does not prevent other tablets to migrate or anything, it only prevents the tablet itself executing migration or repair.

**Comment by raphaelsc** [comment]
V4: 
- new variant where no unsplit sstable will be sealed on disk. Streaming produces unsealed sstable, and seal right before attaching.
- fixed interaction problem with out of space prevention which relies on restart not splitting under critical utilization, made possible with new invariant.
- streaming writer will now fail if need for split under critical utilization
- sstable now unlinked automatically when attaching for streaming consumer fails, fixing #27414

**Comment by tgrabiec** [comment]
> > If split is made per-tablet, then it's okay to make it an exclusive tablet state, since we can migrate other tablets while one is being split.
> 
> See my proposal above, [#26528 (comment)](https://github.com/scylladb/scylladb/pull/26528#issuecomment-3615074404), the tablet_transition_kind::split is per tablet, when one tablet is splitting, it does not prevent other tablets to migrate or anything, it only prevents the tablet itself executing migration or repair.

I think it wouldn't solve load-and-stream though, which doesn't run as a tablet transition.

But I think it's a good idea to make split ACK a tablet transition. But I would improve it to avoid doing compaction in it. Split compaction can be asynchronous, it's just that the ACK we propagate in load_stats would only be a signal that per-tablet split may be ready. The coordinator schedules ACK transition, which re-checks things, and if all sstables are split, it records the hard ACK in tablet metadata. If not, it exits without doing anything.

This way we don't need to deal with cancelations, since the transition is short.

Blocking tablets in transitions for long can have bad effects on load balance currently, since the load balancer can be forced to pick bad candidates for migrations if good candidates are locked. This can mess up with per-table load balance. The cluster may appear balanced globally, but messed up per table.

**Comment by denesb** [comment]
@scylladbbot trigger-ci

**Comment by denesb** [comment]
> [test_multi_column_lwt_during_split_merge.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22395/testReport/junit/cluster.lwt/test_lwt_during_tablets_resize/dev___test_py___dev___test_multi_column_lwt_during_split_merge_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multi_column_lwt_during_split_merge.dev.2)

This looks like https://github.com/scylladb/scylladb/issues/26801, but that is supposed to be fixed (https://github.com/scylladb/scylladb/commit/88765f627af5114faa9ef4424fe2fce2022d431a). Maybe missing rebase?

**Comment by bhalevy** [comment]
> > > If split is made per-tablet, then it's okay to make it an exclusive tablet state, since we can migrate other tablets while one is being split.
> > 
> > 
> > See my proposal above, [#26528 (comment)](https://github.com/scylladb/scylladb/pull/26528#issuecomment-3615074404), the tablet_transition_kind::split is per tablet, when one tablet is splitting, it does not prevent other tablets to migrate or anything, it only prevents the tablet itself executing migration or repair.
> 
> I think it wouldn't solve load-and-stream though, which doesn't run as a tablet transition.

Not yet.  But we do plan to offer a cluster restore api that will use tablet transitions for snapshot (See https://github.com/scylladb/scylladb/issues/27512)

> But I think it's a good idea to make split ACK a tablet transition. But I would improve it to avoid doing compaction in it. Split compaction can be asynchronous, it's just that the ACK we propagate in load_stats would only be a signal that per-tablet split may be ready. The coordinator schedules ACK transition, which re-checks things, and if all sstables are split, it records the hard ACK in tablet metadata. If not, it exits without doing anything.

How about a split_start transition so we serialize this state transition per-tablet.
With a split_start transition no sstable would need to be split on split_ack since all sstables would be written and sealed either before split started or after (in which case the can be segregated for split in the sstable writer), including sstables written by repair (and in the future load-and-stream)

> This way we don't need to deal with cancelations, since the transition is short.
> 
> Blocking tablets in transitions for long can have bad effects on load balance currently, since the load balancer can be forced to pick bad candidates for migrations if good candidates are locked. This can mess up with per-table load balance. The cluster may appear balanced globally, but messed up per table.

We have other long transitions like tablet rebuild, not doing the split compaction in a transition may mitigate the load-balancing problem but it doesn't solve it.

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)	✅	spider18.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)	✅	spider18.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	❌	spider18.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)	❌	spider4.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)	✅	spider16.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)	✅	spider16.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22398/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	❌	spider16.cloudius-systems.com
> #### Failed Tests (2/55841):
> * [test_table_drop_with_auto_snapshot.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22398/testReport/junit/cluster/test_tablets2/debug___Unit_Tests_Custom___debug___test_table_drop_with_auto_snapshot_debug_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_table_drop_with_auto_snapshot.debug.2)
> * [test_table_drop_with_auto_snapshot.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22398/testReport/junit/cluster/test_tablets2/dev___Unit_Tests_Custom___dev___test_table_drop_with_auto_snapshot_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_table_drop_with_auto_snapshot.dev.3)
> 
> #### Build Details:
> * Duration: 3 hr 52 min
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

https://github.com/scylladb/scylladb/issues/27501

**Comment by raphaelsc** [comment]
@scylladbbot trigger-ci

**Comment by tgrabiec** [comment]
> > > > If split is made per-tablet, then it's okay to make it an exclusive tablet state, since we can migrate other tablets while one is being split.
> > > 
> > > 
> > > See my proposal above, [#26528 (comment)](https://github.com/scylladb/scylladb/pull/26528#issuecomment-3615074404), the tablet_transition_kind::split is per tablet, when one tablet is splitting, it does not prevent other tablets to migrate or anything, it only prevents the tablet itself executing migration or repair.
> > 
> > 
> > I think it wouldn't solve load-and-stream though, which doesn't run as a tablet transition.
> 
> Not yet. But we do plan to offer a cluster restore api that will use tablet transitions for snapshot (See #27512)
> 
> > But I think it's a good idea to make split ACK a tablet transition. But I would improve it to avoid doing compaction in it. Split compaction can be asynchronous, it's just that the ACK we propagate in load_stats would only be a signal that per-tablet split may be ready. The coordinator schedules ACK transition, which re-checks things, and if all sstables are split, it records the hard ACK in tablet metadata. If not, it exits without doing anything.
> 
> How about a split_start transition so we serialize this state transition per-tablet. With a split_start transition no sstable would need to be split on split_ack since all sstables would be written and sealed either before split started or after (in which case the can be segregated for split in the sstable writer), including sstables written by repair (and in the future load-and-stream)

split_start is not better than split_ack in avoiding split work. It doesn't matter if split_start waits for repair which started before the decision to split, or split_ack waits for it, in either case we will have to split those sstables.

Currently, split_ack is a better choice because it accounts for things like load-and-stream, which may add sstables outside transitions. So it's a safer approach IMO. 

> 
> > This way we don't need to deal with cancelations, since the transition is short.
> > Blocking tablets in transitions for long can have bad effects on load balance currently, since the load balancer can be forced to pick bad candidates for migrations if good candidates are locked. This can mess up with per-table load balance. The cluster may appear balanced globally, but messed up per table.
> 
> We have other long transitions like tablet rebuild, not doing the split compaction in a transition may mitigate the load-balancing problem but it doesn't solve it.

True. But the problem is more likely to happen during splits, which correlates with size imbalance forming (e.g. data ingestion). repair is often run in a steady state.

If we can make transitions shorter, that's always better.

**Comment by raphaelsc** [comment]
> We wouldn't have the restart problem if we maintained the invariant that sealed sstables on disk are always split if the split was ACKed. So instead of splitting after sealing, we would have to split them before sealing.
> 
> That also solves another problem we encountered in production. If sstable attaching fails, we currently will just leave the sstable on disk, but not make it accessible to reads until the next restart. That can cause data resurrection issues when the node finally restarts. If split-on-attach fails, we'll run into the same problem.
> 
> To fix both issues:
> 
> 1. don't seal an sstable if it requires a split. Split it unsealed. Never seal the old one.
> 2. We don't try to split sstables on restart.
> 
> Phase 2. We can get rid of the need to split on attach by changing the global split algorithm to have 2 prepare phases.
> 
> Old algorithm:
> 
> 1. advertise split decision, seq=x
> 2. collect ACKs for seq=x
> 3. execute finalizing topology transition
> 
> New algorithm:
> 
> 1. advertise split decision, seq=x, phase=prepare
> 2. collect ACKs for seq=x
> 3. execute a new "prepare" topology transition
>    3.1 barrier
>    3.2 set phase=prepare2, seq=(x+1)
> 4. collect ACKs for seq=(x+1).
> 5. execute finalizing topology transition
> 
> The topology transition in step 3 ensures that repair or other processes which could generate sstables which didn't see the need for split, are finished. Any sstables produced by them will be split after nodes ACK seq=(x+1).

Don't we need the ACK collection in step 4 to happen in the topology transition in step 3? Otherwise, we could still have a new repair process initiated between step 3 and 4, and we end up with the same problem.

**Comment by raphaelsc** [comment]
> > > If split is made per-tablet, then it's okay to make it an exclusive tablet state, since we can migrate other tablets while one is being split.
> > 
> > 
> > See my proposal above, [#26528 (comment)](https://github.com/scylladb/scylladb/pull/26528#issuecomment-3615074404), the tablet_transition_kind::split is per tablet, when one tablet is splitting, it does not prevent other tablets to migrate or anything, it only prevents the tablet itself executing migration or repair.
> 
> I think it wouldn't solve load-and-stream though, which doesn't run as a tablet transition.
> 
> But I think it's a good idea to make split ACK a tablet transition. But I would improve it to avoid doing compaction in it. Split compaction can be asynchronous, it's just that the ACK we propagate in load_stats would only be a signal that per-tablet split may be ready. The coordinator schedules ACK transition, which re-checks things, and if all sstables are split, it records the hard ACK in tablet metadata. If not, it exits without doing anything.
> 
> This way we don't need to deal with cancelations, since the transition is short.
> 

Agree.

split (phase 2) ack, as topology transition, is a good solution

1) enters split (phase 2) ack transition
2) executes barrier, ensures it waits for things like load-and-stream that doesn't go through coordinator
3) rpc verb for rechecking all replicas are split ready

wouldn't it be enough to double check with a verb in execution phase?

similar to how we check the decision is still to split within the execution transition?!

since we want the "double check" and actual finalization to happen atomically.

**Comment by bhalevy** [comment]
@raphaelsc / @asias is the issue really restricted to incremental repair?
Can't the race between sstable sealing and split finalization happen with full repair as well?

**Comment by denesb** [comment]
@tgrabiec @raphaelsc I see there is still discussion here, is it related to this PR (more changes needed) or long term solutions (follow-up)?
@tgrabiec if the latest version is good enough, please approve the PR, so we can merge as soon as we get green CI.

**Comment by raphaelsc** [comment]
> @tgrabiec @raphaelsc I see there is still discussion here, is it related to this PR (more changes needed) or long term solutions (follow-up)? 

long term, we hijacked this PR to discuss it. we should open a new issue with the ideas

**Comment by raphaelsc** [comment]
> @raphaelsc / @asias is the issue really restricted to incremental repair? Can't the race between sstable sealing and split finalization happen with full repair as well?

with full repair, we will split the sstable before attaching it to the table (doesn't happen with incremental repair). if there's a failure while splitting, we can leave unsplit sstable on disk, that's https://github.com/scylladb/scylladb/issues/27414, which is covered now in new version. so yes, we could reproduce it with full repair too. problem much easier to reproduce with incremental repair, but you have a point it can happen with regular repair and even load-and-stream. Perhaps PR should be renamed to a more generic title: Synchronize streaming consumers and tablet split

**Comment by tgrabiec** [comment]
> > We wouldn't have the restart problem if we maintained the invariant that sealed sstables on disk are always split if the split was ACKed. So instead of splitting after sealing, we would have to split them before sealing.
> > That also solves another problem we encountered in production. If sstable attaching fails, we currently will just leave the sstable on disk, but not make it accessible to reads until the next restart. That can cause data resurrection issues when the node finally restarts. If split-on-attach fails, we'll run into the same problem.
> > To fix both issues:
> > 
> > 1. don't seal an sstable if it requires a split. Split it unsealed. Never seal the old one.
> > 2. We don't try to split sstables on restart.
> > 
> > Phase 2. We can get rid of the need to split on attach by changing the global split algorithm to have 2 prepare phases.
> > Old algorithm:
> > 
> > 1. advertise split decision, seq=x
> > 2. collect ACKs for seq=x
> > 3. execute finalizing topology transition
> > 
> > New algorithm:
> > 
> > 1. advertise split decision, seq=x, phase=prepare
> > 2. collect ACKs for seq=x
> > 3. execute a new "prepare" topology transition
> >    3.1 barrier
> >    3.2 set phase=prepare2, seq=(x+1)
> > 4. collect ACKs for seq=(x+1).
> > 5. execute finalizing topology transition
> > 
> > The topology transition in step 3 ensures that repair or other processes which could generate sstables which didn't see the need for split, are finished. Any sstables produced by them will be split after nodes ACK seq=(x+1).
> 
> Don't we need the ACK collection in step 4 to happen in the topology transition in step 3? Otherwise, we could still have a new repair process initiated between step 3 and 4, and we end up with the same problem.

I was assuming that repair would use splitting interposer in the writer. In that case, repair initiated after step 3 would produce split sstables.

If we do the split_ack transition approach, we don't really care. I'm now in favor of split_ack transition.

File: replica/table.cc [hunk 13]
```diff
@@ -1398,6 +1395,39 @@ table::add_sstables_and_update_cache(const std::vector<sstables::shared_sstable>
...
+            co_await do_add_sstable_and_update_cache(cg, std::move(sst), offstrategy, trigger_compaction);
+        }
+    } catch (...) {
+        ex = std::current_exception();
+    }
+
+    if (ex) {
+        tlogger.error("Failed to load SSTable {} of origin {} due to {}, it will be unlinked automatically...", sst->get_filename(), sst->get_origin(), ex);
+        co_await sst->unlink();
+        co_await coroutine::return_exception_ptr(std::move(ex));
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply replica/table.cc:1445]: He's right.

File: streaming/consumer.cc [hunk 14]
```diff
@@ -63,30 +63,45 @@ mutation_reader_consumer make_streaming_consumer(sstring origin,
...
-                }).then([cf, s, sst, use_view_update_path, &vb, &vbw]() mutable -> future<> {
+                    co_return co_await cf->add_new_sstable_and_update_cache(sst, on_add, offstrategy);
+                }).then([cf, s, sst, use_view_update_path, &vb, &vbw] (std::vector<sstables::shared_sstable> new_sstables) mutable -> future<> {
+                    auto& vb_ = vb;
+                    auto new_sstables_ = std::move(new_sstables);
+                    auto table = cf;
+
                     if (use_view_update_path == db::view::sstable_destination_decision::staging_managed_by_vbc) {
-                        return vbw.local().register_staging_sstable_tasks({sst}, cf->schema()->id());
+                        co_return co_await vbw.local().register_staging_sstable_tasks(new_sstables, cf->schema()->id());
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply streaming/consumer.cc]: Right

File: streaming/consumer.cc [hunk 15]
```diff
@@ -75,6 +78,9 @@ mutation_reader_consumer make_streaming_consumer(sstring origin,
                                 sstable_list_to_mark_as_repaired->insert(loading_sst);
                             }
                         }
+                        if (loading_sst == sst) {
+                            co_await loading_sst->seal_sstable(cfg.backup);
+                        }
```
Comment (tgrabiec) [inline streaming/consumer.cc:83]: Shouldn't add_new_sstable_and_update_cache() seal it? Since it seals the split ones, it makes sense if it also seals the original one if there's no need to split.

File: compaction/compaction_manager.cc [hunk 16]
```diff
@@ -2290,8 +2290,12 @@ compaction_manager::maybe_split_new_sstable(sstables::shared_sstable sst, compac
...
         co_return std::vector<sstables::shared_sstable>{sst};
     }
-    if (!can_proceed(&t)) {
-        co_return std::vector<sstables::shared_sstable>{sst};
+    // Throw an error if split cannot be performed due to e.g. out of space prevention.
+    // We don't want to prevent split because compaction is temporarily disabled on a view only for synchronization,
+    // which is uneeded against new sstables that aren't part of any set yet, so never use can_proceed(&t) here.
+    if (is_disabled()) {
+        co_return coroutine::exception(std::make_exception_ptr(std::runtime_error(format("Cannot split {} because manager has compaction disabled, " \
+                                                                                         "reason might be out of space prevention", sst->get_filename()))));
```
Comment (tgrabiec) [inline compaction/compaction_manager.cc:2302]: Would be nice if can_proceed() told us the reason, but this can be fixed later.

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: replica/table.cc (hunk 13 above)
[the remark this answers is not in the document]
Comment (tgrabiec) [reply replica/table.cc:1445]: If split fails, we want to remove any sstable (left or right) which might be already sealed.

[the remark this answers is not in the document]
Comment (tgrabiec) [reply replica/table.cc:1445]: split compaction will produce sealed sstables, right? 

Perhaps we should make split compaction preserve not-sealed state, so that we seal everything here. And remove all stables on exception.

[the remark this answers is not in the document]
Comment (raphaelsc) [reply replica/table.cc:1445]: we could have compaction_manager::maybe_split_new_sstable track all new sstables, and just unlink them on exception. we don't really have to write them unsealed, since they're split.

[the remark this answers is not in the document]
Comment (raphaelsc) [reply replica/table.cc:1445]: ah just remembered compaction will automatically unlink all new sstables on failure, see compaction::delete_sstables_for_interrupted_compaction().

File: streaming/consumer.cc (hunk 15 above)
Comment (raphaelsc) [reply streaming/consumer.cc:83]: It was my first direction, but later I found it better that the caller which produced unsealed sstable is also responsible for sealing. Leave the sealing knowledge in the consumer. add_new_sstable_and_update_cache() only concerns itself with maybe splitting and attaching.

File: compaction/compaction_manager.cc (hunk 16 above)
Comment (raphaelsc) [reply compaction/compaction_manager.cc:2302]: Agreed. There can be simulteanously more than 1 reason, example out of space prevention + shutdown, but I think we can do it.

File: streaming/consumer.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (raphaelsc) [reply streaming/consumer.cc]: fixed

File: replica/table.cc [hunk 17]
```diff
@@ -1375,12 +1374,10 @@ table::do_add_sstable_and_update_cache(compaction_group& cg, sstables::shared_ss
...
 future<>
 table::do_add_sstable_and_update_cache(sstables::shared_sstable new_sst, sstables::offstrategy offstrategy, bool trigger_compaction) {
-    for (auto sst : co_await maybe_split_new_sstable(new_sst)) {
-        auto& cg = compaction_group_for_sstable(sst);
-        // Hold gate to make share compaction group is alive.
-        auto holder = cg.async_gate().hold();
-        co_await do_add_sstable_and_update_cache(cg, std::move(sst), offstrategy, trigger_compaction);
-    }
+    auto& cg = compaction_group_for_sstable(new_sst);
+    // Hold gate to make share compaction group is alive.
```
[the remark this answers is not in the document]
Comment (raphaelsc) [reply replica/table.cc:1381]: preexisting

File: streaming/consumer.cc (hunk 15 above)
Comment (tgrabiec) [reply streaming/consumer.cc:83]: Ok.

**Comment by raphaelsc** [comment]
v5:
- rebased
- fixed some cosmetic issues
- fixed use-after-free in make_streaming_consumer()
- note: removal of new sstable(s) on split failure is already done in compaction::delete_sstables_for_interrupted_compaction()

File: replica/table.cc (hunk 13 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply replica/table.cc:1445]: @raphaelsc IIUC the problem is if split compaction succeeded and we hit an error after that.  Who deletes the split sstables then?

[the remark this answers is not in the document]
Comment (raphaelsc) [reply replica/table.cc:1445]: this is a good point. I focused only on the failing split scenario raised by Tomek. For successful split, we indeed can unlink them on failure to add

[the remark this answers is not in the document]
Comment (raphaelsc) [reply replica/table.cc:1445]: Fixed

**Comment by raphaelsc** [comment]
v6:
fixed exception handling after successful split in add_new_sstable_and_update_cache()

**Comment by bhalevy** [comment]
@tgrabiec please re-review

File: replica/table.cc [hunk 18]
```diff
@@ -1397,6 +1397,52 @@ table::add_sstables_and_update_cache(const std::vector<sstables::shared_sstable>
...
+
+        ssts = co_await maybe_split_new_sstable(new_sst);
+        // on sucessful split, input sstable is unlinked.
+        new_sst = nullptr;
+        for (auto& sst : ssts) {
+            auto& cg = compaction_group_for_sstable(sst);
+            // Hold gate to make sure compaction group is alive.
+            auto holder = cg.async_gate().hold();
+            co_await on_add(sst);
+            co_await do_add_sstable_and_update_cache(cg, sst, offstrategy, trigger_compaction);
```
Comment (tgrabiec) [inline replica/table.cc:1425]: When do_add_sstable_and_update_cache() throws, we don't know if the sstable was already added to the sstable set or not. If it was added, we shouldn't unlink it because it may be observed.
So I think the responsibility for unlinking should by on do_add_sstable_and_update_cache(), or we should pass sst by reference and let it clear it out when sstable is consumed by external_updater.

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: replica/table.cc (hunk 18 above)
Comment (raphaelsc) [reply replica/table.cc:1425]: Makes sense

**Comment by raphaelsc** [comment]
v7: account for do_add_sstable_and_update_cache() throwing after sstable has been loaded

**Comment by raphaelsc** [comment]
@tgrabiec please review again.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/pull/27530 disables incremental repair until this PR fixes https://github.com/scylladb/scylladb/issues/26041 and https://github.com/scylladb/scylladb/issues/27414 .

Please revert #27530 following the fix and consider backporting the fix and the revert back to incremental_mode="incremental" by default to 2025.4

**Review by tgrabiec — APPROVED** [review]

**Comment by raphaelsc** [comment]
v8: return intact sstables returned by maybe_split_new_sstable() in add_new_sstable_and_update_cache(), in order to fix view updates from staging.

**Comment by raphaelsc** [comment]
> #27530 disables incremental repair until this PR fixes #26041 and #27414 .
> 
> Please revert #27530 following the fix and consider backporting the fix and the revert back to incremental_mode="incremental" by default to 2025.4

Sure.

**Review by tgrabiec — APPROVED** [review]

**Comment by bhalevy** [comment]
I'm not sure if ci was retriggered so doing it now.

@scylladbbot trigger-ci

**Comment by raphaelsc** [comment]
> I'm not sure if ci was retriggered so doing it now.
> 
> @scylladbbot trigger-ci

it's taking a long while sometimes for it to start.

**Comment by bhalevy** [comment]
> > I'm not sure if ci was retriggered so doing it now.
> > @scylladbbot trigger-ci
> 
> it's taking a long while sometimes for it to start.

Over 5 hours?
It looked like the jenkins job was not running

**Comment by raphaelsc** [comment]
> > > I'm not sure if ci was retriggered so doing it now.
> > > @scylladbbot trigger-ci
> > 
> > 
> > it's taking a long while sometimes for it to start.
> 
> Over 5 hours? It looked like the jenkins job was not running

@yaronkaikov any idea what might happened? we might have lost the logs, since ci was retriggered. is it a known issue?

**Comment by yaronkaikov** [comment]
> > > > I'm not sure if ci was retriggered so doing it now.
> > > > @scylladbbot trigger-ci
> > > 
> > > 
> > > it's taking a long while sometimes for it to start.
> > 
> > 
> > Over 5 hours? It looked like the jenkins job was not running
> 
> @yaronkaikov any idea what might happened? we might have lost the logs, since ci was retriggered. is it a known issue?

The queue is very long due to some changes we did with dtest, we already reverted this. So i am trying now to release the queue, it will slowing get back to normal

**Comment by yaronkaikov** [comment]
> > > > > I'm not sure if ci was retriggered so doing it now.
> > > > > @scylladbbot trigger-ci
> > > > 
> > > > 
> > > > it's taking a long while sometimes for it to start.
> > > 
> > > 
> > > Over 5 hours? It looked like the jenkins job was not running
> > 
> > 
> > @yaronkaikov any idea what might happened? we might have lost the logs, since ci was retriggered. is it a known issue?
> 
> The queue is very long due to some changes we did with dtest, we already reverted this. So i am trying now to release the queue, it will slowing get back to normal

I trigger it again on cloud

**Comment by raphaelsc** [comment]
> > > > > > I'm not sure if ci was retriggered so doing it now.
> > > > > > @scylladbbot trigger-ci
> > > > > 
> > > > > 
> > > > > it's taking a long while sometimes for it to start.
> > > > 
> > > > 
> > > > Over 5 hours? It looked like the jenkins job was not running
> > > 
> > > 
> > > @yaronkaikov any idea what might happened? we might have lost the logs, since ci was retriggered. is it a known issue?
> > 
> > 
> > The queue is very long due to some changes we did with dtest, we already reverted this. So i am trying now to release the queue, it will slowing get back to normal
> 
> I trigger it again on cloud

@yaronkaikov what's up with the CI for this PR? I don't know how to follow it anymore

**Comment by raphaelsc** [comment]
@yaronkaikov what happened?

**Comment by raphaelsc** [comment]
> @yaronkaikov what happened?

apparently it's going well now

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider11.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider13.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider13.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	spider13.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider6.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider6.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	spider6.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider3.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider3.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2	✅	spider3.cloudius-systems.com
> dtest	[dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/9594/)	✅	
> [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/12914/)	✅	
> [dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/21150/)	❌	
> #### Failed Tests (2/100460):
> * [test_repair_disjoint_row_2nodes_diff_shard_count](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22537/testReport/junit/repair_additional_test/TestRepairAdditional/release___dtest_with_gossip_topology_changes___test_repair_disjoint_row_2nodes_diff_shard_count) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_disjoint_row_2nodes_diff_shard_count)
> * [test_repair_disjoint_row_2nodes_diff_shard_count](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22537/testReport/junit/repair_additional_test/TestRepairAdditional/release___dtest_with_gossip_topology_changes___test_repair_disjoint_row_2nodes_diff_shard_count_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_disjoint_row_2nodes_diff_shard_count)
> 
> #### Build Details:
> * Duration: 4 hr 18 min
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

looks like same problem we faced here, on restart

https://github.com/scylladb/scylla-enterprise/issues/4446

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000002733352 in repair_meta::repair_meta(repair_service&, replica::table&, seastar::lw_shared_ptr<schema const>, reader_permit, interval<dht::token>, row_level_diff_detect_algorithm, unsigned long, unsigned long, seastar::bool_class<repair_master_tag>, unsigned int, streaming::stream_reason, shard_config, utils::small_vector<utils::tagged_uuid<locator::host_id_tag>, 3ul>, unsigned long, std::vector<std::optional<unsigned int>, std::allocator<std::optional<unsigned int> > >, row_level_repair*, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, utils::tagged_uuid<service::session_id_tag>, std::optional<long>, locator::tablet_repair_incremental_mode) ()
[Current thread is 1 (LWP 21673)]
Missing file(s), try: dnf --enablerepo='*debug*' install /usr/lib/.build-id/ed/c47e35d6b1803f798660a863c1e8b54ccb83bf /usr/lib/debug/.build-id/ed/c47e35d6b1803f798660a863c1e8b54ccb83bf.debug
(gdb) bt
#0  0x0000000002733352 in repair_meta::repair_meta(repair_service&, replica::table&, seastar::lw_shared_ptr<schema const>, reader_permit, interval<dht::token>, row_level_diff_detect_algorithm, unsigned long, unsigned long, seastar::bool_class<repair_master_tag>, unsigned int, streaming::stream_reason, shard_config, utils::small_vector<utils::tagged_uuid<locator::host_id_tag>, 3ul>, unsigned long, std::vector<std::optional<unsigned int>, std::allocator<std::optional<unsigned int> > >, row_level_repair*, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, utils::tagged_uuid<service::session_id_tag>, std::optional<long>, locator::tablet_repair_incremental_mode) ()
#1  0x000000000825ddbb in repair_service::insert_repair_meta(utils::tagged_uuid<locator::host_id_tag>, unsigned int, unsigned int, interval<dht::token>, row_level_diff_detect_algorithm, unsigned long, unsigned long, shard_config, utils::tagged_uuid<table_schema_version_tag>, streaming::stream_reason, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, seastar::abort_source&, utils::tagged_uuid<service::session_id_tag>, std::optional<long>, locator::tablet_repair_incremental_mode) ()
#2  0x00000000083b9852 in repair_meta::repair_row_level_start_handler(repair_service&, utils::tagged_uuid<locator::host_id_tag>, unsigned int, unsigned int, seastar::basic_sstring<char, unsigned int, 15u, true>, seastar::basic_sstring<char, unsigned int, 15u, true>, interval<dht::token>, row_level_diff_detect_algorithm, unsigned long, unsigned long, shard_config, utils::tagged_uuid<table_schema_version_tag>, streaming::stream_reason, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, seastar::abort_source&, utils::tagged_uuid<service::session_id_tag>, std::optional<long>, locator::tablet_repair_incremental_mode) [clone .resume] ()
#3  0x0000000008313c1b in seastar::internal::coroutine_traits_base<repair_row_level_start_response>::promise_type::run_and_dispose() ()
#4  0x0000000001ef2d25 in seastar::reactor::task_queue_group::run_some_tasks() ()
#5  0x0000000002b75313 in seastar::reactor::do_run() ()
#6  0x0000000009ecf06d in std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) ()
#7  0x0000000009e8275b in seastar::posix_thread::start_routine(void*) ()
#8  0x00007fce62c7e464 in start_thread (arg=<optimized out>) at pthread_create.c:448
#9  0x00007fce62d015ac in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

one of them failed because the former left a core on some common dir.

**Comment by raphaelsc** [comment]
@scylladbbot trigger-ci

**Comment by tgrabiec** [comment]
> > #### 🔴 CI State: FAILURE
> > Mode	Stage	Status	Node
> > [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider11.cloudius-systems.com
> > dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider13.cloudius-systems.com
> > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider13.cloudius-systems.com
> > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> > 🔹 test/boost/compaction_group_test.cc
> > 🔹 test/boost/sstable_compaction_test.cc
> > 🔹 cluster/test_tablets2	✅	spider13.cloudius-systems.com
> > release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider6.cloudius-systems.com
> > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider6.cloudius-systems.com
> > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> > 🔹 test/boost/compaction_group_test.cc
> > 🔹 test/boost/sstable_compaction_test.cc
> > 🔹 cluster/test_tablets2	✅	spider6.cloudius-systems.com
> > debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider3.cloudius-systems.com
> > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider3.cloudius-systems.com
> > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> > 🔹 test/boost/compaction_group_test.cc
> > 🔹 test/boost/sstable_compaction_test.cc
> > 🔹 cluster/test_tablets2	✅	spider3.cloudius-systems.com
> > dtest	[dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/9594/)	✅
> > [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/12914/)	✅
> > [dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/21150/)	❌
> > #### Failed Tests (2/100460):
> > 
> > * [test_repair_disjoint_row_2nodes_diff_shard_count](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22537/testReport/junit/repair_additional_test/TestRepairAdditional/release___dtest_with_gossip_topology_changes___test_repair_disjoint_row_2nodes_diff_shard_count) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_disjoint_row_2nodes_diff_shard_count)
> > * [test_repair_disjoint_row_2nodes_diff_shard_count](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22537/testReport/junit/repair_additional_test/TestRepairAdditional/release___dtest_with_gossip_topology_changes___test_repair_disjoint_row_2nodes_diff_shard_count_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_disjoint_row_2nodes_diff_shard_count)
> > 
> > #### Build Details:
> > 
> > * Duration: 4 hr 18 min
> > 
> > **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`
> 
> looks like same problem we faced here, on restart
> 
> [scylladb/scylla-enterprise#4446](https://github.com/scylladb/scylla-enterprise/issues/4446)

Please open an issue.

**Comment by raphaelsc** [comment]
> > > #### 🔴 CI State: FAILURE
> > > Mode	Stage	Status	Node
> > > [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider11.cloudius-systems.com
> > > dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider13.cloudius-systems.com
> > > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider13.cloudius-systems.com
> > > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> > > 🔹 test/boost/compaction_group_test.cc
> > > 🔹 test/boost/sstable_compaction_test.cc
> > > 🔹 cluster/test_tablets2	✅	spider13.cloudius-systems.com
> > > release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider6.cloudius-systems.com
> > > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider6.cloudius-systems.com
> > > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> > > 🔹 test/boost/compaction_group_test.cc
> > > 🔹 test/boost/sstable_compaction_test.cc
> > > 🔹 cluster/test_tablets2	✅	spider6.cloudius-systems.com
> > > debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider3.cloudius-systems.com
> > > [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)	✅	spider3.cloudius-systems.com
> > > [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22537/)
> > > 🔹 test/boost/compaction_group_test.cc
> > > 🔹 test/boost/sstable_compaction_test.cc
> > > 🔹 cluster/test_tablets2	✅	spider3.cloudius-systems.com
> > > dtest	[dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/9594/)	✅
> > > [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/12914/)	✅
> > > [dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/21150/)	❌
> > > #### Failed Tests (2/100460):
> > > 
> > > * [test_repair_disjoint_row_2nodes_diff_shard_count](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22537/testReport/junit/repair_additional_test/TestRepairAdditional/release___dtest_with_gossip_topology_changes___test_repair_disjoint_row_2nodes_diff_shard_count) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_disjoint_row_2nodes_diff_shard_count)
> > > * [test_repair_disjoint_row_2nodes_diff_shard_count](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22537/testReport/junit/repair_additional_test/TestRepairAdditional/release___dtest_with_gossip_topology_changes___test_repair_disjoint_row_2nodes_diff_shard_count_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_disjoint_row_2nodes_diff_shard_count)
> > > 
> > > #### Build Details:
> > > 
> > > * Duration: 4 hr 18 min
> > > 
> > > **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`
> > 
> > 
> > looks like same problem we faced here, on restart
> > [scylladb/scylla-enterprise#4446](https://github.com/scylladb/scylla-enterprise/issues/4446)
> 
> Please open an issue.

sure, it can be a bug in memory allocator when small pool is exhausted. i will investigate it further tomorrow.

**Comment by raphaelsc** [comment]
v9:
- handle intra node streaming (needed add_new_* variant too for splitting unsealed sstable)
- added reproducer for intra node streaming problem
- added test for split during repair, under critical disk utilization
- added test  for the exception handling path in add_new_* variants

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22652/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22652/)	✅	spider15.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22652/)	❌	spider15.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22652/)	❌	spider8.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22652/)	❌	spider8.cloudius-systems.com
> #### Failed Tests (3/24645):
> * [test_split_and_incremental_repair_synchronization[True].dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22652/testReport/junit/cluster/test_tablets2/test_split_and_incremental_repair_synchronization_True__dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_split_and_incremental_repair_synchronization%5BTrue%5D.dev.1)
> * [test_split_and_incremental_repair_synchronization[True].dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22652/testReport/junit/cluster/test_tablets2/test_split_and_incremental_repair_synchronization_True__dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_split_and_incremental_repair_synchronization%5BTrue%5D.dev.2)
> * [test_split_and_incremental_repair_synchronization[True].dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22652/testReport/junit/cluster/test_tablets2/test_split_and_incremental_repair_synchronization_True__dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_split_and_incremental_repair_synchronization%5BTrue%5D.dev.3)
> 
> #### Build Details:
> * Duration: 1 hr 40 min
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

apparently test failed because of https://github.com/scylladb/scylladb/commit/e7ca52ee79f9180095ebca34af2bcd84b5028582, now requires repair to run in incremental mode explicitly

**Comment by raphaelsc** [comment]
v10:
- rebased
- made test_split_and_incremental_repair_synchronization run explicitly with incremental repair

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Node
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider9.cloudius-systems.com
> dev	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider15.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider15.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2
> 🔹 storage/test_out_of_space_prevention	✅	spider15.cloudius-systems.com
> release	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider16.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider16.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2
> 🔹 storage/test_out_of_space_prevention	✅	spider16.cloudius-systems.com
> debug	[Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider18.cloudius-systems.com
> [test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)	✅	spider18.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/22661/)
> 🔹 test/boost/compaction_group_test.cc
> 🔹 test/boost/sstable_compaction_test.cc
> 🔹 cluster/test_tablets2
> 🔹 storage/test_out_of_space_prevention	❌	spider18.cloudius-systems.com
> dtest	[dtest with gossip topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/21219/)	✅	
> [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/9663/)	✅	
> [dtest with consistent topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/12983/)	✅	
> #### Failed Tests (1/102097):
> * [test_table_drop_with_auto_snapshot.debug.7](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/22661/testReport/junit/cluster/test_tablets2/debug___Unit_Tests_Custom___debug___test_table_drop_with_auto_snapshot_debug_7) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_table_drop_with_auto_snapshot.debug.7)
> 
> #### Build Details:
> * Duration: 3 hr 26 min
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

https://github.com/scylladb/scylladb/issues/27501 :-(

**Comment by raphaelsc** [comment]
@scylladbbot trigger-ci

**Comment by raphaelsc** [comment]
@tgrabiec please re-review.

**Comment by raphaelsc** [comment]
@tgrabiec please review again.

**Comment by raphaelsc** [comment]
@tgrabiec ping.

**Review by tgrabiec — APPROVED** [review]

**Comment by tgrabiec** [comment]
One consequence of this will be that intra-node migration during split decision will move split to the foreground by blocking the migration. But we already do that for regular migration too.

This can be fixed once we have `split_ack`, then we can avoid splitting when decision is set, only when groups are already split.

**Comment by raphaelsc** [comment]
> One consequence of this will be that intra-node migration during split decision will move split to the foreground by blocking the migration. But we already do that for regular migration too.
> 
> This can be fixed once we have `split_ack`, then we can avoid splitting when decision is set, only when groups are already split.

Exactly, and this is the behavior today, since before this series, we already conditionally split the sstable being attached.

**Comment by raphaelsc** [comment]
@bhalevy @scylladb/scylla-maint can this urgent fix bypass the merge freeze? it fixes some longevity tests.

**Comment by bhalevy** [comment]
> @bhalevy @scylladb/scylla-maint can this urgent fix bypass the merge freeze? it fixes some longevity tests.

I'm not sure.  If it doesn't fix a ci issue, it might need to wait for unfreeze.

**Comment by avikivity** [comment]
@raphaelsc I understand exactly how you feel, but there's a good chance a 22-patch series itself introduces instability, let's get a few days of sanity before we stir in more highly flammable fuel into the soup.
