### PR TITLE
[branch-5.1] - minimal fix for crash caused by empty primary key range in LWT update

### LINKED ISSUE #13001: consistent segmentation fault with one batch query
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): `docker.io/scylladb/scylla:5.1.5`
Cluster size: 1

`dump.zst` uploaded to 1bb343bf-450a-4f24-8645-3541efde8294

The query which always triggers it is a logged batch query with two statements, something like "DELETE FROM mytable where "table/column"=:value ... IF EXISTS" and "INSERT INTO mytable ..."

### PR DESCRIPTION
**Pull request by cvybhu**
This is another attempt to fix #13001 on `branch-5.1`.

In #13001 we found a test case which causes a crash on `branch-5.1` because it didn't handle `UNSET_VALUE` properly:

```python3
def test_unset_insert_where(cql, table2):
    p = unique_key_int()
    stmt = cql.prepare(f'INSERT INTO {table2} (p, c) VALUES ({p}, ?)')
    with pytest.raises(InvalidRequest, match="unset"):
        cql.execute(stmt, [UNSET_VALUE])

def test_unset_insert_where_lwt(cql, table2):
    p = unique_key_int()
    stmt = cql.prepare(f'INSERT INTO {table2} (p, c) VALUES ({p}, ?) IF NOT EXISTS')
    with pytest.raises(InvalidRequest, match="unset"):
        cql.execute(stmt, [UNSET_VALUE])
```

This problem has been fixed on `master` by PR #12517. I tried to backport it to `branch-5.1` (#13029), but this didn't go well - it was a big change that touched a lot of components. It's hard to make sure that it won't cause some unexpected issues.

Then I made a simpler fix  for `branch-5.1`, which achieves the same effect as the original PR (#13057).
The problem is that this effect includes backwards incompatible changes - it bans UNSET_VALUE in some places that `branch-5.1` used to allow.

Breaking changes are bad, so I made this PR, which does an absolutely minimal change to fix the crash.
It adds a check the moment before the crash would happen.

To make sure that everything works correctly, and to detect any possible breaking changes, I wrote a bunch of tests that validate the current behavior.
I also ported some tests from the `master` branch, at least the ones that were in line with the behavior on `branch-5.1`.

### CODE REVIEW

File: cql3/statements/cas_request.cc [hunk 1]
```diff
@@ -119,6 +119,9 @@ std::optional<mutation> cas_request::apply(foreign_ptr<lw_shared_ptr<query::resu
 
 const update_parameters::prefetch_data::row* cas_request::find_old_row(const cas_row_update& op) const {
     static const clustering_key empty_ckey = clustering_key::make_empty();
+    if (_key.empty()) {
+        throw exceptions::invalid_request_exception("partition key ranges empty - probably caused by an unset value");
```
Comment (nyh) [inline cql3/statements/cas_request.cc:123]: I think this is acceptable for branch 5.1, but please remember to also add such a check in master (maybe as on_internal_error), because if _key is empty because of some unknown bug, this code will crash - also on master.

**Review by nyh — APPROVED** [review]
I think this is a good option for the backport. I tend to think it's the better option, but if you prefer the other option, I don't feel strongly about this one.

**Comment by cvybhu** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4862/

The CI failure is the same as in #13057. It failed 2 times, but then there was a different run for a non-master branch (`scylla-ci` instead of `Scylla-CI`) and this different CI build passed. @benipeled  can I trigger the CI for a non-master branch somehow?

**Comment by benipeled** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4862/
> 
> The CI failure is the same as in #13057. In there it failed 2 times, but then there was a different run for a non-master branch (`scylla-5.1/job/scylla-ci` instead of `releneg/job/Scylla-CI`) and this different CI build passed. @benipeled can I trigger the CI for a non-master branch somehow?

Triggered - https://jenkins.scylladb.com/job/scylla-5.1/job/scylla-ci/3

Until we make the switch officially (hopefully next week) you can trigger it manually - https://jenkins.scylladb.com/job/scylla-5.1/job/scylla-ci (this one is for 5.1, we have the same on 5.2 and master folders)

**Comment by nyh** [comment]
Merged to next-5.1.
If I remember correctly, despite the "Closes" on the merge commit, this issue won't automatically close when the fix is promoted to brach-5.1, so we'll need to do it manually.

@cvybhu what about backporting to 5.2 and/or 5.0? We could (?) backport the original fix to 5.2 and this new simplified fix to 5.0, but I don't know if you had some other plan.

**Comment by nyh** [comment]
> @cvybhu what about backporting to 5.2 and/or 5.0? We could (?) backport the original fix to 5.2 and this new simplified fix to 5.0, but I don't know if you had some other plan.

Correction: 5.2 is not vulnerable because it already had the UNSET-handling changes.
So 5.0 is the only one left to consider.

**Comment by cvybhu** [comment]
> Merged to next-5.1. If I remember correctly, despite the "Closes" on the merge commit, this issue won't automatically close when the fix is promoted to brach-5.1, so we'll need to do it manually.
> 
> @cvybhu what about backporting to 5.2 and/or 5.0? We could (?) backport the original fix to 5.2 and this new simplified fix to 5.0, but I don't know if you had some other plan.

I'll add a backport to 5.0
