### PR TITLE
generic_server: convert connection tracking to seastar::gate

### LINKED ISSUE #10305: Scylla hangs when it doesn't have permissions to TLS files
Scylla fails to start at late stage without any error message when it doesn't have permissions to read TLS cert and key needed for enabling encrypted native transport.

Relevant Scylla config:
```
client_encryption_options:
  enabled: true
  certificate: /etc/scylla/db.crt
  keyfile: /etc/scylla/db.key
  truststore: /etc/scylla/ca.crt
  require_client_auth: true
```
File permissions:
```
[root@ip-172-31-33-136 ec2-user]# ls -la /etc/scylla/
total 52
drwxr-xr-x  3 root root   119 03-30 19:58 .
drwxr-xr-x 86 root root  8192 03-30 19:18 ..
-rw-r--r--  1 root root  1915 03-30 19:57 ca.crt
drwxr-xr-x  2 root root   239 03-30 19:18 cassandra
-rw-r--r--  1 root root   366 03-06 12:54 cassandra-rackdc.properties
-rw-r--r--  1 root root  1915 03-30 19:57 db.crt
-rw-------  1 root root  3243 03-30 19:57 db.key
-rw-r--r--  1 root root 23566 03-30 19:58 scylla.yaml
```

Scylla journal:

```
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal systemd[1]: Starting Scylla Server...
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: Scylla version 4.6.0-0.20220306.2f2d22a86 with build-id d487cdea729e95d8caebe2e9e2ae8698f35f19ee starting ...
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-2,7-8 --smp 4 --memory=33710M"
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, io-properties-file: /etc/scylla.d/io_properties.yaml, cpuset, (positional) 1-2,7-8, smp, (positional) 4, memory: 33710M]
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: WARN  2022-03-30 20:10:48,822 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: WARN  2022-03-30 20:10:48,863 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: WARN  2022-03-30 20:10:48,886 [shard 3] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: WARN  2022-03-30 20:10:48,886 [shard 2] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,889 [shard 0] seastar - updated: blocked-reactor-notify-ms=1000000
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,889 [shard 1] seastar - updated: blocked-reactor-notify-ms=1000000
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,889 [shard 2] seastar - updated: blocked-reactor-notify-ms=1000000
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,889 [shard 3] seastar - updated: blocked-reactor-notify-ms=1000000
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,893 [shard 0] init - installing SIGHUP handler
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,916 [shard 0] init - Scylla version 4.6.0-0.20220306.2f2d22a86 with build-id d487cdea729e95d8caebe2e9e2ae8698f35f19ee starting ...
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,916 [shard 0] init - starting prometheus API server
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - starting tokens manager
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - starting migration manager notifier
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - starting lifecycle notifier
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - creating tracing
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - creating snitch
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - determining DNS name
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - starting API server
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,917 [shard 0] init - Scylla API server listening on 127.0.0.1:10000 ...
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] service_level_controller - update_from_distributed_data: starting configuration polling loop
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] init - starting gossiper
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] init - seeds={172.31.33.136}, listen_address=172.31.33.136, broadcast_address=172.31.33.136
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] init - starting Raft service
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] init - initializing storage service
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] storage_service - Started node_ops_abort_thread
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 1] storage_service - Started node_ops_abort_thread
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 3] storage_service - Started node_ops_abort_thread
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 2] storage_service - Started node_ops_abort_thread
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] init - starting per-shard database core
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,919 [shard 0] init - creating and verifying directories
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,938 [shard 0] init - starting database
mar 30 20:10:48 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:48,959 [shard 0] database - Populating Keyspace system_schema
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,045 [shard 0] seastar - updated: blocked-reactor-notify-ms=200
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,045 [shard 1] seastar - updated: blocked-reactor-notify-ms=200
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,045 [shard 3] seastar - updated: blocked-reactor-notify-ms=200
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,045 [shard 2] seastar - updated: blocked-reactor-notify-ms=200
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,045 [shard 0] init - starting storage proxy
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,051 [shard 0] init - starting migration manager
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,051 [shard 0] init - starting query processor
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,052 [shard 0] init - initializing batchlog manager
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,053 [shard 0] format_selector - Selected md sstables format
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,053 [shard 0] legacy_schema_migrator - Moving 0 keyspaces from legacy schema tables to the new schema keyspace (system_schema)
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,054 [shard 0] legacy_schema_migrator - Dropping legacy schema tables
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,067 [shard 0] legacy_schema_migrator - Completed migration of legacy schema tables
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,067 [shard 0] init - loading system sstables
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,072 [shard 0] init - loading non-system sstables
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Populating Keyspace system_traces
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_traces: Reading CF sessions_time_idx id=0ebf001c-c1d1-3693-9a63-c3d96ac53318 version=d80bfb8b-bb07-34c5-8e50-80395de23041
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_traces: Reading CF sessions id=c5e99f16-8677-3914-b17e-960613512345 version=4682ce3d-17fb-3979-8563-6203b096722c
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_traces: Reading CF node_slow_log_time_idx id=f9706768-aa1e-3d87-9e5c-51a3927c2870 version=5038e46f-d51e-3c86-a985-d5044b1e1e34
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_traces: Reading CF node_slow_log id=bfcc4e62-5b63-3aa1-a1c3-6f5e47f3325c version=24b2f10f-3309-3e6d-945d-7bd5b8b82944
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_traces: Reading CF events id=8826e8e9-e16a-3728-8753-3bc1fc713c25 version=2a3150ee-39a2-3de5-a4d1-137ec32c5471
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Populating Keyspace system_auth
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_auth: Reading CF roles id=5bc52802-de25-35ed-aeab-188eecebb090 version=7a6b9a7b-2b0d-3afd-90f0-d9a4609844f4
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_auth: Reading CF role_permissions id=3afbe79f-2194-31a7-add7-f5ab90d8ec9c version=909d45a0-6e3f-30cf-9cc9-dc9670eecb9f
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,106 [shard 0] database - Keyspace system_auth: Reading CF role_members id=0ecdaa87-f8fb-3e60-88d1-74fb36fe5c0d version=ba73c274-5709-3c37-b997-953fb97523ce
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Keyspace system_auth: Reading CF role_attributes id=6b8c7359-a843-33f2-a1d8-5dc6a187436f version=db323a72-29cb-3779-8a33-f8372c385233
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Populating Keyspace system_distributed_everywhere
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Keyspace system_distributed_everywhere: Reading CF cdc_generation_descriptions_v2 id=234d2227-dd63-3d37-ac5f-c013e2ea9e6e version=f04f0def-50da-31c9-96b1-ab22ba0cc08e
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Populating Keyspace system_distributed
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Keyspace system_distributed: Reading CF view_build_status id=5582b59f-8e4e-35e1-b913-3acada51eb04 version=e61ea49b-8dbc-3ff6-a69f-896f4d38b7bb
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Keyspace system_distributed: Reading CF service_levels id=b8c556bd-212d-37ad-9484-690c73a5994b version=8a951d7a-1758-346d-953f-b8cc9cbc0f96
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Keyspace system_distributed: Reading CF cdc_streams_descriptions_v2 id=0bf73fd7-65b2-36b0-85e5-658131d5df36 version=58a18c32-0c5a-34ba-992f-7723dd0265c0
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,107 [shard 0] database - Keyspace system_distributed: Reading CF cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=5777e043-a81a-3324-8803-b497c056849f
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,119 [shard 0] init - starting view update generator
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,119 [shard 0] init - setting up system keyspace
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,131 [shard 0] init - starting commit log
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,133 [shard 0] init - initializing migration manager RPC verbs
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,133 [shard 0] init - initializing storage proxy RPC verbs
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,133 [shard 0] init - starting streaming service
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,133 [shard 0] init - starting hinted handoff manager
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,135 [shard 0] init - starting messaging service
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,135 [shard 0] repair - Setting max_repair_memory=883530137, max_repair_memory_per_range=33554432, max_repair_ranges_in_parallel=6
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,135 [shard 0] init - starting CDC Generation Management service
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,135 [shard 0] init - starting CDC log service
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,135 [shard 0] init - starting storage service
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal systemd[1]: Started Scylla Server.
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,136 [shard 0] init - starting sstables loader
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,136 [shard 0] messaging_service - Starting Messaging Service on port 7000
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,136 [shard 0] storage_service - Loading persisted ring state
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,140 [shard 0] storage_service - initial_contact_nodes={172.31.33.136}, loaded_endpoints={}, loaded_peer_features=0
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,140 [shard 0] storage_service - Checking remote features with gossip, initial_contact_nodes={172.31.33.136}
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,140 [shard 0] gossip - Gossip shadow round started with nodes={}
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: WARN  2022-03-30 20:10:49,140 [shard 0] gossip - All nodes={} are down for get_endpoint_states verb. Skip ShadowRound.
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,140 [shard 0] gossip - Gossip shadow round finisehd with nodes_talked={}
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,140 [shard 0] gossip - Feature check passed. Local node 172.31.33.136 features = {CDC, CDC_GENERATIONS_V2, COMPUTED_COLUMNS, CORRECT_COUNTER_ORDER, CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX, CORRECT_NON_COMPOUND_RANGE_TOMBSTONES, CORRECT_STATIC_COMPACT_IN_MC, COUNTERS, DIGEST_FOR_NULL_VALUES, DIGEST_INSENSITIVE_TO_EXPIRY, DIGEST_MULTIPARTITION_READ, HINTED_HANDOFF_SEPARATE_CONNECTION, INDEXES, LARGE_PARTITIONS, LA_SSTABLE_FORMAT, LWT, MATERIALIZED_VIEWS, MC_SSTABLE_FORMAT, MD_SSTABLE_FORMAT, NONFROZEN_UDTS, PER_TABLE_CACHING, PER_TABLE_PARTITIONERS, RANGE_SCAN_DATA_VARIANT, RANGE_TOMBSTONES, ROLES, ROW_LEVEL_REPAIR, SCHEMA_TABLES_V3, STREAM_WITH_RPC_STREAM, TRUNCATION_TABLE, UDA, UNBOUNDED_RANGE_TOMBSTONES, VIEW_VIRTUAL_COLUMNS, WRITE_FAILURE_REPLY, XXHASH}, Remote common_features = {}
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,142 [shard 0] storage_service - Restarting a node in NORMAL status
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,171 [shard 0] schema_tables - Schema version changed to 617833bb-62e0-3f2d-8890-9c5be0500fa0
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,171 [shard 0] storage_service - Starting up server gossip
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,174 [shard 0] compaction - [Compact system.compaction_history 7ddd18b0-b065-11ec-8314-f508921f074f] Compacted 2 sstables to [/var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/md-20-big-Data.db:level=0]. 136kB to 88kB (~65% of original) in 25ms = 3MB/s. ~256 total partitions merged to 22.
mar 30 20:10:49 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:10:49,176 [shard 0] gossip - failure_detector_loop: Started main loop
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] gossip - No gossip backlog; proceeding
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature CDC is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature CDC_GENERATIONS_V2 is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature COMPUTED_COLUMNS is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature DIGEST_FOR_NULL_VALUES is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature DIGEST_INSENSITIVE_TO_EXPIRY is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature HINTED_HANDOFF_SEPARATE_CONNECTION is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature LWT is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature MD_SSTABLE_FORMAT is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature NONFROZEN_UDTS is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature PER_TABLE_CACHING is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature PER_TABLE_PARTITIONERS is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature RANGE_SCAN_DATA_VARIANT is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature UDA is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,177 [shard 0] features - Feature VIEW_VIRTUAL_COLUMNS is enabled
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,179 [shard 0] init - starting system distributed keyspace
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,182 [shard 0] schema_tables - Schema version changed to 0838d873-6c47-3e09-9ab5-f691077d828b
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,185 [shard 0] schema_tables - Schema version changed to 0838d873-6c47-3e09-9ab5-f691077d828b
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,188 [shard 0] schema_tables - Schema version changed to 0838d873-6c47-3e09-9ab5-f691077d828b
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,191 [shard 0] schema_tables - Schema version changed to 0838d873-6c47-3e09-9ab5-f691077d828b
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,193 [shard 0] schema_tables - Schema version changed to 0838d873-6c47-3e09-9ab5-f691077d828b
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,223 [shard 0] storage_service - NORMAL: node is now in normal status
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,223 [shard 0] cdc - Latest generation seen during startup: (2022/03/30 20:03:31, 0347f492-aaec-428e-805f-b70dfaaf2aab)
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,225 [shard 0] cdc - Starting to use generation (2022/03/30 20:03:31, 0347f492-aaec-428e-805f-b70dfaaf2aab)
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,225 [shard 0] cdc - Generation (2022/03/30 20:03:31, 0347f492-aaec-428e-805f-b70dfaaf2aab): streams description table already updated.
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,225 [shard 0] init - starting tracing
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,226 [shard 0] init - SSTable data integrity checker is disabled.
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,226 [shard 0] init - starting auth service
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,227 [shard 0] init - starting batchlog manager
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,227 [shard 0] init - starting load meter
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,227 [shard 0] init - starting cf cache hit rate calculator
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,227 [shard 0] init - starting view update backlog broker
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,227 [shard 0] init - Waiting for gossip to settle before accepting client requests...
mar 30 20:11:01 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:01,228 [shard 3] compaction - [Compact system.peers 850fbf70-b065-11ec-a572-f50a921f074f] Compacted 2 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/md-31-big-Data.db:level=0]. 11kB to 5kB (~50% of original) in 3ms = 1MB/s. ~256 total partitions merged to 1.
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,227 [shard 0] gossip - No gossip backlog; proceeding
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,227 [shard 0] init - allow replaying hints
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,228 [shard 0] init - Launching generate_mv_updates for non system tables
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,228 [shard 0] init - starting the view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,232 [shard 0] init - starting native transport
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down view builder API
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down view builder API was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] view - Stopping view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] view - Draining view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 1] view - Stopping view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 1] view - Draining view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 3] view - Stopping view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 2] view - Stopping view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 3] view - Draining view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 2] view - Draining view builder
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down view builder was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down hinted handoff API
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down hinted handoff API was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,233 [shard 0] init - Shutting down view update backlog broker
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down view update backlog broker was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down cf cache hit rate calculator
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down cf cache hit rate calculator was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down load meter
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down load meter was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down batchlog manager
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down batchlog manager was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down snapshots API
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down snapshots API was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down snapshots
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down snapshots was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down auth service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down auth service was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down tracing
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] tracing - Asked to shut down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] tracing - Tracing is down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 1] tracing - Asked to shut down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 3] tracing - Asked to shut down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 2] tracing - Asked to shut down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 2] tracing - Tracing is down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 3] tracing - Tracing is down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 1] tracing - Tracing is down
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down tracing was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down storage service notifications
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down storage service notifications was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down system distributed keyspace
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down system distributed keyspace was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down storage service notifications
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down storage service notifications was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down sstables loader API
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down sstables loader API was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down sstables loader
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down sstables loader was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down repair API
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down repair API was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down messaging service API
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down messaging service API was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down storage service messaging
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down storage service messaging was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down cdc log service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down cdc log service was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,234 [shard 0] init - Shutting down CDC Generation Management service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down CDC Generation Management service was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down repair service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down repair service was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down drain storage proxy
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] hints_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] hints_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down drain storage proxy was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down streaming service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down streaming service was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down storage proxy RPC verbs
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down storage proxy RPC verbs was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down sstables format selector
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down sstables format selector was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down migration manager
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] migration_manager - stopping migration service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] migration_manager - stopping migration service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] migration_manager - stopping migration service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] migration_manager - stopping migration service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down migration manager was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] init - Shutting down database
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] compaction_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 0] compaction_manager - Stopping 1 ongoing compactions due to shutdown
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] compaction_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] compaction_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] compaction_manager - Asked to stop
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] compaction_manager - Stopping 0 ongoing compactions due to shutdown
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] compaction_manager - Stopping 0 ongoing compactions due to shutdown
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 1] compaction_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 3] compaction_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] compaction_manager - Stopping 0 ongoing compactions due to shutdown
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,235 [shard 2] compaction_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,238 [shard 0] compaction - [Compact system.truncated 8c382d00-b065-11ec-8314-f508921f074f] Compacted 2 sstables to [/var/lib/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-68-big-Data.db:level=0]. 82kB to 76kB (~93% of original) in 5ms = 15MB/s. ~256 total partitions merged to 2.
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,238 [shard 0] compaction_manager - Stopped
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down database was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down service_memory_limiter
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down service_memory_limiter was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down sst_dir_semaphore
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down sst_dir_semaphore was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down storage_service
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,316 [shard 0] init - Shutting down storage_service was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,317 [shard 0] init - Shutting down Raft
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,317 [shard 0] init - Shutting down Raft was successful
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,317 [shard 0] init - Shutting down gossiper
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,317 [shard 0] gossip - My status = NORMAL
mar 30 20:11:13 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:13,317 [shard 0] gossip - Announcing shutdown
mar 30 20:11:15 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:15,317 [shard 0] gossip - Disable and wait for gossip loop started
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,177 [shard 0] gossip - Gossip is now stopped
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,177 [shard 0] init - Shutting down gossiper was successful
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,177 [shard 0] init - Shutting down messaging service
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,177 [shard 0] init - Shutting down messaging service was successful
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,177 [shard 0] init - Shutting down service level controller
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,178 [shard 0] service_level_controller - update_from_distributed_data: configuration polling loop aborted
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,178 [shard 0] init - Shutting down service level controller was successful
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,178 [shard 0] init - Shutting down API server
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,178 [shard 0] init - Shutting down API server was successful
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal scylla[25943]: INFO  2022-03-30 20:11:16,178 [shard 0] init - Shutting down tracing instance
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal systemd[1]: Unit scylla-server.service entered failed state.
mar 30 20:11:16 ip-172-31-33-136.eu-west-1.compute.internal systemd[1]: scylla-server.service failed.

```

After fixing permissions:
```
[root@ip-172-31-33-136 ec2-user]# chmod 644 /etc/scylla/db.key
[root@ip-172-31-33-136 ec2-user]# ls -la /etc/scylla/
total 52
drwxr-xr-x  3 root root   119 03-30 19:58 .
drwxr-xr-x 86 root root  8192 03-30 19:18 ..
-rw-r--r--  1 root root  1915 03-30 19:57 ca.crt
drwxr-xr-x  2 root root   239 03-30 19:18 cassandra
-rw-r--r--  1 root root   366 03-06 12:54 cassandra-rackdc.properties
-rw-r--r--  1 root root  1915 03-30 19:57 db.crt
-rw-r--r--  1 root root  3243 03-30 19:57 db.key
-rw-r--r--  1 root root 23566 03-30 19:58 scylla.yaml
```

Scylla starts fine.

*Installation details*
Scylla version (or git commit hash): 4.6.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Amazon Linux, Scylla installed from RHEL repo

*Hardware details (for performance issues)*    
Platform (physical/VM/cloud instance type/docker): VM

### PR DESCRIPTION
**Pull request by lersek**
~~~
generic_server: convert connection tracking to seastar::gate

If we call server::stop() right after "server" construction, it hangs:

With the server never listening (never accepting connections and never
serving connections), nothing ever calls server::maybe_stop().
Consequently,

    co_await _all_connections_stopped.get_future();

at the end of server::stop() deadlocks.

Such a server::stop() call does occur in controller::do_start_server()
[transport/controller.cc], when

- cserver->start() (sharded<cql_server>::start()) constructs a
  "server"-derived object,

- start_listening_on_tcp_sockets() throws an exception before reaching
  listen_on_all_shards() (for example because it fails to set up client
  encryption -- certificate file is inaccessible etc.),

- the "deferred_action"

      cserver->stop().get();

  is invoked during cleanup.

(The cserver->stop() call exposing the connection tracking problem dates
back to commit ae4d5a60ca61 ("transport::controller: Shut down distributed
object on startup exception", 2020-11-25), and it's been triggerable
through the above code path since commit 6b178f9a4a90
("transport/controller: split configuring sockets into separate
functions", 2024-02-05).)

Tracking live connections and connection acceptances seems like a good fit
for "seastar::gate", so rewrite the tracking with that. "seastar::gate"
can be closed (and the returned future can be waited for) without anyone
ever having entered the gate.

NOTE: this change makes it quite clear that neither server::stop() nor
server::shutdown() must be called multiple times. The permitted sequences
are:

- server::shutdown() + server::stop()

- or just server::stop().

Fixes #10305

Signed-off-by: Laszlo Ersek <laszlo.ersek@scylladb.com>
~~~

Fixes #10305.

I think we might want to backport this -- it fixes a hang-on-misconfiguration which affects `scylla-6.1.0-0.20240804.abbf0b24a60c.x86_64` minimally. Basically every release that contains commit ae4d5a60ca61 has a theoretical chance for the hang, and every release that contains commit 6b178f9a4a90 has a practical chance for the hang.

Focusing on the more practical symptom (i.e., releases containing commit 6b178f9a4a90), `git tag --contains 6b178f9a4a90` gives us (ignoring candidates and release candidates):
- scylla-6.0.0
- scylla-6.0.1
- scylla-6.0.2
- scylla-6.1.0

### CODE REVIEW

**Comment by lersek** [comment]
I've set the `area/cql` label because the practical way to trigger the hang is to misconfigure the `client_encryption_options` stanza in `scylla.yaml` (see #10305).

File: generic_server.cc [hunk 1]
```diff
@@ -175,12 +173,11 @@ server::listen(socket_address addr, std::shared_ptr<seastar::tls::credentials_bu
 
 future<> server::do_accepts(int which, bool keepalive, socket_address server_addr) {
     return repeat([this, which, keepalive, server_addr] {
-        ++_connections_being_accepted;
-        return _listeners[which].accept().then_wrapped([this, keepalive, server_addr] (future<accept_result> f_cs_sa) mutable {
-            --_connections_being_accepted;
-            if (_stopping) {
+        seastar::gate::holder holder(_gate);
+        return _listeners[which].accept().then_wrapped([this, keepalive, server_addr, holder = std::move(holder)] (future<accept_result> f_cs_sa) mutable {
+            holder.release();
```
Comment (elcallio) [inline generic_server.cc:178]: Not really needed is it? You grab the holder inside the repeat, so it will be released on iteration return anyway.

**Comment by elcallio** [comment]
One minor nit, otherwise looks good.

**Review by elcallio — APPROVED** [review]

File: generic_server.cc (hunk 1 above)
Comment (lersek) [reply generic_server.cc:178]: @elcallio I wanted to hold the gate as narrowly as possible; basically only for the duration of the `accept()`; just like the original code did. If I remove `holder.release()`, then the gate will only be released at the end of the lambda that is executed upon `accept()` completion (successful or exceptional).

... I do agree though that the rest of said lambda never blocks; the `(void)futurize_invoke(...).then_wrapped(...)` part only creates a chain of futures (which is not waited-for by anyone in particular, but will be processed asynchronously still). Thus dropping the explicit `holder.release()` should not make any difference because we won't switch to another task until the end of the scope anyway. I'll push v2.

**Comment by lersek** [comment]
v2: drop `holder.release()` [@elcallio]

File: generic_server.cc (hunk 1 above)
Comment (lersek) [reply generic_server.cc]: Done in v2.

File: generic_server.cc [hunk 2]
```diff
@@ -21,23 +21,21 @@ connection::connection(server& server, connected_socket&& fd)
     , _fd{std::move(fd)}
     , _read_buf(_fd.input())
```
Comment (avikivity) [inline generic_server.cc:22]: > Closes <https://github.com/scylladb/scylladb/issues/10305>.

Please don't invent new syntax, our bots aren't intelligent enough to follow it.

**Comment by lersek** [comment]
I've not found mention of `6b178f9a4a90` in any `cherry picked from` line, in the logs of the currently existing tags, so `6b178f9a4a90` has presumably never been ported to (as opposed to "inherited by") any side branch, and therefore this patch should only be backported (at most) to 6.0 and 6.1.

**Comment by lersek** [comment]
v3: fix `Closes` syntax in commit message [@avikivity]

File: generic_server.cc (hunk 2 above)
Comment (lersek) [reply generic_server.cc:22]: apologies; fixed in v3.

**Comment by lersek** [comment]
The dtest failures (`test_safe_unsafe_rebuild`) are unexpected; I believe they are caused by #20242.

**Comment by bhalevy** [comment]
> The dtest failures (`test_safe_unsafe_rebuild`) are unexpected; I believe they are caused by #20242.

And https://github.com/scylladb/scylla-dtest/issues/4823
(which fix handles #20242 gracefully, until fixed)

File: generic_server.cc (hunk 2 above)
Comment (bhalevy) [reply generic_server.cc:22]: @lersek, sorry for the nitpicking but we use `Fixes #10305` rather than `Closes ...` when it is a bug fix.
`Closes` is used when a patch closes a PR, or when we want to close an issue without fixing it (akin to closing as "Not Planned").

File: generic_server.cc [hunk 3]
```diff
@@ -115,15 +113,15 @@ server::~server()
...
         co_await shutdown();
     }
 
-    co_await _all_connections_stopped.get_future();
+    co_await std::move(_all_connections_stopped);
 }
 
 future<> server::shutdown() {
-    _stopping = true;
+    _all_connections_stopped = _gate.close();
```
Comment (bhalevy) [inline generic_server.cc:124]: I think we better mark this function as `noexcept` now, otherwise close may hang forever
if we don't get to call `c.shutdown()` for all open connection.

File: generic_server.cc [hunk 4]
```diff
@@ -115,15 +113,15 @@ server::~server()
 }
 
 future<> server::stop() {
-    if (!_stopping) {
+    if (!_gate.is_closed()) {
```
Comment (bhalevy) [inline generic_server.cc:116]: I'd move it to inside `shutdown()` in case it is called from other paths,
but can be done as a followup as this hunk follow the existing logic with that respect.

File: generic_server.cc (hunk 2 above)
Comment (lersek) [reply generic_server.cc:22]: will update iv 

> we use `Fixes #10305` rather than `Closes ...` when it is a bug fix.
> `Closes` is used when a patch closes a PR, or when we want to close an issue without fixing it

will update in v4

File: generic_server.cc (hunk 3 above)
Comment (lersek) [reply generic_server.cc:124]: Can you please elaborate? I don't understand.

`seastar::gate::close()` is `noexcept`, so if `server::shutdown()` throws, then it must be after `seastar::gate::close()` returns.

If `server::shutdown()` throws, then we don't know what's going to happen in callers in general (`server::shutdown()` is `public`). `server::stop()` is an internal caller of `server::shutdown()`; if the latter throws, then `server::stop()` will not get as far as waiting for the future returned by `_gate.close()` -- through `_all_connections_stopped`; instead the exception will escape from `server::stop()`.

I don't understand "close may hang forever".

File: generic_server.cc (hunk 4 above)
Comment (lersek) [reply generic_server.cc:116]: > I'd move it to inside `shutdown()` in case it is called from other paths, but can be done as a followup as this hunk follows the existing logic with that respect.

Apologies, I don't understand -- what exactly should I move into `shutdown()`? Thanks.

Comment (bhalevy) [reply generic_server.cc:116]: The condition.
I think it'd be better to check `if (!_gate.is_closed())` in `shutdown()` rather than here to allow calling it from other places as well.

File: generic_server.cc (hunk 3 above)
Comment (bhalevy) [reply generic_server.cc:124]: `_gate.close()` returns a future that will be resolved once all connections are destroyed.
If we don't get to `c.shutdown()` because an exception is thrown this `future<>` will never resolve.
Currently nothing  is likely to throw, but e.g. abort_accept is not marked as `noexcept` either so theoretically, it might throw an exception.
`make_lw_shared<size_t>(0);` can theoretically throw bad_alloc as well (in that case we're in deep trouble and seastar tasks would probably fail to allocate as well, but it just goes to show other stuff could happen as well.
BTW, this allocation seems extraneous, and coroutinizing this function could save it.

Comment (lersek) [reply generic_server.cc:124]: Understood, thanks; I'll look into those for v4.

**Comment by avikivity** [comment]
Please add a test. As it's likely timing dependent, you may need to inject a wait using our failure injection.

**Comment by lersek** [comment]
> Please add a test. As it's likely timing dependent, you may need to inject a wait using our failure injection.

The hang itself is 100% deterministic, but how do we determine from a test, "by this time initialization should have completed"?

File: generic_server.cc (hunk 3 above)
Comment (lersek) [reply generic_server.cc:124]: @bhalevy

> BTW, this allocation seems extraneous, and coroutinizing this function could save it.

I'm finding it difficult to coroutinize `shutdown()`, for two reasons:
- Within the `parallel_for_each`, there are two (nested) lambdas that each capture (by reference). [Capturing lambdas should not be coroutines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rcoro-capture), so I can't seem to turn these lambdas themselves into coroutines, only the "outer code".
- The chain of futures returned by `shutdown()` is terminated with `_listeners_stopped` (moved); the caller of `shutdown()`, i.e. `stop()`, will wait for that to resolve. As far as I can tell, if I were to turn `shutdown()` into a coroutine, then I'd have to finish up the function with `co_await std::move(_listeners_stopped)`. That seems to be moving the wait for `_listeners_stopped` from the callers of `shutdown()` -- for example, from `server::stop()` -- into `shutdown()`. Is that OK?

Comment (lersek) [reply generic_server.cc:124]: Hm, regarding the second question anyway -- that seems quite the "standard" with coroutinization.

**Comment by avikivity** [comment]
> > Please add a test. As it's likely timing dependent, you may need to inject a wait using our failure injection.
> 
> The hang itself is 100% deterministic, but how do we determine from a test, "by this time initialization should have completed"?

Splurge on a huge timeout. Since this test is expected to not fail, it doesn't matter if the timeout is unrealistic, since usually you won't hang. Huge timeout = 300 sec.

File: generic_server.cc (hunk 3 above)
Comment (lersek) [reply generic_server.cc:124]: Right, I think I managed to do the coroutinization (minus the lambda as explained above).

File: generic_server.cc (hunk 2 above)
Comment (lersek) [reply generic_server.cc:22]: done in v4

File: generic_server.cc (hunk 3 above)
Comment (lersek) [reply generic_server.cc:124]: done in v4

File: generic_server.cc (hunk 4 above)
Comment (lersek) [reply generic_server.cc]: done in v4

**Comment by lersek** [comment]
> > > Please add a test. As it's likely timing dependent, you may need to inject a wait using our failure injection.
> > The hang itself is 100% deterministic, but how do we determine from a test, "by this time initialization should have completed"?
> Splurge on a huge timeout. Since this test is expected to not fail, it doesn't matter if the timeout is unrealistic, since usually you won't hang. Huge timeout = 300 sec.

done in v4

**Comment by lersek** [comment]
v5:

While I was looking at the Seastar tutorial for an independent reason, I realized that [`seastar::coroutine::lambda`](https://github.com/scylladb/seastar/blob/master/doc/tutorial.md#lambda-coroutines) would let me coroutinize the lambda passed to `parallel_for_each` as well, inside `server::shutdown()`. So v5 updates patch#6 to do that. (I've updated the commit message too, and retested the patch.)

File: generic_server.cc [hunk 5]
```diff
@@ -129,16 +129,15 @@ future<> server::shutdown() noexcept {
...
     auto nr_conn_total = _connections_list.size();
     _logger.debug("shutdown connection nr_total={}", nr_conn_total);
-    return parallel_for_each(_connections_list.begin(), _connections_list.end(), [this, nr_conn, nr_conn_total] (auto&& c) {
-        return c.shutdown().then([this, nr_conn, nr_conn_total] {
-            _logger.debug("shutdown connection {} out of {} done", ++(*nr_conn), nr_conn_total);
-        });
-    }).then([this] {
-        return std::move(_listeners_stopped);
-    });
+    co_await parallel_for_each(_connections_list.begin(), _connections_list.end(),
```
Comment (avikivity) [inline generic_server.cc:135]: We have a seastar::coroutine::parallel_for_each() which is slightly faster (allocates state within the outer coroutine rather than in a separate block), and is immune to the lambda coroutine fiasco. May as well use it.

File: test/boost/server_stop_without_listening_test.cc [hunk 6]
```diff
@@ -0,0 +1,37 @@
+/*
+ * Copyright (C) 2024-present ScyllaDB
+ */
+
+/*
```
Comment (avikivity) [inline test/boost/server_stop_without_listening_test.cc:5]: Please name the file generic_server_test.cc, so if we ever have related tests, they'll have a home.

File: test/boost/server_stop_without_listening_test.cc [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+    test_server() : server("test_server", test_logger) {};
+protected:
+    [[noreturn]] shared_ptr<connection> make_connection(socket_address, connected_socket&&, socket_address) {
+        SCYLLA_ASSERT(false);
+    }
+};
+
+SEASTAR_TEST_CASE(server_stop_without_listening) {
+    test_server srv;
+    co_await with_timeout(lowres_clock::now() + 5min, srv.stop());
```
Comment (avikivity) [inline test/boost/server_stop_without_listening_test.cc:36]: If the test fails, shouldn't it be added after the fix? For the holy bisect.

File: generic_server.cc [hunk 8]
```diff
@@ -113,14 +113,14 @@ server::~server()
...
-    }
-
+    co_await shutdown();
     co_await std::move(_all_connections_stopped);
 }
 
 future<> server::shutdown() {
+    if (_gate.is_closed()) {
+        return make_ready_future<>();
+    }
```
Comment (avikivity) [inline generic_server.cc:123]: This isn't accurate. A first shutdown() call will start tearing things down, wait for wheels to turn, and return when done. A second shutdown that is initiated before the first completes will return immediately, misinforming its caller.

This can trigger if the user requests a shutdown (I think it's possible via `nodetool disablebinary`) and immediately afterwards the server is shut down. server::stop() will flash through server::shutdown() and then the shutdown process will hit use-after-free on its connections.

This is a preexisting problem, so can be fixed later. It's also a difficult to hit race.

Comment (bhalevy) [reply generic_server.cc:123]: the second shutdown() indeed has nothing to do. and then stop() would wait on the _gate.close() future set to  the second shutdown() indeed has nothing to _all_connections_stopped by the first shutdown() call.

File: generic_server.cc [hunk 9]
```diff
@@ -115,32 +113,31 @@ server::~server()
 }
 
 future<> server::stop() {
-    if (!_stopping) {
-        co_await shutdown();
-    }
-
-    co_await _all_connections_stopped.get_future();
+    co_await shutdown();
+    co_await std::move(_all_connections_stopped);
```
Comment (bhalevy) [inline generic_server.cc:117]: better `co_await std::exchange(_all_connections_stopped, make_ready_future<>())`

File: generic_server.cc (hunk 5 above)
Comment (lersek) [reply generic_server.cc:135]: @avikivity

> We have a seastar::coroutine::parallel_for_each() which is slightly faster (allocates state within the outer coroutine rather than in a separate block), and is immune to the lambda coroutine fiasco. May as well use it.

I find the namespace usage slightly confusing. Per `CONTRIBUTING.md`, *Scylla code is written with `using namespace seastar`*, and so we have to watch for the difference between plain `parallel_for_each()` (from `seastar/core/loop.hh`) versus `coroutine::parallel_for_each()` (from `seastar/coroutine/parallel_for_each.hh`).

But yes, it does seem to work.

@bhalevy

> I think it should also be able to work directly on `_connections_list` rather than on `.begin(), .end()`

That's right; there's an overload at the end of `seastar/coroutine/parallel_for_each.hh` that takes a `Range&&`.

Thank you both for the suggestions; I've implemented these in v6.

File: generic_server.cc [hunk 10]
```diff
@@ -129,16 +129,15 @@ future<> server::shutdown() noexcept {
...
     _logger.debug("shutdown connection nr_total={}", nr_conn_total);
-    return parallel_for_each(_connections_list.begin(), _connections_list.end(), [this, nr_conn, nr_conn_total] (auto&& c) {
-        return c.shutdown().then([this, nr_conn, nr_conn_total] {
-            _logger.debug("shutdown connection {} out of {} done", ++(*nr_conn), nr_conn_total);
-        });
-    }).then([this] {
-        return std::move(_listeners_stopped);
-    });
+    co_await parallel_for_each(_connections_list.begin(), _connections_list.end(),
+            seastar::coroutine::lambda([this, &nr_conn, nr_conn_total] (auto&& c) -> future<> {
```
[the remark this answers is not in the document]
Comment (lersek) [reply generic_server.cc:136]: done in v6

File: test/boost/server_stop_without_listening_test.cc (hunk 7 above)
Comment (lersek) [reply test/boost/server_stop_without_listening_test.cc:36]: No, this order was intentional. For bisection, the tree must build at every stage, but it need not pass the test suite at every stage, IMO. I agree that actual bugs should not be introduced even temporarily (mid-series); however, this test case only exposes an existent bug, it does not introduce it.

The idea was that, in general, for a hypothesis to be any good, it has to be falsifiable; specifically, for this test to be worth adding, there should be a state of the tree where the test exists *and* fails -- so that the later bugfix can demonstrate through the test case that the fix makes a difference.

If you disagree, I can of course move the sorting order cleanup and the test case right after the fix (= conversion to `seastar::gate`).

File: test/boost/server_stop_without_listening_test.cc (hunk 6 above)
Comment (lersek) [reply test/boost/server_stop_without_listening_test.cc:5]: I was about 101% sure that I would never get the name right at first try, so it was a "consciously tentative" name ;)

Rename done in v6.

File: test/boost/server_stop_without_listening_test.cc (hunk 7 above)
Comment (avikivity) [reply test/boost/server_stop_without_listening_test.cc:36]: The test should indeed fail-before and pass-after, but sometimes I do bisect with the full ./test.py.

File: generic_server.cc (hunk 8 above)
Comment (avikivity) [reply generic_server.cc:123]: We have shared_future for this.

File: test/boost/server_stop_without_listening_test.cc (hunk 7 above)
Comment (lersek) [reply test/boost/server_stop_without_listening_test.cc:36]: So... should I move the test after the bugfix, or keep it at the front? :)

File: generic_server.cc (hunk 8 above)
Comment (lersek) [reply generic_server.cc:123]: Awesome, I was just about to ask about "something something shared"!

Can we fork this off to a new ticket though? (One reason is at least that it takes a separate/different reproducer.)

File: generic_server.cc (hunk 9 above)
Comment (lersek) [reply generic_server.cc:117]: IIUC, this is to make `server:stop()` idempotent as well. Will do it in v6, but I think it deserves its own patch.

File: test/boost/server_stop_without_listening_test.cc (hunk 7 above)
Comment (avikivity) [reply test/boost/server_stop_without_listening_test.cc:36]: After please

Comment (lersek) [reply test/boost/server_stop_without_listening_test.cc:36]: done in v6

File: generic_server.cc (hunk 8 above)
Comment (lersek) [reply generic_server.cc:123]: `-->` https://github.com/scylladb/scylladb/issues/20309

**Comment by lersek** [comment]
v6:
1. `generic_server: convert connection tracking to seastar::gate`
   - move patch to front [@avikivity]
2. `configure, cmake: sort the lists of boost unit tests`
   - move patch after `generic_server: convert connection tracking to seastar::gate` [@avikivity]
3. `test/server_stop_without_listening: add test case`
   - rename test from `server_stop_without_listening_test` to `generic_server_test` [@avikivity]
   - (noticed that in v4, I had broken the sort order in `test/boost/CMakeLists.txt` anyway...)
   - rename test case from `server_stop_without_listening` to `stop_without_listening`
   - update commit message with new test case name plus log of re-run (failed) test
   - move patch after `generic_server: convert connection tracking to seastar::gate` [@avikivity]
4. `generic_server: make server::shutdown() idempotent`
   - caution in the commit message that server::shutdown() is still not reentrant; should be solved separately [@avikivity]
5. `generic_server: mark server::shutdown() noexcept`
   - no change
6. `generic_server: coroutinize server::shutdown()`
   - coroutinize the lambda with `coroutine::parallel_for_each()` rather than with `parallel_for_each()` + `coroutine::lambda()` [@avikivity]
   - call the `coroutine::parallel_for_each()` overload that takes a `Range&&` [@bhalevy]
   - capture all variables by reference in the (coroutine) lambda passed to `coroutine::parallel_for_each()` [@avikivity]
7. `generic_server: make server::stop() idempotent`
   - new patch in v6 [@bhalevy]

File: generic_server.cc [hunk 11]
```diff
@@ -119,7 +119,7 @@ future<> server::stop() {
 
 future<> server::shutdown() noexcept {
     if (_gate.is_closed()) {
-        return make_ready_future<>();
+        co_return;
```
[the remark this answers is not in the document]
Comment (lersek) [reply generic_server.cc:122]: Great catch thank you! There are a lot of pitfalls to coroutines (and something something about unexpected interactions between theoretically independent C++ features ;) ). Will fix this in v7. Thanks!

[the remark this answers is not in the document]
Comment (avikivity) [reply generic_server.cc:122]: I don't understand why anything is needed. The coroutine has an implicit try/catch around its body. Exceptions caught are sent to seastar::coroutine_traits_base::unhandled_exception(), which forwards it to the underlying promise, so it ends up in the returned future.

[the remark this answers is not in the document]
Comment (lersek) [reply generic_server.cc:122]: IIRC, Benny's point was that an exception would prevent `c.shutdown()` from being initiated for all the connections, and then the gate would never be vacated, and `_all_connections_stopped` would never resolve. ... https://github.com/scylladb/scylladb/pull/20212#discussion_r1726742964

[the remark this answers is not in the document]
Comment (avikivity) [reply generic_server.cc:122]: I don't see how this is related to making server::shutdown() noexcept. After converting it to a coroutine, we're sure it won't throw, because coroutines package unhandled exceptions into the return future. It won't throw whether or not it's marked noexcept.

abort_accept() throwing would indeed be broken, but it doesn't (shouldn't) throw. In any case coroutinization didn't make it better or worse in that aspect.

[the remark this answers is not in the document]
Comment (lersek) [reply generic_server.cc:122]: - assume the consumer of the `server` object calls `stop`, or `shutdown` (and in the former case, `stop` calls `shutdown`)
- `shutdown` closes the gate, `abort_accept` throws, shutdown for the connections is not initated (not reached)
- the exception is propagated to the consumer of the `server` object, which is waiting on either `stop` or `shutdown` to resolve (see first step)
- `future::get()` or `co_await` in the consumer throws; assume the consumer catches it
- what is the consumer now supposed to do? If if calls `shutdown` again, that won't do anything (the gate is closed). if the consumer calls `stop`, then the `co_await` on `_all_connections_stopped` may block indefinitely (the connections don't know they should be leaving the gate).

I believe Benny's point with making `shutdown` noexcept was to prevent this (effective) hang. If `shutdown` were to throw between `_gate.close()` and starting to shut down the connections, we'd abort the scylla process -- no hang. @bhalevy please explain better if I'm mistaken. Thanks.

I'm fine either way, BTW; I can just drop the noexcept patch, or rework it, as long as we reach consensus. Thanks.

> abort_accept() throwing would indeed be broken, but it doesn't (shouldn't) throw

Should I try marking abort_accept() noexcept then?

> In any case coroutinization didn't make it better or worse in that aspect.

I agree; it's just that coroutinization affects (somewhat) how we can express that no exception should prevent `shutdown` from reaching the `parallel_for_each`.

**Comment by lersek** [comment]
v7: drop patch `generic_server: mark server::shutdown() noexcept`

File: generic_server.cc (hunk 11 above)
[the remark this answers is not in the document]
Comment (lersek) [reply generic_server.cc:122]: done in v7

**Review by bhalevy — APPROVED** [review]

**Comment by kbr-scylla** [comment]
I think you accidentally fixed https://github.com/scylladb/scylladb/issues/17862 too, thanks.

**Comment by lersek** [comment]
@kbr-scylla 

> I think you accidentally fixed #17862 too, thanks.

That makes me feel great; thank you for letting me know!
