### PR TITLE
Materialize_views:  don't construct `global_schema_ptr` from views schemas that lacks base information

### LINKED ISSUE #14011: test_interrupt_build_process dtest failed with schema_registry - Tried to build a global schema for view ks.t_by_v2 with an uninitialized base info
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/256/artifact/logs-full.release.016/1684893864334_materialized_views_test.py%3A%3ATestInterruptBuildProcess%3A%3Atest_interrupt_build_process_with_resharding_max_to_half_test/node2.log
```
Scylla version 5.4.0~dev-0.20230524.88fd7f711108 with build-id 5d5b24db70618b9af2ce3ae97752a85522312cbb starting ...
...
INFO  2023-05-24 01:53:46,804 [shard  0] init - Scylla version 5.4.0~dev-0.20230524.88fd7f711108 initialization completed.
INFO  2023-05-24 01:57:45,154 [shard  0] view - Building view ks.t_by_v, starting at token minimum token
INFO  2023-05-24 01:57:45,222 [shard  0] migration_manager - Requesting schema pull from 127.0.75.3:13
INFO  2023-05-24 01:57:45,222 [shard  0] migration_manager - Pulling schema from 127.0.75.3:13
INFO  2023-05-24 01:57:45,223 [shard  0] migration_manager - Requesting schema pull from 127.0.75.3:20
INFO  2023-05-24 01:57:45,227 [shard  0] migration_manager - Requesting schema pull from 127.0.75.3:1
INFO  2023-05-24 01:57:45,227 [shard  0] migration_manager - Requesting schema pull from 127.0.75.3:15
INFO  2023-05-24 01:57:45,229 [shard  0] migration_manager - Requesting schema pull from 127.0.75.3:3
INFO  2023-05-24 01:57:45,232 [shard  0] migration_manager - Requesting schema pull from 127.0.75.3:31
INFO  2023-05-24 01:57:45,235 [shard  0] migration_manager - Requesting schema pull from 127.0.75.1:5
INFO  2023-05-24 01:57:45,235 [shard  0] migration_manager - Pulling schema from 127.0.75.1:0
INFO  2023-05-24 01:57:45,235 [shard  0] migration_manager - Requesting schema pull from 127.0.75.1:7
INFO  2023-05-24 01:57:45,236 [shard  0] migration_manager - Requesting schema pull from 127.0.75.1:18
INFO  2023-05-24 01:57:45,238 [shard  0] schema_tables - Altering ks.t id=fff88220-f9d5-11ed-81ba-e13a14d6d4e6 version=1511e4dd-27f6-35f2-a7c9-bca005c30d17
INFO  2023-05-24 01:57:45,239 [shard  0] schema_tables - Creating ks.t_by_v2 id=603cfa80-f9d6-11ed-81ba-e13a14d6d4e6 version=ebf7abfb-7778-3d27-9f58-c47c2d5af4c6
WARN  2023-05-24 01:57:45,244 [shard 12] storage_proxy - Failed to apply mutation from 127.0.75.3#12: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
WARN  2023-05-24 01:57:45,244 [shard 11] storage_proxy - Failed to apply mutation from 127.0.75.3#11: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
WARN  2023-05-24 01:57:45,244 [shard  1] storage_proxy - Failed to apply mutation from 127.0.75.3#1: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
WARN  2023-05-24 01:57:45,244 [shard 26] storage_proxy - Failed to apply mutation from 127.0.75.3#26: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
INFO  2023-05-24 01:57:45,245 [shard  3] query_processor - Column definitions for ks.t changed, invalidating related prepared statements
WARN  2023-05-24 01:57:45,245 [shard  2] storage_proxy - Failed to apply mutation from 127.0.75.3#2: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
WARN  2023-05-24 01:57:45,247 [shard  7] storage_proxy - Failed to apply mutation from 127.0.75.1#7: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
WARN  2023-05-24 01:57:45,247 [shard 10] storage_proxy - Failed to apply mutation from 127.0.75.1#10: data_dictionary::no_such_column_family (Can't find a column family with UUID 603cfa80-f9d6-11ed-81ba-e13a14d6d4e6)
ERROR 2023-05-24 01:57:45,248 [shard 24] schema_registry - Tried to build a global schema for view ks.t_by_v2 with an uninitialized base info, at: 0x59eb98e 0x59ebf40 0x59ec228 0x5622487 0x1e17696 0x2e94915 0x2f6f263 0x2f6d509 0x2f5be89 0x2f71e71 0x15fd1d2 0x15fbd6a 0x15fb429 0x15f9473 0x15f8811 0x59d24f5 0x59d20b3 0x59d2b59 0x5652b94 0x5653e17 0x56764b1 0x562321a /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x8b12c /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x10cbbf
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::rpc::server::connection::process()::$_22::operator()()::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda(std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> >)#1}, seastar::future<std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> > >::then_impl_nrvo<seastar::rpc::server::connection::process()::$_22::operator()()::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda(std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> >)#1}, seastar::future<void> >(seastar::rpc::server::connection::process()::$_22::operator()()::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda(std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> >)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::rpc::server::connection::process()::$_22::operator()()::{lambda()#1}::operator()() const::{lambda()#2}::operator()()::{lambda(std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> >)#1}&, seastar::future_state<std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> > >&&)#1}, std::tuple<std::optional<unsigned long>, unsigned long, long, std::optional<seastar::rpc::rcv_buf> > >
   --------
   seastar::internal::do_until_state<seastar::rpc::server::connection::process()::$_22::operator()()::{lambda()#1}::operator()() const::{lambda()#1}, seastar::rpc::server::connection::process()::$_22::operator()()::{lambda()#1}::operator()() const::{lambda()#2}>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::rpc::server::connection::process()::$_23, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::rpc::server::connection::process()::$_23>(seastar::rpc::server::connection::process()::$_23&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::rpc::server::connection::process()::$_23&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::rpc::server::connection::process()::$_24, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::rpc::server::connection::process()::$_24, false> >(seastar::future<void>::finally_body<seastar::rpc::server::connection::process()::$_24, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::rpc::server::connection::process()::$_24, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 24.
Backtrace:
  0x5641a78
  0x5676002
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x3cb1f
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x8ce5b
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x3ca75
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x267fb
  0x5622523
  0x1e17696
  0x2e94915
  0x2f6f263
  0x2f6d509
  0x2f5be89
  0x2f71e71
  0x15fd1d2
  0x15fbd6a
  0x15fb429
  0x15f9473
  0x15f8811
  0x59d24f5
  0x59d20b3
  0x59d2b59
  0x5652b94
  0x5653e17
  0x56764b1
  0x562321a
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x8b12c
  /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/88fd7f71110878a8bcd317aa9f5183df722def76/libreloc/libc.so.6+0x10cbbf
```

Decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:60
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/release/seastar/./seastar/src/util/backtrace.cc:170
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:38
 (inlined by) seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./seastar/src/core/on_internal_error.cc:42
global_schema_ptr at ./schema/schema_registry.cc:331
service::storage_proxy::mutate_locally(seastar::lw_shared_ptr<schema const> const&, frozen_mutation const&, tracing::trace_state_ptr, seastar::bool_class<db::force_sync_tag>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, seastar::smp_service_group, std::variant<std::monostate, db::per_partition_rate_limit::account_only, db::per_partition_rate_limit::account_and_enforce>) at ./service/storage_proxy.cc:2790
operator() at ./service/storage_proxy.cc:511
 (inlined by) operator() at ./service/storage_proxy.cc:443
...
```

After restart view building eventually succeeded:
```
INFO  2023-05-24 02:03:39,779 [shard  0] init - Scylla version 5.4.0~dev-0.20230524.88fd7f711108 initialization completed.
INFO  2023-05-24 02:03:39,779 [shard  0] view - Building view ks.t_by_v2, starting at token minimum token
INFO  2023-05-24 02:03:39,780 [shard  0] view - Building view ks.t_by_v, starting at token minimum token
ERROR 2023-05-24 02:03:39,781 [shard  6] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9221727486224115472, view token: -8987928484838087894): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,781 [shard  1] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9222967543607267894, view token: -1947216961110107968): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,781 [shard  0] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9223297786983086897, view token: 7882880537297481526): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,781 [shard 11] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9220419336659099601, view token: 8895350330199977635): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,781 [shard 15] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9219346447766400967, view token: 2990881561334808888): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,782 [shard  6] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,782 [shard  1] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,782 [shard 11] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,782 [shard 15] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,782 [shard  0] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard 10] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9216028065849746303, view token: 8512825797236005302): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard  9] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9220924248064531910, view token: -1648106516271635869): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard 13] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9219859730883390703, view token: -7918806164541364003): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard  2] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9222736443889999821, view token: -5319330787090229318): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard 10] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard  9] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard 13] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard  2] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard  8] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9216704778994998342, view token: -6963653130800501646): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard 16] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9210072177718897089, view token: 6882416012201346086): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard  8] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard 16] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard  5] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9221834874718566760, view token: -4748649548113281064): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard  7] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9216902851336773461, view token: -277866046175722077): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,783 [shard  3] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9222508416203745186, view token: -7926617861274549675): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,783 [shard  5] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,784 [shard  7] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,784 [shard 12] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9220089467296997912, view token: 1164057663306335344): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,784 [shard  3] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,784 [shard 12] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,784 [shard 14] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9214907925253619717, view token: -8987524013768975590): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,784 [shard 14] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
ERROR 2023-05-24 02:03:39,785 [shard  4] view - Error applying view update to 127.0.75.3 (view: ks.t_by_v2, base token: -9217669740212181123, view token: -7761093163043046939): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:39,785 [shard  4] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,782 [shard  6] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,782 [shard  1] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,782 [shard 11] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,782 [shard 15] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,782 [shard  0] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,784 [shard 13] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,784 [shard 10] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard  8] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard 16] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard  5] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard  2] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard  7] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard  3] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard 14] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard 12] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,785 [shard  9] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2023-05-24 02:03:40,786 [shard  4] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
INFO  2023-05-24 02:03:41,714 [shard  0] storage_service - Node 127.0.75.3 state jump to normal
INFO  2023-05-24 02:03:41,715 [shard  0] gossip - InetAddress 127.0.75.3 is now UP, status = NORMAL
INFO  2023-05-24 02:03:41,730 [shard  1] compaction - [Compact system.peers 34ca2020-f9d7-11ed-a0b3-a37fe78104ff] Compacting [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mgwwr68d/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-137-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mgwwr68d/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-120-big-Data.db:level=0:origin=compaction]
INFO  2023-05-24 02:03:41,737 [shard  1] compaction - [Compact system.peers 34ca2020-f9d7-11ed-a0b3-a37fe78104ff] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mgwwr68d/test/node2/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-154-big-Data.db:level=0]. 23kB to 11kB (~50% of original) in 5ms = 2MB/s. ~256 total partitions merged to 1.
INFO  2023-05-24 02:03:41,740 [shard  3] compaction - [Compact system.scylla_local 34cba6c0-f9d7-11ed-92b1-a37de78104ff] Compacting [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mgwwr68d/test/node2/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-377-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mgwwr68d/test/node2/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-360-big-Data.db:level=0:origin=compaction]
INFO  2023-05-24 02:03:41,748 [shard  3] compaction - [Compact system.scylla_local 34cba6c0-f9d7-11ed-92b1-a37de78104ff] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-mgwwr68d/test/node2/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-394-big-Data.db:level=0]. 11kB to 6kB (~51% of original) in 5ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2023-05-24 02:03:44,948 [shard  0] view - Finished building view ks.t_by_v2
INFO  2023-05-24 02:03:44,949 [shard  0] view - Finished building view ks.t_by_v
INFO  2023-05-24 02:03:54,717 [shard  0] storage_service - Node 127.0.75.3 state jump to normal
```

### PR DESCRIPTION
**Pull request by eliransin**
This miniset addresses two potential conversions to `global_schema_ptr` of incomplete materialized views schemas.
One of them was completely unnecessary and also is a "chicken and an egg" problem where on the sync schema procedure itself a view schema was converted to `global_schema_ptr` solely for the purposes of logging. This can create a
"hickup" in the materialized views updates if they are comming from a node with a different mv schema.
The reason why sometimes a synced schema can have no base info is because of deactivision and reactivision of the schema inside the `schema_registry` which doesn't restore the base information due to lack of context.
When a schema is synced the problem becomes easy since we can just use the latest base information from the database.

Fixes #14011

### CODE REVIEW

**Comment by eliransin** [comment]
As a result of working on this PR I also think that as a follow up we should also:
1. Add another state marker to a schema registry "obsolete" which will indicate that we already figured out that further mutations built on top of these schema are stale. If a schema registry is synced but we can't find either the table itself or in the case of a materialized view the base table, it means that the node emitting those mutations has fallen behind on schema sync and haven't learned yet about the deletion of the table/view.
2. We should eventually not log those kind of failures (Today we throw `no_such_column_family`) somewhere in the stack since the error is benign.
3. Also we should probably also eventually not throw exception at all as it is resource intensive and such mutations can be a bursty in nature (i.e view hints) and as a result hog the system unnecesairly.
4. It is probably also a good idea to eventually piggy back on the reply in order to notify the sending node that he needs to sync it's schema - which will eventually make it stop sending stale mutations faster. (maybe the reply should be the receiving node schema? or a sync command in the case of raft)

**Comment by eliransin** [comment]
I still haven't look into backports of this PR as this code changes a lot around this code due to the schema over raft work and probably each branch will need a different portion of this fix.
However those bugs are relatively easy to find and fix.

**Comment by avikivity** [comment]
Please change the subject so we can guess what this is fixing.

File: service/migration_manager.cc [hunk 1]
```diff
@@ -1137,27 +1137,43 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
-        // If Raft is used the schema is synced already (through barrier above), mark it as such.
-        co_await s->registry_entry()->maybe_sync([] { return make_ready_future<>(); });
-    } else {
-        co_await maybe_sync(s, dst);
+    if (!s->is_synced()) {
+        if (use_raft) {
+            // Mark entry as synced
+            co_await s->registry_entry()->maybe_sync([] { return make_ready_future<>(); });
+        } else {
+            // If raft is used the schema is synced already
```
[the remark this answers is not in the document]
Comment (eliransin) [reply service/migration_manager.cc:1158]: This is a carry over from rebasing (the code has changed). In the old code the comment was placed there.
I will remove.

File: service/migration_manager.cc [hunk 2]
```diff
@@ -1137,27 +1137,43 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
+            co_await maybe_sync(s, dst);
+        }
+    }
+    // here s is gurantied to be valid and synced
```
[the remark this answers is not in the document]
Comment (eliransin) [reply service/migration_manager.cc:1162]: Will fix

File: service/migration_manager.cc [hunk 3]
```diff
@@ -1137,27 +1137,43 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
+    if (s->is_view() && !s->view_info()->base_info()) {
+            // The way to get here is if the view schema was deactivated
```
[the remark this answers is not in the document]
Comment (eliransin) [reply service/migration_manager.cc:1164]: Will verify and fix

File: service/migration_manager.cc [hunk 4]
```diff
@@ -1137,27 +1137,43 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
+            // and reactivated again, or if we loaded it from the schema
+            // history.
+            auto& db = _storage_proxy.local_db();
+            // This line might throw a no_such_column_family but
+            // that is fine, if the schema is synced, it means that if
+            // we failed to get the base table, we learned about the base
+            // table not existing (which means that the view also doen't exist
+            // anymre), which means that this schema is actually useless for either
```
[the remark this answers is not in the document]
Comment (eliransin) [reply service/migration_manager.cc:1172]: Will fix

**Comment by eliransin** [comment]
> Looks good except a few typos.
> I'll be honest and say that I don't fully understand what is being fixed here. Am I correct in understanding that the set_base_info() at the very end of this patch is what actually "saves the day" and fixes the missing reference that got lost by freezing/thawing the schema? And all the other changes - are they really needed for the fix, or just to make error-handling in the future less disastrous than it was now?

You got it right.
The changes are not really needed for the fix but the code that was there was very convoluted, and did some unnecessary operations. For example, if we got the schema but it is not synced we called `get_schema_dfinition(...)` which is not a mistake, however doesn't add anything besides extraneous calls into the schema registry again.
Also in the previous function structure, there were multiple return statements so it would have been less clean to "fix" the schema on every return.

Finally you are also correct that this `set_base_info` is the call that actually fix the problem (synced views that doesn't have base information) :slightly_smiling_face:

**Comment by eliransin** [comment]
Pushed a new version, which fixes all of the typos and indentation comments.
Also refactored the function to contain less code duplication.

**Comment by eliransin** [comment]
Added the the persons who most recently touched this code (Gleb and Kamil)

**Review by nyh — APPROVED** [review]
I approve the set_base_info() at the end which is the really important part of this patch. 
For me, the other changes didn't add any clarify to the code (it is still hard to understand), but I can't find any obvious error in it, so I approve.

**Comment by nyh** [comment]
I approved this PR. The issue that this PR fixes was officially marked "P1" and we've been sitting on Eliran's fix for it for three weeks - this is excessive, and also not very fair.

So if anyone else wants to review this PR before it goes in, please try to do it today. Otherwise I'll merge it.

File: service/migration_manager.cc [hunk 5]
```diff
@@ -1145,27 +1145,38 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
+        auto& db = _storage_proxy.local_db();
+        // This line might throw a no_such_column_family but
+        // that is fine, if the schema is synced, it means that if
+        // we failed to get the base table, we learned about the base
+        // table not existing (which means that the view also doesn't exist
+        // any more), which means that this schema is actually useless for either
+        // read or write so we better throw than return an incomplete useless
+        // schema
+        schema_ptr base_schema = db.find_schema(s->view_info()->base_id());
+        s->view_info()->set_base_info(s->view_info()->make_base_dependent_view_info(*base_schema));
```
Comment (tgrabiec) [inline service/migration_manager.cc:1179]: This is done after s is marked as synced, after deferring point, and can race with other requests which may hit in the schema registry before we set the base info, and still trigger the abort.

File: service/migration_manager.cc [hunk 6]
```diff
@@ -1145,27 +1145,38 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
+    if (!s->is_synced()) {
+        if (use_raft) {
+            // Mark entry as synced we have already aquired the barrier
+            co_await s->registry_entry()->maybe_sync([] { return make_ready_future<>(); });
+        } else {
+            co_await maybe_sync(s, dst);
+        }
+    }
+    // here s is guaranteed to be valid and synced
+    if (s->is_view() && !s->view_info()->base_info()) {
```
Comment (tgrabiec) [inline service/migration_manager.cc:1166]: How does this fix prevent the problem after deactivation->activation?

**Review by tgrabiec — CHANGES_REQUESTED** [review]

**Comment by avikivity** [comment]
@eliransin please drive the review process to completion

**Comment by mykaul** [comment]
ping @eliransin

File: service/migration_manager.cc (hunk 6 above)
Comment (eliransin) [reply service/migration_manager.cc:1166]: The code makes sure that we either except out of `get_schema_for_write` or return an activated schema with
the base info.

File: service/migration_manager.cc (hunk 5 above)
Comment (eliransin) [reply service/migration_manager.cc:1179]: @tgrabiec 
I think that what you are asking is exactly what this code is trying to fix,
The bug was that prior to this patch we assumed that a `synced schema` == `schema with base info`
This proved to be wrong because of deactivate->activate (which doesn't restore the base info)
It is worth mentioning the the write workflow (and recently also the read) always gets its schema through this workflow, so following the logic of this patch (in high level):
1. Retrieve a synced schema (regardless of raft), at that point the registry entry can't be deactivated.
2. Fix the view info - which will also pin the base table in registry (if exists)
3. Either Return this schema to the caller or that at some point we except out due to stale schema (missing base which means that the view is also stale)

Maybe I am missing something and having a hard time to figure this out.
Would you describe the scenario you had in mind, that can lead to the crash? (with this code in)

**Comment by nyh** [comment]
pinging Eliran and Tomek:
1. @tgrabiec - you had comments, and Eliran answered them, without changing any code. Are these responses satisfactory, or not?
2. @eliransin github reports a conflict in service/migration_manager.cc. Please rebase your PR.

**Comment by eliransin** [comment]
@tgrabiec can you review my answer to you comments and help me find what I'm missing?

**Comment by eliransin** [comment]
> @tgrabiec can you review my answer to you comments and help me find what I'm missing?

@tgrabiec ping

**Comment by bhalevy** [comment]
@eliransin can you please rebase you branch so the review can resume from that point?

**Comment by nyh** [comment]
@bhalevy @kostja if you guys are looking for rules for reviews and how developers should work together (you seemed to have strong opinions on that last week), here are three rules I would add:
1. A reviewer that started a review, especially if he made some requests or judgement, should resume it promptly. This is much more important than attending to a new PR that someone randomly assigned to you. I already pointed this out last week, but @kostja and @avikivity weren't impressed. Maybe this issue is an even better example of what I was trying to say.
2. A PR author that doesn't rebase his PR often (in this case it's necessary, in other cases it's simply important to get CI running again, in case a success from a month ago no longer guarantees success ) - it means that he gave up on this PR. It might as well be converted to "draft".
3. A manager that sets an issue (https://github.com/scylladb/scylladb/issues/14011) to P1 and then allow a complete patch for it to just sit around for 4 months should give serious re-consideration to what "P1" means and why.

**Comment by bhalevy** [comment]
@nyh I'd add another point where we can improve:
- issue priorities are not inherited by their respective PRs, so it's unclear for a reviewer that a review needs to be in P1 since it fixes a P1 issue.  @mykaul is looking into automating this process somehow with github automagication

**Comment by mykaul** [comment]
> @nyh I'd add another point where we can improve:
> 
> * issue priorities are not inherited by their respective PRs, so it's unclear for a reviewer that a review needs to be in P1 since it fixes a P1 issue.  @mykaul is looking into automating this process somehow with github automagication

https://github.com/scylladb/scylla-pkg/issues/3685

**Comment by mykaul** [comment]
> @bhalevy @kostja if you guys are looking for rules for reviews and how developers should work together (you seemed to have strong opinions on that last week), here are three rules I would add:
> 
> 1. A reviewer that started a review, especially if he made some requests or judgement, should resume it promptly. This is much more important than attending to a new PR that someone randomly assigned to you. I already pointed this out last week, but @kostja and @avikivity weren't impressed. Maybe this issue is an even better example of what I was trying to say.

I'm not sure we have in place the means, other manual follow-up, that a reviewer can know 'the ball is in their court'.

> 2. A PR author that doesn't rebase his PR often (in this case it's necessary, in other cases it's simply important to get CI running again, in case a success from a month ago no longer guarantees success ) - it means that he gave up on this PR. It might as well be converted to "draft".

We could have had automation for it. I keep mentioning https://mergify.com/ as such automation tool.

> 3. A manager that sets an issue ([test_interrupt_build_process dtest failed with schema_registry - Tried to build a global schema for view ks.t_by_v2 with an uninitialized base info #14011](https://github.com/scylladb/scylladb/issues/14011)) to P1 and then allow a complete patch for it to just sit around for 4 months should give serious re-consideration to what "P1" means and why.

Agreed. We need to work on less issues, with more focus on what we fix - every week.

**Review by tgrabiec — APPROVED** [review]

File: service/migration_manager.cc (hunk 6 above)
Comment (tgrabiec) [reply service/migration_manager.cc:1166]: So this fix assumes that every activation goes through get_schema_for_write().

File: service/migration_manager.cc (hunk 5 above)
Comment (tgrabiec) [reply service/migration_manager.cc:1179]: I was worried that a concurrent `local_schema_registry().get_or_load()` which is not going through get_schema_for_write() could get a schema which doesn't yet have the view attached, if it happens before we attach it here.

One such place is here:

```
schema_ptr schema::get_reversed() const {
    return local_schema_registry().get_or_load(reversed(_raw._version), [this] (table_schema_version) {
        return frozen_schema(make_reversed());
    });
}
```

Is it vulnerable too?

Comment (eliransin) [reply service/migration_manager.cc:1198]: Yes, it is vulnerable.
However:
1. I couldn't find where in the code this is actually used (except for tests).
2. In order to fail one will need to reverse the schema and then attempt to make a `global_ptr` out of it.

You are right that we probably need a more accurate solution to the problem (probably amend schema registry in some way to handle "post freeze".
However, the specific flow I fixed was found by investigating real failures.

File: service/migration_manager.cc (hunk 6 above)
Comment (eliransin) [reply service/migration_manager.cc:1185]: Not exactly.
The context of when the activation happened is not that important.
This fix "knows" however, that callers to get_schema_for_write/get_schema_for_read are going to create global pointers from the obtained schema and that there is a chance that the schema deactivated (and maybe even reactivated) in the past. So all that this fix boils down to is to make sure that schemas that are returned from the aforementioned functions can be globalized.

Comment (eliransin) [reply service/migration_manager.cc:1185]: The cover letter first sentence is:
> This miniset addresses two potential conversions to global_schema_ptr of incomplete materialized views schemas.

So it is a specific fix, not a fix all solution which will probably be complicated but I agree we should eventually have.

**Comment by eliransin** [comment]
> @eliransin can you please rebase you branch so the review can resume from that point?

rebased

**Comment by kostja** [comment]
@nyh please merge without waiting for @gleb-cloudius or @kbr-scylla 

The reason they are on this pull request is that I believe this patch is one of the many we will need to address a systemic problem of metadata cache consistency.

**Comment by kostja** [comment]
@mykaul I don't think this is an evident backport candidate. The issue has no test case and it is unclear if it is addressing a regression (the code behaviour that this patch is changing has been present in 5.3 and 5.2). 

This is part of an investigative process we haven't done:

1. When the original issue #14011 was reported we did not verify with certainty it is a regression. I suspect it's because the dtest that found it was flaky all along - why we didn't pay attention before I don't know.
2. The patch doesn't provide an analysis when the problem got introduced.
3. The patch has no test case. 

We need to get better at all three.

**Comment by mykaul** [comment]
> @mykaul I don't think this is an evident backport candidate. The issue has no test case and it is unclear if it is addressing a regression (the code behaviour that this patch is changing has been present in 5.3 and 5.2).

It should be backported to 5.4. It was reported before we branched and we don't want it to be hitting us in 5.4, no?

> 
> This is part of an investigative process we haven't done:
> 
> 1. When the original issue [test_interrupt_build_process dtest failed with schema_registry - Tried to build a global schema for view ks.t_by_v2 with an uninitialized base info #14011](https://github.com/scylladb/scylladb/issues/14011) was reported we did not verify with certainty it is a regression. I suspect it's because the dtest that found it was flaky all along - why we didn't pay attention before I don't know.

Even if it was flaky, it failed enough to expose this issue, no?

> 2. The patch doesn't provide an analysis when the problem got introduced.
> 3. The patch has no test case.

https://github.com/scylladb/scylladb/issues/15235 - not a test case for a patch, but it was caught part of end to end testing.
It's also unclear if the test at https://github.com/scylladb/scylladb/issues/14011 (test_interrupt_build_process dtest failed with schema_registry) reproduces it reliably or not - asked @eliransin to run it 100 times before and after his patch.

> 
> We need to get better at all three.

Always true.

File: service/migration_manager.cc [hunk 7]
```diff
@@ -1159,29 +1159,43 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
-        co_await maybe_sync(s, dst);
+    if (!s->is_synced()) {
+        if (use_raft) {
+            // If Raft is used the schema is synced already (through barrier above), mark it as such.
+            mlogger.trace("Mark schema {} as synced", v);
+            co_await s->registry_entry()->maybe_sync([] { return make_ready_future<>(); });
+        } else {
+            co_await maybe_sync(s, dst);
+        }
+    }
```
Comment (kbr-scylla) [inline service/migration_manager.cc:1183]: The refactors performed above should be in a separate commit, they are not really part of the fix, it would make the reviewer's life much easier.

File: service/migration_manager.cc [hunk 8]
```diff
@@ -1159,29 +1159,43 @@ future<schema_ptr> migration_manager::get_schema_for_write(table_schema_version
...
+        auto& db = _storage_proxy.local_db();
+        // This line might throw a no_such_column_family but
+        // that is fine, if the schema is synced, it means that if
+        // we failed to get the base table, we learned about the base
+        // table not existing (which means that the view also doesn't exist
+        // any more), which means that this schema is actually useless for either
+        // read or write so we better throw than return an incomplete useless
+        // schema
+        schema_ptr base_schema = db.find_schema(s->view_info()->base_id());
+        s->view_info()->set_base_info(s->view_info()->make_base_dependent_view_info(*base_schema));
```
Comment (kbr-scylla) [inline service/migration_manager.cc:1198]: There is an almost exact copy of this piece of code (modulo comments) inside `get_schema_definition`. Maybe it deserves getting refactored to a separate function? (the new comments have more explanation so I'd use them)

**Comment by eliransin** [comment]
@kbr-scylla also reviewed.
@nyh , @tgrabiec , @kbr-scylla can one of you merge it please?

/cc @kostja @mykaul

**Comment by nyh** [comment]
> @nyh please merge without waiting for @gleb-cloudius or @kbr-scylla

Done. Merged.

Note that I never wait for people who were invited to do a review but never came. I do wait for people who started the review and had complaints (as was the case here with @tgrabiec) but as soon as this person "approves", there's no need to wait any more, unless I have reservations of my own.
I will only wait for an invited reviewer who hasn't come to review if I feel that his review is essential (e.g., some code that has one specific expert, and this person should really do a review). Otherwise, the reviewer list is an "or" list, not an "and" list.

**Comment by mykaul** [comment]
Thanks for the merge.
@eliransin - please prepare the backport to 5.4 promptly.

File: service/migration_manager.cc (hunk 6 above)
Comment (tgrabiec) [reply service/migration_manager.cc:1185]: Yes, I approved the fix because it fixes some common scenarios and doesn't make things worse. But I think we still have holes which may bite us and we should come with a more systemic approach for handling view schemas.

File: service/migration_manager.cc (hunk 5 above)
Comment (tgrabiec) [reply service/migration_manager.cc:1198]: > Yes, it is vulnerable. However:
> 
> 1. I couldn't find where in the code this is actually used (except for tests).

It's used in reverse-order reads.

> 2. In order to fail one will need to reverse the schema and then attempt to make a `global_ptr` out of it.

Or just try to access the view info, which will be missing in the reversed schema, right?

**Comment by tgrabiec** [comment]
I think another way to fix this would be to get rid of schema activation from frozen schema, so that we only rely on the loader. We could keep the schema object managed in the registry by unique_ptr while deactivated (with a deleter based on lw_shared_ptr_accessors).

**Comment by eliransin** [comment]
> I think another way to fix this would be to get rid of schema activation from frozen schema, so that we only rely on the loader. We could keep the schema object managed in the registry by unique_ptr while deactivated (with a deleter based on lw_shared_ptr_accessors).

I will look into it.

**Comment by eliransin** [comment]
> Thanks for the merge. @eliransin - please prepare the backport to 5.4 promptly.

On it

**Comment by eliransin** [comment]
@mykaul - @denesb already queued a backport to 5.4
5.3 needs this too and it is not a clean backport so I will prepare a backport.

**Comment by denesb** [comment]
> @mykaul - @denesb already queued a backport to 5.4 5.3 needs this too and it is not a clean backport so I will prepare a backport.

We don't have a 5.3, do you mean 5.2?

**Comment by eliransin** [comment]
> > @mykaul - @denesb already queued a backport to 5.4 5.3 needs this too and it is not a clean backport so I will prepare a backport.
> 
> We don't have a 5.3, do you mean 5.2?

@denesb 5.2 doesn't need this.

**Comment by denesb** [comment]
> > > @mykaul - @denesb already queued a backport to 5.4 5.3 needs this too and it is not a clean backport so I will prepare a backport.
> > 
> > 
> > We don't have a 5.3, do you mean 5.2?
> 
> @denesb 5.2 doesn't need this.

We are good then, no more backporting is required.
