### PR TITLE
encryption_at_rest_test: Fix some spurious errors

### LINKED ISSUE #24574: [x86_64/debug] test_kmip_provider_broken_sstables_on_restart failed
https://jenkins.scylladb.com/job/scylla-master/job/next/9301/ failed on test_kmip_provider_broken_sstables_on_restart test with an ERROR:

```
11:27:57  =================================== FAILURES ===================================
11:27:57  ________________ test_kmip_provider_broken_sstables_on_restart _________________
11:27:57  [gw3] linux -- Python 3.13.3 /usr/bin/python3
11:27:57  working_dir: /jenkins/workspace/scylla-master/next/scylla
11:27:57  Internal Error: calling /jenkins/workspace/scylla-master/next/scylla/build/debug/test/boost/encryption_at_rest_test for test test_kmip_provider_broken_sstables_on_restart failed (return_code=-6):
11:27:57  output file:/scylladir/testlog/x86_64/debug/test_kmip_provider_broken_sstables_on_restart_stdout.log
11:27:57  log:
11:27:57  command to repeat:/jenkins/workspace/scylla-master/next/scylla/build/debug/test/boost/encryption_at_rest_test --report_level=no --output_format=XML --log_sink=/scylladir/testlog/x86_64/debug/test_kmip_provider_broken_sstables_on_restart.log --catch_system_errors=no --color_output=false --run_test=test_kmip_provider_broken_sstables_on_restart -- --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100 --reactor-backend linux-aio -c2 -m2G
11:27:57  encryption_at_rest_test.cc:-1: C++ failure
11:27:57  ------------------------------ Captured log call -------------------------------
11:27:57  03:59:17.918 DEBUG>  Using selector: EpollSelector
11:27:57  03:59:40.314 WARNING>  Error parsing the log_sink output. Can be empty or invalid
11:27:57  ---- generated xml file: /scylladir/testlog/x86_64/report/pytest_cpp_1.xml -----
11:27:57  =========================== short test summary info ============================
11:27:57  FAILED test/boost/encryption_at_rest_test.cc::test_kmip_provider_broken_sstables_on_restart.debug.1
11:27:57  ================= 1 failed, 3231 passed in 2227.94s (0:37:07) ==================
```

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #24574 

* Ensure we close the embedded load_cache objects on encryption shutdown, otherwise we can, in unit testing, get destruction of these while a timer is still active -> assert
* Add extra exception handling to `network_error_test_helper`, so even if test framework might exception-escape, we properly stop the network proxy to avoid use after free.

### CODE REVIEW

File: ent/encryption/kms_host.cc [hunk 1]
```diff
@@ -826,6 +828,11 @@ future<> encryption::kms_host::impl::init() {
     _initialized = true;
 }
 
+future<> encryption::kms_host::impl::stop() {
+    co_await _attr_cache.stop();
+    co_await _id_cache.stop();
```
Comment (bhalevy) [inline ent/encryption/kms_host.cc:833]: nit: any reason order is reversed compared to kmip_host::impl::disconnect?

**Comment by bhalevy** [comment]
Looks good other than nitpicking

File: ent/encryption/kms_host.cc (hunk 1 above)
Comment (elcallio) [reply ent/encryption/kms_host.cc:833]: No. The order does not matter.

Comment (bhalevy) [reply ent/encryption/kms_host.cc:833]: I rrcommend to repeat the same order everywhere for symmetry reasons.

File: ent/encryption/encryption.cc [hunk 2]
```diff
@@ -472,6 +472,14 @@ class encryption_context_impl : public encryption_context {
             for (auto&& [id, h] : _per_thread_kmip_host_cache[this_shard_id()]) {
                 co_await h->disconnect();
             }
+            static auto stop_all = [](auto&& cache) -> future<> {
+                for (auto& [k, host] : cache) {
```
Comment (regevran) [inline ent/encryption/encryption.cc:476]: nit, 
C++26 will have a [nice placeholder with no name](https://github.com/cplusplus/papers/issues/878)
```suggestion
                for (auto& [_, host] : cache) {
```

File: test/boost/encryption_at_rest_test.cc [hunk 3]
```diff
@@ -1077,41 +1077,49 @@ static future<> test_broken_encrypted_commitlog(const test_provider_args& args,
...
+            , exceptions::mutation_write_timeout_exception
+        );
+    } catch (...) {
+        p = std::current_exception();
+    }
 
     co_await proxy.stop();
+
+    if (p) {
+        std::rethrow_exception(p);
```
Comment (regevran) [inline test/boost/encryption_at_rest_test.cc:1121]: Why not just fail the test?

File: ent/encryption/encryption.cc (hunk 2 above)
Comment (elcallio) [reply ent/encryption/encryption.cc:476]: _will_ have. Atm, not all compilers we run do afaik.

File: test/boost/encryption_at_rest_test.cc (hunk 3 above)
Comment (elcallio) [reply test/boost/encryption_at_rest_test.cc:1121]: Throwing the exception will fail the test. And propagate the info. Automatically. Separation of concern.

File: ent/encryption/encryption.cc (hunk 2 above)
Comment (regevran) [reply ent/encryption/encryption.cc:476]: `_` is a valid variable name _today_.
The new thing is that it will be usable in situations where today are not allowed.
e.g:
```cpp
auto& [_, _, _, fourth] = get_tuple();
```

Comment (elcallio) [reply ent/encryption/encryption.cc:476]: Yes. But not in all editions of clang we run.

File: test/boost/encryption_at_rest_test.cc (hunk 3 above)
Comment (regevran) [reply test/boost/encryption_at_rest_test.cc:1121]: Yes, understood.
But when re-throwing we lose the [context](https://github.com/scylladb/scylladb/pull/24633/files#diff-458dba4aa9e925a5898aaaea3d5de8f86b94b7b7b8336f5e079b08c2ae997289R1078-R1079) that might help debugging.

Comment (elcallio) [reply test/boost/encryption_at_rest_test.cc:1121]: Which is why there is a message in the catch, explaining the point of exception. Also, failing the test at this point is borderline pointless, as this is a helper routine.

File: test/boost/test_config.yaml [hunk 4]
```diff
@@ -14,6 +14,7 @@ run_first:
 # These test cannot work in case-by-case mode because
 # some test-cases depend on each other
 no_parallel_cases:
+    - encryption_at_rest_test
```
Comment (avikivity) [inline test/boost/test_config.yaml]: Can you expand on what exactly is problematic? It's okay not to be clever and to run serially, but at least record the root cause.

Comment (elcallio) [reply test/boost/test_config.yaml]: This is probably a bit overly cautious. The KMIP tests all launch a PyKMIP fixture, which, while it _should_ be independent (different work dir, different port etc), _might_ have some issues with running in parallel. I cannot really prove it, but some CI fails look like there might have been a problem here. Serializing the test ensures we get the same behaviour when running the executable directly, as with test.py/CI. 

Noted in the comment: Makes test serial - we use a helper process for KMIP test cases -> can cause issues if parallel

(Should be a "maybe" there - I am not super fond of this myself)

Comment (elcallio) [reply test/boost/test_config.yaml]: Re-ran all tests a number of times, on even higher concurrency. Should be safe to drop this patch.

**Review by bhalevy — APPROVED** [review]

**Comment by elcallio** [comment]
@scylladb/scylla-maint  ping?

**Comment by denesb** [comment]
> @scylladb/scylla-maint ping?

This was queued already by @xemul, but we didn't have a successful promotion yet.
