### PR TITLE
cql3: expr: support evaluate(column_mutation_attribute)

### LINKED ISSUE #12906: Allow evaluating any CQL expressions
A CQL [expression](https://github.com/scylladb/scylladb/blob/ef50170120153b7cc11bea7cfccfa85b5a28bd82/cql3/expr/expression.hh#L147) is our representation of a parsed CQL abstract syntax tree.

Pieces of CQL like `pk = 3` or `token(p1, p2) IN (1, udf_function(1, other_column)) AND c1 = 3 AND ck < 2`  are parsed by ANTLR and then represented as `expression`.

We would like to be able to evaluate any such expression to a single value. This is the job of the function [`expr::evaluate`](https://github.com/scylladb/scylladb/blob/ef50170120153b7cc11bea7cfccfa85b5a28bd82/cql3/expr/expression.hh#L750). It takes an expression like `pk = 3`, finds out the value of `pk` and then evaluates the whole expression to `TRUE`, `FALSE`, `NULL` or an error.

The function is already implemented for most types of expressions, but other still cause `on_internal_error`.

Having `evaluate` could greatly simplify the filtering code. Instead of extracting restrictions for each column and then checking whether they are true we could just call `evaluate()` on the whole WHERE clause. This is currently impossible because e.g `token(pk)` will cause `on_internal_error`, so special care has to be taken to avoid any such situations.

It will also allow us to move forward with the CQL rewrite. It will be much easier and safer to refactor when we can just call `evaluate()` on any expression without worries about crashing.

### PR DESCRIPTION
**Pull request by avikivity**
In preparation for converting selectors to evaluate expressions,
add support for evaluating column_mutation_attribute (representing
the WRITETIME/TTL pseudo-functions).

A unit test is added.

Fixes #12906

### CODE REVIEW

**Review by nyh — APPROVED** [review]

File: cql3/expr/expression.cc [hunk 1]
```diff
@@ -1707,6 +1707,33 @@ cql3::raw_value evaluate(const field_selection& field_select, const evaluation_i
...
 }
 
+static
+cql3::raw_value
+evaluate(const column_mutation_attribute& cma, const evaluation_inputs& inputs) {
+    auto col = expr::as_if<column_value>(&cma.column);
+    if (!col) {
+        on_internal_error(expr_logger, fmt::format("evaluating column_mutation_attribute of non-column {}", cma.column));
+    }
+    int32_t index = inputs.selection->index_of(*col->col);
```
Comment (cvybhu) [inline cql3/expr/expression.cc:1717]: It would be nice to check that this column exists, otherwise we will get a crash when it doesn't.

**Review by cvybhu — APPROVED** [review]

File: cql3/expr/expression.cc (hunk 1 above)
Comment (avikivity) [reply cql3/expr/expression.cc:1717]: prepare should create self-consistent data.

After we clean up the code some more, prepare can store the index directly in the column_value thing.
