### PR TITLE
compaction: update maintenance sstable set on scrub compaction completion

### LINKED ISSUE #20030: [6.1.0~rc1] nodetool scrub --skip-corrupted failed with filesystem error: link failed: No such file or directory
## Packages

Scylla version: `6.1.0~rc1-20240726.97ae704f993c` with build-id `56df0cd0180f616ddf69aeab6263a87d9366a2a2`

Kernel Version: `6.8.0-1012-aws`

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

CorruptThenScrub nemesis failed on node-7 in this run

```
Command: '/usr/bin/nodetool  scrub --skip-corrupted keyspace1'

Exit code: 4

Stdout:



Stderr:

error executing GET request to http://localhost:10000/storage_service/keyspace_scrub/keyspace1 with parameters {"scrub_mode": "SKIP"}: remote replied with status code 500 Internal Server Error:
std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: link failed: No such file or directory [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-TOC.txt] [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/snapshots/pre-scrub-1722042466796/me-3gi6_01m1_2xvq82lxjicx5boij1-big-TOC.txt.tmp])
```

grep node-7 log for `me-3gi6_01m1_2xvq82lxjicx5boij1`:

```
...
Jul 27 00:34:49.500403 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Filter.db: resizing bitset from 216 bytes to 40 bytes. sstable origin: streaming
Jul 27 01:07:19.412452 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Scrub keyspace1.standard1 9265db40-4bb4-11ef-ab93-cf1b23caa2cd] Scrubbing in skip mode [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Data.db:level=0:origin=streaming]
Jul 27 01:38:16.820085 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] compaction - [Reshape keyspace1.standard1 e57fac30-4bb8-11ef-ab93-cf1b23caa2cd] Reshaping [/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01lt_27axs2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ll_0pi7k2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ld_01aao2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01l4_3i11c2lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01ku_2pb342lxjicx5boij1-big-Data.db:level=0:origin=streaming,/var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_04b0_0tktc2lxjicx5boij1-big-Data.db:level=0:origin=repair]
Jul 27 01:38:16.887069 longevity-100gb-4h-6-1-db-node-7b6252df-7 scylla[6506]:  [shard  0:strm] sstable - Unable to delete /var/lib/scylla/data/keyspace1/standard1-126cc1f04ba111ef8575ae8373908466/me-3gi6_01m1_2xvq82lxjicx5boij1-big-TOC.txt because it doesn't exist.
```

## Impact

`nodetool scrub --skip-corrupted <ks>` command failed

## How frequently does it reproduce?

Next run of the same job with 6.1.0-20240804.abbf0b24a60c passed: https://argus.scylladb.com/test/2cca5979-f5f4-424b-9967-7f79e7d6be4c/runs?additionalRuns[]=17c85371-c29d-45c9-b373-ee4ab64cef74

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-6-1-db-node-7b6252df-9 (54.197.132.200 | 10.12.10.146) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-8 (18.212.202.75 | 10.12.8.200) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-7 (3.90.180.142 | 10.12.10.195) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-6 (3.91.58.31 | 10.12.8.103) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-5 (34.236.146.198 | 10.12.10.66) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-4 (54.226.152.70 | 10.12.9.70) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-3 (34.228.199.37 | 10.12.11.183) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-2 (18.234.226.132 | 10.12.8.40) (shards: 14)
- longevity-100gb-4h-6-1-db-node-7b6252df-1 (34.203.223.213 | 10.12.8.51) (shards: 14)

OS / Image: `ami-0b2b53e4d5c876e8d` (aws: undefined_region)

Test: `longevity-100gb-4h-test`
Test id: `7b6252df-9da0-4da6-ab26-d1c35806df1c`
Test name: `scylla-6.1/longevity/longevity-100gb-4h-test`

Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/79af70b59ed166b7764591522074edabd475eecb/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7b6252df-9da0-4da6-ab26-d1c35806df1c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7b6252df-9da0-4da6-ab26-d1c35806df1c)
- Show all stored logs command: `$ hydra investigate show-logs 7b6252df-9da0-4da6-ab26-d1c35806df1c`

## Logs:
- **db-cluster-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/db-cluster-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/db-cluster-7b6252df.tar.gz)
- **sct-runner-events-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-runner-events-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-runner-events-7b6252df.tar.gz)
- **sct-7b6252df.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-7b6252df.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/sct-7b6252df.log.tar.gz)
- **loader-set-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/loader-set-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/loader-set-7b6252df.tar.gz)
- **monitor-set-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/monitor-set-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/monitor-set-7b6252df.tar.gz)
- **parallel-timelines-report-7b6252df.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/parallel-timelines-report-7b6252df.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b6252df-9da0-4da6-ab26-d1c35806df1c/20240727_030147/parallel-timelines-report-7b6252df.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.1/job/longevity/job/longevity-100gb-4h-test/6/)
[Argus](https://argus.scylladb.com/test/2cca5979-f5f4-424b-9967-7f79e7d6be4c/runs?additionalRuns[]=7b6252df-9da0-4da6-ab26-d1c35806df1c)
</details>

### PR DESCRIPTION
**Pull request by lkshminarayanan**
Scrub compaction can pick up input sstables from maintenance sstable set
but on compaction completion, it doesn't update the maintenance set
leaving the original sstable in set after it has been scrubbed. To fix
this, on compaction completion has to update the maintenance sstable if
the input originated from there. This PR solves the issue by updating the
correct sstable_sets on compaction completion.

Fixes #20030

This issue has existed since the introduction of main and maintenance sstable sets into scrub compaction. It would be good to have the fix backported to versions 6.1 and 6.2.

### CODE REVIEW

**Comment by lkshminarayanan** [comment]
> > The PR achieves this by introducing a bool flag
> > using which the origin of the sstable is tracked throughout the scrub
> > compaction process.
> 
> I haven't reviewed the code yet, but right away a bool flag sounds too restrictive. We have many different sstable directories, how can we handle selecting the correct set to remove the sstable from by just a boolean?

The flag is used to identify which sstable_set the sstable belongs to - either main_sstable_set or maintenance_sstable_set. I 'll update the cover letter.

**Comment by denesb** [comment]
> > > The PR achieves this by introducing a bool flag
> > > using which the origin of the sstable is tracked throughout the scrub
> > > compaction process.
> > 
> > 
> > I haven't reviewed the code yet, but right away a bool flag sounds too restrictive. We have many different sstable directories, how can we handle selecting the correct set to remove the sstable from by just a boolean?
> 
> The flag is used to identify which sstable_set the sstable belongs to - either main_sstable_set or maintenance_sstable_set. I'll update the cover letter.

But can we not scrub sstables in other directories?

**Comment by lkshminarayanan** [comment]
> > > > The PR achieves this by introducing a bool flag
> > > > using which the origin of the sstable is tracked throughout the scrub
> > > > compaction process.
> > > 
> > > 
> > > I haven't reviewed the code yet, but right away a bool flag sounds too restrictive. We have many different sstable directories, how can we handle selecting the correct set to remove the sstable from by just a boolean?
> > 
> > 
> > The flag is used to identify which sstable_set the sstable belongs to - either main_sstable_set or maintenance_sstable_set. I'll update the cover letter.
> 
> But can we not scrub sstables in other directories?

The regular scrubbing picks up only sstables from these two sets - relevant code [here](https://github.com/scylladb/scylladb/blob/1d0c6aa26f105056aab001022a0f9487850af16b/compaction/compaction_manager.cc#L2153).

There is a validate mode that works on quarantined sstables but this PR will not affect that path.

**Comment by lkshminarayanan** [comment]
> > > > > > The PR achieves this by introducing a bool flag
> > > > > > using which the origin of the sstable is tracked throughout the scrub
> > > > > > compaction process.
> > > > > 
> > > > > 
> > > > > I haven't reviewed the code yet, but right away a bool flag sounds too restrictive. We have many different sstable directories, how can we handle selecting the correct set to remove the sstable from by just a boolean?
> > > > 
> > > > 
> > > > The flag is used to identify which sstable_set the sstable belongs to - either main_sstable_set or maintenance_sstable_set. I'll update the cover letter.
> > > 
> > > 
> > > But can we not scrub sstables in other directories?
> > 
> > 
> > The regular scrubbing picks up only sstables from these two sets - relevant code [here](https://github.com/scylladb/scylladb/blob/1d0c6aa26f105056aab001022a0f9487850af16b/compaction/compaction_manager.cc#L2153).
> > There is a validate mode that works on quarantined sstables but this PR will not affect that path.
> 
> Maybe we can merge update_sstable_lists_on_off_strategy_completion() into update_main_sstable_list_on_compaction_completion(), so we can get rid of the flag (even existing offstrategy one).

Sounds good. So, we rebuild both main and maintenance sets at the end of every compaction regardless of they are offstrategy or not. Is that okay?

**Comment by raphaelsc** [comment]
> > > > > > > The PR achieves this by introducing a bool flag
> > > > > > > using which the origin of the sstable is tracked throughout the scrub
> > > > > > > compaction process.
> > > > > > 
> > > > > > 
> > > > > > I haven't reviewed the code yet, but right away a bool flag sounds too restrictive. We have many different sstable directories, how can we handle selecting the correct set to remove the sstable from by just a boolean?
> > > > > 
> > > > > 
> > > > > The flag is used to identify which sstable_set the sstable belongs to - either main_sstable_set or maintenance_sstable_set. I'll update the cover letter.
> > > > 
> > > > 
> > > > But can we not scrub sstables in other directories?
> > > 
> > > 
> > > The regular scrubbing picks up only sstables from these two sets - relevant code [here](https://github.com/scylladb/scylladb/blob/1d0c6aa26f105056aab001022a0f9487850af16b/compaction/compaction_manager.cc#L2153).
> > > There is a validate mode that works on quarantined sstables but this PR will not affect that path.
> > 
> > 
> > Maybe we can merge update_sstable_lists_on_off_strategy_completion() into update_main_sstable_list_on_compaction_completion(), so we can get rid of the flag (even existing offstrategy one).
> 
> Sounds good. So, we rebuild both main and maintenance sets at the end of every compaction regardless of they are offstrategy or not. Is that okay?

That's exactly what I thought, removing the input sstables from both (set that doesn't have it won't be affected by attempt to remove sstable that exist in the other set), and adding to main, since it's one-directional (always output is added to main set).

**Comment by lkshminarayanan** [comment]
Changelog V2 :
 - Existing `update_main_sstable_list_on_compaction_completion` method has been repurposed to update the maintenance sstable sets as well on compaction completion.
 - The `update_main_sstable_list_on_compaction_completion` is now renamed to `update_sstable_sets_on_compaction_completion`
 - replaced `update_sstable_lists_on_off_strategy_completion` with the new `update_sstable_sets_on_compaction_completion`

**Comment by lkshminarayanan** [comment]
> > > > > > > > The PR achieves this by introducing a bool flag
> > > > > > > > using which the origin of the sstable is tracked throughout the scrub
> > > > > > > > compaction process.
> > > > > > > 
> > > > > > > 
> > > > > > > I haven't reviewed the code yet, but right away a bool flag sounds too restrictive. We have many different sstable directories, how can we handle selecting the correct set to remove the sstable from by just a boolean?
> > > > > > 
> > > > > > 
> > > > > > The flag is used to identify which sstable_set the sstable belongs to - either main_sstable_set or maintenance_sstable_set. I'll update the cover letter.
> > > > > 
> > > > > 
> > > > > But can we not scrub sstables in other directories?
> > > > 
> > > > 
> > > > The regular scrubbing picks up only sstables from these two sets - relevant code [here](https://github.com/scylladb/scylladb/blob/1d0c6aa26f105056aab001022a0f9487850af16b/compaction/compaction_manager.cc#L2153).
> > > > There is a validate mode that works on quarantined sstables but this PR will not affect that path.
> > > 
> > > 
> > > Maybe we can merge update_sstable_lists_on_off_strategy_completion() into update_main_sstable_list_on_compaction_completion(), so we can get rid of the flag (even existing offstrategy one).
> > 
> > 
> > Sounds good. So, we rebuild both main and maintenance sets at the end of every compaction regardless of they are offstrategy or not. Is that okay?
> 
> That's exactly what I thought, removing the input sstables from both (set that doesn't have it won't be affected by attempt to remove sstable that exist in the other set), and adding to main, since it's one-directional (always output is added to main set).

Done. cc @denesb

File: replica/table.cc [hunk 1]
```diff
@@ -1915,11 +1916,25 @@ compaction_group::update_sstable_sets_on_compaction_completion(sstables::compact
...
         virtual void execute() override {
             for (auto&& [cg, d] : _cg_desc) {
                 cg->set_main_sstables(std::move(d.new_main_sstables));
+                if (d.new_maintenance_sstables) {
+                    // offstrategy or scrub compaction - replace the maintenance set
+                    cg->set_maintenance_sstables(std::move(d.new_maintenance_sstables.value()));
+                }
             }
             // FIXME: the following is not exception safe
             _t.refresh_compound_sstable_set();
```
Comment (raphaelsc) [inline replica/table.cc:1893]: only old sstables from main should be removed from the backlog tracker below. maybe build_new_list() interface can be adjusted to return which sstables were actually removed from the set (using pair or struct), and then you can use that info to simply condition to trigger maintenance set rebuild, and adjust backlog tracker appropriately.

Comment (lkshminarayanan) [reply replica/table.cc:1899]: Done.

**Comment by lkshminarayanan** [comment]
Changelog V3:
 - updated `build_new_list()` to return removed sstables as well and use that to update the main/maintenance sstable sets.

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/sstable_compaction_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/304/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1799/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12904/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4892/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/)
> 
> #### Failed Tests (10/36609):
> * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> * [test_simple_add_new_node_while_query_info[1]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_add_new_node_while_query_info_1_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_add_new_node_while_query_info%5B1%5D)
> * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> 
> #### Build Details:
> * Duration: 8 hr 43 min
> * Builder: i-0797c39d6bf58af00 (m5ad.8xlarge)

@lkshminarayanan any idea on the failure?

**Comment by avikivity** [comment]
> Scrub compaction can pick up input sstables from maintenance sstable set but on compaction completion, it doesn't update the maintenance set leaving the original sstable in set after it has been scrubbed. To fix this, on compaction completion has to update the maintenance sstable if the input originated from there. This PR solves the issue by updating the correct sstable_sets on compaction completion.
> 
> Fixes #20030
> 
> This is a bug fix and should be backported to older versions.

How does scrub change sstables? Isn't it a read-only process?

**Comment by raphaelsc** [comment]
> > Scrub compaction can pick up input sstables from maintenance sstable set but on compaction completion, it doesn't update the maintenance set leaving the original sstable in set after it has been scrubbed. To fix this, on compaction completion has to update the maintenance sstable if the input originated from there. This PR solves the issue by updating the correct sstable_sets on compaction completion.
> > Fixes #20030
> > This is a bug fix and should be backported to older versions.
> 
> How does scrub change sstables? Isn't it a read-only process?

There's a scrub mode that tries to repair logical damage, like reordered keys IIRC. I am not a fan of it, repair is better to fix any kind of corruption. And I am also not a fan of putting the repaired sstable online right away. But anyway, this is orthogonal to this PR.

**Comment by denesb** [comment]
> > Scrub compaction can pick up input sstables from maintenance sstable set but on compaction completion, it doesn't update the maintenance set leaving the original sstable in set after it has been scrubbed. To fix this, on compaction completion has to update the maintenance sstable if the input originated from there. This PR solves the issue by updating the correct sstable_sets on compaction completion.
> > Fixes #20030
> > This is a bug fix and should be backported to older versions.
> 
> How does scrub change sstables? Isn't it a read-only process?

Actually, all but `VALIDATE` scrub mode, do modify the sstable -- they rewrite it into a new output sstable and discard the input sstables, just like all other compaction type. The `VALIDATE` is an exception. In this mode, the only change is that sstables may be moved to the quarantine directory (IIRC this can be disabled via the API).

**Comment by lkshminarayanan** [comment]
> > #### 🔴 CI State: FAILURE
> > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/sstable_compaction_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/304/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1799/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12904/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4892/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/)
> > #### Failed Tests (10/36609):
> > 
> > * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> > * [test_simple_add_new_node_while_query_info[1]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_add_new_node_while_query_info_1_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_add_new_node_while_query_info%5B1%5D)
> > * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> > * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> > 
> > #### Build Details:
> > 
> > * Duration: 8 hr 43 min
> > * Builder: i-0797c39d6bf58af00 (m5ad.8xlarge)
> 
> @lkshminarayanan any idea on the failure?

I'm looking into this.

**Comment by denesb** [comment]
> This is a bug fix and should be backported to older versions.

How old are we talking about? I see you added both 6.1 and 6.2, best to be specific when justifying the backport, with stating which commit introduced the regression or bug (or maybe it was like that since the start of times).

**Comment by lkshminarayanan** [comment]
> > This is a bug fix and should be backported to older versions.
> 
> How old are we talking about? I see you added both 6.1 and 6.2, best to be specific when justifying the backport, with stating which commit introduced the regression or bug (or maybe it was like that since the start of times).

Ack. Updated the cover letter.

**Comment by lkshminarayanan** [comment]
> > > #### 🔴 CI State: FAILURE
> > > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/sstable_compaction_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/304/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1799/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12904/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4892/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13271/)
> > > #### Failed Tests (10/36609):
> > > 
> > > * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_tablets___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> > > * [test_simple_add_new_node_while_query_info[1]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_add_new_node_while_query_info_1_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_add_new_node_while_query_info%5B1%5D)
> > > * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BSizeTieredCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D)
> > > * [test_delete_tombstone_gc_node_down[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13271/testReport/junit/compaction_test/TestCompaction/Tests___dtest_with_topology_changes___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_tombstone_gc_node_down%5BTimeWindowCompactionStrategy%5D)
> > > 
> > > #### Build Details:
> > > 
> > > * Duration: 8 hr 43 min
> > > * Builder: i-0797c39d6bf58af00 (m5ad.8xlarge)
> > 
> > 
> > @lkshminarayanan any idea on the failure?
> 
> I'm looking into this.

Changelog v4:

**Comment by lkshminarayanan** [comment]
@denesb @raphaelsc Hi! This is now ready for review.

**Review by raphaelsc — APPROVED** [review]
Looks good!

**Comment by mykaul** [comment]
@scylladb/scylla-maint  - please review for merge.

**Review by avikivity — APPROVED** [review]
