### PR TITLE
raft: server: drop waiters in `applier_fiber` instead of `io_fiber`

### LINKED ISSUE #11235: randomized_nemesis_test.cc: remove_leader_with_forwarding_finishes: Assertion `std::holds_alternative<std::monostate>(result)' failed.
Seen in https://jenkins.scylladb.com/job/scylla-master/job/build/1119/artifact/testlog/x86_64/debug/randomized_nemesis_test.remove_leader_with_forwarding_finishes.2201.log
scylla version 7f80602b010a973dd24953cf39161699e7afcb42
```
random-seed=872648260
randomized_nemesis_test: test/raft/randomized_nemesis_test.cc:2387: auto remove_leader_with_forwarding_finishes::run_test_case()::(anonymous class)::operator()(environment<ExReg> &, ticker &) const: Assertion `std::holds_alternative<std::monostate>(result)' failed.
Aborting on shard 0.
Backtrace:
  0x2153b50
  0x2a0624d
  0x2a05e4c
  0x28526a4
  0x287e17e
  0x295fefc
  0x296015d
  0x295ff8a
  0x7f64f8820a1f
  /lib64/libc.so.6+0x3d2a1
  /lib64/libc.so.6+0x268a3
  /lib64/libc.so.6+0x26788
  /lib64/libc.so.6+0x35a15
  0x226741c
  0x22a2b7d
  0x22a28d8
  0x287152e
  0x287799e
  0x287c602
  0x287a171
  0x3701c61
  0x36ff7c5
  0x36d3b1d
  0x36d33b2
  0x36d3262
  0x36d2c22
  0x29b0cd9
  0x2c38f6b
  /lib64/libpthread.so.0+0x92a4
  /lib64/libc.so.6+0x100322
```

We can't decode the backtrace since the collected unit test binary is stripped (when will the fix reach master @benipeled?)

### PR DESCRIPTION
**Pull request by kbr-**
When `io_fiber` fetched a batch with a configuration that does not
contain this node, it would send the entries committed in this batch to
`applier_fiber` and proceed by any remaining entry dropping waiters (if
the node was no longer a leader).

If there were waiters for entries committed in this batch, it could
either happen that `applier_fiber` received and processed those entries
first, notifying the waiters that the entries were committed and/or
applied, or it could happen that `io_fiber` reaches the dropping waiters
code first, causing the waiters to be resolved with
`commit_status_unknown`.

The second scenario is undesirable. For example, when a follower tries
to remove the current leader from the configuration using
`modify_config`, if the second scenario happens, the follower will get
`commit_status_unknown` - this can happen even though there are no node
or network failures. In particular, this caused
`randomized_nemesis_test.remove_leader_with_forwarding_finishes` to fail
from time to time.

Fix it by serializing the notifying and dropping of waiters in a single
fiber - `applier_fiber`. We decided to move all management of waiters
into `applier_fiber`, because most of that management was already there
(there was already one `drop_waiters` call, and two `notify_waiters`
calls). Now, when `io_fiber` observes that we've been removed from the
config and no longer a leader, instead of dropping waiters, it sends a
message to `applier_fiber`. `applier_fiber` will drop waiters when
receiving that message.

Improve an existing test to reproduce this scenario more frequently.

Fixes #11235.

### CODE REVIEW

File: raft/server.cc [hunk 1]
```diff
@@ -115,7 +115,13 @@ class server_impl : public rpc_server, public server {
     condition_variable _applied_index_changed;
 
     struct stop_apply_fiber{}; // exception to send when apply fiber is needs to be stopepd
-    queue<std::variant<std::vector<log_entry_ptr>, snapshot_descriptor>> _apply_entries = queue<std::variant<std::vector<log_entry_ptr>, snapshot_descriptor>>(10);
+
+    struct removed_from_config{}; // sent to applier_fiber when we're not a leader and we're outside the current configuration
```
Comment (gleb-cloudius) [inline raft/server.cc:119]: Can we just move the check of  `_current_rpc_config.contains(_id)` to io fiber instead of introducing a new message. We never suppose to add nodes with the same id again. (But we probably do in the tests unfortunately).

File: raft/server.cc [hunk 2]
```diff
@@ -987,8 +997,8 @@ future<> server_impl::applier_fiber() {
         while (true) {
             auto v = co_await _apply_entries.pop_eventually();
 
-            if (std::holds_alternative<std::vector<log_entry_ptr>>(v)) {
-                auto& batch = std::get<0>(v);
+            if (auto* batch_opt = std::get_if<std::vector<log_entry_ptr>>(&v)) {
+                auto& batch = *batch_opt;
```
Comment (gleb-cloudius) [inline raft/server.cc:1001]: Why is this change?

File: raft/server.cc (hunk 1 above)
Comment (kbr-) [reply raft/server.cc:119]: Then you would still have the race that this PR is fixing, just at a different moment.
1. `io_fiber` sends the `batch.committed` entries
2. `io_fiber` updates `_current_rpc_config`
3. `applier_fiber` performs this check before fetching the message from step 1, drops the waiters.

File: raft/server.cc (hunk 2 above)
Comment (kbr-) [reply raft/server.cc:1001]: Using `get_if` is better than `holds_alternative`+`get`, because the latter performs two checks, one of them is redundant.

I used the better option - `get_if` - in the `else` branch. Then the code became inconsistent with this first `if`, so I changed this first `if` as well to make the code consistent.

File: raft/server.cc (hunk 1 above)
Comment (gleb-cloudius) [reply raft/server.cc:119]: You mean there may be more than one batch in the queue and applier will drop waiters before processing all of them? Yes, this probably can happen.

File: raft/server.cc (hunk 2 above)
Comment (gleb-cloudius) [reply raft/server.cc:1001]: I do not think that `get<0>` performs any checks at runtime.

Comment (gleb-cloudius) [reply raft/server.cc:1001]: I do not mind using visit but as a separate patch.

Comment (kbr-) [reply raft/server.cc:1001]: >  I do not think that get<0> performs any checks at runtime.

It does: https://en.cppreference.com/w/cpp/utility/variant/get

> Index-based value accessor: If v.index() == I, returns a reference to the value stored in v. Otherwise, throws [std::bad_variant_access](https://en.cppreference.com/w/cpp/utility/variant/bad_variant_access). The call is ill-formed if I is not a valid index in the variant.

Comment (gleb-cloudius) [reply raft/server.cc:1001]: OK, that it is still same to `ifs`. Either `holds_alternative` returns bool and we check it and then `get<>` does one more `if`. Or `get_if<>` does a check and then there is one more null comparison in the `if`. The point is if you want to change a style better to do it in a separate patch. Here just add another `if` and then you can move the whole thing to `visit`.

Comment (kbr-) [reply raft/server.cc:1001]: I would guess that the variant checks are some type of virtual calls, as std variants are implemented in terms of virtual calls, much more expensive than comparing a pointer to `null`.

Anyway, I will extract to separate patch.

Comment (gleb-cloudius) [reply raft/server.cc:1001]: Yes, variant has function table. Do we really care here?

Comment (kbr-) [reply raft/server.cc:1001]: Probably not.

File: test/raft/randomized_nemesis_test.cc [hunk 3]
```diff
@@ -2353,22 +2353,32 @@ SEASTAR_TEST_CASE(removed_follower_with_forwarding_learns_about_removal) {
...
+                // Tick each server with probability 1/10.
+                // Thus each server is ticked, on average, once every 10 timer/network ticks.
+                // On the other hand, we now have servers running at different speeds.
+                if (srv && dist(random_engine) == 0) {
+                    srv->tick();
+                }
+            });
             return ping_shards();
-        }, 10'000);
+        }, 20'000);
```
Comment (kostja) [inline test/raft/randomized_nemesis_test.cc:2381]: How much more wall clock time does it take now on your box?

File: raft/server.cc (hunk 1 above)
Comment (kostja) [reply raft/server.cc:119]: @gleb-cloudius it doesn't even take an extra batch, applier queue can contain snapshot descriptors as well. So just one batch and one snapshot descriptor.

**Review by kostja — APPROVED** [review]

**Review by kostja — APPROVED** [review]
Approved assuming test execution didn't increase too much.

File: test/raft/randomized_nemesis_test.cc (hunk 3 above)
Comment (kbr-) [reply test/raft/randomized_nemesis_test.cc:2381]: Variation too high to measure quickly whether there's a significant difference.
Example run in debug mode:
```
real    0m0.239s
user    0m0.071s
sys     0m0.050s
```

TBH most of the time is probably spent in seastar initialization anyway, the test is just too short.

File: raft/server.cc [hunk 4]
```diff
@@ -987,8 +987,8 @@ future<> server_impl::applier_fiber() {
         while (true) {
             auto v = co_await _apply_entries.pop_eventually();
 
-            if (std::holds_alternative<std::vector<log_entry_ptr>>(v)) {
-                auto& batch = std::get<0>(v);
+            if (auto* batch_opt = std::get_if<std::vector<log_entry_ptr>>(&v)) {
```
Comment (gleb-cloudius) [inline raft/server.cc:1000]: I thought we agree to move to `visitor`, no? As of `get_if` I do not mind either way, but, as previously discussed, I do not see what it improves (I counted the same amount of branches, and I certainly do not think it is more elegant) and if we will refactor each peace of code we touch to our preferred ways we will have a lot of useless back and forth patches. If there is no clear benefit just use the way the established code is already using.

Comment (kbr-) [reply raft/server.cc:1000]: > I thought we agree to move to visitor, no? 

You said you don't mind, but I'm not sure about the visitor, it might introduce some additional allocations (coroutine inside visitor lambda), so I think `get_if` option is safer.

> but, as previously discussed, I do not see what it improves (I counted the same amount of branches,

I think the `x != null` comparison is cheaper than the check `std::get` must make (but TBH I'm not sure).
Also the code is more obvious to me now, compared to `std::get<0>` (the `0`... meh)

I can remove the patch and use the old way if the change pains you too much.

Comment (gleb-cloudius) [reply raft/server.cc:1000]: For a new code I do not mind how we access a variant, but I do mind when a code that a developer touches is rewritten for its own liking just because he needs to touch it. `visitor` improves the situation because it lets you know it you missed a case, but your change is just cosmetic.

**Comment by kbr-** [comment]
v3:
- use `visit` instead of `get_if`.

**Comment by kbr-** [comment]
Now I noticed that the `visit` version may potentially introduce redundant calls to `signal_applied()` - previously it wouldn't be called if the received batch was empty, although that should never happen anyway, and the call is cheap.

**Comment by kbr-** [comment]
@tgrabiec please review.

**Review by gleb-cloudius — APPROVED** [review]
