### PR TITLE
raft topology: `wait_for_peers_to_enter_synchronize_state` doesn't need to resolve all IPs

### LINKED ISSUE #13543: Bootstrap is blocked in setup_group0 after failed replace when raft is enabled
When scylla is started with `--consistent-cluster-management=true` option, dtest replace_address_test.py::TestReplaceAddress::test_replace_node_no_hibernate_state fails:

https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/byo/job/dtest-byo/16/artifact/logs-full.release.000/1681692373272_replace_address_test.py%3A%3ATestReplaceAddress%3A%3Atest_replace_node_no_hibernate_state%5Buse_endpoint-rbo_disabled%5D/

Scenario:
1. Start a cluster with nodes node1, node2, node3
2. Start node4 replacing node node2
3. Stop node node4 after it joined group0 but before it advertised itself in gossip
4. Start node5 replacing node node2

Node 5 will hang trying to resolve IP of node4 (28b52cc9-9144-421f-b882-fe62f4ddc9c5): 

```
INFO  2023-04-17 00:36:05,801 [shard 0] raft_group0 - setup_group0: waiting for peers to synchronize state...
INFO  2023-04-17 00:36:05,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({4dee07a7-efa7-45b9-b36e-0c1238f10374, 28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:05,801 [shard 0] raft_group0_upgrade - : sleeping for 1s seconds before retrying...
INFO  2023-04-17 00:36:06,277 [shard 0] storage_service - Node 127.0.74.2 state jump to normal
INFO  2023-04-17 00:36:06,277 [shard 0] storage_service - Set host_id=5b39b175-8511-4da6-83ca-82aabca92868 to be owned by node=127.0.74.2
WARN  2023-04-17 00:36:06,277 [shard 0] gossip - Fail to send EchoMessage to 127.0.74.2: seastar::rpc::closed_error (connection is closed)
INFO  2023-04-17 00:36:06,278 [shard 0] gossip - InetAddress 127.0.74.1 is now UP, status = NORMAL
INFO  2023-04-17 00:36:06,278 [shard 0] gossip - InetAddress 127.0.74.3 is now UP, status = NORMAL
INFO  2023-04-17 00:36:06,278 [shard 0] storage_service - Set host_id=613f069a-7f54-4ce2-9243-e0d24061d799 to be owned by node=127.0.74.1
INFO  2023-04-17 00:36:06,281 [shard 0] storage_service - Set host_id=4dee07a7-efa7-45b9-b36e-0c1238f10374 to be owned by node=127.0.74.3
INFO  2023-04-17 00:36:06,287 [shard 0] migration_manager - Requesting schema pull from 127.0.74.1:0
INFO  2023-04-17 00:36:06,287 [shard 0] migration_manager - Pulling schema from 127.0.74.1:0
INFO  2023-04-17 00:36:06,289 [shard 0] migration_manager - Requesting schema pull from 127.0.74.3:0
INFO  2023-04-17 00:36:06,289 [shard 0] migration_manager - Pulling schema from 127.0.74.3:0
WARN  2023-04-17 00:36:06,290 [shard 0] migration_manager - Can't send migration request: node 127.0.74.2 is down.
INFO  2023-04-17 00:36:06,290 [shard 0] gossip - InetAddress 127.0.74.2 is now DOWN, status = shutdown
INFO  2023-04-17 00:36:06,294 [shard 0] compaction - [Compact system.peers d7057b60-dcb7-11ed-a472-7c9f20919656] Compacting [/jenkins/workspace/scylla-master/releng-testing/byo/dtest-byo/scylla/.dtest/dtest-36f3_4vf/test/node5/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-4-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/releng-testing/byo/dtest-byo/scylla/.dtest/dtest-36f3_4vf/test/node5/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-2-big-Data.db:level=0:origin=memtable]
INFO  2023-04-17 00:36:06,296 [shard 0] migration_manager - Requesting schema pull from 127.0.74.1:0
INFO  2023-04-17 00:36:06,303 [shard 0] schema_tables - Schema version changed to 4f531424-ed53-346a-90e2-634dabb858c7
INFO  2023-04-17 00:36:06,303 [shard 0] migration_manager - Schema merge with 127.0.74.1:0 completed
INFO  2023-04-17 00:36:06,303 [shard 0] migration_manager - Requesting schema pull from 127.0.74.3:0
INFO  2023-04-17 00:36:06,304 [shard 0] migration_manager - Pulling schema from 127.0.74.1:0
INFO  2023-04-17 00:36:06,313 [shard 0] raft_group_registry - marking Raft server 4dee07a7-efa7-45b9-b36e-0c1238f10374 as alive for raft groups
INFO  2023-04-17 00:36:06,314 [shard 0] raft_group_registry - marking Raft server 613f069a-7f54-4ce2-9243-e0d24061d799 as alive for raft groups
INFO  2023-04-17 00:36:06,315 [shard 0] schema_tables - Schema version changed to 4f531424-ed53-346a-90e2-634dabb858c7
INFO  2023-04-17 00:36:06,315 [shard 0] migration_manager - Schema merge with 127.0.74.3:0 completed
INFO  2023-04-17 00:36:06,315 [shard 0] migration_manager - Pulling schema from 127.0.74.3:0
INFO  2023-04-17 00:36:06,326 [shard 0] schema_tables - Schema version changed to 4f531424-ed53-346a-90e2-634dabb858c7
INFO  2023-04-17 00:36:06,326 [shard 0] migration_manager - Schema merge with 127.0.74.1:0 completed
INFO  2023-04-17 00:36:06,338 [shard 0] schema_tables - Schema version changed to 4f531424-ed53-346a-90e2-634dabb858c7
INFO  2023-04-17 00:36:06,338 [shard 0] migration_manager - Schema merge with 127.0.74.3:0 completed
INFO  2023-04-17 00:36:06,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:06,801 [shard 0] raft_group0_upgrade - : sleeping for 2s seconds before retrying...
INFO  2023-04-17 00:36:08,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:08,801 [shard 0] raft_group0_upgrade - : sleeping for 4s seconds before retrying...
INFO  2023-04-17 00:36:12,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:12,801 [shard 0] raft_group0_upgrade - : sleeping for 8s seconds before retrying...
INFO  2023-04-17 00:36:20,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:20,801 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:36:36,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:36,801 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:36:52,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:36:52,801 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:37:08,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:37:08,801 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:37:24,801 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:37:24,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:37:40,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:37:40,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:37:56,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:37:56,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:38:12,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:38:12,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:38:28,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:38:28,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:38:44,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:38:44,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:39:00,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:39:00,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:39:16,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
INFO  2023-04-17 00:39:16,802 [shard 0] raft_group0_upgrade - : sleeping for 16s seconds before retrying...
INFO  2023-04-17 00:39:32,802 [shard 0] raft_group0_upgrade - : failed to resolve IP addresses of some of the cluster members ({28b52cc9-9144-421f-b882-fe62f4ddc9c5})
```

node4:

```
INFO  2023-04-17 00:36:02,611 [shard 0] raft_group0 - setup_group0: joining group 0...
INFO  2023-04-17 00:36:02,611 [shard 0] raft_group0 - server 28b52cc9-9144-421f-b882-fe62f4ddc9c5 found no local group 0. Discovering...
INFO  2023-04-17 00:36:02,611 [shard 0] raft_group0 - server 28b52cc9-9144-421f-b882-fe62f4ddc9c5 found group 0 with group id 74a8f870-dcb7-11ed-89cf-5025f1624a62, leader 613f069a-7f54-4ce2-9243-e0d24061d799
INFO  2023-04-17 00:36:02,612 [shard 0] raft_group0 - Server 28b52cc9-9144-421f-b882-fe62f4ddc9c5 is starting group 0 with id 74a8f870-dcb7-11ed-89cf-5025f1624a62
INFO  2023-04-17 00:36:02,616 [shard 0] compaction - [Compact system.local d4d35920-dcb7-11ed-a784-54dbe388dc13] Compacted 2 sstables to [/jenkins/workspace/scylla-master/releng-testing/byo/dtest-byo/scylla/.dtest/dtest-36f3_4vf/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-6-big-Data.db:level=0]. 81kB to 40kB (~50% of original) in 5ms = 8MB/s. ~256 total partitions merged to 1.
INFO  2023-04-17 00:36:02,617 [shard 0] raft_group0 - server 28b52cc9-9144-421f-b882-fe62f4ddc9c5 joined group 0 with group id 74a8f870-dcb7-11ed-89cf-5025f1624a62
INFO  2023-04-17 00:36:02,617 [shard 0] raft_group0 - setup_group0: successfully joined group 0.
INFO  2023-04-17 00:36:02,617 [shard 0] raft_group0 - Replacing a node with Raft ID: 5b39b175-8511-4da6-83ca-82aabca92868, IP address: 127.0.74.2
INFO  2023-04-17 00:36:02,620 [shard 0] raft_group0 - setup_group0: ensuring that the cluster has fully upgraded to use Raft...
INFO  2023-04-17 00:36:02,661 [shard 0] compaction_manager - Asked to stop
WARN  2023-04-17 00:36:02,661 [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
INFO  2023-04-17 00:36:02,661 [shard 0] gossip - failure_detector_loop: Finished main loop
INFO  2023-04-17 00:36:02,662 [shard 0] init - Shutting down group 0 service
INFO  2023-04-17 00:36:02,662 [shard 0] compaction_manager - Stopped
INFO  2023-04-17 00:36:02,662 [shard 1] compaction_manager - Asked to stop
INFO  2023-04-17 00:36:02,662 [shard 1] compaction_manager - Stopped
```

Bystander node (node3) will see this:

```
INFO  2023-04-17 00:35:59,270 [shard 0] gossip - InetAddress 127.0.74.2 is now DOWN, status = shutdown
INFO  2023-04-17 00:36:02,114 [shard 0] raft_group_registry - marking Raft server 5b39b175-8511-4da6-83ca-82aabca92868 as dead for raft groups
WARN  2023-04-17 00:36:02,613 [shard 1] raft_group_registry - Raft server id 28b52cc9-9144-421f-b882-fe62f4ddc9c5 cannot be translated to an IP address.
WARN  2023-04-17 00:36:04,700 [shard 0] raft_group_registry - Raft server id 74ac19e5-16b3-40f9-b55a-b1b2b2478635 cannot be translated to an IP address.
INFO  2023-04-17 00:36:05,699 [shard 0] gossip - InetAddress 127.0.74.5 is now UP, status = UNKNOWN
INFO  2023-04-17 00:36:05,708 [shard 0] raft_group_registry - marking Raft server 74ac19e5-16b3-40f9-b55a-b1b2b2478635 as alive for raft groups
WARN  2023-04-17 00:41:02,678 [shard 1] raft_group_registry - (rate limiting dropped 2999 similar messages) Raft server id 28b52cc9-9144-421f-b882-fe62f4ddc9c5 cannot be translated to an IP address.
WARN  2023-04-17 00:46:02,744 [shard 1] raft_group_registry - (rate limiting dropped 2999 similar messages) Raft server id 28b52cc9-9144-421f-b882-fe62f4ddc9c5 cannot be translated to an IP address.
```

@kbr-scylla  @kostja

### PR DESCRIPTION
**Pull request by margdoc**
Another node can stop after it joined the group0 but before it advertised itself in gossip. `get_inet_addrs` will try to resolve all IPs and `wait_for_peers_to_enter_synchronize_state` will loop indefinitely.

But `wait_for_peers_to_enter_synchronize_state` can return early if one of the nodes confirms that the upgrade procedure has finished. For that, it doesn't need the IPs of all group 0 members - only the IP of some nodes which can do the confirmation.

This pr restructures the code so that IPs of nodes are resolved inside the `max_concurrent_for_each` that `wait_for_peers_to_enter_synchronize_state` performs. Then, even if some IPs won't be resolved, but one of the nodes confirms a successful upgrade, we can continue.

Fixes #13543

### CODE REVIEW

**Comment by margdoc** [comment]
@kbr-scylla please review

File: service/raft/raft_group0.cc [hunk 1]
```diff
@@ -1189,10 +1193,18 @@ static future<bool> wait_for_peers_to_enter_synchronize_state(
...
-                   std::vector<gms::inet_address> current_config,
+                   raft::config_member_set current_members_set, const group0_members& members0,
                    lw_shared_ptr<std::unordered_set<gms::inet_address>> entered_synchronize,
                    lw_shared_ptr<bool> retry, ::tracker<bool> tracker) -> future<> {
-            co_await max_concurrent_for_each(current_config, max_concurrency, [&] (const gms::inet_address& node) -> future<> {
+            co_await max_concurrent_for_each(current_members_set, max_concurrency, [&] (const raft::config_member& member) -> future<> {
+                auto node_opt = members0.get_inet_addr(member);
+
+                if (!node_opt.has_value()) {
+                    co_return;
```
Comment (kbr-scylla) [inline service/raft/raft_group0.cc:1203]: What will happen if some nodes return `synchronize` and we won't be able to resolve IPs for the rest of them?

Comment (margdoc) [reply service/raft/raft_group0.cc:1203]: Okay, now I see the problem. In this case, it will behave as if all node return `synchronize` and the function will return `true` instead of retrying. Is it enough to set `retry` to `true` if IP wasn't resolved?

Comment (kbr-scylla) [reply service/raft/raft_group0.cc:1203]: Yep, it should be enough. Then the behavior for that node will be the same as if we timed out trying to contact it.
Please also print a warning that we cannot resolve the IP of this node here in this branch. Something like:
```
upgrade_log.warn("wait_for_peers_to_enter_synchronize_state: cannot resolve the IP of {}", member);
```

**Review by kbr-scylla — COMMENTED** [review]
Please also add a test which simulates the behavior described by Tomek in https://github.com/scylladb/scylladb/issues/13543:

- boot 3 node cluster
- stop one of the nodes
- start replacing the node, but on the replaced node, enable an error injection which kills it after it joined group 0 but before it advertised itself in gossip
- then start replacing the node with another one

The new replace should finish correctly with this patch. (Without it, it should hang.)

File: test/topology_experimental_raft/test_topology_ops.py [hunk 2]
```diff
@@ -5,8 +5,13 @@
 #
 from test.pylib.scylla_cluster import ReplaceConfig
 from test.pylib.manager_client import ManagerClient
+<<<<<<< HEAD
```
Comment (kbr-scylla) [inline test/topology_experimental_raft/test_topology_ops.py:8]: Conflict markers

File: test/topology_experimental_raft/test_topology_ops.py [hunk 3]
```diff
@@ -39,3 +44,26 @@ async def test_topology_ops(request, manager: ManagerClient):
     logger.info(f"Decommissioning node {servers[1]}")
     await manager.decommission_node(servers[1].server_id)
     await check_token_ring_and_group0_consistency(manager)
+
+
+@pytest.mark.asyncio
+async def test_blocked_bootstrap(manager: ManagerClient):
```
Comment (kbr-scylla) [inline test/topology_experimental_raft/test_topology_ops.py:50]: Please write a comment
the information provided in commit message should be included here.

**Review by kbr-scylla — CHANGES_REQUESTED** [review]
Some submodule updates have sneaked in, and there are merge conflicts with `master`

File: service/raft/raft_group0.cc [hunk 4]
```diff
@@ -592,6 +592,10 @@ future<> raft_group0::setup_group0(
     // Perform a Raft read barrier so we know the set of group 0 members and our group 0 state is up-to-date.
     co_await group0_server.read_barrier(&_abort_source);
 
+    utils::get_local_injector().inject("stop_after_joining_group0", [&] {
+        _abort_source.request_abort();
```
Comment (kbr-scylla) [inline service/raft/raft_group0.cc:596]: This won't cause the execution to stop here, it will proceed until the next usage of `_abort_source`.
Better to `throw runtime_error` or something.

Comment (kbr-scylla) [reply service/raft/raft_group0.cc:596]: Also, why do it here, and not immediately after `co_await join_group0(...)`?

Comment (margdoc) [reply service/raft/raft_group0.cc:596]: > Also, why do it here, and not immediately after co_await join_group0(...)?

Without specific reason, I made it here to match logs from #13543.

File: service/raft/raft_group0.cc (hunk 1 above)
Comment (margdoc) [reply service/raft/raft_group0.cc:1209]: Done.

**Comment by margdoc** [comment]
v3:
* Fixed rebasing artefacts
* Added the comment to the test

File: test/topology_experimental_raft/test_topology_ops.py (hunk 3 above)
Comment (margdoc) [reply test/topology_experimental_raft/test_topology_ops.py:58]: Done.

File: test/topology_experimental_raft/test_topology_ops.py (hunk 2 above)
Comment (margdoc) [reply test/topology_experimental_raft/test_topology_ops.py]: Done.

**Comment by margdoc** [comment]
v4:
* Rebased on master

File: service/raft/raft_group0.cc [hunk 5]
```diff
@@ -1209,10 +1213,20 @@ static future<bool> wait_for_peers_to_enter_synchronize_state(
         }
 
         (void) [] (netw::messaging_service& ms, abort_source& as, gate::holder pause_shutdown,
-                   std::vector<gms::inet_address> current_config,
+                   raft::config_member_set current_members_set, const group0_members& members0,
```
Comment (kbr-scylla) [inline service/raft/raft_group0.cc:1220]: There's one more problem here - sorry, I didn't notice it earlier, I would have pointed out in review otherwise.
(But to be fair you didn't notice it too :P)

Namely, `members0` is a reference to a variable which may be gone by the time that this lambda executes for some of the nodes, so we'll have use-after-free.
That's why we use `lw_shared_ptr` for things like `entered_synchronize` and copied `current_config` (you also copy `current_members_set` which is correct).

`netw::messaging_service& ms, abort_source& as` don't have this problem because they are kept alive by `gate::holder pause_shutdown`, but `const group0_members&` is not protected in this way because the variable is local in `setup_group0`.

I think we can easily fix that by passing `group0_members` by value (the structure consists of two references to services also protected by `pause_shutdown`). Ugly but works.

File: test/topology_experimental_raft/test_topology_ops.py [hunk 6]
```diff
@@ -71,3 +71,39 @@ async def new_gen_appeared() -> Optional[set[datetime]]:
     logger.info(f"Decommissioning node {servers[0]}")
     await manager.decommission_node(servers[0].server_id)
     await check_token_ring_and_group0_consistency(manager)
+
+# Scenario:
```
Comment (kbr-scylla) [inline test/topology_experimental_raft/test_topology_ops.py:75]: The standard way to do it is in Python docstring. (See e.g. the test above.)

File: service/raft/raft_group0.cc (hunk 4 above)
Comment (margdoc) [reply service/raft/raft_group0.cc]: Done. (both comments)

**Comment by margdoc** [comment]
v5:
* `abort_source` -> `runtime_exception`
* abort node after `co_await join_group0(...)`
* python comment -> python docstring comment
* `assert False` moved to `else` and added a message to it
* pass `group0_members` by value

**Review by kbr-scylla — APPROVED** [review]

**Comment by margdoc** [comment]
v6 (after failed CI):
* moved the test to the new file and added it to skipped tests in the release (test uses `error_injections_at_startup`)
