### PR TITLE
raft: improve group 0 reconfiguration failure handling

### LINKED ISSUE #11723: Failure of `remove_from_group0` in `storage_service::removenode` is not handled correctly
This is how `storage_service::removenode` looks like:
```cpp
            try {

                // ... start removenode, do steps 1 through 5 ...

                // Step 6: Finish
                req.cmd = node_ops_cmd::removenode_done;
                parallel_for_each(nodes, [&ss, &req, uuid] (const gms::inet_address& node) {
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got done response from node={}", uuid, node);
                        return make_ready_future<>();
                    });
                }).get();

                slogger.info("removenode[{}]: removing node {} from group 0", uuid, endpoint);
                assert(ss._group0);
                ss._group0->remove_from_group0(endpoint).get();
                slogger.info("removenode[{}]: node {} removed from group 0", uuid, endpoint);

                slogger.info("removenode[{}]: Finished removenode operation, removing node={}, sync_nodes={}, ignore_nodes={}", uuid, endpoint, nodes, ignore_nodes);
            } catch (...) {
                // we need to revert the effect of prepare verb the removenode ops is failed
                req.cmd = node_ops_cmd::removenode_abort;
                parallel_for_each(nodes, [&ss, &req, &nodes_unknown_verb, &nodes_down, uuid] (const gms::inet_address& node) {
                    if (nodes_unknown_verb.contains(node) || nodes_down.contains(node)) {
                        // No need to revert previous prepare cmd for those who do not apply prepare cmd.
                        return make_ready_future<>();
                    }
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got abort response from node={}", uuid, node);
                    });
                }).get();
                slogger.info("removenode[{}]: Aborted removenode operation, removing node={}, sync_nodes={}, ignore_nodes={}", uuid, endpoint, nodes, ignore_nodes);
                throw;
            }
```

As we can see, the `remove_from_group0` step happens after the "Finish" step.
If `remove_from_group0` throws an exception, the exception handler will send a `node_ops_cmd::removenode_abort` message to other nodes. The other nodes will have already cleared their knowledge about this operation by now (due to the Finish step) and they will reject the message.

`remove_from_group0` should either happen before the Finish step or it should be moved out of the try...catch.

EDIT: design doc for fixing the problems with error handling in `removenode` and `decommission`:
https://docs.google.com/document/d/1Gvy2_ZezCa2XY5li05umOznIwjvIYFGmYpeZQg5RbZM/

### PR DESCRIPTION
**Pull request by kbr-scylla**
Make it so that failures in `removenode`/`decommission` don't lead to reduced availability, and any leftovers in group 0 can be removed by `removenode`:
- In `removenode`, make the node a non-voter before removing it from the token ring. This removes the possibility of having a group 0 voting member which doesn't correspond to a token ring member. We can still be left with a non-voter, but that's doesn't reduce the availability of group 0.
- As above but for `decommission`.
- Make it possible to remove group 0 members that don't correspond to token ring members from group 0 using `removenode`. 
- Add an API to query the current group 0 configuration.

Fixes #11723.

### CODE REVIEW

**Comment by kbr-scylla** [comment]
I'll add a commit for the docs tomorrow.

Request to reviewers: please review this promptly, it's important for Raft GA release in 5.2 which is planned to be branched next week.

**Comment by kbr-scylla** [comment]
```
[2023-01-11T20:53:31.926Z] clang++ -MD -MT build/release/gen/rust/wasmtime_bindings.o -MF build/release/gen/rust/wasmtime_bindings.o.d -I/jenkins/workspace/releng/Scylla-CI/scylla/seastar/include -I/jenkins/workspace/releng/Scylla-CI/scylla/build/release/seastar/gen/include -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -march=westmere -Werror=unused-result -DSEASTAR_API_LEVEL=6 -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_HAVE_DPDK -DFMT_SHARED -DSEASTAR_BROKEN_SOURCE_LOCATION -I/usr/include/p11-kit-1 -Wl,--gc-sections -ffunction-sections -fdata-sections  -O3 -mllvm -inline-threshold=2500 -fno-slp-vectorize -DSCYLLA_BUILD_MODE=release -g -gz -iquote. -iquote build/release/gen --std=gnu++20  -ffile-prefix-map=/jenkins/workspace/releng/Scylla-CI/scylla=.  -march=westmere -DBOOST_TEST_DYN_LINK   -DNOMINMAX -DNOMINMAX -fvisibility=hidden  -Wall -Werror -Wno-mismatched-tags -Wno-tautological-compare -Wno-parentheses-equality -Wno-c++11-narrowing -Wno-sometimes-uninitialized -Wno-return-stack-address -Wno-missing-braces -Wno-unused-lambda-capture -Wno-overflow -Wno-noexcept-type -Wno-error=cpp -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-unused-command-line-argument -Wno-defaulted-function-deleted -Wno-redeclared-class-member -Wno-unsupported-friend -Wno-unused-variable -Wno-delete-non-abstract-non-virtual-dtor -Wno-braced-scalar-init -Wno-implicit-int-float-conversion -Wno-delete-abstract-non-virtual-dtor -Wno-uninitialized-const-reference -Wno-psabi -Wno-narrowing -Wno-array-bounds -Wno-nonnull -Wno-uninitialized -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN -DFMT_DEPRECATED_OSTREAM -DHAVE_LZ4_COMPRESS_DEFAULT  -c -o build/release/gen/rust/wasmtime_bindings.o build/release/gen/rust/wasmtime_bindings.cc
[2023-01-11T20:53:31.926Z] build/release/gen/rust/wasmtime_bindings.cc:1:10: fatal error: 'rust/cxx.h' file not found
[2023-01-11T20:53:31.926Z] #include "rust/cxx.h"
[2023-01-11T20:53:31.926Z]          ^~~~~~~~~~~~
[2023-01-11T20:53:31.926Z] 1 error generated.
```
I think this was fixed on `master`, rebase should help

File: service/storage_service.cc [hunk 1]
```diff
@@ -2344,19 +2344,54 @@ future<> storage_service::removenode(locator::host_id host_id, std::list<locator
...
+                const std::string message = format(
+                    "removenode[{}]: Rejected removenode operation (node={}); "
+                    "the node being removed is alive, maybe you should use decommission instead?",
+                    uuid, *endpoint_opt);
+                slogger.warn(std::string_view(message));
+                throw std::runtime_error(message);
             }
+
+            bool removed_from_token_ring = !endpoint_opt;
+        if (endpoint_opt) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:2416]: Forgot to fix indentation here, will add a commit after first round of review.

File: test/topology_raft_disabled/test_raft_upgrade.py [hunk 2]
```diff
@@ -176,49 +176,6 @@ async def test_raft_upgrade_basic(manager: ManagerClient, random_tables: RandomT
     assert(table.full_name in rs[0].description)
 
 
-@pytest.mark.asyncio
```
Comment (gleb-cloudius) [inline test/topology_raft_disabled/test_raft_upgrade.py:179]: I the document in the commit message public? Does it make sense to link to google docs at all?

File: service/raft/raft_group0.cc [hunk 3]
```diff
@@ -671,6 +671,30 @@ future<> raft_group0::finish_setup_after_join() {
     });
 }
 
+future<> raft_group0::become_nonvoter() {
```
Comment (gleb-cloudius) [inline service/raft/raft_group0.cc:691]: Typo: "If the procedure fails before after step..."

Comment (gleb-cloudius) [reply service/raft/raft_group0.cc:691]: Why `become_nonvoter()` does not call `make_nonvoter() ` with itself?

File: service/storage_service.cc [hunk 4]
```diff
@@ -2015,13 +2018,27 @@ future<> storage_service::decommission() {
                     heartbeat_updater.get();
                 });
 
-                // Step 5: Start to sync data
+                // Step 4: Start to sync data
```
Comment (gleb-cloudius) [inline service/storage_service.cc:2031]: Looks like numbering steps is as bad idea as line numbers in Basic.

File: api/api-doc/raft_group0.json [hunk 5]
```diff
@@ -0,0 +1,63 @@
+{
```
Comment (gleb-cloudius) [inline api/api-doc/raft_group0.json:1]: Better to implement https://github.com/scylladb/scylladb/issues/12008 instead adding new rest apis.

**Review by gleb-cloudius — COMMENTED** [review]
Nitpicks mostly except API comment.

File: test/topology_raft_disabled/test_raft_upgrade.py (hunk 2 above)
Comment (kbr-scylla) [reply test/topology_raft_disabled/test_raft_upgrade.py:179]: It's shared with ScyllaDB group. I think it doesn't hurt to add the link.

File: service/raft/raft_group0.cc (hunk 3 above)
Comment (kbr-scylla) [reply service/raft/raft_group0.cc:691]: The only practical difference between these functions is the logging events. `become_nonvoter` talks about "me" (this node), `make_nonvoter` talks about "them" (a different node). The common part which does the actual config change is already extracted to a separate private function, `make_raft_config_nonvoter`.

File: api/api-doc/raft_group0.json (hunk 5 above)
Comment (kbr-scylla) [reply api/api-doc/raft_group0.json:1]: #12008 is not a trivial project - the proposed table would contain all Raft groups and more information than just configuration. I'm also not familiar with the virtual table API that well. It would take me some time, which we don't have before the 5.2 release, to do it. The REST API doesn't hurt and it solves the current problem. I think we should avoid scope creep and keep this PR focused.

Comment (gleb-cloudius) [reply api/api-doc/raft_group0.json:1]: It may start as one group (that all we have anyways for now). I do not know much about virtual tables either, but we have a bunch so the infra should be in place to create more.

File: test/topology_raft_disabled/test_raft_upgrade.py (hunk 2 above)
Comment (gleb-cloudius) [reply test/topology_raft_disabled/test_raft_upgrade.py:179]: It does not, but imagine the annoyance of someone theoretical who read the commit message but cannot read the doc.

**Comment by kbr-scylla** [comment]
Fixed typo in log message, causing formatting errors.
```
ERROR 2023-01-12 13:05:21,201 [shard 0] storage_service - service/storage_service.cc:2091 @operator(): failed to log message: fmt='decommission[{}}: left Raft group 0': fmt::v9::format_error (unmatched '}' in format string)
```

**Comment by kbr-scylla** [comment]
@asias @kostja @avikivity @tgrabiec ping, please review.

I'm working on a table for fetching raft config instead of the rest api, but the rest of the PR can be reviewed.

File: service/raft/raft_group0.cc [hunk 6]
```diff
@@ -87,6 +87,10 @@ namespace service {
 static logging::logger group0_log("raft_group0");
 static logging::logger upgrade_log("raft_group0_upgrade");
 
+// TODO: change the links from master to stable/5.2 after 5.2 is released
+static const auto raft_upgrade_doc = "https://docs.scylladb.com/master/architecture/raft.html#verifying-that-the-internal-raft-upgrade-procedure-finished-successfully";
```
Comment (tgrabiec) [inline service/raft/raft_group0.cc:91]: Shouldn't we change it to 5.2 before 5.2 is released, so that the 5.2 binary refers to the "5.2" path? Should this depend on a variable set by the build system? It will become stale if it requires a manual process.

Comment (kbr-scylla) [reply service/raft/raft_group0.cc:91]: You mean before we branch? I was planning to change it after we branch, on the 5.2 branch.
But maybe it makes sense to change it right now... Although currently the link works, if I change it to refer to non-existing (yet) path it will stop working.

Also, I don't actually know what the path will be :D right now we only have `stable` and `master`, where `stable` corresponds to 5.1, but once we release 5.2, I don't know what it will be. cc @annastuchlik 

Making it depend on a build system variable would be an interesting solution... Although we don't have the necessary scaffolding to do stuff like this right now.

**Comment by kbr-scylla** [comment]
v2:
- rebased on `master`
- added a new commit to fix indentation in `removenode`
- removed the `api: add API to query Raft group 0 configuration` commit. Instead there is `db: system_keyspace: add a virtual table with raft configuration` (preceded with `db: system_keyspace: improve system.raft_snapshot_config schema` to make the schemas match)
- update the test to use the new table instead of the rest api.

File: service/raft/raft_group0.cc (hunk 6 above)
Comment (tgrabiec) [reply service/raft/raft_group0.cc:91]: We shouldn't change it to 5.2 before branching, of course. We should change it on 5.2 before releasing it. 

But I think we also should have an automated process which makes sure one you commit something to master and we branch, say 5.2, the code built from 5.2 will refer to the documentation for 5.2.

**Review by tgrabiec — APPROVED** [review]

File: service/raft/raft_group0.cc [hunk 7]
```diff
@@ -669,70 +669,8 @@ future<> raft_group0::finish_setup_after_join() {
...
-        group0_log.info("leave_group0: waiting until cluster fully upgrades to use Raft before proceeding...");
-        co_await _client.wait_until_group0_upgraded(_abort_source);
-        group0_log.info("leave_group0: cluster finished upgrade, continuing.");
-    }
-
-    // We're fully upgraded, we must have joined group 0.
-    if (!joined_group0()) {
-        on_internal_error(group0_log,
-            "leave_group0: we're fully upgraded to use Raft but didn't join group 0. Please report a bug.");
+    if (!(co_await raft_upgraded())) {
```
Comment (kostja) [inline service/raft/raft_group0.cc:708]: Sorry to bikeshed but I think English is playing a nasty trick here. The name is ambiguous - are we waiting for the non-raft cluster to upgrade to raft, or a raft cluster to upgrade to a better raft ? The name implies the second. I think raft_upgrade_complete() is less ambiguous, or upgrade_to_raft_complete(), or something along these lines.

File: service/raft/raft_group0.cc (hunk 6 above)
Comment (kostja) [reply service/raft/raft_group0.cc:91]: https://docs.scylladb.com/stable/upgrade/ is a fairly stable link, but I wouldn't even use that. "Scylla release upgrade procedure" is easy to google and is more likely to stay relevant over time.

File: test/topology_raft_disabled/test_raft_upgrade.py (hunk 2 above)
Comment (kostja) [reply test/topology_raft_disabled/test_raft_upgrade.py:179]: I also happen to think it's better to put a link to apublic document. It's easy to add the text of the document to the issue or to a github wiki. It's approved now, and will likely stay frozen forever.

**Review by kostja — COMMENTED** [review]
https://docs.google.com/document/d/1Gvy2_ZezCa2XY5li05umOznIwjvIYFGmYpeZQg5RbZM/ - we could add this link to the github issue as a comment or as a wiki to avoid links to internal google doc. Alternatively, you could just copy the relevant bits into the commit comment and avoid the link altogether.

File: service/storage_service.cc [hunk 8]
```diff
@@ -2015,13 +2018,27 @@ future<> storage_service::decommission() {
...
+                // Step 5: Become a group 0 non-voter before leaving the token ring.
+                //
+                // Thanks to this, even if we fail after leaving the token ring but before leaving group 0,
+                // group 0's availability won't be reduced.
+                if (raft_available) {
+                    slogger.info("decommission[{}]: becoming a group 0 non-voter", uuid);
+                    ss._group0->become_nonvoter().get();
+                    slogger.info("decommission[{}]: became a group 0 non-voter", uuid);
+                }
+
```
Comment (kostja) [inline service/storage_service.cc:2045]: If we crash at this step, can decommission get reverted and we stay a non-voter forever?

File: service/raft/raft_group0.cc [hunk 9]
```diff
@@ -776,6 +776,10 @@ future<bool> raft_group0::wait_for_raft() {
             "We're fully upgraded to use Raft but didn't join group 0. Please report a bug.");
     }
 
+    group0_log.info("Performing a group 0 read barrier...");
+    co_await _raft_gr.group0().read_barrier(&_abort_source);
```
Comment (kostja) [inline service/raft/raft_group0.cc:789]: I believe this was explicitly avoided before since we wanted the nodes to restart successfully in absence of a majority. I think we even have dtests for it. @gleb-cloudius

Comment (gleb-cloudius) [reply service/raft/raft_group0.cc:789]: Yes. Good catch. I am not sure we have a test, but if we do not we should have one. It is fine to call the barrier during 'removenode' operation though before accessing the config.

File: service/storage_service.cc (hunk 8 above)
Comment (asias) [reply service/storage_service.cc:2045]: If we crash here, the user can restart the node, the node will still be part of the ring. Will the raft code during restart, make the node a voter again?

File: service/storage_service.cc [hunk 10]
```diff
@@ -2368,7 +2383,20 @@ future<> storage_service::removenode(locator::host_id host_id, std::list<locator
...
+            // but before removing it group 0, group 0's availability won't be reduced.
+            assert(ss._group0);
+            auto raft_id = raft::server_id{host_id.uuid()};
+            bool raft_available = ss._group0->wait_for_raft().get();
+            if (raft_available) {
+                slogger.info("removenode[{}]: making node {} a non-voter in group 0", uuid, raft_id);
+                ss._group0->make_nonvoter(raft_id).get();
+                slogger.info("removenode[{}]: made node {} a non-voter in group 0", uuid, raft_id);
+            }
+
```
Comment (asias) [inline service/storage_service.cc:2419]: In decommission, we make the node non-voter after sync data, here in removenode, we do this before sync data. Can we make they behave the same, i.e., making it non-voter after sync data? The step to sync data takes most of the time and has the best chance to fail.

File: service/storage_service.cc [hunk 11]
```diff
@@ -2413,12 +2441,12 @@ future<> storage_service::removenode(locator::host_id host_id, std::list<locator
                 }).get();
 
 
-                // Step 5: Announce the node has left
+                // Step 6: Announce the node has left
```
Comment (asias) [inline service/storage_service.cc]: I.e., call ```ss._group0->make_nonvoter(raft_id).get()``` right before this step.

File: service/storage_service.cc (hunk 8 above)
Comment (kbr-scylla) [reply service/storage_service.cc:2045]: The node will become a voter again during restart, yes.

File: service/raft/raft_group0.cc (hunk 9 above)
Comment (kbr-scylla) [reply service/raft/raft_group0.cc:789]: `wait_for_raft` is not called during restart.

File: service/storage_service.cc (hunk 10 above)
Comment (kbr-scylla) [reply service/storage_service.cc:2419]: I did this on purpose, `removenode` assumes that the node is dead, so it's desirable to make the dead node a non-voter as soon as possible so we improve group 0's availability. There's no upside to keeping it as a voter for the duration of data sync. In `decommission` the situation is different, we're still alive, so it's desirable for us to keep being a voter until the last moment.

File: service/raft/raft_group0.cc (hunk 6 above)
Comment (kbr-scylla) [reply service/raft/raft_group0.cc:91]: Except "Scylla release upgrade procedure" is not what the link is pointing to, you could google "scylla internal raft upgrade", you can find https://docs.scylladb.com/stable/architecture/raft.html this way but it's not the first link and it's not pointing to the exact section that I wanted to point to here.

File: service/storage_service.cc (hunk 8 above)
Comment (asias) [reply service/storage_service.cc:2045]: Good.

Comment (asias) [reply service/storage_service.cc:2045]: There is another tool we can use to revert the non-voter to voter in case of failure. 

There is a abort function attached to each node_ops_meta_data. The abort function will be called automatically if the decommission node does not update in a timrly manager (like a watchdog) to revert the decommission ops.

Perhaps we can call 'add the decommission node to a voter' in the abort function. This way, the decommission node will become voter automatically without user's operation. 

But on the other hand, without restarting the decommission node, it does not really matter if the decommission node is a voter or a non-voter, since we need to restart the decommission node to make it work properly again anyway. 

```
            auto meta = node_ops_meta_data(ops_uuid, coordinator, std::move(req.ignore_nodes), [this, coordinator, req = std::move(req)] () mutable {
                return mutate_token_metadata([this, coordinator, req = std::move(req)] (mutable_token_metadata_ptr tmptr) mutable {
                    for (auto& node : req.leaving_nodes) {
                        slogger.info("decommission[{}]: Removed node={} as leaving node, coordinator={}", req.ops_uuid, node, coordinator);
                        tmptr->del_leaving_endpoint(node);
                    }
                    return update_pending_ranges(tmptr, format("decommission {}", req.leaving_nodes)); 
                }); 
            },
            [this, ops_uuid] () mutable { node_ops_singal_abort(ops_uuid); });
            _node_ops.emplace(ops_uuid, std::move(meta));
```

Comment (kbr-scylla) [reply service/storage_service.cc:2045]: > But on the other hand, without restarting the decommission node, it does not really matter if the decommission node is a voter or a non-voter, since we need to restart the decommission node to make it work properly again anyway.


This.

And it can actually be considered a good thing that it is a non-voter while it is down.

File: db/system_keyspace.cc [hunk 12]
```diff
@@ -2647,10 +2648,120 @@ class clients_table : public streaming_virtual_table {
...
+        auto id = generate_legacy_id(system_keyspace::NAME, "raft_config");
+        return schema_builder(system_keyspace::NAME, "raft_config", std::make_optional(id))
+            .with_column("group_id", timeuuid_type, column_kind::partition_key)
+            .with_column("disposition", ascii_type, column_kind::clustering_key) // can be 'CURRENT` or `PREVIOUS'
+            .with_column("server_id", uuid_type, column_kind::clustering_key)
+            .with_column("can_vote", boolean_type)
+            .set_comment("Currently operating RAFT configuration")
+            .with_version(system_keyspace::generate_schema_version(id))
+            .build();
+    }
```
Comment (gleb-cloudius) [inline db/system_keyspace.cc:2731]: As suggested in https://github.com/scylladb/scylladb/issues/12008 we will want to include more info (such as current term, leader etc) info this table. We may skip it for now but we have to have a plan how we will do it later. So what is the plan? Static columns?

Comment (kbr-scylla) [reply db/system_keyspace.cc:2731]: I was thinking static column too. Current term and leader need only a single row.
Also maybe `raft_config` is not an appropriate name if we want to include this info in the future (current term and leader are not part of the configuration if we want to use precise terminology). We could use something more generic like `raft_group_info`. Although using `raft_config` is not that a big problem.

Comment (gleb-cloudius) [reply db/system_keyspace.cc:2731]: For someone who does not know raft internals `raft_config` should not be confusing, though may be `raft_state` would be better.

**Review by gleb-cloudius — APPROVED** [review]

File: db/system_keyspace.cc (hunk 12 above)
Comment (kbr-scylla) [reply db/system_keyspace.cc:2731]: "state" is on the other hand too generic to me, arguably the raft log is also part of the state (for example), but it's kept in a separate table.

Meh, let's just keep it as `raft_config`.

File: service/raft/raft_group0.cc (hunk 6 above)
Comment (annastuchlik) [reply service/raft/raft_group0.cc:91]: @kbr-scylla `stable `is and should always be the latest released stable version. As soon as we release 5.2, I'm going to change the configuration so that `stable` (default) is 5.2.

File: db/system_keyspace.cc (hunk 12 above)
Comment (gleb-cloudius) [reply db/system_keyspace.cc:2731]: Raft log *is* part of the state and one of the things I want to add to the table is its length in entries and bytes :)

Those other tables have different purpose. They are persisting the state of the raft needed for it to work. They are not for users to look at and may eventually be removed in favor of persisting directly in the commitlog.

I do not insist on the name though.

File: service/storage_service.cc (hunk 11 above)
Comment (kbr-scylla) [reply service/storage_service.cc]: See my answer above, I want `make_nonvoter` to happen early in `removenode`.

File: service/raft/raft_group0.cc (hunk 6 above)
Comment (kbr-scylla) [reply service/raft/raft_group0.cc:91]: We'll change this link to use `stable` after branching then.

**Comment by kbr-scylla** [comment]
v3:
- rename `raft_upgraded` to `raft_upgrade_complete`
- remove link to internal doc from commit message
- rename `raft_config` to `raft_state`, since we plan to extend this table in the future with more information. Write a comment at the definition of `raft_state_table`.

File: db/system_keyspace.cc (hunk 12 above)
Comment (kbr-scylla) [reply db/system_keyspace.cc:2734]: Renamed to `raft_state` after all.

File: service/raft/raft_group0.cc (hunk 7 above)
Comment (kbr-scylla) [reply service/raft/raft_group0.cc:696]: Renamed to `raft_upgrade_complete`.

**Comment by kbr-scylla** [comment]
> https://docs.google.com/document/d/1Gvy2_ZezCa2XY5li05umOznIwjvIYFGmYpeZQg5RbZM/ - we could add this link to the github issue as a comment or as a wiki to avoid links to internal google doc. Alternatively, you could just copy the relevant bits into the commit comment and avoid the link altogether.

Added the link to issue https://github.com/scylladb/scylladb/issues/11723, removed from commit message and cover letter.

**Comment by kbr-scylla** [comment]
Failed to do a function rename fully, fixed.

File: service/raft/raft_group0.cc (hunk 9 above)
Comment (kostja) [reply service/raft/raft_group0.cc:789]: checked the code, this is the case indeed.

**Review by kostja — APPROVED** [review]

**Comment by tgrabiec** [comment]
Conflicts, please rebase.

File: service/storage_service.cc (hunk 10 above)
Comment (asias) [reply service/storage_service.cc:2419]: OK. Another point is that it is not a big deal even if we make the node leaving as non voter in case of failure.

**Comment by kbr-scylla** [comment]
I rebased on current `next` because there's a conflict with Benny's patch, and I want CI to start running ASAP so we can queue this today

File: service/storage_service.cc [hunk 13]
```diff
@@ -2087,10 +2098,33 @@ future<> storage_service::decommission() {
...
-                slogger.info("DECOMMISSIONING: leaving Raft group 0");
-                ss._group0->leave_group0().get();
-                slogger.info("DECOMMISSIONING: left Raft group 0");
+            // Step 8: Leave group 0
+            //
+            // If the node failed to leave the token ring, don't remove it from group 0
+            // --- hence the `left_token_ring` check.
+            std::exception_ptr leave_group0_ex;
+            try {
+                if (raft_available && left_token_ring) {
```
Comment (tgrabiec) [inline service/storage_service.cc:2110]: Isn't left_token_ring always true here? If we didn't leave the ring, we will exit via throwing.
