### PR TITLE
Fix heart_beat_state::force_highest_possible_version_unsafe

### LINKED ISSUE #13801: `endpoint=127.138.100.38 is not marked for removal but owns no tokens` in `test_mutation_schema_change`
Weird failure of one of topology tests:

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1069/artifact/testlog/x86_64/dev/topology.test_mutation_schema_change.1.log
```python3
    async def test_mutation_schema_change(manager, random_tables):
        """
            Cluster A, B, C
            create table
            stop C
            change schema + do lwt write + change schema
            stop B
            start C
            do lwt write to the same key through C
        """
        server_a, server_b, server_c = await manager.running_servers()
        t = await random_tables.add_table(ncolumns=5, pks=1)
        manager.driver_close()
        # Reduce the snapshot thresholds
        await manager.mark_dirty()
        errs = [inject_error_one_shot(manager.api, s.ip_addr, 'raft_server_snapshot_reduce_threshold')
                for s in [server_a, server_b, server_c]]
        await asyncio.gather(*errs)
    
    
        logger.info("Stopping C %s", server_c)
        await manager.server_stop_gracefully(server_c.server_id)
        await manager.driver_connect()
    
>       async with inject_error(manager.api, server_b.ip_addr, 'paxos_error_before_learn'):
```

The `inject_error` call happened because the connection was dropped:
```
E               aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

I looked into the logs, and it turns out that the server had crashed:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1069/artifact/testlog/x86_64/dev/scylla-59.log
```
ERROR 2023-05-05 18:08:02,779 [shard 0] storage_service - endpoint=127.138.100.38 is not marked for removal but owns no tokens, at: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x527f9e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x528580 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x528898 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x37e983 0x21f67fa 0x21fe4fc 0x22018e3 0x20e673e 0x20ffc17 0x20ce226 0x20f301f 0xfc59fd /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3c7d7f /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3c8f47 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3c8369 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x34198e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x340b9e 0xf5ec1f 0xf97e10 0xf5dc5b /lib64/libc.so.6+0x2750f /lib64/libc.so.6+0x275c8 0xf5c7e4
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::coroutine::parallel_for_each<gms::gossiper::apply_state_locally(std::map<gms::inet_address, gms::endpoint_state, std::less<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, gms::endpoint_state> > >)::$_16>
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0.
Backtrace:
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3b964c
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3e42e2
  /lib64/libc.so.6+0x3cb1f
  /lib64/libc.so.6+0x8ce5b
  /lib64/libc.so.6+0x3ca75
  /lib64/libc.so.6+0x267fb
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x37ea0b
  0x21f67fa
  0x21fe4fc
  0x22018e3
  0x20e673e
  0x20ffc17
  0x20ce226
  0x20f301f
  0xfc59fd
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3c7d7f
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3c8f47
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3c8369
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x34198e
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x340b9e
  0xf5ec1f
  0xf97e10
  0xf5dc5b
  /lib64/libc.so.6+0x2750f
  /lib64/libc.so.6+0x275c8
  0xf5c7e4
------ Ending test dev/topology.test_mutation_schema_change.1::test_mutation_schema_change ------
```

It's a weird failure because the test performed no topology changes other than bootstrapping the initial 3 nodes before the crash.

Server logs and test log:
[dev.zip](https://github.com/scylladb/scylladb/files/11419103/dev.zip)

Test framework log:
[test.py.debug-release-dev-1069.log](https://github.com/scylladb/scylladb/files/11419118/test.py.debug-release-dev-1069.log)

### PR DESCRIPTION
**Pull request by bhalevy**
It turns out that numeric_limits defines an implicit implementation
for std::numeric_limits<utils::tagged_integer<Tag, ValueType>>
which apprently returns a default-constructed tagged_integer
for min() and max(), and this broke
`gms::heart_beat_state::force_highest_possible_version_unsafe()`
since [gms: heart_beat_state: use generation_type and version_type](https://github.com/scylladb/scylladb/compare/4cdad8bc8bc68cfcf1b2677da78e2b87aef77631)
(merged in [Merge 'gms: define and use generation and version types'...](https://github.com/scylladb/scylladb/compare/7f04d8231df86ae4dda31318464fa0e8a100eaff))

Implementing min/max correctly
Fixes #13801

### CODE REVIEW

File: utils/tagged_integer.hh [hunk 1]
```diff
@@ -98,4 +98,19 @@ template <typename Final, typename Tag, std::integral ValueType>
     return s << x.value();
 }
 
+template <typename Final, typename Tag, std::integral ValueType>
+struct numeric_limits<utils::tagged_tagged_integer<Final, Tag, ValueType>> : public numeric_limits<ValueType> {
+    using type = utils::tagged_tagged_integer<Final, Tag, ValueType>;
```
Comment (tchaikov) [inline utils/tagged_integer.hh:103]: no need to define this. on the contrary, the reason why we can inherit from `numeric_limits<ValueType>` is that we rely on the fact that `numeric_limits<ValueType>::is_specialized` and `numeric_limits<ValueType>::is_bounded` are true. so we either need to have
```c++
using value_limits =  numeric_limits<ValueType>;
static_assert(value_limits::is_specialized && value_limits::is_bounded);
```
to make this assumption more explicit.
or we just trust that the library complies to the standard that all built-in fundamental types are bounded and the standard library specializes `numeric_limits` for all integral types.

also, i'd suggest add
```c++
static_assert(static_assert(std::numeric_limits<version_type>::is_bounded);
```

in `heart_beat_state::force_highest_possible_version_unsafe()`, before calling `std::numeric_limits<version_type>::max()`, as the caller site has this assumption on `version_type`, so it might want to make this explicit.

Comment (bhalevy) [reply utils/tagged_integer.hh:103]: > no need to define this. on the contrary, the reason why we can inherit from `numeric_limits<ValueType>` is that we rely on the fact that `numeric_limits<ValueType>::is_specialized` and `numeric_limits<ValueType>::is_bounded` are true. so we either need to have
> 
> ```c++
> using value_limits =  numeric_limits<ValueType>;
> static_assert(value_limits::is_specialized && value_limits::is_bounded);
> ```

I like the direction, but this doesn't work as I intended since with this definition, min/max return `ValueType`, not the `tagged_tagged_integer` type.

Comment (tchaikov) [reply utils/tagged_integer.hh:103]: sorry for the confusion. i didn't suggest remove `min()` or `max()`. i meant to reference `is_specialized = true` when copying this comment from another commit. it is
```c++
static constexpr bool is_specialized = true;
```
which is not necessary, and should be removed or replaced.

**Comment by bhalevy** [comment]
In v2 ([6cba7db](https://github.com/scylladb/scylladb/commit/6cba7db14cfd924678489302ec14b77ef2b54937)):
- `using value_limits = numeric_limits<ValueType>` in specialization of `[6cba7db](https://github.com/scylladb/scylladb/commit/6cba7db14cfd924678489302ec14b77ef2b54937)`
- Added static asserts as per https://github.com/scylladb/scylladb/pull/13880#discussion_r1193308897

File: utils/tagged_integer.hh (hunk 1 above)
Comment (bhalevy) [reply utils/tagged_integer.hh]: NP.  Done this way in v2

File: service/storage_service.cc [hunk 2]
```diff
@@ -2154,11 +2154,9 @@ future<> storage_service::handle_state_normal(inet_address endpoint) {
         if (!owned_tokens.empty()) {
             on_fatal_internal_error(slogger, ::format("endpoint={} is marked for removal but still owns {} tokens", endpoint, owned_tokens.size()));
         }
+    } else if (owned_tokens.empty()) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:2157]: If we had this from the start we would have not catched the bug in tests. Maybe we would catch it in prod eventually which is worse. I'd prefer the `on_internal_error` to stay so we keep catching bugs like this.

Comment (bhalevy) [reply service/storage_service.cc:2157]: I don't mind much keeping the internal error (I put it there in the first place),
But FWIW, in production on_internal_error would just print an error and throw, so it's still about catching the issue in testing.

Comment (kbr-scylla) [reply service/storage_service.cc:2157]: Note that here we were using `on_internal_error_noexcept` which IIUC would also crash in production.

In that case I propose we change it to `on_internal_error` as the nice middle ground - crashing the process during tests to catch bugs easier while only crashing the fiber in prod.

Comment (bhalevy) [reply service/storage_service.cc:2157]: No, `on_internal_error_noexcept` would not crash in production, but rather just print the error and happily continue on as if nothing happened (assuming `abort_on_internal_error` is false).
Changing to `on_internal_error` will either crash in testing or throw an error in production.

**Comment by bhalevy** [comment]
In v3 ([502b552](https://github.com/scylladb/scylladb/commit/502b5522caea235fce5cfac3b7c48285f9d92311)):
- turn `on_internal_error_noexcept` in "owns no tokens" case to `on_internal_error`

**Comment by avikivity** [comment]
> It turns out that numeric_limits defines an implicit implementation for std::numeric_limits<utils::tagged_integer<Tag, ValueType>> which apprently returns a default-constructed tagged_integer for min() and max(), 


How did this happen?

**Comment by bhalevy** [comment]
> > It turns out that numeric_limits defines an implicit implementation for std::numeric_limits<utils::tagged_integer<Tag, ValueType>> which apprently returns a default-constructed tagged_integer for min() and max(),
> 
> How did this happen?

What exactly are you asking about?
The regression was caused by https://github.com/scylladb/scylladb/compare/7f04d8231df86ae4dda31318464fa0e8a100eaff
