### PR TITLE
alternator: fix REST API access to an Alternator LSI

### LINKED ISSUE #5883: Alternator new keyspace names is breaking all kind of nodetool/manager operations
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200222.4e95b67501c
Cluster size: 6 
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-012fcd7ac5f0e1471

## Summary

Since the alternator code create a keyspace per table name like `a#usertable`
all kind of notetool operations started failing like this:

```
DisruptionEvent Severity.ERROR): type=end name=ShowTopPartitions node=Node alternator-3h-alternat-db-node-c76021e2-5 [52.212.138.124 | 10.0.234.176] (seed: False) duration=1 error=Encountered a bad command exit code!

Command: 'nodetool  cfstats '

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/a#usertable:usertable' failed: Column family 'a%23usertable:usertable' not found
See 'nodetool help' or 'nodetool help '.
```

I think the hash is a bit problematic for a keyspace name, and isn't handled correctly across the board.
 

### On nodetool cfstats
```
DisruptionEvent Severity.ERROR): type=end name=ShowTopPartitions node=Node alternator-3h-alternat-db-node-c76021e2-5 [52.212.138.124 | 10.0.234.176] (seed: False) duration=1 error=Encountered a bad command exit code!

Command: 'nodetool cfstats '

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/write_latency/moving_average_histogram/a#usertable:usertable' failed: Column family 'a%23usertable:usertable' not found
See 'nodetool help' or 'nodetool help '.
```

### On nodetool cleanup
```
DisruptionEvent Severity.ERROR): type=end name=Decommission node=Node alternator-3h-alternat-db-node-c76021e2-2 [3.248.212.66 | 10.0.220.251] (seed: False) duration=460 error=Encountered a bad command exit code!

Command: 'nodetool  cleanup a#usertable'

Exit code: 2

Stdout:



Stderr:

	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### On manager backup call
```
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > Command: 'sudo sctool backup -c cbadbfcf-0375-4f68-836c-657ca136f1cb --location s3:manager-backup-tests-eu-west-1'
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > 
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > Exit code: 1
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > 
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > Stdout:
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > 
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > 
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > 
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > Stderr:
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > 
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > Error: failed to create backup target: keyspace a#usertable: get ring description: agent [HTTP 400] Keyspace a%23usertable Does not exist
14:17:05  < t:2020-02-20 12:17:04,773 f:sct_events.py   l:714  c:sdcm.sct_events      p:INFO  > Trace ID: 3saGYMhzTRipb1yF2M8vbg (grep in scylla-manager logs)
```

### PR DESCRIPTION
**Pull request by nyh**
The name of the Scylla table backing an Alternator LSI looks like `basename:!lsiname`. Some REST API clients (including Scylla Manager) when they send a "!" character in the REST API request path may decide to "URL encode" it - convert it to `%21`.

Because of a Seastar bug (https://github.com/scylladb/seastar/issues/725) Scylla's REST API server forgets to do the URL decoding on the path part of the request, which leads to the REST API request failing to address the LSI table.

The first patch in this PR fixes the bug by using a new Seastar API introduced in https://github.com/scylladb/seastar/pull/2125 that does the URL decoding as appropriate. The second patch in the PR is a new test for this bug, which fails without the fix, and passes afterwards.

Fixes #5883.

### CODE REVIEW

**Comment by nyh** [comment]
This PR is still in draft mode until the required Seastar feature https://github.com/scylladb/seastar/pull/2125 is merged.

**Comment by nyh** [comment]
Seastar feature is merged, now we need the new Seastar in Scylla: https://github.com/scylladb/scylladb/pull/18297.
When that's in too, I can mark this PR ready for review.

**Comment by nyh** [comment]
The Seastar submodule was updated with the fix for https://github.com/scylladb/seastar/issues/725, so this PR is ready for review and will hopefully pass the CI, so I removed the "draft" mark.

File: api/storage_service.cc [hunk 1]
```diff
@@ -73,8 +73,12 @@ sstring validate_keyspace(const http_context& ctx, sstring ks_name) {
     throw bad_param_exception(replica::no_such_keyspace(ks_name).what());
 }
 
-sstring validate_keyspace(const http_context& ctx, const parameters& param) {
-    return validate_keyspace(ctx, param["keyspace"]);
+sstring validate_keyspace(const http_context& ctx, const std::unique_ptr<http::request>& req) {
+    return validate_keyspace(ctx, req->get_path_param("keyspace"));
+}
+
+sstring validate_keyspace(const http_context& ctx, const http::request& req) {
```
Comment (bhalevy) [inline api/storage_service.cc:80]: why not expose only this function and let the other callers dereference their `std::unique_ptr<http::request>` to call this function?

Comment (tchaikov) [reply api/storage_service.cc:80]: yeah, i concur with Benny on this.

File: test/alternator/test_lsi.py [hunk 2]
```diff
@@ -538,3 +539,35 @@ def test_lsi_and_gsi_same_name(dynamodb):
                 }
             ])
         table.delete()
+
+# Test that the LSI table can be addressed in Scylla's REST API (obviously,
+# since this test is for the REST API, it is Scylla-only and can't be run on
+# DynamoDB).
```
Comment (nuivall) [inline test/alternator/test_lsi.py:545]: maybe add `scylla_only` fixture? (I even suspect that rest_api fixture could depend on it)

File: api/storage_service.cc (hunk 1 above)
Comment (nyh) [reply api/storage_service.cc:80]: If I remember correctly, it saved me from having to modify another few dozens callers :-(

File: test/alternator/test_lsi.py (hunk 2 above)
Comment (nyh) [reply test/alternator/test_lsi.py:545]: Indeed, "rest_api" already depends on scylla-only, and it's self-explanatory that it does (the "REST API" is a feature that only exists on Scylla).
Moreover, the "rest_api" needs **more** than just Scylla. We need to have Scylla that runs the REST API and its REST API port is open. This is not necessarily the case if Scylla is remote.

Comment (nuivall) [reply test/alternator/test_lsi.py:545]: "REST API"  - since dynamodb is kinda REST it may be more or less clear depends who reads :)

it doesn't depend on scylla_api fixture, but I see now it's doing pretty much the same check with different message so it's fine

Comment (nyh) [reply test/alternator/test_lsi.py:545]: Yes, the phrase "rest api" is a Scylla jargon that perhaps we should have named differently, but it stuck.
The comments on this fixture explain that it is about "Scylla-specific REST API requests"

File: api/storage_service.cc (hunk 1 above)
Comment (tchaikov) [reply api/storage_service.cc:80]: i see. will come up with a follow up after this fix lands.

File: test/alternator/test_lsi.py [hunk 3]
```diff
@@ -538,3 +539,35 @@ def test_lsi_and_gsi_same_name(dynamodb):
...
+    for name in resp.json():
+        if test_table_lsi_1.name in name and 'hello' in name:
+            lsi_rest_name = name
+            break
+    assert lsi_rest_name
+    # Attempt to run a request on this LSI's table name "lsi_rest_name".
+    # We'll use the compaction_strategy request here, but if for some
+    # reason in the future we decide to drop that request, any other
+    # request will be fine.
+    resp = requests.get(f'{rest_api}/column_family/compaction_strategy/' + lsi_rest_name)
```
Comment (tchaikov) [inline test/alternator/test_lsi.py:567]: nit, since we are using the f-string here, why not just put
```py
resp = requests.get(f'{rest_api}/column_family/compaction_strategy/{lsi_rest_name}')
```
?

File: test/alternator/test_lsi.py [hunk 4]
```diff
@@ -538,3 +539,35 @@ def test_lsi_and_gsi_same_name(dynamodb):
...
+    resp.raise_for_status()
+    # Let's make things difficult for the server by URL encoding the
+    # lsi_rest_name - exposing issue #5883.
+    encoded_lsi_rest_name = requests.utils.quote(lsi_rest_name)
+    resp = requests.get(f'{rest_api}/column_family/compaction_strategy/' + encoded_lsi_rest_name)
```
Comment (tchaikov) [inline test/alternator/test_lsi.py:572]: ditto.

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8285/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8285/) **The following new/updated tests ran 100 times for each mode:** 🔹 alternator ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8285/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1188/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9210/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8285/)
> #### Failed Tests (1/257998):
> 
>     * [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8285/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest___test_rolling_upgrade) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
> 
> 
> #### Build Details:
> 
>     * Duration: 6 hr 31 min
> 
>     * Builder: i-01a9a021882f9a03e (m5ad.8xlarge)

#16002

File: test/alternator/test_lsi.py (hunk 3 above)
Comment (nyh) [reply test/alternator/test_lsi.py:567]: No particular reason. I'll change it since anyway I need to get the CI running again.

**Comment by nyh** [comment]
Pushed a rebased version (to fix conflicts with newly-introduce code) and rerun CI (after previous failure was excused as a known flaky test). Also changed Python style in two places as requested by reviewer.

**Comment by tchaikov** [comment]
@nyh could you add the backport label as well?

**Comment by nyh** [comment]
Pushed another rebased version (I messed up the previous version, and it didn't compile).

I'm adding the backport tags - this is an ancient issues, not a regression at all, but it can cause problems in real deployments of extant versions. That being said, the automated backporting will fail because of the missing Seastar feature, so that automation will do more harm than good, at least in this case :-(

**Comment by tchaikov** [comment]
i see. just wanted the backports won't be missed. i once read that we could have the "Backports: " tag in the cover letter / commit message. not sure how it is integrated into our workflow after mergify is used.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help review this change?

**Comment by nyh** [comment]
CI never ran on the latest rebase, I don't know what this means... I'll rebase and repush just to try to get the CI to run.

**Comment by nyh** [comment]
Alternator tests failed every time in every build mode, failing to boot Scylla:
```
ERROR 2024-05-02 10:00:09,914 [shard 0:main] init - Startup failed: std::runtime_error (Handler for /column_family/metrics/true_snapshots_size already exists.)
```
How could anything in my patch (that has nothing to do with snapshots) change this? How did I miss it in my own tests? @amnonh does this error message sound familiar?

I'll look into it.

**Comment by nyh** [comment]
I can reproduce this boot failure with my patch, but not without my patch (which boots correctly), so something is wrong with my patch against the latest master.... I'll debug it and send a fixed version.

**Comment by nyh** [comment]
Turns out it was a rebasing mistake which ended up causing some code to be duplicated (!). I'll re-do the rebase.

**Review by denesb — APPROVED** [review]

**Comment by nyh** [comment]
This patch is already in 6.0, will do the backport to 5.4 now (the automated "mergify" backport doesn't work, it missed the Seastar part). No need to backport to EOL branch 5.2.

**Comment by nyh** [comment]
Backports involving Seastar updates are unfortunately very complicated and even more complicated to make as pull-request, so I merged the backport directly to next-5.4, I hope I won't regret it.
Commit 143b5a9b16e72f0df577530f9b8df54bbd1ce5f7 is the Seastar backport,
Commit  929267cb4087985fb4c8de039692b0064f5fbffa is the Scylla backport.

The Scylla backport was tedious and ugly - I had changes to **a lot** of lines that were also changed by other patches that aren't in 5.4, so I tried to fix everything. I verified that the build works, and the new Alternator test works, before merging. I hope I didn't mess anything up the next-5.4 promotion will work.
