### PR TITLE
alternator: avoid oversized allocation in Query/Scan

### LINKED ISSUE #23535: Alternator doesn't page data
Alternator doesn't pass a row_limit to read_command.

Examples:

```
350/648] CXX build/dev/alternator/executor.o
In file included from alternator/executor.cc:11:
In file included from ./alternator/executor.hh:11:
In file included from /home/avi/scylla/seastar/include/seastar/core/future.hh:36:
In file included from /home/avi/scylla/seastar/include/seastar/core/task.hh:25:
In file included from /home/avi/scylla/seastar/include/seastar/util/backtrace.hh:27:
/home/avi/scylla/seastar/include/seastar/core/shared_ptr.hh:177:39: warning: 'read_command' is deprecated: Please specify a row_limit (page size) explicitly [-Wdeprecated-declarations]
  177 |     lw_shared_ptr_no_esft(A&&... a) : _value(std::forward<A>(a)...) {}
      |                                       ^
/home/avi/scylla/seastar/include/seastar/core/shared_ptr.hh:281:22: note: in instantiation of function template specialization 'seastar::lw_shared_ptr_no_esft<query::read_command>::lw_shared_ptr_no_esft<const utils::tagged_uuid<table_id_tag> &, utils::tagged_uuid<table_schema_version_tag>, query::partition_slice &, query::max_result_size, query::tombstone_limit>' requested here
  281 |         auto p = new typename accessors<T>::concrete_type(std::forward<A>(a)...);
      |                      ^
/home/avi/scylla/seastar/include/seastar/core/shared_ptr.hh:436:30: note: in instantiation of function template specialization 'seastar::lw_shared_ptr<query::read_command>::make<const utils::tagged_uuid<table_id_tag> &, utils::tagged_uuid<table_schema_version_tag>, query::partition_slice &, query::max_result_size, query::tombstone_limit>' requested here
  436 |     return lw_shared_ptr<T>::make(std::forward<A>(a)...);
      |                              ^
alternator/executor.cc:515:22: note: in instantiation of function template specialization 'seastar::make_lw_shared<query::read_command, const utils::tagged_uuid<table_id_tag> &, utils::tagged_uuid<table_schema_version_tag>, query::partition_slice &, query::max_result_size, query::tombstone_limit>' requested here
  515 |     auto command = ::make_lw_shared<query::read_command>(
      |                      ^
./query-request.hh:434:7: note: 'read_command' has been explicitly marked deprecated here
  434 |     [[deprecated("Please specify a row_limit (page size) explicitly")]]
      |       ^
1 warning generated.
[387/648] CXX build/dev/test/boost/database_test.o
test/boost/database_test.cc:1034:41: warning: 'read_command' is deprecated: Please specify a row_limit (page size) explicitly [-Wdeprecated-declarations]
 1034 |                     query::read_command cmd(s->id(), s->version(), slice, query::max_result_size(max_size), query::tombstone_limit::max);
      |                                         ^
./query-request.hh:434:7: note: 'read_command' has been explicitly marked deprecated here
  434 |     [[deprecated("Please specify a row_limit (page size) explicitly")]]
      |       ^
test/boost/database_test.cc:1111:33: warning: 'read_command' is deprecated: Please specify a row_limit (page size) explicitly [-Wdeprecated-declarations]
 1111 |             query::read_command cmd(s->id(), s->version(), slice, query::max_result_size(max_size), query::tombstone_limit::max);
      |                                 ^
./query-request.hh:434:7: note: 'read_command' has been explicitly marked deprecated here
  434 |     [[deprecated("Please specify a row_limit (page size) explicitly")]]
      |       ^
2 warnings generated.
```

This can lead to 8k+ rows in a page, which in turn leads to large allocations in rapidjson.

### PR DESCRIPTION
**Pull request by nyh**
This series fixes one cause of oversized allocations - and therefore potentially stalls and increased tail latencies - in Alternator.

The first patch in the series is the main fix - the later patches are cleanups requested by reviewers but also involved other pre-existing code, so I did those cleanups as separate patches.

Alternator's Scan or Query operation return a page of results. When the number of items is not limited by a "Limit" parameter, the default is to return a 1 MB page. If items are short, a large number of them can fit in that 1MB. The test test_query.py::test_query_large_page_small_rows has 30,000 items returned in a single page.

In the response JSON, all these items are returned in a single array "Items". Before this patch, we build the full response as a RapidJSON object before sending it. The problem is that unfortunately, RapidJSON stores arrays as contiguous allocations. This results in large contiguous allocations in workloads that scan many small items, and large contiguous allocations can also cause stalls and high tail latencies. For example, before this patch, running

    test/alternator/run --runveryslow \
        test_query.py::test_query_large_page_small_rows

reports in the log:

    oversized allocation: 573440 bytes.

After this patch, this warning no longer appears.
The patch solves the problem by collecting the scanned items not in a RapidJSON array, but rather in a chunked_vector<rjson::value>, i.e, a chunked (non-contiguous) array of items (each a JSON value). After collecting this array separately from the response object, we need to print its content without actually inserting it into the object - we add a new function print_with_extra_array() to do that.

The new separate-chunked-vector technique is used when a large number (currently, >256) of items were scanned. When there is a smaller number of items in a page (this is typical when each item is longer), we just insert those items in the object and print it as before.

Beyond the original slow test that demonstrated the oversized allocation (which is now gone), this patch also includes a new test which exercises the new code with a scan of 700 (>256) items in a page - but this new test is fast enough to be permanently in our test suite and not a manual "veryslow" test as the other test.

Fixes #23535

The stalls caused by large allocations was seen by actual users, so it makes sense to backport this patch. On the other hand, the patch while not big is fairly intrusive (modifies the nomal Scan and Query path and also the later patches do some cleanup of additional code) so there is some small risk involved in the backport.

### CODE REVIEW

**Comment by nyh** [comment]
@avikivity I marked this patch "Fixes https://github.com/scylladb/scylladb/issues/23535" but it's not entirely clear to me what #23535 is about so I don't know if the "Fixes" is fair:

The original claim you made in that issue, that Alternator somehow misuses paging or forgets to limit it, was not correct as far as I understand. What we learned in the discussion in that issue was that the default 1MB page size Alternator (correctly) uses can result in a large number of tiny rows (30,000 in the test we already had) which caused a large contiguous allocation of a RapidJSON array. It is this contiguous allocation - and **only** this contiguous allocation - which this patch fixes. After this patch, a query returning 30,000 tiny items in one page, has no "oversized allocation" warnings.

Do you think that's enough for marking #23535 fixed, or is there anything else you think needs to be fixed before that issue is closed.

File: alternator/executor.cc [hunk 1]
```diff
@@ -156,6 +156,50 @@ json::json_return_type make_streamed(rjson::value&& value) {
...
+// array is given a separate chunked_vector, to avoid putting it inside the
+// rjson::value because RapidJSON does contiguous allocations for arrays
+// which we want to avoid for potentially long arrays in Query/Scan responses
+// (see #23535).
+// If we can ever fix RapidJSON (or a replacement) to avoid contiguous
+// allocations for arrays, we can remove this function and the function
+// rjson::print_with_extra_array() which it calls.
+json::json_return_type make_streamed_with_extra_array(rjson::value&& value,
+    std::string array_name, utils::chunked_vector<rjson::value>&& array) {
+    // CMH. json::json_return_type uses std::function, not noncopyable_function.
```
Comment (avikivity) [inline alternator/executor.cc]: What is a CMH?

File: alternator/executor.cc [hunk 2]
```diff
@@ -156,6 +156,50 @@ json::json_return_type make_streamed(rjson::value&& value) {
...
+    // Need to make a copyable version of value. Gah.
+    auto rs = make_shared<rjson::value>(std::move(value));
+    auto ns = make_shared<std::string>(std::move(array_name));
+    auto as = make_shared<utils::chunked_vector<rjson::value>>(std::move(array));
```
Comment (avikivity) [inline alternator/executor.cc]: Could save two allocations by placing all three in a single shared object.

Comment (avikivity) [reply alternator/executor.cc]: And simplify a bit by using make_lw_shared.

File: alternator/executor.cc [hunk 3]
```diff
@@ -156,6 +156,50 @@ json::json_return_type make_streamed(rjson::value&& value) {
...
+        std::exception_ptr ex;
+        try {
+            co_await rjson::print_with_extra_array(*lrs, *lns, *las, los);
+        } catch (...) {
+            // at this point, we cannot really do anything. HTTP headers and return code are
+            // already written, and quite potentially a portion of the content data.
+            // just log + rethrow. It is probably better the HTTP server closes connection
+            // abruptly or something...
+            ex = std::current_exception();
+            elogger.error("Exception during streaming HTTP response: {}", ex);
```
Comment (avikivity) [inline alternator/executor.cc]: Seems like a bad client could spam our logs with errors with this.

File: alternator/executor.cc (hunk 1 above)
Comment (nyh) [reply alternator/executor.cc]: I copied the existing make_streamed() to create the new make_streamed_with_extra_array(), so everything you asked about in this function came from pre-existing code (and is valid also about the pre-existing code). 

That comes from 4a8a7ef8b4f by @elcallio. I asked him once what CMH meant, and it turns out it means "Change missing here". Something like TODO. I agree it's not a common thing. I can clean this function but, per perhaps need to do the same in the pre-existing make_streamed() as well.

File: alternator/executor.cc (hunk 2 above)
Comment (nyh) [reply alternator/executor.cc]: I guess. Again I copied this trick verbatim from Calle's code. It was so sad to see it that I didn't want to look at it any more ;-) But I guess I can improve it a bit.

Of course, the real fix would have been to use a non-copyable function instead of complaining about it in a comment. But maybe such a change would be too intrusive to do in Seastar :-(

File: alternator/executor.cc (hunk 3 above)
Comment (nyh) [reply alternator/executor.cc]: I agree. This message was added my @nuivall in commit 6424dd5ec431f1cf2d38db21b1cb025dfc38d6ab (and again I copied it verbatim). I agree we should silently ignore this case, or just make it a debug-level log or something.
Again I need to consider doing this not just in my copy, but also in the code I copied from.

Comment (nuivall) [reply alternator/executor.cc]: Message was already there before, but text changed to be more accurate. Maybe we can add rate limiting

File: utils/rjson.hh [hunk 4]
```diff
@@ -158,6 +159,21 @@ std::string print(const rjson::value& value, size_t max_nested_level = default_m
...
 seastar::future<> print(const rjson::value& value, seastar::output_stream<char>&, size_t max_nested_level = default_max_nested_level);
 
+// A variant of print() which prints a JSON object (it assumes the given
+// rjson::value is an object) but adds to it at the end an additional array.
+// That extra array is given a separate chunked_vector, to avoid putting it
+// inside the rjson::value because RapidJSON does contiguous allocations
+// for arrays, which we want to avoid for potentially long arrays (#23535).
+// We only have a streaming version of this function, as it is only used for
+// large arrays, and we want to yield while printing the JSON.
+// If we can ever fix RapidJSON (or a replacement) to avoid contiguous
```
Comment (ScyllaPiotr) [inline utils/rjson.hh]: Mention exchanging rapidjson too, with with calling up explicitly #24458.

File: utils/rjson.hh [hunk 5]
```diff
@@ -158,6 +159,21 @@ std::string print(const rjson::value& value, size_t max_nested_level = default_m
...
+// allocations for arrays, we can remove this function.
+future<> print_with_extra_array(const rjson::value& value,
+    std::string_view array_name,
+    const utils::chunked_vector<rjson::value>& array,
+    seastar::output_stream<char>& os,
+    size_t max_nested_level  = default_max_nested_level);
```
Comment (ScyllaPiotr) [inline utils/rjson.hh]: double space

File: utils/rjson.cc [hunk 6]
```diff
@@ -280,6 +280,36 @@ future<> print(const rjson::value& value, seastar::output_stream<char>& os, size
...
+        for (auto m = value.MemberBegin(); m != value.MemberEnd(); ++m) {
+            writer.Key(m->name.GetString(), m->name.GetStringLength());
+            m->value.Accept(writer);
+        }
+        writer.Key(array_name.data(), array_name.size());
+        writer.StartArray();
+        for (const rjson::value& v : array) {
+            v.Accept(writer);
+        }
+        writer.EndArray();
```
Comment (ScyllaPiotr) [inline utils/rjson.cc]: Should have been `writer.EndArray(array.size())`, like [here](https://github.com/Tencent/rapidjson/blob/24b5e7a8b27f42fa16b96fc70aade9106cf7102f/include/rapidjson/document.h#L1972), no? The missing parameter influences only logging.

File: test/alternator/test_query.py [hunk 7]
```diff
@@ -637,3 +637,23 @@ def test_query_large_page_small_rows(test_table_sn):
...
+    with test_table_sn.batch_writer() as batch:
+        for i in range(N):
+            batch.put_item({'p': p, 'c': i})
+    got_items = test_table_sn.query(KeyConditions={
+        'p': {'AttributeValueList': [p], 'ComparisonOperator': 'EQ'}},
+        ConsistentRead=True)['Items']
+    i = 0
+    for item in got_items:
+        assert item == {'p': p, 'c': i}
+        i += 1
```
Comment (ScyllaPiotr) [inline test/alternator/test_query.py:659]: Could be beneficial to `assert N == i+1` afterwards.

File: alternator/executor.cc [hunk 8]
```diff
@@ -156,6 +156,50 @@ json::json_return_type make_streamed(rjson::value&& value) {
     return func;
 }
 
+// make_streamed_with_extra_array() is variant of make_streamed which responds
+// with a JSON object but adds to it at the end an additional array. The extra
+// array is given a separate chunked_vector, to avoid putting it inside the
+// rjson::value because RapidJSON does contiguous allocations for arrays
+// which we want to avoid for potentially long arrays in Query/Scan responses
+// (see #23535).
+// If we can ever fix RapidJSON (or a replacement) to avoid contiguous
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: Mention exchanging rapidjson too, with with calling up explicitly #24458.

File: alternator/executor.cc (hunk 2 above)
Comment (ScyllaPiotr) [reply alternator/executor.cc]: It's a silly thing, but I feel it's hard to understand the meaning of these short names.

File: alternator/executor.cc [hunk 9]
```diff
@@ -4730,13 +4777,25 @@ class describe_items_visitor {
     }
 };
 
-static future<std::tuple<rjson::value, size_t>> describe_items(const cql3::selection::selection& selection, std::unique_ptr<cql3::result_set> result_set, std::optional<attrs_to_get>&& attrs_to_get, filter&& filter) {
+// describe_items() returns a JSON object that includes members "Count"
+// and "ScannedCount", but *not* "Items" - that is returned separately
+// as a chunked_vector to avoid large contiguous allocations which
+// RapidJSON does of its array. The caller should add "Items" to the
+// returned object if needed, or print it separately.
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: `returned object` -> `returned JSON object`

File: alternator/executor.cc [hunk 10]
```diff
@@ -4859,7 +4919,7 @@ static future<executor::request_return_type> do_query(service::storage_proxy& pr
     }
     auto paging_state = rs->get_metadata().paging_state();
     bool has_filter = filter;
-    auto [items, size] = co_await describe_items(*selection, std::move(rs), std::move(attrs_to_get), std::move(filter));
+    auto [items, actual_items, size] = co_await describe_items(*selection, std::move(rs), std::move(attrs_to_get), std::move(filter));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: Like `items` are not actual :-)
Jokes aside, maybe `rjson_items` and `chunked_vec_items` would be better names?

File: alternator/executor.cc [hunk 11]
```diff
@@ -4868,6 +4928,22 @@ static future<executor::request_return_type> do_query(service::storage_proxy& pr
         // update our "filtered_row_matched_total" for all the rows matched, despited the filter
         cql_stats.filtered_rows_matched_total += size;
     }
+    if (actual_items) {
+        if (actual_items->size() >= 256) {
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: Let's have this number declared up as a `static constexpr int`.

File: alternator/executor.cc [hunk 12]
```diff
@@ -4868,6 +4928,22 @@ static future<executor::request_return_type> do_query(service::storage_proxy& pr
...
+            // There are many items, better print the JSON and the array of
+            // items (actual_items) separately to avoid RapidJSON's contiguous
+            // allocation of arrays.
+            co_return executor::request_return_type(make_streamed_with_extra_array(std::move(items), "Items", std::move(*actual_items)));
+        }
+        // There aren't many items in the chunked vector actual_items,
+        // let's just insert them into the JSON object and print the
+        // full JSON normally.
+        rjson::value items_json = rjson::empty_array();
+        for (auto& item : *actual_items) {
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: Does this loop mean we prolong most runs, compared to how things were earlier?

**Comment by mykaul** [comment]
@nyh - ping - let's try to get this in soon.

File: alternator/executor.cc (hunk 8 above)
Comment (nyh) [reply alternator/executor.cc]: I mentioned the possibility of replacing RapidJSON (see "or a replacement"), I'll reconsider the wording and add a reference to that issue.

Comment (nyh) [reply alternator/executor.cc]: By the way, soon all the references to issues in our source code will become outdated garbage. Very sad. It was apparently decided to migrate to JIRA and to NOT to keep the old issue numbers when doing the migration.

File: alternator/executor.cc (hunk 2 above)
Comment (nyh) [reply alternator/executor.cc]: Again, all these comments apply to the code I copied from :-(
I'll spend some time now to completely rewrite this function, and then think if I I should also change the original function I copied...

File: alternator/executor.cc (hunk 1 above)
Comment (nyh) [reply alternator/executor.cc]: The best fix here would be to stop using Seastar's json::json_return_type and seastar/json_elements.hh and its std::function completely - and instead start using a noncopyable_function directly. I'm starting to prepare a second patch which will rewrite the use of json_return_type and then this code (and the make_streamed() which it copied) to use noncopyable_function.

**Comment by nyh** [comment]
> @nyh - ping - let's try to get this in soon.

I'm working on this now. Both reviewers did not like a particular piece of code that I actually copied from pre-existing code and was admittedly ugly because it was built on an inappropriate Seastar feature (Seastar's "json_return_type")

File: alternator/executor.cc (hunk 2 above)
Comment (nyh) [reply alternator/executor.cc]: Wow, I got rid of our use of Seastar's json::json_return_type (which is completely bogus) and make_jsonable and other such crap and everything  - including this ugly function that needed to wrap uncopyable stuff with shared pointers - became so much nicer!!! I can't believe I didn't do this years before

Now an executor's function returns (request_return_type) a variant of 3 things: std::string, noncopyable_function or api_error. The first is for returning a short response, the second for streaming a long response into an output stream, and the last is an error. No more std::function and the copying nonsense. No more "make_jsonable(value)" nonsense - we need to return a string so we just return rjson::print(value)! No more json_string("") - we want to return "" we just return "". Everything is so nicer. I'm cleaning up and will include this cleanup as a second patch in this series.

File: alternator/executor.cc (hunk 1 above)
Comment (nyh) [reply alternator/executor.cc]: Done. Will appear in the next version of this PR as a second patch.

File: alternator/executor.cc (hunk 3 above)
Comment (nyh) [reply alternator/executor.cc]: I'll add a third patch to remove these log messages. There is no real need to log these exceptions. The most likely cause of these exceptions will be a broken connection.

File: alternator/executor.cc (hunk 10 above)
Comment (nyh) [reply alternator/executor.cc]: I don't know. "items" is the object which contains all the items' descriptions (count, etc.), and "actual items" contains the actual items.
I'll rename them to items_descr and items.

File: alternator/executor.cc (hunk 11 above)
Comment (nyh) [reply alternator/executor.cc]: I'd rather not, for now. I wouldn't know how to call it, or which value to choose. We can extract it later, make it configurable, or whatever we want.

File: alternator/executor.cc (hunk 12 above)
Comment (nyh) [reply alternator/executor.cc]: In some sense, yes. HOWEVER, the loop only runs when there is a relatively small number of items (currently this 256). Hopefully when there is a small number of items, the cost of this loop is negligible.

One of the benefits of doing this is that it allows me to, after building the output, decide if it's "big" or not and potentially output everything together instead of streaming. I was hoping it will make everything faster when the responses are small.

Maybe the number 256 was excessive and I should use a smaller number.

File: test/alternator/test_query.py (hunk 7 above)
Comment (nyh) [reply test/alternator/test_query.py:659]: Ok, done.

File: utils/rjson.cc (hunk 6 above)
Comment (nyh) [reply utils/rjson.cc]: You're right. Done

File: utils/rjson.hh (hunk 4 above)
Comment (nyh) [reply utils/rjson.hh]: I mentioned this elsewhere (as your request). Here I think it was a mistake talking about a replacement of RapidJSON (which I did mention!) because the entire file is a header of rapidjson-specific wrappers :-)

File: utils/rjson.hh (hunk 5 above)
Comment (nyh) [reply utils/rjson.hh]: Fixed.

File: test/alternator/test_query.py (hunk 7 above)
Comment (nyh) [reply test/alternator/test_query.py:659]: Note it's N == i, not i+1.

**Comment by nyh** [comment]
Pushed a new version addressing many of the reviewers' comments (see my responses on each of these comments).

The most important change is the second patch, which rewrites the ugly and hard to understand make_streamed() and make_streamed_with_extra_array(). I dropped Alternator's use of the ill-suited seastar::json_return_type and replaced it by something more suited for Alternator's needs, and a lot of the code, especially make_streamed() became much shorter without those strange copies and extra shared pointers needed before.

File: alternator/executor.hh [hunk 13]
```diff
@@ -169,7 +146,19 @@ class executor : public peering_sharded_service<executor> {
...
+    // can be one of:
+    // 1. A string, which is the response body for the request.
+    // 2. A body_writer, an asynchronous function (returning future<>) that
+    //    takes an output_stream and writes the response body into it.
+    // 3. An api_error, which is an error response that should be returned to
+    //    the client.
+    // The body_writer is used for streaming responses, where the response body
+    // is written in chunks to the output_stream. This allows for efficient
+    // handling of large responses without needing to allocate a large buffer
+    // in memory.
```
Comment (ScyllaPiotr) [inline alternator/executor.hh:159]: Maybe add `Ref. #23535`

File: alternator/executor.cc [hunk 14]
```diff
@@ -4882,19 +4900,35 @@ static future<executor::request_return_type> do_query(service::storage_proxy& pr
...
     }
     if (has_filter){
         cql_stats.filtered_rows_read_total += p->stats().rows_read_total;
         // update our "filtered_row_matched_total" for all the rows matched, despited the filter
         cql_stats.filtered_rows_matched_total += size;
     }
-    if (is_big(items)) {
-        co_return executor::request_return_type(make_streamed(std::move(items)));
+    if (opt_items) {
+        if (opt_items->size() >= 256) {
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: Let's promote the number to some `static constexpr` in this file.

File: alternator/executor.cc [hunk 15]
```diff
@@ -1212,7 +1214,7 @@ future<executor::request_return_type> executor::list_tags_of_resource(client_sta
         rjson::push_back(tags, std::move(new_entry));
     }
 
-    return make_ready_future<executor::request_return_type>(make_jsonable(std::move(ret)));
+    return make_ready_future<executor::request_return_type>(rjson::print(std::move(ret)));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc:1217]: `co_return rjson::print(std::move(ret))` should also work and is shorter. If you follow this suggestion, line 1198 will also require a change into `co_return`.

File: alternator/executor.cc [hunk 16]
```diff
@@ -2417,7 +2419,7 @@ static future<executor::request_return_type> rmw_operation_return(rjson::value&&
     if (!attributes.IsNull()) {
         rjson::add(ret, "Attributes", std::move(attributes));
     }
-    return make_ready_future<executor::request_return_type>(make_jsonable(std::move(ret)));
+    return make_ready_future<executor::request_return_type>(rjson::print(std::move(ret)));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc:2414]: ~make_ready_future\<executor::request_return_type>~ and `co_return`?

File: alternator/executor.cc [hunk 17]
```diff
@@ -4256,7 +4258,7 @@ future<executor::request_return_type> executor::get_item(client_state& client_st
         per_table_stats->api_operations.get_item_latency.mark(std::chrono::steady_clock::now() - start_time);
         _stats.api_operations.get_item_latency.mark(std::chrono::steady_clock::now() - start_time);
         uint64_t rcu_half_units = 0;
-        auto res = make_ready_future<executor::request_return_type>(make_jsonable(describe_item(schema, partition_slice, *selection, *qr.query_result, std::move(attrs_to_get), add_capacity, rcu_half_units)));
+        auto res = make_ready_future<executor::request_return_type>(rjson::print(describe_item(schema, partition_slice, *selection, *qr.query_result, std::move(attrs_to_get), add_capacity, rcu_half_units)));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: ~make_ready_future\<executor::request_return_type>~ and then `co_return` at the end?

File: alternator/executor.cc [hunk 18]
```diff
@@ -4882,19 +4900,35 @@ static future<executor::request_return_type> do_query(service::storage_proxy& pr
...
         cql_stats.filtered_rows_matched_total += size;
     }
-    if (is_big(items)) {
-        co_return executor::request_return_type(make_streamed(std::move(items)));
+    if (opt_items) {
+        if (opt_items->size() >= 256) {
+            // There are many items, better print the JSON and the array of
+            // items (opt_items) separately to avoid RapidJSON's contiguous
+            // allocation of arrays.
+            co_return executor::request_return_type(make_streamed_with_extra_array(std::move(items_descr), "Items", std::move(*opt_items)));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: ~executor::request_return_type~ here and 2x more below?

File: alternator/executor.cc [hunk 19]
```diff
@@ -5531,7 +5565,7 @@ future<executor::request_return_type> executor::list_tables(client_state& client
         rjson::add(response, "LastEvaluatedTableName", rjson::copy(last_table_name));
     }
 
-    return make_ready_future<executor::request_return_type>(make_jsonable(std::move(response)));
+    return make_ready_future<executor::request_return_type>(rjson::print(std::move(response)));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: `co_return rjson::print(std::move(response))`?

File: alternator/executor.cc [hunk 20]
```diff
@@ -5561,7 +5595,7 @@ future<executor::request_return_type> executor::describe_endpoints(client_state&
     rjson::push_back(response["Endpoints"], rjson::empty_object());
     rjson::add(response["Endpoints"][0], "Address", rjson::from_string(host_header));
     rjson::add(response["Endpoints"][0], "CachePeriodInMinutes", rjson::value(1440));
-    return make_ready_future<executor::request_return_type>(make_jsonable(std::move(response)));
+    return make_ready_future<executor::request_return_type>(rjson::print(std::move(response)));
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: `co_return rjson::print(std::move(response))`?

**Review by ScyllaPiotr — APPROVED** [review]
Nice one!

File: alternator/executor.cc (hunk 11 above)
Comment (ScyllaPiotr) [reply alternator/executor.cc]: I just noticed that I have re-raised this in my latest review.
You suggest to do this later, but I'm afraid we will forget this. It does not need to be configurable, but at least let it be a named constant. About the name, what about `max_resp_item_count_printed_by_rapidjson_natively`?

File: alternator/executor.cc (hunk 8 above)
Comment (ScyllaPiotr) [reply alternator/executor.cc]: The GH issues will be there still, they will just immediately redirect to issues in Jira.

Comment (nyh) [reply alternator/executor.cc]: There is no reason to be optimistic. A couple of years from now, if we're lucky, nobody will remember what "#123" refers to.  If we're less lucky, we'll close down github issues and the old issues will not be available at all.

If we wanted to keep these numbers working, we have a way. But the official decision was not to keep the old numbers :-(

File: alternator/executor.cc (hunk 2 above)
Comment (nyh) [reply alternator/executor.cc]: Done. In the new version there is a second patch revamping this pre-existing code (which after this patch has two copies) to no longer need to use all these shared pointers, because it uses noncopyable function/

File: alternator/executor.cc (hunk 3 above)
Comment (nyh) [reply alternator/executor.cc]: Done in the third patch (since, again, this is pre-existing code which I copied, the new patch fixes both instances of the problem).

File: alternator/executor.cc (hunk 9 above)
Comment (nyh) [reply alternator/executor.cc]: ok, I'll add this word.

File: alternator/executor.cc (hunk 14 above)
Comment (nyh) [reply alternator/executor.cc]: Since you feel strongly about this, I'll do it. What bothered me about doing something like this is that this is single-use and very obscure constant that will need to have a few lines of explanation where it appears because nobody will understand what it refers to. But it shouldn't be too bad. Watch out this space in the next version :-)

File: alternator/executor.cc (hunk 18 above)
Comment (nyh) [reply alternator/executor.cc]: Good catch. I'll remove this unnecessary cast.
I think this is a leftover from the days of continuations (not coroutines) where if a continuation has multiple returns (not co_returns) they need to have explicitly the same type and if it wasn't exactly the same type (e.g., string vs function) I had to explicitly cast in all return points. With co_return, this is no longer the case, which is nice.

I think I'll do this cleanup in the second patch, not this one, though - because the second patch cleans up that make_jsonable thing in the pre-existing code, and I want to remove all those unnecessary request_return_type things in one patch.

File: alternator/executor.cc (hunk 16 above)
Comment (nyh) [reply alternator/executor.cc:2414]: This function was not yet co-routinized, I don't want to do it in the middle of an unrelated patch (I'll also need to change another unrelated return in the same function).

File: alternator/executor.cc (hunk 17 above)
Comment (nyh) [reply alternator/executor.cc]: I don't remember why, but this function is co-routinized by uses a then() in one place. Which I agree is kind of ugly but I don't think I should change it in this patch. I'll do it in a fourth patch I'll add to this series (although arguably, it's not even related to this series).

File: alternator/executor.cc (hunk 19 above)
Comment (nyh) [reply alternator/executor.cc]: I'll do this too in the new fourth patch

File: alternator/executor.cc (hunk 20 above)
Comment (nyh) [reply alternator/executor.cc]: Done in the fourth patch.

File: alternator/executor.hh (hunk 13 above)
Comment (nyh) [reply alternator/executor.hh:159]: No, I don't think so. We've been using streamed responses long before #23535 - e.g., a BatchGetItem of several large items and other places.

**Comment by nyh** [comment]
Rebased and addressed a bunch of review comments from @ScyllaPiotr. Many of the comments lamented ugly casting in return statements that could be addressed by using co_return instead. Because changing this required changing additional irrelevant things in the same functions (you can't have a single function doing co_return in one place, return in another place) I did this cleanup as a fourth patch.

@ScyllaPiotr let's get this series reviewed and merged before it grows further (it started as one patch, now it's 4... :-)).

**Comment by nyh** [comment]
> #### Failed Tests (1/144862):
> 
>     * [test_network_topology_strategy_counters](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/18144/testReport/junit/consistency_test/TestAccuracy/release___dtest_with_gossip_topology_changes___test_network_topology_strategy_counters) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_network_topology_strategy_counters)

Known flaky test https://github.com/scylladb/scylladb/issues/21608.

**Comment by nyh** [comment]
Restarted the dtest run (I wasn't sure if I should restart the whole build again or just the dtest?)

File: alternator/executor.cc (hunk 14 above)
Comment (ScyllaPiotr) [reply alternator/executor.cc]: > this is single-use and very obscure constant that will need to have a few lines of explanation where it appears because nobody will understand what it refers to

That's **exactly** why it needs to be elevated into a constant and commented about. Assume optimistically, that not all the related future bugs will be handled by you and if I'm the one fixing such bugs, I'd want to have all the help from the code I can get :smile:

File: alternator/executor.cc (hunk 12 above)
Comment (ScyllaPiotr) [reply alternator/executor.cc]: I consider this not very important as we are implementing profiling of full execution path for Alternator in order to then optimize the whole path (more specifically, the identified bottlenecks). So in this context, it's premature to get rid of such a loop - we don't know if it's really problematic or not.

On the other hand, maybe your idea (to use a smaller value of loop iterations) is a good one. I have no data to know this.

**Comment by ScyllaPiotr** [comment]
> @ScyllaPiotr let's get this series reviewed and merged before it grows further (it started as one patch, now it's 4... :-)).

You already have a formal approval from me, I see no significant problems.

File: alternator/executor.cc [hunk 21]
```diff
@@ -4815,6 +4832,12 @@ static rjson::value encode_paging_state(const schema& schema, const service::pag
     return last_evaluated_key;
 }
 
+// RapidJSON allocates arrays contiguously in memory, so we want to avoid
+// returning a large number of items as a single rapidjson array, and use
+// a chunked_vector instead. The following constant is an arbitrary cutoff
+// point for when to switch from a rapidjson array to a chunked_vector.
+static constexpr int max_items_for_rapidjson_array = 256;
```
Comment (ScyllaPiotr) [inline alternator/executor.cc:4839]: Nice and clear explanation :+1:

**Comment by nyh** [comment]
> Restarted the dtest run (I wasn't sure if I should restart the whole build again or just the dtest?)

I don't see new test results. I'll rebase to get the CI running from scratch.

**Comment by mykaul** [comment]
@scylladb/scylla-maint - please review for inclusion.

**Comment by nyh** [comment]
> I'm surprised at how many hoops we have to jump trough to avoid large allocations when writing json. `rjson` has native support for writing JSON in a streamed manner, something the `scylla-sstable` tool makes heavy use of: it can writes GBs or even TBs of JSON without any large allocation. Why not use this capability and why do all this jumping through hoops, adding more and more specific `make_streamed()` overloads?
> 
> I will queue this because it is already approved and customers are waiting for the fix, but I think the above questions should be considered for the future.

The thing is that it's very **convenient** (and efficient) to prepare a small JSON object in memory and then return it, and it makes Alternator's code very simple. The situations where Alternator needs to return a large object are pretty specific, so a "reasonable" compromise was to make only those places "jump through hoops" instead of all the Alternator code everywhere.

Perhaps in the future we can rework this whole response-generating mechanism. Especially if we want to replace RapidJSON by something else. But I don't think this is the right time to do it.

**Comment by nyh** [comment]
Users are still encountering this problem on older releases. Above we only did the backport to 2025.3 and the backports to 2025.2 and 2025.1 which had conflicts were not done. I'll need to do this now.
