### PR TITLE
mutation_query: properly send range tombstones in reverse queries

### LINKED ISSUE #10598: Missing key in cassandra-harry verification while doing rolling restart of the cluster
## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `5.0~rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 6 nodes (i3.large)

Scylla Nodes used in this run:
- longevity-harry-2h-test-har-db-node-5ad966f5-9 (13.51.238.118 | 10.0.2.230) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-8 (16.16.27.133 | 10.0.2.177) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-7 (13.53.112.117 | 10.0.1.21) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-6 (13.51.234.38 | 10.0.1.59) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-5 (13.50.16.149 | 10.0.0.74) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-4 (13.49.245.114 | 10.0.3.165) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-3 (13.49.18.135 | 10.0.3.102) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-2 (16.171.54.36 | 10.0.0.136) (shards: 2)
- longevity-harry-2h-test-har-db-node-5ad966f5-1 (16.171.52.196 | 10.0.3.210) (shards: 2)

OS / Image: `ami-0e4ae5e4a139c50f3` (aws: eu-north-1)

Test: `longevity-harry-2h-test`
Test id: `5ad966f5-8ded-437d-9224-7601b95777f1`
Test name: `scylla-staging/fruch/longevity-harry-2h-test`
Test config file(s):

- [longevity-harry-2h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/558897cd1fb9b5c37a0d48e63d7ae9e7ec6922a3/test-cases/longevity/longevity-harry-2h.yaml)

## Issue description

During RollingRestartCluster, cassandra-harry fail in it's verification find only 19 key out of 134 expected ones.
It's doing the query six times, and in all of them get the same results

This is the query, a prepare statment that runs with `ConsistencyLevel.QUORUM`:
```
SELECT pk0000, pk0001, pk0002, ck0000, ck0001, static0000, static0001, static0002, static0003, static0004, regular0000, regular0001, regular0002, regular0003, writetime(static0000), writetime(static0001), writetime(static0002), writetime(static0003), writetime(static0004), writetime(regular0000), writetime(regular0001), writetime(regular0002), writetime(regular0003) FROM harry.table0 WHERE pk0000 = ? AND pk0001 = ? AND pk0002 = ? ORDER BY ck0000 DESC, ck0001 DESC;
```

Form cassandra-harry log, `Partition state` is the expected result, `Observed state` is the result from the query (notice that the expected is in reverse order then the observed)
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: harry.model.Model$ValidationException: Expected results to have the same number of results, but expected result iterator has more results.

Partition state:
...
133 lines like the following
...
RowState{cd=9101507508570737439, vds=[216457386, -9223372036854775808, 2148363779, -9223372036854775808], lts=[2379820, -9223372036854775808, 2379820, -9223372036854775808], clustering=[1092247935856, 2.1378701E-38], values=[216457386, null, -2146603517, null]}

Observed state:
resultSetRow(2952445832411809646L, 9101507508570737439L, staticValues(13953956969167411L,185L,31129L,215L,148L), slts(2379990L,2379990L,2379990L,2379990L,2379990L), values(216457386L,-9223372036854775808L,2148363779L,-9223372036854775808L), lts(2379820L,-9223372036854775808L,2379820L,-9223372036854775808L), clustering=[1092247935856, 2.1378701E-38], values=[216457386, null, -2146603517, null], statics=[9.77609217999303E-308, -71, 31129, -41, -108])
...
18 lines like that
```

With nemesis running this is happens 3/4 time it run

On steady state, with nemesis cassandra-harry finish with success, on 5.0.rc3

On master we are facing a coredump without nemesis, so we can't compare (#10553)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5ad966f5-8ded-437d-9224-7601b95777f1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5ad966f5-8ded-437d-9224-7601b95777f1)
- Show all stored logs command: `$ hydra investigate show-logs 5ad966f5-8ded-437d-9224-7601b95777f1`

## Logs:
- **db-cluster-5ad966f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/db-cluster-5ad966f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/db-cluster-5ad966f5.tar.gz)
- **monitor-set-5ad966f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/monitor-set-5ad966f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/monitor-set-5ad966f5.tar.gz)
- **loader-set-5ad966f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/loader-set-5ad966f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/loader-set-5ad966f5.tar.gz)
- **sct-runner-5ad966f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/sct-runner-5ad966f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/sct-runner-5ad966f5.tar.gz)
- **parallel-timelines-report-5ad966f5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/parallel-timelines-report-5ad966f5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5ad966f5-8ded-437d-9224-7601b95777f1/20220517_154736/parallel-timelines-report-5ad966f5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-harry-2h-test/13/)

### PR DESCRIPTION
**Pull request by michoecho**
reconcilable_result_builder passes range tombstone changes to _rt_assembler
using table schema, not query schema.
This means that a tombstone with bounds (a; b), where a < b in query schema
but a > b in table schema, will not be emitted from mutation_query.

This is a very serious bug, because it means that such tombstones in reverse
queries are not reconciled with data from other replicas.
If *any* queried replica has a row, but not the range tombstone which deleted
the row, the reconciled result will contain the deleted row.

In particular, range deletes performed while a replica is down will not
later be visible to reverse queries which select this replica, regardless of the
consistency level.

As far as I can see, this doesn't result in any persistent data loss.
Only in that some data might appear resurrected to reverse queries,
until the relevant range tombstone is fully repaired.

This series fixes the bug and adds a minimal reproducer test.

Fixes #10598

### CODE REVIEW

File: mutation_query.hh [hunk 1]
```diff
@@ -121,6 +121,8 @@ class reconcilable_result_builder {
     const schema& _schema;
     const query::partition_slice& _slice;
     bool _reversed;
+    schema_ptr _query_schema_storage; // Engaged only if _reversed.
+    const schema& _query_schema; // If _reversed, equal to *_query_schema_storage. Otherwise, equal to _schema.
```
Comment (denesb) [inline mutation_query.hh:125]: This is unneeded complication, considering the small difference between a reference and a shared ptr instance. Just have a `schema_ptr _query_schema` always.

**Review by denesb — APPROVED** [review]
One minor comment, LGTM otherwise.

File: mutation_query.hh (hunk 1 above)
Comment (michoecho) [reply mutation_query.hh:125]: I wanted to do that, but how do I initialize the `schema_ptr _query_schema` if the query isn't reversed? The constructor doesn't take a `schema_ptr`, only a `const schema&`.

So I see 4 options:
1. Change the constructor (and recursively all its callers) to pass `schema_ptr` instead of `const schema&).
2. Convert the reference to a `shared_ptr` via `shared_from_this()`. But is this legal? How do I know it's always legal?
3. Copy the schema, which IIUC isn't that cheap. (We do it in the reverse case, but I guess we would like to avoid it in the non-reverse case).
4. Do what I did.

Which should I choose?

Comment (denesb) [reply mutation_query.hh:125]: > 2. Convert the reference to a shared_ptr via shared_from_this(). But is this legal? How do I know it's always legal?

This is the way to go. This is always legal. All schemas are shared ptr.

In general, if a class offers, `shared_from_this()`, it **must** always be legal to use it, otherwise it is useless.

Comment (michoecho) [reply mutation_query.hh:125]: Alright.

**Review by bhalevy — APPROVED** [review]
LGTM, thanks

**Review by denesb — APPROVED** [review]

**Comment by michoecho** [comment]
> Failed Tests (2/21816):
> [test_not_created_compaction_task_abort](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4609/testReport/junit/%28root%29/test_compaction_task/Tests___Unit_Tests___test_not_created_compaction_task_abort) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_not_created_compaction_task_abort)
> [rest_api.test_compaction_task.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4609/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___rest_api_test_compaction_task_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+rest_api.test_compaction_task.dev.2)
    
Seems unrelated. Looks like https://github.com/scylladb/scylladb/issues/16005.

**Comment by bhalevy** [comment]
@michoecho please rebase.
@tgrabiec would you like to review before merging?

**Comment by avikivity** [comment]
It was already reviewed, but the unit tests keep failing.

**Comment by michoecho** [comment]
> @michoecho please rebase.

Why would I have to rebase? The CI is supposed to run on the merge of the PR with the target branch, not on the PR itself.
I would have to rebase if there were merge conflicts, but not if I only want to get some CI fixes from master.

I just retriggered the CI (without rebase).
