### PR TITLE
sstables: Fix quadratic space complexity in partitioned_sstable_set

### LINKED ISSUE #23634: partitioned_sstable_set has quadratic space usage if fed small sstables (smaller than the compaction strategy fragment size)
During normal operation, memtable flushes go into _unleveled and after compaction sstables are promoted into _leveled.

However, after a restart they all go into _leveled. If it happens that we had a lot of unleveled sstables (due to a bug), partitioned_sstable_set can go into quadratic memory consumption mode, since practically all sstables overlap.

### PR DESCRIPTION
**Pull request by raphaelsc**
Interval map is very susceptible to quadratic space behavior when it's flooded with many entries overlapping all (or most of) intervals, since each such entry will have presence on all intervals it overlaps with.

A trigger we observed was memtable flush storm, which creates many small "L0" sstables that spans roughly the entire token range.

Since we cannot rely on insertion order, solution will be about storing sstables with such wide ranges in a vector (unleveled).

There should be no consequence for single-key reads, since upper layer applies an additional filtering based on token of key being queried.
And for range scans, there can be an increase in memory usage, but not significant because the sstables span an wide range and would have been selected in the combined reader if the range of scan overlaps with them.

Anyway, this is a protection against storm of memtable flushes and shouldn't be the common scenario.

It works both with tablets and vnodes, by adjusting the token range spanned by compaction group accordingly.

Fixes #23634.

We can backport this into 2024.2, 2025.1, but we should let this cook in master for 1 month or so.

### CODE REVIEW

File: dht/i_partitioner.cc [hunk 1]
```diff
@@ -535,6 +535,27 @@ auto_refreshing_sharder::token_for_next_shard_for_reads(const dht::token& t, sha
     return _sharder->token_for_next_shard_for_reads(t, shard, spans);
 }
 
+double overlap_ratio(const dht::token_range& base, const dht::token_range& other) {
+    auto bound_range = [] (const token_range& tr) {
+        auto start = tr.start() ? *tr.start() : first_token();
+        auto end = tr.end() ? *tr.end() : last_token();
+        return dht::token_range::make(start, end);
+    };
```
Comment (avikivity) [inline dht/i_partitioner.cc:543]: You could intersect with [first_token, last_token].

Comment (avikivity) [reply dht/i_partitioner.cc:543]: This would preserve inclusive/exclusiveness.

File: dht/i_partitioner.cc [hunk 2]
```diff
@@ -535,6 +535,27 @@ auto_refreshing_sharder::token_for_next_shard_for_reads(const dht::token& t, sha
...
+    auto bounded_base = bound_range(base);
+    auto bounded_other = bound_range(other);
+
+    // intersection of two bounded intervals should never yield an interval with unbounded range.
+    auto intersection = bounded_base.intersection(bounded_other, token_comparator());
+    if (!intersection) {
+        return 0.0;
+    }
+    auto size_of_bounded_range = [] (const token_range& tr) {
+        return token::to_int64(tr.end()->value()) - token::to_int64(tr.start()->value());
```
Comment (avikivity) [inline dht/i_partitioner.cc:553]: This can overflow. Better to cast to uint64_t before the subtraction.

File: dht/i_partitioner.cc [hunk 3]
```diff
@@ -535,6 +535,27 @@ auto_refreshing_sharder::token_for_next_shard_for_reads(const dht::token& t, sha
...
+    };
+
+    return size_of_bounded_range(*intersection) / size_of_bounded_range(bounded_base);
```
Comment (avikivity) [inline dht/i_partitioner.cc:556]: And this needs to be a floating division, or it will overflow.

File: replica/table.cc [hunk 4]
```diff
@@ -680,7 +681,8 @@ class single_storage_group_manager final : public storage_group_manager {
         : _t(t)
     {
         storage_group_map r;
-        auto cg = make_lw_shared<compaction_group>(_t, size_t(0), dht::token_range::make_open_ended_both_sides());
+        auto full_token_range = dht::token_range::make(dht::first_token(), dht::last_token());
```
Comment (avikivity) [inline replica/table.cc:684]: This isn't completely accurate, the real limits are (first_vnode, last_vnode].

But it may be good enough. With 256 tokens first_vnode and last_vnode are likely to be within 0.5% of the edge. 

But please add a comment.

File: sstables/sstable_set.cc [hunk 5]
```diff
@@ -265,7 +265,12 @@ partitioned_sstable_set::query(const dht::partition_range& range) const {
 }
 
 bool partitioned_sstable_set::store_as_unleveled(const shared_sstable& sst) const {
-    return _use_level_metadata && sst->get_sstable_level() == 0;
+    // When a sstable spans most of the entire token range, we'll store it in a
+    // vector, to avoid triggering quadratic space complexity in the interval map,
+    // since many of such sstables would have presence on almost all intervals.
+    static constexpr float unleveled_threshold = 0.85f;
+    auto sst_tr = dht::token_range(sst->get_first_decorated_key().token(), sst->get_last_decorated_key().token());
+    return dht::overlap_ratio(_token_range, sst_tr) >= unleveled_threshold;
```
Comment (denesb) [inline sstables/sstable_set.cc:273]: Can we do something simpler instead and rely on sstable origin?
All sstables flushed from memtable would be considered unleveled and not inserted into the sstable set.
SStables flushed from memtables usually span the whole ring/tablet. After compaction, they either have constrained range (ICS) or are larger and we there are fewer of them so we can add them to the set anyway.

Comment (raphaelsc) [reply sstables/sstable_set.cc:273]: We thought about that. But during a flush storm, compaction output is still a small sized sstable spanning almost all the range. Using origin would miss this.

File: replica/table.cc (hunk 4 above)
Comment (raphaelsc) [reply replica/table.cc:684]: Maybe I can easily grab actual first and last token from the replication map. I will see. Otherwise, I will just explain it as you suggest.

**Comment by raphaelsc** [comment]
v2:
- rebased
- fixed overlap_ratio() to not overflow
- split the series
- moved PR to ready for review

File: sstables/sstable_set.cc [hunk 6]
```diff
@@ -265,7 +265,12 @@ partitioned_sstable_set::query(const dht::partition_range& range) const {
 }
 
 bool partitioned_sstable_set::store_as_unleveled(const shared_sstable& sst) const {
-    return _use_level_metadata && sst->get_sstable_level() == 0;
```
Comment (avikivity) [inline sstables/sstable_set.cc:268]: We can later get rid of _use_level_metadata.

**Comment by avikivity** [comment]
Looks good, but please add a dedicated test. We need to verify that unsplit sstables reach _unleveled and split sstables do not. For vnodes and tablets.

**Comment by raphaelsc** [comment]
v3: added test for stressing the change with both tablets and vnodes

**Comment by bhalevy** [comment]
@tgrabiec please review too and consider merging.
@avikivity please ack.

File: dht/i_partitioner.cc [hunk 7]
```diff
@@ -535,6 +535,30 @@ auto_refreshing_sharder::token_for_next_shard_for_reads(const dht::token& t, sha
...
+    auto intersection = bounded_base->intersection(*bounded_other, token_comparator());
+    if (!intersection) {
+        return 0.0;
+    }
+    auto size_of_bounded_range = [] (const token_range& tr) {
+        // uses unbiased token (uint64_t) to avoid overflow when calculating size
+        return tr.end()->value().unbias() - tr.start()->value().unbias();
+    };
+
+    return double(size_of_bounded_range(*intersection)) / size_of_bounded_range(*bounded_base);
```
Comment (bhalevy) [inline dht/i_partitioner.cc:559]: won't we have a problem with the conversion of large enough intersection to double precision?
tokens are 64-bit and double has only 52 bits for the significand

File: compaction/table_state.hh [hunk 8]
```diff
@@ -33,6 +33,7 @@ namespace compaction {
 class table_state {
 public:
     virtual ~table_state() {}
+    virtual dht::token_range token_range() const noexcept = 0;
```
Comment (bhalevy) [inline compaction/table_state.hh:36]: patch lacks motivation

File: test/cluster/test_sstable_set.py [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+    server = await manager.server_add(config=cfg, cmdline=cmdline)
+    await manager.api.disable_tablet_balancing(server.ip_addr)
+
+    cql = manager.get_cql()
+    await wait_for_cql_and_get_hosts(cql, [server], time.time() + 60)
+
+    if mode == 'tablet':
+        ks = await create_new_test_keyspace(cql, "WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND tablets = {'initial': 4};")
+    else:
+        ks = await create_new_test_keyspace(cql, "WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND tablets = {'enabled': 'false'};")
```
Comment (bhalevy) [inline test/cluster/test_sstable_set.py:35]: let's drop te keyspace at the end of the test to facilitate reuse of the cluster in the future.
Or you could use `async with new_test_keyspace` and just format the `WITH replication` extra stuff like
`f"WITH replication = {{'class': 'NetworkTopologyStrategy', 'replication_factor': 1}} AND tablets = {{{'\'initial\': 4' if mode=='tablet' else '\'enabled\': \'false\''}}}"`

**Review by avikivity — APPROVED** [review]

**Comment by avikivity** [comment]
> Please replace this line with justification for the backport/* labels added to this PR
?

There's no discussion of the inaccuracy with vnodes. The token range for vnodes is [min(this_node_tokens), max(this_node_tokens)], not the full range.

That's not a problem, but the patch should explain why.

**Comment by raphaelsc** [comment]
> > Please replace this line with justification for the backport/* labels added to this PR
> 
> ?
> 
> There's no discussion of the inaccuracy with vnodes. The token range for vnodes is [min(this_node_tokens), max(this_node_tokens)], not the full range.
> 
> That's not a problem, but the patch should explain why.

I left a comment exactly where we change vnodes to be [min, max], isn't it enough? I can add a sentence to the patch, can be good for someone reading the commit descriptions but not the changes themselves

**Comment by avikivity** [comment]
> > > Please replace this line with justification for the backport/* labels added to this PR
> > 
> > 
> > ?
> > There's no discussion of the inaccuracy with vnodes. The token range for vnodes is [min(this_node_tokens), max(this_node_tokens)], not the full range.
> > That's not a problem, but the patch should explain why.
> 
> I left a comment exactly where we change vnodes to be [min, max], isn't it enough? I can add a sentence to the patch, can be good for someone reading the commit descriptions but not the changes themselves

It's enough, I somehow missed it.

**Comment by raphaelsc** [comment]
v4: 
- rebased
- added motivation to patch that adds token_range()
- dropped keyspace in new test thinking forward to cluster reuse

**Review by bhalevy — APPROVED** [review]

**Comment by mykaul** [comment]
> > @dani-tweig what should we do with such cases? should we have automation for "delayed backport"?
> 
> @yaronkaikov , can we add a 'delayed backport' functionality to the automation? @avikivity, we will need to define the behaviour we want.

We should just open an issue for the backport work as a separate task to be done instead of the automation, which is not going to be very helpful here.

**Review by avikivity — APPROVED** [review]

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint are we still in merge freeze? otherwise, please consider merging.
