### PR TITLE
alterator::streams: Sort tables in list_streams to ensure no duplicates

### LINKED ISSUE #12601: alternator test_list_streams_limit_parameter: Got unexpected ARN values by list streams paged responses
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/181/testReport/alternator_stream_tests/TestAlternatorStreams/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split005___test_list_streams_limit_parameter/
Scylla 0d64f327e1af
```
self = <alternator_stream_tests.TestAlternatorStreams object at 0x7fc78f183b10>

    def test_list_streams_limit_parameter(self):
        """
        Test the list_streams command limit parameter.
        See that when the response is large enough, it can be paged
        correctly according the 'limit' value.
        Test steps:
        1. create and enable streams for 20 tables.
        2. read variable size chunks of these tables streams in list_streams command via random node.
        3. where using and verifying different 'limit' values + its total output.
        """
        stream_specification = enums.StreamSpecification.KEYS_ONLY.value
        self.prepare_dynamodb_cluster(num_of_nodes=3)
        node1 = self.cluster.nodelist()[0]
        table_names = [TABLE_NAME+str(idx) for idx in range(20)]
        for table_name in table_names:
            self.create_table(node=node1, table_name=table_name, stream_specification=stream_specification)
        tables_arns = [self.wait_for_active_stream(node=node1, table_name=table_name)[0] for table_name in table_names]
        total_limited_stream_responses = []
        last_evaluated_stream_arn = None
        for limit in [5, 7, 3, 1, 4]:  # slice the created 20 tables to various size chunks
            params = {'Limit': limit}
            if last_evaluated_stream_arn:
                params['ExclusiveStartStreamArn'] = last_evaluated_stream_arn
            dynamodb_api = self.get_dynamodb_api(node=random.choice(self.cluster.nodelist()))
            result = dynamodb_api.stream.list_streams(**params)
            assert len(result['Streams']) == limit, \
                f"Got unexpected number of streams [{len(result['Streams'])}] for [{limit}] requested!"
            total_limited_stream_responses += result['Streams']
            last_evaluated_stream_arn = result['LastEvaluatedStreamArn']
>       assert sorted(tables_arns) == sorted([stream['StreamArn'] for stream in total_limited_stream_responses]), \
            f"Got unexpected ARN values by list streams paged responses: {total_limited_stream_responses}"
E       AssertionError: Got unexpected ARN values by list streams paged responses: [{'StreamArn': 'Sea454df3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table19', 'StreamLabel': '"2023-01-21T05:53:23Z"'}, {'StreamArn': 'Se8c14603-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table17', 'StreamLabel': '"2023-01-21T05:53:20Z"'}, {'StreamArn': 'Se8255423-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table16', 'StreamLabel': '"2023-01-21T05:53:19Z"'}, {'StreamArn': 'Se351fa23-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table11', 'StreamLabel': '"2023-01-21T05:53:11Z"'}, {'StreamArn': 'Se2b67d73-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table10', 'StreamLabel': '"2023-01-21T05:53:10Z"'}, {'StreamArn': 'Se1335fe0-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table8', 'StreamLabel': '"2023-01-21T05:53:07Z"'}, {'StreamArn': 'Sdfabae73-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table5', 'StreamLabel': '"2023-01-21T05:53:05Z"'}, {'StreamArn': 'Sdec37153-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table4', 'StreamLabel': '"2023-01-21T05:53:03Z"'}, {'StreamArn': 'Sdd8bdbb3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table2', 'StreamLabel': '"2023-01-21T05:53:01Z"'}, {'StreamArn': 'Sdc9f58d3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table0', 'StreamLabel': '"2023-01-21T05:53:00Z"'}, {'StreamArn': 'Se047a053-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table6', 'StreamLabel': '"2023-01-21T05:53:06Z"'}, {'StreamArn': 'Se5bd06b3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table14', 'StreamLabel': '"2023-01-21T05:53:15Z"'}, {'StreamArn': 'Se4d53ec3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table13', 'StreamLabel': '"2023-01-21T05:53:13Z"'}, {'StreamArn': 'Se6f119e3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table15', 'StreamLabel': '"2023-01-21T05:53:17Z"'}, {'StreamArn': 'Sde27a680-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table3', 'StreamLabel': '"2023-01-21T05:53:02Z"'}, {'StreamArn': 'Se3ed76d3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table12', 'StreamLabel': '"2023-01-21T05:53:12Z"'}, {'StreamArn': 'Se1ceb583-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table9', 'StreamLabel': '"2023-01-21T05:53:08Z"'}, {'StreamArn': 'Se95d37e3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table18', 'StreamLabel': '"2023-01-21T05:53:21Z"'}, {'StreamArn': 'Se047a053-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table6', 'StreamLabel': '"2023-01-21T05:53:06Z"'}, {'StreamArn': 'Se09746f3-994f-11ed-9121-b5f2c5bf5f97', 'TableName': 'user_table7', 'StreamLabel': '"2023-01-21T05:53:06Z"'}]
E       assert ['Sdc9f58d3-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdd3c8333-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdd8bdbb3-994f-11ed-9121-b5f2c5bf5f97',\n 'Sde27a680-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdec37153-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdfabae73-994f-11ed-9121-b5f2c5bf5f97',\n 'Se047a053-994f-11ed-9121-b5f2c5bf5f97',\n 'Se09746f3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se1335fe0-994f-11ed-9121-b5f2c5bf5f97',\n 'Se1ceb583-994f-11ed-9121-b5f2c5bf5f97',\n 'Se2b67d73-994f-11ed-9121-b5f2c5bf5f97',\n 'Se351fa23-994f-11ed-9121-b5f2c5bf5f97',\n 'Se3ed76d3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se4d53ec3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se5bd06b3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se6f119e3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se8255423-994f-11ed-9121-b5f2c5bf5f97',\n 'Se8c14603-994f-11ed-9121-b5f2c5bf5f97',\n 'Se95d37e3-994f-11ed-9121-b5f2c5bf5f97',\n 'Sea454df3-994f-11ed-9121-b5f2c5bf5f97'] == ['Sdc9f58d3-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdd8bdbb3-994f-11ed-9121-b5f2c5bf5f97',\n 'Sde27a680-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdec37153-994f-11ed-9121-b5f2c5bf5f97',\n 'Sdfabae73-994f-11ed-9121-b5f2c5bf5f97',\n 'Se047a053-994f-11ed-9121-b5f2c5bf5f97',\n 'Se047a053-994f-11ed-9121-b5f2c5bf5f97',\n 'Se09746f3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se1335fe0-994f-11ed-9121-b5f2c5bf5f97',\n 'Se1ceb583-994f-11ed-9121-b5f2c5bf5f97',\n 'Se2b67d73-994f-11ed-9121-b5f2c5bf5f97',\n 'Se351fa23-994f-11ed-9121-b5f2c5bf5f97',\n 'Se3ed76d3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se4d53ec3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se5bd06b3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se6f119e3-994f-11ed-9121-b5f2c5bf5f97',\n 'Se8255423-994f-11ed-9121-b5f2c5bf5f97',\n 'Se8c14603-994f-11ed-9121-b5f2c5bf5f97',\n 'Se95d37e3-994f-11ed-9121-b5f2c5bf5f97',\n 'Sea454df3-994f-11ed-9121-b5f2c5bf5f97']
E         At index 1 diff: 'Sdd3c8333-994f-11ed-9121-b5f2c5bf5f97' != 'Sdd8bdbb3-994f-11ed-9121-b5f2c5bf5f97'
E         Full diff:
E           [
E            'Sdc9f58d3-994f-11ed-9121-b5f2c5bf5f97',
E         +  'Sdd3c8333-994f-11ed-9121-b5f2c5bf5f97',
E            'Sdd8bdbb3-994f-11ed-9121-b5f2c5bf5f97',
E            'Sde27a680-994f-11ed-9121-b5f2c5bf5f97',
E            'Sdec37153-994f-11ed-9121-b5f2c5bf5f97',
E            'Sdfabae73-994f-11ed-9121-b5f2c5bf5f97',
E         -  'Se047a053-994f-11ed-9121-b5f2c5bf5f97',
E            'Se047a053-994f-11ed-9121-b5f2c5bf5f97',
E            'Se09746f3-994f-11ed-9121-b5f2c5bf5f97',
E            'Se1335fe0-994f-11ed-9121-b5f2c5bf5f97',
E            'Se1ceb583-994f-11ed-9121-b5f2c5bf5f97',
E            'Se2b67d73-994f-11ed-9121-b5f2c5bf5f97',
E            'Se351fa23-994f-11ed-9121-b5f2c5bf5f97',
E            'Se3ed76d3-994f-11ed-9121-b5f2c5bf5f97',
E            'Se4d53ec3-994f-11ed-9121-b5f2c5bf5f97',
E            'Se5bd06b3-994f-11ed-9121-b5f2c5bf5f97',
E            'Se6f119e3-994f-11ed-9121-b5f2c5bf5f97',
E            'Se8255423-994f-11ed-9121-b5f2c5bf5f97',
E            'Se8c14603-994f-11ed-9121-b5f2c5bf5f97',
E            'Se95d37e3-994f-11ed-9121-b5f2c5bf5f97',
E            'Sea454df3-994f-11ed-9121-b5f2c5bf5f97',
E           ]

alternator_stream_tests.py:135: AssertionError
```

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #12601 (maybe?)

Sort the set of tables on ID. This should ensure we never generate duplicates in a paged listing here. Can obviously miss things if they are added between paged calls and end up with a "smaller" UUID/ARN, but that is to be expected.

### CODE REVIEW

File: alternator/streams.cc [hunk 1]
```diff
@@ -145,19 +145,24 @@ future<alternator::executor::request_return_type> alternator::executor::list_str
...
     }
 
-    // TODO: the unordered_map here is not really well suited for partial
-    // querying - we're sorting on local hash order, and creating a table
-    // between queries may or may not miss info. But that should be rare,
-    // and we can probably expect this to be a single call.
+    // # 12601 (maybe?) - sort the set of tables on ID. This should ensure we never
+    // generate duplicates in a paged listing here. Can obviously miss things if they 
+    // are added between paged calls and end up with a "smaller" UUID/ARN, but that 
+    // is to be expected.
```
Comment (nyh) [inline alternator/streams.cc:156]: I don't think that "duplicates" is necessarily the main issue here. I think the point is that the list of tables may be sorted differently at different times, so we can't continue "after" some id X in the next if the meaning of "after" changed between pages. We can get the same result more than once, and not get other results (we saw this in 12601). We can also get the wrong number of results. In fact, I'm a bit worried that in 12601 we only saw a small error - it could have been much worse (with many duplicates and/or missing items), so I hope this is really this bug and not something else.

**Review by nyh — APPROVED** [review]

File: alternator/streams.cc (hunk 1 above)
Comment (elcallio) [reply alternator/streams.cc:156]: Duplicates in the sense that we report a stream twice, because relative position of "last" changes. Obviously can also miss entries even though they existed before we started paging. But that is "better" in the sense that we are still showing a coherent set (and given that streams. Still not good of course. 
Also hope this fixes the issue. Hard to know.

File: alternator/streams.cc [hunk 2]
```diff
@@ -145,19 +145,24 @@ future<alternator::executor::request_return_type> alternator::executor::list_str
...
+    std::sort(cfs.begin(), cfs.end(), [](const data_dictionary::table& t1, const data_dictionary::table& t2) {
+        return t1.schema()->id().uuid() < t2.schema()->id().uuid();
+    });
+
```
Comment (avikivity) [inline alternator/streams.cc:160]: The whole thing (even before the patch) has quadratic complexity, now it's O(n^2 log n). The number of pages is O(n), copying the tables from data_dictionary is O(n), and now this sort is O(n log n).

It doesn't matter if the number of pages is always very low. Is this the case? A different way to phrase the question: how many tables can a page contain?

If it's a problem, we'll need to define an iterative interface to data_dictionary that has a consistent sort order.

File: alternator/streams.cc [hunk 3]
```diff
@@ -145,19 +145,24 @@ future<alternator::executor::request_return_type> alternator::executor::list_str
...
+    auto i = cfs.begin();
+    auto e = cfs.end();
+
     if (streams_start) {
-        i = std::find_if(i, e, [&](data_dictionary::table t) {
+        i = std::find_if(i, e, [&](const data_dictionary::table& t) {
```
Comment (avikivity) [inline alternator/streams.cc:165]: data_dictionary and friends were designed to be cheap to copy.

Comment (elcallio) [reply alternator/streams.cc:165]: Yes, can see that. But also not needed, as we don't cause continuations or anything, and don't need to defensively copy stuff. Reference unless pointer me says. Also for symmetry with sorter.

File: alternator/streams.cc (hunk 2 above)
Comment (nyh) [reply alternator/streams.cc:160]: ‎The "typical" case is to have an unlimited or very large page size and a "reasonably small" number of tables (Scylla doesn't support a huge number of tables anyway), and call ListStreams only rarely if at all, so the performance of this doesn't matter. But I agree that in the worst case doing ListStreams in tiny pages now needs O(n^2 log n), which isn't much worse than O(n^2). You're right that it would be nice for db::get_tables(), which already returns a vector with some order - to say something about this order. Or create a new function that returns the list in a consistent order. The question is how to do this efficiently (maybe replace the unsorted map of tables by a sorted map?).

@elcallio looking at the code again there is something that concerns me even more. I assume that almost always, ListStreams will be called for a specific table. Ideally in this case, it should be O(1), not O(n log n) . But currently it isn't - we iterate over all tables (after sorting them). Couldn't we find a way to make it O(1)? I think this case will be much more common then listing all the streams of all the tables in the system.

File: alternator/streams.cc [hunk 4]
```diff
@@ -145,19 +145,24 @@ future<alternator::executor::request_return_type> alternator::executor::list_str
...
 
-    // TODO: the unordered_map here is not really well suited for partial
-    // querying - we're sorting on local hash order, and creating a table
-    // between queries may or may not miss info. But that should be rare,
-    // and we can probably expect this to be a single call.
+    // # 12601 (maybe?) - sort the set of tables on ID. This should ensure we never
+    // generate duplicates in a paged listing here. Can obviously miss things if they 
+    // are added between paged calls and end up with a "smaller" UUID/ARN, but that 
+    // is to be expected.
+    std::sort(cfs.begin(), cfs.end(), [](const data_dictionary::table& t1, const data_dictionary::table& t2) {
```
Comment (nyh) [inline alternator/streams.cc:157]: @elcallio a thought: If neither Limit nor ExclusiveStartStreamArn are given, I think we can simply not do this sort. It will reduce the complexity of this single-page case from O(nlogn) to O(n).
This will be common when the TableName is given in the query and only one result is expected anyway (a separate issue is that this case should be O(1), not O(n), but let's at least not make it o(nlogn).

File: alternator/streams.cc (hunk 3 above)
Comment (avikivity) [reply alternator/streams.cc:165]: My comment from an aesthetic perspective, less const and & things. I don't mind the change.

File: alternator/streams.cc (hunk 2 above)
Comment (elcallio) [reply alternator/streams.cc:160]: If we only query one table, even the copy of "tables" seems excessive. Technically, we could just check if a CDC table exists for the given table, and just return it. 

Indeed the default paging is in fact unlimited here. I wonder if this is ok, since we are supposed to be limited in how much payload we can generate in a single call, no? But again, not exactly heavy on the output this method. 

I am not sure if this method is such a hotspot though, so not eager to optimize it too much until shown its needed. Again, iterating ~100 tables now and then is just good for the cpu (get some air). :-)

File: alternator/streams.cc (hunk 3 above)
Comment (elcallio) [reply alternator/streams.cc:165]: More const == more goodness! :-)

File: alternator/streams.cc (hunk 4 above)
Comment (elcallio) [reply alternator/streams.cc:157]: True, but should we not make this a separate fix?

File: alternator/streams.cc (hunk 2 above)
Comment (avikivity) [reply alternator/streams.cc:160]: Maybe all we need is some yields to avoid stalls (but need to exercise care in case the schema is updated while we yield).

**Comment by elcallio** [comment]
Added patches to remove sorting and iterating when not required.

File: alternator/streams.cc [hunk 5]
```diff
@@ -140,7 +140,7 @@ namespace alternator {
 future<alternator::executor::request_return_type> alternator::executor::list_streams(client_state& client_state, service_permit permit, rjson::value request) {
     _stats.api_operations.list_streams++;
 
-    auto limit = rjson::get_opt<int>(request, "Limit").value_or(std::numeric_limits<int>::max());
+    auto limit = rjson::get_opt<int>(request, "Limit").value_or(100);
```
Comment (nyh) [inline alternator/streams.cc:144]: An interesting question is what happens on DynamoDB if you try to set a limit higher than 100. As usual, I'll write a test to check and let you know :-)

**Review by nyh — APPROVED** [review]
Looks great to me. @avikivity is there anything from your comments that you wanted answered before merging this?

File: alternator/streams.cc (hunk 5 above)
Comment (nyh) [reply alternator/streams.cc:144]: As I understood from the documentation, 100 is not only DynamoDB's default limit, it is also the maximum allowed. If you try 101 it complains with a ValidationException: "One or more parameter values were invalid: Limit cannot be greater than the maximum allowed size: 100".

A test for this:
```python
def test_list_streams_too_high_limit(dynamodb, dynamodbstreams):
    with create_stream_test_table(dynamodb, StreamViewType='KEYS_ONLY') as table:
        with pytest.raises(ClientError, match='ValidationException'):
            wait_for_active_stream(dynamodbstreams, table)
            dynamodbstreams.list_streams(Limit=101)

```

If you want to make this PR even better, perhaps you can do that?

Comment (elcallio) [reply alternator/streams.cc:144]: I considered it, but then we should change some other places which allow much higher limits than Dynamo as well. And this in turn would break our dtests etc which apparently use limits of 1000 or so. Probably to get around the insane number of shards Scylla generates and all the round tripping it entails. I don't think we really need to ensure _limitations_ are equal to AWS do we? Just defaults...

Comment (nyh) [reply alternator/streams.cc:144]: Anyway, never mind about this now. I'll send a separate patch for testing (and/or changing) this aspect.

Comment (nyh) [reply alternator/streams.cc:144]: Sent https://github.com/scylladb/scylladb/pull/12625

**Comment by nyh** [comment]
The CI restart didn't restart (?) - I'll try again

**Comment by nyh** [comment]
The spurious CI failures last week caused me to forget to merge this PR, sorry about that. Did it now.
After this goes in I'll send my tests for it (https://github.com/scylladb/scylladb/pull/12616).
