### PR TITLE
cql: create default superuser if it doesn't exist

### LINKED ISSUE #10481: Create default ("superuser") role before accepting CQL commands
@kostja noticed in https://github.com/scylladb/scylla/pull/10406 that when Scylla is run with `--authenticator PasswordAuthenticator` Scylla may become responsive to CQL requests before the default (a.k.a. "superuser") user cassandra/cassandra is set up - so CQL is still not usable for a while longer, until this user is finally set up.

This a bug - CQL should not become responsive before it is expected to work correctly. Users should not experience "invalid request" errors even temporarily while a node is coming up.

Looking at the code I can't seem to find the cause of this bug (@kostja, maybe you found it?), the code in main.cc creates an auth service and calls its `start()` and wait for it to complete. This in turn (see `auth/service.cc`)  calls the role manager's `start()` function and waits for it to complete. The `standard_role_manager::start()` function (in `auth/standard_role_manager.cc`) calls `create_default_role_if_missing()` to create the default role and seems to wait on one shard for it to happen (and since main.cc waits for all shards to complete the start(), that is enough). `create_default_role_if_missing()` also seems to wait for the query that it invokes to complete.

@kostja reproduced this bug in a new test-running code (https://github.com/scylladb/scylla/pull/10406) which started Scylla and quickly sent requests when CQL was available (but apparently before the "cassandra" user become available). I haven't yet been able to reproduce it in the existing test/cql-pytest/run, although if this bug exists, test/cql-pytest/run should be vulnerable to this problem just the same.

### PR DESCRIPTION
**Pull request by KrzaQ**
This change reorganizes the way standard_role_manager startup is handled: role_manager::ensure_superuser_is_created() is added, which returns a future that resolves once the superuser is available. We wait for this future before starting the CQL server.

There is a change in behavior auth::do_after_system_ready is potentially an infinite loop, and we await its result.

Fixes #10481

Reason for no backports: it's not a regresson and it's an issue that may only affect a tiny time window during the cluster startup.

### CODE REVIEW

File: auth/standard_role_manager.cc [hunk 1]
```diff
@@ -248,9 +248,13 @@ future<> standard_role_manager::start() {
             }
             return make_ready_future<>();
         }).then([this] {
-            _stopped = auth::do_after_system_ready(_as, [this] {
-                return seastar::async([this] {
-                    if (legacy_mode(_qp)) {
+            auto work_done = seastar::make_lw_shared<seastar::promise<>>();
+            auto ret = work_done->get_future();
+            _stopped = auth::do_after_system_ready(_as, [this, work_done] mutable {
```
Comment (avikivity) [inline auth/standard_role_manager.cc:253]: I think the code can be simplified by assigning the return value of do_after_system_ready() to a shared_future, which can then be copies to _stopped and ret.

But, do we even need _stopped? If start() waits for do_after_system_ready, why do we need stopped()? There's no work to wait for.

File: main.cc [hunk 2]
```diff
@@ -1781,10 +1781,8 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
 
             auto start_auth_service = [&mm] (sharded<auth::service>& auth_service, std::any& stop_auth_service, const char* what) {
                 supervisor::notify(fmt::format("starting {}", what));
-                auth_service.invoke_on_all(&auth::service::start, std::ref(mm), std::ref(sys_ks)).get();
-
-                stop_auth_service = defer_verbose_shutdown(what, [&auth_service] {
-                    auth_service.stop().get();
+                return auth_service.invoke_on_all(&auth::service::start, std::ref(mm), std::ref(sys_ks)).then([&, w = what] {
+                    stop_auth_service = defer_verbose_shutdown(w, [&auth_service] { auth_service.stop().get(); });
                 });
```
Comment (avikivity) [inline main.cc:1786]: I don't understand why this change is necessary. It looks like a no-op.

**Comment by avikivity** [comment]
This has the effect that a node starting without group0 won't open its CQL connection. Or maybe the check whether the superuser exists is done using a local read, and we only hang if it doesn't (which would only happen during auth transition)? Please clarify.

**Review by nuivall — CHANGES_REQUESTED** [review]
I think the original idea for the fix was a bit different.
1. Why not create user while group0 is being created? This would be aprox. once per cluster bootstrap, and I suspect in such case waiting logic is already there (to verify this).
2. Also if I recall you need to take https://github.com/scylladb/scylladb/issues/10481#issuecomment-2144594369 into account, I think password is being inserted in a separate statement, so the same problem exists for password as well (can't login before initial password is inserted).

**Comment by avikivity** [comment]
> I think the original idea for the fix was a bit different.
> 
> 1. Why not create user while group0 is being created? This would be aprox. once per cluster bootstrap, and I suspect in such case waiting logic is already there (to verify this).

Some clusters are created without auth, and auth is added later. The first node to recognize that auth is needed must create the superuser. Currently this is always on restart, but if we were to ever make it LiveUpdate then it would not be on restart.

This suggests that we don't really need to wait during restart.

> 2. Also if I recall you need to take [Create default ("superuser") role before accepting CQL commands #10481 (comment)](https://github.com/scylladb/scylladb/issues/10481#issuecomment-2144594369) into account, I think password is being inserted in a separate statement, so the same problem exists for password as well (can't login before initial password is inserted).

**Comment by nuivall** [comment]
> > I think the original idea for the fix was a bit different.
> > 
> > 1. Why not create user while group0 is being created? This would be aprox. once per cluster bootstrap, and I suspect in such case waiting logic is already there (to verify this).
> 
> Some clusters are created without auth, and auth is added later. The first node to recognize that auth is needed must create the superuser. Currently this is always on restart, but if we were to ever make it LiveUpdate then it would not be on restart.
> 

Yes, forgot about this. But still maybe we can tie it to raft leader selection somehow. If I understand the flow during startup we'd wait for the leader, correct?

If so we can place creation logic on the leader and then other nodes would pull it via raft log before they start.

I think we need to solve this in a generic way because metadata initialization problem occurs also in other components.

Some flavor of this was auth-v2 enablement migration code trigger, we ended up placing the check in loading snapshot code but it was a hack (used already by something else).

> This suggests that we don't really need to wait during restart.
> 

I theory during the procedures we have something like `cqlsh -u cassandra -p cassandra` and this can fail. User can retry sure, but it's confusing. I assume in practice it works because user is slower than our async code.

**Comment by avikivity** [comment]
> > > I think the original idea for the fix was a bit different.
> > > 
> > > 1. Why not create user while group0 is being created? This would be aprox. once per cluster bootstrap, and I suspect in such case waiting logic is already there (to verify this).
> > 
> > 
> > Some clusters are created without auth, and auth is added later. The first node to recognize that auth is needed must create the superuser. Currently this is always on restart, but if we were to ever make it LiveUpdate then it would not be on restart.
> 
> Yes, forgot about this. But still maybe we can tie it to raft leader selection somehow. If I understand the flow during startup we'd wait for the leader, correct?

We wait to join the raft group, not for leader election. But again, if we ever make this LiveUpdate::yes we wouldn't have some point to synchronize to.

> 
> If so we can place creation logic on the leader and then other nodes would pull it via raft log before they start.
> 
> I think we need to solve this in a generic way because metadata initialization problem occurs also in other components.
> 
> Some flavor of this was auth-v2 enablement migration code trigger, we ended up placing the check in loading snapshot code but it was a hack (used already by something else).
> 
> > This suggests that we don't really need to wait during restart.
> 
> I theory during the procedures we have something like `cqlsh -u cassandra -p cassandra` and this can fail. User can retry sure, but it's confusing. I assume in practice it works because user is slower than our async code.

We can enhance the procedures to wait for something first.

File: test/topology/suite.yaml [hunk 3]
```diff
@@ -1,7 +1,7 @@
 type: Topology
 pool_size: 4
 cluster:
-  initial_size: 3
+  initial_size: 2
```
Comment (avikivity) [inline test/topology/suite.yaml:4]: Why this change?

**Comment by avikivity** [comment]
> I think the original idea for the fix was a bit different.
> 
> 1. Why not create user while group0 is being created? This would be aprox. once per cluster bootstrap, and I suspect in such case waiting logic is already there (to verify this).

The point where we start using auth and the point where we create group0 are different. We may never use auth, or not use auth and then start using auth.

**Comment by avikivity** [comment]
> > > I think the original idea for the fix was a bit different.
> > > 
> > > 1. Why not create user while group0 is being created? This would be aprox. once per cluster bootstrap, and I suspect in such case waiting logic is already there (to verify this).
> > 
> > 
> > Some clusters are created without auth, and auth is added later. The first node to recognize that auth is needed must create the superuser. Currently this is always on restart, but if we were to ever make it LiveUpdate then it would not be on restart.
> > This suggests that we don't really need to wait during restart.
> > > 2. Also if I recall you need to take [Create default ("superuser") role before accepting CQL commands #10481 (comment)](https://github.com/scylladb/scylladb/issues/10481#issuecomment-2144594369) into account, I think password is being inserted in a separate statement, so the same problem exists for password as well (can't login before initial password is inserted).
> 
> @avikivity what is the harm of having the superuser role in clusters that have no auth?

Right now we always have standard_role_manager. But if that ever changes, or if the user changes auth_superuser_name after setting up the cluster but before enabling auth, they get surprising results.

**Comment by kostja** [comment]
@KrzaQ please explain in the commit comment why the patch is the correct and optimal way to address the problem. Specifically, incorporate Avi's explanation why adding the superuser role to the initial group0 snapshot is not the alternative you used, and explain that we're not attempting to add the role on restart if it is already present locally, and hence the change doesn't require a group0 read barrier, and hence a raft quorum, if the role already exists. It does, however, if the role doesn't exist, e.g. we changed from no auth to auth, and perform a resetart.

BTW, I still don't get why it's not feasible to just add the role to the initial snapshot in all cases, @avikivity could you please elaborate?

**Comment by kostja** [comment]
@avikivity authentication and authorizaiton are not the same thing. I don't see how we are ever going to not have a role model inside scylla. Which role we authenticte a connection to can be of course configurable. 

So I don't see why decouple the existence of the superuser role from the initial snapshot.

And regarding your comment that the initial snapshot use point and role use points are different, I don't get this either. We consoldiate both roles and objects inside group0 state. I always advocated that users are part of the schema, same as types - each database object has a creator, the user who created it, so you can't really have database objects without users.

**Comment by kostja** [comment]
PostgreSQL and MySQL system catalog created at bootstrap stores the initial users: 
https://www.postgresql.org/docs/current/view-pg-user.html
https://www.postgresql.org/docs/current/catalog-pg-init-privs.html

**Comment by avikivity** [comment]
> @KrzaQ please explain in the commit comment why the patch is the correct and optimal way to address the problem. Specifically, incorporate Avi's explanation why adding the superuser role to the initial group0 snapshot is not the alternative you used, and explain that we're not attempting to add the role on restart if it is already present locally, and hence the change doesn't require a group0 read barrier, and hence a raft quorum, if the role already exists. It does, however, if the role doesn't exist, e.g. we changed from no auth to auth, and perform a resetart.
> 
> BTW, I still don't get why it's not feasible to just add the role to the initial snapshot in all cases, @avikivity could you please elaborate?

The role manager is configurable:

```c++
static const class_registrator<
        role_manager,
        standard_role_manager,
        cql3::query_processor&,
        ::service::raft_group0_client&,
        ::service::migration_manager&> registration("org.apache.cassandra.auth.CassandraRoleManager");
```

so it should create its own roles.

We can decide that it's not configurable, and then it's okay to create the superuser outside the standard role manager, but I think it's wrong.

File: auth/standard_role_manager.cc [hunk 4]
```diff
@@ -266,9 +270,12 @@ future<> standard_role_manager::start() {
                             return;
                         }
                     }
-                    create_default_role_if_missing().get();
+                    create_default_role_if_missing().then([legacy, work_done] mutable {
+                        if (!legacy) work_done->set_value();
```
Comment (nuivall) [inline auth/standard_role_manager.cc:274]: I think we avoid omitting '{' for readability

**Comment by nuivall** [comment]
What about password issue, are you planning to fix it in separate PR or this one? Because the test problem will occur more or less the same w/o fixing it fully.

**Comment by kostja** [comment]
> > @KrzaQ please explain in the commit comment why the patch is the correct and optimal way to address the problem. Specifically, incorporate Avi's explanation why adding the superuser role to the initial group0 snapshot is not the alternative you used, and explain that we're not attempting to add the role on restart if it is already present locally, and hence the change doesn't require a group0 read barrier, and hence a raft quorum, if the role already exists. It does, however, if the role doesn't exist, e.g. we changed from no auth to auth, and perform a resetart.
> > BTW, I still don't get why it's not feasible to just add the role to the initial snapshot in all cases, @avikivity could you please elaborate?
> 
> The role manager is configurable:
> 
> ```c++
> static const class_registrator<
>         role_manager,
>         standard_role_manager,
>         cql3::query_processor&,
>         ::service::raft_group0_client&,
>         ::service::migration_manager&> registration("org.apache.cassandra.auth.CassandraRoleManager");
> ```
> 
> so it should create its own roles.
> 
> We can decide that it's not configurable, and then it's okay to create the superuser outside the standard role manager, but I think it's wrong.

Configuring or not configuring the pre-defined system roles should not be up to the role manager, especially since we have only one system role, superuser.

**Comment by ptrsmrn** [comment]
All comments have been addressed, the one remaining https://github.com/scylladb/scylladb/issues/20566 will be done as a follow up in a separate PR
@scylladb/scylla-maint can you please review/queue? The CI is green.

**Comment by ptrsmrn** [comment]
@scylladb/scylla-maint please consider reviewing/merging.

File: test/topology_experimental_raft/test_restart_cluster.py [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+    """Test that cluster can restart fine after all nodes are stopped gracefully"""
+    servers = await manager.servers_add(3)
+
+    logger.info(f"Servers {servers}, gracefully stopping servers {[s.server_id for s in servers]} to check if one will go up")
+    for s in servers:
+        await manager.server_stop_gracefully(s.server_id)
+
+    logger.info(f"Starting servers {[s.server_id for s in servers]}")
+    for s in servers:
+        await manager.server_start(s.server_id)
```
Comment (nuivall) [inline test/topology_experimental_raft/test_restart_cluster.py:29]: no need to `wait_for_cql_and_get_hosts`? in theory what you're doing you're adding something which prevents/delays CQL startup so it'd be nice to check that

File: auth/standard_role_manager.cc [hunk 6]
```diff
@@ -248,9 +248,13 @@ future<> standard_role_manager::start() {
             }
             return make_ready_future<>();
         }).then([this] {
-            _stopped = auth::do_after_system_ready(_as, [this] {
-                return seastar::async([this] {
-                    if (legacy_mode(_qp)) {
+            auto work_done = seastar::make_lw_shared<seastar::promise<>>();
```
Comment (nuivall) [inline auth/standard_role_manager.cc:251]: so you spawn async only to block it later? unless it's legacy because then you don't want to block

wouldn't  doing just:
if legacy(...) {
return seastar::async(...) /*current master's code here*/
}
return  create_default_role_if_missing(...);

have the same effect?

File: auth/standard_role_manager.cc [hunk 7]
```diff
@@ -266,9 +270,14 @@ future<> standard_role_manager::start() {
                             return;
                         }
                     }
-                    create_default_role_if_missing().get();
+                    create_default_role_if_missing().then([legacy, work_done] mutable {
+                        if (!legacy) {
```
Comment (nuivall) [inline auth/standard_role_manager.cc:274]: please avoid branching on legacy, it's written currently so that it'd be easy to drop it in the future, it's better to leave old flow intact.

currently the structure is usually:

if (legacy_mode) {
// old path
return
}
// new path

File: auth/standard_role_manager.cc (hunk 6 above)
Comment (nuivall) [reply auth/standard_role_manager.cc:251]: btw perhaps corotinizing (in separate commit) would make it easier to understand the flow

File: test/topology_experimental_raft/test_restart_cluster.py [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+import logging
+
+import pytest
+from test.pylib.manager_client import ManagerClient
+
+logger = logging.getLogger(__name__)
+
+
+@pytest.mark.asyncio
+async def test_restart_cluster(manager: ManagerClient) -> None:
```
Comment (avikivity) [inline test/topology_experimental_raft/test_restart_cluster.py:19]: Surprised we don't already have such a test.

**Review by avikivity — APPROVED** [review]

File: auth/standard_role_manager.cc (hunk 6 above)
Comment (nuivall) [reply auth/standard_role_manager.cc:251]: what do you mean? there is no `auto work_done` on master

File: main.cc [hunk 9]
```diff
@@ -1820,10 +1820,8 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
 
             auto start_auth_service = [&mm] (sharded<auth::service>& auth_service, std::any& stop_auth_service, const char* what) {
                 supervisor::notify(fmt::format("starting {}", what));
-                auth_service.invoke_on_all(&auth::service::start, std::ref(mm), std::ref(sys_ks)).get();
-
-                stop_auth_service = defer_verbose_shutdown(what, [&auth_service] {
-                    auth_service.stop().get();
+                return auth_service.invoke_on_all(&auth::service::start, std::ref(mm), std::ref(sys_ks)).then([&, w = what] {
```
Comment (xemul) [inline main.cc:1823]: Why do you need to move deferred action creation into .then() continuation?

File: main.cc [hunk 10]
```diff
@@ -2127,6 +2126,7 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
                 ss.local().drain_on_shutdown().get();
             });
 
+            auth_service_future.get();
```
Comment (xemul) [inline main.cc:2129]: It's a pity, that standard auth service start-shutdow-stop sequence is broken. Can you please introduce `future<> auth_service::ensure_superuser_is_created()` and explicitly call it here (or even better -- few lines above, where `db.invoke_on_all(&replica::database::revert_initial_system_read_concurrency_boost).get();` is called. The `auth_service` itself would need maintain the `promise<> superuser_created` and the `auth_service::start()` would start the needed background fiber to resolve it.

**Review by xemul — CHANGES_REQUESTED** [review]

File: auth/standard_role_manager.cc [hunk 11]
```diff
@@ -248,26 +248,24 @@ future<> standard_role_manager::start() {
...
-                        _migration_manager.wait_for_schema_agreement(_qp.db().real_database(), db::timeout_clock::time_point::max(), &_as).get();
-
-                        if (any_nondefault_role_row_satisfies(_qp, &has_can_login).get()) {
-                            if (legacy_metadata_exists()) {
-                                log.warn("Ignoring legacy user metadata since nondefault roles already exist.");
-                            }
-
-                            return;
-                        }
+            _stopped = auth::do_after_system_ready(_as, [this] () -> future<void>  {
```
Comment (nuivall) [inline auth/standard_role_manager.cc]: we typically type `future<>` instead of `future<void>`

File: auth/standard_role_manager.cc [hunk 12]
```diff
@@ -248,27 +248,26 @@ future<> standard_role_manager::start() {
...
                         }
+
+                        co_return;
                     }
-                    create_default_role_if_missing().get();
-                });
+
+                    if (legacy_metadata_exists()) {
+                        co_await migrate_legacy_metadata();
+                        co_return;
```
Comment (nuivall) [inline auth/standard_role_manager.cc:265]: hint, since co_await returns future you can do in one line, co_return co_await ...

File: auth/standard_role_manager.cc [hunk 13]
```diff
@@ -267,6 +267,7 @@ future<> standard_role_manager::start() {
                 }
                 co_await create_default_role_if_missing();
             });
+            return _stopped.then([] {});
```
Comment (nuivall) [inline auth/standard_role_manager.cc:270]: I'm not sure what `.then([] {})` is supposed to do?

File: auth/standard_role_manager.cc (hunk 12 above)
Comment (avikivity) [reply auth/standard_role_manager.cc:265]: IMO it's clearer this way. co_return co_await tells the reader we're calling migrate_legacy_metadata() and returning whatever it returns. Then the reader sees it returns void and has to feel stupid.

Returning void is useful for templates (which don't know what they return) but is bad for readability.

Comment (nuivall) [reply auth/standard_role_manager.cc:265]: at least it wouldn't compile if migrate_legacy_metadata returns something, current way best case there will be warning

but not important change anyway

File: auth/standard_role_manager.cc (hunk 13 above)
Comment (kbr-scylla) [reply auth/standard_role_manager.cc:270]: Well. After attaching a `then` to a future, the future becomes unusable. (Waiting for it again or trying to attach a different continuation is a bug, and IIRC it would trigger some assert in seastar.)

So it is basically equivalent to `return std::move(_stopped)`. But using `std::move` makes it a bit clearer that this future is no longer supposed to be used.

Comment (kbr-scylla) [reply auth/standard_role_manager.cc:270]: Probably even better: `return std::exchange(_stopped, make_ready_future<>())`

File: auth/standard_role_manager.cc [hunk 14]
```diff
@@ -278,6 +277,10 @@ future<> standard_role_manager::stop() {
     return _stopped.handle_exception_type([] (const sleep_aborted&) { }).handle_exception_type([](const abort_requested_exception&) {});;
 }
 
+future<> standard_role_manager::ensure_superuser_is_created() {
+    return _superuser_created.get_future();
```
Comment (nuivall) [inline auth/standard_role_manager.cc:281]: I wonder is it safe to call it several times? I see there is some assert `assert(!this->_future && this->_state && !this->_task);` 

Asking because `ensure_superuser_is_created` doesn't limit how many times it can be called.

File: main.cc [hunk 15]
```diff
@@ -2128,6 +2128,11 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
                 ss.local().drain_on_shutdown().get();
             });
 
+            auth_service.invoke_on_all([] (auth::service& auth_service) {
```
Comment (nuivall) [inline main.cc:2131]: what's the point of calling this on all shards?

File: auth/standard_role_manager.cc (hunk 14 above)
Comment (xemul) [reply auth/standard_role_manager.cc:281]: > I wonder is it safe to call it several times? 

No, it's not :) To make it safe one need to use shared_future-s or play games with some other indicator member (bool called_once or make _superuser_created a pointer)

Comment (nuivall) [reply auth/standard_role_manager.cc:281]: maybe semaphore would be enough instead of future+bool/flag ?

Comment (nuivall) [reply auth/standard_role_manager.cc]: seastar::semaphore::wait wouldn't do the job?

Comment (nuivall) [reply auth/standard_role_manager.cc]: you set it to 0, increment by 1 after superuser created, and wait in ensure_superuser_is_created. it would also serialize ensure_superuser_is_created calls but that's not a big problem

**Comment by kostja** [comment]
> Rebased on current master, responded to comments.
> 
> Awaiting superuser creation may create a busy-ish wait loop until it is created, but it can only happen during system startup and it's not a blocking loop.

Nevertheless it'd be best to avoid this loop, and @nuivall has suggested a method for that.

File: auth/standard_role_manager.cc [hunk 16]
```diff
@@ -250,26 +251,27 @@ future<> standard_role_manager::start() {
...
-                });
+
+                    if (legacy_metadata_exists()) {
+                        co_await migrate_legacy_metadata();
+                        _superuser_created.signal();
+                        co_return;
+                    }
+                }
+                co_await create_default_role_if_missing();
+                _superuser_created.signal();
```
Comment (nuivall) [inline auth/standard_role_manager.cc:274]: maybe single defer() in the right scope would be better?

like defer([](){ _superuser_created.signal()}

Comment (nuivall) [reply auth/standard_role_manager.cc:274]: also btw not sure what happens if exception is thrown during superuser creation, worth to make sure startup doesn't hang, it should terminate.

perhaps some glue with semaphore::broken is needed

Comment (nuivall) [reply auth/standard_role_manager.cc]: yes

File: auth/standard_role_manager.cc [hunk 17]
```diff
@@ -250,26 +251,26 @@ future<> standard_role_manager::start() {
...
-
-                        if (any_nondefault_role_row_satisfies(_qp, &has_can_login).get()) {
-                            if (legacy_metadata_exists()) {
-                                log.warn("Ignoring legacy user metadata since nondefault roles already exist.");
-                            }
-
-                            return;
-                        }
+            _stopped = auth::do_after_system_ready(_as, [this] () -> future<>  {
+                auto signal_super_user_created = defer([this] {
```
Comment (nuivall) [inline auth/standard_role_manager.cc:255]: is this for sure correct scope? maybe there is no good place to place defer, keep in mind that do_after_system_ready is potentially calling lambda several times due to retries

there are probably multiple ways to solve this, for instance attach it to the future returned by do_system_ready, like:

```
auth::do_after_system_ready(...).then_wrapped(future<> f) {
try {
f.get()
catch(...) { ...broken(); return; }
...signal()
});
```

Comment (nuivall) [reply auth/standard_role_manager.cc:255]: yes, no need to defer because if try block you will anyway have it in one place (after try block) and that was the point of using defer

Comment (nuivall) [reply auth/standard_role_manager.cc:255]: also you should be able to pass exception_ptr to broken(), so that it will be acted on startup instead as currently only on ::stop()

But *do* check how exception lifetime works as I am not sure if exception_ptr is smart pointer...

File: auth/standard_role_manager.cc [hunk 18]
```diff
@@ -250,26 +251,32 @@ future<> standard_role_manager::start() {
...
-                            return;
+                            co_await migrate_legacy_metadata();
+                            co_return;
                         }
                     }
-                    create_default_role_if_missing().get();
-                });
+                    co_await create_default_role_if_missing();
+                } catch (...) {
+                    // If we fail to create the default role, we should not signal that we are ready.
```
Comment (nuivall) [inline auth/standard_role_manager.cc:276]: cool, but then nobody will signal and code in main will block forever, since future is awaited only during stop() method nobody before that will see the error as well

please manually test by inserting throw into create_default_role_if_missing(), code is not trivial and it's easy to write something which wouldn't handle errors properly

File: auth/standard_role_manager.cc (hunk 17 above)
Comment (nuivall) [reply auth/standard_role_manager.cc:255]: yes I didn't mean you should not throw but do both

**Comment by kostja** [comment]
* Paweł Zakrzewski ***@***.***> [24/10/01 22:19]:
> @KrzaQ commented on this pull request.
> 
> 
> 
> >                          }
>                      }
> -                    create_default_role_if_missing().get();
> -                });
> +                    co_await create_default_role_if_missing();
> +                } catch (...) {
> +                    // If we fail to create the default role, we should not signal that we are ready.
> 
> I'm not sure how to solve this. `create_default_role_if_missing()` can fail naturally and throw (that's how `do_after_system_ready()` knows it needs to wait and retry)

If we fail to create the role I think we could panic, no?

-- 
Konstantin Osipov, Moscow, Russia

**Comment by kostja** [comment]
> @kostja I don't think so. I can't reproduce this out of hand, but I had it happen in the past that the first (few) executions failed because the system wasn't fully up. That's exactly why this is wrapped in `do_after_system_ready()`.

What exceptions were you getting then, do you remember?

Perhaps this is a boot order issue @xemul and needs to be addressed?

File: auth/standard_role_manager.cc (hunk 18 above)
Comment (nuivall) [reply auth/standard_role_manager.cc:276]: you need to attach try catch block to future returned by do_after_system_ready because it throws when it's done with retries, pseudocode:

```
auth::do_after_system_ready(...).then_wrapped(future<> f) {
try {
f.get()
catch(...) { ...broken(...); throw; }
...signal()
});
```

**Comment by nuivall** [comment]
> > @kostja I don't think so. I can't reproduce this out of hand, but I had it happen in the past that the first (few) executions failed because the system wasn't fully up. That's exactly why this is wrapped in `do_after_system_ready()`.
> 
> What exceptions were you getting then, do you remember?
> 
> Perhaps this is a boot order issue @xemul and needs to be addressed?
> 
> The solution then I think is to ignore these specific exceptions, and let all others through.

yes, it is boot order issue swept under the rug, in general main.cc code lacks generic solution for dependency injection and breaking service's cycles

but I don't see why https://github.com/scylladb/scylladb/pull/20137#discussion_r1784047586 can't solve it in this PR, we shouldn't refactor dependencies code in this patch

File: auth/standard_role_manager.cc [hunk 19]
```diff
@@ -250,24 +251,32 @@ future<> standard_role_manager::start() {
...
         }).then([this] {
-            _stopped = auth::do_after_system_ready(_as, [this] () -> future<void>  {
-                if (legacy_mode(_qp)) {
-                    co_await _migration_manager.wait_for_schema_agreement(_qp.db().real_database(), db::timeout_clock::time_point::max(), &_as);
+            _stopped = auth::do_after_system_ready(_as, [this] () -> future<>  {
+                auto signal_super_user_created = defer([this] {
+                    _superuser_created.signal();
+                });
+                try {
+                    if (legacy_mode(_qp)) {
```
Comment (kbr-scylla) [inline auth/standard_role_manager.cc:259]: Please split the whitespace change to a separate commit so it's easier to review. (I.e. the commit where you introduce `try` block, do not shift everything to the right; shift it in a follow-up commit that fixes whitespace)

File: auth/standard_role_manager.cc [hunk 20]
```diff
@@ -250,24 +251,32 @@ future<> standard_role_manager::start() {
...
-
-                    if (legacy_metadata_exists()) {
-                        co_await migrate_legacy_metadata();
-                        co_return;
                     }
+                    co_await create_default_role_if_missing();
+                } catch (...) {
+                    // If we fail to create the default role, we should not signal that we are ready.
+                    signal_super_user_created.cancel();
+                    throw;
```
Comment (kbr-scylla) [inline auth/standard_role_manager.cc:278]: So why use `defer` in the first place? It would be equivalent (but much easier to read) to put the `_superuser_created.signal();` directly after the `catch` block.

File: auth/standard_role_manager.cc [hunk 21]
```diff
@@ -278,6 +287,11 @@ future<> standard_role_manager::stop() {
     return _stopped.handle_exception_type([] (const sleep_aborted&) { }).handle_exception_type([](const abort_requested_exception&) {});;
 }
 
+future<> standard_role_manager::ensure_superuser_is_created() {
+    co_await get_units(_superuser_created, 1);
```
Comment (kbr-scylla) [inline auth/standard_role_manager.cc:291]: `semaphore` is the wrong tool for the job. What you want is a `promise<>` + `future<>` pair.

**Review by kbr-scylla — CHANGES_REQUESTED** [review]

File: auth/standard_role_manager.cc (hunk 20 above)
Comment (kbr-scylla) [reply auth/standard_role_manager.cc:278]: Right.

File: auth/standard_role_manager.cc (hunk 21 above)
Comment (kbr-scylla) [reply auth/standard_role_manager.cc:291]: > it has the correct semantics: it can be accessed multiple times

if `ensure_superuser_is_created()` is called more than once, we're in trouble: every call other than the first will **hang**.

With promise+future, the second call will crash on an assertion (IIRC). I think that is better than a hang. Definitely easier to debug.

Comment (kbr-scylla) [reply auth/standard_role_manager.cc:291]: Ah, that's what it does... we get the units, and then immediately destroy them.

It's a bit hacky, don't you think?

`get_units` should probably be marked `[[nodiscard]]` and here you would have to explicitly discard them (by `(void)` or whatever), it would make it a bit clearer.

But still

IIUC `ensure_superuser_is_created()` should still be called exactly once -- when we initialize Scylla. Is it intended to be called more than once? If not, then wouldn't calling more than once be a bug (and bugs should be preferably catched as early as possible?)

Comment (kbr-scylla) [reply auth/standard_role_manager.cc:291]: Either way, if we decide that "ensuring" should or can be done multiple times, the idiomatic way in seastar to have multiple waiters to wait for something to happen is `shared_promise`/`shared_future`, a semaphore where you get units only to immediately discard them is... weird.

Comment (nuivall) [reply auth/standard_role_manager.cc:291]: I think whatever is simplest wins, readability matters too. Semaphore is commonly used. It doesn't matter if functions calls are serialized - there is exactly one call in the code, and even if there will be 10, still doesn't matter.

By the way  condition_variable seems even more appropriate than suggested future+promise.

Comment (kbr-scylla) [reply auth/standard_role_manager.cc:291]: > I think whatever is simplest wins, readability matters too

Agreed.

> Semaphore is commonly used

But not like that. Getting units from a semaphore just to destroy them immediately is far from common. It is abuse. Therefore it is not readable and not simple.

**Comment by nuivall** [comment]
I think we should change backport decision because there are clients with usages like this one: https://github.com/scylladb/scylla-enterprise/issues/4788 and if they are not hitting it yet they probably will .

File: auth/standard_role_manager.hh [hunk 22]
```diff
@@ -38,6 +38,8 @@ class standard_role_manager final : public role_manager {
     future<> _stopped;
     abort_source _as;
     std::string _superuser;
+    std::atomic_bool _superuser_created;
```
Comment (nuivall) [inline auth/standard_role_manager.hh:41]: 1. why you need atomic_bool, are you accessing it via different shards concurrently? this doesn't seem right. btw there is no atomic_bool usage in the whole codebase, this may be a hint.
2. _superuser_created(this_shard_id() != 0) - it doesn't make sense to fake that if you are not shard then superuser is created, this is misleading. What we usually do is that we explicitly check this_shard_id in the code, and also comment if necessary

File: main.cc [hunk 23]
```diff
@@ -2129,6 +2129,10 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
                 ss.local().drain_on_shutdown().get();
             });
 
+            auth_service.invoke_on_all([] (auth::service& auth_service) -> future<> {
```
Comment (nuivall) [inline main.cc:2132]: I think I commented on that before, why check all shards if only shard 0 is responsible for creation?
I guess startup is done on shard 0 so it's just enough to do:
```
bool ensure_superuser_is_created() {
SCYLLA_ASSERT(this_shard_id() == 0);
return ...
};

...
void main() {
...
co_await auth_service.local().ensure_superuser_is_created();
...
}
```

File: auth/standard_role_manager.cc [hunk 24]
```diff
@@ -243,35 +244,60 @@ future<> standard_role_manager::migrate_legacy_metadata() {
...
-        });
+
+                    if (legacy_metadata_exists()) {
+                        co_await migrate_legacy_metadata();
+                        co_return;
+                    }
+                }
+                co_await create_default_role_if_missing();
+                bool previous = _superuser_created.exchange(true);
+                if (!previous) _superuser_created_promise.set_value();
```
Comment (nuivall) [inline auth/standard_role_manager.cc:273]: I think I commented on that before, we never omit `{`

File: auth/standard_role_manager.cc [hunk 25]
```diff
@@ -243,35 +244,60 @@ future<> standard_role_manager::migrate_legacy_metadata() {
...
+            } catch (const exceptions::unavailable_exception& e) {
```
Comment (nuivall) [inline auth/standard_role_manager.cc:274]: could you explain why those extra catches were needed to be added?

File: auth/standard_role_manager.hh [hunk 26]
```diff
@@ -38,6 +38,8 @@ class standard_role_manager final : public role_manager {
...
+    shared_promise<> _superuser_created_promise;
```
Comment (nuivall) [inline auth/standard_role_manager.hh:42]: same comment as for atomic bool, I don't get why shared_ is needed here

File: auth/standard_role_manager.cc [hunk 27]
```diff
@@ -243,35 +244,60 @@ future<> standard_role_manager::migrate_legacy_metadata() {
...
-            });
-        });
+
+                    if (legacy_metadata_exists()) {
+                        co_await migrate_legacy_metadata();
+                        co_return;
+                    }
+                }
+                co_await create_default_role_if_missing();
+                bool previous = _superuser_created.exchange(true);
```
Comment (nuivall) [inline auth/standard_role_manager.cc:272]: since start() should be called only once I understand previous is only to break the retry loop here? If so there has to be a better way. For instance you can throw different kind of exception and in do_after_system_ready check for it, this would be more explicit and readable.

**Comment by ptrsmrn** [comment]
@scylladb/scylla-maint Please consider merging: comments have been addressed, CI is green.

File: auth/standard_role_manager.cc [hunk 28]
```diff
@@ -243,35 +243,39 @@ future<> standard_role_manager::migrate_legacy_metadata() {
...
-                        }
+    return once_among_shards([this] () -> future<> {
+        if (legacy_mode(_qp)) {
+            co_await create_legacy_metadata_tables_if_missing();
+        }
+
+        auto handler = [this] () -> future<> {
+            const bool legacy = legacy_mode(_qp);
+            if (legacy) {
+                if (!_superuser_created_promise.available()) {
```
Comment (nuivall) [inline auth/standard_role_manager.cc:254]: not sure why legacy path check `_superuser_created_promise.available()` and non legacy doesn't

**Review by nuivall — APPROVED** [review]

File: auth/standard_role_manager.cc (hunk 28 above)
Comment (nuivall) [reply auth/standard_role_manager.cc:254]: ok

**Comment by nuivall** [comment]
Please update cover letter with description of changes in logic, namely:
- wait is not done via start()'s future anymore
- brings create super user logic from the background effectively to the foreground
- which in turn means that main blocks forever if creation encounters non-transient error
