### PR TITLE
repair: Fix stall in repair_get_row_diff_with_rpc_stream_process_op_slow_path

### LINKED ISSUE #21016: repair_get_row_diff_with_rpc_stream_process_op stalls from ~repair_row_on_wire_with_cmd
The following stall was found during a test:

```
Processed 1919 stalls lasting a total of 144733 milliseconds.
min=32 avg=75.4 median=70 p95=130 p99=132 p999=134 max=134

This graph is printed in bottom-up order, where callees are printed first.
Use --direction=top-down to print callers first.

[level#index/out_of pct%] below denotes:
  level  - nesting level in the graph
  index  - index of node among to its siblings
  out_of - number of siblings
  pct    - percentage of total stall time of this call relative to its siblings

Command line options: --address-threshold=0x100000000 --executable=libexec/scylla --direction=bottom-up --branch-threshold=0.03 --file=/tmp/10.31.188.7.txt

++[0#1/454 15%] addr=0x12ab083 total=21697 count=227 avg=96:
|               bytes_ostream::free_chain at ././bytes_ostream.hh:159
| ++[1#1/2 95%] addr=0x3936b8f total=20619 count=213 avg=97:
| |             ~bytes_ostream at ././bytes_ostream.hh:195
| |             (inlined by) ~frozen_mutation_fragment at ././frozen_mutation.hh:268
| |             (inlined by) std::destroy_at<frozen_mutation_fragment> at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:88
| |             (inlined by) std::allocator_traits<std::allocator<std::_List_node<frozen_mutation_fragment> > >::destroy<frozen_mutation_fragment> at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/alloc_traits.h:537
| |             (inlined by) std::__cxx11::_List_base<frozen_mutation_fragment, std::allocator<frozen_mutation_fragment> >::_M_clear at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/list.tcc:77
| |             (inlined by) ~_List_base at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_list.h:499
| |             (inlined by) ~partition_key_and_mutation_fragments at ././repair/repair.hh:298
| |             (inlined by) ~repair_row_on_wire_with_cmd at ././repair/repair.hh:335
| |             (inlined by) operator() at ./repair/row_level.cc:1881
| |             (inlined by) seastar::futurize<seastar::future<void> >::invoke<repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)::{lambda(partition_key_and_mutation_fragments&)#1}&, {lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}> at ././seastar/include/seastar/core/future.hh:2149
| |             (inlined by) seastar::futurize_invoke<repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)::{lambda(partition_key_and_mutation_fragments&)#1}&, {lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}> at ././seastar/include/seastar/core/future.hh:2180
| |             (inlined by) seastar::internal::do_for_each_impl<std::_List_iterator<partition_key_and_mutation_fragments>, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)::{lambda(partition_key_and_mutation_fragments&)#1}> at ././seastar/include/seastar/core/loop.hh:423
| |             (inlined by) seastar::do_for_each<std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)::{lambda(partition_key_and_mutation_fragments&)#1}> at ././seastar/include/seastar/core/loop.hh:483
| |             (inlined by) operator() at ./repair/row_level.cc:1880
| |             (inlined by) std::__invoke_impl<seastar::future<void>, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}&, std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&> at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
| |             (inlined by) std::__invoke<repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}&, std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&> at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
| |             (inlined by) std::__apply_impl<repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}&, std::tuple<std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> > >&, 0ul> at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1858
| |             (inlined by) std::apply<repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}&, std::tuple<std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> > >&> at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1869
| |             (inlined by) seastar::internal::do_with_impl<std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}> at ././seastar/include/seastar/core/do_with.hh:96
| |             (inlined by) seastar::futurize<seastar::future<void> >::invoke<seastar::future<void> (*&)(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&&, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}&&), std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, {lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}> at ././seastar/include/seastar/core/future.hh:2149
| |             (inlined by) seastar::futurize_invoke<seastar::future<void> (*&)(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&&, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}&&), std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, {lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}> at ././seastar/include/seastar/core/future.hh:2180
| |             (inlined by) seastar::do_with<std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >, repair_get_row_diff_with_rpc_stream_process_op(seastar::sharded<repair_service>&, gms::inet_address, unsigned int, unsigned int, seastar::rpc::sink<repair_row_on_wire_with_cmd>, seastar::rpc::source<repair_hash_with_cmd>, bool&, absl::btree_set<repair_hash, std::less<repair_hash>, std::allocator<repair_hash> >&, std::optional<std::tuple<repair_hash_with_cmd> >)::$_12::operator()(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >)::{lambda(std::__cxx11::list<partition_key_and_mutation_fragments, std::allocator<partition_key_and_mutation_fragments> >&)#1}> at ././seastar/include/seastar/core/do_with.hh:131
| |             (inlined by) operator() at ./repair/row_level.cc:1879
```

### PR DESCRIPTION
**Pull request by asias**
Use clear_gently to avoid the following stalls.

```
~frozen_mutation_fragment at ././frozen_mutation.hh:268

std::destroy_at<frozen_mutation_fragment> at
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_construct.h:88

std::allocator_traits<std::allocator<std::_List_node<frozen_mutation_fragment>
> >::destroy<frozen_mutation_fragment> at
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/alloc_traits.h:537

std::__cxx11::_List_base<frozen_mutation_fragment,
std::allocator<frozen_mutation_fragment> >::_M_clear at
/usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/list.tcc:77

~_List_base at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_list.h:499
~partition_key_and_mutation_fragments at ././repair/repair.hh:298
~repair_row_on_wire_with_cmd at ././repair/repair.hh:335
operator() at ./repair/row_level.cc:1881
```

Fixes #21016

Performance improvement only. No backport.

### CODE REVIEW

**Review by denesb — APPROVED** [review]

File: repair/row_level.cc [hunk 1]
```diff
@@ -2003,7 +2003,9 @@ static future<> repair_get_row_diff_with_rpc_stream_process_op_slow_path(
             co_await sink(repair_row_on_wire_with_cmd{repair_stream_cmd::end_of_current_rows, repair_row_on_wire()});
         } else {
             for (repair_row_on_wire& row : rows_on_wire) {
-                co_await sink(repair_row_on_wire_with_cmd{repair_stream_cmd::row_data, std::move(row)});
+                auto cmd = repair_row_on_wire_with_cmd{repair_stream_cmd::row_data, std::move(row)};
+                co_await sink(cmd);
+                co_await cmd.row.clear_gently();
```
Comment (bhalevy) [inline repair/row_level.cc:2008]: It's unfortunate we cannot co_await in deferred_action, since we might stall if `sink` throws.
Maybe we should consider `co_await sink(cmd).finally([&cmd] { return cmd.row.clear_gently(); });`

Comment (avikivity) [inline repair/row_level.cc:2008]: I see. repair_row_on_wire is misnamed, because it encompasses multiple rows.

Isn't it a problem to send on rpc if it can contain many rows?

Comment (asias) [reply repair/row_level.cc:2008]: Yes, each repair_row_on_wire could contain multiple fragments within the same partition. 
Since we have repair_rows_on_wire, that's why we used  repair_row_on_wire for partition_key_and_mutation_fragments.
```
using repair_row_on_wire = partition_key_and_mutation_fragments;
using repair_rows_on_wire = std::list<partition_key_and_mutation_fragments>;
```
The data is sent over rpc stream not a single rpc verb call.
