### PR TITLE
cql3: respect PER PARTITION LIMIT for aggregate queries

### LINKED ISSUE #5363: PER PARTITION LIMIT doesn't work right when using GROUP BY
as mentioned on #5361 , as an effort to develop tests for testing #2206 , this issue has been reproducible.
as the original's test expected result, it is supposed to print 3 lines, not 5
```
cqlsh:test_paging_with_group_by> select * from test PER PARTITION LIMIT 1;

 a | b | c | d  | e
---+---+---+----+----
 1 | 2 | 1 |  3 |  6
 2 | 2 | 3 |  3 |  6
 4 | 8 | 2 | 12 | 24

---MORE---
(3 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, e, count(b), max(e) FROM test GROUP BY a, b PER PARTITION LIMIT 1;

 a | b | e  | system.count(b) | system.max(e)
---+---+----+-----------------+---------------
 1 | 2 |  6 |               2 |            12
 1 | 4 | 12 |               2 |            24
 2 | 2 |  6 |               1 |             6
 2 | 4 | 12 |               1 |            12
 4 | 8 | 24 |               1 |            24

(5 rows)
cqlsh:test_paging_with_group_by> DESCRIBE TABLE test

CREATE TABLE test_paging_with_group_by.test (
    a int,
    b int,
    c int,
    d int,
    e int,
    PRIMARY KEY (a, b, c, d)
) WITH CLUSTERING ORDER BY (b ASC, c ASC, d ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

### PR DESCRIPTION
**Pull request by KrzaQ**
Currently, PER PARTITION LIMIT is not implemented for aggregates and queries can result in more rows than expected from the same partition. 

Instrument the result_set_builder class so that it can enforce PER PARTITION LIMIT for aggregate queries, specifically:
- add per_partition_limit to the result_set_builder
- expose the number of input rows in the selector

result_set_builder gets two new functions handling partition start and end:
- accept_partition_end for notifying that a partition has been finished. This is also called when a page ends, so we cannot simply flush here, as a naive implementation could do.
- accept_new_partition, where we flush_selectors() if it's indeed a new partition (and not a continuation of the previous) and the query has a grouping: we don't want to flush on new partition in a query like SELECT COUNT(*) FROM foo;

Fixes #5363

### CODE REVIEW

File: cql3/selection/selection.cc [hunk 1]
```diff
@@ -504,11 +517,14 @@ selection::collect_metadata(const schema& schema, const std::vector<prepared_sel
...
                                        std::vector<size_t> group_by_cell_indices,
-                                       uint64_t limit)
+                                       uint64_t limit, uint64_t per_partition_limit)
     : _result_set(std::make_unique<result_set>(::make_shared<metadata>(*(s.get_result_metadata()))))
     , _selectors(s.new_selectors())
     , _group_by_cell_indices(std::move(group_by_cell_indices))
     , _limit(limit)
+    , _per_partition_limit(per_partition_limit)
+    , _per_partition_remaining(per_partition_limit)
+    , _per_partition_remaining_before(per_partition_limit)
```
Comment (ptrsmrn) [inline cql3/selection/selection.cc:527]: We need to rename this var. Probably also carefully explain in a comment why it's needed.

File: cql3/selection/selection.cc [hunk 2]
```diff
@@ -598,14 +620,42 @@ void result_set_builder::complete_row() {
     _selectors->add_input_row(*this);
 }
 
+void result_set_builder::accept_new_partition(const std::vector<bytes>& key)
```
Comment (ptrsmrn) [inline cql3/selection/selection.cc:623]: Per @nuivall : it seems wrong that `accept_new_partition` is triggered for both: new page and new partition events. The code below works around it, but in order not to get ourselves into even bigger troubles, we may want to fix it before addressing groupby vs perpartition limit issue.

File: configure.py [hunk 3]
```diff
@@ -1530,6 +1530,7 @@ def get_warning_options(cxx):
         '-Wno-mismatched-tags',  # clang-only
         '-Wno-c++11-narrowing',
         '-Wno-overloaded-virtual',
```
Comment (avikivity) [inline configure.py:1532]: > Revert "configure.py: remove -Wno-unused-command-line-argument"
> This reverts commit https://github.com/scylladb/scylladb/commit/fe8e37c5bd968193dc2776152842f4a1b3815c47.

Why?

File: cql3/statements/select_statement.cc [hunk 4]
```diff
@@ -497,8 +497,17 @@ select_statement::execute_without_checking_exception_message_aggregate_or_paged(
...
             state, options, command, std::move(key_ranges), _restrictions_need_filtering ? _restrictions : nullptr);
 
+    uint64_t per_partition_limit = std::numeric_limits<uint64_t>::max();
+    if (_per_partition_limit) {
+        auto val = expr::evaluate(*_per_partition_limit, options);
+        if (!val.is_null()) {
+            auto l = val.view().validate_and_deserialize<int32_t>(*int32_type);
+            per_partition_limit = l < 0 ? std::numeric_limits<uint64_t>::max() : static_cast<uint64_t>(l);
+        }
+    }
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:507]: We should deduplicate the evaluation in make_partition_slice().

Comment (avikivity) [reply cql3/statements/select_statement.cc:507]: (and use get_limit())

**Comment by avikivity** [comment]
I think there is tension with the partition_slice per_partition_limit. In some cases we can push down the per_partition_limit to the read_command (I think: when there is no filtering). In others, we cannot. Need to make the decision explicit in the code and not accidental (this is one of the motivations for my stalled work on statement_restrictions), and add tests.

**Comment by avikivity** [comment]
> @avikivity: could you provide an example select statement to help me understand the concern?
> 
> This patch only deals with aggregate queries, which are already processed by the result_set_builder class. Pushing them down to read_command is out of scope for this change set.

The problem isn't to push the per partition limit into read_command; the problem is that the per partition limit is unconditionally pushed into the read command, and it's sometimes wrong.

But no, I now see that it was fixed with your patch that changed the call to get_inner_loop_limit(). If it's an aggregation, then we avoid pushing the per partition limit to read_command. So I think all is fine.

**Comment by avikivity** [comment]
But: we can improve things. If we aren't filtering, then we /can/ push down the per partition limit. But that's for a different patch.

**Comment by nyh** [comment]
Please add "Fixes" of whichever issues this PR is fixing to the cover letter (I also looked for them, and didn't see, in individual commits).

File: test/cql-pytest/cassandra_tests/validation/operations/compact_storage_test.py [hunk 5]
```diff
@@ -1787,7 +1787,6 @@ def testGroupByWithoutPagingWithDeletions(cql, test_keyspace):
                    row(1, 2, 2, 3, 12),
                    row(1, 2, 3, 4, 12))
 
-@pytest.mark.xfail(reason="issue #5361, #5363")
```
Comment (nyh) [inline test/cql-pytest/cassandra_tests/validation/operations/compact_storage_test.py:1790]: I see you un-xfailed some tests for #5361 and #5363 but please explain this in the commit message, and more importantly - explain if you un-xfailed **all** the tests that mentioned 5361 and 5363, or if not, why not.

**Comment by ptrsmrn** [comment]
I think these dtest failures are something we anticipated for, right @KrzaQ ? In the sense that we're not really running dtests locally, so it's kind-of expected some mail fail.

**Comment by ptrsmrn** [comment]
BTW. I noticed that whenever I get an email update with regards to this PR, there's still WIP in the title, even though you've changed it already. I guess it may have something to do with keeping all the emails under one conversation, so the email title has to remain the same, so github has to remember the initial title (maybe). Pic attached
image

**Comment by nyh** [comment]
> BTW. I noticed that whenever I get an email update with regards to this PR, there's still WIP in the title, even though you've changed it already. I guess it may have something to do with keeping all the emails under one conversation

It's not "in the title" - if you look at one of the latest mails and (if you use gmail's web interface) press the black triangle next to the "to" line, you'll see the real subject line of this mail, and it doesn't contain the word "WIP". It's just that gmail decides to group it together with the previous mails (I'm not sure what it bases this decision on), and for this whole group it unfortunately shows you the first subject line in the group - not the last subject line.

**Comment by ptrsmrn** [comment]
> > BTW. I noticed that whenever I get an email update with regards to this PR, there's still WIP in the title, even though you've changed it already. I guess it may have something to do with keeping all the emails under one conversation
> 
> It's not "in the title" - if you look at one of the latest mails and (if you use gmail's web interface) press the black triangle next to the "to" line, you'll see the real subject line of this mail, and it doesn't contain the word "WIP". It's just that gmail decides to group it together with the previous mails (I'm not sure what it bases this decision on), and for this whole group it unfortunately shows you the first subject line in the group - not the last subject line.

@nyh thanks for the explanation. I think that grouping the emails, even though the title changed, makes more sense - it's still the same PR, so every email about it should be in 1 conversation.

**Review by nyh — APPROVED** [review]
Looks good to me, but obviously we can't merge yet before we fix the dtests not to enshrine incorrect behavior. I also left a few trivial comments inline, and please don't forget a Fixes line in the cover letter. Thanks.

**Comment by nuivall** [comment]
@KrzaQ I think you should add to the cover letter a description what was wrong before the patch (*the bug*), including how it breaks, then it will be easier to understand the fix

File: cql3/selection/selection.cc [hunk 6]
```diff
@@ -344,6 +349,7 @@ class selection_with_processing : public selection {
         const selection_with_processing& _sel;
         std::vector<raw_value> _temporaries;
         bool _requires_thread;
+        size_t _input_row_count;
```
Comment (avikivity) [inline cql3/selection/selection.cc:352]: size_t is logically wrong here (and in the function too). size_t is for "countable things in memory", and this counts things on disk. A theoretical 32-bit scylladb would fail if we'd page in more than 2^32 rows.

In practice it works, but it still sends readers the wrong signal. Should be uint64_t.

File: cql3/statements/select_statement.cc [hunk 7]
```diff
@@ -497,8 +497,17 @@ select_statement::execute_without_checking_exception_message_aggregate_or_paged(
     auto p = service::pager::query_pagers::pager(qp.proxy(), _query_schema, _selection,
             state, options, command, std::move(key_ranges), _restrictions_need_filtering ? _restrictions : nullptr);
 
+    uint64_t per_partition_limit = std::numeric_limits<uint64_t>::max();
+    if (_per_partition_limit) {
+        auto val = expr::evaluate(*_per_partition_limit, options);
+        if (!val.is_null()) {
+            auto l = val.view().validate_and_deserialize<int32_t>(*int32_type);
+            per_partition_limit = l < 0 ? std::numeric_limits<uint64_t>::max() : static_cast<uint64_t>(l);
+        }
```
[the remark this answers is not in the document]
Comment (nyh) [reply cql3/statements/select_statement.cc]: I agree, you can consider this later, if you want. It's also worth checking what Cassandra does (as usual, a test can do this) - if Cassandra is inconsistent in the same way, then it's fine (we can always say we did it to be compatible!), if it's just our own private bug, we can fix it. But indeed, doesn't need to be now.

**Comment by avikivity** [comment]
With very large partitions, we'll iterate through all rows even though we only need the first few. But fixing that can be done later.
