### PR TITLE
misc_services: fix data race from bad usage of get_next_version

### LINKED ISSUE #17493: Missing gossiper updates
This is an issue to describe the possible root cause of multiple different issues found by tests, and document findings from investigation.

In https://github.com/scylladb/scylladb/issues/16902, a joining node finished the bootstrap correctly and entered the NORMAL status. However one of the nodes in the cluster did not observe the NORMAL status, which was detected by SCT health check. By investigating gossipinfo output, I determined that the node does not have the updated STATUS application state.

https://github.com/scylladb/scylladb/issues/15602 looks the same, except it happened on dtest. The test waits until a replacing node enters NORMAL state by checking how other nodes see its state in gossiper. The test timed out because one of the nodes never saw the replacing node entering NORMAL state.

In https://github.com/scylladb/scylla-enterprise/issues/3720 there was a schema change and after each schema change all nodes start gossiping the current schema version. SCT detected that one of the nodes observes an outdated (pre-change) version for another node (in gossipinfo and system.peers), this state remained until the next schema change.

In https://github.com/scylladb/scylladb/issues/16668 a node replaced another, and then decommissioned. During decommission there was a crash on another node. Turns out that another node never saw the replacing node enter NORMAL state -- it kept seeing it as if it was still doing the replace. (There was never `handle_state_normal` call that would appropriately update `token_metadata`).

In https://github.com/scylladb/scylladb/issues/15393 a node got stuck during bootstrap waiting for schema versions to synchronize across the cluster.  And apparently it keeps seeing an outdated schema version for one of the nodes in gossip, even though logs of that node show that it transitioned to new version.

---

All these issues lead to a single hypothesis -- there is some bug in gossiping algorithm that causes application state updates to go missing. It's not transient, once node A obtains new application states for node B but somehow one of the application state updates goes missing, then A will never get update for this particular app state of node B, regardless of how long they keep gossiping. The way to go out of this is for node B to increase the version of this app state (e.g. for schema, do another schema change). Or reboot which will increase the generation number of its endpoint state)

EDIT update: actual root cause described in fix https://github.com/scylladb/scylladb/pull/18184
the below description is for old hypothesis

As for possible explanations what the bug could be, we have one. After digging into the code I saw this
```cpp
namespace gms {
namespace version_generator {
// In the original Cassandra code, version was an AtomicInteger.
// For us, we run the gossiper on a single CPU, and don't need to use atomics.
static version_type version;

version_type get_next_version() noexcept
{
    return ++version;
}
```
knowing from experience that assertions through comments never work (unlike `assert` macro or similar mechanism), I found this immediately suspicious.

@piodul investigated this further and indeed, after putting an actual `assert` there (that it's called only from shard 0), Scylla immediately crashes. So we know we have a data race in gossiper. The non-shard0 access comes from updating CACHE_HITRATES in service/misc_services.cc

From reading the code, we came up with possible theoretical scenario in which this data race could cause missing application state updates. Gossiper exchanges application states as follows: each node remembers the latest application states it saw for every other node, and calculates the max version of those states. When doing the exchange, it receives only application states with versions greater than this max version.

So the scenario is:

- shard 1 on node A calls `get_next_version()` which observes version `v - 1` and hangs before storing `v` (gets preempted or sth)
- node A calls `add_local_application_state` (always happens on shard 0), calls `get_next_version()` which observes version `v - 1`, increments it and returns `v` which is used for the updated app state.
- node A calls `add_local_application_state` again, calls `get_next_version()` which observes version `v`, increments it and returns `v + 1` which his used for this updated app state.
- gossip message handler called on node A, which causes node A to return its app states to node B. The max version is `v + 1`
- shard 1 on A resumes and stores version `v`
- node A calls `add_local_application_state` again, calls `get_next_version()` which observes version `v`, increments it and returns `v + 1` which his used for this updated app state.
- node B will never get that last app state because it already assumes that max version on node A is `v + 1`, and we only obtain states with versions greater than last max.

@piodul ran a test which some modifications to Scylla:
- make the cache hitrates updater to run more frequently
- putting an assertion in `add_local_application_state` that it only observes strictly increasing version numbers
- running a test that performs schema changes in a loop

and after a few hours, the assertion was triggered.

But we never managed to reproduce a scenario where the two `add_local_application_state` calls which reuse the same version are interleaved with a gossip exchange that would actually cause the bug. Plus the cache hitrates updater which usually runs every 1 second or so, was modified to run thousands of times per second to trigger the data race more often.

In fact this scenario (where a gossip exchange timing correlates with the data race timing) seems very unlikely already with the frequent cache hitrate updating, and even extremely unlikely with regular cache hitrate updating.

But we don't have any other explanation for the observed failures.

So the plan for now is to fix the data race and see if we keep observing similar failures in our tests for the next month or 2. If nothing like that appears again, we will assume that it was the data race. Otherwise we'll need to investigate further.
```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/15393
- [ ] https://github.com/scylladb/scylladb/issues/15602
- [ ] https://github.com/scylladb/scylladb/issues/16668
- [ ] https://github.com/scylladb/scylladb/issues/16902
- [ ] https://github.com/scylladb/scylla-enterprise/issues/3720
- [ ] https://github.com/scylladb/scylladb/issues/18118
```

### PR DESCRIPTION
**Pull request by piodul**
The function `gms::version_generator::get_next_version()` can only be called from shard 0 as it uses a global, unsynchronized counter to issue versions. Notably, the function is used as a default argument for the constructor of `gms::versioned_value` which is used from shorthand constructors such as `versioned_value::cache_hitrates`, `versioned_value::schema` etc.

The `cache_hitrate_calculator` service runs a periodic job which updates the `CACHE_HITRATES` application state in the local gossiper state. Each time the job is scheduled, it runs on the next shard (it goes through shards in a round-robin fashion). The job uses the `versioned_value::cache_hitrates` shorthand to create a `versioned_value`, therefore risking a data race if it is not currently executing on shard 0.

The PR fixes the race by moving the call to `versioned_value::cache_hitrates` to shard 0. Additionally, in order to help detect similar issues in the future, a check is introduced to `get_next_version` which aborts the process if the function was called on other shard than 0.

There is a possibility that it is a fix for #17493. Because `get_next_version` uses a simple incrementation to advance the global counter, a data race can occur if two shards call it concurrently and it may result in shard 0 returning the same or smaller value when called two times in a row. The following sequence of events is suspected to occur on node A:

1. Shard 1 calls `get_next_version()`, loads version `v - 1` from the global counter and stores in a register; the thread then is preempted,
2. Shard 0 executes `add_local_application_state()` which internally calls `get_next_version()`, loads `v - 1` then stores `v` and uses version `v` to update the application state,
3. Shard 0 executes `add_local_application_state()` again, increments version to `v + 1` and uses it to update the application state,
4. Gossip message handler runs, exchanging application states with node B. It sends its application state to B. Note that the max version of any of the local application states is `v + 1`,
5. Shard 1 resumes and stores version `v` in the global counter,
6. Shard 0 executes `add_local_application_state()` and updates the application state - again - with version `v + 1`.
7. After that, node B will never learn about the application state introduced in point 6. as gossip exchange only sends endpoint states with version larger than the previous observed max version, which was `v + 1` in point 4.

Note that the above scenario was _not_ reproduced. However, I managed to observe a race condition by:

1. modifying Scylla to run update of `CACHE_HITRATES` much more frequently than usual,
2. putting an assertion in `add_local_application_state` which fails if the version returned by `get_next_version` was not larger than the previous returned value,
3. running a test which performs schema changes in a loop.

The assertion from the second point was triggered. While it's hard to tell how likely it is to occur without making updates of cache hitrates more frequent - not to mention the full theorized scenario - for now this is the best lead that we have, and the data race being fixed here is a real bug anyway.

Refs: #17493

### CODE REVIEW

File: service/misc_services.cc [hunk 1]
```diff
@@ -204,8 +204,10 @@ future<lowres_clock::duration> cache_hitrate_calculator::recalculate_hitrates()
             llogger.debug("Send CACHE_HITRATES update max_diff={}, published_nr={}", _diff, _published_nr);
             ++_published_nr;
             _published_time = now;
-            return _gossiper.add_local_application_state(gms::application_state::CACHE_HITRATES,
-                    gms::versioned_value::cache_hitrates(_gstate)).then([recalculate_duration] {
+            return container().invoke_on(0, [&gstate = _gstate] (cache_hitrate_calculator& self) {
```
Comment (kbr-scylla) [inline service/misc_services.cc:207]: `recalculate_hitrates()` is called sequentially, right? So `_gstate` cannot be modified concurrently with this.

**Review by kbr-scylla — APPROVED** [review]

File: service/misc_services.cc (hunk 1 above)
Comment (piodul) [reply service/misc_services.cc:207]: Yes, there is at most one `recalculate_hitrates()` running at a time:

- `run_on` arms a non-periodic local timer,
- timer executes `recalculate_timer()`, which executes `recalculate_hitrates()` and schedules a continuation that calls `run_on` after `recalculate_hitrates()` completes,

In `main.cc`, there is a single `run_on` call which starts the loop described above.

**Comment by kbr-scylla** [comment]
I suspect that this might improve CI stability (even if insignificantly), there was at least one CI failure in the past where this is the suspected root cause. So I'm merging.

**Comment by kbr-scylla** [comment]
> I suspect that this might improve CI stability (even if insignificantly), there was at least one CI failure in the past where this is the suspected root cause. So I'm merging.

cc @avikivity

**Comment by kbr-scylla** [comment]
Backports queued to 5.2 and 5.4
