### PR TITLE
replica: fix copy constructor of tablet_sstable_set

### LINKED ISSUE #19519: tablet_sstable_set copy ctor does not copy _sstable_set_ids
Commit 9f93dd9fa3376cfe560c65fb9c9c938ff1d3f99d changed `tablet_sstable_set::_sstable_sets` to be a `absl::flat_hash_map` and in addition, `std::set<size_t> _sstable_set_ids` was added (Used when ordering is required for correctness).

`_sstable_set_ids` is set up in the `tablet_sstable_set(schema_ptr s, const storage_group_manager& sgm, const locator::tablet_map& tmap)` constructor, but it is not copied in `tablet_sstable_set(const tablet_sstable_set& o)`.

* Requires backport to 6.0

### PR DESCRIPTION
**Pull request by lkshminarayanan**
Commit https://github.com/scylladb/scylladb/commit/9f93dd9fa3376cfe560c65fb9c9c938ff1d3f99d changed `tablet_sstable_set::_sstable_sets` to be a `absl::flat_hash_map` and in addition, `std::set<size_t> _sstable_set_ids` was added. `_sstable_set_ids` is set up in the `tablet_sstable_set(schema_ptr s, const storage_group_manager& sgm, const locator::tablet_map& tmap)` constructor, but it is not copied in `tablet_sstable_set(const tablet_sstable_set& o)`. 

This affects the `tablet_sstable_set::tablet_sstable_set` method as it depends on the copy constructor. Since sstable set can be cloned when a new sstable set is added, the issue will cause ids not being copied into the new sstable set. It's healed only after compaction, since the sstable set is rebuilt from scratch there.

This PR fixes this issue by removing the existing copy constructor of `tablet_sstable_set` to enable the implicit default copy constructor.

Fixes #19519

### CODE REVIEW

**Review by denesb — APPROVED** [review]
@raphaelsc please also review.

File: replica/tablet_sstable_set.hh [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+    }
+
+    tablet_sstable_set(const tablet_sstable_set& o)
+        : _schema(o._schema)
+        , _tablet_map(o._tablet_map.tablet_count())
+        , _sstable_sets(o._sstable_sets)
+        , _sstable_set_ids(o._sstable_set_ids)
+        , _size(o._size)
+        , _bytes_on_disk(o._bytes_on_disk)
+    {}
```
Comment (raphaelsc) [inline replica/tablet_sstable_set.hh:53]: are we able to switch to the default copy ctor here? I think it should be possible. tablet map can be copied, and will have same effect as invoking ctor with tablet count of original map.

File: test/boost/sstable_set_test.cc [hunk 2]
```diff
@@ -167,3 +172,27 @@ SEASTAR_TEST_CASE(test_partitioned_sstable_set_bytes_on_disk) {
...
+            env.execute_cql(fmt::format("INSERT INTO test_tablet_sstable_set_copy_ctor.test (pk) VALUES ({})", i)).get();
+        }
+        auto& cf = env.local_db().find_column_family("test_tablet_sstable_set_copy_ctor", "test");
+        auto& sgm = column_family_test::get_storage_group_manager(cf);
+        sgm->split_all_storage_groups().get();
+
+        replica::tablet_sstable_set tablet_sstable_set(cf.schema(), *sgm.get(), replica::tablet_map(2));
+        auto tablet_sstable_set_copy = tablet_sstable_set;
+        BOOST_REQUIRE(tablet_sstable_set_copy == tablet_sstable_set);
+
```
Comment (raphaelsc) [inline test/boost/sstable_set_test.cc:196]: could we test it through sstable_set interface? so tablet_sstable_set doesn't have to be directly exposed.

1) create tablet set through make_tablet_sstable_set().
2) copy the set, so invokes sstable_set_impl::clone(), which calls tablet_sstable_set's copy ctor
3) then perform an operation on cloned set, which requires _sstable_set_ids to be correct. for example, sstable_set::select(const dht::partition_range&) or all().

**Comment by raphaelsc** [comment]
@lkshminarayanan I suggest you rename patch title to something that describe what the patch fixes. For example, "replica: Fix clone of tablet_sstable_set'. I think this actually can fix a problem, since sstable set can be cloned when a new sstable set is added and will result in ids not being copied into new set. It's healed after compaction, since set is rebuilt from scratch there. Please add it to the description.

File: replica/tablet_sstable_set.hh (hunk 1 above)
Comment (lkshminarayanan) [reply replica/tablet_sstable_set.hh]: yes the default ctor worked.

File: test/boost/sstable_set_test.cc (hunk 2 above)
Comment (lkshminarayanan) [reply test/boost/sstable_set_test.cc:197]: Thank you, this worked. I have updated the code.

**Comment by lkshminarayanan** [comment]
> @lkshminarayanan I suggest you rename patch title to something that describe what the patch fixes. For example, "replica: Fix clone of tablet_sstable_set'. I think this actually can fix a problem, since sstable set can be cloned when a new sstable set is added and will result in ids not being copied into new set. It's healed after compaction, since set is rebuilt from scratch there. Please add it to the description.

Done.

**Review by raphaelsc — APPROVED** [review]

**Comment by lkshminarayanan** [comment]
@scylladb/scylla-maint PR is ready for merge.
