### PR TITLE
Fix for auth version change during node startup

### LINKED ISSUE #25505: [dtest with gossip topology changes] test_schema_and_data_on_mixed_versions_cluster failed with Connection refused
Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-with-gossip-topology-changes/357/

Error message
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.35.2', port=10000): Max retries exceeded with url: /storage_service/raft_topology/upgrade (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51c2f5f3e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Logs - [logs-full.release.000 (1).zip](https://github.com/user-attachments/files/21761675/logs-full.release.000.1.zip)

### PR DESCRIPTION
**Pull request by nuivall**
Before this patch we may trigger `SCYLLA_ASSERT(legacy_mode(_qp))`.
That's because some auth startup is done in the background
and assumes that auth version doesn't change in the middle
of the startup. But topology coordinator may decide to do
the migration at any time, regadless if auth service is
fully started on all nodes.

This change makes sure that in legacy startup flow we'll
always use old auth-v1 keyspace and therefore auth version
change in the middle won't negatively affect the flow.

Fixes https://github.com/scylladb/scylladb/issues/25505

### CODE REVIEW

File: service/topology_coordinator.cc [hunk 1]
```diff
@@ -20,6 +20,7 @@
 #include <seastar/core/with_scheduling_group.hh>
 #include <seastar/util/noncopyable_function.hh>
 
+#include <stdexcept>
```
Comment (andrzej-jackowski-scylladb) [inline service/topology_coordinator.cc]: Why is this include needed? There were already some `throw std::runtime_error` in this file

**Review by andrzej-jackowski-scylladb — APPROVED** [review]
Minor comment regarding #include.
The change looks ok.

File: auth/service.cc [hunk 2]
```diff
@@ -854,7 +854,11 @@ future<> commit_mutations(service& ser, ::service::group0_batch&& mc) {
     return ser.commit_mutations(std::move(mc));
 }
 
-future<> migrate_to_auth_v2(db::system_keyspace& sys_ks, ::service::raft_group0_client& g0, start_operation_func_t start_operation_func, abort_source& as) {
+future<> service::migrate_to_auth_v2(db::system_keyspace& sys_ks, ::service::raft_group0_client& g0, start_operation_func_t start_operation_func, abort_source& as) {
+    // wait until service is fully started, otherwise some init code assuming auth v1
+    // may run after we migrate it to v2 here
+    co_await ensure_superuser_is_created();
```
Comment (piodul) [inline auth/service.cc]: This wait should be abortable and should take `as` as a parameter. I think that `shared_promise::get_shared_future` already allows waiting on it in such a manner, so this shouldn't be a difficult change.

File: service/storage_service.cc [hunk 3]
```diff
@@ -199,6 +200,7 @@ storage_service::storage_service(abort_source& abort_source,
     sharded<db::view::view_builder>& view_builder,
     cql3::query_processor& qp,
     sharded<qos::service_level_controller>& sl_controller,
+    sharded<auth::service>& auth_service,
```
Comment (piodul) [inline service/storage_service.cc]: :(

Not super happy about the fact that we introduce more dependencies. I'm not sure I have a good suggestion to improve this, though - perhaps instead of passing the reference, we could pass a callback which allows to check/wait whether it is fine to proceed with the upgrade. This will discourage from using the auth service for other stuff within storage_service.

**Review by piodul — CHANGES_REQUESTED** [review]
I am not sure the check is 100% solid. The `standard_role_manager::start` function, which calls the problematic `legacy_create_default_role_if_missing` function with the assert looks like this:

```c++
future<> standard_role_manager::start() {
    return once_among_shards([this] () -> future<> {
        if (legacy_mode(_qp)) {
            co_await create_legacy_metadata_tables_if_missing();
        }

        auto handler = [this] () -> future<> {
            const bool legacy = legacy_mode(_qp);
            if (legacy) {
                if (!_superuser_created_promise.available()) {
                    _superuser_created_promise.set_value();
                }
                co_await _migration_manager.wait_for_schema_agreement(_qp.db().real_database(), db::timeout_clock::time_point::max(), &_as);

                if (co_await any_nondefault_role_row_satisfies(_qp, &has_can_login)) {
                    if (legacy_metadata_exists()) {
                        log.warn("Ignoring legacy user metadata since nondefault roles already exist.");
                    }
                    co_return;
                }

                if (legacy_metadata_exists()) {
                    co_await migrate_legacy_metadata();
                    co_return;
                }
                co_await legacy_create_default_role_if_missing();
            }
            if (!legacy) {
                co_await maybe_create_default_role_with_retries();
                if (!_superuser_created_promise.available()) {
                    _superuser_created_promise.set_value();
                }
            }
        };

        _stopped = auth::do_after_system_ready(_as, handler);
        co_return;
    });
}
```

The `_superuser_created_promise` promise - for some reason that is absolutely unknown to me - is set _before_ the superuser is actually created, if we are in legacy mode. Between this and actually trying to create the superuser, there is the schema agreement wait - which should make the race more likely.

I believe that the race can still happen until we actually wait that we got past the`legacy_create_default_role_if_missing` call.

There is an analogous problem with the `password_authenticator` object.

**Comment by andrzej-jackowski-scylladb** [comment]
> The _superuser_created_promise promise - for some reason that is absolutely unknown to me - is set before the superuser is actually created, if we are in legacy mode. 

I'm not the author of the original `_superuser_created_promise` implementation that, in legacy mode, sets the promise before creating the superuser, but my understanding is that the fix was originally introduced to just delay CQL serving before superuser is available to just prevent sporadic test failures. Therefore, the intention was to not modify anything in the legacy mode (e.g. to avoid regression).

However, this PR requires stronger guarantees from the legacy behaviour of `_superuser_created_promise`, so @piodul is right that the fix is **not** working.

File: service/topology_coordinator.cc (hunk 1 above)
Comment (nuivall) [reply service/topology_coordinator.cc]: I guess someone forgot to add it

File: auth/service.cc (hunk 2 above)
Comment (nuivall) [reply auth/service.cc]: ok

File: service/storage_service.cc (hunk 3 above)
Comment (nuivall) [reply service/storage_service.cc]: Ok, we can do something like this to limit the scope.

But problem is general I think that logically there is such dependency, and we just hide it.
It'd help if topology coordinator dependencies were set like all the others in main.cc. And even more if it had  plugable logic wrt running various upgrades and raft dependent inits (e.g. for auth, service levels, etc).

**Comment by nuivall** [comment]
> I am not sure the check is 100% solid.

Yes it is rather 0% solid :) It's unexpected that ready promise is set at the beginning for legacy mode, I'll fix it.

**Comment by nuivall** [comment]
v2:
- added callback instead of auth dependency
- added abort_source
- changed when promise is ready

**Comment by nuivall** [comment]
@scylladbbot trigger-ci

File: auth/password_authenticator.cc [hunk 4]
```diff
@@ -209,33 +209,34 @@ future<> password_authenticator::start() {
...
                     legacy_create_default_if_missing().get();
                 }
                 utils::get_local_injector().inject("password_authenticator_start_pause", utils::wait_for_message(5min)).get();
                 if (!legacy_mode(_qp)) {
                     maybe_create_default_password_with_retries().get();
-                    if (!_superuser_created_promise.available()) {
-                        _superuser_created_promise.set_value();
-                    }
                 }
+                ready();
```
Comment (piodul) [inline auth/password_authenticator.cc]: Nit: I've got a suggestion on how to do it in a cleaner way: add a continuation to the future returned by `async` where you conditionally set the `_superuser_created_promise`. This way, it will be handled in one place and nobody will have to remember to add further `ready` calls (unlikely, but also makes it easier to read the code, at least in my opinion).

File: auth/standard_role_manager.cc [hunk 5]
```diff
@@ -303,31 +303,33 @@ future<> standard_role_manager::start() {
...
             if (!legacy) {
                 co_await maybe_create_default_role_with_retries();
-                if (!_superuser_created_promise.available()) {
-                    _superuser_created_promise.set_value();
-                }
             }
+            ready();
         };
 
         _stopped = auth::do_after_system_ready(_as, handler);
```
Comment (piodul) [inline auth/standard_role_manager.cc:343]: Not sure how you could handle this case with respect to `_superuser_created_promise`, so perhaps it's better to leave it like this and also keep the `password_authenticator` code as it is now as well.

**Review by piodul — COMMENTED** [review]
I've left a single nitpick of a dubious value as a comment to the code.

One question before leaving a verdict. I am worried that you might run into a situation where a non-coordinator node is restarted (e.g. it is upgraded) and then the topology coordinator decides to run the upgrade, before the restarted node finished setting up the auth service. What will happen in that case? Do I understand correctly that if the superuser is already created then it is safe to run the upgrade in parallel? If so then I think that the current approach __will__ work, but it's not immediately obvious - it would be good to write it down in the PR description.

A regression test would be nice to have - I think you can write one relatively easily for the scenario where the restarted node != topology coordinator (which I think is a omre important case than when restarted node == topology coordinator).

**Comment by nuivall** [comment]
>  the topology coordinator decides to run the upgrade, before the restarted node finished setting up the auth service. What will happen in that case? Do I understand correctly that if the superuser is already created then it is safe to run the upgrade in parallel?

So there are 3 flows here:
- migration - done on topology coordinator
- upgrade - done on topology_state_load
- version setup -  done during startup (not relevant here)

Migration is not destructive to auth-v1 data. Since it's performed on coordinator it won't be run concurrently.
But maybe you're right that upgrade via topology_state_load can be called during auth startup, and in such case version can still be changed in the middle.

**Comment by nuivall** [comment]
> The _superuser_created_promise promise - for some reason that is absolutely unknown to me - is set before the superuser is actually created

I finally found the reason for this. It would be easier to spot if the dependencies were managed more explicitly. There is wait_for_schema_agreement on legacy startup path, without any timeout, and it means auth-v1 can't start without majority, that's why we didn't block on auth-v1 startup.

**Comment by nuivall** [comment]
v3: reworked the whole patchset, new approach allows auth version change as it's too complicated to prevent it, but it makes startup not affected by it.

**Review by ptrsmrn — APPROVED** [review]

File: auth/password_authenticator.cc [hunk 6]
```diff
@@ -119,8 +123,7 @@ future<> password_authenticator::migrate_legacy_metadata() const {
 }
 
 future<> password_authenticator::legacy_create_default_if_missing() {
```
Comment (piodul) [inline auth/password_authenticator.cc:125]: I think you missed the `update_row_query` call in this function.

File: auth/password_authenticator.cc [hunk 7]
```diff
@@ -119,7 +123,6 @@ future<> password_authenticator::migrate_legacy_metadata() const {
...
```
Comment (piodul) [inline auth/password_authenticator.cc:125]: `maybe_create_default_password_with_retries` is also called during the `do_after_system_ready` flow, maybe it should be updated as well?

Similarly for `maybe_create_default_role_with_retries` in `standard_role_manager`.

File: auth/password_authenticator.cc (hunk 6 above)
Comment (nuivall) [reply auth/password_authenticator.cc:125]: yes, thanks, I'll move string directly to this func, little benefit in adding param to this function

File: auth/password_authenticator.cc (hunk 7 above)
Comment (nuivall) [reply auth/password_authenticator.cc:125]: yes it is, but this is auth-v2 flow, since there is no v2->v1 downgrade, and we don't know how potential future v2->v3 would look like, we don't need to change it

**Comment by nuivall** [comment]
v4: fixed update_row_query in legacy_create_default_if_missing

**Comment by calebxyz** [comment]
@piodul please see if this is good now

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued
