### PR TITLE
view: row_lock: lock_ck: find or construct row_lock under partition lock

### LINKED ISSUE #12632: Scylla 5.0.9 segfault
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [v] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.0.9
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VM (KVM)
Hardware: vcores=4 memory=32GB
Disks: (SSD/HDD, count) HDD

health check report: 08d974ea-b238-4845-9ac0-30c80f4b997d/prod-data2-health-check-report.txt
core dump: 08d974ea-b238-4845-9ac0-30c80f4b997d/core.scylla.995.05f478d8544d4ee08fa36934d05bb33a.1228.1674525348000000.xz

Scylla 5.0.9 crashed with core dump, don't know what trigger this. Please help check.

```
Jan 24 08:55:48 prod-data2 scylla: Segmentation fault on shard 2.
Jan 24 08:55:48 prod-data2 scylla: Backtrace:
Jan 24 08:55:48 prod-data2 scylla: 0x4445718
Jan 24 08:55:48 prod-data2 scylla: 0x44761f6
Jan 24 08:55:48 prod-data2 scylla: 0x4ac5fd1
Jan 24 08:55:48 prod-data2 scylla: 0x7f8d6c8e5a1f
Jan 24 08:55:48 prod-data2 scylla: 0x447b5b3
Jan 24 08:55:48 prod-data2 scylla: 0x24c422b
Jan 24 08:55:48 prod-data2 scylla: 0x2b715cb
Jan 24 08:55:48 prod-data2 scylla: 0x4456674
Jan 24 08:55:48 prod-data2 scylla: 0x4457a47
Jan 24 08:55:48 prod-data2 scylla: 0x4476765
Jan 24 08:55:48 prod-data2 scylla: 0x442a4ca
Jan 24 08:55:48 prod-data2 scylla: /opt/scylladb/libreloc/libpthread.so.0+0x9298
Jan 24 08:55:48 prod-data2 scylla: /opt/scylladb/libreloc/libc.so.6+0x100352
Jan 24 08:55:48 prod-data2 kernel: reactor-2[1230]: segfault at 8a ip 000000000447b5b4 sp 00007f8d691d3480 error 4 in scylla[fa4000+3e23000]
Jan 24 08:56:53 prod-data2 systemd-coredump: Process 1228 (scylla) of user 995 dumped core.#012#012Stack trace of thread 1230:#012#0  0x000000000447b5b4 _ZN7seastar5timerINS_12lowres_clockEED1Ev (scylla)#012#1  0x00000000024c422c _ZN7seastar15basic_semaphoreINS_35semaphore_default_exception_factoryENS_12lowres_clockEE4waitENSt6chrono10time_pointIS2_NS4_8durationIlSt5ratioILl1ELl1000000000EEEEEEm (scylla)#012#2  0x0000000002b715cc _ZN7seastar12continuationINS_8internal22promise_base_with_typeIN10row_locker11lock_holderEEEZNS3_7lock_ckERKN3dht13decorated_keyERK21clustering_key_prefixbNSt6chrono10time_pointINS_12lowres_clockENSD_8durationIlSt5ratioILl1ELl1000000000EEEEEERNS3_5statsEE3$_2ZNS_6futureINS_15semaphore_unitsINS_35semaphore_default_exception_factoryESF_EEE14then_impl_nrvoISN_NSO_IS4_EEEET0_OT_EUlOS5_RSN_ONS_12future_stateISR_EEE_SR_E15run_and_disposeEv (scylla)#012#3  0x0000000004456675 _ZN7seastar7reactor14run_some_tasksEv (scylla)#012#4  0x0000000004457a48 _ZN7seastar7reactor6do_runEv (scylla)#012#5  0x0000000004476766 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE5$_100E9_M_invokeERKSt9_Any_data (scylla)#012#6  0x000000000442a4cb _ZN7seastar12posix_thread13start_routineEPv (scylla)#012#7  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#8  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1233:#012#0  0x00007f8d6bde25bf __poll (libc.so.6)#012#1  0x000000000449b6c6 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)#012#2  0x00007f8d6bfb0c84 execute_native_thread_routine (libstdc++.so.6)#012#3  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#4  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1236:#012#0  0x00007f8d6c8e494c read (libpthread.so.0)#012#1  0x0000000004498ba5 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)#012#2  0x0000000004498f10 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)#012#3  0x000000000442a4cb _ZN7seastar12posix_thread13start_routineEPv (scylla)#012#4  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#5  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1239:#012#0  0x00007f8d6bde25bf __poll (libc.so.6)#012#1  0x000000000449b6c6 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)#012#2  0x00007f8d6bfb0c84 execute_native_thread_routine (libstdc++.so.6)#012#3  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#4  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1232:#012#0  0x00007f8d6c8e494c read (libpthread.so.0)#012#1  0x0000000004498ba5 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)#012#2  0x0000000004498f10 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)#012#3  0x000000000442a4cb _ZN7seastar12posix_thread13start_routineEPv (scylla)#012#4  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#5  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1228:#012#0  0x000000000236b66d _ZN7service13storage_proxy10mutate_endEN7seastar6futureIvEEN5utils15latency_counterERNS_19storage_proxy_stats11write_statsEN7tracing15trace_state_ptrE (scylla)#012#1  0x000000000242ad90 _ZN7seastar12continuationINS_8internal22promise_base_with_typeIvEEZN7service13storage_proxy15mutate_internalIN5boost14iterator_rangeIN9__gnu_cxx17__normal_iteratorIP8mutationSt6vectorISB_SaISB_EEEEEEEENS_6futureIvEET_N2db17consistency_levelEbN7tracing15trace_state_ptrE14service_permitSt8optionalINSt6chrono10time_pointINS_12lowres_clockENSR_8durationIlSt5ratioILl1ELl1000000000EEEEEEENS_13lw_shared_ptrIN3cdc24operation_result_trackerEEEEUlSJ_E_ZNSJ_17then_wrapped_nrvoISJ_S14_EENS_8futurizeISK_E4typeEOT0_EUlOS3_RS14_ONS_12future_stateINS1_9monostateEEEE_vE15run_and_disposeEv (scylla)#012#2  0x0000000004456675 _ZN7seastar7reactor14run_some_tasksEv (scylla)#012#3  0x0000000004457a48 _ZN7seastar7reactor6do_runEv (scylla)#012#4  0x0000000004456cad _ZN7seastar7reactor3runEv (scylla)#012#5  0x00000000043fd039 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)#012#6  0x00000000043fc517 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIiEEvEE (scylla)#012#7  0x0000000000fa78fe _ZL11scylla_mainiPPc (scylla)#012#8  0x0000000000fa51db main (scylla)#012#9  0x00007f8d6bd14b75 __libc_start_main (libc.so.6)#012#10 0x0000000000fa41ae _start (scylla)#012#012Stack trace of thread 1238:#012#0  0x00007f8d6c8e494c read (libpthread.so.0)#012#1  0x0000000004498ba5 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)#012#2  0x0000000004498f10 _ZNSt17_Function_handlerIFvvEZN7seastar11thread_poolC1EPNS1_7reactorENS1_13basic_sstringIcjLj15ELb1EEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)#012#3  0x000000000442a4cb _ZN7seastar12posix_thread13start_routineEPv (scylla)#012#4  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#5  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1237:#012#0  0x00007f8d6bde25bf __poll (libc.so.6)#012#1  0x000000000449b6c6 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)#012#2  0x00007f8d6bfb0c84 execute_native_thread_routine (libstdc++.so.6)#012#3  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#4  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1231:#012#0  0x00000000013e73be _ZN11intrusive_b4nodeI10rows_entryXadL_ZNS1_5_linkEEENS1_11tri_compareELm12ELm20ELNS_10key_searchE0ELNS_10with_debugE0EE10remove_keyEm (scylla)#012#1  0x0000000001403e69 _ZN10rows_entry10on_evictedER13cache_tracker (scylla)#012#2  0x000000000143a9b3 _ZNSt17_Function_handlerIFN7seastar6memory17reclaiming_resultEvEZN13cache_trackerC1ER26mutation_application_statsNS0_10bool_classI20register_metrics_tagEEE3$_0E9_M_invokeERKSt9_Any_data (scylla)#012#3  0x00000000014d15ed _ZN8logalloc11region_impl10evict_someEv (scylla)#012#4  0x00000000014dd0e9 _ZN8logallocL22reclaim_from_evictableERNS_11region_implEmN7seastar10bool_classI18is_preemptible_tagEE (scylla)#012#5  0x00000000014d8dc8 _ZN8logalloc7tracker4impl24compact_and_evict_lockedEmmN7seastar10bool_classI18is_preemptible_tagEE (scylla)#012#6  0x00000000014c9c27 _ZN8logalloc7tracker4impl17compact_and_evictEmmN7seastar10bool_classI18is_preemptible_tagEE (scylla)#012#7  0x00000000014c8560 _ZN8logalloc12segment_pool16allocate_segmentEm (scylla)#012#8  0x00000000014e6c58 _ZN8logalloc18allocating_section7reserveEv (scylla)#012#9  0x00000000018aec2d _ZN8sstables27index_consume_entry_contextINS_14index_consumerEE13process_stateERN7seastar16temporary_bufferIcEE (scylla)#012#10 0x00000000018ab75f _ZZN7seastar12input_streamIcE7consumeISt17reference_wrapperIN8sstables27index_consume_entry_contextINS4_14index_consumerEEEEEENS_6futureIvEEOT_ENUlvE_clEv (scylla)#012#11 0x00000000018b4ce1 _ZN7seastar8internal8repeaterIZNS_12input_streamIcE7consumeISt17reference_wrapperIN8sstables27index_consume_entry_contextINS6_14index_consumerEEEEEENS_6futureIvEEOT_EUlvE_E15run_and_disposeEv (scylla)#012#12 0x0000000004456675 _ZN7seastar7reactor14run_some_tasksEv (scylla)#012#13 0x0000000004457a48 _ZN7seastar7reactor6do_runEv (scylla)#012#14 0x0000000004476766 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE5$_100E9_M_invokeERKSt9_Any_data (scylla)#012#15 0x000000000442a4cb _ZN7seastar12posix_thread13start_routineEPv (scylla)#012#16 0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#17 0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1235:#012#0  0x00007f8d6bde25bf __poll (libc.so.6)#012#1  0x000000000449b6c6 _ZN7seastar21reactor_backend_epoll26task_quota_timer_thread_fnEv (scylla)#012#2  0x00007f8d6bfb0c84 execute_native_thread_routine (libstdc++.so.6)#012#3  0x00007f8d6c8db299 start_thread (libpthread.so.0)#012#4  0x00007f8d6bded353 __clone (libc.so.6)#012#012Stack trace of thread 1234:#012#0  0x00007f8d6c8e494c read (libpthread.so.0)#012#1  0x0000000004498ba5 _ZN7seastar11thread_p
```

### PR DESCRIPTION
**Pull request by bhalevy**
Since we're potentially searching the row_lock in parallel to acquiring the read_lock on the partition, we're racing with row_locker::unlock that may erase the _row_locks entry for the same clustering key, since there is no lock to protect it up until the partition lock has been acquired and the lock_partition future is resolved.

This change moves the code to search for or allocate the row lock _after_ the partition lock has been acquired to make sure we're synchronously starting the read/write lock function on it, without yielding, to prevent this use-after-free.

This adds an allocation for copying the clustering key in advance that wasn't needed before if the lock for it was already found, but the view building is not on the hot path so we can tolerate that.

This is required on top of 5007ded2c19303ce1bc95cb6b313597b1b9de2d6 as seen in https://github.com/scylladb/scylladb/issues/12632 which is closely related to #12168 but demonstrates a different race causing use-after-free.

Fixes #12632

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

File: db/view/row_locking.cc [hunk 1]
```diff
@@ -85,29 +85,21 @@ future<row_locker::lock_holder>
 row_locker::lock_ck(const dht::decorated_key& pk, const clustering_key_prefix& cpk, bool exclusive, db::timeout_clock::time_point timeout, stats& stats) {
     mylog.debug("taking shared lock on partition {}, and {} lock on row {} in it", pk, (exclusive ? "exclusive" : "shared"), cpk);
     auto tracker = latency_stats_tracker(exclusive ? stats.exclusive_row : stats.shared_row);
+    auto ck = cpk;
+    // The two-level lock is guaranteed to be kept alive as long as it's locked.
```
Comment (nyh) [inline db/view/row_locking.cc:89]: nitpick: I would move this comment one line down, and start it with "the two_level_locks entry we just created  guaranteed to be kept alive ...".

**Review by nyh — APPROVED** [review]
Looks good, but one comment about the commit message:
You talks about the performance impact of the key copying. It's in "view building" as you said - it's any view updates, so it's sort of the hot path. BUT, I think the important point is that it only us slows down (a bit) when there is contention and the lock already existed when we want to go locking. In the fast path I would say there is no contention and then the code already had to create the lock and copy the key.
In any case I think the penalty of copying the key one is tiny compared to the rest of the work that view updates are doing.

**Comment by avikivity** [comment]
> This adds an allocation for copying the clustering key in advance that wasn't needed before if the lock for it was already found, but the view building is not on the hot path so we can tolerate that.


Also, the common case is not to find the lock.

File: db/view/row_locking.cc [hunk 2]
```diff
@@ -85,29 +85,21 @@ future<row_locker::lock_holder>
...
-                // TODO: unlock (lock = {}) now, search for the partition in the
-                // hash table (we know it's still there, because we held the lock until
-                // now) and remove the unused lock from the hash table if still unused.
-                return make_exception_future<row_locker::lock_holder>(std::current_exception());
-            });
+    return lock_partition.then([this, pk = &i->first, row_locks = &i->second._row_locks, ck = std::move(ck), exclusive, tracker = std::move(tracker), timeout] (auto lock1) mutable {
+        auto j = row_locks->find(ck);
+        if (j == row_locks->end()) {
+            // Not yet locked, need to create the lock.
+            j = row_locks->emplace(std::move(ck), lock_type()).first;
```
Comment (avikivity) [inline db/view/row_locking.cc:99]: This could be simplified to try_emplace. However, let's not mix it into this bug fix, and instead follow up post-merge as a cleanup.

**Review by avikivity — APPROVED** [review]
Amazing how many bugs such a small piece of code can hold.

**Comment by avikivity** [comment]
@benipeled yet another case of concurrent CI runs.

File: db/view/row_locking.cc (hunk 2 above)
Comment (bhalevy) [reply db/view/row_locking.cc:99]: Agreed

**Comment by bhalevy** [comment]
In v2 ([d2893f9](https://github.com/scylladb/scylladb/commit/d2893f93cbfb6d36c20f182d638eee2c363c1c0f)):
- improved comments
- added "view: row_lock: lock_ck: try_emplace row_lock entry"
