### PR TITLE
atomic_cell: compare value last

### LINKED ISSUE #14182: compare_cells_for_merge may wrongly prefer an expired cell over a live and expiring one
`compare_atomic_cell_for_merge` currently compares cell values for two live / expiring cells that have the same write timestamp.

If the values are different, the function selects the cell with the larger value, without comparing their expiration time and ttl.

That may lead to selecting an already expired cell over one that is still alive and that will expire later.
This may show up over cql as a row with null value for the cell, instead of no results if only the expired cell would exist.

Detailed description:
The comparison function is implemented as follows:
https://github.com/scylladb/scylladb/blob/ce6a1ca13b598e1ecbf60c270b69a3810053522c/mutation/atomic_cell.cc#L73-L110

It compares the cell's attributes in the following order:
1. timestamp
2. liveliness
and in case both are alive:
3. value
4. has_ttl (prefer expiring cells)
if both are expiring
5. expiry (prefer cells that expire later)
6. ttl (prefer cells that were written later, i.e. have smaller ttl)

With eventual consistency semantics, it's unclear why comparing cells value trumps over timing related attributes, where the write timestamp-based logic clearly dictates that latest writes wins, regardless of the value they carry.
So when 2 cells timestamp is equal, we should pick the one that appears to have been written later, and only if all timing-related attributes are equal, examine the value so to keep the selection algorithm deterministic.

This was suggested by @vladzcloudius based on a field issue where the user apparently uses `USING TIMESTAMP` and hits a corner case when apparently retrying a write using a previously used timestamp that causes a cell to lose its value:

This was reproduced by @tgrabiec as follows:
```
cqlsh> insert into test.t (pk, ck, v) values (1, 2, 100) using ttl 10 and timestamp 700;
cqlsh> insert into test.t (pk, ck, v) values (1, 2, 90) using ttl 10 and timestamp 700;

cqlsh> select * from test.t;

 pk | ck | v
----+----+-----
  1 |  2 | 100

(1 rows)
cqlsh> select * from test.t;

 pk | ck | v
----+----+------
  1 |  2 | null
```

### PR DESCRIPTION
**Pull request by bhalevy**
Currently, when two cells have the same write timestamp
and both are alive or expiring, we compare their value first,
before checking if either of them is expiring
and if both are expiring, comparing their expiration time
and ttl value to determine which of them will expire
later or was written later.

This was based on an early version of Cassandra.
However, the Cassandra implementation rightfully changed in
https://github.com/apache/cassandra/commit/e225c88a65f2e8091f8ea6212c291416674882a1 ([CASSANDRA-14592](https://issues.apache.org/jira/browse/CASSANDRA-14592)),
where the cell expiration is considered before the cell value.

To summarize, the motivation for this change is three fold:
1. Cassandra compatibility
2. Prevent an edge case where a null value is returned by select query when an expired cell has a larger value than a cell with later expiration.
3. A generalization of the above: value-based reconciliation may cause select query to return a mixture of upserts, if multiple upserts use the same timeastamp but have different expiration times.  If the cell value is considered before expiration, the select result may contain cells from different inserts, while reconciling based the expiration times will choose cells consistently from either upserts, as all cells in the respective upsert will carry the same expiration time.

Fixes #14182

Also, this series:
- updates dml documentation
- updates internal documentation
- updates and adds unit tests and cql pytest reproducing #14182

### CODE REVIEW

**Comment by avikivity** [comment]
When did the change in the algorithm happen (commit)?

**Comment by bhalevy** [comment]
> When did the change in the algorithm happen (commit)?

The problem was there early on, when f43836eb687542cbdf9d24ac162a80dd1f53a335 initially added handling of expirations, already evaluated after comparing the cell value.

**Comment by avikivity** [comment]
> > When did the change in the algorithm happen (commit)?
> 
> The problem was there early on, when [f43836e](https://github.com/scylladb/scylladb/commit/f43836eb687542cbdf9d24ac162a80dd1f53a335) initially added handling of expirations, already evaluated after comparing the cell value.

Ok, so backport all the way to 0.10.

**Comment by avikivity** [comment]
@tgrabiec please review. I don't have intuition about whether the old or new algorithm are more correct.

**Comment by nyh** [comment]
A comment I wrote in the issue:
"If we change the order in our code, we may need to do something to avoid the above "oscillation" problem on mixed clusters during upgrade".
Do you think it's fine to not handle this issue?

**Comment by nyh** [comment]
> also add a cql pytest to reproducing #14182.

We already have a test file, "test-timestamp.py", for tests of USING TIMESTAMP. Please add your test to that file - and feel free to rename it in your patch (I admit test_using_timestamp.py is a better name, and I don't know why this test ended up the only one having a minus instead of an underscore in its name...)

**Comment by bhalevy** [comment]
> > also add a cql pytest to reproducing #14182.
> 
> We already have a test file, "test-timestamp.py", for tests of USING TIMESTAMP. Please add your test to that file - and feel free to rename it in your patch (I admit test_using_timestamp.py is a better name, and I don't know why this test ended up the only one having a minus instead of an underscore in its name...)

Done in [8cd6755](https://github.com/scylladb/scylladb/commit/8cd67559b7ceef7fc2cf923ff533ff5a5e22407f)

File: mutation/atomic_cell.cc [hunk 1]
```diff
@@ -79,23 +79,20 @@ compare_atomic_cell_for_merge(atomic_cell_view left, atomic_cell_view right) {
         return left.is_live() ? std::strong_ordering::less : std::strong_ordering::greater;
```
Comment (vladzcloudius) [inline mutation/atomic_cell.cc:79]: I think that giving a live cell preference to not-live cell even if the not-live cell was written after the live cell is not obvious at all.

File: test/boost/mutation_test.cc [hunk 2]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
     assert_order(
         atomic_cell::make_live(*bytes_type, 1, bytes("value")),
         atomic_cell::make_live(*bytes_type, 1, bytes("value"), expiry_1, ttl_1));
 
+    testlog.debug("Live cells are ordered before expiring cells, regardless of their value");
+    assert_order(
+        atomic_cell::make_live(*bytes_type, 1, bytes("value2")),
+        atomic_cell::make_live(*bytes_type, 1, bytes("value1"), expiry_1, ttl_1));
+
+    testlog.debug("Dead cells with same expiry are equal");
```
Comment (vladzcloudius) [inline test/boost/mutation_test.cc:718]: another unrelated change

File: test/boost/mutation_test.cc [hunk 3]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
     assert_equal(
         atomic_cell::make_dead(1, expiry_1),
         atomic_cell::make_dead(1, expiry_1));
 
+    testlog.debug("Live cells are ordered before expiring cells, with empty value");
```
Comment (vladzcloudius) [inline test/boost/mutation_test.cc:723]: and another one

File: test/boost/mutation_test.cc [hunk 4]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
     assert_order(
         atomic_cell::make_live(*bytes_type, 1, bytes()),
         atomic_cell::make_live(*bytes_type, 1, bytes(), expiry_2, ttl_2));
 
     // Origin doesn't compare ttl (is it wise?)
     // But we do. See https://github.com/scylladb/scylla/issues/10156
     // and https://github.com/scylladb/scylla/issues/10173
+    testlog.debug("Expiring cells with higher ttl are ordered before expiring cells with smaller ttl and same expiry time");
```
Comment (vladzcloudius) [inline test/boost/mutation_test.cc:731]: and another one

File: test/boost/mutation_test.cc [hunk 5]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
     assert_order(
         atomic_cell::make_live(*bytes_type, 1, bytes("value"), expiry_1, ttl_2),
         atomic_cell::make_live(*bytes_type, 1, bytes("value"), expiry_1, ttl_1));
 
+    testlog.debug("Cells are ordered by value if all else is equal");
     assert_order(
         atomic_cell::make_live(*bytes_type, 0, bytes("value1")),
         atomic_cell::make_live(*bytes_type, 0, bytes("value2")));
 
+    testlog.debug("Cells are ordered by value in lexicographical order if all else is equal");
```
Comment (vladzcloudius) [inline test/boost/mutation_test.cc:741]: and another one

File: test/boost/mutation_test.cc [hunk 6]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
+        atomic_cell::make_live(*bytes_type, 1, bytes("value1"), expiry_1, ttl_1),
+        atomic_cell::make_live(*bytes_type, 1, bytes("value2"), expiry_1, ttl_1));
+
+    testlog.debug("Dead wins");
     assert_order(
         atomic_cell::make_live(*bytes_type, 1, bytes("value")),
         atomic_cell::make_dead(1, expiry_1));
 
-    // Dead wins with expiring cell
+    testlog.debug("Dead wins with expiring cell");
```
Comment (vladzcloudius) [inline test/boost/mutation_test.cc:771]: and another one

File: test/boost/mutation_test.cc [hunk 7]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
         atomic_cell::make_dead(1, expiry_1));
 
-    // Deleted cells are ordered first by timestamp
+    testlog.debug("Deleted cells are ordered first by timestamp...");
     assert_order(
         atomic_cell::make_dead(1, expiry_2),
         atomic_cell::make_dead(2, expiry_1));
 
-    // ...then by expiry
+    testlog.debug("...then by expiry");
```
Comment (vladzcloudius) [inline test/boost/mutation_test.cc:781]: and another one

**Review by vladzcloudius — CHANGES_REQUESTED** [review]

File: test/boost/mutation_test.cc [hunk 8]
```diff
@@ -703,68 +700,85 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
 
+    testlog.debug("Live cells are ordered before expiring cells");
     assert_order(
         atomic_cell::make_live(*bytes_type, 1, bytes("value")),
         atomic_cell::make_live(*bytes_type, 1, bytes("value"), expiry_1, ttl_1));
 
+    testlog.debug("Live cells are ordered before expiring cells, regardless of their value");
+    assert_order(
+        atomic_cell::make_live(*bytes_type, 1, bytes("value2")),
+        atomic_cell::make_live(*bytes_type, 1, bytes("value1"), expiry_1, ttl_1));
```
[the remark this answers is not in the document]
Comment (denesb) [reply test/boost/mutation_test.cc:716]: Only expiring/dead cells have a write time. Live cells don't have one.

File: mutation/atomic_cell.cc (hunk 1 above)
Comment (denesb) [reply mutation/atomic_cell.cc:79]: We have no way to determine this. We use timestamps to determine order and we are in a tie. Our ordering broke down, and we just need *some* order (bonus if it is also intuitive).

Comment (vladzcloudius) [reply mutation/atomic_cell.cc:79]: @denesb Don't we always store a coordinator time *together* with a "timestamp" (which can be overridden with `USING TIMESTAMP`)? 
Or we only have it if there if data is TTLed and we have an `expire_at`?

Comment (vladzcloudius) [reply mutation/atomic_cell.cc:79]: @bhalevy is the code with this patch copies the latest C* logic 1-to-1?

File: mutation/atomic_cell.cc [hunk 9]
```diff
@@ -79,23 +79,20 @@ compare_atomic_cell_for_merge(atomic_cell_view left, atomic_cell_view right) {
...
         if (left.is_live_and_has_ttl() != right.is_live_and_has_ttl()) {
             // prefer expiring cells.
             return left.is_live_and_has_ttl() ? std::strong_ordering::greater : std::strong_ordering::less;
         }
         if (left.is_live_and_has_ttl()) {
             if (left.expiry() != right.expiry()) {
                 return left.expiry() <=> right.expiry();
-            } else {
+            } else if (right.ttl() != left.ttl()) {
                 // prefer the cell that was written later,
```
Comment (vladzcloudius) [inline mutation/atomic_cell.cc:90]: This comment doesn't seem to reflect the need logic: the following comparison is going to order based on the TTL value - not the "expiry" (which would match the old comment).

You probably want to move this comment above line 87 and add a different comment here.

**Review by vladzcloudius — CHANGES_REQUESTED** [review]

File: test/boost/mutation_test.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (vladzcloudius) [reply test/boost/mutation_test.cc:716]: I see. It kinda makes sense to me now too: they want to prefer the value that has the longest "expire_at" and the alive cell has an infinite value for this (formally).

**Review by vladzcloudius — CHANGES_REQUESTED** [review]
The code makes sense to me logically.
Beyond a few cosmetic changes I requested yesterday and today it looks good to me.

**Comment by avikivity** [comment]
The patch  fixes the issue, but that's only because they are phrased the same way.

Issue: we should do X
Patch: do X

That's convenient, but it avoids the question of what's the right behavior, what's the user impact, and what should be written in the release notes.

**Comment by bhalevy** [comment]
> The patch fixes the issue, but that's only because they are phrased the same way.
> 
> Issue: we should do X Patch: do X
> 
> That's convenient, but it avoids the question of what's the right behavior, what's the user impact, and what should be written in the release notes.

I edited the issue title and description to describe the user visible impact rather than the technical details.

File: test/cql-pytest/test_using_timestamp.py [hunk 10]
```diff
@@ -90,3 +90,56 @@ def test_key_writetime(cql, table1):
         cql.execute(f'SELECT writetime(k) FROM {table1}')
     with pytest.raises(InvalidRequest, match='PRIMARY KEY part k'):
         cql.execute(f'SELECT ttl(k) FROM {table1}')
+
+# Reproducer for https://github.com/scylladb/scylladb/issues/14182
+def test_rewrite_using_same_timeout_and_ttl(scylla_only, cql, table1):
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:95]: Wait, what?
I thought the main point of this patch was to behave like Cassandra always did in this specific case. So why a scylla_only test case?

File: test/cql-pytest/test_using_timestamp.py [hunk 11]
```diff
@@ -90,3 +90,56 @@ def test_key_writetime(cql, table1):
...
+        rewrite = f"INSERT INTO {table} (k, v) VALUES ({k}, {v2}) USING TIMESTAMP {ts2} AND TTL {ttl2}"
+        cql.execute(rewrite)
+        select = f"SELECT * FROM {table} WHERE k = {k}"
+        res = list(cql.execute(select))
+        expected = v1 if v1 >= v2 else v2
+        if res[0].v != expected:
+            errors.append(f"Expected (k={k}, v={expected}) after immediate rewrite in iteration {i}, but got {res[0]}")
+
+        delay = 4
+        time.sleep(delay)
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:120]: Sad you need such a long sleep. To be honest, I don't understand why you need to sleep at all, can't you read the data and its ttl() immediately and see this problem without needing to wait for the TTL?
This also relates to my question about what it is that we are **really** fixing in this PR, I'll write it as a separate comment.

File: test/cql-pytest/test_using_timestamp.py [hunk 12]
```diff
@@ -90,3 +90,56 @@ def test_key_writetime(cql, table1):
...
+        expire1 = t1 + ttl1
+        time.sleep(expire1 - time.time() + 2)
+        res = list(cql.execute(select))
+        # reading after the first write expires should return the latter value
+        expected = v2
+        if res[0].v != expected:
+            errors.append(f"Expected (k={k}, v={expected}) after first expiration in iteration {i}, but got {res[0]}")
+
+        expire2 = t2 + ttl2
+        time.sleep(expire2 - time.time() + 2)
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:138]: Please remember that typical cql-pytest tests take time measured in milliseconds, and think if there is no way to do this test without so many multi-second sleeps. I think no sleeps are really needed here (see above) but maybe I'm missing something?

**Review by nyh — CHANGES_REQUESTED** [review]
Although I understand this patch, I don't like the fact that it's **motivation** is ambiguous, and it makes it harder to review if the implementation lives up to the motivation. I can think of three related, but different motivations:

1. @vladzcloudius believes that this this patch fixes a real "error", and your commit message also claims it avoids a "weird corner case". What is this error / corner case, and without explaining what it is, how can I review that the code fixes it and the test reproduces it?
2. The fact that Cassandra's ordering is different from Scylla's was mentioned several times, and a possible motivation was to make them the same. But did we? The test is marked "scylla_only", suggesting it fails on Cassandra. But why?
3. Why I try to explain the motivation of this patch to myself, it's not about the TTL at all! Instead, it's about what to do when a user send different writes A and write B with the same timestamp - how can we try (if possible) to make sure either A or B gets written but not a mixture half-A-half-B? When writes have expiration-times, we are lucky:  In CQL, when you do a write, all of it will have the **same** expiration time. So all the cells in A have the same expiration time tA, and all the cells in B have the same expiration tB. If tA != tB (e.g., we have default-TTL and more than a second passed between the two writes), if we base the reconciliation decision on the expiration time, not cell values - we can consistently choose either A and B without mixing them!

I think the real motivation is, or should be, 3. Stating that this is the motivation isn't just nice for understanding, or for understanding how serious (or not) this issue is, it can also change the way you look at testing this issue. Benny, your test has a lot of sleeps waiting until the the data actually expires. Although it might make sense to have a slow test that exactly reproduces the same scenario that the user saw, I think you can actually reproduce the usefulness of this patch in one second (unfortunately, not less): Do a write A of two int cells with values 0, 1 with TTL 1000, sleep a whole second (unfortunately), then do a write B of the cells with values 1, 0 with TTL 1000. Now read. Before this patch, I believe you'll read a mixture of A and B (I think 0,0)). After this patch, you'll read one of A or B - not a mixture of the two. Also, unless I'm missing something, the same test should pass on Cassandra.

**Comment by bhalevy** [comment]
In v2 ([ea9cb20](https://github.com/scylladb/scylladb/commit/ea9cb201936c506449ebc69b077442d6405cd551))
- rebased
- cleaned up changes to unit test (separating cosmetic changes from functional ones)
- added and update source documentation for `compare_atomic_cell_for_merge`
- Update user-facing doc: docs/cql/dml.rst with a new, `Update ordering` section

**Comment by bhalevy** [comment]
> Although I understand this patch, I don't like the fact that it's **motivation** is ambiguous, and it makes it harder to review if the implementation lives up to the motivation.

Good point.  Let's clear that out.

> I can think of three related, but different motivations:
> 
> 1. @vladzcloudius believes that this this patch fixes a real "error", and your commit message also claims it avoids a "weird corner case". What is this error / corner case, and without explaining what it is, how can I review that the code fixes it and the test reproduces it?

Sure.  I'll describe the case more clearly.

> 2. The fact that Cassandra's ordering is different from Scylla's was mentioned several times, and a possible motivation was to make them the same. But did we? The test is marked "scylla_only", suggesting it fails on Cassandra. But why?

Today, after reviewing both implementation, I convinced myself the implementation are now compatible and the scylla_only marker can be removed (will do in next version of the series)

> 3. Why I try to explain the motivation of this patch to myself, it's not about the TTL at all! Instead, it's about what to do when a user send different writes A and write B with the same timestamp - how can we try (if possible) to make sure either A or B gets written but not a mixture half-A-half-B? When writes have expiration-times, we are lucky:  In CQL, when you do a write, all of it will have the **same** expiration time. So all the cells in A have the same expiration time tA, and all the cells in B have the same expiration tB. If tA != tB (e.g., we have default-TTL and more than a second passed between the two writes), if we base the reconciliation decision on the expiration time, not cell values - we can consistently choose either A and B without mixing them! If we're lucky, we shouldn't waste this luck!

That's a good point and another motivator for this change (that I didn't think about).

> I think the real motivation is, or should be, 3. Stating that this is the motivation isn't just nice for understanding, or for understanding how serious (or not) this issue is, it can also change the way you look at testing this issue. Benny, your test has a lot of sleeps waiting until the the data actually expires. Although it might make sense to have a slow test that exactly reproduces the same scenario that the user saw, I think you can actually reproduce the usefulness of this patch in one second (unfortunately, not less) - without waiting for anything to expire: Do a write A of two int cells with values 0, 1 with TTL 1000, sleep a whole second (unfortunately), then do a write B of the cells with values 1, 0 with TTL 1000. Now read. Before this patch, I believe you'll read a mixture of A and B (I think 0,0)). After this patch, you'll read one of A or B - not a mixture of the two. Also, unless I'm missing something, the same test should pass on Cassandra.

I'll try that.

File: test/cql-pytest/test_using_timestamp.py (hunk 10 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:95]: I wasn't sure at the time that we're indeed compatible.
Today I'm more confident that we are (with recent enough version of Cassandra).
I'll test that in the next version of this series.

File: test/cql-pytest/test_using_timestamp.py (hunk 11 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:120]: I'd like to reproduce the actual issue, rather than testing for indirect evidence.
But I'll see if it can be reproduced reliably using short timeouts.

File: test/cql-pytest/test_using_timestamp.py (hunk 12 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:138]: I wanted to reproduce the null value issue, and that requires the first insert to expire.

**Comment by bhalevy** [comment]
> When did the change in the algorithm happen (commit)?

@avikivity our original implementation was based on a respectively old version of Cassandra.
They changed their algorithm in https://github.com/apache/cassandra/commit/e225c88a65f2e8091f8ea6212c291416674882a1 ([CASSANDRA-14592](https://issues.apache.org/jira/browse/CASSANDRA-14592)), but we didn't update our implementation correspondingly.

**Comment by bhalevy** [comment]
In v3 ([3214dbf](https://github.com/scylladb/scylladb/commit/3214dbf17088c830ccd5ec6000a970e2222088c3)):
- Improved user-facing docs
- Improved annotations in git commits
- cql-pytest
  - reduce timeouts
  - removed `scylla_only` marker
  - added test case for updating multiple cells
- updated description of this PR to clarify the motivation for the change.

**Comment by bhalevy** [comment]
In [6c98ed4](https://github.com/scylladb/scylladb/commit/6c98ed4cb73638878d4422a197f62e89292aac0d): changed git commit log to `Refs` https://github.com/scylladb/scylladb/issues/14063 rather than `Fixes`.

**Comment by nyh** [comment]
Some comments about the new cover letter:

> Currently, when two cells have the same write timestamp and both are alive or expiring, we compare their value first, before checking if either of them is expiring and if both are expiring, comparing their expiration time and ttl value to determine which of them will expire later or was written later.

I think the phrase "was written later" is misleading. As I understand your code, you don't check which write was done "later". All we know is that in CQL as it is today, a single write statement (INSERT or UPDATE) will always set every touched cell to the same "expiration time", so we can consistently choose between two separate writes in all cells. We don't know if what we chose is "later" or "earlier".

If you really wanted to see which write was "later" I think you should calculate `expire - ttl`, and use that as an estimate (one second resolution) for the item's write time. But I don't see your code doing that.

> 
> This was based on an early version of Cassandra. However, the Cassandra implementation rightfully changed in [apache/cassandra@e225c88](https://github.com/apache/cassandra/commit/e225c88a65f2e8091f8ea6212c291416674882a1) ([CASSANDRA-14592](https://issues.apache.org/jira/browse/CASSANDRA-14592)), where the cell expiration is considered before the cell value.

I'm confused - are you sure that this Cassandra issue was about the same situation that we're fixing here, and not yet another corner case?

File: test/boost/mutation_test.cc [hunk 13]
```diff
@@ -710,6 +710,11 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
         atomic_cell::make_live(*bytes_type, 1, bytes("value")),
         atomic_cell::make_live(*bytes_type, 1, bytes("value"), expiry_1, ttl_1));
 
+    testlog.debug("Live cells are ordered before expiring cells, regardless of their value");
```
Comment (nyh) [inline test/boost/mutation_test.cc:713]: "live" cells does not contrast with "expiring" cells. It seems that in your example, both cells are live - just one has a ttl and one doesn't.

File: test/boost/mutation_test.cc [hunk 14]
```diff
@@ -748,6 +753,16 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
         atomic_cell::make_live(*bytes_type, 1, bytes(), expiry_1, ttl_1),
         atomic_cell::make_live(*bytes_type, 1, bytes(), expiry_2, ttl_1));
 
+    testlog.debug("...then by ttl (in reverse)");
```
Comment (nyh) [inline test/boost/mutation_test.cc:756]: I don't like these C++ tests because it's not possible to run them against Cassandra and check if we just invented our own rules, or Cassandra also follows the same rules.

File: mutation/atomic_cell.cc [hunk 15]
```diff
@@ -66,24 +66,27 @@ atomic_cell::atomic_cell(const abstract_type& type, atomic_cell_view other)
...
         return left.is_live() ? std::strong_ordering::less : std::strong_ordering::greater;
     }
     if (left.is_live()) {
+        // Prefer expiring cells (which will become tombstones at some future date) over live cells.
+        // See https://issues.apache.org/jira/browse/CASSANDRA-14592
         if (left.is_live_and_has_ttl() != right.is_live_and_has_ttl()) {
-            // prefer expiring cells.
             return left.is_live_and_has_ttl() ? std::strong_ordering::greater : std::strong_ordering::less;
         }
+        // If both are expiring, we do not want to consult the value bytes if we can avoid it, as like with C-14592
```
Comment (nyh) [inline mutation/atomic_cell.cc:87]: I didn't understand why this is like CASSANDRA-14592 (please don't shorthand Cassandra's bug-number convention). But anyway, since we have our own issue about this now, probably should mention that?

File: docs/cql/dml.rst [hunk 16]
```diff
@@ -601,7 +601,7 @@ by the same node are unique. Timestamps assigned at different
 nodes are not guaranteed to be globally unique.
 With a steadily high write rate timestamp collision
 is not unlikely. If it happens, i.e. two ``INSERTS`` have the same
-timestamp, the lexicographically bigger value prevails:
+timestamp, a tie-breaking algorithm determines which if the inserts prevails (see :ref:`update ordering <update-ordering>`).
```
Comment (nyh) [inline docs/cql/dml.rst:604]: This phrasing (also before your change, but also after) seems to suggest than one of the two INSERTS will prevail, while in reality, under some conditions, the result can be a weird mix of the two (with each column getting the maximum value from the two inserts).

File: test/cql-pytest/test_using_timestamp.py [hunk 17]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
         cql.execute(f'SELECT writetime(k) FROM {table1}')
     with pytest.raises(InvalidRequest, match='PRIMARY KEY part k'):
         cql.execute(f'SELECT ttl(k) FROM {table1}')
+
+# Reproducer for https://github.com/scylladb/scylladb/issues/14182
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:94]: If you already bothered to write a paragraph-long explanation of this test (and the second test) in the commit message, it will be great to copy it here. So in a few years if this test fails, the reader won't need to start guessing what this test was supposed to check.

Nitpick: It's great that you mentioned the issue that this reproduces, but you can also write "#14182" instead of the long github link.

File: test/cql-pytest/test_using_timestamp.py [hunk 18]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
...
+    values = [[1, 1], [1, 2], [2, 1]]
+    errors = []
+    for i in range(3):
+        v1, v2 = values[i]
+
+        # sync with wall-clock on exact second so that expiration won't cross the whole-second boundary
+        t1 = time.time()
+        while t1 - int(t1) >= 0.9:
+            time.sleep(1 - (t1 - int(t1)))
+            t1 = time.time()
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:110]: I think this is risky. On a very slow machine it can do weird things. Why is this even necessary?

**Comment by bhalevy** [comment]
> Some comments about the new cover letter:
> 
> > Currently, when two cells have the same write timestamp and both are alive or expiring, we compare their value first, before checking if either of them is expiring and if both are expiring, comparing their expiration time and ttl value to determine which of them will expire later or was written later.
> 
> I think the phrase "was written later" is misleading. As I understand your code, you don't check which write was done "later". All we know is that in CQL as it is today, a single write statement (INSERT or UPDATE) will always set every touched cell to the same "expiration time", so we can consistently choose between two separate writes in all cells. We don't know if what we chose is "later" or "earlier".
> 
> If you really wanted to see which write was "later" I think you should calculate `expire - ttl`, and use that as an estimate (one second resolution) for the item's write time. But I don't see your code doing that.

The existing code already does this, though it might not be obvious.
After comparing the `expiry()` time point, when it's equal on both cells, we compare the `ttl()` value and choose the cell with the smaller `ttl`.  As the comment there says, a smaller `ttl` for the same `expiry` means a later write time.
> 
> > This was based on an early version of Cassandra. However, the Cassandra implementation rightfully changed in [apache/cassandra@e225c88](https://github.com/apache/cassandra/commit/e225c88a65f2e8091f8ea6212c291416674882a1) ([CASSANDRA-14592](https://issues.apache.org/jira/browse/CASSANDRA-14592)), where the cell expiration is considered before the cell value.
> 
> I'm confused - are you sure that this Cassandra issue was about the same situation that we're fixing here, and not yet another corner case?

The Cassandra change does not mention this issue, but practically, it prevents its.
The motivation for https://issues.apache.org/jira/browse/CASSANDRA-14592 as I understand is more about considering the cell expiration so that expiring cells are preferred over live cells with the same write timestamp, before the expiring cell becomes a tombstone, in which case it will be preferred over the live cell, based on an earlier term in the algorithm.

File: test/cql-pytest/test_using_timestamp.py [hunk 19]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
...
+
+        cql.execute(f"INSERT INTO {table} (k, v) VALUES ({k}, {v1}) USING TIMESTAMP {ts} AND TTL {ttl1}")
+        # rewriting right away, so that both cells will carry the same expiry and ttl should return the larger value
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:113]: I wouldn't test this case at all. The purpose of the test was supposed to be to check the case where the expiry is NOT the same, and you can achieve this by setting different TTL and not by weird sleeps.
I guess you can also do *this* check but I would make it a separate test (if it exists at all).

File: test/cql-pytest/test_using_timestamp.py [hunk 20]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
...
+        rewrite = f"INSERT INTO {table} (k, v) VALUES ({k}, {v2}) USING TIMESTAMP {ts} AND TTL {ttl2}"
+        cql.execute(rewrite)
+        select = f"SELECT k, v FROM {table} WHERE k = {k}"
+        res = list(cql.execute(select))
+        assert len(res) == 1, f"Expected a single row, but got {res}"
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:118]: General comment about pytest: `assert len(res) == 1` is enough, you don't need to invent a different failure message. That's one of the most beautiful features of pytest: It instruments "assert()" calls to give you a lot of extra information when it fails. In this case it will tell you exactly which assert call fails (the entire call tree), and tell you what was `len(res)` and even what was `res` when this failed. It's beautiful.

File: test/cql-pytest/test_using_timestamp.py (hunk 11 above)
Comment (nyh) [reply test/cql-pytest/test_using_timestamp.py:124]: Sometimes after you understand an issue you understand that although the customer noticed the problem only after the expiration, if they used "SELECT ttl(...)" they would have seen it immediately after the second write, so you don't need to wait for the expiration. But I guess I'm ok with this if a couple of 1-second sleeps are involved, and not a dozen 4-second sleeps.

File: test/cql-pytest/test_using_timestamp.py [hunk 21]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
...
+    k = unique_key_int()
+    ts = 1000
+    ttl = 10
+    t1 = time.time()
+    values = [{'v':1, 'w':2}, {'v':2, 'w':1}]
+
+    # sync with wall-clock on exact second so that expiration won't cross the whole-second boundary
+    while t1 - int(t1) >= 0.9:
+        time.sleep(1 - (t1 - int(t1)))
+        t1 = time.time()
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:156]: This loop isn't needed here at all. Since you do a sleep(1) below between the first and second writesd, their expiration time will be **at least** one second difference. It doesn't matter if the first write is close to the beginning of a second or its end.

File: test/cql-pytest/test_using_timestamp.py [hunk 22]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
...
+
+    # rewrite values using the same write time and ttl, after waiting a second, so they get different expiration time
+    # if reconciliation is done by value, the result will be a mix of the two writes
+    # while if reconciliation is based first on the expiration time, the second write should prevail.
+    cql.execute(f"INSERT INTO {table} (k, v, w) VALUES ({k}, {values[0]['v']}, {values[0]['w']}) USING TIMESTAMP {ts} AND TTL {ttl}")
+    time.sleep(1)
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:162]: Note: Instead of this sleep(1), you could have also just used a different TTL for the two writes - e.g., 1000 and 2000. They will have very different expiration times (and because you look at the expiration time first, before ttl, it doesn't matter that the ttls differ).

File: test/cql-pytest/test_using_timestamp.py [hunk 23]
```diff
@@ -90,3 +90,79 @@ def test_key_writetime(cql, table1):
...
+    cql.execute(f"INSERT INTO {table} (k, v, w) VALUES ({k}, {values[1]['v']}, {values[1]['w']}) USING TIMESTAMP {ts} AND TTL {ttl}")
+
+    res = list(cql.execute(f"SELECT * FROM {table} WHERE k = {k}"))
+    assert len(res) == 1, f"Expected a single row, but got {res}"
+    assert res[0].k == k and res[0].v == values[1]['v'] and res[0].w == values[1]['w'], \
```
Comment (nyh) [inline test/cql-pytest/test_using_timestamp.py:167]: As before, all these messages are unnecessary, and just hide the fact that pytest is fantastic and an order of magnitude easier to write and debug tests than Boost tests ;-)

**Review by nyh — APPROVED** [review]
Looks good. I still have comments and requests, but their are relatively minor and not critical.

File: docs/cql/dml.rst (hunk 16 above)
Comment (bhalevy) [reply docs/cql/dml.rst:604]: I agree that the text is quite vague but taking it simply, it does imply that the INSERT is considered in whole, rather than selecting which cell will prevail, individually.

We can add a note about that in the update-ordering section.

File: mutation/atomic_cell.cc (hunk 1 above)
Comment (bhalevy) [reply mutation/atomic_cell.cc:79]: @vladzcloudius it doesn't _copy_ the C* logic but it is compatible with it, using a different implementation.
Also, it extend C*'s algorithm as we examine the cell remaining ttl, while C* doesn't so that.  They stop processing at the expiry time and if both cells expire at the same time, their value is compared.

File: mutation/atomic_cell.cc (hunk 15 above)
Comment (bhalevy) [reply mutation/atomic_cell.cc:87]: The comment was taken from them btw (including the shorthand).
I think using our issue number would be better indeed. thanks.
will change.

File: mutation/atomic_cell.cc (hunk 9 above)
Comment (bhalevy) [reply mutation/atomic_cell.cc:93]: The comment does refer to selection by ttl, although it's not obvious.
Having shorter ttl with same expiry means that the derived write time is later.
With that in mind, the cell becomes purgeable gc_grace_seconds after its write time, hence it will survive for longer (as a tombstone).

File: test/boost/mutation_test.cc [hunk 24]
```diff
@@ -687,14 +687,11 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
     auto assert_order = [] (atomic_cell_view first, atomic_cell_view second) {
-        if (compare_atomic_cell_for_merge(first, second) >= 0) {
-            testlog.trace("Expected {} < {}", first, second);
-            abort();
-        }
-        if (compare_atomic_cell_for_merge(second, first) <= 0) {
-            testlog.trace("Expected {} < {}", second, first);
-            abort();
-        }
+        testlog.trace("Expected {} < {}", first, second);
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply test/boost/mutation_test.cc:690]: The trace logs are needed since we can't use `BOOST_REQUIRE_LT(compare_atomic_cell_for_merge(first, second), 0)` because boost doesn't know how to print `std::strong_ordering` and the boost printout on failure is too cryptic for `BOOST_REQUIRE(compare_atomic_cell_for_merge(first, second) < 0)`, making the trace logging useful when trying to figure out what exactly happened (the comparison can fail 2 ways: when comparing left, right and when comparing right, left).

File: test/boost/mutation_test.cc (hunk 13 above)
Comment (bhalevy) [reply test/boost/mutation_test.cc:713]: ok, will clarify message.

File: test/boost/mutation_test.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply test/boost/mutation_test.cc:716]: According to CASSANDRA-14592 they keep expiring cells because they'll become tombstones in the future and then they'll trump live cells.  If they kept the non-expiring cell (as it will survive longer), the expiration would be lost.  Their description of the issue indicates that this inconsistency depends on WHEN the comparison took place, as if it was made early enough, before the cell expired, then the live cell could have been picked (based on its value), but if the comparison took place later on, after the cell expired, then it would be considered as a tombstone and then it would prevail, so preferring expiring cells over live ones is there to be consistent with the rule the prefers tombstones over live cells.

File: test/boost/mutation_test.cc (hunk 14 above)
Comment (bhalevy) [reply test/boost/mutation_test.cc:756]: Maybe we should extend the cql pytest to do that so it can be tested against the reference.
Keep in mind just that the ttl rule is scylla-only, as cassandra stops at the expiry level and if the cells expire at the same time, the one with the higher value (lexicographically) is selected, regardless of their remaining ttl.

File: test/cql-pytest/test_using_timestamp.py (hunk 17 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:94]: I dislike the `#14182` as it implies the scylladb.git repo.
This breaks when this patch is merged into the scylla-enterprise repo.

File: test/cql-pytest/test_using_timestamp.py (hunk 18 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:110]: ttl is quantized in full second resolution.
If the two consecutive inserts cross the full second boundary they will not have the same expiry anymore and this makes the test flaky (I actually reproduced that in debug mode with a millisecond to go before the full-second mark). 10 milliseconds margin proved to be reliable enough on my local machine  in debug mode.

File: test/cql-pytest/test_using_timestamp.py (hunk 20 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:118]: yeah, I'm too familiar with pytest assertion failure messages.
The only problem with them is that they abbreviate long values, while the hand-written error message provides the full `res` list.

File: test/cql-pytest/test_using_timestamp.py (hunk 21 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:156]: Hmm, it makes sense in this test case.

File: test/cql-pytest/test_using_timestamp.py (hunk 22 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:162]: true, will change

File: test/cql-pytest/test_using_timestamp.py (hunk 20 above)
Comment (nyh) [reply test/cql-pytest/test_using_timestamp.py:118]: Almost two years ago, pytest added the "-vv" option (the v option twice) that will avoid this truncation of long values.
Note that even when long lists are involved, pytest many times managest to print the right part. For example, if you do "assert l1 == l2", it doesn't prints specifically which part of l1 and l2 differ, not a hundred items which are equal. In our C++ tests and dtest we jumped through hoops to add these features, but pytest gives it to use for free - you just need to use "assert". This pytest feature is called "assertion rewriting" and is perhaps my favorite part of pytest.

Check out:
https://www.pythoninsight.com/2018/01/assertion-rewriting-in-pytest-part-1/
https://www.pythoninsight.com/2018/02/assertion-rewriting-in-pytest-part-4-the-implementation/

File: test/boost/mutation_test.cc (hunk 14 above)
Comment (nyh) [reply test/boost/mutation_test.cc:756]: So we should ask ourselves why we need a different rule. Although I do agree checking the TTL as a penultimate check does make sense - for the same reason that all the cells in a single write will have the same "ttl", not just same expiration. In any case, it's good to have tests that demonstrate how we differ from Cassandra - I don't think you said what you said here (that we won't be identical to Cassandra in this case) in any of the commit messages, for example.

File: docs/cql/dml.rst (hunk 16 above)
Comment (bhalevy) [reply docs/cql/dml.rst:604]: Also, not that we can't guarantee that "insert atomicity" if neither of the inserts have a TTL.
In that case, the cells values are used for cell selection, independently, and the result could very well be a mixture of the inserts (since a. we compare the cells independently and not the whole row-mutation, and b. we don't keep a write time on non-expiring cells that could use to break the tie more elegantly)

Comment (nyh) [reply docs/cql/dml.rst:604]: Exactly, which is why I'm saying that it's not a great idea to have wording that suggests we can always choose "which insert prevails".

File: test/boost/mutation_test.cc (hunk 14 above)
Comment (bhalevy) [reply test/boost/mutation_test.cc:756]: It was mentioned, though quite timidly in a57c087c897f60c331d8c9c3abcb125aef9250a2
but it can be expressed more visibly and explicitly tested.

Comment (bhalevy) [reply test/boost/mutation_test.cc:756]: In v4, the deviation is documented more clearly in a C++ comment
and a scylla_only pytest tests this

File: test/cql-pytest/test_using_timestamp.py (hunk 19 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py]: Separated into a different test case in v4

File: test/cql-pytest/test_using_timestamp.py (hunk 20 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py]: got rid of the customized error messages in v4

File: test/cql-pytest/test_using_timestamp.py (hunk 23 above)
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py]: cleaned up in v4

**Comment by bhalevy** [comment]
In v4 ([a749f0c](https://github.com/scylladb/scylladb/commit/a749f0c686b55723e0dbc99840d6bba28b6db1b5)):
- atomic_cell: compare_atomic_cell_for_merge: update and add documentation
  - Improved comments
  - Added note about extending C*'s algorithm when comparing ttl
- docs: dml: update tie breaking algorithm description when using timestamp
  - fixed a couple typos
  - added note to "Update ordering" section about atomicity of multi-column upserts (and referral to LWT)
- cql-pytest: test_using_timestamp: add tests for rewrites using same timestamp
  - cleaned up and simplified tests
  - separated out `test_rewrite_different_values_using_same_timestamp`
  - and scylla_only `test_rewrite_different_values_using_same_timestamp_and_expiration`

File: mutation/atomic_cell.cc [hunk 25]
```diff
@@ -66,32 +66,43 @@ atomic_cell::atomic_cell(const abstract_type& type, atomic_cell_view other)
...
-                // prefer the cell that was written later,
-                // so it survives longer after it expires, until purged.
+                // The cell write time is derived by (expiry - ttl).
+                // Prefer the cell that was written later,
+                // so it survives longer after it expires, until purged,
+                // as it become purgeable gc_grace_seconds after it was written.
+                //
+                // Note that this is an extension to Cassandra's algorithm
+                // which stops at the expiration time, and if equal,
+                // move forward to compare the cell values.
```
Comment (nyh) [inline mutation/atomic_cell.cc:100]: Good comment.

File: test/boost/mutation_test.cc (hunk 13 above)
Comment (bhalevy) [reply test/boost/mutation_test.cc:713]: Oops, I changed similar comments but missed this one...
Will fix.

Comment (bhalevy) [reply test/boost/mutation_test.cc]: fixed in next version (f298a9e485)

**Comment by bhalevy** [comment]
In [f298a9e](https://github.com/scylladb/scylladb/commit/f298a9e4854235bd01d1a775a0caf40e029e9df9):
- fixed debug message in `test_cell_ordering`

**Review by nyh — APPROVED** [review]
Benny, let's make a deal - I'll agree to commit this PR and its tests if you agree to fix them if any of them is discovered to be flaky in the future ;-)

**Comment by bhalevy** [comment]
> Benny, let's make a deal - I'll agree to commit this PR and its tests if you agree to fix them if any of them is discovered to be flaky in the future ;-)

It's a deal :)

File: docs/cql/dml.rst [hunk 26]
```diff
@@ -759,6 +759,37 @@ parameters:
...
+
+Dead cells win over live cells; and if both cells are deleted, the one with the later deletion time prevails.
+
+If both cells are alive, their expiration time is examined.
+Expiring cells win over live cells as they will become tombstones at some future date
+and so, going by the rule above, they should be preferred over live cells.
+
+If both cells are expiring, the one with the latest expiration time wins;
+and if they have the same expiration time (in whole second resolution),
+their write time is derived from the expiration time less the remaining time-to-live
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst:780]: sigh, we shouldn't get into the gory technical details, but you're technically correct.  It's the ttl used when applying the cell.

File: docs/cql/dml.rst [hunk 27]
```diff
@@ -759,6 +759,37 @@ parameters:
...
+and the one that was written at a later time prevails.
+
+Finally, if both cells are live and not expiring, or have the same expiration time and remaining time-to-live,
+the cell with the lexicographically bigger value prevails.
+
+Note that when a TTL is used and multiple columns are INSERTed or UPDATEed using the same timestamp,
+SELECTing those columns will return cells picked from only one of those upserts, that has the latest expiration time,
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst:787]: so should we mention this at all?
since we have so many gotchas to this "feature" it's very hard for the application to make use of it anyhow.

File: test/cql-pytest/test_using_timestamp.py [hunk 28]
```diff
@@ -18,10 +18,20 @@
...
 
+# sync with wall-clock on exact second so that expiration won't cross the whole-second boundary
+# 100 milliseconds should be enough to execute 2 inserts at the same second in debug mode
+# sleep until the next whole second mark if there is not enough time left on the clock
+def ensure_sync_with_tick(millis = 100):
+    t = time.time()
+    while t - int(t) >= 1 - millis / 1000:
+        time.sleep(1 - (t - int(t)))
+        t = time.time()
+    return t
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply test/cql-pytest/test_using_timestamp.py:33]: The test I added also tests the "by value" case where there are 2 inserts that expire at the same time.
To achieve that they need to be written at the same whole-second period.  If one is inserted just before the 1-second mark and the other right after it, they won't have the same expiration time anymore.

**Comment by bhalevy** [comment]
In v5 ([cc63305](https://github.com/scylladb/scylladb/commit/cc63305d39597534d337de476464ea0a9bb08e93)):
- updated docs/cql/dml.rst
  - clarified text about expiration time and about atomicity of updates with that respect, @annastuchlik please review docs patch.

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: docs/cql/dml.rst [hunk 29]
```diff
@@ -601,7 +601,7 @@ by the same node are unique. Timestamps assigned at different
 nodes are not guaranteed to be globally unique.
 With a steadily high write rate timestamp collision
 is not unlikely. If it happens, i.e. two ``INSERTS`` have the same
-timestamp, the lexicographically bigger value prevails:
+timestamp, a tie-breaking algorithm determines which of the inserts prevails (see :ref:`update ordering <update-ordering>`).
```
[the remark this answers is not in the document]
Comment (vladzcloudius) [reply docs/cql/dml.rst:604]: System behavior **must** be documented. Period! There is nothing worse and "undefined behavior".
What users should or should not do - leave to users to decide.
If you are personally so against some particular practices you are welcome to write a "Best Practices" article and reference it from the document page mentioned above. 
I suggest we continue this discussion on the PR that adds this article.

File: mutation/atomic_cell.cc [hunk 30]
```diff
@@ -79,23 +79,20 @@ compare_atomic_cell_for_merge(atomic_cell_view left, atomic_cell_view right) {
         return left.is_live() ? std::strong_ordering::less : std::strong_ordering::greater;
     }
     if (left.is_live()) {
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply mutation/atomic_cell.cc:81]: It deviates from the current C* implementation.

File: docs/cql/dml.rst (hunk 29 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst:604]: I can drop the patch that updates the documentation from this series if it's still controversial.
I think it's okay to document our behavior, but we should still be careful to be clear about what we want and can guarantee v.s. what we consider as implementation details that are subject to change, and also timing-sensitive so may produce different result due to server time-skew and/or low resolution of ttl - and so we advise the users not to step into those grey areas.

File: docs/cql/dml.rst [hunk 31]
```diff
@@ -748,8 +748,8 @@ parameters:
   implicitly set by the coordinator by default, when the `USING TIMESTAMP` update parameter is absent.
   Scylla ensures that query timestamps created by the same coordinator node are unique (even across different shards
   on the same node). However, timestamps assigned at different nodes are not guaranteed to be globally unique.
-  Note that with a steadily high write rate, timestamp collision is not unlikely. If it happens, e.g. two INSERTS
-  have the same timestamp, conflicting cell values are compared and the cells with the lexicographically bigger value prevail.
+  Note that with a steadily high write rate, timestamp collision is not unlikely. If it happens, e.g. two INSERTS or UPDATES
+  have the same timestamp, a tie-breaking algorithm determines which of the upserts prevails (see :ref:`update ordering <update-ordering>` for more information):
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst:752]: Good point.  I'll phrase it closer to the original phrase that referred to the individual cells as the unit of comparison.

File: mutation/atomic_cell.cc (hunk 30 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply mutation/atomic_cell.cc:85]: commitlog message improved in v6

File: docs/cql/dml.rst (hunk 29 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst]: Added disclaimer in v6

File: docs/cql/dml.rst (hunk 31 above)
[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst]: improved in v6

File: docs/cql/dml.rst (hunk 29 above)
[the remark this answers is not in the document]
Comment (tgrabiec) [reply docs/cql/dml.rst]: What about 

> What if someone relied on "the lexicographically bigger value prevails"?

The old behavior was documented, so a user could have "decided" to rely on it.

[the remark this answers is not in the document]
Comment (bhalevy) [reply docs/cql/dml.rst]: I see your point, but what exactly do you think we should do?

File: mutation/mutation_partition.cc [hunk 32]
```diff
@@ -1108,20 +1108,34 @@ operator<<(std::ostream& os, const mutation_partition::printer& p) {
 constexpr gc_clock::duration row_marker::no_ttl;
 constexpr gc_clock::duration row_marker::dead;
 
+// Note: the ordering algorithm for rows is the same as for cells,
+// except that there is no cell value to break a tie in case all other attributes are equal.
+// See compare_atomic_cell_for_merge.
```
[the remark this answers is not in the document]
Comment (bhalevy) [reply mutation/mutation_partition.cc:1113]: yeah, let's leave it as a possible follow up

File: docs/cql/dml.rst (hunk 29 above)
[the remark this answers is not in the document]
Comment (nyh) [reply docs/cql/dml.rst]: I agree with @tgrabiec, I think we can document that if a user does two writes with the same timestamp, the result MAY be a mixed version of the two writes - without explain exactly which extenuating circumstances (such as TTL and conflicting writes more than one second apart) may ensure that the conflict will result in one of the two writes but not n a mix.

I'd love to have a developer-oriented documentation (in docs/dev/) for the conflict resolution details, but I don't think users should make use of these details (and if they did, now with this PR, they will be frustrated because the details changed).

File: docs/cql/dml.rst [hunk 33]
```diff
@@ -759,6 +759,51 @@ parameters:
...
+
+The fundamental rule for ordering multiple inserts or updates to a cell
+is that the cell with the highest timestamp wins.
+
+Otherwise, if cells have the same timestamp, Scylla implements the following
+tie-breaking algorithm.
+
+DISCLAIMER: The algorithm may be subject to change.
+The actual results depend on real-time differences between the cluster servers'
+clocks and is limited by the 1-second resolution of the TTL value.
```
Comment (annastuchlik) [inline docs/cql/dml.rst:775]:
```suggestion
clocks and are limited by the 1-second resolution of the TTL value.
```

File: docs/cql/dml.rst [hunk 34]
```diff
@@ -759,6 +759,51 @@ parameters:
...
+
+The first tie-breaking rule when two cells have the same write timestamp is that
+dead cells win over live cells; and if both cells are deleted, the one with the later deletion time prevails.
+
+If both cells are alive, their expiration time is examined.
+Cells that are written with a non-zero TTL (either implicit, as determined by
+the table's default TTL, or explicit, ``USING TTL``) are due to expire
+TTL seconds after the time they were written (as determined by the coordinator,
+and rounded to 1 second resolution). That time is the cell's expiration time.
+When cells expire they become tombstones, shadowing any data written with a write timestamp
```
Comment (annastuchlik) [inline docs/cql/dml.rst:789]:
```suggestion
When cells expire, they become tombstones, shadowing any data written with a write timestamp
```

File: docs/cql/dml.rst [hunk 35]
```diff
@@ -759,6 +759,51 @@ parameters:
...
+and if they have the same expiration time (in whole second resolution),
+their write time is derived from the expiration time less the original time-to-live value
+and the one that was written at a later time prevails.
+
+Finally, if both cells are live and have no expiration, or have the same expiration time and time-to-live,
+the cell with the lexicographically bigger value prevails.
+
+Note that when multiple columns are INSERTed or UPDATEed using the same timestamp,
+SELECTing those columns might return a result that mixes cells from either upsert
+if both upserts have no expiration time, or their expiration time and ttl are the
```
Comment (annastuchlik) [inline docs/cql/dml.rst:803]:
```suggestion
This may happen when both upserts have no expiration time or their expiration time and TTL are the
```

File: docs/cql/dml.rst [hunk 36]
```diff
@@ -759,6 +759,51 @@ parameters:
...
+same, in whole second resolution; as cell selection would be based on the cell values
```
Comment (annastuchlik) [inline docs/cql/dml.rst:804]:
```suggestion
same (in whole second resolution). In such a case, cell selection will be based on the cell values
```

File: mutation/mutation_partition.cc [hunk 37]
```diff
@@ -1108,20 +1108,34 @@ operator<<(std::ostream& os, const mutation_partition::printer& p) {
...
-            return left.expiry() < right.expiry() ? -1 : 1;
+        // If both are expiring, choose the cell with the latest expiry or derived write time.
+        if (left.is_expiring()) {
+            if (left.expiry() != right.expiry()) {
+                return left.expiry() < right.expiry() ? -1 : 1;
+            } else if (left.ttl() != right.ttl()) {
+                // The cell write time is derived by (expiry - ttl).
+                // Prefer row that was written later (and has a smaller ttl).
+                return left.ttl() < right.ttl() ? 1 : -1;
+            }
```
Comment (raphaelsc) [inline mutation/mutation_partition.cc:1138]: @bhalevy does this merit a backport?

**Comment by bhalevy** [comment]
In v7 ([9f4e84c](https://github.com/scylladb/scylladb/commit/9f4e84c67b80ef072e678797c8e89e7477ef5d5b)):
- updated dml.doc based on the review comments and https://github.com/scylladb/scylladb/pull/14183#issuecomment-1589293308
 - added docs/dev/timestamp-conflict-resolution.md to document the details of the algorithm
 - dml test deals with the more generic topoics and explain the higher-level properties of the conflict resolution algorithm
 - s/tie-breaking/conflict resolution/ when it is referenced in other sections.

@avikivity one more issue I discussed with @tgrabiec is the roll-out of the change.
Ideally, we may want to add a config option (false for existing clusters and true for new ones)
for backward compatibility, plus cluster feature to enable the new algorithm on all nodes in the cluster only after rolling upgrade completes, since the conflict resolution should be consistent on all nodes.
OTOH, this case is so rare I'm not sure it merits the extra safety and the alight performance penalty it might carry (that is very small but happens on frequently-called code)

File: docs/cql/dml.rst [hunk 38]
```diff
@@ -759,6 +759,57 @@ parameters:
...
+other attributes related to its expiration when it has a non-zero time-to-live (``TTL``),
+and the cell value.
+
+The fundamental rule for ordering cells that insert, update, or delete data in a given row and column
+is that the cell with the highest timestamp wins.
+
+However, it is possible that multiple such cells will carry the same ``TIMESTAMP``.
+There could be several reasons for ``TIMESTAMP`` collision:
+
+1. Benign collision can be caused by "replay" of a mutation, e.g. due to client retry, or due to internal processes.
```
Comment (annastuchlik) [inline docs/cql/dml.rst:780]:
```suggestion
* Benign collision can be caused by "replay" of a mutation, e.g., due to client retry, or due to internal processes.
```

File: docs/cql/dml.rst [hunk 39]
```diff
@@ -759,6 +759,57 @@ parameters:
...
+In such case the cells are equivalent and any of them can be selected, arbitrarily.
```
Comment (annastuchlik) [inline docs/cql/dml.rst:781]:
```suggestion
In such cases, the cells are equivalent, and any of them can be selected arbitrarily.
```

File: docs/cql/dml.rst [hunk 40]
```diff
@@ -759,6 +759,57 @@ parameters:
...
+
+2. ``TIMESTAMP`` collisions might be normally caused by parallel queries that are served
```
Comment (annastuchlik) [inline docs/cql/dml.rst:783]:
```suggestion
* ``TIMESTAMP`` collisions might be normally caused by parallel queries that are served
```

File: docs/cql/dml.rst [hunk 41]
```diff
@@ -759,6 +759,57 @@ parameters:
...
+by different coordinator nodes. The coordinators might calculate the same write ``TIMESTAMP``
+based on their local time in microseconds.
+
+1. Collisions might also happen with user-provided timestamps, if the application does not guarantee
```
Comment (annastuchlik) [inline docs/cql/dml.rst:787]:
```suggestion
* Collisions might also happen with user-provided timestamps if the application does not guarantee
```

**Review by annastuchlik — APPROVED** [review]

**Comment by bhalevy** [comment]
In v8 ([6dd2e15](https://github.com/scylladb/scylladb/commit/6dd2e155356269af9c22d1d9acb7fbb6b2ecbf5f)):
- Fixed @annastuchlik doc review comments (thanks for the prompt review!)

File: docs/cql/dml.rst (hunk 38 above)
Comment (bhalevy) [reply docs/cql/dml.rst]: fixed in v8

File: docs/cql/dml.rst (hunk 39 above)
Comment (bhalevy) [reply docs/cql/dml.rst]: fixed in v8

File: docs/cql/dml.rst (hunk 40 above)
Comment (bhalevy) [reply docs/cql/dml.rst]: fixed in v8

File: docs/cql/dml.rst (hunk 41 above)
Comment (bhalevy) [reply docs/cql/dml.rst]: fixed in v8

**Comment by nyh** [comment]
> CI state **`ABORTED`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1821/

It seems that the Alternator test hung, but I can't figure out where I got completely lost in the log files which keep moving around :-( I'll restart the CI.

@tgrabiec you have a "request changes" mark so please re-review this version. @annastuchlik maybe you also want to review, you had some comments on the last version.

File: test/boost/mutation_test.cc [hunk 42]
```diff
@@ -703,68 +700,75 @@ SEASTAR_TEST_CASE(test_cell_ordering) {
...
         atomic_cell::make_live(*bytes_type, 0, bytes("value2")));
 
-    // Live cells are ordered first by timestamp...
+    testlog.debug("Live cells are ordered first by timestamp...");
     assert_order(
         atomic_cell::make_live(*bytes_type, 0, bytes("value2")),
         atomic_cell::make_live(*bytes_type, 1, bytes("value1")));
 
-    // ..then by value
+    testlog.debug("...then by value");
```
Comment (avikivity) [inline test/boost/mutation_test.cc]: Will this cause a huge expansion in the logs, or is the default level for tests INFO?

(or the repetition count is low enough)?

File: mutation/mutation_partition.cc (hunk 37 above)
Comment (avikivity) [inline mutation/mutation_partition.cc:1138]: This is a copy of the atomic_cell algorithm, yes? We should consolidate it into a template (but not in this series).

Comment (avikivity) [reply mutation/mutation_partition.cc:1138]: Also change to std::strong_ordering.

**Review by avikivity — APPROVED** [review]
Looks good, asked a minor question earlier.

@tgrabiec should have the final say + merge.

File: test/boost/mutation_test.cc (hunk 42 above)
Comment (bhalevy) [reply test/boost/mutation_test.cc]: The default level is INFO and the repetition count is low (single digit)

File: mutation/mutation_partition.cc (hunk 37 above)
Comment (bhalevy) [reply mutation/mutation_partition.cc:1138]: a template or maybe a function that gets the individual attributes and a value reference that can be set to zero by row markers.

Comment (raphaelsc) [reply mutation/mutation_partition.cc:1138]: the reason I asked this is because  I didn't see an issue opened specifically for row marker missing the logic, but perhaps there's no need for one at this patch will be included in the backport anyway.

Comment (avikivity) [reply mutation/mutation_partition.cc:1138]: Yes

**Comment by bhalevy** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1906/

That weird.  The failure, https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1906/artifact/testlog/x86_64/release/cql-pytest.test_using_timestamp.1.log:
```
    def test_key_writetime(cql, table1):
>       with pytest.raises(InvalidRequest, match='PRIMARY KEY part k'):
E       AssertionError: Regex pattern 'PRIMARY KEY part k' does not match 'Error from server: code=2200 [Invalid query] message="WRITETIME is not legal on partition key component k"'.
```

seems related to b7bbcdd178088c9fdfd217e9a419821d3a87c345 which isn't in the pushed branch.

I don't understand how test-timestamp.py passes in master after e1513f11991c2cd8b378132419472525fdcbf24e

**Comment by bhalevy** [comment]
@nyh I tried running ./test.py --mode=dev cql-pytest in master and it didn't run `test-timestamp.py` at all.
I suspect that pytest ignores it since it doesn't use the `test_` naming convention.
(and `./test.py --mode=$mode test-timestamp` fails with: `Test test-timestamp not found`)

With `git mv test/cql-pytest/test{-,_}timestamp.py` it is found and fails as in the above CI.
I'll submit a PR to fix and rename the test.

**Comment by nyh** [comment]
Not running one of the tesfs is a test.py bug, that thinks it knows better than pytest what to run. If you run test/cql-pytest/run, it will run pytest and it will also run this test.
In any case, last week this test file was renamed (from dash to underscore) so you won't have this problem any more.

**Comment by nyh** [comment]
Not running one of the tesfs is a test.py bug, that thinks it knows better than pytest what to run. If you run test/cql-pytest/run, it will run pytest and it will also run this test.
In any case, last week this test file was renamed (from dash to underscore) so you won't have this problem any more.

To clarify:
1. pytest looks at files test*, not test_* as test files. Using the pattern test_* is a test.py bug.
2. This test file was already reamed when we noticed its odd name last week, you don't need to send another patch to do that.

**Comment by bhalevy** [comment]
> 2. This test file was already reamed when we noticed its odd name last week, you don't need to send another patch to do that.

@nyh I don't see such PR nor a patch on the mailing list.
Care to provide a reference so I know when to rebase and on what?

**Comment by bhalevy** [comment]
> @bhalevy this is so funny, we managed to confuse each other. It was **you**, who already added a patch in **this** PR, to rename test-timestamp.py to test_using_timestamp.py. It wasn't another PR - it was this one :-) So you don't need to submit another PR to rename this patch, you already did, this one...
> 
> Of course, if you want you can split out this rename from this PR and send it as a **separate** PR. Maybe that's what you meant you wanted to do, and I just misunderstood you?

Yes, I want to separate it since it's fixing a preexisting issue and would have different backport requirements.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/pull/14293

**Review by tgrabiec — APPROVED** [review]

**Comment by bhalevy** [comment]
[26ff8f7](https://github.com/scylladb/scylladb/commit/26ff8f7bf78a75f7e513e701e5f945ed6b311b9d): fixed warnings in docs/cql/dml.rst regarding empty lines in bullet-points list

**Comment by DoronArazii** [comment]
@avikivity please merge
