### PR TITLE
raft: verify RPC destination ID

### LINKED ISSUE #12179: raft: verify destination ID when receiving RPCs
A node may receive Raft RPCs not intended for that node, e.g. when replacing a node with the same IP.

All Raft verbs already include `dst_id`, the ID of the destination server:
```
verb [[with_client_info, with_timeout]] raft_send_snapshot (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::install_snapshot) -> raft::snapshot_reply;
verb [[with_client_info, with_timeout, one_way]] raft_append_entries (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::append_request);
verb [[with_client_info, with_timeout, one_way]] raft_append_entries_reply (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::append_reply);
verb [[with_client_info, with_timeout, one_way]] raft_vote_request (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::vote_request);
verb [[with_client_info, with_timeout, one_way]] raft_vote_reply (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::vote_reply);
verb [[with_client_info, with_timeout, one_way]] raft_timeout_now (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::timeout_now);
verb [[with_client_info, with_timeout, one_way]] raft_read_quorum (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::read_quorum);
verb [[with_client_info, with_timeout, one_way]] raft_read_quorum_reply (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::read_quorum_reply);
verb [[with_client_info, with_timeout]] raft_execute_read_barrier_on_leader (raft::group_id, raft::server_id from_id, raft::server_id dst_id) -> raft::read_barrier_reply;
verb [[with_client_info, with_timeout]] raft_add_entry (raft::group_id, raft::server_id from_id, raft::server_id dst_id, raft::command cmd) -> raft::add_entry_reply;
verb [[with_client_info, with_timeout]] raft_modify_config (raft::group_id gid, raft::server_id from_id, raft::server_id dst_id, std::vector<raft::config_member> add, std::vector<raft::server_id> del) -> raft::add_entry_reply;
```

but we don't use the `dst_id` for anything:
```cpp
    auto handle_raft_rpc = [this] (
            const rpc::client_info& cinfo,
            const raft::group_id& gid, raft::server_id from, raft::server_id dst, auto handler) {
        return container().invoke_on(shard_for_group(gid),
                [addr = netw::messaging_service::get_source(cinfo).addr, from, dst, gid, handler] (raft_group_registry& self) mutable {
            // Update the address mappings for the rpc module
            // in case the sender is encountered for the first time
            auto& rpc = self.get_rpc(gid);
            // The address learnt from a probably unknown server should
            // eventually expire. Do not use it to update
            // a previously learned gossiper address: otherwise an RPC from
            // a node outside of the config could permanently
            // change the address map of a healthy cluster.
            self._address_map.opt_add_entry(from, std::move(addr));
            // Execute the actual message handling code
            return handler(rpc);
        });
    };
```

we should verify that `dst_id` matches our ID and reject the verb if it doesn't. Not sure if we should do that by an exception or a special response (for two-way RPCs).

I do this in https://github.com/scylladb/scylladb/pull/12107 for the direct failure detector verb.
Note: in the above PR I make the Raft ID of the local server available early in `raft_group_registry` so the check can be easily implemented in `handle_raft_rpc`.

Example scenario where not verifying `dst_id` could cause problems:
Suppose you have a leader A and a dead node B. C starts replacing B with the same IP. A is now sending `append_entries` messages (and others) intended for B to C, because they have the same IP.
C is now receiving `append_entries` for B and for itself. Weird.

cc @kostja  @gleb-cloudius

### PR DESCRIPTION
**Pull request by margdoc**
All Raft verbs include `dst_id`, the ID of the destination server, but it isn't checked. `append_entries` will work even if it arrives at completely the wrong server (but in the same group). It can cause problems, e.g. in the scenario of replacing a dead node.

This commit adds verifying if `dst_id` matches the server's ID and if it doesn't, the Raft verb is rejected.

Closes #12179

### Testing
Testcase and scylla's configuration: https://github.com/margdoc/scylla/commit/57d3ef14d848840b93346fdb9f86c7605d53bdcd

It artificially lengthens the duration of replacing the old node. It increases the chance of getting the RPC command sent to a replaced node, by the new node.

In the logs of the node that replaced the old one, we can see logs in the form:
```
DEBUG <time> [shard 0] raft_group_registry - Got message for server <dst_id>, but my id is <my_id>
```
It indicates that the Raft verb with the wrong `dst_id` was rejected.

This test isn't included in the pr because it doesn't catch any specific error.

### CODE REVIEW

File: service/raft/raft_group_registry.cc [hunk 1]
```diff
@@ -151,6 +151,11 @@ void raft_group_registry::init_rpc_verbs() {
     auto handle_one_way_rpc = [this] (
             const rpc::client_info& cinfo,
             const raft::group_id& gid, raft::server_id from, raft::server_id dst, auto handler) {
+        if (*_my_id != dst) {
```
Comment (kbr-scylla) [inline service/raft/raft_group_registry.cc:154]: Please replace `*_my_id` with `get_my_raft_id()`, which asserts that `_my_id` is initialized.
Same below.

**Comment by kbr-scylla** [comment]
> Raft rpc destination

Please update the title to actually explain what's done using imperative form, like:
"raft: verify RPC destination ID"

**Comment by avikivity** [comment]
Please use meaningful English sentences for the subject. "Raft rpc destination" doesn't give me an idea about what the series is trying to do.

**Comment by margdoc** [comment]
v2
* rebased to master
* used metaprogramming
* replaced `*_my_id` with `get_my_raft_id()`

File: service/raft/raft_group_registry.cc [hunk 2]
```diff
@@ -148,7 +148,27 @@ raft_group_registry::raft_group_registry(bool is_enabled, raft_address_map& addr
 }
 
 void raft_group_registry::init_rpc_verbs() {
-    auto handle_raft_rpc = [this] (
+    auto handle_one_way_rpc = [this] (
+            const rpc::client_info& cinfo,
+            const raft::group_id& gid, raft::server_id from, raft::server_id dst, auto handler) {
+        return container().invoke_on(shard_for_group(gid),
```
[the remark this answers is not in the document]
Comment (margdoc) [reply service/raft/raft_group_registry.cc]: Changed.

File: service/raft/raft_group_registry.cc (hunk 1 above)
Comment (margdoc) [reply service/raft/raft_group_registry.cc]: Replaced.

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
@gleb-cloudius please re-review

**Review by gleb-cloudius — APPROVED** [review]
