### PR TITLE
alternator: allow empty tag value

### LINKED ISSUE #16904: Alternator: an empty tag value should be allowed
In DynamoDB, it is allowed to set an **empty** string value for a tag on a table. Alternator incorrectly forbids it - it says:

> An error occurred (ValidationException) when calling the TagResource operation: The Tag Value provided is invalid string

The empty string should not be considered invalid - it's a perfectly valid string. I even wanted to use it in https://github.com/scylladb/scylladb/pull/16900 to disable tablets.

The following test demonstrates that an empty tag value is supported in DynamoDB, but rejected in Alternator:

```python

# An empty string is allowed as a tag's value
def test_empty_tag_value(dynamodb, test_table):
    client = dynamodb.meta.client
    arn = client.describe_table(TableName=test_table.name)['Table']['TableArn']
    client.tag_resource(ResourceArn=arn, Tags=[{'Key': 'dog', 'Value': ''}])
    # Verify that the tag with the empty value was correctly saved:
    tags = client.list_tags_of_resource(ResourceArn=arn)['Tags']
    assert {'Key': 'dog', 'Value': ''} in tags
    # Clean up the tag we just added
    client.untag_resource(ResourceArn=arn, TagKeys=['dog'])
```

### PR DESCRIPTION
**Pull request by nyh**
Alternator incorrectly refuses an empty tag value for TagResource, but DynamoDB does allow this case and it's useful (note that an empty tag key is rightly forbidden). So this short series fixes this case, and adds additional tests for TagResource which covers this case and other cases we forgot to cover in tests.

Fixes #16904.

### CODE REVIEW

File: alternator/executor.cc [hunk 1]
```diff
@@ -763,15 +763,33 @@ enum class update_tags_action { add_tags, delete_tags };
...
+                throw api_error::validation("string Key and Value required");
+            }
+            auto tag_key = rjson::to_string_view(*key);
+            auto tag_value = rjson::to_string_view(*value);
+
+            if (tag_key.empty()) {
+                throw api_error::validation("A tag Key cannot be empty");
+            }
+            if (tag_key.size() > 128) {
+                throw api_error::validation("A tag Key is limited to 128 letters");
```
Comment (ptrsmrn) [inline alternator/executor.cc:781]:
```suggestion
                throw api_error::validation("A tag Key is limited to 128 characters");
```

File: alternator/executor.cc [hunk 2]
```diff
@@ -763,15 +763,33 @@ enum class update_tags_action { add_tags, delete_tags };
...
+            }
+            if (!validate_legal_tag_chars(tag_key)) {
+                throw api_error::validation("A tag Key can only contain letters, spaces, and [+-=._:/]");
+            }
+            // Note tag values are limited similarly to tag keys, but have a
+            // longer length limit, and *can* be empty.
+            if (tag_value.size() > 256) {
+                throw api_error::validation("A tag Value is limited to 256 letters");
```
Comment (ptrsmrn) [inline alternator/executor.cc:789]:
```suggestion
                throw api_error::validation("A tag Value is limited to 256 characters");
```

File: alternator/executor.cc (hunk 1 above)
Comment (nyh) [reply alternator/executor.cc:781]: I really meant "letters" when I wrote this because most non-letters aren't allowed (except a few select ones,  see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TaggingRestrictions.html). But perhaps because a few non-letters are indeed allowed, the word characters is even better... Maybe you're right.

Comment (ptrsmrn) [reply alternator/executor.cc:781]: 2 lines below we're calling a method named `validate_legal_tag_chars`, so it's either letters or chars ;)

File: test/alternator/test_tag.py [hunk 3]
```diff
@@ -342,3 +342,103 @@ def tag_loop(tag, count):
...
+    client = dynamodb.meta.client
+    arn = client.describe_table(TableName=test_table.name)['Table']['TableArn']
+    value = 'x'*257
+    with pytest.raises(ClientError, match='ValidationException'):
+        client.tag_resource(ResourceArn=arn, Tags=[{'Key': 'dog', 'Value': value}])
+
+# According to the DynamoDB documentation, only letters, whitespace, numbers,
+# and the characters [+-=._:/] are allowed in both tag keys or values.
+# Let's check that other non-letter characters are not allowed in either
+# key or value.
```
Comment (nuivall) [inline test/alternator/test_tag.py:416]: this `or value` is refering to test below, perhaps could be merged to one test, with 2 for loops? To spare extra boilerplate and describe calls.

File: alternator/executor.cc [hunk 4]
```diff
@@ -763,15 +763,33 @@ enum class update_tags_action { add_tags, delete_tags };
...
-                throw api_error::validation("The Tag Key provided is invalid string");
+            if (!it->IsObject()) {
+                throw api_error::validation("invalid tag object");
             }
-            auto tag_value = rjson::to_string_view(value);
-            if (tag_value.empty() || tag_value.size() > 256 || !validate_legal_tag_chars(tag_value)) {
-                throw api_error::validation("The Tag Value provided is invalid string");
+            const rjson::value* key = rjson::find(*it, "Key");
+            const rjson::value* value = rjson::find(*it, "Value");
+            if (!key || !key->IsString() || !value || !value->IsString()) {
```
Comment (nuivall) [inline alternator/executor.cc:771]: are you sure that missing value field doesn't fallback to empty string?

File: test/alternator/test_tag.py (hunk 3 above)
Comment (nyh) [reply test/alternator/test_tag.py:416]: I deliberately did this as two separate tests because in theory, it can fail separately. In fact, I wrote these tests to explore the situation, because after finding that the rules for empty key and value are not the same (contrary to what I guess Piotr Sarna believed when he wrote this code), I started to worry if we're not missing other differences. I didn't know when I wrote these two tests if both will pass, or just one, and so on.

But I guess you're right that now that I know that both key and value should follow the **same** rules, it makes sense to test these rules in one test - so we don't accidentally test them differently. So I'll merge the two tests.

File: alternator/executor.cc (hunk 1 above)
Comment (nuivall) [reply alternator/executor.cc:781]: I am not sure if number is a letter (probably not). So characters seem to fit better

File: alternator/executor.cc [hunk 5]
```diff
@@ -763,15 +763,33 @@ enum class update_tags_action { add_tags, delete_tags };
...
+            }
+            if (!validate_legal_tag_chars(tag_key)) {
+                throw api_error::validation("A tag Key can only contain letters, spaces, and [+-=._:/]");
+            }
+            // Note tag values are limited similarly to tag keys, but have a
+            // longer length limit, and *can* be empty.
+            if (tag_value.size() > 256) {
+                throw api_error::validation("A tag Value is limited to 256 letters");
+            }
+            if (!validate_legal_tag_chars(tag_value)) {
```
Comment (nuivall) [inline alternator/executor.cc:791]: perhaps validate_legal_tag_chars can throw inside to not duplicate error messages.

not a must as it's already duplicated on master

**Review by nuivall — APPROVED** [review]
LGTM

File: alternator/executor.cc (hunk 1 above)
Comment (nyh) [reply alternator/executor.cc:781]: Switched to "characters", as you suggested.

**Comment by nuivall** [comment]
Cheers for the extra tests!

File: alternator/executor.cc (hunk 2 above)
Comment (nyh) [reply alternator/executor.cc:789]: Switched to "characters", as you suggested.

File: alternator/executor.cc (hunk 4 above)
Comment (nyh) [reply alternator/executor.cc:771]: Do you mean that a missing value field should be allowed, and mean an empty value?
I'm guessing no, a Value is required, but you're right - I didn't actually test this. I'll add a test.

File: alternator/executor.cc (hunk 5 above)
Comment (nyh) [reply alternator/executor.cc:791]: Yes, it's pre-existing code (by Piotr Sarna) and anyway, the message is only duplicated twice and is slightly different (one refers to a key, the other to a value), so we wouldn't be saving much duplication anyway.

File: alternator/executor.cc (hunk 4 above)
Comment (nyh) [reply alternator/executor.cc:771]: My test confirms that DynamoDB doesn't allow a missing Value (it's not the same as an empty value) -
```
An error occurred (ValidationException) when calling the TagResource operation: 1 validation error detected: Value null at 'tags.1.member.value' failed to satisfy constraint: Member must not be null
```
But the same test also shows that Alternator produces a really ugly message in this case:
```
An error occurred (ValidationException) when calling the TagResource operation: JSON error: condition not met: false
```

So in the next version I'll push shortly, I'll include this additional test, and improve the message in this case.

Comment (nuivall) [reply alternator/executor.cc:771]: They mention this in docs as allowing NULL, so technically in json it'd mean missing ("Value") key, because empty string is different than NULL. But dunno how it's handled in reality.

Comment (nuivall) [reply alternator/executor.cc:771]: ok, thanks for testing this

Comment (nuivall) [reply alternator/executor.cc:771]: I forgot, there is another way to represent null - using keyword, as per json spec: `{"Value": null}`

**Comment by denesb** [comment]
@nyh I think you forgot to force-push.

File: alternator/executor.cc (hunk 4 above)
Comment (nyh) [reply alternator/executor.cc:771]: I mis-ran the test - the ugly error message happened on Alternator **without** my patch. After my patch it becomes
```
string Key and Value required
```
So good. And I'll include the new test in my next push.

**Comment by nyh** [comment]
> @nyh I think you forgot to force-push.

Actually, I was still working on the reviewers' comments :-) Now I finished doing them and forced-pushed the result.

File: alternator/executor.cc (hunk 4 above)
Comment (nyh) [reply alternator/executor.cc:771]: > I forgot, there is another way to represent null - using keyword, as per json spec: `{"Value": null}`

I didn't test "null"... I could but I have other things to do ;-) The empty string case is actually useful (I really tried to do it for the initial_tablets parameter, and was surprised when it didn't work). Sending null or 7 or a hash table instead of a string really looks like a user mistake.
