### PR TITLE
cql3: add option to not unify bind variables with the same name

### LINKED ISSUE #15559: Cassandra-incompatible behavior of prepared statement with same-named bind markers
When a query like `SELECT * FROM {table1} WHERE p=:x AND c=:x'` has two bind markers **with the same name**, here `:x`, Cassandra behaves as follows when executing the prepared statement:

1. When a bound value is passed in the request **with a name** (CQL protocol flag 0x40), e.g., x=3, this value is assigned to both instances of `:x` in the request. EDIT: As explained below in a comment https://github.com/scylladb/scylladb/issues/15559#issuecomment-1737217073, the driver doesn't actually uses the protocol flag 0x40 in this case - it actually passes the server just the values.
2. When a bound value is passed in the request **without a name** (CQL protocol flag 0x01), e.g., 3, this value is assigned just to the first bind marker, and the second one remains unset. The user needs to pass two values, e.g., (3,3), to fill both bind markers. Even passing (3,4) works, and the two bind markers that had the same name get different values! This is not different from the case of a query which uses the bind marker "?" multiple times, and execute can bind each one a different value.

Today, Scylla behaves differently. Point 1 above is the same, but point 2 behaves differently: Passing just 3 will fill both bind markers ":x". Passing (3,3) is considered an error _"Too many arguments provided to bind() (got 2, expected 1)"_.

In pull request #15526, in the context of token calculation, @cvybhu declared Cassandra's behavior in this case a bug, and added a "scylla_only" tag (should have been "cassandra_bug"...) to two tests that were vulnerable to this incompatibility:
* `test_prepare.py`::`test_single_pk_indexes_duplicate_named_variables`
* `test_prepare.py`::`test_composite_pk_indexes_duplicate_named_variables`

The reason why I created this issue is to rethink this declaration, and perhaps consider Scylla's behavior - not Cassandra's - to be buggy. If we decide to leave the current Cassandra-incompatible behavior, we should document it.

Here is a test reproducing this issue, passing on Cassandra and failing (in multiple places) on Scylla:
```python
def test_duplicate_named_bind_marker_prepared(cql, table1):
    x = unique_key_int()
    cql.execute(f'INSERT INTO {table1} (p,c) VALUES ({x},{x})')
    cql.execute(f'INSERT INTO {table1} (p,c) VALUES ({x},{x+1})')
    stmt = cql.prepare(f'SELECT * FROM {table1} WHERE p=:x AND c=:x')
    # If EXECUTE is passed a bound value with a name "x", both bind markers
    # named "x" are assigned, and the query works:
    assert [(1,1)] == list(cql.execute(stmt, {'x': x}))
    # If EXECUTE is passed unnamed bound values, they go to the bind
    # markers no matter what their name is - using ":x" twice in the query
    # has the same effect as using "?" twice - you still need to pass two
    # bound values.
    # The following currently fails on Scylla - the driver complains that
    # "Too many arguments provided to bind() (got 2, expected 1)", because
    # Scylla told it there is just one bind variable in the query.
    assert [(1,1)] == list(cql.execute(stmt, (x,x)))
    # Passing one unnamed value sets just the first :x and leaves the
    # second one unset, resulting in an invalid query:
    with pytest.raises(InvalidRequest, match='Invalid unset value for column c'):
        assert [(1,1)] == list(cql.execute(stmt, (x,)))
    # Passing unnamed values one can pass two different values even if the
    # query's bind markers have the same name :x - exactly like two different
    # "?" can also be bound to different values:
    y = unique_key_int()
    cql.execute(f'INSERT INTO {table1} (p,c) VALUES ({y},{y+1})')
    assert [(y,y+1)] == list(cql.execute(stmt, (y,y+1)))
```

### PR DESCRIPTION
**Pull request by avikivity**
Bind variables in CQL have two formats: positional (`?`) where a variable is referred to by its relative position in the statement, and named (`:var`), where the user is expected to supply a name->value mapping.

In 19a6e69001f26 we identified the case where a named bind variable appears twice in a query, and collapsed it to a single entry in the statement metadata. Without this, a driver using the named variable syntax cannot disambiguate which variable is referred to.

However, it turns out that users can use the positional call form even with the named variable syntax, by using the positional API of the driver. To support this use case, we add a configuration variable to disable the same-variable detection.

Because the detection has to happen when the entire statement is visible, we have to supply the configuration to the parser. We call it the `dialect` and pass it from all callers. The alternative would be to add a pre-prepare call similar to fill_prepare_context that rewrites all expressions in a statement to deduplicate variables.

A unit test is added.

Fixes #15559

This may be useful to users transitioning from Cassandra, so merits a backport.

### CODE REVIEW

**Comment by nyh** [comment]
dtest above had a "collection failure", I don't know what it means. @yaronkaikov @fruch maybe you knows what it means?

File: cql3/dialect.hh [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// Copyright (C) 2024-present ScyllaDB
+// SPDX-License-Identifier: AGPL-3.0-or-later
+
+#pragma once
+
+namespace cql3 {
+
+struct dialect {
+    bool duplicate_bind_variable_names_refer_to_same_variable = true;  // if :a is found twice in a query, the two references are to the same variable
```
Comment (nyh) [inline cql3/dialect.hh:9]: Perhaps it will be useful to refer to the issue number, or test, or something, that expands on this difference. And/or mention that "false" is the behavior of Scylla 5.0 (IIRC) and earlier, and all Cassandra, and "true" is Scylla's default since 5.1 (IIRC).
I think without an expanded comment, a year (or a week ;-)) from now, nobody will remember why this flag exists. I guess "git blame" could help, but as the code moves around it becomes harder to follow the (hi)story of this flag.

**Comment by avikivity** [comment]
> You didn't explicitly say this in the commit message, but if I understand correctly, the new config parameter defaults to leaving the existing behavior - **not** returning to the behavior of Scylla 5.0, Scylla 2021.1 or Cassandra behavior (all these behaved the same). Right?

Yes

> 
> This difference, and flag, should be perhaps documented in docs/cql/cql-extensions.md?

Yes

> 
> Finally, regarding a test - #15559 listed three tests that we already have which demonstrate this issue:
> 
> * `test_prepare.py`::`test_single_pk_indexes_duplicate_named_variables`
> * `test_prepare.py`::`test_composite_pk_indexes_duplicate_named_variables`
> * `test_prepare.py`::`test_duplicate_named_bind_marker_prepared`
> 
> The first two tests were written in the mindset that Scylla is never wrong so were marked "scylla_only", the third was written with the mindset that Scylla should be compatible with Cassandra, so was marked "xfail" mentioning #15559.
> 
> One can argue that after your patch nothing actually changes (the flag is off by default) so the three tests should remain with the same tags as they are today. However, it is really odd to have an xfailing test for an issue that was already solved. So I think at the very minimum the comment in this test should be modified to explain the new situation. 

Yes

> But at the less minimum, we should consider perhaps configuring the test framework with the new parameter and testing with it (so the xfail test would start to pass). We already did this with the "--strict-allow-filtering" option - for some reason we decided not to make it (yet) the default, but test/cql-pytest/run.py (and test.py) enable it, so tests assume this flag is enabled.

Ok

> 
> Finally, no matter what you decide to do with the existing test test_duplicate_named_bind_marker_prepared, it should at least be mentioned. It's supposed to _pass_ after your patch when the new flag is enabled. Does it? More generally, in a patch like this whose goal is to restore compatiblity with Cassandra (and older Scylla), we need the test to confirm Cassandra compatibility. Adding a new C++ test just doesn't test this. The existing cql-pytest test does.


We could duplicate the test to run both with and without the new option.

File: cql3/dialect.hh (hunk 1 above)
Comment (ptrsmrn) [inline cql3/dialect.hh:9]: Consider:
```suggestion
    bool duplicate_bind_variable_names_refer_to_same_variable = true;  // if :a is found more than once in a query, all the references are to the same variable
```

**Comment by nyh** [comment]
> We could duplicate the test to run both with and without the new option.

This is something which is not trivial in the cql-pytest framework because it doesn't start a separate Scylla for every test, but - we do have a convenient function `config_value_context` which allows a test to temporarily change some config variable (assuming - which we do - that tests to not run in parallel on the same Scylla). So using `config_value_context` you can easily enable or disable this flag inside a test.

Let's just make sure that the test which has this config set to true also runs on Cassandra - I want to see the same test passing on Scylla and Cassandra - which means the compatibility that this patch set out to achieve was actually achieved.

**Comment by avikivity** [comment]
Yet another obstacle: https://github.com/scylladb/scylladb/pull/19792

**Comment by avikivity** [comment]
v2:
 - rebased past obstables
 - added documentation
 - split dialect into its own patch
 - make dialect part of prepared statement cache key, so that if the dialect is changed during runtime, we re-prepare the statement
 - duplicated relevant tests so we test both current state and with the new compatibility mode

File: cql3/cql_config.hh [hunk 2]
```diff
@@ -11,14 +11,17 @@
...
 namespace db { class config; }
 
 namespace cql3 {
 
 struct cql_config {
     restrictions::restrictions_config restrictions;
-    explicit cql_config(const db::config& cfg) : restrictions(cfg) {}
+    explicit cql_config(const db::config& cfg)
+            : restrictions(cfg) {
+    }
```
Comment (avikivity) [inline cql3/cql_config.hh:24]: This is unneeded, I'll remove it.

**Comment by avikivity** [comment]
v3:
 - remove unnecessart change to cql_config
 - marked test_duplicate_named_bind_marker_prepared as no longer xfail
 - adjusted comments in test_duplicate_named_bind_marker_prepared

**Review by nyh — APPROVED** [review]
The patch and tests look good to me, but I have an uneasy feeling that the fix, with the new "dialect" everywhere, is way more complex than we really need. Since the setting of true or false on this parameter comes from _configuration_, why can't we just use the configuration to get the _current_ value instead of saving it in prepared statements, passing it through dozens of functions, and so on? 

Is it all because you wanted to make this option live-updatable so it's possible to use a prepared statement after the change of this option? Could we perhaps solved this problem by clearing the prepared statement cache when this option is changed? Or did you consider that a problem or inefficient? Is this "dialect" thing needed for anything besides the prepared statement cache?

By the way, what happens if not all the cluster agrees on the value of this option (during a rolling upgrade or a rolling live-update to this option) - will things work as expected? Won't the driver get confused when different nodes think there are different number of bound variables, or maybe the drivers already hold this information in a per-node basis so it won't get confused?

File: cql3/prepared_statements_cache.hh [hunk 3]
```diff
@@ -37,13 +38,17 @@ class prepared_cache_key_type {
 public:
     // derive from cql_prepared_id_type so we can customize the formatter of
     // cache_key_type
-    struct cache_key_type : public cql_prepared_id_type {};
+    struct cache_key_type : public cql_prepared_id_type {
+        cache_key_type(cql_prepared_id_type&& id, cql3::dialect d) : cql_prepared_id_type(std::move(id)), dialect(d) {}
+        cql3::dialect dialect; // Not part of hash, but we don't expect collisions because of that
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/prepared_statements_cache.hh:43]: Usually only one dialect will be active. So you won't have collisions due to the dialect not being part of the hash.

**Comment by avikivity** [comment]
@nyh please see my answer to your concern re complexity

**Comment by nyh** [comment]
> > Could we perhaps solved this problem by clearing the prepared statement cache when this option is changed? Or did you consider that a problem or inefficient? Is this "dialect" thing needed for anything besides the prepared statement cache?
> 
> Consider:
> 
>     1. statement is prepared with dialect A
> 
>     2. yield
> 
>     3. dialect changed to B
> 
>     4. preparation complete, stored to cache with dialect B

The "store to cache"  code could check if the dialect configuration changed since step 1, and if it did, not store it. This is a kind of "optimistic locking" (you can also have real locking, with a semaphore, but I think it's unnecessary in this case).

> In principle this can happen in other places if the dialect is sampled more than once.

I guess that's true, if a particular long query gets its dialect changed in the middle. This can even happen between queries, in a long scan. I don't know if it's a disaster, doesn't matter, or something in the middle.

> > By the way, what happens if not all the cluster agrees on the value of this option (during a rolling upgrade or a rolling live-update to this option) - will things work as expected? Won't the driver get confused when different nodes think there are different number of bound variables, or maybe the drivers already hold this information in a per-node basis so it won't get confused?
> 
> I believe the drivers don't have the notion of per-node preparation (and that this is a problem if different nodes can come up with different query plans).
> 
> It's likely a problem for this series too, but it has to be solved in the drivers (or by cycling the application).

This is what worried me - if live-update of "dialect" is still a problem with this pach, just not on a single node but between nodes, and if this problems mean we can't do updates of dialect (not even live-updates - even rolling changes are a problem) - I'm not sure what all the complexity in this series - which is all about allowing live-update - actually buys us.

If live-update will "usually" work but there are certain concerns about what is safe and not safe regarding changing the "dialect" configuration with this patch in a multi-node cluster, or what changes (if at all) we will need to do drivers, maybe we need to document this somewhere.

If you personally believe in this "dialect" approach and considering to add other things to it in the future and planning to maintain it, I am willing to merge and consider the rest of the things later.

**Comment by avikivity** [comment]
> > > Could we perhaps solved this problem by clearing the prepared statement cache when this option is changed? Or did you consider that a problem or inefficient? Is this "dialect" thing needed for anything besides the prepared statement cache?
> > 
> > 
> > Consider:
> > ```
> > 1. statement is prepared with dialect A
> > 
> > 2. yield
> > 
> > 3. dialect changed to B
> > 
> > 4. preparation complete, stored to cache with dialect B
> > ```
> 
> The "store to cache" code could check if the dialect configuration changed since step 1, and if it did, not store it. This is a kind of "optimistic locking" (you can also have real locking, with a semaphore, but I think it's unnecessary in this case).

This would work, but wouldn't it require propagation of the dialect everywhere? Or at least, every time we sample the dialect, store it, and then compare with the point of actual use.



> 
> > In principle this can happen in other places if the dialect is sampled more than once.
> 
> I guess that's true, if a particular long query gets its dialect changed in the middle. This can even happen between queries, in a long scan. I don't know if it's a disaster, doesn't matter, or something in the middle.

I wanted to avoid the problem where a bad query gets cached and there's no way to avoid it other than cycling the server. In general I don't think we need to give special consideration for changing the meaning mid-query.


For example, I want to change the meaning of `col = NULL`, and to do that we can implement IS NULL and ask users who have such queries to switch. We just need to make sure that when we do update, we don't leave any incorrectly interpreted queries behind.

> 
> > > By the way, what happens if not all the cluster agrees on the value of this option (during a rolling upgrade or a rolling live-update to this option) - will things work as expected? Won't the driver get confused when different nodes think there are different number of bound variables, or maybe the drivers already hold this information in a per-node basis so it won't get confused?
> > 
> > 
> > I believe the drivers don't have the notion of per-node preparation (and that this is a problem if different nodes can come up with different query plans).
> > It's likely a problem for this series too, but it has to be solved in the drivers (or by cycling the application).
> 
> This is what worried me - if live-update of "dialect" is still a problem with this pach, just not on a single node but between nodes, and if this problems mean we can't do updates of dialect (not even live-updates - even rolling changes are a problem) - I'm not sure what all the complexity in this series - which is all about allowing live-update - actually buys us.
> 
> If live-update will "usually" work but there are certain concerns about what is safe and not safe regarding changing the "dialect" configuration with this patch in a multi-node cluster, or what changes (if at all) we will need to do drivers, maybe we need to document this somewhere.

We can, but this is one of the cases where no one will read the documentation because it's for an extremely obscure case, and it will only serve as a "see, it's documented" thing. Such problems have to be solved by making the system less fragile.

> 
> If you personally believe in this "dialect" approach and considering to add other things to it in the future and planning to maintain it, I am willing to merge and consider the rest of the things later.


I can't say I'm 100% sure. I do see LWT `col = NULL` as a candidate.

**Comment by avikivity** [comment]
> > > The patch and tests look good to me, but I have an uneasy feeling that the fix, with the new "dialect" everywhere, is way more complex than we really need.
> > 
> > 
> > I'm not thrilled with it either.
> > > Since the setting of true or false on this parameter comes from _configuration_, why can't we just use the configuration to get the _current_ value instead of saving it in prepared statements, passing it through dozens of functions, and so on?
> > > Is it all because you wanted to make this option live-updatable so it's possible to use a prepared statement after the change of this option?
> > 
> > 
> > Yes (it's really annoying if you change a configuration option and it has no effect due to some cache).
> > > Could we perhaps solved this problem by clearing the prepared statement cache when this option is changed? Or did you consider that a problem or inefficient? Is this "dialect" thing needed for anything besides the prepared statement cache?
> > 
> > 
> > Consider:
> > ```
> > 1. statement is prepared with dialect A
> > 
> > 2. yield
> > 
> > 3. dialect changed to B
> > 
> > 4. preparation complete, stored to cache with dialect B
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In principle this can happen in other places if the dialect is sampled more than once.
> > > By the way, what happens if not all the cluster agrees on the value of this option (during a rolling upgrade or a rolling live-update to this option) - will things work as expected? Won't the driver get confused when different nodes think there are different number of bound variables, or maybe the drivers already hold this information in a per-node basis so it won't get confused?
> > 
> > 
> > I believe the drivers don't have the notion of per-node preparation (and that this is a problem if different nodes can come up with different query plans).
> > It's likely a problem for this series too, but it has to be solved in the drivers (or by cycling the application).
> 
> What needs to be solved in the drivers and how? As you said, drivers don't have any "per-node" prepared statement, and I don't think it's possible to introduce such thing. To calculate Token, and thus query plan, driver needs to serialize partition key columns. If different nodes return different prepared metadata, which one should be used for this?

I don't think anything needs to be solved in the drivers for this.

The scenario is:
 - user migrates from an older ScyllaDB version or Cassandra
 - query that uses the same bind variable name in multiple places with different meaning (and values!) stops preparing or working, or query that declares named variables but uses them with the positional API stops preparing or working
 - user updates all nodes with the new configuration
 - queries that stopped preparing now do prepare
 - queries that did prepare might not have their metadata updated, so need to cycle the application
 
The goal of the plumbing down dialect was to avoid having to cycle the servers. There's no need to change the drivers to achieve that. We could add an extra goal to avoid having to cycle the application, but that would be a much larger project.

**Comment by avikivity** [comment]
@nyh ping

**Comment by avikivity** [comment]
@nyh ping2

**Comment by avikivity** [comment]
@denesb please review, as @nyh is on vacation

**Comment by avikivity** [comment]
v4: rebased

File: test/cql-pytest/test_prepare.py [hunk 4]
```diff
@@ -183,11 +220,42 @@ def test_duplicate_named_bind_marker_prepared(cql, table1):
...
+        assert [(x,x)] == list(cql.execute(stmt, {'x1': x, 'x2': x}))
+        assert [(x,x)] == list(cql.execute(stmt, (x,x)))
+        # Now for the real test: Use the same bind-marker name twice.
+        stmt = cql.prepare(f'SELECT * FROM {table1} WHERE p=:x AND c=:x')
+        # If EXECUTE is passed a bound value with a name "x", both bind markers
+        # named "x" are assigned, and the query works:
+        assert [(x,x)] == list(cql.execute(stmt, {'x': x}))
+        # In Cassandra, if EXECUTE is passed unnamed bound values, they go to the
+        # bind markers no matter what their name is - using ":x" twice in the
+        # query has the same effect as using "?" twice - you still need to pass
```
Comment (denesb) [inline test/cql-pytest/test_prepare.py:256]: This sentence looks incomplete.

File: test/lib/cql_test_env.cc [hunk 5]
```diff
@@ -186,6 +186,7 @@ class single_node_cql_env : public cql_test_env {
 private:
     cql3::dialect test_dialect() {
         return cql3::dialect{
+            .duplicate_bind_variable_names_refer_to_same_variable = _db.local().get_config().cql_duplicate_bind_variable_names_refer_to_same_variable(),
```
Comment (denesb) [inline test/lib/cql_test_env.cc:189]: Looks like users have to make up their minds about which mode to use very early and choose one or the other. How does Cassandra solve this? Do they also have a config?

Comment (denesb) [reply test/lib/cql_test_env.cc:189]: After reading the comments above, it looks like this is feature flag that the user has to consciously update on a per-need basis. Is that correct?

Comment (avikivity) [reply test/lib/cql_test_env.cc:189]: Cassandra only has duplicate_bind_variable_names_refer_to_same_variable = false. This is nonsensical if one uses named bind variables and uses the keyword API in the driver. However, it can work if one uses named bind variables but the positional API in the driver, which in fact was seen in the field.

**Comment by avikivity** [comment]
v5:
 - completed a sentence in a comment
