### PR TITLE
Basic tablet repair support

### LINKED ISSUE #16599: Add tablet repair support
Tablet table does not work with current repair code. We need to adjust the row level repair code to make them work together.  As a starter, we will make `nodetool repair myks mytable` and `nodetool repair -pr myks mytable`  work. 
Other repair options are not supported.  We will support more repair options incrementally.

### PR DESCRIPTION
**Pull request by asias**
This patch adds basic tablet repair support.

Below is an example showing how tablet repairs works. The `nodetool
repair -pr` cmd was performed on all the nodes, which makes sure no duplication
repair work will be performed and each tablet will be repaired exactly once.

Three nodes in the cluster. RF = 2. 16 initial tablets.

Tablets:
```
cqlsh> SELECT  * FROM system.tablets;

 keyspace_name | table_id                             | last_token           | table_name | tablet_count | new_replicas | replicas                                                                               | session | stage
---------------+--------------------------------------+----------------------+------------+--------------+--------------+----------------------------------------------------------------------------------------+---------+-------
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -8070450532247928833 |  standard1 |           16 |         null | [(951cb5bc-5749-481a-9645-4dd0f624f24a, 6), (2dd3808d-6601-4483-b081-adf41ef094e5, 5)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -6917529027641081857 |  standard1 |           16 |         null | [(2dd3808d-6601-4483-b081-adf41ef094e5, 0), (19caaeb3-d754-4704-a998-840df53eb54c, 5)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -5764607523034234881 |  standard1 |           16 |         null | [(19caaeb3-d754-4704-a998-840df53eb54c, 2), (2dd3808d-6601-4483-b081-adf41ef094e5, 3)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -4611686018427387905 |  standard1 |           16 |         null | [(951cb5bc-5749-481a-9645-4dd0f624f24a, 5), (2dd3808d-6601-4483-b081-adf41ef094e5, 4)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -3458764513820540929 |  standard1 |           16 |         null | [(19caaeb3-d754-4704-a998-840df53eb54c, 1), (951cb5bc-5749-481a-9645-4dd0f624f24a, 0)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -2305843009213693953 |  standard1 |           16 |         null | [(951cb5bc-5749-481a-9645-4dd0f624f24a, 7), (2dd3808d-6601-4483-b081-adf41ef094e5, 1)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 | -1152921504606846977 |  standard1 |           16 |         null | [(19caaeb3-d754-4704-a998-840df53eb54c, 7), (951cb5bc-5749-481a-9645-4dd0f624f24a, 1)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |                   -1 |  standard1 |           16 |         null | [(951cb5bc-5749-481a-9645-4dd0f624f24a, 2), (2dd3808d-6601-4483-b081-adf41ef094e5, 7)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  1152921504606846975 |  standard1 |           16 |         null | [(951cb5bc-5749-481a-9645-4dd0f624f24a, 6), (19caaeb3-d754-4704-a998-840df53eb54c, 2)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  2305843009213693951 |  standard1 |           16 |         null | [(2dd3808d-6601-4483-b081-adf41ef094e5, 5), (951cb5bc-5749-481a-9645-4dd0f624f24a, 7)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  3458764513820540927 |  standard1 |           16 |         null | [(2dd3808d-6601-4483-b081-adf41ef094e5, 1), (19caaeb3-d754-4704-a998-840df53eb54c, 3)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  4611686018427387903 |  standard1 |           16 |         null | [(2dd3808d-6601-4483-b081-adf41ef094e5, 7), (951cb5bc-5749-481a-9645-4dd0f624f24a, 1)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  5764607523034234879 |  standard1 |           16 |         null | [(19caaeb3-d754-4704-a998-840df53eb54c, 6), (2dd3808d-6601-4483-b081-adf41ef094e5, 2)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  6917529027641081855 |  standard1 |           16 |         null | [(19caaeb3-d754-4704-a998-840df53eb54c, 5), (951cb5bc-5749-481a-9645-4dd0f624f24a, 3)] |    null |  null
           ks1 | 3ffadad0-a552-11ee-bc15-66412bbb6978 |  8070450532247928831 |  standard1 |           16 |         null | [(2dd3808d-6601-4483-b081-adf41ef094e5, 0), (19caaeb3-d754-4704-a998-840df53eb54c, 7)] |    null |  null
```

node1:
```
$nodetool repair -p 7199 -pr ks1 standard1
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: starting user-requested repair for keyspace ks1, repair id 6, options {{trace -> false}, {primaryRange -> true}, {columnFamilies -> standard1}, {jobThreads -> 1}, {incremental -> false}, {parallelism -> parallel}}
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c] Repair 1 out of 5 tablets: table=ks1.standard1 tablet_id=2 range=(-6917529027641081857,-5764607523034234881] replicas={19caaeb3-d754-4704-a998-840df53eb54c:2, 2dd3808d-6601-4483-b081-adf41ef094e5:3} primary_replica_only=true
[shard 2:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.07399633 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7174440}, {127.0.0.2, 7174440}}, row_from_disk_nr={{127.0.0.1, 15330}, {127.0.0.2, 15330}}, row_from_disk_bytes_per_sec={{127.0.0.1, 92.4651}, {127.0.0.2, 92.4651}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 207172}, {127.0.0.2, 207172}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c] Repair 2 out of 5 tablets: table=ks1.standard1 tablet_id=4 range=(-4611686018427387905,-3458764513820540929] replicas={19caaeb3-d754-4704-a998-840df53eb54c:1, 951cb5bc-5749-481a-9645-4dd0f624f24a:0} primary_replica_only=true
[shard 1:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.07302664 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7195032}, {127.0.0.3, 7195032}}, row_from_disk_nr={{127.0.0.1, 15374}, {127.0.0.3, 15374}}, row_from_disk_bytes_per_sec={{127.0.0.1, 93.9618}, {127.0.0.3, 93.9618}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 210526}, {127.0.0.3, 210526}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c] Repair 3 out of 5 tablets: table=ks1.standard1 tablet_id=6 range=(-2305843009213693953,-1152921504606846977] replicas={19caaeb3-d754-4704-a998-840df53eb54c:7, 951cb5bc-5749-481a-9645-4dd0f624f24a:1} primary_replica_only=true
[shard 7:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.06781354 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7095816}, {127.0.0.3, 7095816}}, row_from_disk_nr={{127.0.0.1, 15162}, {127.0.0.3, 15162}}, row_from_disk_bytes_per_sec={{127.0.0.1, 99.7898}, {127.0.0.3, 99.7898}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 223584}, {127.0.0.3, 223584}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c] Repair 4 out of 5 tablets: table=ks1.standard1 tablet_id=12 range=(4611686018427387903,5764607523034234879] replicas={19caaeb3-d754-4704-a998-840df53eb54c:6, 2dd3808d-6601-4483-b081-adf41ef094e5:2} primary_replica_only=true
[shard 6:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.06793772 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7150572}, {127.0.0.2, 7150572}}, row_from_disk_nr={{127.0.0.1, 15279}, {127.0.0.2, 15279}}, row_from_disk_bytes_per_sec={{127.0.0.1, 100.376}, {127.0.0.2, 100.376}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 224897}, {127.0.0.2, 224897}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c] Repair 5 out of 5 tablets: table=ks1.standard1 tablet_id=13 range=(5764607523034234879,6917529027641081855] replicas={19caaeb3-d754-4704-a998-840df53eb54c:5, 951cb5bc-5749-481a-9645-4dd0f624f24a:3} primary_replica_only=true
[shard 5:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.068579935 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7129512}, {127.0.0.3, 7129512}}, row_from_disk_nr={{127.0.0.1, 15234}, {127.0.0.3, 15234}}, row_from_disk_bytes_per_sec={{127.0.0.1, 99.1432}, {127.0.0.3, 99.1432}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 222135}, {127.0.0.3, 222135}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[f7ac8fb6-8e49-4b31-8c7d-0d493064977c]: Finished user-requested repair for tablet keyspace=ks1 tables={standard1} repair_id=6 duration=0.352379s
```

node2:
```
$nodetool repair -p 7200 -pr ks1 standard1
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: starting user-requested repair for keyspace ks1, repair id 1, options {{trace -> false}, {primaryRange -> true}, {columnFamilies -> standard1}, {jobThreads -> 1}, {incremental -> false}, {parallelism -> parallel}}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e] Repair 1 out of 6 tablets: table=ks1.standard1 tablet_id=1 range=(-8070450532247928833,-6917529027641081857] replicas={2dd3808d-6601-4483-b081-adf41ef094e5:0, 19caaeb3-d754-4704-a998-840df53eb54c:5} primary_replica_only=true
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.07016466 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7212816}, {127.0.0.2, 7212816}}, row_from_disk_nr={{127.0.0.1, 15412}, {127.0.0.2, 15412}}, row_from_disk_bytes_per_sec={{127.0.0.1, 98.0362}, {127.0.0.2, 98.0362}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 219655}, {127.0.0.2, 219655}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e] Repair 2 out of 6 tablets: table=ks1.standard1 tablet_id=9 range=(1152921504606846975,2305843009213693951] replicas={2dd3808d-6601-4483-b081-adf41ef094e5:5, 951cb5bc-5749-481a-9645-4dd0f624f24a:7} primary_replica_only=true
[shard 5:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.07180758 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.2, 7236216}, {127.0.0.3, 7236216}}, row_from_disk_nr={{127.0.0.2, 15462}, {127.0.0.3, 15462}}, row_from_disk_bytes_per_sec={{127.0.0.2, 96.104}, {127.0.0.3, 96.104}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.2, 215325}, {127.0.0.3, 215325}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e] Repair 3 out of 6 tablets: table=ks1.standard1 tablet_id=10 range=(2305843009213693951,3458764513820540927] replicas={2dd3808d-6601-4483-b081-adf41ef094e5:1, 19caaeb3-d754-4704-a998-840df53eb54c:3} primary_replica_only=true
[shard 1:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.06772773 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7039188}, {127.0.0.2, 7039188}}, row_from_disk_nr={{127.0.0.1, 15041}, {127.0.0.2, 15041}}, row_from_disk_bytes_per_sec={{127.0.0.1, 99.1188}, {127.0.0.2, 99.1188}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 222080}, {127.0.0.2, 222080}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e] Repair 4 out of 6 tablets: table=ks1.standard1 tablet_id=11 range=(3458764513820540927,4611686018427387903] replicas={2dd3808d-6601-4483-b081-adf41ef094e5:7, 951cb5bc-5749-481a-9645-4dd0f624f24a:1} primary_replica_only=true
[shard 7:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.07025768 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.2, 7229664}, {127.0.0.3, 7229664}}, row_from_disk_nr={{127.0.0.2, 15448}, {127.0.0.3, 15448}}, row_from_disk_bytes_per_sec={{127.0.0.2, 98.1351}, {127.0.0.3, 98.1351}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.2, 219876}, {127.0.0.3, 219876}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e] Repair 5 out of 6 tablets: table=ks1.standard1 tablet_id=14 range=(6917529027641081855,8070450532247928831] replicas={2dd3808d-6601-4483-b081-adf41ef094e5:0, 19caaeb3-d754-4704-a998-840df53eb54c:7} primary_replica_only=true
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.0719635 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7225452}, {127.0.0.2, 7225452}}, row_from_disk_nr={{127.0.0.1, 15439}, {127.0.0.2, 15439}}, row_from_disk_bytes_per_sec={{127.0.0.1, 95.7531}, {127.0.0.2, 95.7531}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 214539}, {127.0.0.2, 214539}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e] Repair 6 out of 6 tablets: table=ks1.standard1 tablet_id=15 range=(8070450532247928831,9223372036854775807] replicas={2dd3808d-6601-4483-b081-adf41ef094e5:4, 19caaeb3-d754-4704-a998-840df53eb54c:3} primary_replica_only=true
[shard 4:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.0691715 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7122960}, {127.0.0.2, 7122960}}, row_from_disk_nr={{127.0.0.1, 15220}, {127.0.0.2, 15220}}, row_from_disk_bytes_per_sec={{127.0.0.1, 98.2049}, {127.0.0.2, 98.2049}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 220033}, {127.0.0.2, 220033}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[5c805f0c-4ff2-4c5c-88df-bb318d559e0e]: Finished user-requested repair for tablet keyspace=ks1 tables={standard1} repair_id=1 duration=0.42178s
```
node3:
```
$nodetool repair -p 7300 -pr ks1 standard1
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: starting user-requested repair for keyspace ks1, repair id 1, options {{trace -> false}, {primaryRange -> true}, {columnFamilies -> standard1}, {jobThreads -> 1}, {incremental -> false}, {parallelism -> parallel}}
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6] Repair 1 out of 5 tablets: table=ks1.standard1 tablet_id=0 range=(minimum token,-8070450532247928833] replicas={951cb5bc-5749-481a-9645-4dd0f624f24a:6, 2dd3808d-6601-4483-b081-adf41ef094e5:5} primary_replica_only=true
[shard 6:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.07126866 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.2, 7133256}, {127.0.0.3, 7133256}}, row_from_disk_nr={{127.0.0.2, 15242}, {127.0.0.3, 15242}}, row_from_disk_bytes_per_sec={{127.0.0.2, 95.4529}, {127.0.0.3, 95.4529}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.2, 213867}, {127.0.0.3, 213867}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6] Repair 2 out of 5 tablets: table=ks1.standard1 tablet_id=3 range=(-5764607523034234881,-4611686018427387905] replicas={951cb5bc-5749-481a-9645-4dd0f624f24a:5, 2dd3808d-6601-4483-b081-adf41ef094e5:4} primary_replica_only=true
[shard 5:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.0701025 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.2, 7138404}, {127.0.0.3, 7138404}}, row_from_disk_nr={{127.0.0.2, 15253}, {127.0.0.3, 15253}}, row_from_disk_bytes_per_sec={{127.0.0.2, 97.1108}, {127.0.0.3, 97.1108}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.2, 217581}, {127.0.0.3, 217581}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6] Repair 3 out of 5 tablets: table=ks1.standard1 tablet_id=5 range=(-3458764513820540929,-2305843009213693953] replicas={951cb5bc-5749-481a-9645-4dd0f624f24a:7, 2dd3808d-6601-4483-b081-adf41ef094e5:1} primary_replica_only=true
[shard 7:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.06859512 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.2, 7171632}, {127.0.0.3, 7171632}}, row_from_disk_nr={{127.0.0.2, 15324}, {127.0.0.3, 15324}}, row_from_disk_bytes_per_sec={{127.0.0.2, 99.7068}, {127.0.0.3, 99.7068}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.2, 223398}, {127.0.0.3, 223398}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6] Repair 4 out of 5 tablets: table=ks1.standard1 tablet_id=7 range=(-1152921504606846977,-1] replicas={951cb5bc-5749-481a-9645-4dd0f624f24a:2, 2dd3808d-6601-4483-b081-adf41ef094e5:7} primary_replica_only=true
[shard 2:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.06975318 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.2, 7105176}, {127.0.0.3, 7105176}}, row_from_disk_nr={{127.0.0.2, 15182}, {127.0.0.3, 15182}}, row_from_disk_bytes_per_sec={{127.0.0.2, 97.1429}, {127.0.0.3, 97.1429}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.2, 217653}, {127.0.0.3, 217653}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6] Repair 5 out of 5 tablets: table=ks1.standard1 tablet_id=8 range=(-1,1152921504606846975] replicas={951cb5bc-5749-481a-9645-4dd0f624f24a:6, 19caaeb3-d754-4704-a998-840df53eb54c:2} primary_replica_only=true
[shard 6:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: stats: repair_reason=repair, keyspace=ks1, tables={standard1}, ranges_nr=1, round_nr=2, round_nr_fast_path_already_synced=2, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=6, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.070810474 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.0.1, 7023276}, {127.0.0.3, 7023276}}, row_from_disk_nr={{127.0.0.1, 15007}, {127.0.0.3, 15007}}, row_from_disk_bytes_per_sec={{127.0.0.1, 94.5894}, {127.0.0.3, 94.5894}} MiB/s, row_from_disk_rows_per_sec={{127.0.0.1, 211932}, {127.0.0.3, 211932}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
[shard 0:strm] repair - repair[350b97f3-f06e-470f-9164-43997a4f82a6]: Finished user-requested repair for tablet keyspace=ks1 tables={standard1} repair_id=1 duration=0.351395s
```

Fixes #16599

### CODE REVIEW

File: repair/repair.hh [hunk 1]
```diff
@@ -147,6 +148,7 @@ public:
         : all(std::move(a))
         , mandatory(std::move(m)) {
     }
+    repair_neighbors(std::vector<gms::inet_address> nodes, std::vector<shard_id> shards);
```
Comment (avikivity) [inline repair/repair.hh:156]: It's a bit weak that we can use the wrong constructor and get an instance of repair_neighbors without shards. But we'll have to live with it.

File: message/messaging_service.hh [hunk 2]
```diff
@@ -383,21 +383,21 @@ public:
     future<std::tuple<rpc::sink<frozen_mutation_fragment, streaming::stream_mutation_fragments_cmd>, rpc::source<int32_t>>> make_sink_and_source_for_stream_mutation_fragments(table_schema_version schema_id, streaming::plan_id plan_id, table_id cf_id, uint64_t estimated_partitions, streaming::stream_reason reason, service::session_id session, msg_addr id);
 
     // Wrapper for REPAIR_GET_ROW_DIFF_WITH_RPC_STREAM
-    future<std::tuple<rpc::sink<repair_hash_with_cmd>, rpc::source<repair_row_on_wire_with_cmd>>> make_sink_and_source_for_repair_get_row_diff_with_rpc_stream(uint32_t repair_meta_id, msg_addr id);
+    future<std::tuple<rpc::sink<repair_hash_with_cmd>, rpc::source<repair_row_on_wire_with_cmd>>> make_sink_and_source_for_repair_get_row_diff_with_rpc_stream(uint32_t repair_meta_id, shard_id dst_cpu_id, msg_addr id);
```
Comment (avikivity) [inline message/messaging_service.hh:386]: Why do we need to change the rpc? Doesn't the remote node know the shard for the range?

File: repair/task_manager_module.hh [hunk 3]
```diff
@@ -100,6 +100,33 @@ protected:
     virtual std::optional<double> expected_children_number() const override;
 };
 
+class tablet_repair_task_impl : public repair_task_impl {
+private:
+    std::vector<table_id> _table_ids;
+    dht::token_range_vector _ranges;
+    std::unordered_map<dht::token_range, repair_neighbors> _neighbors;
+    locator::effective_replication_map_ptr _erm;
```
Comment (avikivity) [inline repair/task_manager_module.hh:108]: If we hold this, it should block tablet migrations, no?

This is bad for the long term, but good for the short term. It ensures correctness over performance.

@tgrabiec

File: repair/repair.cc [hunk 4]
```diff
@@ -2052,6 +2052,77 @@ future<> repair_service::replace_with_repair(locator::token_metadata_ptr tmptr,
     co_return co_await do_rebuild_replace_with_repair(std::move(cloned_tmptr), std::move(op), myloc.dc, reason, std::move(ignore_nodes));
 }
```
Comment (avikivity) [inline repair/repair.cc:2116]: > Given a table, this function repairs all the tablets belong to this
node.  If the primary_replica_only flag is set, it only repairs the
tablets if the node is the primary replica, i.e, the first node in the
locator::tablet_info.replicas.

Shouldn't it be "first node among all the nodes in tablet_info.replicas that are in this datacenter"?

File: repair/repair.cc [hunk 5]
```diff
@@ -2052,6 +2052,77 @@ future<> repair_service::replace_with_repair(locator::token_metadata_ptr tmptr,
...
+// Repair all tablets belong to this node for the given table
+future<> repair_service::repair_tablets(repair_uniq_id rid, sstring keyspace_name, sstring table_name, host2ip_t host2ip, bool primary_replica_only) {
+    auto& t = _db.local().find_column_family(keyspace_name, table_name);
+    if (!t.uses_tablets()) {
+        throw std::runtime_error(format("Table {}.{} is not a tablet table", keyspace_name, table_name));
+    }
+    table_id tid = t.schema()->id();
+    // FIXME: we need to wait for current tablet movement and disable future tablet movment
+    auto erm = t.get_effective_replication_map();
+    auto& tmap = erm->get_token_metadata_ptr()->tablets().get_tablet_map(tid);
```
Comment (avikivity) [inline repair/repair.cc:2126]: We should refresh the erm after each tablet to give the load balancer a chance to make progress.

I don't mind if this comes as a follow-up, but it's important.

File: repair/repair.cc [hunk 6]
```diff
@@ -2052,6 +2052,77 @@ future<> repair_service::replace_with_repair(locator::token_metadata_ptr tmptr,
...
+        shard_id master_shard_id;
+        // Repair all tablets belong to this node
+        for (auto& r : replicas) {
+            if (r.host == myhostid) {
+                master_shard_id = r.shard;
+                found = true;
+                break;
+            }
+            if (primary_replica_only) {
+                break;
```
Comment (avikivity) [inline repair/repair.cc:2153]: So I think this is wrong for multi-datacenter deployments.

Comment (avikivity) [reply repair/repair.cc:2153]: Maybe: `for (auto& r: replicas | filtered(on_this_datacenter)) {`

File: repair/repair.cc [hunk 7]
```diff
@@ -2052,6 +2052,77 @@ future<> repair_service::replace_with_repair(locator::token_metadata_ptr tmptr,
...
+                nodes.push_back(ip);
+            }
+        }
+        std::unordered_map<dht::token_range, repair_neighbors> neighbors;
+        neighbors[m.range] = repair_neighbors(nodes, shards);
+        co_await container().invoke_on(master_shard_id, [rid, keyspace_name, tid, neighbors, range] (repair_service& rs) -> future<> {
+            auto& t = rs._db.local().find_column_family(tid);
+            auto erm = t.get_effective_replication_map();
+            co_await rs.sync_tablet_using_repair(rid, keyspace_name, tid, erm, range, neighbors, streaming::stream_reason::repair);
+        });
```
Comment (avikivity) [inline repair/repair.cc:2184]: This repairs one tablet per node at a time, we should repair one tablet per shard.

File: repair/repair.cc [hunk 8]
```diff
@@ -2052,6 +2052,77 @@ future<> repair_service::replace_with_repair(locator::token_metadata_ptr tmptr,
...
+                rlogger.debug("repair[{}] Repair get neighbors table={}.{} hostid={} shard={} ip={} myip={} myhostid={}",
+                        rid.uuid(), keyspace_name, table_name, r.host, shard, ip, myip, myhostid);
+                shards.push_back(shard);
+                nodes.push_back(ip);
+            }
+        }
+        std::unordered_map<dht::token_range, repair_neighbors> neighbors;
+        neighbors[m.range] = repair_neighbors(nodes, shards);
+        co_await container().invoke_on(master_shard_id, [rid, keyspace_name, tid, neighbors, range] (repair_service& rs) -> future<> {
+            auto& t = rs._db.local().find_column_family(tid);
```
Comment (avikivity) [inline repair/repair.cc:2181]: Check for drop?

**Comment by avikivity** [comment]
Looks good, I had comments, but it looks like we aren't far.

File: repair/task_manager_module.hh (hunk 3 above)
Comment (raphaelsc) [reply repair/task_manager_module.hh:108]: @tgrabiec provided an example[1], in tablets design doc, on why repair and migration are mutually exclusive. and then he proceed to suggest how to make the locking fine grained, through coordination between balancer and repair scheduler.

[1]
```
Tablet has replicas on nodes A, B C
Tablet movement is initiated with replica change C -> D
Repair is run on node D
Replica movement completes
Repair is run on node C
Repair is run on the remaining replicas

After this, the whole system is supposedly repaired, but the tablet's replica C is in fact not touched by repair.
```

Comment (avikivity) [reply repair/task_manager_module.hh:108]: Tablets should use tombstone_gc_mode = repair, and then if we miss a tablet nothing bad happens.

File: repair/repair.cc [hunk 9]
```diff
@@ -1081,6 +1076,80 @@ future<int> repair_service::do_repair_start(sstring keyspace, std::unordered_map
...
+        for (auto& table_name : cfs) {
+            auto& t = db.find_column_family(keyspace, table_name);
+            if (t.uses_tablets()) {
+                nr_tablet_table++;
+            } else {
+                nr_vnode_table++;
+            }
+        }
+
+        if (nr_tablet_table !=0) {
```
Comment (tgrabiec) [inline repair/repair.cc:1102]: Space after !=

File: repair/repair.cc [hunk 10]
```diff
@@ -1081,6 +1076,80 @@ future<int> repair_service::do_repair_start(sstring keyspace, std::unordered_map
...
+                });
+            };
+            bool primary_replica_only = options.primary_range;
+            auto start_time = std::chrono::steady_clock::now();
+            for (auto& table_name : cfs) {
+                co_await repair_tablets(id, keyspace, table_name, host2ip, primary_replica_only);
+            }
+            auto duration = std::chrono::duration<float>(std::chrono::steady_clock::now() - start_time);
+            rlogger.info("repair[{}]: Finished user-requested repair for tablet keyspace={} tables={} repair_id={} duration={}", id.uuid(), keyspace, cfs, id.id, duration);
+            co_return id.id;
```
Comment (tgrabiec) [inline repair/repair.cc:1144]: This changes the semantic of the API, which now waits for the repair to finish instead of just starting the task.

It could interact badly with scylla manager. \cc @karol-kokoszka

File: repair/repair.cc [hunk 11]
```diff
@@ -1081,6 +1076,80 @@ future<int> repair_service::do_repair_start(sstring keyspace, std::unordered_map
...
+
+    std::vector<sstring> cfs =
+        options.column_families.size() ? options.column_families : list_column_families(db, keyspace);
+    if (cfs.empty()) {
+        rlogger.info("repair[{}]: completed successfully: no tables to repair", id.uuid());
+        co_return id.id;
+    }
+
+    {
+        std::sort(cfs.begin(), cfs.end());
```
Comment (tgrabiec) [inline repair/repair.cc:1089]: Why sort?

File: repair/repair.cc [hunk 12]
```diff
@@ -1081,6 +1076,80 @@ future<int> repair_service::do_repair_start(sstring keyspace, std::unordered_map
...
+                throw std::runtime_error("The hosts option is not supported for tablet repair");
+            }
+            if (!options.ignore_nodes.empty()) {
+                throw std::runtime_error("The ignore_nodes option is not supported for tablet repair");
+            }
+            if (!options.data_centers.empty()) {
+                throw std::runtime_error("The dataCenters option is not supported for tablet repair");
+            }
+            if (!options.start_token.empty()) {
+                throw std::runtime_error("The starToken option is not supported for tablet repair");
```
Comment (tgrabiec) [inline repair/repair.cc:1123]: typo: startToken

File: test/topology_experimental_raft/test_tablets.py [hunk 13]
```diff
@@ -388,3 +388,33 @@ async def test_table_dropped_during_streaming(manager: ManagerClient):
...
+                  "'replication_factor': 2, 'initial_tablets': 32};")
+    await cql.run_async("CREATE TABLE test.test (pk int PRIMARY KEY, c int);")
+
+    logger.info("Populating table")
+
+    keys = range(256)
+    await asyncio.gather(*[cql.run_async(f"INSERT INTO test.test (pk, c) VALUES ({k}, {k});") for k in keys])
+
+    logger.info("Repair table")
+    await manager.api.repair(servers[0].ip_addr, "test", "test")
```
Comment (tgrabiec) [inline test/topology_experimental_raft/test_tablets.py:409]: Would be good to check that repair actually repairs the table, e.g.:
1) write with node2 down, no hints
2) node2 up
3) repair
4) node1 down
5) select * from test.test

**Review by tgrabiec — CHANGES_REQUESTED** [review]

File: repair/repair.hh (hunk 1 above)
Comment (asias) [reply repair/repair.hh:156]: The vnode repair still uses the repair_neighbors without shards.

File: message/messaging_service.hh (hunk 2 above)
Comment (asias) [reply message/messaging_service.hh:386]: There are multiple reasons 1) we need the correct shard id to find the repair_meta on the followers 1) range and others information like table id for querying of shard id are not send on each rpc call 2) most of the rpcs calls are on the fast past, we can not afford to do the query for each rpc call.

File: repair/row_level.cc [hunk 14]
```diff
@@ -2566,6 +2608,17 @@ class row_level_repair {
...
+        auto& map = r_neighbors.shard_map;
+        for (auto& n : _all_live_peer_nodes) {
+            auto it = map.find(n);
+            if (it != map.end()) {
+                _all_live_peer_shards.push_back(it->second);
+            } else {
+                _all_live_peer_shards.push_back(std::nullopt);
+            }
+        }
+        assert(_all_live_peer_shards.size() == _all_live_peer_nodes.size());
```
[the remark this answers is not in the document]
Comment (asias) [reply repair/row_level.cc:2624]: ok.

File: repair/task_manager_module.hh (hunk 3 above)
Comment (asias) [reply repair/task_manager_module.hh:108]: How can we do that? Is there any sample code to achieve that?

File: repair/repair.cc (hunk 4 above)
Comment (asias) [reply repair/repair.cc:2116]: By default, repair would be global repair not a DC only repair.  This patch does not support the DC selection. If we want to support DC selection, we can extend to first node in locator::tablet_info.replicas that belongs to DC X.

File: repair/repair.cc (hunk 5 above)
Comment (asias) [reply repair/repair.cc:2126]: Noted. I will consider this as follow up. It is more complicated than refreshing. The tablet mapping (both number of tablets and ownership of tablet) might change after we have repaired some of the tablets. We need to figure out where to continue after the refresh.

File: repair/repair.cc (hunk 6 above)
Comment (asias) [reply repair/repair.cc:2153]: Yes, see https://github.com/scylladb/scylladb/pull/16600#discussion_r1440008392. By default repair is global repair.

File: repair/repair.cc (hunk 7 above)
Comment (asias) [reply repair/repair.cc:2184]: We could indeed split the work into multiple shards and start on per shard. One problem is that followers might have more than one tablet repair, e,g. tablet(n1:0 n2:1) tablet (n1:1 n2:1). Another things is that if we run nodetool repair -pr on all nodes in parallel, the node in question could run repair on other shards as well, other shards would be utilized even if the repair master work on one shard at a time.

File: repair/repair.cc (hunk 8 above)
Comment (asias) [reply repair/repair.cc:2181]: OK.

File: main.cc [hunk 15]
```diff
@@ -1568,7 +1568,7 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
             // both)
             supervisor::notify("starting repair service");
             auto max_memory_repair = memory::stats().total_memory() * 0.1;
-            repair.start(std::ref(gossiper), std::ref(messaging), std::ref(db), std::ref(proxy), std::ref(bm), std::ref(sys_dist_ks), std::ref(sys_ks), std::ref(view_update_generator), std::ref(task_manager), std::ref(mm), max_memory_repair).get();
+            repair.start(std::ref(gossiper), std::ref(messaging), std::ref(db), std::ref(proxy), std::ref(ss), std::ref(bm), std::ref(sys_dist_ks), std::ref(sys_ks), std::ref(view_update_generator), std::ref(task_manager), std::ref(mm), max_memory_repair).get();
```
[the remark this answers is not in the document]
Comment (asias) [reply main.cc:1571]: Ok. I will try.

File: repair/row_level.cc [hunk 16]
```diff
@@ -510,7 +510,8 @@ void repair_writer_impl::create_writer(lw_shared_ptr<repair_writer> w) {
     replica::table& t = _db.local().find_column_family(_schema->id());
     rlogger.debug("repair_writer: keyspace={}, table={}, estimated_partitions={}", w->schema()->ks_name(), w->schema()->cf_name(), w->get_estimated_partitions());
     service::frozen_topology_guard topo_guard = service::null_topology_guard; // FIXME: propagate
-    _writer_done = mutation_writer::distribute_reader_and_consume_on_shards(_schema, _schema->get_sharder(), std::move(_queue_reader),
+    auto& sharder = t.get_effective_replication_map()->get_sharder(*(w->schema()));
```
[the remark this answers is not in the document]
Comment (asias) [reply repair/row_level.cc:513]: Then we need to take a ref of the erm and hold it until the writer is done.

File: repair/task_manager_module.hh [hunk 17]
```diff
@@ -100,6 +100,33 @@ protected:
...
+    optimized_optional<abort_source::subscription> _abort_subscription;
+public:
+    tablet_repair_task_impl(tasks::task_manager::module_ptr module, repair_uniq_id id, std::string keyspace, dht::token_range_vector ranges, std::unordered_map<dht::token_range, repair_neighbors> neighbors, streaming::stream_reason reason, table_id tid, locator::effective_replication_map_ptr erm)
+        : repair_task_impl(module, id.uuid(), id.id, "keyspace", std::move(keyspace), "", "", tasks::task_id::create_null_id(), reason)
```
[the remark this answers is not in the document]
Comment (asias) [reply repair/task_manager_module.hh:112]: I have no idea what the scope and entity do. I followed existing usage. The table is set to empty in user_requested_repair_task_impl too. I think it is probably not really used in task manager.

File: repair/row_level.cc [hunk 18]
```diff
@@ -2228,6 +2230,7 @@ static future<> repair_get_full_row_hashes_with_rpc_stream_handler(
                             source,
                             error,
                             std::move(status_opt)).handle_exception([sink, &error] (std::exception_ptr ep) mutable {
+                        rlogger.warn("repair_get_full_row_hashes_with_rpc_stream_handler: got error: {}", ep);
```
[the remark this answers is not in the document]
Comment (asias) [reply repair/row_level.cc:2233]: We could. Knowing the exact exception was good enough for me during the development. I will add.

File: repair/repair.cc [hunk 19]
```diff
@@ -2052,6 +2052,77 @@ future<> repair_service::replace_with_repair(locator::token_metadata_ptr tmptr,
     co_return co_await do_rebuild_replace_with_repair(std::move(cloned_tmptr), std::move(op), myloc.dc, reason, std::move(ignore_nodes));
 }
 
+// Repair all tablets belong to this node for the given table
+future<> repair_service::repair_tablets(repair_uniq_id rid, sstring keyspace_name, sstring table_name, host2ip_t host2ip, bool primary_replica_only) {
```
[the remark this answers is not in the document]
Comment (asias) [reply repair/repair.cc:2118]: The range selection is not supported yet. Let's add it later.

File: repair/repair.cc (hunk 12 above)
Comment (asias) [reply repair/repair.cc:1123]: fixed.

File: repair/repair.cc [hunk 20]
```diff
@@ -22,6 +22,7 @@
 #include "utils/hashers.hh"
 #include "locator/network_topology_strategy.hh"
 #include "service/migration_manager.hh"
+#include "service/storage_service.hh"
```
[the remark this answers is not in the document]
Comment (asias) [reply repair/repair.cc:25]: We can add new issues for the missing options that we want to support. No need to use a single issue for everything.

File: repair/repair.cc (hunk 11 above)
Comment (asias) [reply repair/repair.cc:1089]: Because I want the order of tables to repair in a more stable way. Btw, we could also sort from the size of the tablet so we can repair small tables first which SM does the same (Not for now). 

```
    using ks_cf_to_uuid_t =
        flat_hash_map<ks_cf_t, table_id, utils::tuple_hash, string_pair_eq>;
    class tables_metadata {
        rwlock _cf_lock;
        std::unordered_map<table_id, lw_shared_ptr<column_family>> _column_families;
        ks_cf_to_uuid_t _ks_cf_to_uuid;
```

File: test/topology_experimental_raft/test_tablets.py (hunk 13 above)
Comment (asias) [reply test/topology_experimental_raft/test_tablets.py:409]: Yes, we definitely could add more repair tests in test.py.

File: repair/repair.cc (hunk 10 above)
Comment (asias) [reply repair/repair.cc:1144]: We need to fix the PR to make it following the old semantics.

File: repair/row_level.cc (hunk 16 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply repair/row_level.cc:513]: Yes. It will cause problems with repair mutually excluding other things, but that's okay for now.

File: repair/task_manager_module.hh (hunk 3 above)
Comment (tgrabiec) [reply repair/task_manager_module.hh:108]: I will provide the code to do that. You can ignore it for now.

File: repair/repair.cc (hunk 7 above)
Comment (tgrabiec) [reply repair/repair.cc:2184]: This problem will be solved when we implement the design based on tablet scheduler, which has global knowledge. If we want to do it earlier, we'd have to redo the scheduling code here. If it's not based on group0, then parallel nodetool invocations won't see each other.

I think we'd be better off investing in moving this to tablet scheduler.

File: repair/task_manager_module.hh (hunk 17 above)
[the remark this answers is not in the document]
Comment (tgrabiec) [reply repair/task_manager_module.hh:112]: @Deexie Do you have some hints on this?

File: repair/repair.cc (hunk 20 above)
[the remark this answers is not in the document]
Comment (tgrabiec) [reply repair/repair.cc:25]: I'd rather keep the original issue open, unless there is a decision that some options are not needed for the release.

File: repair/repair.cc (hunk 11 above)
Comment (tgrabiec) [reply repair/repair.cc:1089]: What does it help with? We need to leave a comment because it's not obvious.

File: repair/task_manager_module.hh (hunk 3 above)
Comment (tgrabiec) [reply repair/task_manager_module.hh:108]: > Tablets should use tombstone_gc_mode = repair, and then if we miss a tablet nothing bad happens.

I opened https://github.com/scylladb/scylladb/issues/16627 for this.

Comment (avikivity) [reply repair/task_manager_module.hh:108]: If the last repair time stored locally for tombstone_gc_mode = repair? If so it will quickly get out of date. We should move it to the tablets table.

File: repair/repair.cc (hunk 5 above)
Comment (avikivity) [reply repair/repair.cc:2126]: Suggest to maintain an interval map of unrepaired ranges. Start from the beginning, if a range is unowned by this node, remove it. If a range is owned by a shard and the shard isn't repairing, remove the range and start repairing. If the range is owned by a shard and the shard is repairing, move on to the next range.

File: repair/repair.cc (hunk 6 above)
Comment (avikivity) [reply repair/repair.cc:2153]: Ah, I misunderstood -pr (but could have derived it using logic).

File: repair/repair.cc (hunk 7 above)
Comment (avikivity) [reply repair/repair.cc:2184]: It will be a serious regression (slower by number of shards in a node). I think [this](https://github.com/scylladb/scylladb/pull/16600#discussion_r1440669935) is simple enough.

File: repair/task_manager_module.hh (hunk 17 above)
[the remark this answers is not in the document]
Comment (Deexie) [reply repair/task_manager_module.hh:112]: `scope` indicates the size of the job represented by the task. For `user_requested_repair_task_impl`  its "keyspace" as it covers keyspace repair, here I think "tablet" is ok.

`table` is empty when task represents work on many tables or is unrelated to tables. `tablet_repair_task_impl` works on one table, so it would be nice to pass its name.

`entity` is for additional info and is empty for most tasks.

File: repair/task_manager_module.hh (hunk 3 above)
Comment (asias) [reply repair/task_manager_module.hh:108]: Yes, it is stored in a local table. Will it introduce any circular dependency?  The table needs repair.  The repair needs the table to work.

File: repair/repair.cc (hunk 11 above)
Comment (asias) [reply repair/repair.cc:1089]: For example, when a keyspace have multiple tables, it is better to see repair to finish tables in some order, e.g., ks.standard1, ks.standard2, ks.standar3.  Not a in  random order.

File: repair/repair.cc (hunk 20 above)
[the remark this answers is not in the document]
Comment (asias) [reply repair/repair.cc:25]: This is what it was 

```
 As a starter, we will make nodetool repair myks mytable and nodetool repair -pr myks mytable work.
```

I modified the issue description to be more explicit that other repair options are not supported.  We will create new issues to request options we want to support.

File: repair/task_manager_module.hh (hunk 17 above)
[the remark this answers is not in the document]
Comment (asias) [reply repair/task_manager_module.hh:112]: The tablet_repair_task_impl also covers keyspace repair. In my view version, it can repair multiple tables as well. So, I will keep it the same as user_requested_repair_task_impl. Thanks @Deexie .

File: repair/task_manager_module.hh (hunk 3 above)
Comment (avikivity) [reply repair/task_manager_module.hh:108]: The tablets table is managed by Raft and doesn't need repair.

Comment (avikivity) [reply repair/task_manager_module.hh:108]: (one day Raft will use repair internally to transfer state, so we'll have to figure something out, but we don't need to worry about it now)

File: repair/task_manager_module.hh (hunk 17 above)
[the remark this answers is not in the document]
Comment (tgrabiec) [reply repair/task_manager_module.hh:112]: > The tablet_repair_task_impl also covers keyspace repair.

But the task works on a single tablet, so its scope is "tablet", even though its part of a larger keyspace repair. If we tracked keyspace repair as a parent task, then the scope of that task would be "keyspace".

If you set the scope to "keyspace", and repair tablets concurrently, you will see many tasks for the same keyspace with scope "keyspace", which will be confusing, we're not really repairing the same keyspace concurrently.

File: repair/task_manager_module.hh (hunk 3 above)
Comment (tgrabiec) [reply repair/task_manager_module.hh:108]: > Is the last repair time stored locally for tombstone_gc_mode = repair? If so it will quickly get out of date. We should move it to the tablets table.

You mean it will get out of date because tablet replicas are migrated but repair metadata is not? Moving metadata to tablets table is best, but we can also migrate the metadata as part of tablet migration to avoid churn.

File: repair/task_manager_module.hh (hunk 17 above)
[the remark this answers is not in the document]
Comment (asias) [reply repair/task_manager_module.hh:112]: In v2, tablet_repair_task_impl works on multiple tablets, so it is "keyspace" scope. But anyway, I think the concept of scope in task manager is confusing in the first place.

[the remark this answers is not in the document]
Comment (tgrabiec) [reply repair/task_manager_module.hh:112]: Ok.

**Comment by asias** [comment]
Changes in v2:
- Add one more test to check missing rows are repaired
- Rework the repair request api to keep it async
- Take a reference of erm to keep sharder alive
- Use raft_address_map for host id to ip map
- Allow repair working on multiple shards in parallel. Repair one tablet per shard
  instead of one tablet per node

File: repair/repair.cc (hunk 10 above)
Comment (asias) [reply repair/repair.cc:1145]: Fixed in v2.

**Comment by asias** [comment]
Checking CI results for https://github.com/scylladb/scylladb/pull/16600#issuecomment-1880496784

1) test_raft_replace_ignore_nodes 

Unrelated error, fails to stop a node.

`await manager.server_stop_gracefully(servers[2].server_id)`

2) no details why it fails on ci

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5601/testReport/junit/(root)/test_tablets/Tests___Unit_Tests___test_tablet_missing_data_repair/

3)  topology_experimental_raft.test_tablets.dev.5

Not clear what has failed exactly.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5601/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_tablets_dev_5/

4) topology_experimental_raft.test_raft_ignore_nodes.dev.1

Not clear what has failed exactly. 
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5601/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_raft_ignore_nodes_dev_1/

**Comment by bhalevy** [comment]
> Checking CI results for [#16600 (comment)](https://github.com/scylladb/scylladb/pull/16600#issuecomment-1880496784)
> 
> 1. test_raft_replace_ignore_nodes
> 
> Unrelated error, fails to stop a node.
> 
> `await manager.server_stop_gracefully(servers[2].server_id)`
> 
> 2. no details why it fails on ci
> 
> https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5601/testReport/junit/(root)/test_tablets/Tests___Unit_Tests___test_tablet_missing_data_repair/
> 
> 3. topology_experimental_raft.test_tablets.dev.5
> 
> Not clear what has failed exactly.
> 
> https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5601/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_tablets_dev_5/
> 
> It seems to be schema mismatch
> 
> test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode
> 
> ```
> 09:18:34.232 DEBUG> [control connection] Waiting for schema agreement
> 09:18:34.233 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:34.434 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:34.635 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:34.836 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:35.037 DEBUG> [control connection] Schemas mismatched, trying again
> ...
> 
> 09:18:54.953 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:55.154 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:55.355 DEBUG> [control connection] Schemas mismatched, trying again
> 09:18:55.556 DEBUG> [control connection] Schemas mismatched, trying again
> ```
> 
> 4. topology_experimental_raft.test_raft_ignore_nodes.dev.1
> 
> Not clear what has failed exactly. https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5601/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_raft_ignore_nodes_dev_1/

possibly https://github.com/scylladb/scylladb/issues/16435

@asias can you please rebase / re-run CI

**Review by tgrabiec — APPROVED** [review]

File: repair/repair.cc [hunk 21]
```diff
@@ -211,6 +211,17 @@ void remove_item(Collection& c, T& item) {
     }
 }
 
+repair_neighbors::repair_neighbors(std::vector<gms::inet_address> nodes, std::vector<shard_id> shards)
+    : all(std::move(nodes))
+{
+    if (all.size() != shards.size()) {
+        std::runtime_error("The number of shards and nodes do not match");
+    }
```
Comment (raphaelsc) [inline repair/repair.cc:221]: missing throw?

**Comment by tgrabiec** [comment]
We will still need a follow-up to support standard parameters: range, dc, host, ignore nodes. We cannot release without them.

File: repair/repair.cc (hunk 21 above)
Comment (asias) [reply repair/repair.cc:221]: Thanks. Fixed.

**Comment by asias** [comment]
Changes in v3:
- Fixed missing throw
- Rebased

**Comment by asias** [comment]
> We will still need a follow-up to support standard parameters: range, dc, host, ignore nodes. We cannot release without them.

Yes. We will decide which options we want to support and support them in follow-up.

**Comment by asias** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5796/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5796/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7166/)
> #### Failed Tests (1/23784):
> 
>     * [test_disablebinary_and_disablegossip](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5796/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest___test_disablebinary_and_disablegossip) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_disablebinary_and_disablegossip)
> 
> 
> #### Build Details:
> 
>     * Duration: 2 hr 12 min
> 
>     * Builder: spider5.cloudius-systems.com

The failed dtest is unrelated to this PR:

FullDtest / full-split008 / nodetool_additional_test.TestNodetool.test_disablebinary_and_disablegossip

I will start the CI again.

**Comment by asias** [comment]
Changes in v4:
- Rebased to master
- Used the new tablets = {'initial': 1} syntax in dtest after rebase

**Comment by tgrabiec** [comment]
> The failed dtest is unrelated to this PR:
> 
> FullDtest / full-split008 / nodetool_additional_test.TestNodetool.test_disablebinary_and_disablegossip

Please link a related CI-stability issue, or create one if it doesn't exist.

**Comment by asias** [comment]
> > The failed dtest is unrelated to this PR:
> > FullDtest / full-split008 / nodetool_additional_test.TestNodetool.test_disablebinary_and_disablegossip
> 
> Please link a related CI-stability issue, or create one if it doesn't exist.

There is one: https://github.com/scylladb/scylladb/issues/16219

**Comment by asias** [comment]
> #### 🔴 CI State: ABORTED
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5822/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7190/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5822/)
> #### Failed Tests (1/19089):
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5822/testReport/junit/boost.sstable_compaction_test.max_ongoing_compaction_test.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
> 
> #### Build Details:
> 
>     * Duration: 7 hr 35 min
> 
>     * Builder: spider1.cloudius-systems.com

There was no detail why the test failed. 

Tests / Unit Tests / boost.sstable_compaction_test.max_ongoing_compaction_test.2.xunit.xml.[empty]

Test report file /jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/xml/boost.sstable_compaction_test.max_ongoing_compaction_test.2.xunit.xml was length 0

**Comment by asias** [comment]
@scylladb/scylla-maint The CI is green now. Please merge if there are no objections.

**Comment by denesb** [comment]
Looks like all reviewers approved, so I will queue this PR.
