### PR TITLE
cql: fix regression in SELECT * GROUP BY

### LINKED ISSUE #16531: GROUP BY behavior change in 5.4.0? Possible bug?
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04 / Scylla AMI

I upgraded my cluster to 5.4.0 from 5.2.7 yesterday, things went pretty smoothly and afterwards I'm seeing a bit better performance.

However we have 1 program that started to fail and produce unexpected results, and this program uses the "GROUP BY" CQL clause. We tracked the problem down to apparently the program now receiving multiple rows back for the same value that should be grouped to just return the 1st row for each unique grouped value? At least that is how things behaved prior to 5.4.0, I don't know if this change was on purpose or is a bug?

Here's an edited version of the table schema in question:

```
CREATE TABLE a_table (
   pk varint,
   id varchar,
   ts timestamp,
   something varint,
   ...
   blah varchar,
   PRIMARY KEY (pk, id, ts)
) WITH CLUSTERING ORDER BY (id ASC, ts DESC)
  AND compaction = {'class': 'LeveledCompactionStrategy'}
  AND tombstone_gc = {'mode': 'repair'}
  AND comment = 'A comment'
;
```

And if I go into cqlsh now in 5.4.0 and do this query:

> select * FROM a_table WHERE pk = 7 AND id = 'an id that has multiple rows' AND ts > '2023-08-28 02:01:02+0000' GROUP BY id BYPASS CACHE;

Then it returns all the rows for 'an id that has multiple rows' instead of just the 1st row. We also see this behavior in this type of query that returns all the rows in the partition I think:

> select * FROM a_table WHERE pk = 59999 AND ts > '2023-08-28 02:01:02+0000' GROUP BY id ALLOW FILTERING BYPASS CACHE;

Prior to 5.4.0 that query only would return the 1st row for each unique id value in the partition. Can we get this behavior back? For now we are writing a workaround in our software.

### PR DESCRIPTION
**Pull request by nyh**
This short series fixes a regression from Scylla 5.2 to Scylla 5.4 in "SELECT * GROUP BY" - this query was supposed to return just a single row from each partition (the first one in clustering order), but after the expression rewrite started to wrongly return all rows.

The series also includes a regression test that verifies that this query works doesn't work correctly before this series, but works with this patch - and also works as expected in Scylla 5.2 and in Cassadra.

Fixes #16531.

### CODE REVIEW

**Review by avikivity — APPROVED** [review]

**Comment by nyh** [comment]
@avikivity please review my fix. It's fairly simple, but not pretty - the most straightforward way I found to fix this bug was to rewrite the "*" selection to the appropriate list of columns, and although that was pretty easy, it resulted in some ugly code (though very localized), and I wonder if you can think of a better solution.

This PR does **not** address the alleged performance regression mentioned in https://github.com/scylladb/scylladb/issues/16531#issuecomment-1868607100 - it is possible that the rewrite to use first() aggregation hurt performance of the query. But I'm not sure how did this actually happen, or how to solve it, and it might be orthogonal to this fix (the "SELECT a,b,c,d GROUP BY..." should also perform well, not just "SELECT * GROUP BY").

File: cql3/statements/select_statement.cc [hunk 1]
```diff
@@ -1927,6 +1927,21 @@ std::unique_ptr<prepared_statement> select_statement::prepare(data_dictionary::d
     // Force aggregation if GROUP BY is used. This will wrap every column x as first(x).
     if (!_group_by_columns.empty()) {
         aggregation_depth = std::max(aggregation_depth, 1u);
+        if (prepared_selectors.empty()) {
+            // We have a "SELECT * GROUP BY". If we leave prepared_selectors
+            // empty, below we choose selection::wildcard() for SELECT *, and
+            // forget to do the "levellize" trick needed for the GROUP BY.
```
Comment (mykaul) [inline cql3/statements/select_statement.cc:1933]:
```suggestion
            // forget to do the "levelize" trick needed for the GROUP BY.
```

Comment (nyh) [reply cql3/statements/select_statement.cc:1933]: Yes, but Avi used the spelling "levellize" in his original code, so I repeated it here (if you search the quoted word in the rest of this source file, you can see what this trick refers to).
