### PR TITLE
wasm: move compilation to an alien thread

### LINKED ISSUE #12904: Moving WASM compilation to alien
Currently, the compilation of WASM UDFs is performed by a call to a foreign function (wasmtime::precompile_module), which cannot be divided with yielding points and, as a result, causes
long reactor stalls for big UDFs, which in turn may increase latency.

Some time ago, when discussing this problem with @avikivity, he suggested submitting the compilation to the `alien` instance. This would in fact remove the stalls (because the stall detector does not measure the execution time of `alien` tasks) and help with latency (the `alien` tasks are executed only after the more "urgent" tasks), but I'm not sure whether the difference would be worthwhile.

Also, I'm not completely sure how to approach implementation of this. I started writing a working example like [this](https://github.com/scylladb/scylladb/commit/d35cc886f79dcdf2f39d71efa5b136dd1b0b2ed8#diff-e52e05ed9f80dc30769fd670b11bd29b7910703a45628f06dde87ec31171360a) but this approach may be completely wrong, so I'm not posting a PR yet, and waiting for some input instead

### PR DESCRIPTION
**Pull request by wmitros**
The compilation of wasm UDFs is performed by a call to a foreign
function, which cannot be divided with yielding points and, as a
result, causes long reactor stalls for big UDFs.
We avoid them by submitting the compilation task to a non-seastar
std::thread, and retrieving the result using seastar::alien.

The thread is created at the start of the program. It executes
tasks from a queue in an infinite loop.

All seastar shards reference the thread through a std::shared_ptr
to a `alien_thread_runner`.

Considering that the compilation takes a long time anyway, the
alien_thread_runner is implemented with focus on simplicity more
than on performance. The tasks are stored in an std::queue, reading
and writing to it is synchronized using an std::mutex for reading/
writing to the queue, and an std::condition_variable waiting until
the queue has elements.

When the destructor of the alien runner is called, an std::nullopt
sentinel is pushed to the queue, and after all remaining tasks are
finished and the sentinel is read, the thread finishes.

Fixes #12904

### CODE REVIEW

**Comment by wmitros** [comment]
This approach is still not perfect, I'm particularly concerned about how we're accessing memory between shards (in particular, the final compiled module is allocated on the alien thread, and we're saving the result on each shard).
This should still be an improvement over the first approach at #12904 (the compilation wasn't actually performed on an alien thread there), so I'm posting this as a PR.

File: cql3/statements/create_aggregate_statement.cc [hunk 1]
```diff
@@ -22,7 +22,7 @@ namespace cql3 {
 
 namespace statements {
 
-shared_ptr<db::functions::function> create_aggregate_statement::create(query_processor& qp, db::functions::function* old) const {
+seastar::future<shared_ptr<db::functions::function>> create_aggregate_statement::create(query_processor& qp, db::functions::function* old) const {
```
Comment (avikivity) [inline cql3/statements/create_aggregate_statement.cc:25]: When converting non-future to future there is always a risk of introducing races - now two such statements can execute concurrently.

We can assume Raft, so if Raft already serializes execution, we're fine. I don't have any concrete reasons to think  there's a race here, but I'm not too familiar with the code path, so please double check it.

File: lang/wasm_alien_thread_runner.cc [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+#include "lang/wasm.hh"
+#include "lang/wasm_alien_thread_runner.hh"
+
+using namespace std::chrono_literals;
+
+namespace wasm {
+
+std::optional<wasm_compile_task> task_queue::pop_front() {
+    if (_sem.try_acquire_for(10ms)) {
```
Comment (avikivity) [inline lang/wasm_alien_thread_runner.cc:20]: This just generates unnecessary wakeups. Better to use a condition variable and a mutex, then you can wake up the thread for when something is queued or when _stopped is set. Another option is to have a queue of std::optionals, and stop when nullopt is queued.

File: lang/wasm_alien_thread_runner.cc [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+}
+
+void alien_thread_runner::submit(seastar::promise<rust::Box<wasmtime::Module>>& p, std::function<rust::Box<wasmtime::Module>()> f) {
+    std::function<void()> packaged([f=std::move(f), &p, &alien = seastar::engine().alien(), shard = seastar::this_shard_id()] () mutable {
+        try {
+            rust::Box<wasmtime::Module> mod = f();
+            seastar::alien::run_on(alien, shard, [&p, mod = std::move(mod)] () mutable {
+                p.set_value(std::move(mod));
+            });
+        } catch (const rust::Error& e) {
```
Comment (avikivity) [inline lang/wasm_alien_thread_runner.cc:82]: Should handle any exception.

File: main.cc [hunk 4]
```diff
@@ -1006,13 +1007,19 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
             static sharded<wasm::instance_cache> wasm_instance_cache;
             auto udf_enabled = cfg->enable_user_defined_functions() && cfg->check_experimental(db::experimental_features_t::feature::UDF);
             std::any stop_udf_cache_handlers;
+            static std::shared_ptr<wasm::alien_thread_runner> alien_runner = nullptr;
```
Comment (avikivity) [inline main.cc:1010]: You don't need the static if you have correct stop/start. The statics you see are due to bugs.

File: main.cc [hunk 5]
```diff
@@ -1146,6 +1153,7 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
             if (udf_enabled) {
                 qp.invoke_on_all([&] (cql3::query_processor& qp) {
                     qp.set_wasm_instance_cache(&wasm_instance_cache.local());
+                    qp.set_alien_runner(alien_runner);
```
Comment (avikivity) [inline main.cc:1156]: What prevents use of the alien runner before it is set?

**Comment by avikivity** [comment]
Looks good. I had some minor comments.

It would be good to renice the thread so it doesn't compete with reactor threads or the networking core. See pthread_setthreadprio(). If it uses the same priority levels as nice(), then 10 would be reasonable.

File: lang/wasm_alien_thread_runner.cc (hunk 2 above)
Comment (tchaikov) [reply lang/wasm_alien_thread_runner.cc:20]: yeah, the reason why `ShardedWorkQueue` uses `try_acquire_for()` is get it waked up for checking if the thread pool is stopped or not. in our case, an `std::optional<>` or `std::unique_ptr<>` would serve the purpose better. as Avi puts, the nullopt or an empty pointer would be a `sentinel`. i'd suggest use an `optional<>`, as `task_queue::pop_front()` already returns an `optional<>`.

File: main.cc (hunk 4 above)
Comment (tchaikov) [reply main.cc:1010]: nit, no need to initialize the `shared_ptr` with nullptr. it's already empty if created with the default ctor.

File: test/boost/wasm_alloc_test.cc [hunk 6]
```diff
@@ -98,6 +99,7 @@ SEASTAR_TEST_CASE(test_allocation_failures) {
         // Check that we can actually throw errors both during compilation and during execution
         BOOST_CHECK(errors_during_compilation > 0);
         BOOST_CHECK(errors_during_execution > 0);
+        alien_runner.stop();
```
Comment (tchaikov) [inline test/boost/wasm_alloc_test.cc:102]: nit, might need to use `auto stop_alien_runner = deferred_stop(alien_runner);` right after it is defined? more idiomatic this way.

File: lang/wasm_alien_thread_runner.cc [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+                work_item->func();
+            } else if (_stopping) {
+                break;
+            }
+        }
+    })
+{ }
+
+alien_thread_runner::~alien_thread_runner() {
+    thread.join();
```
Comment (tchaikov) [inline lang/wasm_alien_thread_runner.cc:72]: how about `assert(pending_queue.size() == 0`? if we don't call `stop()` in the dtor, we might need to make sure the user of `alien_thread_runner` class does this. or, we can do so in the dtor of `task_queue`.

File: lang/wasm_alien_thread_runner.hh [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+    std::optional<wasm_compile_task> pop_front();
+    void stop();
+    void push_back(wasm_compile_task work_item);
+    size_t size() { return _pending.size(); }
+};
+
+class alien_thread_runner {
+    std::thread thread;
+    bool _stopping = false;
+    task_queue pending_queue;
```
Comment (tchaikov) [inline lang/wasm_alien_thread_runner.hh:47]: might want to add `_` prefix to the private member variables to be more consistent with the rest of this project.

File: lang/wasm.cc [hunk 9]
```diff
@@ -7,6 +7,7 @@
  */
 
 #include "wasm.hh"
+#include "seastar/coroutine/exception.hh"
```
[the remark this answers is not in the document]
Comment (wmitros) [reply lang/wasm.cc:10]: Ok

File: lang/wasm_alien_thread_runner.cc (hunk 3 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc:82]: Ok

File: main.cc (hunk 4 above)
Comment (wmitros) [reply main.cc:1010]: Ok

File: lang/wasm_alien_thread_runner.hh (hunk 8 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.hh:47]: Yes, I'm surprised I missed that

**Comment by wmitros** [comment]
I fixed some comments in the rebase (the answered ones). 

Regarding the remaining comments, I think we should maybe consider handling the stopping of the alien runner less gently. In my manual tests I saw that we finish all compilations before stopping the runner anyway (even if they take a long time), so the stop() method doesn't really do anything other than preventing further tasks from being added, which probably shouldn't happen if we we're already requested to stop.

One more issue that I noticed with this PR is that now, when all compilations are performed on one thread, for each UDF we perform the same compilation again and again for each shard. Instead, we could compile it once and cache it, and then copy the result for the following calls. The runtime that we're using actually has a feature of caching modules, but it uses `mmap` for allocating memory for them, so I disabled them by default. We can consider using, or just implement our our cache.
Either way, we can probably do it as a follow up.

File: cql3/statements/create_aggregate_statement.cc (hunk 1 above)
Comment (wmitros) [reply cql3/statements/create_aggregate_statement.cc:25]: I examined the new futures again, but couldn't find any races that could be caused by them. A potential race that looked like it might appear was between replacing and dropping the UDF, but it looks like we handle it well enough already.

File: lang/wasm_alien_thread_runner.cc (hunk 2 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc]: Ok, I tried to use the approach with a condition variable and an `optional` sentinel in the rebase

File: main.cc (hunk 5 above)
Comment (wmitros) [reply main.cc:1152]: The code structure - similarly to the instance cache - the runner's only used for initialization when parsing system tables (which happens later in the scylla_main()) and when executing queries (which is started even later in scylla_main()).
We could add the runner(and cache) to the query_processor constructor, but the wasm parameters are sill optional (UDFs are experimental) and it's already taking a lot of parameters so I don't know if we want it. We could also add some checks when trying to use them (alien runner and cache), but it seems like it's simpler to just keep the order of operations correct.

File: test/boost/wasm_alloc_test.cc (hunk 6 above)
Comment (wmitros) [reply test/boost/wasm_alloc_test.cc]: Looks like the `deferred_stop` only works with `stop()` methods that return a future, so it can't be used easily here, but this stops being a problem anyway in the new approach.

File: lang/wasm_alien_thread_runner.cc (hunk 7 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc]: I moved the stop to the dtor in the rebase

**Comment by wmitros** [comment]
I addressed the review comments in the rebase. The stopping code is now only present in the destructor of the `alien_thread_runner`. @avikivity @tchaikov please take a look

File: main.cc (hunk 5 above)
Comment (avikivity) [reply main.cc:1152]: I think it's nicer to pass it as a constructor parameter, it eliminates the question about use-before-set. It's an idiom in C++, pass your dependencies up-front.

UDF will not be experimental forever (in fact, I hope we can move them out of experimental soon).

File: lang/wasm_alien_thread_runner.hh [hunk 10]
```diff
@@ -0,0 +1,52 @@
...
+    std::function<void()> func;
+    seastar::promise<rust::Box<wasmtime::Module>>& done;
+    int shard;
+};
+
+struct task_queue {
+    std::mutex _mut;
+    std::condition_variable _cv;
+    static constexpr unsigned QUEUE_SIZE = 128;
+    std::queue<std::optional<wasm_compile_task>> _pending;
```
Comment (avikivity) [inline lang/wasm_alien_thread_runner.hh:34]: I can see this morphing to be a unique_ptr<some_base_class_type> later on, but no need to change it now.

File: lang/wasm_alien_thread_runner.cc [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+    std::optional<wasm_compile_task> work_item = std::move(_pending.front());
+    _pending.pop();
+    return work_item;
+}
+
+void task_queue::push_back(std::optional<wasm_compile_task> work_item) {
+    std::unique_lock<std::mutex> lock(_mut);
+    if (work_item && _pending.size() >= QUEUE_SIZE) {
+        seastar::alien::run_on(seastar::engine().alien(), work_item->shard, [&done = work_item->done] {
+            done.set_exception(std::runtime_error("alien_thread_runner queue is full"));
```
Comment (avikivity) [inline lang/wasm_alien_thread_runner.cc:32]: Could this cause use to fail to load?

Consider 150 shards trying to compile a UDF in parallel. The last 30 will fail. How do we recover from this?

Better to have an unbounded queue.

File: lang/wasm_alien_thread_runner.cc [hunk 12]
```diff
@@ -0,0 +1,75 @@
...
+    })
+{ }
+
+alien_thread_runner::~alien_thread_runner() {
+    _pending_queue.push_back(std::nullopt);
+    _thread.join();
+}
+
+void alien_thread_runner::submit(seastar::promise<rust::Box<wasmtime::Module>>& p, std::function<rust::Box<wasmtime::Module>()> f) {
+    std::function<void()> packaged([f=std::move(f), &p, &alien = seastar::engine().alien(), shard = seastar::this_shard_id()] () mutable {
```
Comment (avikivity) [inline lang/wasm_alien_thread_runner.cc:60]: spaces around `=`.

File: lang/wasm_alien_thread_runner.cc [hunk 13]
```diff
@@ -0,0 +1,75 @@
...
+        try {
+            rust::Box<wasmtime::Module> mod = f();
+            seastar::alien::run_on(alien, shard, [&p, mod = std::move(mod)] () mutable {
+                p.set_value(std::move(mod));
+            });
+        } catch (const std::exception& e) {
```
Comment (avikivity) [inline lang/wasm_alien_thread_runner.cc:66]: `catch (...)`

File: lang/wasm.cc [hunk 14]
```diff
@@ -227,8 +235,12 @@ void precompile(context& ctx, const std::vector<sstring>& arg_names, std::string
         create_func(*inst, *store, ctx.function_name);
         ctx.module.value()->release();
     } catch (const rust::Error& e) {
-        throw wasm::exception(e.what());
+        ex = std::make_exception_ptr(wasm::exception(format("Compilation failed: {}", e.what())));
+    }
+    if (ex) {
+        co_await coroutine::return_exception_ptr(std::move(ex));
     }
+    co_return;
```
Comment (tchaikov) [inline lang/wasm.cc:243]: nit, no need to call `co_return` explicitly here.

File: lang/wasm_alien_thread_runner.cc [hunk 15]
```diff
@@ -0,0 +1,75 @@
...
+
+#include "lang/wasm.hh"
+#include "lang/wasm_alien_thread_runner.hh"
+
+using namespace std::chrono_literals;
+
+namespace wasm {
+
+std::optional<wasm_compile_task> task_queue::pop_front() {
+    std::unique_lock<std::mutex> lock(_mut);
```
Comment (tchaikov) [inline lang/wasm_alien_thread_runner.cc:21]:
```suggestion
    std::unique_lock lock(_mut);
```

as the compiler is able to deduce the template parameter.

File: lang/wasm_alien_thread_runner.hh [hunk 16]
```diff
@@ -0,0 +1,52 @@
...
+public:
+    std::optional<wasm_compile_task> pop_front();
+    void push_back(std::optional<wasm_compile_task> work_item);
+    size_t size() { return _pending.size(); }
+};
+
+class alien_thread_runner {
+    std::thread _thread;
+    task_queue _pending_queue;
```
Comment (tchaikov) [inline lang/wasm_alien_thread_runner.hh:43]: probably need to put `_pending_queue` before `_thread`, so `_pending_queue` is initialized before `_thread`, as in the constructor of `alien_thread_runner`, it initializes `_thread` using `_pending_queue`.

File: lang/wasm_alien_thread_runner.hh [hunk 17]
```diff
@@ -0,0 +1,52 @@
...
+
+#include "rust/cxx.h"
+#include "rust/wasmtime_bindings.hh"
+
+namespace wasm {
+
+struct wasm_compile_task {
+    std::function<void()> func;
+    seastar::promise<rust::Box<wasmtime::Module>>& done;
+    int shard;
```
Comment (tchaikov) [inline lang/wasm_alien_thread_runner.hh:27]: might want to use `unsigned`. to be consistent with the function signature of `seastar::alien::run_on()` . FWIW, we have `using shard_id = unsigned;`, and use `unsigned` and `shard_id` interchangeably.   but, in general, we don't use a signed int for shard.

File: main.cc (hunk 5 above)
Comment (wmitros) [reply main.cc:1152]: I did not add this in the last rebase, but I assume we would like to do this also for the instance cache and also wasmtime::Engine (which is currently in the `database`)? If so, maybe I'll just make a follow-up, which moves them all to the constructor

File: lang/wasm_alien_thread_runner.cc (hunk 11 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc]: Ok

File: lang/wasm_alien_thread_runner.cc (hunk 12 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc]: Ok

File: lang/wasm_alien_thread_runner.cc (hunk 13 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc]: Ok

File: lang/wasm.cc (hunk 14 above)
Comment (wmitros) [reply lang/wasm.cc]: Ok

File: lang/wasm_alien_thread_runner.cc (hunk 15 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.cc]: Ok

File: lang/wasm_alien_thread_runner.hh (hunk 17 above)
Comment (wmitros) [reply lang/wasm_alien_thread_runner.hh]: Makes sense

File: configure.py [hunk 18]
```diff
@@ -1015,6 +1015,7 @@ def find_headers(repodir, excluded_dirs):
                 'mutation_writer/feed_writers.cc',
                 'lang/lua.cc',
                 'lang/wasm.cc',
+                'lang/wasm_alien_thread_runner.cc',
```
[the remark this answers is not in the document]
Comment (wmitros) [reply configure.py:1023]: Sure. I think the cmake build was not yet synced with the `lang` directory when I first posted the PR, but now the cmake should be kept up to date with each new PR

**Comment by wmitros** [comment]
I rebased on top of master and addressed the last review comments (except [one](https://github.com/scylladb/scylladb/pull/13051#discussion_r1127898722))

File: configure.py (hunk 18 above)
[the remark this answers is not in the document]
Comment (tchaikov) [reply configure.py:1023]: yeah, it's been under active development. this file was actually added in last week.

File: lang/alien_task_queue.hh [hunk 19]
```diff
@@ -0,0 +1,16 @@
...
+ */
+
+#pragma once
+
+#include "lang/wasm.hh"
+namespace wasm {
+    class alien_task_queue {
+        
+    }
+}
```
Comment (tchaikov) [inline lang/alien_task_queue.hh:16]: is this file a leftover?

Comment (wmitros) [reply lang/alien_task_queue.hh]: Yes, sorry for that

File: lang/wasm_alien_thread_runner.hh [hunk 20]
```diff
@@ -0,0 +1,52 @@
...
+struct wasm_compile_task {
+    seastar::noncopyable_function<void()> func;
+    seastar::promise<rust::Box<wasmtime::Module>>& done;
+    unsigned shard;
+};
+
+struct task_queue {
+    std::mutex _mut;
+    std::condition_variable _cv;
+    static constexpr unsigned QUEUE_SIZE = 128;
```
Comment (tchaikov) [inline lang/wasm_alien_thread_runner.hh:34]: it seems we don't use this variable anymore after switching to unbounded queue and using the combination of `mutex` and `condition_variable` for coordinating the consumer and producer of the queue.

**Review by tchaikov — APPROVED** [review]

**Comment by wmitros** [comment]
@avikivity I addressed all suggestions (maybe apart from https://github.com/scylladb/scylladb/pull/13051#discussion_r1127898722) and we got one LGTM, do you have any more comments?

File: lang/wasm_alien_thread_runner.hh (hunk 20 above)
Comment (avikivity) [reply lang/wasm_alien_thread_runner.hh]: btw, an unbounded queue has its own obvious problems. But I think it cannot grow in an unbounded way because Raft will serialize schema changes.

File: main.cc (hunk 5 above)
Comment (avikivity) [reply main.cc:1152]: ok for a follow-up.

File: lang/wasm_alien_thread_runner.hh (hunk 16 above)
Comment (avikivity) [reply lang/wasm_alien_thread_runner.hh:41]: Good catch.
