### PR TITLE
token_metadata: keep the set of normal token owners as a member

### LINKED ISSUE #11128: token_metadata can use a std::unordered_set<inet_address> member to speed up get_all_endpoints and count_normal_token_owners
Today `get_all_endpoints` and `count_normal_token_owners` need to traverse `_token_to_endpoint_map` to calculate the unique set of endpoints. But this set can be easily kept up-to-date by functions that change `_token_to_endpoint_map`, most importantly, `update_normal_tokens`.

I'm not sure why `std::set` (vs. `std::unordered_set`) is used in `count_normal_token_owners`, by the way.
it returns its size so the internal order doesn't matter, and insertion to `std::set` is O(log(n)) in contrast to O(1) for unordered_set...

### LINKED ISSUE #11146: locator::token_metadata_impl::get_all_endpoints stalls 10ms
```
Test: performance_regression_test.PerformanceRegressionTest.test_latency_mixed_with_nemesis
Test start time: 2022-07-27 11:48:33.486992
Test id: 7d18efab-9db2-4351-9179-6e907f8aca7e
Scylla Server Version: 5.1.dev.20220724.f46b207472a3 with build-id d947aaccafa94647f71c1c79326eb88840c5b6d2
Setup Details:

    ami_id_db_scylla: ami-01315ab72a1b3951d
    append_scylla_args: --blocked-reactor-notify-ms 5
    cluster_backend: aws
    instance_type_db: i3.2xlarge
    instance_type_loader: c5.2xlarge
    instance_type_monitor: t3.large
    region_name: ['us-east-1']
```
```
Links:

    [Build URL](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/for_xemul/job/latency-with-nemesis-rbno-control/33/)
    [Download "Per server metrics nemesis" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-overview-20220727_163427-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [Download "Overview metrics" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_163633-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)

Logs:

    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_114217.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_114217.tar.gz)
    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_163359.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_163359.tar.gz)
    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_164808.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_164808.tar.gz)
    [prometheus - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_170317.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/prometheus_snapshot_20220727_170317.tar.gz)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_113134-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_113134-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-overview-20220727_112917-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_112917/grafana-screenshot-overview-20220727_112917-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_162226-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_162226-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-overview-20220727_162022-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_162022/grafana-screenshot-overview-20220727_162022-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_163633-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_163633-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-overview-20220727_163427-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_163427/grafana-screenshot-overview-20220727_163427-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_165125-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-latency-with-nemesis-rbno-control-scylla-per-server-metrics-nemesis-20220727_165125-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [grafana - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-overview-20220727_164920-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_164920/grafana-screenshot-overview-20220727_164920-perf-latency-nemesis-perf-job-monitor-node-7d18efab-1.png)
    [db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/db-cluster-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/db-cluster-7d18efab.tar.gz)
    [loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/loader-set-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/loader-set-7d18efab.tar.gz)
    [monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/monitor-set-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/monitor-set-7d18efab.tar.gz)
    [sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/sct-runner-7d18efab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d18efab-9db2-4351-9179-6e907f8aca7e/20220727_170402/sct-runner-7d18efab.tar.gz)

```

```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:772
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:791
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1366
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1108
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1125
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1349
?? ??:0
std::__detail::_Mod_range_hashing::operator()(unsigned long, unsigned long) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:430
 (inlined by) std::__detail::_Hash_code_base<gms::inet_address, gms::inet_address, std::__detail::_Identity, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>::_M_bucket_index(unsigned long, unsigned long) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:1233
 (inlined by) std::_Hashtable<gms::inet_address, gms::inet_address, std::allocator<gms::inet_address>, std::__detail::_Identity, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_bucket_index(unsigned long) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable.h:795
 (inlined by) std::pair<std::__detail::_Node_iterator<gms::inet_address, true, false>, bool> std::_Hashtable<gms::inet_address, gms::inet_address, std::allocator<gms::inet_address>, std::__detail::_Identity, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_insert<gms::inet_address const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<gms::inet_address, false> > > >(gms::inet_address const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<gms::inet_address, false> > > const&, std::integral_constant<bool, true>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable.h:2103
 (inlined by) std::__detail::_Insert_base<gms::inet_address, gms::inet_address, std::allocator<gms::inet_address>, std::__detail::_Identity, std::equal_to<gms::inet_address>, std::hash<gms::inet_address>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::insert(gms::inet_address const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:844
 (inlined by) _Hashtable<boost::iterators::transform_iterator<boost::range_detail::select_second_const<std::unordered_map<dht::token, gms::inet_address> >, std::__detail::_Node_const_iterator<std::pair<const dht::token, gms::inet_address>, false, true> > > at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable.h:1148
 (inlined by) _Hashtable<boost::iterators::transform_iterator<boost::range_detail::select_second_const<std::unordered_map<dht::token, gms::inet_address> >, std::__detail::_Node_const_iterator<std::pair<const dht::token, gms::inet_address>, false, true> > > at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable.h:565
 (inlined by) unordered_set<boost::iterators::transform_iterator<boost::range_detail::select_second_const<std::unordered_map<dht::token, gms::inet_address> >, std::__detail::_Node_const_iterator<std::pair<const dht::token, gms::inet_address>, false, true> > > at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unordered_set.h:171
 (inlined by) std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> > boost::copy_range<std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, boost::range_detail::select_second_const_range<std::unordered_map<dht::token, gms::inet_address, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<std::pair<dht::token const, gms::inet_address> > > > >(boost::range_detail::select_second_const_range<std::unordered_map<dht::token, gms::inet_address, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<std::pair<dht::token const, gms::inet_address> > > > const&) at /usr/include/boost/range/iterator_range_core.hpp:842
 (inlined by) locator::token_metadata_impl::get_all_endpoints() const at ./locator/token_metadata.cc:272
 (inlined by) locator::token_metadata::get_all_endpoints() const at ./locator/token_metadata.cc:1214
locator::everywhere_replication_strategy::calculate_natural_endpoints(dht::token const&, locator::token_metadata const&) const at ./locator/everywhere_replication_strategy.cc:23
operator() at ./repair/repair.cc:1586
void std::__invoke_impl<void, repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(std::__invoke_other, repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::__invoke_result<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>::type std::__invoke<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
 (inlined by) decltype(auto) std::__apply_impl<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30, std::tuple<>>(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1858
 (inlined by) decltype(auto) std::apply<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30, std::tuple<> >(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1869
 (inlined by) seastar::future<void> seastar::futurize<void>::apply<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2113
 (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
 (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30>(seastar::thread_attributes, repair_service::do_decommission_removenode_with_repair(seastar::lw_shared_ptr<locator::token_metadata const>, gms::inet_address, seastar::shared_ptr<node_ops_info>)::$_30&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
 (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299
```

db-cluster-7d18efab/perf-latency-nemesis-perf-job-db-node-7d18efab-6/messages.log:2022-07-27T16:15:37+00:00  perf-latency-nemesis-perf-job-db-node-7d18efab-6 !INFO    | scylla[6551]: Reactor stalled for 10 ms on shard 0. Backtrace: 0x4bbb9d2 0x4bba630 0x4bbb8e0 0x7fd365262a1f 0x2face49 0x2f5caff 0x36ca29f 0x36c89c3 0x4e3a0e1

### PR DESCRIPTION
**Pull request by bhalevy**
token_metadata: impl: keep the set of normal token owners as a member

We don't need to recalculate the unique set of normal token
everytime we change `_token_to_endpoint_map`.
Similarly, this doesn't have to be done in `get_all_endpoints`.

Instead we can maintain it inexpensively in
`remove_endpoint`, and let `count_normal_token_owners`
just return its size and `get_all_endpoints` just return
the saved set.

Closes #11128
Fixes #11146

### CODE REVIEW

**Comment by bhalevy** [comment]
c80c532abd: rebased to pass CI

**Comment by bhalevy** [comment]
given #11146, we should let update_normal_token yield

**Comment by bhalevy** [comment]
@asias ping, please review

File: locator/token_metadata.cc [hunk 1]
```diff
@@ -367,7 +366,8 @@ future<token_metadata_impl> token_metadata_impl::clone_only_token_map(bool clone
         return do_for_each(_token_to_endpoint_map, [&ret] (const auto& p) {
             ret._token_to_endpoint_map.emplace(p);
         }).then([this, &ret] {
-            ret._nr_normal_token_owners = _nr_normal_token_owners;
+            ret._normal_token_owners = _normal_token_owners;
+        }).then([this, &ret] {
```
Comment (asias) [inline locator/token_metadata.cc:370]: Any reason to add the then here?

File: locator/token_metadata.cc [hunk 2]
```diff
@@ -913,15 +913,16 @@ future<> token_metadata_impl::update_pending_ranges(
...
-    return _nr_normal_token_owners;
+    return _normal_token_owners.size();
 }
 
-void token_metadata_impl::update_normal_token_owners() {
+future<> token_metadata_impl::update_normal_token_owners() {
     std::unordered_set<inet_address> eps;
     for (auto [t, ep]: _token_to_endpoint_map) {
         eps.insert(ep);
+        co_await coroutine::maybe_yield();
```
Comment (asias) [inline locator/token_metadata.cc:923]: This is going to make backport harder since we do not have coroutine::maybe_yield in 2021.1.

File: locator/token_metadata.cc (hunk 1 above)
Comment (bhalevy) [reply locator/token_metadata.cc:370]: The idea was to allow yielding, but it turns out we don't check `need_preempt` in .then when the future is ready.
so the reason is moot.

Comment (asias) [reply locator/token_metadata.cc:370]: I see.

File: locator/token_metadata.cc (hunk 2 above)
Comment (bhalevy) [reply locator/token_metadata.cc:923]: 2022.1 would be an easy target for backporting
but I'm not sure if the issue is severe enough to warrant backporting to 2021.1
We can deal with it if and when this is backported there.

See discussion in https://github.com/scylladb/scylla-enterprise/issues/2194#issuecomment-1202046266
There are quite a few optimizations around token_metadata (and particularly effective_replication_map) that aren't feasible for backporting there.

Comment (asias) [reply locator/token_metadata.cc:923]: OK.

**Review by asias — APPROVED** [review]

File: locator/token_metadata.cc (hunk 1 above)
Comment (avikivity) [reply locator/token_metadata.cc:370]: So why do it?

**Comment by avikivity** [comment]
Let's have a new rule that says that if a patch fixes a non-bug issue ("X should do Y"), then we close it with Closes #vwxyz instead of Fixes #vwxyz, so there is less work to determine if it needs to be backported.

File: locator/token_metadata.cc [hunk 3]
```diff
@@ -50,9 +50,9 @@ class token_metadata_impl final {
      */
     // FIXME: have to be BiMultiValMap
     std::unordered_map<token, inet_address> _token_to_endpoint_map;
-    // Track the number of nodes in _token_to_endpoint_map. Need to update
-    // _nr_normal_token_owners when _token_to_endpoint_map is updated.
-    size_t _nr_normal_token_owners;
+
+    // Track the unique set of nodes in _token_to_endpoint_map
+    std::unordered_set<inet_address> _normal_token_owners;
```
Comment (avikivity) [inline locator/token_metadata.cc:55]: Some things we can consider (not proposing for now):
 - switch to abseil btree containers for fewer allocations/branches
 - store all node vectors in a few larger vector and return std::span<>s to it
 - start storing node* instead of inet_address, pointing to a vector<node> i token_metadata

The last two require that we hold token_metadata_ptr in the read/write executors, but that's easy.

**Comment by avikivity** [comment]
I don't see a CI run, what happened?

**Review by avikivity — APPROVED** [review]

File: locator/token_metadata.cc (hunk 1 above)
Comment (bhalevy) [reply locator/token_metadata.cc:370]: In hindsight it's unneeded. I can remove it in v2.
(No CI ran apparently so pushing a new version should trigger one)

File: locator/token_metadata.cc (hunk 3 above)
Comment (bhalevy) [reply locator/token_metadata.cc:55]: I think that the node instances belong elsewhere, not in token_metadata, maybe in topology.
and then they can be reference by a shared ptr until they are removed from the cluster.

**Comment by bhalevy** [comment]
> Let's have a new rule that says that if a patch fixes a non-bug issue ("X should do Y"), then we close it with Closes #vwxyz instead of Fixes #vwxyz, so there is less work to determine if it needs to be backported.

Makes sense

> I don't see a CI run, what happened?

Good question.  I'll push v2 (without the extraneous .then continuation) to trigger one.

**Comment by bhalevy** [comment]
In v3 (0dfd92d0b3):
- rebased + retested
- updated git log message with "Closes" rather than "Fixes"
- deleted the extraneous `.then` continuation discussed in https://github.com/scylladb/scylladb/pull/11158#discussion_r935159907

**Comment by avikivity** [comment]
Looks like CI is running.
