### PR TITLE
Apply hard limit to partition range vectors in secondary index queries

### LINKED ISSUE #18536: Reserving capacity for large partition_range_vector might stall
Seen stalls of up to over 100 ms in the field coming from this code path:
```
seastar::memory::allocate_large(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1342
 (inlined by) seastar::memory::allocate(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:1403
operator new(unsigned long) at ./build/release/seastar/./seastar/src/core/memory.cc:2065
std::__new_allocator<nonwrapping_interval<dht::ring_position> >::allocate(unsigned long, void const*) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/new_allocator.h:137
 (inlined by) std::allocator<nonwrapping_interval<dht::ring_position> >::allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/allocator.h:188
 (inlined by) std::allocator_traits<std::allocator<nonwrapping_interval<dht::ring_position> > >::allocate(std::allocator<nonwrapping_interval<dht::ring_position> >&, unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/alloc_traits.h:464
 (inlined by) std::_Vector_base<nonwrapping_interval<dht::ring_position>, std::allocator<nonwrapping_interval<dht::ring_position> > >::_M_allocate(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:378
 (inlined by) std::vector<nonwrapping_interval<dht::ring_position>, std::allocator<nonwrapping_interval<dht::ring_position> > >::reserve(unsigned long) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/vector.tcc:79
 (inlined by) operator() at ./cql3/statements/select_statement.cc:1303
 (inlined by) seastar::future<boost::outcome_v2::basic_result<std::tuple<std::vector<nonwrapping_interval<dht::ring_position>, std::allocator<nonwrapping_interval<dht::ring_position> > >, seastar::lw_shared_ptr<service::pager::paging_state const> >, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> > seastar::futurize<seastar::future<boost::outcome_v2::basic_result<std::tuple<std::vector<nonwrapping_interval<dht::ring_position>, std::allocator<nonwrapping_interval<dht::ring_position> > >, seastar::lw_shared_ptr<service::pager::paging_state const> >, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception, exceptions::rate_limit_exception>, utils::exception_container_throw_policy> > >::invoke<cql3::statements::indexed_table_select_statement::find_index_partition_ranges(cql3::query_processor&, service::query_state&, cql3::query_options const&) const::$_20&, seastar::shared_ptr<cql_transport::messages::result_message::rows> >(cql3::statements::indexed_table_select_statement::find_index_partition_ranges(cql3::query_processor&, service::query_state&, cql3::query_options const&) const::$_20&, seastar::shared_ptr<cql_transport::messages::result_message::rows>&&) at ././seastar/include/seastar/core/future.hh:2147
 (inlined by) auto seastar::futurize_invoke<cql3::statements::indexed_table_select_statement::find_index_partition_ranges(cql3::query_processor&, service::query_state&, cql3::query_options const&) const::$_20&, seastar::shared_ptr<cql_transport::messages::result_message::rows> >(cql3::statements::indexed_table_select_statement::find_index_partition_ranges(cql3::query_processor&, service::query_state&, cql3::query_options const&) const::$_20&, seastar::shared_ptr<cql_transport::messages::result_message::rows>&&) at ././seastar/include/seastar/core/future.hh:2178
```

```
future<coordinator_result<std::tuple<dht::partition_range_vector, lw_shared_ptr<const service::pager::paging_state>>>>
indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
                                             service::query_state& state,
                                             const query_options& options) const
{
    using value_type = std::tuple<dht::partition_range_vector, lw_shared_ptr<const service::pager::paging_state>>;
    auto now = gc_clock::now();
    auto timeout = db::timeout_clock::now() + get_timeout(state.get_client_state(), options);
    return read_posting_list(qp, options, get_limit(options), state, now, timeout, false).then(utils::result_wrap(
            [this, now, &options] (::shared_ptr<cql_transport::messages::result_message::rows> rows) {
        auto rs = cql3::untyped_result_set(rows);
        dht::partition_range_vector partition_ranges;
        partition_ranges.reserve(rs.size());
```

Turning `dht::partition_range_vector` into a chunked vector should prevent those stalls and have zero impact on the common path.

### PR DESCRIPTION
**Pull request by ndragazis**
Secondary index queries fetch partition keys from the index view and store them in an `std::vector`. The vector size is currently limited by the user's page size and the page memory limit (1MiB). These are not enough to prevent large contiguous allocations (which can lead to stalls).

This series introduces a hard limit to the vector size to ensure it does not exceed the allocator's preferred max contiguous allocation size (128KiB). With the size of each element being 120 bytes, this allows for 1092 partition keys. The limit was set to 1000. Any partitions above this limit are discarded.

Discarding partitions breaks the querier cache on the replicas, causing a performance regression, as can be seen from the following measurements:
```
* Cluster: 3 nodes (local Docker containers), 1 vCPU, 4GB memory, dev mode
* Schema:
  CREATE KEYSPACE ks WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'datacenter1': '3'} AND durable_writes = true AND tablets = {'enabled': false};
  CREATE TABLE ks.t1 (pk1 int, pk2 int, ck int, value int, PRIMARY KEY ((pk1, pk2), ck));
  CREATE INDEX t1_pk2_idx ON ks.t1(pk2); 
* Query: CONSISTENCY LOCAL_QUORUM; SELECT * FROM ks.t1 where pk2 = 1;

+------------+-------------------+-------------------+
|  Page Size |      Master       |   Vector Limit    |
+============+===================+===================+
|            |   Latency (sec)   |   Latency (sec)   |
+------------+-------------------+-------------------+
|     100    |  5.80 ± 0.13      |  5.64 ± 0.10      |
+------------+-------------------+-------------------+
|    1000    |  4.77 ± 0.07      |  4.62 ± 0.06      |
+------------+-------------------+-------------------+
|    2000    |  4.67 ± 0.07      |  5.13 ± 0.03      |
+------------+-------------------+-------------------+
|    5000    |  4.82 ± 0.09      |  6.25 ± 0.06      |
+------------+-------------------+-------------------+
|   10000    |  4.89 ± 0.36      |  7.52 ± 0.13      |
+------------+-------------------+-------------------+
|     -1     |  4.90 ± 0.67      |  4.79 ± 0.33      |
+------------+-------------------+-------------------+
```
We expect this to be fixed with adaptive paging in a future PR. Until then, users can avoid regressions by adjusting their page size.

Additionally, this series changes the `untyped_result_set` to store rows in a `chunked_vector` instead of an `std::vector`, similarly to the `result_set`. Secondary index queries use an `untyped_result_set` to store the raw result from the index view before processing. With 1MiB results, the `std::vector` would cause a large allocation of this magnitude. 

Finally, a unit test is added to reproduce the bug.

Fixes #18536.

The PR fixes stalls of up to 100ms, but there is an easy workaround: adjust the page size. No need to backport.

### CODE REVIEW

File: cql3/untyped_result_set.hh [hunk 1]
```diff
@@ -154,7 +154,7 @@ class result_set;
 class untyped_result_set {
 public:
     using row = untyped_result_set_row;
-    using rows_type = std::vector<row>;
+    using rows_type = utils::chunked_vector<row>;
```
Comment (avikivity) [inline cql3/untyped_result_set.hh:157]: untyped_result_set is not performance sensitive, so we don't need to worry about performance here.

File: cql3/statements/select_statement.cc [hunk 2]
```diff
@@ -1400,12 +1400,16 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
     using value_type = std::tuple<dht::partition_range_vector, lw_shared_ptr<const service::pager::paging_state>>;
     auto now = gc_clock::now();
     auto timeout = db::timeout_clock::now() + get_timeout(state.get_client_state(), options);
+    bool is_paged = options.get_page_size() >= 0;
+    size_t max_vector_size = is_paged
+            ? current_allocator().preferred_max_contiguous_allocation() / sizeof(dht::partition_range_vector::value_type)
+            : std::numeric_limits<size_t>::max();
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:1406]: It's somehow wrong that we derive such an important quantity from two unrelated constants. If ring_position changes size (hopefully in the downward direction), the page size for indexing will increase.

A better way is to set it to 1000 and static_assert that such a vector won't cause a large allocation. This way it won't change, and if the size of ring_position grows, someone will have to make a conscious decision to reduce it.


In the future I'd like to make it adapt to actual conditions.

File: cql3/statements/select_statement.cc [hunk 3]
```diff
@@ -1404,9 +1404,20 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
...
+    std::unique_ptr<query_options> paging_adjusted_options = [&] () {
+        if (is_paged && _schema->clustering_key_size() == 0 && static_cast<size_t>(options.get_page_size()) > max_vector_size) {
+            // Result is guaranteed to contain one partition key per row.
+            // Limit the page size a priori.
+            auto internal_options = std::make_unique<cql3::query_options>(cql3::query_options(options));
+            internal_options.reset(new cql3::query_options(std::move(internal_options), options.get_paging_state(), max_vector_size));
+            return internal_options;
+        }
+        return std::unique_ptr<cql3::query_options>(nullptr);
+    }();
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:1416]: I'm confused about this, how do single-row partitions in the base table affect indexing?

File: test/boost/secondary_index_test.cc [hunk 4]
```diff
@@ -2006,4 +2006,38 @@ SEASTAR_TEST_CASE(test_returning_failure_from_ghost_rows_deletion) {
...
+        }
+        auto qo = std::make_unique<cql3::query_options>(db::consistency_level::LOCAL_ONE, std::vector<cql3::raw_value>{},
+                cql3::query_options::specific_options{partitions, nullptr, {}, api::new_timestamp()});
+        const auto stats_before = memory::stats();
+        const memory::scoped_large_allocation_warning_threshold _{allocation_threshold + 1};
+        shared_ptr<cql_transport::messages::result_message> msg = co_await e.execute_cql("SELECT * FROM t WHERE c = 1;", std::move(qo));
+        const auto stats_after = memory::stats();
+
+        assert_that(msg).is_rows().is_not_empty();
+        BOOST_REQUIRE_EQUAL(stats_before.large_allocations(), stats_after.large_allocations());
```
[the remark this answers is not in the document]
Comment (ndragazis) [reply test/boost/secondary_index_test.cc:2039]: > Please move this test until after the fix to preserve bisectability (alternatively: start with BOOST_REQUIRE_LT to prove the problem is there, and adjust it to EQUAL in the patch that fixes it.

Ack.

> How stable is the test? If some background work generates a large allocation, it will fail once in a while.

It didn't fail after 1000 runs. If such a background work exists, is it not a bug?

To mitigate this, we could increase the threshold to something larger, say, 512KiB. This can be triggered with 5000 partitions.

File: cql3/untyped_result_set.hh (hunk 1 above)
Comment (ndragazis) [reply cql3/untyped_result_set.hh:157]: I'm not sure I follow this one. A stall may not be important for the task that triggers it, but it hinders all other tasks running on the same reactor, whether they are performance-sensitive or not.

Also, notice that we don't reserve its memory upfront, so we may end up with lots of reallocations and data copies. For example, if I increase the page size to 10,000 in my unit test, and I keep the warning threshold to 128KiB, I get 3 extra large allocation warnings: 160KiB, 320KiB, 640KiB.

640 can definitely cause stalls. The stall in the issue was coming from a `partition_range_vector` constructed with page size 5000, which means at most 5000 partition keys, 120 bytes each -> 5000 * 120 = ~600 KiB.

File: cql3/statements/select_statement.cc (hunk 3 above)
Comment (ndragazis) [reply cql3/statements/select_statement.cc:1416]: With single-row partitions we can reduce the page size, as you suggested in the previous comment. That's because each index row will bring a distinct partition key.

File: cql3/statements/select_statement.cc (hunk 2 above)
Comment (ndragazis) [reply cql3/statements/select_statement.cc:1406]: > static_assert that such a vector won't cause a large allocation.

Ack, but it has to be a runtime check. `preferred_max_contiguous_allocation()` is not constexpr.

**Comment by ndragazis** [comment]
v2 Changelog:
* Adjust the the unit test to succeed both before and after the fix.
* Disable the unit test in "sanitize" mode (ASAN messes up with memory allocations).
* Increase threshold in unit test to 512KiB to filter out large allocations that may be caused by other internal operations.
* Wrap `paging_adjusted_options` with `do_with()` (fixes use-after-free bug).
* Hardcode the max vector size to 1000 instead of deriving it from the allocator's preferred max.
* Add runtime check with `on_fatal_internal_error()` to ensure that 1000 won't cause large allocations.

File: test/boost/secondary_index_test.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply test/boost/secondary_index_test.cc:2042]: > > Please move this test until after the fix to preserve bisectability (alternatively: start with BOOST_REQUIRE_LT to prove the problem is there, and adjust it to EQUAL in the patch that fixes it.
> 
> Ack.
> 
> > How stable is the test? If some background work generates a large allocation, it will fail once in a while.
> 
> It didn't fail after 1000 runs. If such a background work exists, is it not a bug?

No, we do have background workloads. Maybe cql_test_env is repeatable enough not to trigger it (or perhaps, the background workloads don't trigger any large allocations).


> 
> To mitigate this, we could increase the threshold to something larger, say, 512KiB. This can be triggered with 5000 partitions.

That will increase test time, especially in debug mode. Let's keep it as is for now and think of something if flakiness hits.

File: cql3/statements/select_statement.cc [hunk 5]
```diff
@@ -1400,12 +1401,26 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
     using value_type = std::tuple<dht::partition_range_vector, lw_shared_ptr<const service::pager::paging_state>>;
     auto now = gc_clock::now();
     auto timeout = db::timeout_clock::now() + get_timeout(state.get_client_state(), options);
+    bool is_paged = options.get_page_size() >= 0;
+    constexpr size_t MAX_PARTITION_RANGES = 1000;
+    // This check ensures that `partition_range_vector` won't cause a large allocation (see #18536).
+    // This is not a fatal error, but we treat it as such to ensure this won't go under the radar.
+    // If this fails, please adjust MAX_PARTITION_RANGES accordingly.
+    if(MAX_PARTITION_RANGES * sizeof(dht::partition_range_vector::value_type) > current_allocator().preferred_max_contiguous_allocation()) {
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:1409]: `if` has a following space in our code style.

File: cql3/statements/select_statement.cc [hunk 6]
```diff
@@ -1436,6 +1440,9 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
             last_dk = dk;
             auto range = dht::partition_range::make_singular(dk);
             partition_ranges.emplace_back(range);
+            if (partition_ranges.size() >= partition_ranges.capacity()) {
+                break;
+            }
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/statements/select_statement.cc:1469]: I reviewed too quickly and didn't consider that we're shrinking the input (the `continue` above). You're right.

We can go with this, but we need to acknowledge that dropping rows from the index query is bad and will make the following page less efficient. The replicas can resume a query that was paused on a page boundary, but if you drop rows, the next page will have to be queried from scratch.

Given this, your original approach of paging internally is better. Perhaps we should resurrect it.

You can try to reproduce the problem using tracing, when you restart a query after dropping rows you should see 

```
Found cached querier(s) for key {} but none matches the query range(s) {}
```

And if everything goes well and the paused query is resumed you'll see

```
Found cached querier for key {} and range(s) {}
```

But! I think you won't see either, since we don't extract the query cookie from paging_options, and instead we generate a new query each time. So we won't benefit from the complexity of internal paging until we improve query caching here. @denesb

File: cql3/statements/select_statement.cc [hunk 7]
```diff
@@ -1400,12 +1401,26 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
     using value_type = std::tuple<dht::partition_range_vector, lw_shared_ptr<const service::pager::paging_state>>;
     auto now = gc_clock::now();
     auto timeout = db::timeout_clock::now() + get_timeout(state.get_client_state(), options);
+    bool is_paged = options.get_page_size() >= 0;
+    constexpr size_t MAX_PARTITION_RANGES = 1000;
+    // This check ensures that `partition_range_vector` won't cause a large allocation (see #18536).
+    // This is not a fatal error, but we treat it as such to ensure this won't go under the radar.
+    // If this fails, please adjust MAX_PARTITION_RANGES accordingly.
+    if(MAX_PARTITION_RANGES * sizeof(dht::partition_range_vector::value_type) > current_allocator().preferred_max_contiguous_allocation()) {
+        on_fatal_internal_error(logger, seastar::format(
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:1410]: I thought a static_assert would work. A runtime fatal error is too much, we can just emit a warning.

File: cql3/statements/select_statement.cc [hunk 8]
```diff
@@ -1415,9 +1415,22 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
...
+            // Result is guaranteed to contain one partition key per row.
+            // Limit the page size a priori.
+            auto internal_options = std::make_unique<cql3::query_options>(cql3::query_options(options));
+            internal_options.reset(new cql3::query_options(std::move(internal_options), options.get_paging_state(), max_vector_size));
+            return internal_options;
+        }
+        return std::unique_ptr<cql3::query_options>(nullptr);
+    }();
+    return do_with(std::move(paging_adjusted_options), [&, max_vector_size](auto& paging_adjusted_options) {
+    // FIXME: Indent.
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:1429]: Please follow up (no need to do so in this series) with a coroutinization of this function, we should not be adding do_with:s.

**Comment by avikivity** [comment]
Looks good, sorry for causing confusion.

File: cql3/statements/select_statement.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (denesb) [reply cql3/statements/select_statement.cc:1469]: AFAIK we try to regenerate the paging cookie for the posting list queries (secondary index queries), but there is no guarantee we will be able to continue the previous page. We query 1000 keys from the index, then read these from the base table. We cut the page on the base table results, which may or may not match that of the posting list page.

**Comment by ndragazis** [comment]
## Measurements

@avikivity, @denesb, I measured the latency of some secondary index queries on a local 3-node cluster.

Setup:
* cluster: 3 nodes, 1 vcpu, 4G memory, dev mode
* schema: replication factor = 3, no tablets (secondary indexed not supported yet)
* query: indexed, selects all rows, QL = LOCAL_QUORUM
* 5 runs per measurement

Requirements:
* [simple_scylla_cluster_manager.py](https://github.com/scylladb/scylla-dev-utils/blob/master/simple_scylla_cluster_manager.py) to set up a local cluster
* custom [test scripts](https://github.com/ndragazis/scylladb/tree/perf-secondary-index) to create the table, fill it with data, run queries that retrieve the whole table with various page sizes, and print latency stats
* scylla braches for testing:
   - master (`2025.2.0~dev-0.20250207.2a9949475285`)
   - current PR: limited vector size of 1000 partition keys
   - previous PR with internal paging (https://github.com/scylladb/scylladb/pull/22254): internal page size of 1000

Steps:
1. Build scylla from desired branch.
2. Spin up the cluster:
    ```bash
    cd scylla-dev-utils/
    mkdir rundir && cd rundir
    ../simple_scylla_cluster_manager.py create-cluster -n3 -c1 -s -p /home/ndragazis/Documents/scylladb/git/scylladb
    ```
3. Find the IP of one of the nodes:
    ```bash
    ./simple_scylla_cluster_manager.py status | jq -r .[0].ip
    ```
4. Edit the IP in the test script.
5. Run the test script.

## Results

### Case 1: Small partition range vectors, no short reads

1,000 partitions, 100 rows per partition
<details>
<summary>Schema:</summary>

```sql
CREATE KEYSPACE ks WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'datacenter1': '3'} AND durable_writes = true AND tablets = {'enabled': false};

CREATE TABLE ks.t1 (
    pk1 int,
    pk2 int,
    ck int,
    value int,
    PRIMARY KEY ((pk1, pk2), ck)
) WITH CLUSTERING ORDER BY (ck ASC)  
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'IncrementalCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000    
    AND max_index_interval = 2048      
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99.0PERCENTILE'
   AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'};

CREATE INDEX t1_pk2_idx ON ks.t1(pk2);
```

</details>

```
+------------+-------------------+-------------------+-------------------+
|  Page Size |      Master       |   Vector Limit    |  Internal Paging  |
+============+===================+===================+===================+
|            |   Latency (sec)   |   Latency (sec)   |   Latency (sec)   |
+------------+-------------------+-------------------+-------------------+
|     100    |  4.06 ± 0.13      |  4.12 ± 0.16      |  4.15 ± 0.13      |
+------------+-------------------+-------------------+-------------------+
|    1000    |  2.90 ± 0.08      |  2.94 ± 0.06      |  2.94 ± 0.07      |
+------------+-------------------+-------------------+-------------------+
|    2000    |  2.72 ± 0.06      |  2.77 ± 0.05      |  2.76 ± 0.05      |
+------------+-------------------+-------------------+-------------------+
|    5000    |  2.63 ± 0.08      |  2.61 ± 0.08      |  2.67 ± 0.03      |
+------------+-------------------+-------------------+-------------------+
|   10000    |  2.54 ± 0.07      |  2.57 ± 0.10      |  2.63 ± 0.05      |
+------------+-------------------+-------------------+-------------------+
|     -1     |  2.55 ± 0.03      |  2.50 ± 0.04      |  2.55 ± 0.08      |
+------------+-------------------+-------------------+-------------------+
```
Latencies are pretty much the same in all cases. The vector limit is expected to perform a bit faster than internal paging, because it fetches all primary keys from the index view in one request instead of `<page size> / 1000` requests. This is hardly noticeable in the measurements.

### Case 2: Large partition range vectors, no short reads

30,000 partitions, 1 row per partition
Same schema as case 1.

```
+------------+-------------------+-------------------+-------------------+
|  Page Size |      Master       |   Vector Limit    |  Internal Paging  |
+============+===================+===================+===================+
|            |   Latency (sec)   |   Latency (sec)   |   Latency (sec)   |
+------------+-------------------+-------------------+-------------------+
|     100    |  5.80 ± 0.13      |  5.64 ± 0.10      |  5.81 ± 0.05      |
+------------+-------------------+-------------------+-------------------+
|    1000    |  4.77 ± 0.07      |  4.62 ± 0.06      |  4.84 ± 0.09      |
+------------+-------------------+-------------------+-------------------+
|    2000    |  4.67 ± 0.07      |  5.13 ± 0.03      |  4.76 ± 0.04      |
+------------+-------------------+-------------------+-------------------+
|    5000    |  4.82 ± 0.09      |  6.25 ± 0.06      |  4.86 ± 0.16      |
+------------+-------------------+-------------------+-------------------+
|   10000    |  4.89 ± 0.36      |  7.52 ± 0.13      |  5.09 ± 0.30      |
+------------+-------------------+-------------------+-------------------+
|     -1     |  4.90 ± 0.67      |  4.79 ± 0.33      |  4.92 ± 0.47      |
+------------+-------------------+-------------------+-------------------+
```
With the vector limit, the querier cache is lost above 1000, so latencies increase. This doesn't happen with internal paging.

### Case 3: Small partition range vectors, short base table reads

1,000 partitions, 100 rows per partition, ~1KiB per row (large non-primary key column)
Same schema as case 1, except that the non-primary key column is a blob with 1KiB of random data.

```
+------------+-------------------+-------------------+-------------------+
|  Page Size |      Master       |   Vector Limit    |  Internal Paging  |
+============+===================+===================+===================+
|            |   Latency (sec)   |   Latency (sec)   |   Latency (sec)   |
+------------+-------------------+-------------------+-------------------+
|     100    |  4.35 ± 0.09      |  4.45 ± 0.05      |  4.51 ± 0.11      |
+------------+-------------------+-------------------+-------------------+
|    1000    |  3.20 ± 0.08      |  3.13 ± 0.11      |  3.22 ± 0.06      |
+------------+-------------------+-------------------+-------------------+
|    2000    |  3.00 ± 0.11      |  2.98 ± 0.08      |  3.07 ± 0.06      |
+------------+-------------------+-------------------+-------------------+
|    5000    |  3.77 ± 0.16      |  3.74 ± 0.09      |  3.36 ± 0.03      |
+------------+-------------------+-------------------+-------------------+
|   10000    |  5.79 ± 0.16      |  5.86 ± 0.21      |  3.36 ± 0.02      |
+------------+-------------------+-------------------+-------------------+
|     -1     |  2.99 ± 0.12      |  2.93 ± 0.12      |  2.90 ± 0.07      |
+------------+-------------------+-------------------+-------------------+
```
In this test, each partition is 100KiB and contains 100 rows, so given the exponential concurrency on base table reads, we expect to hit a short read when a read exceeds 1MiB, so: (1 * 100KiB) + (2 * 100KiB) + (4 * 100KiB) + (8 * 100KiB) + **(16 * 100KiB)** = 3100 KiB -> 3100 rows -> 5000 page size. Indeed, internal paging seems to perform better than the vector limit above 2000. That's because, with internal paging, the number of discarded partition keys are bounded (in this case 1000 - 3100 % 1000 = 900). In contrast, with the vector limit, we discard 5000 - 3100 = 1900 and 10000 - 3100 = 6900 partition keys. Notice also that internal paging has a slight overhead above 2000. This must be due to losing the querier cache.

PS: I don't understand why the coordinator declares a read as short only based on the last read, and not from the aggregate of all past reads of this query. In the above example, the short read happens way beyond 1MiB.

**Comment by bhalevy** [comment]
so according to the findings above, it looks like the overall winner is internal paging, right?

> PS: I don't understand why the coordinator declares a read as short only based on the last read, and not from the aggregate of all past reads of this query. In the above example, the short read happens way beyond 1MiB.

@denesb any insight?

**Comment by denesb** [comment]
> so according to the findings above, it looks like the overall winner is internal paging, right?
> 
> > PS: I don't understand why the coordinator declares a read as short only based on the last read, and not from the aggregate of all past reads of this query. In the above example, the short read happens way beyond 1MiB.
> 
> @denesb any insight?

Whether a read is short or not always refers to the current page, not to the entire query as a whole. A page is cut when one of these things happen:
1) The page has requested number of rows already
2) No more data for the query
3) Page hit the page-size (in bytes) limit
4) Page hit the tombstone-limit

In case (1) the page has requested number of rows and the page is not short. In case (2) the page doesn't have the requested number of rows and it isn't short. This is the query termination criteria.
In all other cases the page doesn't have the requested number of rows and the page is short. So short-read simply means: please continue the query, even though the requested number of rows wasn't supplied in the last page.

**Comment by ndragazis** [comment]
> > > PS: I don't understand why the coordinator declares a read as short only based on the last read, and not from the aggregate of all past reads of this query. In the above example, the short read happens way beyond 1MiB.
> >
> >   @denesb any insight?
>
> Whether a read is short or not always refers to the current page, not to the entire query as a whole. 

@denesb I was specifically referring to secondary index queries. The coordinator constructs the page from multiple queries on the base table, but only examines the last base table query to decide if the page is short. Why are we ignoring the data we have collected so far?

https://github.com/scylladb/scylladb/blob/9ec1a457d65a20f7f4c6c8b015bc308ffdcec4ba/cql3/statements/select_statement.cc#L726-L727

**Comment by bhalevy** [comment]
> > so according to the findings above, it looks like the overall winner is internal paging, right?
> 
> We have the aggressive approach (vector limit), where we fetch as much primary keys as possible and drop the surplus, and the conservative approach (internal paging), where we only fetch up to 1k primary keys at a time.
> 
> The aggressive approach breaks the querier cache. Based on my measurements, this is very bad and should be avoided.
> 
> The conservative approach doesn't break the cache, but it runs slower with large partitions, as it triggers extra requests to the replicas (up to 9 requests, assuming page sizes < 10k). These cause extra latencies. I haven't tested this on a real cluster, but I believe this is better than breaking the cache. The network round trips within a region should be <1ms, and I guess the request dispatch rate should be way less than 1ms under normal load.
> 
> That said, I believe internal paging is a better option and we should resurrect it. Does this make sense?
> 
> Another option would be to do the simplest thing: restrict the page size to 1000. That would be way simpler, but also a bit slower than internal paging in some cases, because the `concurrency` in `do_execute_base_query()` would be reset after every 1000 rows. This is why in the above measurements for internal paging the latency improves even above 1000 (the internal page size).

I agree it's more important to not break the querier cache.
Given the reasonable amplitude of the inefficiency of limiting the vector size, I'd go with that first, since it's simpler and has lower risk.  We can open an issue for improving it using internal queries as a follow up.

**Comment by denesb** [comment]
> > > > PS: I don't understand why the coordinator declares a read as short only based on the last read, and not from the aggregate of all past reads of this query. In the above example, the short read happens way beyond 1MiB.
> > > 
> > > 
> > > @denesb any insight?
> > 
> > 
> > Whether a read is short or not always refers to the current page, not to the entire query as a whole.
> 
> @denesb I was specifically referring to secondary index queries. The coordinator constructs the page from multiple queries on the base table, but only examines the last base table query to decide if the page is short. Why are we ignoring the data we have collected so far?
> 
> https://github.com/scylladb/scylladb/blob/9ec1a457d65a20f7f4c6c8b015bc308ffdcec4ba/cql3/statements/select_statement.cc#L726-L727

When we are going to read the next base-table page, it only matters whether the last page we read was short, it doesn't matter whether any intermediate ones were short or not.
Also note that each query on the base table is a separate query from the pager and replica POV, it makes no sense to combine paging flags between them.

**Comment by denesb** [comment]
@ndragazis I agree with @bhalevy, it is important to not break the querier cache.

Can we somehow allow the user to influence the page-size used for internal reads, buy setting the page-size on the overall query? Expert users prefer to have a way to tweak the system to make it behave the best with the workload at hand.

**Comment by ndragazis** [comment]
> I agree it's more important to not break the querier cache.
Given the reasonable amplitude of the inefficiency of limiting the vector size, I'd go with that first, since it's simpler and has lower risk.

OK. Let's go with the vector limit then. I will follow up with a v3.

> We can open an issue for improving it using internal queries as a follow up.

Or we can fix this as part of adaptive paging (https://github.com/scylladb/scylladb/issues/3807). The idea there was to dynamically calibrate the page size to prevent short base table reads, but we can extend the algorithm to also prevent hitting the vector limit. If we do that, there won't be much merit left in internal paging.

> @ndragazis I agree with @bhalevy, it is important to not break the querier cache.
>
> Can we somehow allow the user to influence the page-size used for internal reads, buy setting the page-size on the overall query? Expert users prefer to have a way to tweak the system to make it behave the best with the workload at hand.

Note that breaking the querier cache can happen already from short base table reads. With the vector limit, we will introduce a second cause. In any case, yes, the user can reduce the page size to prevent it. The user's page size controls the number of primary keys we read from the index view.

**Comment by ndragazis** [comment]
v3 Changelog:
* Rebase.
* Add space after "if".
* Replace runtime fatal error with warning.
* Revert the increase of allocation threshold in test.
* Mention the regression in PR description.

v2->v3 Inter-diff:
```diff
diff --git a/cql3/statements/select_statement.cc b/cql3/statements/select_statement.cc
index dc10904577..9a8bf06ca1 100644
--- a/cql3/statements/select_statement.cc
+++ b/cql3/statements/select_statement.cc
@@ -1401,16 +1401,15 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
     auto timeout = db::timeout_clock::now() + get_timeout(state.get_client_state(), options);
     bool is_paged = options.get_page_size() >= 0;
     constexpr size_t MAX_PARTITION_RANGES = 1000;
-    // This check ensures that `partition_range_vector` won't cause a large allocation (see #18536).
-    // This is not a fatal error, but we treat it as such to ensure this won't go under the radar.
-    // If this fails, please adjust MAX_PARTITION_RANGES accordingly.
-    if(MAX_PARTITION_RANGES * sizeof(dht::partition_range_vector::value_type) > current_allocator().preferred_max_contiguous_allocation()) {
-        on_fatal_internal_error(logger, seastar::format(
+    // Check that `partition_range_vector` won't cause a large allocation (see #18536).
+    // If this warning appears, please adjust MAX_PARTITION_RANGES accordingly.
+    if (MAX_PARTITION_RANGES * sizeof(dht::partition_range_vector::value_type) > current_allocator().preferred_max_contiguous_allocation()) {
+        logger.warn(
                 "MAX_PARTITION_RANGES ({}) too high - will cause large allocations from partition_range_vector: max allocation size = {} bytes, allocator's preferred max contiguous allocation size = {} bytes",
                 MAX_PARTITION_RANGES,
                 MAX_PARTITION_RANGES * sizeof(dht::partition_range_vector::value_type),
                 current_allocator().preferred_max_contiguous_allocation()
-        ));
+        );
     }
     size_t max_vector_size = is_paged ? MAX_PARTITION_RANGES : std::numeric_limits<size_t>::max();
     std::unique_ptr<query_options> paging_adjusted_options = [&] () {
diff --git a/test/boost/secondary_index_test.cc b/test/boost/secondary_index_test.cc
index 046a852688..2e7554fb25 100644
--- a/test/boost/secondary_index_test.cc
+++ b/test/boost/secondary_index_test.cc
@@ -2014,8 +2014,7 @@ SEASTAR_TEST_CASE(test_returning_failure_from_ghost_rows_deletion) {
 //
 // This test reproduces the problem with a query on an index with many
 // single-row partitions, and checks the memory stats for any large contiguous
-// allocations. The allocation threshold is set to an arguably high value (512KiB)
-// to filter out large allocations that may be caused by other internal operations.
+// allocations.
 //
 // The test is disabled in "sanitize" mode (ASAN interferes with memory allocations).
 #ifndef SEASTAR_ASAN_ENABLED
@@ -2023,8 +2022,8 @@ SEASTAR_TEST_CASE(test_large_allocations) {
     return do_with_cql_env([] (cql_test_env& e) -> future<> {
         co_await e.execute_cql("CREATE TABLE t (p int, c int, PRIMARY KEY (p, c));");
         co_await e.execute_cql("CREATE INDEX ON t (c);");
-        int allocation_threshold = 512 * 1024;
-        int partitions = 5000;
+        int allocation_threshold = current_allocator().preferred_max_contiguous_allocation();
+        int partitions = allocation_threshold / sizeof(dht::partition_range) + 1; // lowest number that reproduces #18536
         auto prepared_id = co_await e.prepare("INSERT INTO t (p, c) VALUES (?, 1);");
         for (int pk : std::views::iota(0, partitions)) {
             co_await e.execute_prepared(prepared_id,
~
```

File: cql3/statements/select_statement.cc [hunk 9]
```diff
@@ -1398,12 +1399,25 @@ indexed_table_select_statement::find_index_partition_ranges(query_processor& qp,
     using value_type = std::tuple<dht::partition_range_vector, lw_shared_ptr<const service::pager::paging_state>>;
     auto now = gc_clock::now();
     auto timeout = db::timeout_clock::now() + get_timeout(state.get_client_state(), options);
+    bool is_paged = options.get_page_size() >= 0;
+    constexpr size_t MAX_PARTITION_RANGES = 1000;
+    // Check that `partition_range_vector` won't cause a large allocation (see #18536).
+    // If this warning appears, please adjust MAX_PARTITION_RANGES accordingly.
+    if (MAX_PARTITION_RANGES * sizeof(dht::partition_range_vector::value_type) > current_allocator().preferred_max_contiguous_allocation()) {
```
Comment (avikivity) [inline cql3/statements/select_statement.cc:1406]: You can code 128k here and convert it to static_assert, there's no way we'd use anything other than the standard allocator.

Yes, we should have a named constant for it, but we don't. At this point 128k is like Plank's constant for us.

**Comment by ndragazis** [comment]
v4 Changelog:
* Convert warning to `static_assert`. Use a hardcoded value of 128KiB as the allocation threshold.

**Comment by ndragazis** [comment]
> [test_topology_ops[False].debug.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15843/testReport/junit/cluster/test_topology_ops/Tests___Unit_Tests___test_topology_ops_False__debug_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops%5BFalse%5D.debug.3)

Known issue: https://github.com/scylladb/scylladb/issues/21949

**Review by denesb — APPROVED** [review]
