### PR TITLE
streaming: Avoid deadlock by running view checks in a separate scheduling group

### LINKED ISSUE #24807: streaming,repair: `db::view::check_needs_view_update_path()` can deadlock with the repair/streaming permit
This was seen in the past already: https://github.com/scylladb/scylladb/issues/21264.
The fix (https://github.com/scylladb/scylladb/commit/7c75fc599fab53c0722ac63dd1a7d9d1f471fc6d) addressed the deadlock on the count resources, but not the one on the memory resources. We just hit this deadlock in the field recently: the permit of the view table query was queued because the resources used by the permit of the stream transfer task, causing the query to time out and the streaming to fail.

### LINKED ISSUE #24925: non-RBNO streaming may hang on failure if IO permits are deadlocked
If IO permits are exhausted, `db::view::check_needs_view_update_path()` called by the streaming receiver side will time-out on the read concurrency semaphore. Error handling on the receiver side will then attempt to sync the schema via table_sync_and_check() using group0 before responding with failure:

```c++
                    if (db.local_is_initialized() && mm.local_is_initialized() && co_await table_sync_and_check(db.local(), mm.local(), cf_id)) {
                        level = seastar::log_level::debug;
                        status = -2;
                    }
                    sslog.log(level, "[Stream #{}] Failed to handle STREAM_MUTATION_FRAGMENTS (receive and distribute phase) for ks={}, cf={}, peer={}: {}",
                        plan_id, s->ks_name(), s->cf_name(), from, aborted?"Streaming aborted":format("{}",ex));

```

group0 barrier does a local read, which will hang as well on the semaphore, this time with indefinite timeout.

Introduced in 35bc1fe2762216d5dd3a16518c490373b708bc4d (2025.2.0)

Related to scenario in https://github.com/scylladb/scylladb/issues/24807

permits may be exhausted and deadlocked when running non-RBNO removenode on vnode-based keyspaces.

### PR DESCRIPTION
**Pull request by tgrabiec**
This issue happens with removenode, when RBNO is disabled, so range
streamer is used.

The deadlock happens in a scenario like this:
1. Start 3 nodes: {A, B, C}, RF=2
2. Node A is lost
3. removenode A
4. Both B and C gain ownership of ranges.
5. Streaming sessions are started with crossed directions: B->C, C->B

Readers created by sender side exhaust streaming semaphore on B and C.
Receiver side attempts to obtain a permit indirectly by calling
check_needs_view_update_path(), which reads local tables. That read is
blocked and times-out, causing streaming to fail. The streaming writer
is already using a tracking-only permit.

Even if we didn't deadlock, and the streaming semaphore was simply exhausted
by other receiving sessions (via tracking-only permit), the query may still time-out due to starvation. 

To avoid that, run the query under a different scheduling group, which
translates to the system semaphore instead of the maintenance
semaphore, to break the dependency. The gossip group was chosen
because it shouldn't be contended and this change should not interfere
with it much.

Fixes #24807
Fixes #24925

### CODE REVIEW

**Comment by avikivity** [comment]
> translates to the system semaphore i

This can overload the system semaphore, which wants to be unloaded so service to group0 and gossip can be fast.

File: service/migration_manager.cc [hunk 1]
```diff
@@ -56,7 +56,9 @@ migration_manager::migration_manager(migration_notifier& notifier, gms::feature_
         , _group0_barrier(this_shard_id() == 0 ?
             std::function<future<>()>([this] () -> future<> {
                 // This will run raft barrier and will sync schema with the leader
-                (void)co_await start_group0_operation();
+                return with_scheduling_group(_storage_proxy.get_db().local().get_gossip_scheduling_group(), [this] {
```
Comment (avikivity) [inline service/migration_manager.cc:59]: There's co_await coroutine::switch_to() (switch_to.hh), no need to go back to continuations.

Wouldn't it be enough to call mm._group0_barrier.trigger() like the other side of the conditional?

File: streaming/consumer.cc [hunk 2]
```diff
@@ -35,7 +36,9 @@ mutation_reader_consumer make_streaming_consumer(sstring origin,
 
             auto cf = db.local().find_column_family(reader.schema()).shared_from_this();
             auto guard = service::topology_guard(frozen_guard);
-            auto use_view_update_path = co_await db::view::check_needs_view_update_path(vb.local(), db.local().get_token_metadata_ptr(), *cf, reason);
+            bool use_view_update_path = co_await with_scheduling_group(db.local().get_gossip_scheduling_group(), [&] {
+                return db::view::check_needs_view_update_path(vb.local(), db.local().get_token_metadata_ptr(), *cf, reason);
+            });
```
Comment (avikivity) [inline streaming/consumer.cc:41]: As mentioned above (or below, depends on github formatting), this throws data into a control-plane scheduling group, which can easily starve it. Or perhaps, cause it to starve other data-plane groups.

Switching groups can reduce throughput if there isn't enough concurrency, I don't know if that's the case here. Since it's in a consumer, probably it is.

Comment (avikivity) [reply streaming/consumer.cc:41]: Alternatives can be:
 - add a new group (reasonable when we have [nested scheduling](https://github.com/scylladb/seastar/pull/2823), but doesn't solve the throughput problem if it exists)
 - teach the reader_concurrency_semaphore about query nesting

File: service/migration_manager.cc (hunk 1 above)
Comment (tgrabiec) [reply service/migration_manager.cc:59]: This is the handler for the trigger

File: streaming/consumer.cc (hunk 2 above)
Comment (tgrabiec) [reply streaming/consumer.cc:41]: This is done once per stream session, when it starts. So should be rare.

Comment (denesb) [reply streaming/consumer.cc:41]: > teach the reader_concurrency_semaphore about query nesting

This would be the "proper" way, but I don't know how to do it. The nested query can run on another shard [of another node].

Comment (denesb) [reply streaming/consumer.cc:41]: Also, with nested queries, you can have the ABBA deadlock, across nodes.

Maybe a "reserved" semaphore capacity can solve this: mainline consumers can take 9/10 of the semaphore's resources, but 1/10 is reserved for nested consumers. We still need to add a way to tag queries as "nested" ones.

Comment (avikivity) [reply streaming/consumer.cc:41]: Yes, by nesting I meant reservations for the nested/inner queries.

It could also be done by having two semaphores, indexed by the level, with separate reservations.

And yes, we'd need to tag queries.

nested scheduling groups is attractive here because it tags requests, and because we already associate reader concurrency semaphores with scheduling groups, and because it's just pretty. But it doesn't backport and we shouldn't employ it just for that. @xemul

File: service/migration_manager.cc (hunk 1 above)
Comment (avikivity) [reply service/migration_manager.cc:59]: Oops

File: streaming/consumer.cc (hunk 2 above)
Comment (avikivity) [reply streaming/consumer.cc:41]: > This is done once per stream session, when it starts. So should be rare.

Indeed it's independent of any key. And it's not that expensive (though the code is quite involved).

So it's okay to run it on the gossip scheduling group.

**Comment by denesb** [comment]
Dequeued, breaks promotion: https://jenkins.scylladb.com/job/scylla-master/job/next/9386/
Looks like there is bad interaction with the keyspace/table drop check during streaming/repair.
@Deexie can you please review and also check the failed tests to see where is the bad interaction coming from?

**Comment by bhalevy** [comment]
@tgrabiec please backport also to relevant enterprise release (2024.2)
