### PR TITLE
Standardize node ops sync_nodes selection

### LINKED ISSUE #12862: Scylla sometimes fails to boot with node replace
In CI run https://jenkins.scylladb.com/job/scylla-master/job/build/1366/ the test `test/topology/test_topology_ip.py` failed once (it usually passes...) when Scylla failed to boot (in debug build):

```
E               Failed to start server with ID = 181, IP = 127.213.224.6.
E               Check the log files:
E               /jenkins/workspace/scylla-master/build/scylla/testlog/x86_64/test.py.debug-release-dev.log
E               /jenkins/workspace/scylla-master/build/scylla/testlog/x86_64/debug/scylla-181.log
```

The log file https://jenkins.scylladb.com/job/scylla-master/job/build/1366/artifact/testlog/x86_64/debug/scylla-181.log has some weird repair-related RPC error during the boot:

```
...
INFO  2023-02-15 04:46:38,853 [shard 0] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={replace}
INFO  2023-02-15 04:46:38,853 [shard 0] storage_service - replace[812e5015-9e25-42f0-9adc-8f9aca3bc3b7]: Using repair based node ops to sync data
INFO  2023-02-15 04:46:38,867 [shard 0] repair - replace_with_repair: started with keyspaces=system_authsystem_distributed_everywheresystem_distributedsystem_traces, source_dc=datacenter1, nr_ranges_total=438, ignore_nodes=[]
INFO  2023-02-15 04:46:38,869 [shard 0] repair - replace_with_repair: started with keyspace=system_auth, source_dc=datacenter1, nr_ranges=48, ignore_nodes=[]
INFO  2023-02-15 04:46:38,871 [shard 0] repair - replace_with_repair: finished with keyspace=system_auth, source_dc=datacenter1, nr_ranges=0
INFO  2023-02-15 04:46:38,871 [shard 0] repair - replace_with_repair: started with keyspace=system_distributed_everywhere, source_dc=datacenter1, nr_ranges=49, ignore_nodes=[]
INFO  2023-02-15 04:46:38,874 [shard 0] repair - repair[f43eeae1-6808-4ff0-abe6-f83c9c286292]: sync data for keyspace=system_distributed_everywhere, status=started
INFO  2023-02-15 04:46:38,875 [shard 0] repair - repair[f43eeae1-6808-4ff0-abe6-f83c9c286292]: Started to repair 1 out of 1 tables in keyspace=system_distributed_everywhere, table=cdc_generation_descriptions_v2, table_id=234d2227-dd63-3d37-ac5f-c013e2ea9e6e, repair_reason=replace
INFO  2023-02-15 04:46:38,876 [shard 1] repair - repair[f43eeae1-6808-4ff0-abe6-f83c9c286292]: Started to repair 1 out of 1 tables in keyspace=system_distributed_everywhere, table=cdc_generation_descriptions_v2, table_id=234d2227-dd63-3d37-ac5f-c013e2ea9e6e, repair_reason=replace
WARN  2023-02-15 04:46:38,892 [shard 1] repair - repair[f43eeae1-6808-4ff0-abe6-f83c9c286292]: shard=1, keyspace=system_distributed_everywhere, cf=cdc_generation_descriptions_v2, range=(-inf, -8681815950261682620], got error in row level repair: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 1 for node 127.213.224.6 does not exist)
WARN  2023-02-15 04:46:39,894 [shard 0] repair - repair[f43eeae1-6808-4ff0-abe6-f83c9c286292]: sync data for keyspace=system_distributed_everywhere, status=failed: std::runtime_error ({shard 0: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 0 for node 127.213.224.6 does not exist), shard 1: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 1 for node 127.213.224.6 does not exist)})
INFO  2023-02-15 04:46:39,989 [shard 0] storage_service - replace[812e5015-9e25-42f0-9adc-8f9aca3bc3b7]: Stopped heartbeat_updater
ERROR 2023-02-15 04:46:39,989 [shard 0] storage_service - replace[812e5015-9e25-42f0-9adc-8f9aca3bc3b7]: Abort replace operation started, replace_nodes={{127.213.224.6 -> 127.213.224.6}}, sync_nodes=[127.213.224.6, 127.213.224.54, 127.213.224.31], ignore_nodes=[]: std::runtime_error ({shard 0: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 0 for node 127.213.224.6 does not exist), shard 1: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 1 for node 127.213.224.6 does not exist)})
INFO  2023-02-15 04:46:39,993 [shard 0] storage_service - replace[812e5015-9e25-42f0-9adc-8f9aca3bc3b7]: Removed replacing_node=127.213.224.6 to replace existing_node=127.213.224.6, coordinator=127.213.224.6
INFO  2023-02-15 04:46:39,993 [shard 0] token_metadata - Removed node 127.213.224.6 as pending replacing endpoint which replaces existing node 127.213.224.6
ERROR 2023-02-15 04:46:40,016 [shard 0] storage_service - replace[812e5015-9e25-42f0-9adc-8f9aca3bc3b7]: Abort replace operation finished, replace_nodes={{127.213.224.6 -> 127.213.224.6}}, sync_nodes=[127.213.224.6, 127.213.224.54, 127.213.224.31], ignore_nodes=[]: std::runtime_error ({shard 0: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 0 for node 127.213.224.6 does not exist), shard 1: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 1 for node 127.213.224.6 does not exist)})
...
ERROR 2023-02-15 04:46:53,058 [shard 0] init - Startup failed: std::runtime_error ({shard 0: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 0 for node 127.213.224.6 does not exist), shard 1: seastar::rpc::remote_verb_error (get_repair_meta: repair_meta_id 1 for node 127.213.224.6 does not exist)})
```

@asias does this error look familiar? Should this problem really have caused Scylla to refuse to boot, or maybe it is some sort of race because the topology tests do not "sleep enough"? (obviously, they shouldn't need to sleep, but I remember we had bugs like this in the past).

@kostja @kbr-scylla @alecco maybe you can explain better than me what the failing test was trying to do when it failed?

### PR DESCRIPTION
**Pull request by bhalevy**
Use token_metadata get_endpoint_to_host_id_map_for_reading
to get all normal token owners for all node operations,
rather than using gossip for some operation and
token_metadata for others.

Fixes #12862

### CODE REVIEW

**Comment by bhalevy** [comment]
```
[gw2] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_removenode_rejected_with_rnbo 
[gw3] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_lcs_reshape_efficiency 
[gw5] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_enable_rbno_for_bootstrap 
[gw1] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_enable_rbno_for_default_operation 
[gw0] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_disable_rbno 
[gw4] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_disable_rbno_for_all_operations 
[gw0] PASSED repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_ignore_dead_nodes_for_replace_option 
```

File: service/storage_service.cc [hunk 1]
```diff
@@ -629,18 +629,18 @@ future<> storage_service::mark_existing_views_as_built(sharded<db::system_distri
...
             std::replace(n.begin(), n.end(), '\"', ' ');
             std::replace(n.begin(), n.end(), '\'', ' ');
             boost::trim_all(n);
             if (!n.empty()) {
                 auto ep_and_id = tm.parse_host_id_and_endpoint(n);
-                ignore_nodes.push_back(ep_and_id.endpoint);
+                ignore_nodes.insert(ep_and_id.endpoint);
             }
         } catch (...) {
             throw std::runtime_error(format("Failed to parse --ignore-dead-nodes-for-replace parameter: ignore_nodes={}, node={}: {}", ignore_nodes_strs, n, std::current_exception()));
```
Comment (asias) [inline service/storage_service.cc:646]: The comment for "replace" is not updated after the renaming of the function.

File: service/storage_service.cc [hunk 2]
```diff
@@ -2248,21 +2261,15 @@ void storage_service::run_bootstrap_ops(std::unordered_set<token>& bootstrap_tok
     node_ops_ctl ctl(*this, node_ops_cmd::bootstrap_prepare, db.get_config().host_id, get_broadcast_address());
     auto stop_ctl = deferred_stop(ctl);
     const auto& uuid = ctl.uuid();
+
+    // Step 1: Decide who needs to sync data for bootstrap operation
     // TODO: Specify ignore_nodes
+    ctl.start("bootstrap", [this_node = get_broadcast_address()] (gms::inet_address node) {
```
Comment (asias) [inline service/storage_service.cc:2267]: We do not need to exclude this_node. Original code excludes this_node because we do not bother to check the gossip status of this_node.  In ctrl.start, get_endpoint_to_host_id_map_for_reading will not return this_node any way. 

Note, at line 2274, we insert this_node to sync_nodes explicitly. 

It is better to drop the this_node check filter here to avoid confusion.

File: service/storage_service.cc [hunk 3]
```diff
@@ -2288,11 +2295,13 @@ void storage_service::run_bootstrap_ops(std::unordered_set<token>& bootstrap_tok
             }
             slogger.warn("bootstrap[{}]: Found pending node ops = {}, sleep 5 seconds and check again", uuid, pending_ops);
             sleep_abortable(std::chrono::seconds(5), _abort_source).get();
+
+            ctl.refresh_sync_nodes([this_node = get_broadcast_address()] (gms::inet_address node) {
```
Comment (asias) [inline service/storage_service.cc:2299]: We can drop the filter here too.

But refresh_sync_nodes will revert what we do at line 2274 which adds this_node to sync_nodes. 

We need to call here:

```
ctl.refresh_sync_nodes();
ctl.sync_nodes.insert(get_broadcast_address());
```

File: service/storage_service.cc (hunk 2 above)
Comment (bhalevy) [reply service/storage_service.cc:2267]: okay, makes sense

File: service/storage_service.cc (hunk 3 above)
Comment (bhalevy) [reply service/storage_service.cc:2299]: But it will be re-added by line 2274 when we loop back.

File: service/storage_service.cc (hunk 2 above)
Comment (bhalevy) [reply service/storage_service.cc]: Actually, it turns out that get_endpoint_to_host_id_map_for_reading does return pending nodes.
It's not restricted to normal town owners.
I'll delete the first patch then.
I'm tempted to change refresh_sync_nodes to return only normal token owners
but we should do that as a followup since it would impact decommission and removenode.

**Comment by bhalevy** [comment]
In v2 ([dc6e9e6](https://github.com/scylladb/scylladb/commit/dc6e9e6776850853061acc0d71d38a2889e4c499)):
- Reverted "token_metadata: get_endpoint_to_host_id_map_for_reading: document return of normal token owners"
- storage_service: get_ignore_dead_nodes_for_replace: make static and rename to parse_node_list
  - renamed function to a more generic name
  - and updated log printout
- storage_service: node ops: standardize sync_nodes selection
  - erase the bootstrapping node from sync_nodes and add it back explicitly after `wait_for_normal_state_handled_on_boot`  for bootstrap and replace.

**Comment by bhalevy** [comment]
v3 ([ca61d88](https://github.com/scylladb/scylladb/commit/ca61d88764f234851c95a26123dbe72abd28ed4b)):
- rebased

**Comment by bhalevy** [comment]
@asias please ack.

**Comment by bhalevy** [comment]
ping @asias

**Comment by asias** [comment]
> ping @asias

Sorry, I was out last week. 

Looks good to me.

**Comment by bhalevy** [comment]
@tgrabiec / @scylladb/scylla-maint please merge
