### PR TITLE
Fix large data warning and docs

### LINKED ISSUE #11620: missing delimiter between partition key and clustering key in large data warning
f3089bf3d1eda2be01e3af07fe1fde6fb08b62d5 added https://github.com/scylladb/scylladb/blob/f3089bf3d1eda2be01e3af07fe1fde6fb08b62d5/db/large_data_handler.cc#L64

That prints `pk_str` possibly followed, immediately, by the clustering key for large rows and cells.
Note that there is no delimiter between `pk_str` and `extra_path` so they are concatenated together.

### LINKED ISSUE #11621: Adjust large_* docs for sstable base names
Since 244df0777153d5719d972508b02c3fa22c6f6524 (scylla 5.1),
only the sstable basename is kept in the large_* system tables.
The base path can be determined from the keyspace and
table name.
    
Adjust the examples in documentation respectively.

### LINKED ISSUE #11622: Adjust docs/large-partition-table.rst to rows column
Since a7511cf6000de0e2191e9ca18025f45bfdb04068 (scylla 5.0),
sstables containing partitions with too many rows are recorded in system.large_partitions.

Adjust the doc respectively.

### PR DESCRIPTION
**Pull request by bhalevy**
The series contains fixes for system.large_* log warning and respective documentation.
This prepares the way for adding a new system.large_collections table (See #11449):

Fixes #11620
Fixes #11621
Fixes #11622

the respective fixes should be backported to different release branches, based on the respective patches they depend on (mentioned in each issue).

### CODE REVIEW

**Comment by bhalevy** [comment]
In v2 ([a5814cc](https://github.com/scylladb/scylladb/commit/a5814cc2d2fdcbb28e573d2ce7a096a7f28190ec)):
- db/large_data_handler: separate pk and ck strings in warning with delimiter:
  - fixed bug affecting cql query to update the system.large_cells table
- added "b/large_data_handler: print static cell/collection description in warning"
- rebased + retested

File: db/large_data_handler.cc [hunk 1]
```diff
@@ -146,9 +146,9 @@ future<> cql_table_large_data_handler::record_large_cells(const sstables::sstabl
     if (clustering_key) {
         const schema &s = *sst.get_schema();
         auto ck_str = key_to_str(*clustering_key, s);
-        return try_record("cell", sst, partition_key, int64_t(cell_size), cell_type, format("{} {}", ck_str, column_name), extra_fields, ck_str, column_name);
+        return try_record("cell", sst, partition_key, int64_t(cell_size), cell_type, format("/{}/{}", ck_str, column_name), extra_fields, ck_str, column_name);
```
Comment (nyh) [inline db/large_data_handler.cc:149]: I'm afraid I don't understand this change or why try_record even takes this parameter which you changed here...
According to docs/dev/system_keyspace.md, the partition key, clustering key, and column name, are all stored individually in the table. This is also why this function try_record() takes partition_key, ck_str, and column_name separately. So why do we ned to pass it, additionally, this concatenated format? why can't it calculate it on its own?

Comment (nyh) [reply db/large_data_handler.cc:149]: Also, you forgot to mention in the commit message (or it wasn't clear enough to me) that what you're changing here is just the log messages - NOT the large-cell/row system table - which is why we think it's ok to change the format - we are not backward compatible when it comes to log messages.

File: docs/troubleshooting/large-partition-table.rst [hunk 2]
```diff
@@ -73,24 +75,27 @@ Example output:
...
+in the scylla.yaml configuration file.
+Partitions that are bigger than the size threshold and/or hold more than the rows count threshold are reported in the ``system.large_partitions`` table and generate a warning in the Scylla log (refer to :doc:`log </getting-started/logging/>`).
 
-For example (set to 500MB):
+For example (set to 500MB / 50000, respectively):
 
 .. code-block:: console
 
    compaction_large_partition_warning_threshold_mb: 500
+   compaction_rows_count_warning_threshold: 50000
```
Comment (nyh) [inline docs/troubleshooting/large-partition-table.rst:98]: Nice, I wasn't aware we added this.
Sad there's duplication and partial information between docs/troubleshooting/large-partition-table.rst which you modify here, and docs/dev/system_keyspace.md. But we don't have to fix that right now.

**Review by nyh — APPROVED** [review]

File: db/large_data_handler.cc (hunk 1 above)
Comment (bhalevy) [reply db/large_data_handler.cc:149]: Right.  This changes only the log message, that need not be backward compatible (it was buggy anyhow by concatenating the partition and clustering keys together, with no delimiter).
We can also consider printing it in a more structured way like, `pk=<partition_key> ck=<clustering_key> column=<column_name>` instead of `<partition_key>/<clustering_key>/<column_name>` that might be useful for developers that may use the code to parse the log message, but less useful to users - who should consult the system.large_* tables rather than the log.

**Comment by bhalevy** [comment]
In v3 ([a1adbf1](https://github.com/scylladb/scylladb/commit/a1adbf1f59058be4406480e3c9f976760611dbb4))
- clarified patches' commit log (title and comment)
