### PR TITLE
tests: utils: error injection: print time duration instead of count

### LINKED ISSUE #15902: error_injection_test.test_inject_future_disabled is flaky in debug mode
```
[2023-10-31T17:14:07.941Z] test/boost/error_injection_test.cc(161): Entering test case "test_inject_future_disabled"
[2023-10-31T17:14:07.941Z] WARNING: debug mode. Not for benchmarking or production
[2023-10-31T17:14:07.941Z] WARN  2023-10-31 14:54:51,230 seastar - Seastar compiled with default allocator, --memory option won't take effect
[2023-10-31T17:14:07.941Z] INFO  2023-10-31 14:54:51,300 seastar - Reactor backend: linux-aio
[2023-10-31T17:14:07.942Z] INFO  2023-10-31 14:54:51,302 [shard 0:n/a ] seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
[2023-10-31T17:14:07.942Z] random-seed=1356563082
[2023-10-31T17:14:07.942Z] test/boost/error_injection_test.cc(167): fatal error: in "test_inject_future_disabled": critical check wait_time.count() < sleep_msec.count() has failed [12 >= 10]
[2023-10-31T17:14:07.942Z] test/boost/error_injection_test.cc(161): Leaving test case "test_inject_future_disabled"; testing time: 267049us
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4461

### PR DESCRIPTION
**Pull request by tchaikov**
before this change, we always cast the wait duration to millisecond,
even if it could be using a higher resolution. actually
`std::chrono::steady_clock` is using `nanosecond` for its duration,
so if we inject a deadline using `steady_clock`, we could be awaken
earlier due to the narrowing of the duration type caused by the
duration_cast.

in this change, we just use the duration as it is. this should allow
the caller to use the resolution provided by Seastar without losing
the precision. the tests are updated to print the time duration 
instead of count to provide information with a higher resolution.

Fixes #15902

### CODE REVIEW

File: test/boost/error_injection_test.cc [hunk 1]
```diff
@@ -152,7 +155,8 @@ SEASTAR_TEST_CASE(test_inject_sleep_deadline_db_clock) {
         auto deadline = db::timeout_clock::now() + sleep_msec;
         errinj.enable("future_deadline");
         errinj.inject("future_deadline", deadline).then([deadline] {
-            BOOST_REQUIRE_GE(std::chrono::duration_cast<std::chrono::milliseconds>(db::timeout_clock::now() - deadline).count(), 0);
+            BOOST_REQUIRE_GE(db::timeout_clock::now() - deadline,
+                             db::timeout_clock::duration::zero());
```
Comment (xemul) [inline test/boost/error_injection_test.cc:159]: Why is it only steady clock that deserves a "small tolerance, in case i am awaken a little bit early"? (above)

Comment (tchaikov) [reply test/boost/error_injection_test.cc:159]: because this is the only test which failed with the original change.

Comment (xemul) [reply test/boost/error_injection_test.cc:159]: That's weird. I mean the steady-clock fixlet. Sleep shouldn't return earlier, it could only resolve later

Comment (tchaikov) [reply test/boost/error_injection_test.cc:159]: Yeah. Good point. Would be better off root-causing it.

Comment (tchaikov) [reply test/boost/error_injection_test.cc:159]: before it is root-caused, i am marking this change draft.

**Comment by tchaikov** [comment]
v2:

- added a commit allowing inject with a higher resolution than millisecond -- this should address the test failure of #15902

**Comment by tchaikov** [comment]
@xemul hi Pavel, i updated the changeset. could you help re-review this change?

**Review by xemul — APPROVED** [review]

**Comment by mykaul** [comment]
@tchaikov - do we need to backport this to 5.2, 5.4?

**Comment by tchaikov** [comment]
@mykaul yes, the bug was introduced by a8b14b022789799bbe2dd2b31b0cc57dd9186def, was included by all releases after 4.2, and before 5.4.5, inclusive.

**Comment by tchaikov** [comment]
and .. it's already backported to 5.2 with #17911 and 5.4 at #17909 respectively. thanks to Yaron's great work and mergify.
