### PR TITLE
storage_service: Fix race between tablet split and stats retrieval

### LINKED ISSUE #18085: topology_experimental_raft.test_tablets: test_tablet_split: Invalid tablet id: 2 >= 2
Seen in: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7775/

```
terminate called after throwing an instance of 'std::logic_error'
  what():  Invalid tablet id: 2 >= 2
Aborting on shard 0.
Backtrace:
  0xd5c600a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x492058c
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x49201e3
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x475b0c8
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x478bc95
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4886789
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4886ace
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x48868de
  /lib64/libc.so.6+0x3dbaf
  /lib64/libc.so.6+0x8e883
  /lib64/libc.so.6+0x3dafd
  /lib64/libc.so.6+0x2687e
  /lib64/libstdc++.so.6+0xa4d18
  /lib64/libstdc++.so.6+0xb4f4b
  /lib64/libstdc++.so.6+0xb4fb6
  0xd75e73a
  0xe891397
  0x129324a5
  0x12931ad4
  0x129bd3fb
  0x12b1da96
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x477dbfe
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4786120
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x478a142
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4787d63
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x42af28a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x42ac82a
  0xd65fa09
  0xd65c8ef
  /lib64/libc.so.6+0x27b89
  /lib64/libc.so.6+0x27c4a
  0xd5808e4
------ Ending test debug/topology_experimental_raft.test_tablets.5::test_tablet_split ------
```

Logs:
[scylla-2665.log](https://github.com/scylladb/scylladb/files/14788931/scylla-2665.log)
[scylla-2666.log](https://github.com/scylladb/scylladb/files/14788933/scylla-2666.log)
[topology_experimental_raft.test_tablets.5.log](https://github.com/scylladb/scylladb/files/14788934/topology_experimental_raft.test_tablets.5.log)

### PR DESCRIPTION
**Pull request by raphaelsc**
Retrieval of tablet stats must be serialized with mutation to token metadata, as the former requires tablet id stability.
If tablet split is finalized while retrieving stats, the saved erm, used by all shards, can have a lower tablet count than the one in a particular shard, causing an abort as tablet map requires that any id feeded into it is lower than its current tablet count.

Fixes #18085.

### CODE REVIEW

**Review by denesb — APPROVED** [review]
LGTM and makes sense but @tgrabiec should also have a look.

**Comment by raphaelsc** [comment]
@tgrabiec ping.

File: service/storage_service.cc [hunk 1]
```diff
@@ -6023,6 +6023,14 @@ future<locator::load_stats> storage_service::load_stats_for_tablet_based_tables(
         });
     }
 
+    // Retrieval of tablet stats must be serialized with mutation to token metadata,
+    // as the former requires tablet id stability.
+    // If tablet split is finalized while retrieving stats, the saved erm, used by all
+    // shards, can have a lower tablet count than the one in a particular shard, causing
+    // an abort as tablet map requires that any id feeded into it is lower than its
+    // current tablet count.
+    auto tmlock = co_await get_token_metadata_lock();
```
Comment (tgrabiec) [inline service/storage_service.cc:6032]: Why not pass the current tablet_map to the filter function instead?

Comment (tgrabiec) [reply service/storage_service.cc:6032]: tablet_id is meaningful within a given tablet_map version, so we should use that version.

Comment (raphaelsc) [reply service/storage_service.cc:6032]: the reason for having a global erm is that we want consistent view across shards (busy shards might be processing a tablet map different than the ones processed earlier). with intra node migration (which can complete fast), we could have double accounting. 

why if we still take token metadata lock (as done in this patch) and feed local tablet map into filter function (as you suggest)? then we can get rid of this global erm approach.

Comment (tgrabiec) [reply service/storage_service.cc:6032]: Across-node stats collection is still async, so it only helps with intra-node migration. But ok.

I think this is orthogonal to tablet id stability, and we should still pass tablet_map& to the handler for simplicity.

File: service/storage_service.cc [hunk 2]
```diff
@@ -6023,6 +6023,14 @@ future<locator::load_stats> storage_service::load_stats_for_tablet_based_tables(
...
+
```
Comment (tgrabiec) [inline service/storage_service.cc:6033]: btw, the check below:

```
s < locator::tablet_transition_stage::cleanup
```

is no longer accurate because stages are non-linear, we have revert_migration and end_migration. Better to have a helper function with a switch for all stages.

Comment (raphaelsc) [reply service/storage_service.cc:6033]: Will send another patch to fix this. Thanks.

File: service/storage_service.cc (hunk 1 above)
Comment (raphaelsc) [reply service/storage_service.cc:6032]: sure, will proceed with the changes.

**Comment by raphaelsc** [comment]
v2: 
- feed local tablet map instead for simplicity
- fix handling of double accounting since migration revert was introduced (new patch added for that).

@tgrabiec please re-review.

**Review by tgrabiec — APPROVED** [review]

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8398/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8398/) **The following new/updated tests ran 100 times for each mode:** 🔹 topology_experimental_raft/test_tablets
> 
> #### Failed Tests (4/6600):
> * [topology_experimental_raft.test_tablets.release.29](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8398/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_release_29) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.release.29)
> * [topology_experimental_raft.test_tablets.release.30](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8398/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_release_30) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.release.30)
> * [test_topology_changes](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8398/testReport/junit/%28root%29/test_tablets/test_topology_changes) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes)
> * [test_topology_changes](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8398/testReport/junit/%28root%29/test_tablets/test_topology_changes_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes)
> 
> #### Build Details:
> * Duration: 7 hr 53 min
> * Builder: spider5.cloudius-systems.com

test/topology_experimental_raft/test_tablets.py::test_topology_changes 

unrelated, will take a look tomorrow

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8431/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8431/) **The following new/updated tests ran 100 times for each mode:** 🔹 topology_experimental_raft/test_tablets
> 
> #### Failed Tests (4/6600):
> * [test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/test_tablets/test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode)
> * [test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/test_tablets/test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode)
> * [topology_experimental_raft.test_tablets.dev.17](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_dev_17) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.dev.17)
> * [topology_experimental_raft.test_tablets.dev.19](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_dev_19) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.dev.19)
> 
> #### Build Details:
> * Duration: 7 hr 48 min
> * Builder: spider6.cloudius-systems.com



> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8431/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8431/) **The following new/updated tests ran 100 times for each mode:** 🔹 topology_experimental_raft/test_tablets
> 
> #### Failed Tests (4/6600):
> * [test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/test_tablets/test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode)
> * [test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/test_tablets/test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode)
> * [topology_experimental_raft.test_tablets.dev.17](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_dev_17) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.dev.17)
> * [topology_experimental_raft.test_tablets.dev.19](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8431/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_dev_19) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.dev.19)
> 
> #### Build Details:
> * Duration: 7 hr 48 min
> * Builder: spider6.cloudius-systems.com

That's https://github.com/scylladb/scylladb/issues/14746, apparently problem is in the driver https://github.com/scylladb/python-driver/issues/295.

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8444/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8444/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/chunked_managed_vector_test 🔹 boost/chunked_vector_test 🔹 cql-pytest/test_alter_table 🔹 object_store/test_basic 🔹 topology_experimental_raft/test_tablets
> 
> #### Failed Tests (6/9614):
> * [test_storage_service_api_uneven_ownership_keyspace_and_table_params_used](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8444/testReport/junit/%28root%29/test_tablets/test_storage_service_api_uneven_ownership_keyspace_and_table_params_used) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_storage_service_api_uneven_ownership_keyspace_and_table_params_used)


@pwrobelse please take a look at failure above. log: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8444/artifact/testlog/x86_64/release/topology_experimental_raft.test_tablets.29.log 

> * [test_tablet_load_and_stream[True]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8444/testReport/junit/%28root%29/test_tablets/test_tablet_load_and_stream_True_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_load_and_stream%5BTrue%5D)

I think this is https://github.com/scylladb/scylladb/issues/15356, hopefully fixed by https://github.com/scylladb/scylladb/pull/18484

> * [test_table_drop_with_auto_snapshot](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8444/testReport/junit/%28root%29/test_tablets/test_table_drop_with_auto_snapshot) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_table_drop_with_auto_snapshot)
> * [topology_experimental_raft.test_tablets.release.29](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8444/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_release_29) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.release.29)
> * [topology_experimental_raft.test_tablets.release.30](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8444/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_release_30) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.release.30)
> * [topology_experimental_raft.test_tablets.release.32](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8444/testReport/junit/%28root%29/non-boost%20tests/topology_experimental_raft_test_tablets_release_32) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.release.32)
> 
> #### Build Details:
> * Duration: 8 hr 50 min
> * Builder: spider8.cloudius-systems.com

**Comment by pwrobelse** [comment]
Hi @raphaelsc,

I checked the logs produced by `test_storage_service_api_uneven_ownership_keyspace_and_table_params_used` and it seems, that the error comes from the tear-down of the test case. 

Error details: `failed on teardown with "aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected"`.

The error occurred in `manager_internal.after_test()` function that is defined in `test/pylib/manager_client.py`. The tear-down procedure failed on reporting the results of execution of the test case.

The full log below:

```
test/topology_experimental_raft/test_tablets.py::test_storage_service_api_uneven_ownership_keyspace_and_table_params_used ERROR

==================================== ERRORS ====================================
_ ERROR at teardown of test_storage_service_api_uneven_ownership_keyspace_and_table_params_used _

    def finalizer() -> None:
        """Yield again, to finalize."""
    
        async def async_finalizer() -> None:
            try:
                await gen_obj.__anext__()
            except StopAsyncIteration:
                pass
            else:
                msg = "Async generator fixture didn't stop."
                msg += "Yield only once."
                raise ValueError(msg)
    
>       event_loop.run_until_complete(async_finalizer())

/usr/lib/python3.11/site-packages/pytest_asyncio/plugin.py:297: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.11/asyncio/base_events.py:654: in run_until_complete
    return future.result()
/usr/lib/python3.11/site-packages/pytest_asyncio/plugin.py:289: in async_finalizer
    await gen_obj.__anext__()
test/topology/conftest.py:181: in manager
    await manager_internal.after_test(test_case_name, not failed)
test/pylib/manager_client.py:133: in after_test
    cluster_str = await self.client.put_json(f"/cluster/after-test/{success}",
test/pylib/rest_client.py:111: in put_json
    ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
test/pylib/rest_client.py:64: in _fetch
    async with request(method, uri,
/usr/lib64/python3.11/site-packages/aiohttp/client.py:1243: in __aenter__
    self._resp = await self._coro
/usr/lib64/python3.11/site-packages/aiohttp/client.py:605: in _request
    await resp.start(conn)
/usr/lib64/python3.11/site-packages/aiohttp/client_reqrep.py:966: in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiohttp.client_proto.ResponseHandler object at 0x7f760c204c90>

    async def read(self) -> _T:
        if not self._buffer and not self._eof:
            assert not self._waiter
            self._waiter = self._loop.create_future()
            try:
>               await self._waiter
E               aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

/usr/lib64/python3.11/site-packages/aiohttp/streams.py:622: ServerDisconnectedError
```


It does not seem to be an error related to the tested logic. Also, I do not see any additional wait operations in other test cases from `topology_experimental_raft/test_tablets.py`. Could it be related to some environment problem?

**Comment by raphaelsc** [comment]
v3: rebase

**Review by avikivity — APPROVED** [review]

**Comment by raphaelsc** [comment]
v4:
rebased
added fix for flakiness in topology_experimental_raft.test_tablets

**Comment by raphaelsc** [comment]
@benipeled will this come back to life: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9116/console ?

**Comment by raphaelsc** [comment]
@benipeled CI is not working for me, see: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9150/console (some infrastructure issue)

**Comment by benipeled** [comment]
> @benipeled CI is not working for me, see: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9150/console (some infrastructure issue)

Checkout issue - fixed on Friday - I re-triggered a new CI https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/

**Comment by raphaelsc** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/) **The following new/updated tests ran 100 times for each mode:** 🔹 topology_experimental_raft/test_tablets
> 
> #### Failed Tests (4/5400):
> * [test_topology_changes](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/9204/testReport/junit/%28root%29/test_tablets/test_topology_changes) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes)
> * [test_table_dropped_during_streaming](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/9204/testReport/junit/%28root%29/test_tablets/test_table_dropped_during_streaming) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_table_dropped_during_streaming)
> * [test_tablet_split](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/9204/testReport/junit/%28root%29/test_tablets/test_tablet_split) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_split)
> * [test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/9204/testReport/junit/%28root%29/test_tablets/test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode)
> 
> #### Build Details:
> * Duration: 8 hr 12 min
> * Builder: i-0e662465e8b790484 (m5ad.12xlarge)

tracking flakiness in topology_experimental_raft/test_tablets with https://github.com/scylladb/scylladb/issues/18896, it seems to be caused by either https://github.com/scylladb/scylladb/issues/15356 or https://github.com/scylladb/python-driver/issues/230 (which happens with enough concurrency)

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint please consider merging. opened issue (https://github.com/scylladb/scylladb/issues/18896) to track flakiness in topology_experimental_raft/test_tablets, which is definitely unrelated to this series, managed to fix some of them in the last patch, but some still remain. they seem to be caused by python driver bug (https://github.com/scylladb/python-driver/issues/230) and gossiper being aborted prematurely on shutdown, causing driver to go into reconnection storm (https://github.com/scylladb/scylladb/issues/15356).

File: test/topology_experimental_raft/test_tablets.py [hunk 3]
```diff
@@ -440,7 +455,7 @@ async def check_with_down(down_node):
         for r in rows:
             assert r.c == r.pk
 
-    await manager.rolling_restart(servers, with_down=check_with_down)
+    cql = await safe_rolling_restart(manager, servers, with_down=insert_with_down)
```
Comment (tgrabiec) [inline test/topology_experimental_raft/test_tablets.py:458]: This dropped the use of check_with_down

@raphaelsc

Comment (raphaelsc) [reply test/topology_experimental_raft/test_tablets.py:458]: oops, will send a fix.
