### PR TITLE
replica: Fix use-after-free with concurrent schema change and sstable set update

### LINKED ISSUE #22040: heap-use-after-free /jenkins/workspace/scylla-master/scylla-ci/scylla/sstables/sstable_set.cc:354
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14043/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_secondary_index_test_debug_1/
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14043/artifact/testlog/x86_64/debug/scylla-284.log

```
INFO  2024-12-23 21:22:07,114 [shard 0: gms] schema_tables - Altering cql_test_1734981726456.cql_test_1734981726470 id=327c6170-c163-11ef-a802-2c5b8e27a785 version=32dc34b0-c163-11ef-a802-2c5b8e27a785
INFO  2024-12-23 21:22:07,115 [shard 0: gms] schema_tables - Creating cql_test_1734981726456.camelcase_index id=32dc34b1-c163-11ef-a802-2c5b8e27a785 version=32dc34b2-c163-11ef-a802-2c5b8e27a785
INFO  2024-12-23 21:22:07,121 [shard 0: gms] query_processor - Column definitions for cql_test_1734981726456.cql_test_1734981726470 changed, invalidating related prepared statements
=================================================================
==193639==ERROR: AddressSanitizer: heap-use-after-free on address 0x50300089a130 at pc 0x0000092084dc bp 0x7ffc934172b0 sp 0x7ffc934172a8
READ of size 8 at 0x50300089a130 thread T0
INFO  2024-12-23 21:22:07,123 [shard 1: gms] query_processor - Column definitions for cql_test_1734981726456.cql_test_1734981726470 changed, invalidating related prepared statements
INFO  2024-12-23 21:22:07,186 [shard 1:comp] compaction - [Compact cql_test_1734981726456.cql_test_1734981726470 32e95410-c163-11ef-9740-2c5a8e27a785] Compacting [/scylladir/testlog/x86_64/debug/scylla-284/data/cql_test_1734981726456/cql_test_1734981726470-327c6170c16311efa8022c5b8e27a785/me-3gmb_1hsv_0qd2o2asxjxmc180w5-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-284/data/cql_test_1734981726456/cql_test_1734981726470-327c6170c16311efa8022c5b8e27a785/me-3gmb_1hsv_02sb42asxjxmc180w5-big-Data.db:level=0:origin=compaction]
INFO  2024-12-23 21:22:07,216 [shard 1:comp] sstable - Rebuilding bloom filter /scylladir/testlog/x86_64/debug/scylla-284/data/cql_test_1734981726456/cql_test_1734981726470-327c6170c16311efa8022c5b8e27a785/me-3gmb_1hsv_15d742asxjxmc180w5-big-Filter.db: resizing bitset from 328 bytes to 8 bytes. sstable origin: compaction
INFO  2024-12-23 21:22:07,230 [shard 1:comp] compaction - [Compact cql_test_1734981726456.cql_test_1734981726470 32e95410-c163-11ef-9740-2c5a8e27a785] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-284/data/cql_test_1734981726456/cql_test_1734981726470-327c6170c16311efa8022c5b8e27a785/me-3gmb_1hsv_15d742asxjxmc180w5-big-Data.db:level=0]. 130kB to 65kB (~49% of original) in 40ms = 3MB/s. ~256 total partitions merged to 2.
    #0 0x92084db in std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>::_M_next() const /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:387:47
    #1 0x92084db in std::__detail::_Node_iterator_base<seastar::lw_shared_ptr<sstables::sstable>, true>::_M_incr() /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:404:26
    #2 0x92084db in std::__detail::_Node_iterator<seastar::lw_shared_ptr<sstables::sstable>, true, true>::operator++() /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:456:8
    #3 0x92084db in sstables::partitioned_sstable_set::for_each_sstable_gently_until(std::function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag>> (seastar::lw_shared_ptr<sstables::sstable> const&)>) const (.resume) /jenkins/workspace/scylla-master/scylla-ci/scylla/sstables/sstable_set.cc:354:20
    #4 0x46c0556 in std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<seastar::bool_class<seastar::stop_iteration_tag>>::promise_type>::resume() const /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242:29
    #5 0x46c0556 in seastar::internal::coroutine_traits_base<seastar::bool_class<seastar::stop_iteration_tag>>::promise_type::run_and_dispose() /jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include/seastar/core/coroutine.hh:80:20
    #6 0x7f934ff38b90 in seastar::reactor::run_tasks(seastar::reactor::task_queue&) build/Debug/seastar/./seastar/src/core/reactor.cc:2606:14
    #7 0x7f934ff44e9d in seastar::reactor::run_some_tasks() build/Debug/seastar/./seastar/src/core/reactor.cc:3078:9
    #8 0x7f934ff4a33d in seastar::reactor::do_run() build/Debug/seastar/./seastar/src/core/reactor.cc:3246:9
    #9 0x7f934ff48349 in seastar::reactor::run() build/Debug/seastar/./seastar/src/core/reactor.cc:3136:16
    #10 0x7f934fa999b4 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) build/Debug/seastar/./seastar/src/core/app-template.cc:276:31
    #11 0x7f934fa9634a in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) build/Debug/seastar/./seastar/src/core/app-template.cc:167:12
    #12 0x3145417 in scylla_main(int, char**) /jenkins/workspace/scylla-master/scylla-ci/scylla/main.cc:778:16
    #13 0x31429b3 in std::function<int (int, char**)>::operator()(int, char**) const /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591:9
    #14 0x31429b3 in main /jenkins/workspace/scylla-master/scylla-ci/scylla/main.cc:2391:12
    #15 0x7f934add4087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: b871aacf7b252210b87d2e5dbea81bda8ada61f1)
    #16 0x7f934add414a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14a) (BuildId: b871aacf7b252210b87d2e5dbea81bda8ada61f1)
    #17 0x3062684 in _start (/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/scylla+0x3062684) (BuildId: a7df302949e1e9b383fffd753ba8156ae482cd05)

0x50300089a130 is located 0 bytes inside of 24-byte region [0x50300089a130,0x50300089a148)
freed by thread T0 here:
    #0 0x313a56d in operator delete(void*) /mnt/clang_build/llvm-project-x86_64/compiler-rt/lib/asan/asan_new_delete.cpp:143:3
    #1 0x3ba14e7 in std::__new_allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>::deallocate(std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>*, unsigned long) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/new_allocator.h:172:2
    #2 0x3ba14e7 in std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>::deallocate(std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>*, unsigned long) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/allocator.h:208:25
    #3 0x3ba14e7 in std::allocator_traits<std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>>::deallocate(std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>&, std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>*, unsigned long) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/alloc_traits.h:513:13
    #4 0x3ba14e7 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>>::_M_deallocate_node_ptr(std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>*) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:2051:7
    #5 0x3ba14e7 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>>::_M_deallocate_node(std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>*) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:2041:7
    #6 0x3ba14e7 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>>::_M_deallocate_nodes(std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>*) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:2062:4

previously allocated by thread T0 here:
    #0 0x3139d0d in operator new(unsigned long) /mnt/clang_build/llvm-project-x86_64/compiler-rt/lib/asan/asan_new_delete.cpp:86:3
    #1 0x5411d74 in std::__new_allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/new_allocator.h:151:27
    #2 0x5411d74 in std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>::allocate(unsigned long) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/allocator.h:196:32
    #3 0x5411d74 in std::allocator_traits<std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>>::allocate(std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>&, unsigned long) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/alloc_traits.h:478:20
    #4 0x5411d74 in std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<seastar::lw_shared_ptr<sstables::sstable>, true>>>::_M_allocate_node<seastar::lw_shared_ptr<sstables::sstable> const&>(seastar::lw_shared_ptr<sstables::sstable> const&) /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable_policy.h:2019:16

SUMMARY: AddressSanitizer: heap-use-after-free /jenkins/workspace/scylla-master/scylla-ci/scylla/sstables/sstable_set.cc:354:20 in sstables::partitioned_sstable_set::for_each_sstable_gently_until(std::function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag>> (seastar::lw_shared_ptr<sstables::sstable> const&)>) const (.resume)
Shadow bytes around the buggy address:
  0x503000899e80: fa fa fd fd fd fd fa fa fd fd fd fd fa fa 00 00
  0x503000899f00: 00 00 fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x503000899f80: 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x50300089a000: fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00
  0x50300089a080: 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
=>0x50300089a100: fa fa fa fa fa fa[fd]fd fd fa fa fa 00 00 05 fa
  0x50300089a180: fa fa 00 00 00 07 fa fa fd fd fd fd fa fa 00 00
  0x50300089a200: 00 03 fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x50300089a280: 00 00 00 fa fa fa 00 00 00 fa fa fa fd fd fd fa
  0x50300089a300: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x50300089a380: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==193639==ABORTING
Aborting on shard 0, in scheduling group compaction.
Backtrace:
  0x30a6935
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x38d3197
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x38d2e25
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x371045b
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374bab5
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3831719
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3831a47
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x383186e
  /lib64/libc.so.6+0x40d0f
  /lib64/libc.so.6+0x99bd3
  /lib64/libc.so.6+0x40c5d
  /lib64/libc.so.6+0x28901
  0x31223b6
  0x3120550
  0x31015ce
  0x3104614
  0x31052b7
  0x92084db
  0x46c0556
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3738b90
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3744e9d
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374a33d
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3748349
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x32999b4
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x329634a
  0x3145417
  0x31429b3
  /lib64/libc.so.6+0x2a087
  /lib64/libc.so.6+0x2a14a
  0x3062684
------ Ending test cqlpy.cassandra_tests/validation/entities/secondary_index_test.1 ------

```

### PR DESCRIPTION
**Pull request by raphaelsc**
When schema is changed, sstable set is updated according to the compaction strategy of the new schema (no changes to set are actually made, just the underlying set type is updated), but the problem is that it happens without a lock, causing a use-after-free when running concurrently to another set update.

Example:

1) A: sstable set is being updated on compaction completion
2) B: schema change updates the set (it's non deferring, so it happens in one go) and frees the set used by A.
3) when A resumes, system will likely crash since the set is freed already.

ASAN screams about it:
SUMMARY: AddressSanitizer: heap-use-after-free sstables/sstable_set.cc ...

Fix is about deferring update of the set on schema change to compaction, which is triggered after new schema is set. Only strategy state and backlog tracker are updated immediately, which is fine since strategy doesn't depend on any particular implementation of sstable set.

Fixes #22040.

### CODE REVIEW

File: sstables/sstable_set.cc [hunk 1]
```diff
@@ -927,7 +927,21 @@ filter_sstable_for_reader_by_ck(std::vector<shared_sstable>&& sstables, replica:
...
+        // When a run cannot accept sstable due to overlapping, treat the rejected sstable
+        // as a single-fragment run.
+        if (!runs_m[sst->run_identifier()].insert(sst)) {
+            all_runs.push_back(make_lw_shared<const sstable_run>(sst));
+        }
+    }
+    for (auto&& r : runs_m | std::views::values) {
+        all_runs.push_back(make_lw_shared<const sstable_run>(std::move(r)));
+    }
+    return all_runs;
```
Comment (denesb) [inline sstables/sstable_set.cc:944]: How similar is this to the other implementations? Can they be shared?

File: replica/table.cc [hunk 2]
```diff
@@ -2190,26 +2191,26 @@ void table::set_compaction_strategy(sstables::compaction_strategy_type strategy)
...
+            cg.main_sstables()->for_each_sstable([&new_sstables_for_backlog_tracker] (const sstables::shared_sstable& s) {
                 new_sstables_for_backlog_tracker.push_back(s);
             });
             new_bt.replace_sstables({}, std::move(new_sstables_for_backlog_tracker));
         }
 
         void execute() noexcept {
+            // Update strategy state and backlog tracker according to new strategy. SSTable set update
+            // is delayed until new compaction, which is triggered on strategy change. SSTable set
+            // cannot be updated here since it must happen under the set update lock.
```
Comment (denesb) [inline replica/table.cc:2205]: This means that if the schema update didn't change the compaction strategy, the set won't be updated. But this is the only case where it needs to be updated, right?

File: replica/table.cc [hunk 3]
```diff
@@ -2218,7 +2219,6 @@ void table::set_compaction_strategy(sstables::compaction_strategy_type strategy)
     for (auto& updater : cg_sstable_set_updaters) {
         updater.execute();
     }
-    refresh_compound_sstable_set();
```
Comment (denesb) [inline replica/table.cc:2221]: I don't see any changes that do the part which makes compaction finish update the sstable set. Does this code already exists?

Comment (raphaelsc) [reply replica/table.cc:2221]: Yes, since compaction must replace old by new sstables. see compaction_group::update_sstable_sets_on_compaction_completion().

**Comment by raphaelsc** [comment]
v3:
rebased

**Comment by denesb** [comment]
> #### 🟢 CI State: SUCCESS
> 
> ✅ - [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/17136/) ❌ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/17136/)
> #### Build Details:
> 
>     * Duration: 36 min
> 
>     * Builder: spider3.cloudius-systems.com

I cannot figure out what failed here, @yaronkaikov can you please have a look?

**Comment by mykaul** [comment]
From what I can see, curl failed to connect to GH API with error code 60, which is: "60     Peer certificate cannot be authenticated with known CA certificates." ... ?!

**Comment by denesb** [comment]
Why does it keep happening on this PR?

**Comment by yaronkaikov** [comment]
> > #### 🟢 CI State: SUCCESS
> > ✅ - [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/17136/) ❌ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/17136/)
> > #### Build Details:
> > ```
> > * Duration: 36 min
> > 
> > * Builder: spider3.cloudius-systems.com
> > ```
> 
> I cannot figure out what failed here, @yaronkaikov can you please have a look?

seems like some network issue, i saw it's failed on publishing the artifact into S3
