### PR TITLE
Alternator/cache expressions

### LINKED ISSUE #25855: Alternator: incorrect parsing of a condition expression with single attribute
The current implementation of this specific case is clearly explained in this test:

```python
# Primitive conditions usually look like an operator between two (<, <=,
# etc.), three (BETWEEN) or more (IN) values. Can just a single value be
# a condition? The special case of a single function call *can* be - we saw
# an example attribute_exists(z) in the previous test. However only
# function calls are supported in this context - not general values (i.e.,
# attribute or value references).
# While DynamoDB does not accept a non-function-call value as a condition
# (it results with with a syntax error), in Alternator currently, for
# simplicity of the parser, this case is parsed correctly and only fails
# later when the calculated value ends up to not be a boolean.
def test_update_condition_single_value_attribute(test_table_s):
    p = random_string()
    test_table_s.update_item(Key={'p': p},
            AttributeUpdates={'a': {'Value': 1, 'Action': 'PUT'}})
    with pytest.raises(ClientError, match='ValidationException'):
        test_table_s.update_item(Key={'p': p},
            UpdateExpression='SET c = :val',
                ConditionExpression='a',
                ExpressionAttributeValues={':val': 1})
```
https://github.com/m-szymon/scylladb/blob/a39b773d36b054efc97b76cf29e7bc2f7c93c31c/test/alternator/test_condition_expression.py#L975-L993

However this only works when the attribute or value is not actually a boolean. I confirmed the difference in Alternator vs DynamoDB changing initially set value:
```python
            AttributeUpdates={'a': {'Value': True, 'Action': 'PUT'}})
```

### PR DESCRIPTION
**Pull request by m-szymon**
Before this patch, every expression in Alternator's requests was parsed from string to adequate structure.
This patch enables caching, where input expression strings are mapped to parsed template structures.
Every new valid (parsable) expression is added to the cache. The cache has limited (configurable) size - when it is reached, the least recently used entry is removed.
When requested expression is in the cache, the copy of the template is returned - individual instances still need to be resolved (placeholders substituted with names and values).
Caching is implemented for all expression types. The cache is per shard - shared for all operations, expression types, tables, users.
Default cache size is 2000 entries per shard and it has configuration option `alternator_max_expression_cache_entries_per_shard` (0 means cache disabled).
Basic metrics (total count of hits and misses for each expression type and number of evicted enries) are implemented.
Cache features are tested in boost unit tests and overall expression caching is tested with Python tests - both mostly rely on metrics.

refs #5023
`perf-alternator` test shows improvement (median):
| test | throughput | instructions_per_op | cpu_cycles_per_op | allocs_per_op |
| ------ | ---------------- | ----------------------------- | --------------------------- | -------------------  |
| read | +6.0% | -8.5% | -7.0% | -4.9% |
| write | +13.4% | -17.6% | -14.7% | -7.4% |
| write(lwt) | +12.7% | -7.9% | -6.9% | -2.8% |
| write_rwm | +5.4% | -10.5% | -7.3% | -4.1% |

"read" had a ProjectionExpression with 10 column names, "write" had a UpdateExpression with 10 column names and "write_rmw" had both ConditionExpression and UpdateExpression.

This patch also includes minor refactoring of other expressions related tests (https://github.com/scylladb/scylladb/issues/22494) - use `test_table_ss` instead of `test_table`.
Fixes #25855.

This is new feature - no backporting.

### CODE REVIEW

**Comment by ScyllaPiotr** [comment]
Thanks Szymon!

About the title of the cover letter:
> Alternator/cache expressions

Are all expressions going to be cached now? IIRC only some subset of a specific type of a request - only those inside `UpdateExpression` parameter of `UpdateItem` operation. Please reflect this in the title as good as possible and also in the cover letter's content.

@nyh do the patches with new features require issues that such PRs fix?

@m-szymon:
> ...where input expression strings are mapped to parsed structures.

Please call up `UpdateItem` and `UpdateExpression` explicitly.
Also, I propose to call the cached items _templates_, as these still need to be filled with names and values of each single JSON request.

> When requested expression is in the cache, the copy is returned, as individual instances still need to be resolved (substituted with names and values).

When requested expression is in the cache, the copy **of the template** is returned, as individual instances still need to be resolved (substituted with names and values).

IIRC there is a single cache on each shard, which is shared with all tables and clients. This is relevant info.

If the cache is disabled by default, how to enable it?

**Comment by avikivity** [comment]
I don't see any measurements.

We have several caching strategies proposed, with no conclusion, but this patch just goes and implements one of them.

File: alternator/executor.hh [hunk 1]
```diff
@@ -173,7 +172,9 @@ public:
              db::system_distributed_keyspace& sdks,
              cdc::metadata& cdc_metadata,
              smp_service_group ssg,
-             utils::updateable_value<uint32_t> default_timeout_in_ms);
+             utils::updateable_value<uint32_t> default_timeout_in_ms,
+             utils::updateable_value<uint32_t> expression_cache_size);
+    ~executor();
```
Comment (ScyllaPiotr) [inline alternator/executor.hh:178]: Why split the declaration and the implementation, since the latter is default?

File: alternator/expression_factory.cc [hunk 2]
```diff
@@ -0,0 +1,191 @@
...
+ */
+
+#include "expressions.hh"
+#include "utils/log.hh"
+
+#include <boost/intrusive/list.hpp>
+#include <absl/container/node_hash_map.h>
+#include <optional>
+
+logging::logger cache_logger("alternator-cache");
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: `"alternator-cache"` is a bit vague, maybe `"alternator-parsed-req-cache"`?

File: alternator/expression_factory.cc [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+
+namespace alternator {
+namespace {
+
+template<typename Value>
+class lru_string_map {
+    struct key {
+        mutable boost::intrusive::list_member_hook<> list_hook;
+        seastar::sstring str;
+        explicit key(std::string_view s) : str(std::move(s)) {
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: Isn't the `std::move` an idle suggestion here?

**Comment by m-szymon** [comment]
@avikivity, I am not planing to close the original issue #5023 and forget about topic - it is still an open discussion.
But this strategy is so simple, that it is easier to implement it and then measure it thoroughly, than to try to estimate how much would it help. I consider it a single step forward, but given that you advocate for caching entire requests I can imagine that it is unnecessary from your point of view.
However this a good case to actually define what is our reference and how we measure performance. If we can quantify the gain of this patch it should be easier to agree about next optimizations. And this is work in progress.

There are no new measurements here, the last started discussion was here https://github.com/scylladb/scylladb/issues/5023#issuecomment-3053089376 (which I missed to continue).

**Comment by avikivity** [comment]
> @avikivity, I am not planing to close the original issue #5023 and forget about topic - it is still an open discussion. But this strategy is so simple, that it is easier to implement it and then measure it thoroughly, than to try to estimate how much would it help. I consider it a single step forward, but given that you advocate for caching entire requests I can imagine that it is unnecessary from your point of view. However this a good case to actually define what is our reference and how we measure performance. If we can quantify the gain of this patch it should be easier to agree about next optimizations. And this is work in progress.
> 
> There are no new measurements here, the last started discussion was here [#5023 (comment)](https://github.com/scylladb/scylladb/issues/5023#issuecomment-3053089376) (which I missed to continue).

A patch that aims to improve performance should show that in the changelog.

File: alternator/expressions.hh [hunk 4]
```diff
@@ -26,9 +28,20 @@ public:
...
+public:
+    struct config {
+        utils::updateable_value<uint32_t> max_cache_entries;
+    };
+    expression_factory(config cfg, stats& stats);
+    ~expression_factory();
+
+    parsed::update_expression parse_update_expression(std::string_view query);
+    std::vector<parsed::path> parse_projection_expression(std::string_view query);
+    parsed::condition_expression parse_condition_expression(std::string_view query, const char* caller);
```
Comment (avikivity) [inline alternator/expressions.hh]: Seems sad to return values (that need allocations) rather than references, but don't need to improve everything at once.

File: alternator/stats.cc [hunk 5]
```diff
@@ -155,6 +155,22 @@ static void register_metrics_with_optional_table(seastar::metrics::metric_groups
...
+    metrics.add_group(group_name, {
+            seastar::metrics::make_total_operations("expression_cache_evictions", stats.expression_cache.evictions,
+                    seastar::metrics::description("Counts number of evictions from expressions cache"), labels).aggregate(aggregate_labels).set_skip_when_empty(),
+
+#define EXPR_CACHE(name, Type) \
+                seastar::metrics::make_total_operations("expression_cache_hits", stats.expression_cache.requests[stats::expression_types::name].hits, \
+                        seastar::metrics::description("Counts number of hits of cached expressions"), labels)(expression_label(Type)).aggregate(aggregate_labels).set_skip_when_empty(), \
+                seastar::metrics::make_total_operations("expression_cache_misses", stats.expression_cache.requests[stats::expression_types::name].misses, \
+                        seastar::metrics::description("Counts number of misses of cached expressions"), labels)(expression_label(Type)).aggregate(aggregate_labels).set_skip_when_empty()
+
```
Comment (avikivity) [inline alternator/stats.cc:173]: Please avoid C macros.

File: conf/scylla.yaml [hunk 6]
```diff
@@ -885,6 +885,9 @@ rf_rack_valid_keyspaces: false
 # Note: DynamoDB has a hard-coded limit of 25.
 # alternator_max_items_in_batch_write: 100
 
+# Maximum number of expressions cached by Alternator. Default 0 means cache is disabled.
+# alternator_max_expression_cache_entries: 0
```
Comment (avikivity) [inline conf/scylla.yaml]: No need to add such esoteric (no offence) configuration to scylla.yaml.

File: db/config.cc [hunk 7]
```diff
@@ -1363,6 +1363,7 @@ db::config::config(std::shared_ptr<db::extensions> exts)
     // alternator_max_items_in_batch_write matches DynamoDB behaviour of size limit, but with different value - for DynamoDB it's 25
     // (see DynamoDB's documentation for BatchWriteItem command)
     , alternator_max_items_in_batch_write(this, "alternator_max_items_in_batch_write", value_status::Used, 100, "Maximum amount of items in single BatchItemWrite call.")
+    , alternator_max_expression_cache_entries(this, "alternator_max_expression_cache_entries", liveness::LiveUpdate, value_status::Used, 0, "Maximum amount of entries in expression cache.")
```
Comment (avikivity) [inline db/config.cc]: 0 means it will never be used. No one will edit the configuration.

File: alternator/expression_factory.cc [hunk 8]
```diff
@@ -0,0 +1,188 @@
...
+        lru_list.push_back(key_ref);
+    }
+public:
+    auto size() { return map.size(); }
+    void reserve(size_t n) { return map.reserve(n); }
+
+    // Lookup by string_view, move key to back, and return value
+    std::optional<std::reference_wrapper<Value>> find(std::string_view key) {
+        auto it = map.find(key);
+        if(it == map.end()) {
```
Comment (avikivity) [inline alternator/expression_factory.cc]: We leave a space after `if`, because `if` isn't a function.

File: alternator/expression_factory.cc [hunk 9]
```diff
@@ -0,0 +1,188 @@
...
+        return std::ref(it->second);
+    }
+
+    // Removes the least recently used item from the cache
+    // Returns true if an item was removed, false if the cache was empty
+    bool pop() {
+        if (!lru_list.empty()) {
+            auto it = map.find(lru_list.front());
+            lru_list.pop_front();
+            if(it != map.end()) { // This should be always true
```
Comment (avikivity) [inline alternator/expression_factory.cc]: Here too

Comment (avikivity) [reply alternator/expression_factory.cc]: If it's always true, add an on_internal_error() in the alternate path.

File: alternator/expression_factory.cc [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+    _cached_entries.reserve(_max_cache_entries);
+}
+
+expression_factory::expression_factory(expression_factory::config cfg, stats& stats) : 
+    _impl(std::make_unique<expression_factory_impl>(std::move(cfg), stats)) {
+}
+expression_factory::~expression_factory() = default;
+
+parsed::update_expression expression_factory::parse_update_expression(std::string_view query) {
+    //cache_logger.trace("Requesting update expression for query: {}", query);
```
Comment (avikivity) [inline alternator/expression_factory.cc]: Don't leave commented out code like that. Either it should be there or not.

File: alternator/expression_factory.cc [hunk 11]
```diff
@@ -0,0 +1,188 @@
...
+
+    template <typename Func, typename... Args>
+    using ParseResult = std::invoke_result_t<Func, std::string_view, Args...>;
+
+    template <stats::expression_types StatsType, typename Func, typename... Args>
+    ParseResult<Func, Args...> get_or_create(std::string_view query, Func&& parse_func, Args&&... other_args) {
+        if (_cfg.max_cache_entries == 0) {
+            return parse_func(query, std::forward<Args>(other_args)...);
+        }
+        auto value = _cached_entries.find(query);
```
Comment (avikivity) [inline alternator/expression_factory.cc]: Shouldn't the StatsType (it's not just for statistics, should be renamed) be part of the key? Or the same string in different roles would hit the cache.

**Comment by nyh** [comment]
> `perf-alternator` test shows improvement (median):
> test 	throughput 	instructions_per_op 	cpu_cycles_per_op 	allocs_per_op
> read 	+5.9% 	-8.6% 	-7.4% 	-4.9%
> write 	+13.6% 	-17.9% 	-15.8% 	-7.4%
> write (lwt) 	+5.6% 	-8.7% 	-5.6% 	-2.8%
> write_rwm 	+7.7% 	-11.0% 	-7.9% 	-4.1%

I dug into perf_alternator.cc to understand what expressions these different request types actually use - because obviously a read with no expressions will see a 0% improvement :-)
Turns out that "read" for example had a ProjectionExpression with 10 column names. "write" had a UpdateExpression. "write_rmw" had both ConditionExpression and UpdateExpression.
(this information may be useful in the commit message).

File: alternator/executor.cc [hunk 12]
```diff
@@ -200,19 +200,23 @@ executor::executor(gms::gossiper& gossiper,
...
       _enforce_authorization(_proxy.data_dictionary().get_config().alternator_enforce_authorization()),
-      _ssg(ssg)
+      _ssg(ssg),
+      _expression_factory(std::make_unique<expression_factory>(expression_factory::config{std::move(expression_max_cache_size)}, _stats))
 {
     s_default_timeout_in_ms = std::move(default_timeout_in_ms);
     register_metrics(_metrics, _stats);
 }
 
+executor::~executor() = default;
```
Comment (nyh) [inline alternator/executor.cc:255]: Is this change needed?

File: alternator/executor.cc [hunk 13]
```diff
@@ -200,19 +200,23 @@ executor::executor(gms::gossiper& gossiper,
...
+         utils::updateable_value<uint32_t> expression_max_cache_size)
     : _gossiper(gossiper),
       _proxy(proxy),
       _mm(mm),
       _sdks(sdks),
       _cdc_metadata(cdc_metadata),
       _enforce_authorization(_proxy.data_dictionary().get_config().alternator_enforce_authorization()),
-      _ssg(ssg)
+      _ssg(ssg),
+      _expression_factory(std::make_unique<expression_factory>(expression_factory::config{std::move(expression_max_cache_size)}, _stats))
```
Comment (nyh) [inline alternator/executor.cc]: Why does _expression_factory need to be a unique_ptr and can't be a direct member?
(maybe I'll see the answer later, this is a big patch...)

File: alternator/CMakeLists.txt [hunk 14]
```diff
@@ -17,6 +17,7 @@ target_sources(alternator
     streams.cc
     consumed_capacity.cc
     ttl.cc
+    expression_factory.cc
```
Comment (nyh) [inline alternator/CMakeLists.txt]: A thought while reading this:
The "expression factory" you created is not really an expression factor - it doesn't create expressions. Rather, it creates "parsed expressions" (one of the alternator::parsed::* types) so parsed_expression_factory, or more succinctly - it "parses" stuff. So perhaps it should be an expression_parser?

File: alternator/expression_factory.cc [hunk 15]
```diff
@@ -0,0 +1,188 @@
...
+ */
+
+#include "expressions.hh"
+#include "utils/log.hh"
+
+#include <boost/intrusive/list.hpp>
+#include <absl/container/node_hash_map.h>
+#include <optional>
+
+logging::logger cache_logger("alternator-cache");
```
Comment (nyh) [inline alternator/expression_factory.cc]: nitpick: please make the logger's name (the "alternator-cache") one related to the file's name if it's a file-local logger.

Also I suggest defining it as **static** and calling the variable **logger** - it makes everything easier to guess when you want to write logging code and need to start guessing the variable name.

File: alternator/expression_factory.cc [hunk 16]
```diff
@@ -0,0 +1,188 @@
...
+
+namespace alternator {
+namespace {
+
+template<typename Value>
+class lru_string_map {
+    struct key {
+        mutable boost::intrusive::list_member_hook<> list_hook;
+        seastar::sstring str;
```
Comment (nyh) [inline alternator/expression_factory.cc]: In Alternator we usually use std::string, not seastar::sstring. It made it easier to use rapidjson (see https://github.com/scylladb/seastar/issues/634), and this has become the norm in Alternator unless you're interoperating with the rest of Scylla.

File: alternator/expression_factory.cc [hunk 17]
```diff
@@ -0,0 +1,188 @@
...
+#include <absl/container/node_hash_map.h>
+#include <optional>
+
+logging::logger cache_logger("alternator-cache");
+
+namespace alternator {
+namespace {
+
+template<typename Value>
+class lru_string_map {
```
Comment (nyh) [inline alternator/expression_factory.cc]: I'll need to review this class in detail later, so I won't finish my review right now.
A quick grep yielded that we already have utils/lru.hh but no comments explaining what it is or whether we can reuse it :-(

I wonder if it wouldn't have easier for you and the readers if you just used STL's std::unordered_map plus std::list. It seems lang/wasm_instance_cache.hh does LRU this way.
And utils/loading_cache.hh does LRU with a simple pointer.
It seems everybody invented their own LRU :-)

But each one needs to be reviewed, and to be honest - also needs a unit test (which you're missing).

File: alternator/expression_factory.cc [hunk 18]
```diff
@@ -0,0 +1,188 @@
...
+        auto ret = map.insert_or_assign(key, std::move(value));
+        (ret.second ? touch<true>(ret.first) : touch<false>(ret.first));
+    }
+};
+}
+
+// Actual parsing functions are defined in alternator/expressions.cc
+parsed::update_expression parse_update_expression(std::string_view query);
+std::vector<parsed::path> parse_projection_expression(std::string_view query);
+parsed::condition_expression parse_condition_expression(std::string_view query, const char* caller);
```
Comment (nyh) [inline alternator/expression_factory.cc]: These declaration should be in a header file used by both this file and alternator/expression.cc - it helps check against differing signatures.
They were actually already in alternator/expression.hh. Did you remove them?

File: alternator/expression_factory.cc [hunk 19]
```diff
@@ -0,0 +1,188 @@
...
+        auto value = _cached_entries.find(query);
+        if (value) {
+            cache_logger.trace("Cache hit for query: {}", query);
+            _stats.expression_cache.requests[StatsType].hits++;
+            try {
+                return std::get<ParseResult<Func, Args...>>(value->get());
+            } catch (const std::bad_variant_access&) {
+                // Although nothing here prevents same query to be parsed into different types,
+                // in practice valid queries are different enough to not collide.
+                cache_logger.error("Cache hit for '{}' but type mismatch - it should never happen.", query);
```
Comment (nyh) [inline alternator/expression_factory.cc]: Avi's proposal above will solve this. I don't like this error log and the text that "should never happen" - a mischievous user can easily cause this by passing the same string to two types of expressions - e.g., pass "SET a=3" as an UpdateExpression, and then give "SET a=3" as a ConditionExpression and instead of getting the expected error, you'll get a scary error log (I hope you'll also get the parse error later, right?)

File: alternator/expressions.hh (hunk 4 above)
Comment (nyh) [reply alternator/expressions.hh]: I think (but I'm not sure I'm following everything here) it anyway needs to be a writable copy, because the "references" in the expression need to be replaced by the real value.

File: db/config.cc (hunk 7 above)
Comment (nyh) [reply db/config.cc]: I think you should also add a clarification that this is per-shard (how did we explain other per-shard numbers in the config?)

File: test/alternator/suite.yaml [hunk 20]
```diff
@@ -19,5 +19,6 @@ extra_scylla_config_options:
     alternator_timeout_in_ms: 30000,
     alternator_ttl_period_in_seconds: 0.5,
     alternator_streams_time_window_s: 0,
-    tablets_mode_for_new_keyspaces: enabled
+    tablets_mode_for_new_keyspaces: enabled,
+    alternator_max_expression_cache_entries: 0
```
Comment (nyh) [inline test/alternator/suite.yaml]: This will mean that the expression caching will never get tested by regular tests just using it.

File: test/alternator/test_filter_expression.py [hunk 21]
```diff
@@ -669,13 +669,13 @@ def test_filter_expression_and_sort_key_condition(test_table_sn_with_data):
 # In particular, test that FilterExpression may inspect attributes which will
 # not be returned by the query, because of the ProjectionExpression.
 # This test reproduces issue #6951.
-def test_filter_expression_and_projection_expression(test_table):
+def test_filter_expression_and_projection_expression(test_table_ss):
```
Comment (nyh) [inline test/alternator/test_filter_expression.py:672]: please move all these renamings to a separate patch (can be same PR, if you want).
I'm not sure why you decided to do this right now, but in any case it's not really related to the main patch.

**Review by nyh — COMMENTED** [review]
I couldn't review the whole thing in one sitting, so I'm leaving some comments and will have to review it again later. Sorry about that. You can make some changes before I come here again :-)

File: alternator/CMakeLists.txt (hunk 14 above)
Comment (m-szymon) [reply alternator/CMakeLists.txt]: It doesn't parse itself - but it manages object creation and knows how to parse if necessary. So to me it is a 'factory'.

> it doesn't create expressions

It creates expression objects. 'parsed expressions' are the only expression types (classes) we have. 
'Factory' implies that this is about objects, not strings - at least this is the convention I thought to be universal.
(Expression) factor creates (expression) objects.
(Expression) builder builds (expression) strings.

I am not against being more specific, I just don't agree that 'it doesn't create expressions'.
I will change the name to `parsed_expression_factory` in the end, as I suspect it would mess up the review.
Should the class be as well `parsed_expression_factory` or `parsed::expression_factory`?

File: alternator/executor.cc (hunk 13 above)
Comment (m-szymon) [reply alternator/executor.cc]: It can be a direct member, but this requires "expressions.hh" to be included in "executor.hh" and only 'executor.cc' really needs it.
I think `executor` as a whole should have a private implementation part with such members. So I am open to change 'expression_factory' now and wait for future refactoring.

File: alternator/executor.cc (hunk 12 above)
Comment (m-szymon) [reply alternator/executor.cc:255]: It is needed for `unique_ptr<expression_factory>`, which needs to know destructor of `expression_factory` and it is not known in the header.

File: alternator/expression_factory.cc (hunk 17 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: I have seen `utils/lru.hh`, but I don't know how to reuse it in general - and it implements two lists without a map-like lookup.
`utils/loading_cache.hh` is quite complex. It uses pointers, but it uses 'intrusive' implementation of both lru-list and a map, and handles ownership of the objects on it's own.
There is `ang/wasm_instance_cache.hh`, but I don't understand how it handles evictions - it seems that in `evict_lru()` it releases the stored value, but the key in the map stays.

The thing is that I don't want a LRU of values, but LRU of keys. Initially I implemented this with std::list, but it still required keeping addtional references. I think 'intrusive' implementation is exactly for such a situations.
I didn't use std::unordered_map due to some minor issues I had, that I am not sure are still valid. It should be easy to change to std::unordered map, but I don't think it would make anything easier.

File: alternator/expression_factory.cc (hunk 15 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]:
```
error: reference to 'logger' is ambiguous
note: candidate found by name lookup is 'seastar::logger'
```

File: alternator/expression_factory.cc (hunk 9 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: Done.

File: alternator/expression_factory.cc (hunk 18 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: > it helps check against differing signatures

It help in some (indeed not rare) cases of conflicting signatures, but often it still only fails at linking. Main purpose of headers is re-use and I don't want it to be re-used - only through 'factory'. So these declarations were replaced in `alternator/expression.hh` with 'factory' declaration.
Now these functions are only declared here and defined in `alternator/expressions.cc`. I will comply with recommendation, but which is it?
- move it back to `alternator/expression.hh`,
- move it to new header shared only by `expression_factory.cc` and `expressions.cc`,
- move whole expression_factory implemenatation to `alternator/expressions.cc`

File: alternator/expression_factory.cc (hunk 11 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: It is just for statistics. 
Splitting statistics made it bit uglier, but I decided it is worth to have it. I considered splitting also statistics per operation, but it would make this patch even bigger/would require changes in a lot of places, and I am not sure if it is needed. But it is still possible to add StatsType UPDATE_ITEM_CONDITION and PUT_ITEM_CONDITION (just needs to be called adequately). 
So this is orthogonal to `ParseResult` type, that could be mapped to same value included in the key.

Now "the same string in different roles would hit the cache", however valid expressions do not overlap:
- "update" needs reserved words SET/ADD/REMOVE/DELETE,
- "conditions" need some operators, other reserved names or signs that are not used in "projection".

Invalid request will not make it into a cache.
The only "problem" is that, if an invalid request hits existing (valid) cache it 'touches' the entry and prolongs its existence. But I don't think it is a problem.

File: alternator/expression_factory.cc (hunk 19 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: Maybe error is too scary, I can change it. 
You would get validation error and invalid expression will not mess the cache.

Otherwise is this a problem?

File: alternator/expressions.hh (hunk 4 above)
Comment (m-szymon) [reply alternator/expressions.hh]: yes, this would require changes in how expressions are "resolved" and used later.

File: db/config.cc (hunk 7 above)
Comment (m-szymon) [reply db/config.cc]: 1. I was not sure if it should be already enabled by default.
2. I have no intuition what would be a good default value.

File: test/alternator/test_filter_expression.py (hunk 21 above)
Comment (m-szymon) [reply test/alternator/test_filter_expression.py:672]: I was reviewing the tests to have better understanding of expressions, so I decided I can fix those few places.
But I shouldn't have squashed the commits.

File: test/alternator/suite.yaml (hunk 20 above)
Comment (m-szymon) [reply test/alternator/suite.yaml]: Yes, I considered tests with cache less deterministic - with each run it can hit shards with different pattern, so I thought it would be better to run all tests without cache (explicitly, regardless of default scylla setting) and have separate tests for cache.
But now I agree maybe it is not that good approach.

File: alternator/expressions.hh (hunk 4 above)
Comment (avikivity) [reply alternator/expressions.hh]: Well, cql3 expressions solve this by having immutable expressions evaluated by an evaluator.

We should consider merging the two, especially if we start to go crazy like jitting expressions.

File: db/config.cc (hunk 7 above)
Comment (avikivity) [reply db/config.cc]: To evaluate what would be a good default, we need to consider what's an upper bound on the number of expressions we'll cache and the memory usage of expressions.

Each expression more or less corresponds to a line of code in the application that calls into the DynamoDB SDK. A large application will likely have hundreds. A small application perhaps 10. So 2000 seems like a reasonable number.

The memory usage of an expression is likely very low, dozens of bytes. Even if it's 100 bytes, 2000*100 = 200kB, tiny compared to a shard. So 2000 is okay in that regard.

As long as the metrics allow us to understand if the cache isn't performing well, it's not too terrible if it's mis-sized.

File: alternator/expression_factory.cc (hunk 11 above)
Comment (avikivity) [reply alternator/expression_factory.cc]: Ok. Please add a comment explaining it.

**Comment by ScyllaPiotr** [comment]
Please make the cover letter contain only the description of the changes with at most only the synthetic measurement results. All the detailed empirical results should go into the discussion thread instead.

**Comment by ScyllaPiotr** [comment]
I propose the following changes to the cover letter:

_This patch allows caching, where input expression strings are mapped to template structures_ **that were parsed from earlier requests**.

_...individual instances still need to be resolved (~substituted~_ **supplemented** _with_ **the current** _names and values)._
(I see you copied my description, hence correcting here my own text)

Furthermore,
> Basic metrics (total count of hits and misses for each expression type and number of evictions) are implemented.
Added tests are based on metrics.

Is the current size of cache reported as well (per shard)?
I don't know how the metrics work, can the numbers be viewed per second / per minute too?

> "read" had a ProjectionExpression with 10 column names, "write" had a UpdateExpression with 10 column names and "write_rmw" had both ConditionExpression and UpdateExpression.

Is such traffic realistic?

File: alternator/controller.cc [hunk 22]
```diff
@@ -89,9 +89,13 @@ future<> controller::start_server() {
...
             return cfg.alternator_timeout_in_ms;
         };
+        auto get_max_expression_cache_entries_per_shard = [] (const db::config& cfg) -> utils::updateable_value<uint32_t> {
+            return cfg.alternator_max_expression_cache_entries_per_shard;
+        };
         _executor.start(std::ref(_gossiper), std::ref(_proxy), std::ref(_mm), std::ref(_sys_dist_ks),
                         sharded_parameter(get_cdc_metadata, std::ref(_cdc_gen_svc)), _ssg.value(),
-                        sharded_parameter(get_timeout_in_ms, std::ref(_config))).get();
+                        sharded_parameter(get_timeout_in_ms, std::ref(_config)),
+                        sharded_parameter(get_max_expression_cache_entries_per_shard, std::ref(_config))).get();
```
Comment (ScyllaPiotr) [inline alternator/controller.cc]: Out of curiosity, I wonder if a lambda would go there instead as well.

File: alternator/executor.cc (hunk 12 above)
Comment (ScyllaPiotr) [reply alternator/executor.cc:255]: It's and impl. of `~executor()`, not `~expression_factory()`

File: db/config.cc [hunk 23]
```diff
@@ -1395,6 +1395,7 @@ db::config::config(std::shared_ptr<db::extensions> exts)
     , alternator_allow_system_table_write(this, "alternator_allow_system_table_write", liveness::LiveUpdate, value_status::Used,
         false,
         "Allow writing to system tables using the .scylla.alternator.system prefix")
+    , alternator_max_expression_cache_entries_per_shard(this, "alternator_max_expression_cache_entries_per_shard", liveness::LiveUpdate, value_status::Used, 2000, "Maximum amount of entries in each shard's expression cache.")
```
Comment (ScyllaPiotr) [inline db/config.cc]: `Maximum amount of entries in each shard's expression cache` -> `Maximum number of cached parsed request expressions, per shard.`

File: alternator/expression_factory.cc [hunk 24]
```diff
@@ -0,0 +1,195 @@
...
+
+namespace alternator {
+namespace {
+
+template<typename Value>
+class lru_string_map {
+    struct key {
+        mutable boost::intrusive::list_member_hook<> list_hook;
+        std::string str;
+        explicit key(std::string_view s) : str(std::move(s)) {}
```
Comment (radoslawcybulski) [inline alternator/expression_factory.cc]: Use `key(std::string)` - caller might have a free std::string key lying around (in which case they will `std::move` into `key` object). Otherwise the caller will make a copy (instead of `key` constructor).

Also no point in `std::move` `std::string_view` :)

File: alternator/expression_factory.cc [hunk 25]
```diff
@@ -0,0 +1,195 @@
...
+            _stats.expression_cache.requests[StatsType].hits++;
+            try {
+                return std::get<ParseResult<Func, Args...>>(value->get());
+            } catch (const std::bad_variant_access&) {
+                // User can reach this code, by sending the same query string as a different expression type.
+                // In practice valid queries are different enough to not collide.
+                // Entries in cache are only valid queries.
+                // This request will fail at parsing below.
+                // If, by any chance this is a valid query, `push` below will update the cache with the new value.
+                logger_.error("Cache hit for '{}' but type mismatch.", query);
```
Comment (radoslawcybulski) [inline alternator/expression_factory.cc]: This might be spammable - if the user has two queries with different expression type and use both of them often will this error print every time? Can we add some sort of limit to this?

File: alternator/expression_factory.cc [hunk 26]
```diff
@@ -0,0 +1,195 @@
...
+        }
+        cached_expressions_types new_value = expr;
+        _cached_entries.push(query, std::move(new_value));
+        return expr;
+    }
+};
+
+expression_factory_impl::expression_factory_impl(expression_factory::config cfg, stats& stats) : 
+    _cfg(cfg), _max_cache_entries(_cfg.max_cache_entries), _stats(stats),
+    _max_cache_entries_observer(_cfg.max_cache_entries.observe([this] (const uint32_t &max_value) {
```
Comment (radoslawcybulski) [inline alternator/expression_factory.cc]: Nit: do we need `const &` for `uint32_t` here?

File: alternator/expression_factory.cc [hunk 27]
```diff
@@ -0,0 +1,195 @@
...
+        logger_.trace("Expression cache max entries changed to {}", max_value);
+        _max_cache_entries = max_value;
+        while (_cached_entries.size() > _max_cache_entries && _cached_entries.pop()) {
+            _stats.expression_cache.evictions++;
+        }
+        _cached_entries.reserve(_max_cache_entries); //but it never shrinks container
```
Comment (radoslawcybulski) [inline alternator/expression_factory.cc]: This feels redundant - `_cached_entries` once hits `_max_cache_entries` it never goes down, does it?

File: alternator/expression_factory.cc [hunk 28]
```diff
@@ -0,0 +1,195 @@
...
+            _stats.expression_cache.evictions++;
+        }
+        cached_expressions_types new_value = expr;
+        _cached_entries.push(query, std::move(new_value));
+        return expr;
+    }
+};
+
+expression_factory_impl::expression_factory_impl(expression_factory::config cfg, stats& stats) : 
+    _cfg(cfg), _max_cache_entries(_cfg.max_cache_entries), _stats(stats),
```
Comment (radoslawcybulski) [inline alternator/expression_factory.cc]: You're `std::move` `config` below, so you should probably move here as well for consistency.

File: test/alternator/test_expression_caching.py [hunk 29]
```diff
@@ -0,0 +1,360 @@
...
+@cache
+def alternator_max_expression_cache_entries(cql):
+    return int(list(cql.execute("SELECT value FROM system.config WHERE name = 'alternator_max_expression_cache_entries_per_shard'"))[0][0])
+
+# Context manager to temporarily change cache settings
+# Note: It flushes the cache, by first setting it to 0, then to the desired size.
+@contextmanager
+def cache_settings(cql, cache_size):
+    initial_cache_size = alternator_max_expression_cache_entries(cql)
+    cql.execute(f"UPDATE system.config SET value='0' WHERE name='alternator_max_expression_cache_entries_per_shard';")
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py]: I believe `config_value_context` class does what you need.

**Review by radoslawcybulski — COMMENTED** [review]
Amazing work!

File: alternator/CMakeLists.txt (hunk 14 above)
Comment (avikivity) [reply alternator/CMakeLists.txt]: > It creates expression objects. 

Yes, but so does any function that returns an expression. So it's not descriptive.

I think the most descriptive is prepared_expression_cache. Database people know the concept of statement/expression preparation well, and everyone knows what a cache is.

File: alternator/expression_factory.cc (hunk 17 above)
Comment (avikivity) [reply alternator/expression_factory.cc]: That was is for evictable caches - caches so large we might want to evict some items to free memory. Here we can stick with a fixed-size cache and evict only when we hit the size limit.

File: alternator/stats.cc [hunk 30]
```diff
@@ -155,6 +155,27 @@ static void register_metrics_with_optional_table(seastar::metrics::metric_groups
...
+            seastar::metrics::make_total_operations("expression_cache_misses", stats.expression_cache.requests[stats::expression_types::CONDITION_EXPRESSION].misses,
+                    seastar::metrics::description("Counts number of misses of cached expressions"), labels)(expression_label("ConditionExpression")).aggregate(aggregate_labels).set_skip_when_empty(),
+
+            seastar::metrics::make_total_operations("expression_cache_hits", stats.expression_cache.requests[stats::expression_types::PROJECTION_EXPRESSION].hits,
+                    seastar::metrics::description("Counts number of hits of cached expressions"), labels)(expression_label("ProjectionExpression")).aggregate(aggregate_labels).set_skip_when_empty(),
+            seastar::metrics::make_total_operations("expression_cache_misses", stats.expression_cache.requests[stats::expression_types::PROJECTION_EXPRESSION].misses,
+                    seastar::metrics::description("Counts number of misses of cached expressions"), labels)(expression_label("ProjectionExpression")).aggregate(aggregate_labels).set_skip_when_empty()
+    });
 }
```
Comment (avikivity) [inline alternator/stats.cc:179]: Once this gets merged, please work with @amnonh to get it visible in grafana.

File: test/alternator/test_expression_caching.py (hunk 29 above)
Comment (avikivity) [reply test/alternator/test_expression_caching.py]: yes

File: alternator/expression_factory.cc (hunk 17 above)
Comment (ScyllaPiotr) [reply alternator/expression_factory.cc]: Maybe in order for better code reusability it would be beneficial to have your LRU map implemented into `utils/lru.hh`, next to the one existing there. This way if anyone needed an LRU map (or cache) in the future, they would be able to find your implementation too and hopefully reuse it. You could add a comment there explaining which module uses the code at the time of your PR.

File: alternator/expression_factory.cc [hunk 31]
```diff
@@ -0,0 +1,195 @@
...
+static logging::logger logger_("parsed-expression-factory");
+
+namespace alternator {
+namespace {
+
+template<typename Value>
+class lru_string_map {
+    struct key {
+        mutable boost::intrusive::list_member_hook<> list_hook;
+        std::string str;
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: There's also a seastar string to consider...

File: alternator/expression_factory.cc [hunk 32]
```diff
@@ -0,0 +1,195 @@
...
+        using is_transparent = void;
+        size_t operator()(const key& k) const noexcept { return std::hash<std::string_view>{}(k.str); }
+        size_t operator()(std::string_view sv) const noexcept { return std::hash<std::string_view>{}(sv); }
+    };
+    struct key_equal {
+        using is_transparent = void;
+        bool operator()(const key& k, std::string_view sv) const noexcept { return k.str == sv; }
+        bool operator()(std::string_view sv, const key& k) const noexcept { return sv == k.str; }
+        bool operator()(const key& a, const key& b) const noexcept { return a.str == b.str; }
+    };
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: I wonder if these explicit declarations with `string_view` as a parameter could have been avoided by declaring type conversion of `key` into `string_view`. However, this would still allow the compiler not to use the provided conversion (and some other inefficient one instead), while your approach leaves no ambiguity.

File: alternator/expression_factory.cc [hunk 33]
```diff
@@ -0,0 +1,195 @@
...
+    lru_key_list lru_list;
+
+    // Move the accessed key to the back of the LRU list
+    template<bool IsNew=false> 
+    void touch(string_map::iterator it) {
+        // key is const, but it has mutable list_hook, so we remove constness
+        // to allow moving it in the list.
+        // This is safe because we only use this for moving keys in the LRU list,
+        // and we never modify the key itself.
+        key& key_ref = const_cast<key&>(it->first);
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: With `list_hook` already declared as `mutable`, why is the `const_cast` required?

File: alternator/expression_factory.cc [hunk 34]
```diff
@@ -0,0 +1,195 @@
...
+        if constexpr (!IsNew) {
+            lru_list.erase(lru_list.iterator_to(key_ref));
+        }
+        lru_list.push_back(key_ref);
+    }
+public:
+    auto size() { return map.size(); }
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: Maybe worth checking for `map.size() == lru_list.size()` and otherwise:
- emitting an error
- purging both containers

File: alternator/expression_factory.cc [hunk 35]
```diff
@@ -0,0 +1,195 @@
...
+        return std::ref(it->second);
+    }
+
+    // Removes the least recently used item from the cache
+    // Returns true if an item was removed, false if the cache was empty
+    bool pop() {
+        if (!lru_list.empty()) {
+            auto it = map.find(lru_list.front());
+            lru_list.pop_front();
+            if (it != map.end()) { // This should be always true
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: If not true, let's also purge both containers.

File: alternator/expression_factory.cc [hunk 36]
```diff
@@ -0,0 +1,195 @@
...
+        bool operator()(const key& k, std::string_view sv) const noexcept { return k.str == sv; }
+        bool operator()(std::string_view sv, const key& k) const noexcept { return sv == k.str; }
+        bool operator()(const key& a, const key& b) const noexcept { return a.str == b.str; }
+    };
+
+    using string_map = absl::node_hash_map<key, Value, key_hash, key_equal>;
+    string_map map;
+    using lru_key_list_hook = boost::intrusive::member_hook<key, boost::intrusive::list_member_hook<>,&key::list_hook>;
+    using lru_key_list = boost::intrusive::list<key, lru_key_list_hook>;
+    lru_key_list lru_list;
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: I'm almost sorry for raising this, but I find the variable name inadequate. It's more important what the list contains and less important what type it is (or how it behaves). Therefore, let's use the name `key_list`.

File: alternator/expression_factory.cc [hunk 37]
```diff
@@ -0,0 +1,195 @@
...
+            }
+            return true;
+        }
+        return false;
+    }
+
+    // Insert or update the value for the given key.
+    void push(std::string_view key, Value&& value) {
+        auto ret = map.insert_or_assign(key, std::move(value));
+        (ret.second ? touch<true>(ret.first) : touch<false>(ret.first));
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: `touch<ret.second>(ret.first)` instead? Although I'm not sure my proposal will compile...

File: alternator/expression_factory.cc [hunk 38]
```diff
@@ -0,0 +1,195 @@
...
+    expression_factory::config _cfg;
+    size_t _max_cache_entries;
+    stats& _stats;
+
+    using cached_expressions_types = std::variant<
+        parsed::update_expression,
+        parsed::condition_expression,
+        std::vector<parsed::path>
+    >;
+    lru_string_map<cached_expressions_types> _cached_entries;
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: For me it's unexpected for the factory to be the owner and the holder of all its products (parsed expressions). The class is more of a manager of cached expressions, or simply, parsed expressions cache.

File: alternator/expression_factory.cc [hunk 39]
```diff
@@ -0,0 +1,195 @@
...
+
+    template <typename Func, typename... Args>
+    using ParseResult = std::invoke_result_t<Func, std::string_view, Args...>;
+
+    // Caching layer for parsed expressions
+    // The expression type is determined only from the parsing function (ParseResult<Func, Args...>)
+    // StatsType is used only to update appropriate statistics - currently it is aligned with the expression type,
+    // but it could be extended in the future if needed, e.g. split per operation.
+    template <stats::expression_types StatsType, typename Func, typename... Args>
+    ParseResult<Func, Args...> get_or_create(std::string_view query, Func&& parse_func, Args&&... other_args) {
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: Masterpiece!

File: alternator/expression_factory.cc [hunk 40]
```diff
@@ -0,0 +1,195 @@
...
+    lru_string_map<cached_expressions_types> _cached_entries;
+    utils::observable<uint32_t>::observer _max_cache_entries_observer;
+
+    expression_factory_impl(expression_factory::config cfg, stats& stats);
+
+    template <typename Func, typename... Args>
+    using ParseResult = std::invoke_result_t<Func, std::string_view, Args...>;
+
+    // Caching layer for parsed expressions
+    // The expression type is determined only from the parsing function (ParseResult<Func, Args...>)
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: The expression type is determined ~only from the parsing function (ParseResult<Func, Args...>)~ be the type of the parsing function passed as a parameter, and the return type is exactly the same as the return type of this parsing function.

File: alternator/expression_factory.cc [hunk 41]
```diff
@@ -0,0 +1,195 @@
...
+        parsed::condition_expression,
+        std::vector<parsed::path>
+    >;
+    lru_string_map<cached_expressions_types> _cached_entries;
+    utils::observable<uint32_t>::observer _max_cache_entries_observer;
+
+    expression_factory_impl(expression_factory::config cfg, stats& stats);
+
+    template <typename Func, typename... Args>
+    using ParseResult = std::invoke_result_t<Func, std::string_view, Args...>;
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: Propose to add a comment: `// to define the polymorphic return type of get_or_create()`

File: alternator/expression_factory.cc [hunk 42]
```diff
@@ -0,0 +1,195 @@
...
+                _stats.expression_cache.requests[StatsType].hits--;
+            }
+        } else {
+            logger_.trace("Cache miss for query: {}", query);
+        }
+        ParseResult<Func, Args...> expr = parse_func(query, std::forward<Args>(other_args)...);
+        // Invalid query will throw here ^
+
+        _stats.expression_cache.requests[StatsType].misses++;
+        if (_cached_entries.size() >= _cfg.max_cache_entries && _cached_entries.pop()) {
```
Comment (ScyllaPiotr) [inline alternator/expression_factory.cc]: Propose ~if~ **while** for safety.

File: test/alternator/test_expression_caching.py [hunk 43]
```diff
@@ -0,0 +1,360 @@
...
+# But we can detect it from the metrics.
+
+
+# Helper function that gets the setting for alternator_max_expression_cache_entries.
+# This is cached as we use it only for getting the initial value.
+@cache
+def alternator_max_expression_cache_entries(cql):
+    return int(list(cql.execute("SELECT value FROM system.config WHERE name = 'alternator_max_expression_cache_entries_per_shard'"))[0][0])
+
+# Context manager to temporarily change cache settings
```
Comment (ScyllaPiotr) [inline test/alternator/test_expression_caching.py]: _Context manager to temporarily change cache settings **for the duration of the yield**_

File: test/alternator/test_expression_caching.py [hunk 44]
```diff
@@ -0,0 +1,360 @@
...
+        yield
+    finally:
+        cql.execute(f"UPDATE system.config SET value='{initial_cache_size}' WHERE name='alternator_max_expression_cache_entries_per_shard';")
+
+# Checks if actual cache metric increase (misses, hits, evictions) during the scope of this context match given expected values.
+# If misses, hits or evictions are None, they are not checked.
+# Labels are used to filter metrics, e.g. {'shard': 0, 'expression': 'UpdateExpression'}.
+# Note: evictions are filtered by shard label only (if given), as they are not per-expression.
+# If labels are None, no filtering is done.
+# If minimal is True, it checks that actual values are at least as high as expected.
```
Comment (ScyllaPiotr) [inline test/alternator/test_expression_caching.py]: Let's rename `minimal`, which (without this comment) would normally imply that the `cache_metrics_check` is minimal, to `allow_higher_values`.

File: test/alternator/test_expression_caching.py [hunk 45]
```diff
@@ -0,0 +1,360 @@
...
+    assert all(cmp(actual_metric_values[metric], expected_metric_values[metric]) for metric in expected_metric_values), \
+        f'cache metrics: {actual_metric_values} changed not as expected: {expected_metric_values}'
+
+# Helper function to change a value in the table using UpdateExpression and/or ConditionExpression.
+# Operation can be "put_item", "update_item" or "delete_item"
+# If operation is "put_item", it sets the value directly.
+# If operation is "update_item", it uses UpdateExpression to set the value.
+# If operation is "delete_item", it deletes the item.
+# If condition_fails is True, it uses ConditionExpression to ensure the value is not equal to the given value, which will fail if the value is already set.
+# If condition_fails is False, it uses ConditionExpression to ensure the value is equal to the given value, which will succeed if the value is already set.
```
Comment (ScyllaPiotr) [inline test/alternator/test_expression_caching.py]: This I find not clear.

File: test/alternator/test_expression_caching.py [hunk 46]
```diff
@@ -0,0 +1,360 @@
...
+def scylla_shard_count(metrics):
+    import re
+    matches = re.findall(r',shard="(\d+)"', get_metrics(metrics))
+    if not matches:
+        return 2 # by default tests are run with "--smp 2"
+    return 1+max(int(n) for n in matches)
+
+# Basic test to check that the expressions are cached at all. It uses only UpdateExpression.
+# It does not depend on the shard that handles each requests - requests are repeated and minimal values are checked,
+# so it will work even if the shards handling them would be changed during the test.
```
Comment (ScyllaPiotr) [inline test/alternator/test_expression_caching.py]: This is not clear for me.

File: test/alternator/test_expression_caching.py [hunk 47]
```diff
@@ -0,0 +1,360 @@
...
+# Helper function to change a value in the table using UpdateExpression and/or ConditionExpression.
+# Operation can be "put_item", "update_item" or "delete_item"
+# If operation is "put_item", it sets the value directly.
+# If operation is "update_item", it uses UpdateExpression to set the value.
+# If operation is "delete_item", it deletes the item.
+# If condition_fails is True, it uses ConditionExpression to ensure the value is not equal to the given value, which will fail if the value is already set.
+# If condition_fails is False, it uses ConditionExpression to ensure the value is equal to the given value, which will succeed if the value is already set.
+# If condition_fails is None, no ConditionExpression is used.
+# The function asserts that the value is set correctly in the table after the operation.
+def set_a_value(table, key, value, pattern='', operation="update_item", condition_fails=None):
```
Comment (ScyllaPiotr) [inline test/alternator/test_expression_caching.py]: With this level of processing, the function requires its own test ;-)

**Review by ScyllaPiotr — COMMENTED** [review]
Thank for this set. I am honestly impressed!

One thing that I find lacking here is the unit tests of the cache. You have provided an impressive and extensive test set based on correctness of the metrics of the cache (how many items are cached, the number of cache hits and misses), but there are no checks (tests) related to the actual content of the cache.

File: alternator/controller.cc (hunk 22 above)
Comment (m-szymon) [reply alternator/controller.cc]: You mean the argument to `sharded_parameter`? It is lambda. It could be inline, but it wouldn't be more readable.
It is tempting to use `std::mem_fn(&db::config::alternator_max_expression_cache_entries_per_shard)`, 
but I think the crucial part is the convertion to `updateable_value`, which probably must happen already here, and not implicitly, at sharded `executor` constructor.

File: alternator/executor.cc (hunk 12 above)
Comment (m-szymon) [reply alternator/executor.cc:255]: Yes, but default implementation of `~executor()` needs to know the `~std::unique_ptr<expression_factory>()`, which needs to know `~expression_factory()`.
An implicit (or explicit inline) destructor would be "implemented" already in the header file, which knows only that `expression_factory` exists and would not compile.

`expression_factory` is a private implementation and in my opinion its details shouldn't spill to all the headers.
`std::unique_ptr` has this small requirement for a complete type, but alternatives are raw pointers or e.g. std::shared_ptr - which has some minor overhead.

File: alternator/executor.hh (hunk 1 above)
Comment (m-szymon) [reply alternator/executor.hh:178]: Explained above.

File: alternator/expression_factory.cc (hunk 31 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: https://github.com/scylladb/scylladb/pull/25176#discussion_r2258062765

File: alternator/expression_factory.cc (hunk 24 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: The `std::move` is indeed a leftover form the time when it was a string and coping happend earlier.

The thing is the caller doesn't have free std::string. The input is string_view. 
So this is totally on purpose to make sure I am not missing anything and there is not excessive coping - I convert only when I really need it.

File: alternator/expression_factory.cc (hunk 36 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: I don't agree.
"lru" behaviour is the sole purpose of this member - if you need a "key list", why not iterate a "map"? And the fact that it links keys (and not some iterators, "entries", pairs, etc.) is a technicality.
In the code below when I "edit" this list it is clear that I don't change the "set" on the list, but the ordering.

File: alternator/expression_factory.cc (hunk 33 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: Because it doesn't compile. I guess there are too many levels of indirection.
`lru_list` doesn't allow a const object, even thought it could operate on the hook, and it doesn't allow direct hook reference, because it points to a whole object.
In this case `mutable` is just to be nice.

File: alternator/expression_factory.cc (hunk 37 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: It won't compile. 
I agree this looks weird here, but it saves one `if` in `find`, while keeping a single implementation of `touch`, which requires a longer comment due to `const_cast`.

File: alternator/expression_factory.cc (hunk 38 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: It owns a copy and it is its internal thing. From the outside you don't see it and once a expression is out it is not managed.
But everyone is against the name, so I will change it.

File: alternator/expression_factory.cc (hunk 41 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: Comment added, but this is not polymorphism.

File: alternator/expression_factory.cc (hunk 34 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: 1. If applied - I would use exception here and handle it externally. It should be 'const' function.
2. I am not convinced to so defensive approach:
If implementation is correct it will not happen. It doesn't depend on "user/caller" correct usage.
I am adding unit tests to confirm correctness.

File: alternator/expression_factory.cc (hunk 35 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: Similar to comment regarding `size()`. This one is a bit different - not checking `it` feels wrong, because you would use invalid pointers, which is not the case in other places. And I am changing it, as `erase` can be given a 'key' directly.

File: alternator/expression_factory.cc (hunk 27 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: Here it handles change of `_max_cache_entries`.
If it is decreased, the number of objects in cache goes down, but the container itself can't be shrunk - so in that case `reserve` does nothing.
If it is increased additional space in container is reserved.

File: test/alternator/test_expression_caching.py (hunk 29 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: Not exactly - here I set the value twice to flush preexisting entries.
But I will reuse `config_value_context`.

File: test/alternator/test_expression_caching.py (hunk 45 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: After some time - me either

File: test/alternator/test_expression_caching.py (hunk 46 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: Improved.

File: test/alternator/test_expression_caching.py (hunk 44 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: Done

File: test/alternator/test_expression_caching.py (hunk 43 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: Done

File: alternator/expression_factory.cc (hunk 26 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: no

File: alternator/expression_factory.cc (hunk 28 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: right

File: alternator/expression_factory.cc (hunk 25 above)
Comment (m-szymon) [reply alternator/expression_factory.cc]: In such case one of this expressions is invalid. If the user keeps sending invalid requests he will have other errors repeated anyway.

**Review by m-szymon — COMMENTED** [review]
Thanks for all the comments, I hope I considered them all.
I did some refactoring and I added unit tests.

File: alternator/expressions.g [hunk 48]
```diff
@@ -257,6 +257,13 @@ primitive_condition returns [parsed::primitive_condition c]:
          (',' v=value[0] { $c.add_value(std::move($v.v)); })*
          ')'
       )?
+      {
+          // Post-parse check to reject non-function single values
+          if ($c._op == parsed::primitive_condition::type::VALUE &&
+              !$c._values.front().is_func()) {
+              throw expressions_syntax_error("Single value must be a function");
+          }
```
Comment (nyh) [inline alternator/expressions.g:283]: I think your approach is good and can be kept.

I just wanted to comment that a more "traditional" approach would be to implement this syntax limitation in the parser definition itself (the so-called BNF, Backus–Naur form) - not in extra C++ code. 
Specifically, one way to do way to do this is to make primitive condition rule to be an "or" of two distinct cases:

1. A function call. This is not the existing "value" rule but a subset of which allows only a function call and not other types of values.
2. The existing content of the primitivecondition rule (i.e., any value followed by the other stuff) but the question mark at the end is removed, meaning that "the other stuff" is not optional - rather it is mandatory.

File: alternator/executor.cc [hunk 49]
```diff
@@ -2619,7 +2623,7 @@ future<executor::request_return_type> rmw_operation::execute(service::storage_pr
     });
 }
 
-static parsed::condition_expression get_parsed_condition_expression(rjson::value& request) {
+static parsed::condition_expression get_parsed_condition_expression(prepared_expression_cache& expression_cache, rjson::value& request) {
```
Comment (nyh) [inline alternator/executor.cc]: A thought:
Throughout Alternator we called the expressions after parsing, well..., "parsed expressions". We even have a namespace "parsed" and write things like `parsed::condition_expression` and so on, and here the function name is `get_parsed_condition_expression`.

So my question here is why should we invent a new concept, "prepared expression" - is it different from "parsed expression"? I think it isn't. I think it's confusing to introduce a new name for the existing concept.

File: alternator/executor.cc [hunk 50]
```diff
@@ -2728,7 +2732,7 @@ future<executor::request_return_type> executor::put_item(client_state& client_st
     auto start_time = std::chrono::steady_clock::now();
     elogger.trace("put_item {}", request);
 
-    auto op = make_shared<put_item_operation>(_proxy, std::move(request));
+    auto op = make_shared<put_item_operation>(*_prepared_expression_cache, _proxy, std::move(request));
```
Comment (nyh) [inline alternator/executor.cc]: Again, regarding the word "prepared", here I also want to note that in some functions you called the variable parameter "expression_cache" and here call it "_prepared_expression_cache", I think you should pick a consistent name for this variable.

File: alternator/executor.hh [hunk 51]
```diff
@@ -58,10 +58,6 @@ namespace alternator {
 
 class rmw_operation;
 
-namespace parsed {
-class path;
-};
```
Comment (nyh) [inline alternator/executor.hh:63]: Good riddance. I see this was never needed - attribute_path_map_node holds something "similar" to parsed::path, but doesn't use parsed::path, so this definition isn't needed.

File: alternator/executor.hh [hunk 52]
```diff
@@ -144,6 +141,8 @@ class executor : public peering_sharded_service<executor> {
     // forwarding Alternator request between shards - if necessary for LWT.
     smp_service_group _ssg;
 
+    std::unique_ptr<prepared_expression_cache> _prepared_expression_cache;
```
Comment (nyh) [inline alternator/executor.hh]: When I saw this a unique_ptr and not directly an object I guessed maybe you were to achieve the benefits of PIMPL without a separate impl class,  but then I looked below, and it seems like you do have prepared_expression_cache_impl, so you have two layers of PIMPL? That's a bit unorthodox, no?

File: alternator/prepared_expression_cache.cc [hunk 53]
```diff
@@ -0,0 +1,119 @@
...
+#include <variant>
+#include <seastar/core/on_internal_error.hh>
+
+static logging::logger logger_("prepared-expression-cache");
+
+namespace alternator {
+
+struct prepared_expression_cache_impl {
+    prepared_expression_cache::config _cfg;
+    size_t _max_cache_entries;
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc]: I think there's something wrong here: "_cfg" allows an **updateable** max_cache_entries (it can be changed via configuration long after this cache is created), while _max_cache_entries is not updateable. So which one takes affect? Why do you need both?

Comment (nyh) [reply alternator/prepared_expression_cache.cc]: Oh, I see you do handle this below, with an "observer". I think it's worth adding a comment in front of the two above lines explaining what happens if _cfg.max_cache_entries changes, and what _max_cache_entries contain.

File: alternator/prepared_expression_cache.cc [hunk 54]
```diff
@@ -0,0 +1,119 @@
...
+ */
+
+/*
+ * SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0
+ */
+
+#include "expressions.hh"
+#include "utils/log.hh"
+
+#include "utils/lru_string_map.hh"
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc:12]: I think you should add utils/lru_string_map.hh in a separate commit. This one is getting very long and hard to review, because it really contains 3 different things: 
1. A new lru_string_map - its implementation and tests.
2. A new expression_cache class.
3. Passing a expression_cache in a bunch of places and using it in a bunch of places.

File: alternator/prepared_expression_cache.cc [hunk 55]
```diff
@@ -0,0 +1,119 @@
...
+        parsed::condition_expression,
+        std::vector<parsed::path>
+    >;
+    lru_string_map<cached_expressions_types> _cached_entries;
+    utils::observable<uint32_t>::observer _max_cache_entries_observer;
+
+    prepared_expression_cache_impl(prepared_expression_cache::config cfg, stats& stats);
+
+    size_t evict_until_size(size_t n) {
+        try { // Very defensive approach - if impossible happens, we purge the cache
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc]: I don't know why evict_until_size() would throw logic_error, I don't know what "impossible" refers to (this is why I think you should put the new lru_string_map in a separate patch before this one). If it's really impossible, why didn't the utility call on_internal_error itself instead of  throwing logic_error?

File: alternator/prepared_expression_cache.cc [hunk 56]
```diff
@@ -0,0 +1,119 @@
...
+            _stats.expression_cache.requests[StatsType].hits++;
+            try {
+                return std::get<ParseResult<Func, Args...>>(value->get());
+            } catch (const std::bad_variant_access&) {
+                // User can reach this code, by sending the same query string as a different expression type.
+                // In practice valid queries are different enough to not collide.
+                // Entries in cache are only valid queries.
+                // This request will fail at parsing below.
+                // If, by any chance this is a valid query, `push` below will update the cache with the new value.
+                logger_.error("Cache hit for '{}', but type mismatch.", query);
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc]: I don't think users will know what to do about such "errors", but since it won't happen in practice (certainly not after you eliminated "a" as being a valid ConditionExpression), maybe it doesn't mater, so I'm not against.

File: alternator/prepared_expression_cache.cc [hunk 57]
```diff
@@ -0,0 +1,119 @@
...
+                _stats.expression_cache.requests[StatsType].hits--;
+            }
+        } else {
+            logger_.trace("Cache miss for query: {}", query);
+        }
+        ParseResult<Func, Args...> expr = parse_func(query, std::forward<Args>(other_args)...);
+        // Invalid query will throw here ^
+
+        _stats.expression_cache.requests[StatsType].misses++;
+        _stats.expression_cache.evictions += evict_until_size(_max_cache_entries - 1);
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc]: I hope this is a cheap operation that cannot stall. I guess I'll see later when I come to reviewing the implementation of the LRU cache.

File: alternator/prepared_expression_cache.cc [hunk 58]
```diff
@@ -0,0 +1,119 @@
...
+        cached_expressions_types new_value = expr;
+        _cached_entries.push(query, std::move(new_value));
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc]: nitpick: why two lines? Wouldn't it be shorter and nicer to write just
```
_cached_entries.push(query, cached_expressions_types{expr});
```
or even shorter (if there's an implicit constructor, or there's an emplace() method):
```
_cached_entries.emplace(query, expr);
```

File: alternator/prepared_expression_cache.cc [hunk 59]
```diff
@@ -0,0 +1,119 @@
...
+};
+
+prepared_expression_cache_impl::prepared_expression_cache_impl(prepared_expression_cache::config cfg, stats& stats) : 
+    _cfg(std::move(cfg)), _max_cache_entries(_cfg.max_cache_entries), _stats(stats),
+    _max_cache_entries_observer(_cfg.max_cache_entries.observe([this] (uint32_t max_value) {
+        logger_.trace("Expression cache max entries changed to {}", max_value);
+        _max_cache_entries = max_value;
+        if (_max_cache_entries > 0) {
+            _stats.expression_cache.evictions += evict_until_size(_max_cache_entries);
+            _cached_entries.reserve(_max_cache_entries); //it never shrinks container
```
Comment (nyh) [inline alternator/prepared_expression_cache.cc]: A thought (I still haven't seen the lru implementation so maybe I'll see the answer soon):

Are we guaranteed that if the cache grows or shrinks, and in general, moves, the actual objects in the cache (the expressions) do not move?

Comment (nyh) [reply alternator/prepared_expression_cache.cc]: I also don't understand the comment "it never shrinks container" - are you saying this as an explanation of why this is good (?), or are you saying it as some sort of FIXME - "It doesn't shrink, and it's bad! we need to fix it!".

File: alternator/stats.cc [hunk 60]
```diff
@@ -155,6 +155,27 @@ static void register_metrics_with_optional_table(seastar::metrics::metric_groups
             seastar::metrics::make_histogram("batch_item_count_histogram", seastar::metrics::description("Histogram of the number of items in a batch request"), labels,
                     [&stats]{ return estimated_histogram_to_metrics(stats.api_operations.batch_write_item_histogram);})(op("BatchWriteItem")).aggregate({seastar::metrics::shard_label}).set_skip_when_empty(),
     });
+
+    seastar::metrics::label expression_label("expression");
+    metrics.add_group(group_name, {
+            seastar::metrics::make_total_operations("expression_cache_evictions", stats.expression_cache.evictions,
+                    seastar::metrics::description("Counts number of evictions from expressions cache"), labels).aggregate(aggregate_labels).set_skip_when_empty(),
```
Comment (nyh) [inline alternator/stats.cc]: Are "evictions" the act of evicting a single entry, or the act of evicting many entries? If it's the former, maybe it's better to talk about "number of entries evicted from the expression cache" instead of "number of evictions".

File: test/alternator/test_expression_caching.py [hunk 61]
```diff
@@ -0,0 +1,352 @@
...
+# - scylla_alternator_expression_cache_misses,
+# - scylla_alternator_expression_cache_hits,
+# - scylla_alternator_expression_cache_evictions.
+# It assumes that cache works, when metrics report expected number of events.
+#
+# As the cache is per shard, the caching events for each request rely on the shard that processes them.
+# There are basic tests, checking minimal values, that work even if the shard handling the requests changes during the test.
+# The rest (checking exact values) strictly requires that all requests are handled by the same shard.
+# While in practice this is what happens (connection is reused), theoretically it is not guaranteed.
+# Optimally, the tests should be run with "--smp 1" or use shard-aware port (when it is implemented).
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: I would like to eliminate this risk, but and **not** with `--smp 1` and this shouldn't even be mentioned as an option... The test should work (unless absolutely impossibe) on any Alternator that someone runs anywhere, not just the one you know how to run manually yourself.

The way we eliminate this multi-shard "problem" in test/alternator/test_metrics.py is simple: Just sum the metrics over all shards. So if we do a request, we expect the total "hits" metric (for example), summed over all shards, to increase by 1 - we don't care on which shard it increased.

I see below you have a comment about a complication with LWT, I'll discuss this below.

File: test/alternator/test_expression_caching.py [hunk 62]
```diff
@@ -0,0 +1,352 @@
...
+# For now we monitor that new connections are not created during the test, so the shard is not changed.
+# If it happens, the test will be marked as xfail.
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: I don't think this is a good idea. Please consider the "sum on all shards" idea I proposed above as an alternative.

File: test/alternator/test_expression_caching.py [hunk 63]
```diff
@@ -0,0 +1,352 @@
...
+# We also need to know which shard was used (in case of LWT requests can be bounced and parsed again).
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: You're right that it's possible that an LWT request gets parsed twice and sort of ruin this test. I can think of two solutions:

One "solution" is more of a workaround: don't use LWT. See for example test_write_isolation.py, table_unsafe_rmw, for a table that never uses LWT even if you use ConditionExpression or UpdateExpression. I know this is kind of non-default and awkward, but since the expression parsing is the same, I think it's fine.

Alternatively, you should note that we also have a shard_bounce_for_lwt metric which you can read, and expect the number of cache misses (for example) to be equal 1 plus shard_bounce_for_lwt (so 1 in the typical case, 2 in the shard-bounced case).

The downside of the second solution is that it will be harder to test that you programmed it correctly (how can you force a shard bounce? Maybe if you run with many cores the chances will be higher?)

File: test/alternator/test_expression_caching.py [hunk 64]
```diff
@@ -0,0 +1,352 @@
...
+# Context manager to temporarily change cache settings for the duration of the yield
+# Note: It flushes the cache, by first setting it to 0, then to the desired size.
+@contextmanager
+def cache_settings(cql, cache_size):
+    with config_value_context(cql, 'alternator_max_expression_cache_entries_per_shard', '0'):
+        with config_value_context(cql, 'alternator_max_expression_cache_entries_per_shard', str(cache_size)):
+            # TODO: Ensure that the cache size is reset to the desired value - maybe get some metric showing current status
+            # for now sleep
+            import time
+            time.sleep(0.2)
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: I don't like this :-( Can't we make this change immediate?

In particular, I propose that every attempt to **use** the cache will check if the cache size is incorrect and resize it. The "observer" thing will only be needed for the case where somebody wants to shrink the cache and then never uses it for a long time.

File: test/alternator/test_expression_caching.py (hunk 47 above)
Comment (nyh) [reply test/alternator/test_expression_caching.py]: I wonder if this function actually made the tests easier to understand. I'm afraid the answer might be no, it makes things worse: For example, in tests below I saw a line like
```
set_a_value(test_table_s, p, next(counter), pattern='1')
```
I have no intuitive understanding what this does, and what the strange parameters like 'pattern=1' even mean.
I tried to translate the function call to what it actually does, and I think I got the following:
```
value = next(counter)
test_table_s.update_item(Key={'p': p}, UpdateExpression='SET a = :val1', ExpressionAttributeValues{'val1': value}'
assert table.get_item(Key={'p': p}, ConsistentRead=True)['Item']['a'] == value
```
Yes, without the function the code is a bit longer, but I claim - much easier to understand a year from now when you or someone else needs to come back to this test and understand it. You just look at this code and immediate see what it does and what it tests.

File: test/alternator/test_expression_caching.py [hunk 65]
```diff
@@ -0,0 +1,352 @@
...
+
+# Helper function to get the number of shards from metrics.
+# It looks for the 'shard' label in the metrics and returns the maximum shard number found.
+# If no shards are found, it returns 2 by default (as tests are run with "--smp 2" by default).
+@cache
+def scylla_shard_count(metrics):
+    import re
+    matches = re.findall(r',shard="(\d+)"', get_metrics(metrics))
+    if not matches:
+        return 2 # by default tests are run with "--smp 2"
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: How can we ever reach this case?

File: test/alternator/test_expression_caching.py [hunk 66]
```diff
@@ -0,0 +1,352 @@
...
+# and repeat requests to reach minimal number of events, even if each request is handled by a different shard.
+def test_caching_basic_workflow(cql, metrics, test_table_s):
+    with cache_settings(cql, 2):
+        p = random_string()
+        shards_count = scylla_shard_count(metrics)
+        counter = count(1)
+
+        with cache_metrics_check(metrics, evictions=0):
+            # All cache clean - must be a miss, no evictions
+            with cache_metrics_check(metrics, misses=1, allow_higher_values=True):
```
Comment (nyh) [inline test/alternator/test_expression_caching.py:115]: How can it be more than 1? Because of the LWT bouncing?

File: test/alternator/test_expression_caching.py [hunk 67]
```diff
@@ -0,0 +1,352 @@
...
+                set_a_value(test_table_s, p, next(counter), pattern='1')
+
+            # Repeat 'shards_count' times - at least one hit, no evictions
```
Comment (nyh) [inline test/alternator/test_expression_caching.py:118]: Interesting idea - you want to see a hit and each request may go to a different shard and get a miss, but after N requests you are guaranteed one hit.

I didn't understand this idea earlier when you tried to explain why the number of shards matter.

File: test/alternator/test_expression_caching.py [hunk 68]
```diff
@@ -0,0 +1,352 @@
...
+            with cache_metrics_check(metrics, hits=1, allow_higher_values=True):
+                for i in range(0, shards_count):
+                    set_a_value(test_table_s, p, next(counter), pattern='1')
+
+            # New pattern - must be a miss, no evictions
```
Comment (nyh) [inline test/alternator/test_expression_caching.py:123]: Until this moment I didn't understand that by "pattern" you meant an unparsed expression (the expression string).

File: test/alternator/test_expression_caching.py [hunk 69]
```diff
@@ -0,0 +1,352 @@
...
+# It does not depend on the shard that handles each request - we measure sums of events from all shards
+# and repeat requests to reach minimal number of events, even if each request is handled by a different shard.
+def test_caching_is_ever_evicted(cql, metrics, test_table_s):
+    cache_size = 2
+    with cache_settings(cql, cache_size):
+        p = random_string()
+        shards_count = scylla_shard_count(metrics)
+        counter = count(1)
+        patterns = cache_size*shards_count + 1
+        with cache_metrics_check(metrics, misses=patterns, evictions=1, allow_higher_values=True):
```
Comment (nyh) [inline test/alternator/test_expression_caching.py:142]: nice

File: test/alternator/test_expression_caching.py [hunk 70]
```diff
@@ -0,0 +1,352 @@
...
+            for i in range(0, patterns):
+                set_a_value(test_table_s, p, next(counter), pattern=i)
+
+# Context manager to ensure that all requests are handled by the same shard.
+# It yields the shard number of the existing connection determined by metrics of GetItem operation.
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: I made comments above about the number-of-shards, and later as I continued to review, I saw that you are summing counters over shards (like I suggested) and also used the number of shards in clever way to check hits.
But I am not happy about the "ensure that all requests are handled by the same shard" in this function. I think we need to figure out a way NOT to "ensure" this. I would like to see this function go away.

File: test/alternator/test_expression_caching.py [hunk 71]
```diff
@@ -0,0 +1,352 @@
...
+    con_shard = [ shard for shard,value in saved_metrics.items() if get_op_count(metrics, the_metrics, shard) - value == 1 ]
+    if len(con_shard) != 1:
+        pytest.xfail(f'Expected exactly one shard to handle the requests, but found {len(con_shard)}: {con_shard}')
+    yield con_shard[0]
+
+# Tests that UpdateExpression patterns are cached correctly - 
+# the first time we see an expression, it is a miss, then we have hits for the same pattern.
+# With full cache we have evictions along with misses.
+# It strictly requires that all requests are handled by the same shard, as it checks exact values.
+def test_caching_update_expression(cql, metrics, test_table_s, monkeypatch):
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: What is the "monkeypatch" fixture? I can't see to find it (nor do I understand why we need such a fixture).

File: test/alternator/test_expression_caching.py [hunk 72]
```diff
@@ -0,0 +1,352 @@
...
+            for i in range(5):
+                set_a_value(test_table_s, p, next(counter), pattern='A')
+                set_a_value(test_table_s, p, next(counter), pattern='B')
+
+        # Patterns 0 - 9
+        with cache_metrics_check(metrics, hits=0, misses=10, evictions=10, labels=labels):
+            for i in range(10):
+                set_a_value(test_table_s, p, next(counter), pattern=i)
+
+# Tests that ConditionExpression patterns are cached correctly -
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: Please mention that in this test you test ConditionExpression in UpdateTime, PutItem, DeleteItem. It wasn't obvious to me until I read the code more carefully.

File: test/alternator/test_expression_caching.py [hunk 73]
```diff
@@ -0,0 +1,352 @@
...
+        # PutItem/DeleteItem
+        with cache_metrics_check(metrics, hits=10, misses=2, evictions=2, labels=labels):
+            for i in range(3):
+                v = next(counter)
+                set_a_value(test_table_s, p, v, pattern='C', operation="put_item", condition_fails=False)
+                set_a_value(test_table_s, p, v, pattern='D', operation="put_item", condition_fails=True)
+                set_a_value(test_table_s, p, v, pattern='C', operation="delete_item", condition_fails=True)
+                set_a_value(test_table_s, p, next(counter), pattern='D', operation="delete_item", condition_fails=False)
+
+# Tests that ProjectionExpression patterns are cached correctly -
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: Again, please mention which request types you are testing with ProjectionExpression. I was happy to see you indeed test it for all of them, and not for one (e.g., GetItem).

File: test/alternator/test_expression_caching.py [hunk 74]
```diff
@@ -0,0 +1,352 @@
...
+        ret = {'a': 'hello'}
+
+        # fill cache
+        set_a_value(test_table_s, p, "hi", pattern='A')
+        set_a_value(test_table_s, p, "hello", pattern='B')
+
+        # Query
+        with cache_metrics_check(metrics, hits=6, misses=3, evictions=2, labels=labels):
+            for i in range(3):
+                assert full_query(test_table_s, ProjectionExpression="a", KeyConditionExpression='p=:p', FilterExpression='a=:a', ExpressionAttributeValues={':p': p, ':a': 'hello'}) == [ret]
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: Watch out - if you use the full_query() function you have no control on how many pages are retrieved, and if you retrieve 2 pages - i.e., call Query twice - the number of hits/misses/etc. will double.
In practice this will not cause you any trouble (since you know how many results are returned), but maybe it's better to just directly call one page of Query instead of calling the full_query() function?

File: test/boost/alternator_prepared_expression_cache_test.cc [hunk 75]
```diff
@@ -0,0 +1,183 @@
...
+        } else {
+            BOOST_REQUIRE_MESSAGE(!is_hit || !causes_eviction, "Invalid test setup");
+        }
+        BOOST_REQUIRE_EQUAL(stats, expected_stats);
+    }
+
+    co_return;
+}
+
+// Test that same strings can't be parsed to different expression types.
```
Comment (nyh) [inline test/boost/alternator_prepared_expression_cache_test.cc]: I'm a bit worried that maybe in the future we'll want to support some fourth kind of expression, and we won't be as lucky as to still have no string that can be parsed as two different types of expressions. Just for this reason, I would have used the expression type as part of the lookup key instead of part of the value.

But since the problem of extending the number of expressions syntaxes seems unlikely to happen soon, I don't insist on this at all.

File: utils/lru_string_map.hh [hunk 76]
```diff
@@ -0,0 +1,153 @@
...
+
+#pragma once
+
+#include <boost/intrusive/list.hpp>
+#include <absl/container/node_hash_map.h>
+#include <optional>
+#include <string>
+#include <string_view>
+
+// A simple LRU cache, mapping strings to values of type Value.
```
Comment (nyh) [inline utils/lru_string_map.hh:24]: Again, I think this class (and its test) belongs in a separate patch (in the same pull request), with its own explanation.
Here I'm curious how the new utils/lru_string_map.hh differs from utils/lru.hh (I am guessing they are different, but wondering if we could have used utils/lru.hh to implement this one).

File: utils/lru_string_map.hh [hunk 77]
```diff
@@ -0,0 +1,153 @@
...
+        size_t operator()(std::string_view sv) const noexcept { return std::hash<std::string_view>{}(sv); }
+    };
+    struct key_equal {
+        using is_transparent = void;
+        bool operator()(const key& k, std::string_view sv) const noexcept { return k.str == sv; }
+        bool operator()(std::string_view sv, const key& k) const noexcept { return sv == k.str; }
+        bool operator()(const key& a, const key& b) const noexcept { return a.str == b.str; }
+    };
+
+    using string_map = absl::node_hash_map<key, Value, key_hash, key_equal>;
```
Comment (nyh) [inline utils/lru_string_map.hh:77]: Asking of curiousity: Why use absl::node_hash_map instead of the more "usual" std::unordered_map?

File: utils/lru_string_map.hh [hunk 78]
```diff
@@ -0,0 +1,153 @@
...
+    lru_key_list lru_list;
+
+    // Move the accessed key to the back of the LRU list
+    template<bool IsNew=false> 
+    void touch(string_map::iterator it) {
+        // key is const, but it has mutable list_hook, so we remove constness
+        // to allow moving it in the list.
+        // This is safe because we only use this for moving keys in the LRU list,
+        // and we never modify the key itself.
+        key& key_ref = const_cast<key&>(it->first);
```
Comment (nyh) [inline utils/lru_string_map.hh:94]: If list_hook is mutable, it can be modified even on a const oject, so why is this const_cast needed?

File: utils/lru_string_map.hh [hunk 79]
```diff
@@ -0,0 +1,153 @@
...
+        lru_list.push_back(key_ref);
+    }
+public:
+    enum class sanity_check { none, basic, detailed };
+    // Returns the size of the cache.
+    // By default no sanity checks are performed.
+    // Optionally the level of sanity checks can be increased:
+    // - basic: checks that the size of the LRU list matches the size of the map
+    // - detailed: checks that all keys in the LRU list are present in the map
+    // Throws std::logic_error if the state is inconsistent.
```
Comment (nyh) [inline utils/lru_string_map.hh]: Why not on_internal_error()? Doesn't this indicate a bug? Or is there a way that the application can reach this situation?
With std::logic_error, you are just forcing the need to catch it and throw on_internal_error() on to the calling code.

Comment (nyh) [reply utils/lru_string_map.hh]: Any why are you creating three overloads of the function size() (with 3 template-parameter values for sanity_check) instead of having one "normal" size with no sanity checks, and another function for sanity-checking? Will we ever need checking on every call to size(), of all things?

File: utils/lru_string_map.hh [hunk 80]
```diff
@@ -0,0 +1,153 @@
...
+        }
+        return map.size();
+    }
+    void reserve(size_t n) { return map.reserve(n); }
+
+    // Clears all entries from cache
+    // If `release` is true, the memory used by the cache is released.
+    // Returns the number of entries removed.
+    size_t clear(bool release=false) {
+        lru_list.clear();
```
Comment (nyh) [inline utils/lru_string_map.hh]: Eventually, we will probably regret the fact that this function does a long loop without an ability to preempt. We'll probably need a `future<> clear_gently()` variant of this.

File: utils/lru_string_map.hh [hunk 81]
```diff
@@ -0,0 +1,153 @@
...
+        } else {
+            map.clear();
+        }
+        return ret;
+    }
+
+    // Lookup a value by a key
+    // If found, the value is moved to the back of the LRU list (most recently used).
+    // Returns std::nullopt if the key is not found.
+    std::optional<std::reference_wrapper<Value>> find(std::string_view key) {
```
Comment (nyh) [inline utils/lru_string_map.hh]: `std::optional<std::reference_wrapper<T>>` is the post-modern `T*`? :-)

File: utils/lru_string_map.hh [hunk 82]
```diff
@@ -0,0 +1,153 @@
...
+
+    // Evict items until the size is at most max_size.
+    // Returns the number of evicted items.
+    // Optionally it can use sanity checks (see size() for details).
+    template<sanity_check check=sanity_check::none>
+    size_t evict_until_size(size_t max_size) {
+        size_t ss, is;
+        ss = is = size<check>();
+        while (ss > max_size && pop()) {
+            ss = size<check>();
```
Comment (nyh) [inline utils/lru_string_map.hh]: What's the point of calling size() again and again (especially if sanity_check is not NONE)? Aren't we sure that every pop() will decrease it by exactly 1? What am I missing?

File: alternator/expressions.g [hunk 83]
```diff
@@ -230,7 +230,7 @@ update_expression_clause returns [parsed::update_expression e]:
 // Note the "EOF" token at the end of the update expression. We want to the
 //  parser to match the entire string given to it - not just its beginning!
 update_expression returns [parsed::update_expression e]:
-    (update_expression_clause { e.append($update_expression_clause.e); })* EOF;
+    (update_expression_clause { e.append($update_expression_clause.e); })+ EOF;
```
Comment (nyh) [inline alternator/expressions.g:251]: Nice catch. There was nothing "wrong" in the old code, but I agree it's nicer to have the parser's BNF contain the really allowed syntax instead of allowing bad syntax and then later double-checking and rejecting.

Comment (nyh) [reply alternator/expressions.g:251]: By the way, as I commented in test_update_expression_empty(), the empty UpdateExpression didn't **have** to be forbidden, and I don't know why it was forbidden. It's all very lucky for the caching implementation :-)

Comment (m-szymon) [reply alternator/expressions.g:251]: Quite often being strict is making things harder for the client, but easier for the server.
However this case is not THAT important for caching. 
The worst case we want to avoid is when same string is truly valid for two or more types (two success paths compete).
Slightly less bad is, if a valid text of one type is correctly parsed and cached as another one - error path influences success path.
But here other expression were already rejected, so even if empty update pollutes the cache - it is a minor issue. There are other cases like that (e.g. I think `size(a,a)` parses as a valid value) and I don't think it would be worth "fixing".

File: alternator/controller.cc (hunk 22 above)
Comment (ScyllaPiotr) [reply alternator/controller.cc]: By definition lambda is an unnamed function.
I'd be happy to understand why it's
```
auto get_max_expression_cache_entries_per_shard = [] (const db::config& cfg) -> utils::updateable_value<uint32_t> {
    return cfg.alternator_max_expression_cache_entries_per_shard;
};
```
and
`sharded_parameter(get_max_expression_cache_entries_per_shard, std::ref(_config))`

and not this:

```
auto get_max_expression_cache_entries_per_shard = [&_config] () -> utils::updateable_value<uint32_t> {
    return _config.alternator_max_expression_cache_entries_per_shard;
};
```
and
`sharded_parameter(get_max_expression_cache_entries_per_shard)`

which in turn would allow to just put a single line instead of the two places:

`sharded_parameter([&_config] () -> utils::updateable_value<uint32_t> { return _config.alternator_max_expression_cache_entries_per_shard; });`

File: alternator/expression_factory.cc (hunk 33 above)
Comment (ScyllaPiotr) [reply alternator/expression_factory.cc]: Stopped reading at `Because it [otherwise] doesn't compile.` ;-)

File: alternator/expression_factory.cc (hunk 34 above)
Comment (ScyllaPiotr) [reply alternator/expression_factory.cc]: > 1. If applied - I would use exception here and handle it externally. It should be 'const' function.

No, that's not what I suggested. Emit only an error-level log msg, especially that the remedy (purging of both containers) resolves the error.

> 2. I am not convinced to so defensive approach:
>        If implementation is correct it will not happen. It doesn't depend on "user/caller" correct usage.
>        I am adding unit tests to confirm correctness.

If the code is correct, the mechanism I'm proposing will never be triggered, so there's no harm in adding this and the triggering condition is easy enough to be sure to be flawless (regarding the risk of false-execution).

File: alternator/expression_factory.cc (hunk 35 above)
Comment (ScyllaPiotr) [reply alternator/expression_factory.cc]: It's outdated so I can't view the relevant code anymore.
Anyway, https://github.com/scylladb/scylladb/pull/25176#discussion_r2257601796

File: alternator/expression_factory.cc (hunk 36 above)
Comment (ScyllaPiotr) [reply alternator/expression_factory.cc]: > "lru" behaviour is the sole purpose of this member 

Agreed, but you'd still like to know what does this list contain. The `lru_key_list` as a variable name would satisfy us both, but it's taken already as the type name... Maybe append `_type` to the name of the type?

File: alternator/expression_factory.cc (hunk 37 above)
Comment (ScyllaPiotr) [reply alternator/expression_factory.cc]: I agree, it's very clever!

File: alternator/controller.cc (hunk 22 above)
Comment (m-szymon) [reply alternator/controller.cc]: Honestly I don't know.
I followed the pattern for `get_timeout_in_ms` (https://github.com/scylladb/scylladb/pull/13300) and I thought I understand reasons, but looking deeper I don't see it.
I suspect your proposal would be valid. Maybe it is just a matter of convention?
If the `_config` was `sharded<>` then it would matter, but here it is simply forwarded. Now I doubt if `sharded_parameter` is even necessary. @nyh ?

File: alternator/executor.cc (hunk 49 above)
Comment (m-szymon) [reply alternator/executor.cc]: I agree parsed::expression_cache will be a more consistent name.
`prepared_expression_cache` was @avikivity's idea, when we discussed my previous naming - 'factory'. 
I still think that it is not intuitive to parse things inside a cache, but I will not argue about names.

File: alternator/executor.cc (hunk 50 above)
Comment (m-szymon) [reply alternator/executor.cc]: as above

File: alternator/executor.hh (hunk 52 above)
Comment (m-szymon) [reply alternator/executor.hh]: That's because I like PIMPL :).
But more seriously the executor probably should already have its own private implementation. At least I don't like the idea of including "expressions" header here.
On the other hand cache itself has its private part. If I must I would remove that second layer, but on its own it is fine. It looks weird, only because of executor.

File: alternator/prepared_expression_cache.cc (hunk 54 above)
Comment (m-szymon) [reply alternator/prepared_expression_cache.cc:12]: done

File: alternator/prepared_expression_cache.cc (hunk 53 above)
Comment (m-szymon) [reply alternator/prepared_expression_cache.cc]: I think I don't need `_cfg.max_cache_entries`, as I keep the observer.

File: alternator/prepared_expression_cache.cc (hunk 56 above)
Comment (m-szymon) [reply alternator/prepared_expression_cache.cc]: It can happen if the user repeats expression as a different types.
But he should get also parsing error next, so maybe it is not necessary.

File: alternator/prepared_expression_cache.cc (hunk 55 above)
Comment (m-szymon) [reply alternator/prepared_expression_cache.cc]: `lru_string_map` is a more generalized structure with "public" header. Potentially it could be reused in other contex (but maybe we shouldn't care about it now?). It could call `on_internal_error`, but the message would be very general. Here we not only use our local logger, but we can write how we solve it.
And that's the second point - in this context we can recover from that situation. But it may make no sense if `lru_string_map` is used in another context. 

I am sure it will not happen, but I may be wrong. It was added after https://github.com/scylladb/scylladb/pull/25176#discussion_r2307358307

File: alternator/prepared_expression_cache.cc (hunk 57 above)
Comment (m-szymon) [reply alternator/prepared_expression_cache.cc]: In 'normal' case we evict only by one, so it is cheap.
The other case is when we limit the max cache size. It is 'live updateable' mostly for the testing - I don't expect it to be used often. So if you evict really large number - it may get expensive. Workaround is to decrease size gradually. 
And finally there is "impossible" case when cache internal state is corrupted and we purge it.

File: alternator/prepared_expression_cache.cc (hunk 59 above)
Comment (m-szymon) [reply alternator/prepared_expression_cache.cc]: It is based on `node_hash_map` and to my understanding it guarantees that objects are not moved.

"it never shrinks container" is neither good nor bad. It is just a reminder, that may not be clear - if we reduce the cache size, this function does nothing.
If we want to reduce real container capacity (because we've set it to some ridiculously large number) we need to first disable/flush it.

File: alternator/stats.cc (hunk 60 above)
Comment (m-szymon) [reply alternator/stats.cc]: the former - fixed

**Comment by ScyllaPiotr** [comment]
> Please make the cover letter contain only the description of the changes with at most only the synthetic measurement results. All the detailed empirical results should go into the discussion thread instead.

I believe you either missed this comment, or decided against these suggestions.
Additionally, you're not fixing #5023, but you're definitely refering to it (`refs`).

File: test/boost/alternator_prepared_expression_cache_test.cc (hunk 75 above)
Comment (m-szymon) [reply test/boost/alternator_prepared_expression_cache_test.cc]: It wouldn't be difficult to extend for that case.
Where would be best place to note it, if ever such a need arise?

File: test/alternator/test_expression_caching.py (hunk 65 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: I don't know.
Should it just fail at this point?

File: test/alternator/test_expression_caching.py (hunk 63 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: As you have seen it is not only LWT.
If we check minimal number of events in a sum - we don't care if LWT doubled it.
If we want exact numbers - we still have to use single shard and LWT won't affect its metrics. We just need to know which shard. Without LWT we could use a sum - other shard would be all 0.
I think figuring out which shard we use (when we already need to control it) is a simpler solution.

File: test/alternator/test_expression_caching.py (hunk 61 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: I removed mention of `--smp 1`, as I agree that is not an option.
The only good option I see is having shard-aware port.

File: test/alternator/test_expression_caching.py (hunk 70 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: As I wrote above, the only good option (with this testing approach) would be having shard-aware port.
It is hard to see if cache works on anything else than metrics.
With arbitrary number of shards, with each subsequent request the space of possible results is growing dramatically. And we want to test deterministically here.

However, after I added unit tests the "exact numbers" are checked there.
So the option is to make these test "shard-aware" ready and xfail until it is implemented. In practice the shard is fixed with reused connection, but I don't want to add potentially flaky tests to CI.
Still it should be tested that all the requests types actually use cache, but it doesn't have to be exact values. So maybe I should drop the idea of exact numbers test here?

File: test/alternator/test_expression_caching.py (hunk 71 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: It is bulit-in pytest fixture. I use it in `sticky_shard_connection` to replace a function implementation.

File: test/alternator/test_expression_caching.py (hunk 72 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: done

File: test/alternator/test_expression_caching.py (hunk 73 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: done

File: test/alternator/test_expression_caching.py (hunk 74 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: Right. But is it possible when there is exactly one result to return?

File: utils/lru_string_map.hh (hunk 78 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:94]: https://github.com/scylladb/scylladb/pull/25176#discussion_r2316278079
`lru_list` doesn't know the hook is mutable.

File: test/alternator/test_expression_caching.py (hunk 47 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: I agree that the function was not the pretties one and had to be fixed. Especially including various operations went too far.

I almost bought @nyh argument that maybe it doesn't make the tests easier to understand.
I knew it was very convenient when writing tests - but for reading them I am not the best person to judge my code.
So I started unwrapping it, which wasn't hard, esp. with help of AI. And I got lost.
There were all similar lines, with minor differences (or not) hard to notice. I wasn't sure I didn't make mistake - I could see what the code does, but I wasn't sure if this is what I wanted. Maybe it is still personal thing (I hate scrolling back and forth to see whole context) and maybe I would have had a different opinion, if I didn't do it on a laptop screen.

I reverted it and just tried to do some things more readable.

File: test/alternator/test_expression_caching.py (hunk 64 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: That is something I wasn't sure - how config works with sharding.
If I understand correctly the observer doesn't matter - it is called synchronously after updating the value:
https://github.com/scylladb/scylladb/blob/9bca90be0d3ced7c5a1d79178c0e36dbcd16b5ea/utils/updateable_value.hh#L136-L139
I investigated it even further in `db/virtual_tables.cc` and I am convinced that at this point all shards must have been notified.
So waiting can be removed.

File: utils/lru_string_map.hh (hunk 76 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:24]: https://github.com/scylladb/scylladb/pull/25176#discussion_r2259578038

File: utils/lru_string_map.hh (hunk 77 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:77]: I guess the main reason was pointer stability. 
But also heterogeneous lookup is not yet fully supported - e.g in insert_or_assign.

File: utils/lru_string_map.hh (hunk 81 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: yes - pointers are too scary :)

File: utils/lru_string_map.hh (hunk 79 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: It indicates bug. Not on_internal_error here because caller can give much more specific message.
But also potentially we can recover from that situation. It was added after https://github.com/scylladb/scylladb/pull/25176#discussion_r2307358307 and https://github.com/scylladb/scylladb/pull/25176#discussion_r2307365764
I am using 'detailed check' in unit tests. Having overloads makes it easier to use in `evict_until_size` with the same options.

File: utils/lru_string_map.hh (hunk 82 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: If the list would contain elements not from the map (and maybe not all elements from the map) at some point pop will decrease only list. So we call size to actually trigger sanity check and we don't loop precalculated number of times, but until reached size of map. Sanity check is reading a size.

File: utils/lru_string_map.hh (hunk 80 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: I wouldn't add it here. Just a warning comment.
Limiting the cache size is responsibility of the caller. The caller can decrease the size gradually with preempts before final clearing. Between the calls cache remains valid - no race conditions.
`clear_gently` could do the same thing - but caller still would have to manage its `max_size` e.g not to allow other async function to add to many new entries. So this doesn't make things easier.
`clear_gently` could be slightly more efficient by not caring about preserving cache validity during preempts. But it just asking for race condition, it is not worth it and I wouldn't add it before we really want to use it somewhere.

**Comment by nyh** [comment]
@m-szymon, @swasik told me this patch was waiting for my review, is this true?

I didn't see you answered most of my questions and comments from the previous review. It is perfectly fine to reply to my comment that you disagree (hopefully with an explanation why), I can be wrong too (and often am), but if you don't reply at all I have no idea if you disagreed with my comment, already implemented, or what.

As I noted in my review, I thought overall your patch was very good, and I just had small comments. But we need to handle those too.

Also I asked for a slightly bigger change to the structure of the pulll request:

> The third patch is massive and I would like you to please split it so at least the new util/lru_string_map will a separate patch, and also probably the expression cache class can be a separate patch that is only used (in a few dozen places) in the following patch.

**Comment by m-szymon** [comment]
> Please make the cover letter contain only the description of the changes with at most only the synthetic measurement results. All the detailed empirical results should go into the discussion thread instead.

Updated `perf-alternator` runs:

| test | throughput | instructions_per_op | cpu_cycles_per_op | allocs_per_op |
| ------ | ---------------- | ----------------------------- | --------------------------- | -------------------  |
| read | +6.0% | -8.5% | -7.0% | -4.9% |
| write | +13.4% | -17.6% | -14.7% | -7.4% |
| write(lwt) | +12.7% | -7.9% | -6.9% | -2.8% |
| write_rwm | +5.4% | -10.5% | -7.3% | -4.1% |

```
./build/release/scylla perf-alternator --options-file /mnt/xfsram/scylla.yaml --smp 1 --cpuset 0 --alternator-port 8000 --io-properties-file /mnt/xfsram/io_properties.yaml --default-log-level error --flush 1 --duration 30 ...
Disable expressions cache / isolation: only_rmw_uses_lwt
Running test with config: {workload=read, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
Creating 10000 partitions...
Flushing partitions...
18662.16 tps (388.6 allocs/op,   0.0 logallocs/op,  42.4 tasks/op,  187847 insns/op,   77172 cycles/op,        0 errors)
18802.89 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187858 insns/op,   77825 cycles/op,        0 errors)
19334.11 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187868 insns/op,   77007 cycles/op,        0 errors)
19396.53 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187921 insns/op,   76685 cycles/op,        0 errors)
19342.29 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187862 insns/op,   76893 cycles/op,        0 errors)
17353.04 tps (390.2 allocs/op,   0.0 logallocs/op,  42.8 tasks/op,  189162 insns/op,   80198 cycles/op,        0 errors)
15922.05 tps (391.1 allocs/op,   0.0 logallocs/op,  43.0 tasks/op,  189685 insns/op,   85250 cycles/op,        0 errors)
17139.75 tps (389.8 allocs/op,   0.0 logallocs/op,  42.6 tasks/op,  188920 insns/op,   81627 cycles/op,        0 errors)
18117.31 tps (389.5 allocs/op,   0.0 logallocs/op,  42.5 tasks/op,  188851 insns/op,   79404 cycles/op,        0 errors)
19092.13 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187797 insns/op,   77259 cycles/op,        0 errors)
19271.98 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187825 insns/op,   76910 cycles/op,        0 errors)
18393.65 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187790 insns/op,   79192 cycles/op,        0 errors)
19100.02 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187855 insns/op,   77665 cycles/op,        0 errors)
19224.12 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187757 insns/op,   76875 cycles/op,        0 errors)
19373.44 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187864 insns/op,   76806 cycles/op,        0 errors)
19326.64 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187915 insns/op,   76927 cycles/op,        0 errors)
19429.47 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187895 insns/op,   76544 cycles/op,        0 errors)
18632.79 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187828 insns/op,   78433 cycles/op,        0 errors)
19363.81 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187743 insns/op,   76864 cycles/op,        0 errors)
19444.08 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187880 insns/op,   76667 cycles/op,        0 errors)
19297.43 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187807 insns/op,   76672 cycles/op,        0 errors)
18771.28 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187796 insns/op,   78103 cycles/op,        0 errors)
18846.26 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187785 insns/op,   78154 cycles/op,        0 errors)
19463.70 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187746 insns/op,   76420 cycles/op,        0 errors)
19380.72 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187833 insns/op,   76641 cycles/op,        0 errors)
18331.35 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187808 insns/op,   78874 cycles/op,        0 errors)
19112.57 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187812 insns/op,   77528 cycles/op,        0 errors)
18931.34 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187797 insns/op,   77939 cycles/op,        0 errors)
19333.96 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187752 insns/op,   76889 cycles/op,        0 errors)
19271.42 tps (388.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  187799 insns/op,   76700 cycles/op,        0 errors)
throughput:
	mean=   18855.18 standard-deviation=819.89
	median= 19224.12 median-absolute-deviation=478.78
	maximum=19463.70 minimum=15922.05
instructions_per_op:
	mean=   188007.26 standard-deviation=485.29
	median= 187827.53 median-absolute-deviation=200.30
	maximum=189684.61 minimum=187743.50
cpu_cycles_per_op:
	mean=   77894.83 standard-deviation=1877.59
	median= 77007.10 median-absolute-deviation=1019.59
	maximum=85249.76 minimum=76420.20

Enable expressions cache / isolation: only_rmw_uses_lwt
Running test with config: {workload=read, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
Creating 10000 partitions...
Flushing partitions...
18893.95 tps (369.6 allocs/op,   0.0 logallocs/op,  42.4 tasks/op,  171964 insns/op,   73283 cycles/op,        0 errors)
19596.69 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171870 insns/op,   73037 cycles/op,        0 errors)
20208.58 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171848 insns/op,   72186 cycles/op,        0 errors)
20260.73 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171947 insns/op,   71846 cycles/op,        0 errors)
20381.25 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171909 insns/op,   71420 cycles/op,        0 errors)
20318.20 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171860 insns/op,   71320 cycles/op,        0 errors)
19750.95 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171978 insns/op,   73119 cycles/op,        0 errors)
20533.64 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171993 insns/op,   71157 cycles/op,        0 errors)
20284.21 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172009 insns/op,   71837 cycles/op,        0 errors)
20322.14 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171869 insns/op,   71327 cycles/op,        0 errors)
20451.40 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171868 insns/op,   71362 cycles/op,        0 errors)
19886.49 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171919 insns/op,   72800 cycles/op,        0 errors)
20413.41 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171939 insns/op,   71455 cycles/op,        0 errors)
20374.20 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172011 insns/op,   71188 cycles/op,        0 errors)
20509.41 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171978 insns/op,   71247 cycles/op,        0 errors)
20519.84 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171931 insns/op,   71114 cycles/op,        0 errors)
19823.00 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171876 insns/op,   72532 cycles/op,        0 errors)
20100.63 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171751 insns/op,   71933 cycles/op,        0 errors)
20449.57 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172020 insns/op,   71339 cycles/op,        0 errors)
20508.27 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172010 insns/op,   71335 cycles/op,        0 errors)
20435.66 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171815 insns/op,   71439 cycles/op,        0 errors)
19874.46 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171848 insns/op,   72303 cycles/op,        0 errors)
20354.93 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172073 insns/op,   71703 cycles/op,        0 errors)
20404.59 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171939 insns/op,   71615 cycles/op,        0 errors)
20420.45 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171864 insns/op,   71322 cycles/op,        0 errors)
20406.02 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172032 insns/op,   71177 cycles/op,        0 errors)
20212.00 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171936 insns/op,   71888 cycles/op,        0 errors)
20376.57 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171991 insns/op,   71633 cycles/op,        0 errors)
20372.56 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  172018 insns/op,   71678 cycles/op,        0 errors)
20004.74 tps (369.1 allocs/op,   0.0 logallocs/op,  42.2 tasks/op,  171980 insns/op,   72134 cycles/op,        0 errors)
throughput:
	mean=   20260.50 standard-deviation=253.95
	median= 20372.56 median-absolute-deviation=159.87
	maximum=20533.64 minimum=19596.69
instructions_per_op:
	mean=   171933.94 standard-deviation=76.38
	median= 171938.72 median-absolute-deviation=64.49
	maximum=172072.60 minimum=171751.45
cpu_cycles_per_op:
	mean=   71739.58 standard-deviation=566.28
	median= 71615.33 median-absolute-deviation=404.56
	maximum=73119.36 minimum=71114.16

Disable expressions cache / isolation: only_rmw_uses_lwt
Running test with config: {workload=write, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
11049.97 tps (424.5 allocs/op,   9.6 logallocs/op,  43.5 tasks/op,  300424 insns/op,  119845 cycles/op,        0 errors)
12044.99 tps (423.0 allocs/op,   9.1 logallocs/op,  43.1 tasks/op,  303180 insns/op,  118272 cycles/op,        0 errors)
12300.18 tps (424.3 allocs/op,   9.1 logallocs/op,  43.0 tasks/op,  305960 insns/op,  117928 cycles/op,        0 errors)
12673.62 tps (422.7 allocs/op,   9.0 logallocs/op,  42.8 tasks/op,  304787 insns/op,  116392 cycles/op,        0 errors)
13339.26 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303397 insns/op,  115084 cycles/op,        0 errors)
14024.20 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303439 insns/op,  112026 cycles/op,        0 errors)
13414.66 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303464 insns/op,  113267 cycles/op,        0 errors)
14263.58 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303490 insns/op,  110883 cycles/op,        0 errors)
14112.76 tps (420.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303480 insns/op,  111427 cycles/op,        0 errors)
13577.51 tps (420.8 allocs/op,   9.0 logallocs/op,  42.5 tasks/op,  303796 insns/op,  113946 cycles/op,        0 errors)
14066.75 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303451 insns/op,  112065 cycles/op,        0 errors)
12902.18 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303425 insns/op,  116586 cycles/op,        0 errors)
14248.43 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303455 insns/op,  110840 cycles/op,        0 errors)
14212.33 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303444 insns/op,  110668 cycles/op,        0 errors)
13930.59 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303454 insns/op,  111240 cycles/op,        0 errors)
14284.48 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303408 insns/op,  110665 cycles/op,        0 errors)
13272.63 tps (420.3 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303350 insns/op,  115936 cycles/op,        0 errors)
14006.44 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303488 insns/op,  111397 cycles/op,        0 errors)
14223.88 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303457 insns/op,  110602 cycles/op,        0 errors)
14187.83 tps (420.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303520 insns/op,  111151 cycles/op,        0 errors)
14013.17 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303483 insns/op,  111404 cycles/op,        0 errors)
13981.07 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303453 insns/op,  111658 cycles/op,        0 errors)
13951.17 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303469 insns/op,  111140 cycles/op,        0 errors)
14180.46 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303443 insns/op,  111006 cycles/op,        0 errors)
14335.15 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303410 insns/op,  110679 cycles/op,        0 errors)
14023.01 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303466 insns/op,  111225 cycles/op,        0 errors)
13449.48 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303447 insns/op,  113187 cycles/op,        0 errors)
13876.17 tps (420.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303402 insns/op,  111912 cycles/op,        0 errors)
13984.29 tps (420.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  303482 insns/op,  111384 cycles/op,        0 errors)
14273.99 tps (420.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  303553 insns/op,  110825 cycles/op,        0 errors)
throughput:
	mean=   13763.94 standard-deviation=611.03
	median= 14006.44 median-absolute-deviation=416.52
	maximum=14335.15 minimum=12044.99
instructions_per_op:
	mean=   303588.08 standard-deviation=526.82
	median= 303454.64 median-absolute-deviation=136.63
	maximum=305960.34 minimum=303180.36
cpu_cycles_per_op:
	mean=   112579.02 standard-deviation=2339.78
	median= 111403.63 median-absolute-deviation=1439.23
	maximum=118271.95 minimum=110601.75

Enable expressions cache / isolation: only_rmw_uses_lwt
Running test with config: {workload=write, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
13070.63 tps (393.2 allocs/op,   9.5 logallocs/op,  43.4 tasks/op,  247157 insns/op,  100773 cycles/op,        0 errors)
14253.62 tps (392.6 allocs/op,   9.1 logallocs/op,  42.8 tasks/op,  251173 insns/op,  100143 cycles/op,        0 errors)
14565.35 tps (391.2 allocs/op,   9.0 logallocs/op,  42.8 tasks/op,  250766 insns/op,   98758 cycles/op,        0 errors)
15611.72 tps (389.5 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  249996 insns/op,   95619 cycles/op,        0 errors)
16205.05 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250006 insns/op,   94166 cycles/op,        0 errors)
15929.05 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250061 insns/op,   94758 cycles/op,        0 errors)
15985.13 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250017 insns/op,   95090 cycles/op,        0 errors)
15886.65 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250106 insns/op,   94633 cycles/op,        0 errors)
16335.45 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250050 insns/op,   94094 cycles/op,        0 errors)
16091.95 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250100 insns/op,   94519 cycles/op,        0 errors)
15959.65 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250061 insns/op,   94764 cycles/op,        0 errors)
15688.73 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250029 insns/op,   95480 cycles/op,        0 errors)
14997.22 tps (389.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  250025 insns/op,   99082 cycles/op,        0 errors)
16258.34 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250000 insns/op,   94388 cycles/op,        0 errors)
16091.58 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250054 insns/op,   94630 cycles/op,        0 errors)
15726.63 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250045 insns/op,   95743 cycles/op,        0 errors)
15788.83 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250040 insns/op,   95614 cycles/op,        0 errors)
15869.28 tps (389.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  250059 insns/op,   95232 cycles/op,        0 errors)
16300.97 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250049 insns/op,   94169 cycles/op,        0 errors)
15845.29 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250143 insns/op,   95019 cycles/op,        0 errors)
16243.92 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250047 insns/op,   94212 cycles/op,        0 errors)
15789.56 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250019 insns/op,   95646 cycles/op,        0 errors)
15789.89 tps (389.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  250013 insns/op,   95232 cycles/op,        0 errors)
16038.35 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250014 insns/op,   94736 cycles/op,        0 errors)
15960.96 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250089 insns/op,   94777 cycles/op,        0 errors)
16281.30 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250059 insns/op,   94278 cycles/op,        0 errors)
15857.65 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250030 insns/op,   95267 cycles/op,        0 errors)
15616.66 tps (389.4 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250098 insns/op,   95556 cycles/op,        0 errors)
16207.39 tps (389.3 allocs/op,   9.0 logallocs/op,  42.3 tasks/op,  250022 insns/op,   94535 cycles/op,        0 errors)
15805.05 tps (389.4 allocs/op,   9.0 logallocs/op,  42.4 tasks/op,  250137 insns/op,   95488 cycles/op,        0 errors)
throughput:
	mean=   15826.94 standard-deviation=481.06
	median= 15886.65 median-absolute-deviation=210.27
	maximum=16335.45 minimum=14253.62
instructions_per_op:
	mean=   250113.98 standard-deviation=246.09
	median= 250049.35 median-absolute-deviation=69.48
	maximum=251172.98 minimum=249995.65
cpu_cycles_per_op:
	mean=   95366.46 standard-deviation=1472.55
	median= 95018.59 median-absolute-deviation=608.21
	maximum=100143.01 minimum=94093.75

Disable expressions cache / isolation: always
Running test with config: {workload=write, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
3938.48 tps (1105.7 allocs/op,  72.4 logallocs/op, 172.3 tasks/op,  690811 insns/op,  351086 cycles/op,        0 errors)
4334.71 tps (1102.1 allocs/op,  66.1 logallocs/op, 165.2 tasks/op,  684197 insns/op,  350817 cycles/op,        0 errors)
4706.15 tps (1098.8 allocs/op,  63.4 logallocs/op, 160.3 tasks/op,  679808 insns/op,  333901 cycles/op,        0 errors)
5196.93 tps (1094.0 allocs/op,  61.6 logallocs/op, 156.2 tasks/op,  674950 insns/op,  317560 cycles/op,        0 errors)
5412.56 tps (1094.3 allocs/op,  60.6 logallocs/op, 154.5 tasks/op,  675168 insns/op,  310353 cycles/op,        0 errors)
5353.89 tps (1094.9 allocs/op,  59.8 logallocs/op, 153.2 tasks/op,  675252 insns/op,  310431 cycles/op,        0 errors)
5042.74 tps (1095.2 allocs/op,  59.7 logallocs/op, 153.1 tasks/op,  675093 insns/op,  318647 cycles/op,        0 errors)
5524.41 tps (1095.0 allocs/op,  59.3 logallocs/op, 152.3 tasks/op,  676246 insns/op,  305992 cycles/op,        0 errors)
4808.04 tps (1095.4 allocs/op,  59.2 logallocs/op, 152.3 tasks/op,  675002 insns/op,  315360 cycles/op,        0 errors)
4964.11 tps (1095.3 allocs/op,  59.2 logallocs/op, 152.1 tasks/op,  675627 insns/op,  310453 cycles/op,        0 errors)
4710.89 tps (1095.6 allocs/op,  59.1 logallocs/op, 152.2 tasks/op,  674860 insns/op,  314760 cycles/op,        0 errors)
4640.56 tps (1095.7 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  675605 insns/op,  318362 cycles/op,        0 errors)
4836.89 tps (1095.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  674904 insns/op,  310553 cycles/op,        0 errors)
4853.10 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  675362 insns/op,  311678 cycles/op,        0 errors)
5044.60 tps (1095.2 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  675338 insns/op,  307083 cycles/op,        0 errors)
4725.17 tps (1095.5 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  675913 insns/op,  312833 cycles/op,        0 errors)
4690.39 tps (1095.5 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  675697 insns/op,  316882 cycles/op,        0 errors)
5102.04 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  676075 insns/op,  308612 cycles/op,        0 errors)
5145.78 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  676055 insns/op,  308922 cycles/op,        0 errors)
5367.46 tps (1095.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  675610 insns/op,  306421 cycles/op,        0 errors)
5160.06 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  677086 insns/op,  311407 cycles/op,        0 errors)
4910.48 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  675979 insns/op,  315696 cycles/op,        0 errors)
5129.04 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  674941 insns/op,  312229 cycles/op,        0 errors)
5321.47 tps (1095.4 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  675958 insns/op,  308247 cycles/op,        0 errors)
5554.23 tps (1095.1 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  675917 insns/op,  301918 cycles/op,        0 errors)
5536.50 tps (1095.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  675368 insns/op,  304634 cycles/op,        0 errors)
4978.05 tps (1095.5 allocs/op,  58.9 logallocs/op, 151.8 tasks/op,  675164 insns/op,  316771 cycles/op,        0 errors)
5584.09 tps (1095.2 allocs/op,  59.1 logallocs/op, 151.8 tasks/op,  675017 insns/op,  304673 cycles/op,        0 errors)
5549.29 tps (1095.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  675485 insns/op,  302980 cycles/op,        0 errors)
5450.76 tps (1095.6 allocs/op,  59.1 logallocs/op, 152.1 tasks/op,  675395 insns/op,  308753 cycles/op,        0 errors)
throughput:
	mean=   5090.84 standard-deviation=334.61
	median= 5102.04 median-absolute-deviation=276.62
	maximum=5584.09 minimum=4334.71
instructions_per_op:
	mean=   675967.99 standard-deviation=1840.17
	median= 675484.72 median-absolute-deviation=605.61
	maximum=684197.41 minimum=674859.54
cpu_cycles_per_op:
	mean=   312997.46 standard-deviation=9619.77
	median= 310552.75 median-absolute-deviation=4244.87
	maximum=350817.05 minimum=301918.32

Enable expressions cache / isolation: always
Running test with config: {workload=write, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
3934.52 tps (1130.5 allocs/op,  75.1 logallocs/op, 193.6 tasks/op,  675596 insns/op,  359027 cycles/op,        0 errors)
4263.50 tps (1177.7 allocs/op,  66.1 logallocs/op, 178.9 tasks/op,  705992 insns/op,  360881 cycles/op,        0 errors)
4667.79 tps (1135.0 allocs/op,  65.6 logallocs/op, 165.2 tasks/op,  679476 insns/op,  338173 cycles/op,        0 errors)
5108.99 tps (1067.5 allocs/op,  61.6 logallocs/op, 156.9 tasks/op,  625639 insns/op,  308100 cycles/op,        0 errors)
5488.55 tps (1063.6 allocs/op,  60.7 logallocs/op, 154.6 tasks/op,  621849 insns/op,  300677 cycles/op,        0 errors)
5561.18 tps (1064.0 allocs/op,  59.8 logallocs/op, 153.2 tasks/op,  622211 insns/op,  294822 cycles/op,        0 errors)
5336.39 tps (1064.3 allocs/op,  59.6 logallocs/op, 153.1 tasks/op,  621598 insns/op,  300928 cycles/op,        0 errors)
5793.43 tps (1064.0 allocs/op,  59.3 logallocs/op, 152.2 tasks/op,  621875 insns/op,  289244 cycles/op,        0 errors)
5379.91 tps (1064.4 allocs/op,  59.2 logallocs/op, 152.4 tasks/op,  621322 insns/op,  303659 cycles/op,        0 errors)
5672.53 tps (1064.4 allocs/op,  59.1 logallocs/op, 152.1 tasks/op,  621713 insns/op,  290761 cycles/op,        0 errors)
5869.58 tps (1063.9 allocs/op,  59.0 logallocs/op, 151.5 tasks/op,  622068 insns/op,  287694 cycles/op,        0 errors)
5388.28 tps (1064.4 allocs/op,  59.1 logallocs/op, 152.0 tasks/op,  622426 insns/op,  296826 cycles/op,        0 errors)
5778.49 tps (1064.3 allocs/op,  59.1 logallocs/op, 151.9 tasks/op,  621745 insns/op,  288642 cycles/op,        0 errors)
5792.13 tps (1064.0 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  621862 insns/op,  288529 cycles/op,        0 errors)
5777.23 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  622102 insns/op,  288674 cycles/op,        0 errors)
5751.56 tps (1064.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  621926 insns/op,  290211 cycles/op,        0 errors)
5631.33 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  621354 insns/op,  291496 cycles/op,        0 errors)
5749.54 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  622119 insns/op,  288086 cycles/op,        0 errors)
5747.88 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  622121 insns/op,  287400 cycles/op,        0 errors)
5776.05 tps (1064.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  622431 insns/op,  288599 cycles/op,        0 errors)
5889.24 tps (1064.1 allocs/op,  59.0 logallocs/op, 151.6 tasks/op,  622036 insns/op,  286862 cycles/op,        0 errors)
5428.36 tps (1064.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  622330 insns/op,  296656 cycles/op,        0 errors)
5815.01 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  623214 insns/op,  288557 cycles/op,        0 errors)
5888.95 tps (1064.0 allocs/op,  59.0 logallocs/op, 151.6 tasks/op,  621675 insns/op,  287005 cycles/op,        0 errors)
5792.78 tps (1064.2 allocs/op,  58.9 logallocs/op, 151.6 tasks/op,  622318 insns/op,  288901 cycles/op,        0 errors)
5775.03 tps (1064.2 allocs/op,  59.1 logallocs/op, 151.9 tasks/op,  621527 insns/op,  288365 cycles/op,        0 errors)
5388.90 tps (1064.3 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  621658 insns/op,  297654 cycles/op,        0 errors)
5804.69 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  622263 insns/op,  288024 cycles/op,        0 errors)
5735.96 tps (1064.2 allocs/op,  59.0 logallocs/op, 151.7 tasks/op,  623610 insns/op,  289894 cycles/op,        0 errors)
5833.37 tps (1064.4 allocs/op,  59.0 logallocs/op, 151.8 tasks/op,  621806 insns/op,  287844 cycles/op,        0 errors)
throughput:
	mean=   5582.30 standard-deviation=370.75
	median= 5749.54 median-absolute-deviation=196.20
	maximum=5889.24 minimum=4263.50
instructions_per_op:
	mean=   627043.66 standard-deviation=18555.20
	median= 622067.61 median-absolute-deviation=5117.23
	maximum=705992.36 minimum=621322.46
cpu_cycles_per_op:
	mean=   295971.05 standard-deviation=16137.05
	median= 289243.97 median-absolute-deviation=7372.08
	maximum=360880.52 minimum=286861.91

Disable expressions cache / isolation: only_rmw_uses_lwt
Running test with config: {workload=write_rmw, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
3265.37 tps (1280.3 allocs/op,  76.4 logallocs/op, 195.9 tasks/op,  801725 insns/op,  416500 cycles/op,        0 errors)
3745.65 tps (1290.6 allocs/op,  66.8 logallocs/op, 181.8 tasks/op,  787011 insns/op,  403770 cycles/op,        0 errors)
3892.67 tps (1369.1 allocs/op,  64.4 logallocs/op, 172.8 tasks/op,  836987 insns/op,  409262 cycles/op,        0 errors)
4140.46 tps (1412.6 allocs/op,  64.9 logallocs/op, 163.8 tasks/op,  863914 insns/op,  406089 cycles/op,        0 errors)
4503.28 tps (1330.5 allocs/op,  61.2 logallocs/op, 155.9 tasks/op,  786930 insns/op,  370361 cycles/op,        0 errors)
4604.53 tps (1339.7 allocs/op,  60.5 logallocs/op, 154.5 tasks/op,  788786 insns/op,  366661 cycles/op,        0 errors)
4096.91 tps (1349.6 allocs/op,  59.9 logallocs/op, 153.8 tasks/op,  792937 insns/op,  387918 cycles/op,        0 errors)
4802.77 tps (1352.8 allocs/op,  59.6 logallocs/op, 152.9 tasks/op,  792673 insns/op,  358566 cycles/op,        0 errors)
4688.27 tps (1357.6 allocs/op,  59.4 logallocs/op, 152.8 tasks/op,  795243 insns/op,  361182 cycles/op,        0 errors)
4693.53 tps (1359.2 allocs/op,  59.2 logallocs/op, 152.6 tasks/op,  795679 insns/op,  361376 cycles/op,        0 errors)
4700.93 tps (1359.3 allocs/op,  59.1 logallocs/op, 152.1 tasks/op,  796421 insns/op,  361189 cycles/op,        0 errors)
4455.61 tps (1361.5 allocs/op,  59.1 logallocs/op, 152.4 tasks/op,  796376 insns/op,  369795 cycles/op,        0 errors)
4784.57 tps (1361.4 allocs/op,  59.1 logallocs/op, 152.2 tasks/op,  796783 insns/op,  358598 cycles/op,        0 errors)
4750.43 tps (1362.2 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  796501 insns/op,  358747 cycles/op,        0 errors)
4768.62 tps (1362.1 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  796334 insns/op,  358290 cycles/op,        0 errors)
4727.26 tps (1362.3 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  797893 insns/op,  359089 cycles/op,        0 errors)
4456.04 tps (1362.7 allocs/op,  59.0 logallocs/op, 152.3 tasks/op,  796914 insns/op,  370259 cycles/op,        0 errors)
4864.41 tps (1362.4 allocs/op,  59.0 logallocs/op, 151.9 tasks/op,  796728 insns/op,  353853 cycles/op,        0 errors)
4502.35 tps (1362.7 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  796510 insns/op,  365175 cycles/op,        0 errors)
4832.50 tps (1362.6 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  796820 insns/op,  357270 cycles/op,        0 errors)
4703.29 tps (1362.6 allocs/op,  58.9 logallocs/op, 152.0 tasks/op,  796645 insns/op,  361062 cycles/op,        0 errors)
4308.38 tps (1362.8 allocs/op,  59.1 logallocs/op, 152.4 tasks/op,  798055 insns/op,  376032 cycles/op,        0 errors)
4488.64 tps (1362.8 allocs/op,  59.0 logallocs/op, 152.2 tasks/op,  796906 insns/op,  363340 cycles/op,        0 errors)
4774.03 tps (1362.5 allocs/op,  58.9 logallocs/op, 151.9 tasks/op,  796017 insns/op,  360444 cycles/op,        0 errors)
4758.10 tps (1362.6 allocs/op,  59.1 logallocs/op, 152.1 tasks/op,  796668 insns/op,  358578 cycles/op,        0 errors)
4757.93 tps (1362.6 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  797962 insns/op,  357759 cycles/op,        0 errors)
4557.48 tps (1362.4 allocs/op,  58.9 logallocs/op, 151.9 tasks/op,  797510 insns/op,  364731 cycles/op,        0 errors)
4723.34 tps (1362.7 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  797257 insns/op,  360364 cycles/op,        0 errors)
4891.00 tps (1362.3 allocs/op,  59.1 logallocs/op, 152.0 tasks/op,  797732 insns/op,  353860 cycles/op,        0 errors)
4634.06 tps (1362.9 allocs/op,  58.9 logallocs/op, 152.1 tasks/op,  797241 insns/op,  364016 cycles/op,        0 errors)
throughput:
	mean=   4572.66 standard-deviation=287.70
	median= 4693.53 median-absolute-deviation=177.77
	maximum=4891.00 minimum=3745.65
instructions_per_op:
	mean=   799290.80 standard-deviation=14928.13
	median= 796668.25 median-absolute-deviation=2780.55
	maximum=863914.24 minimum=786930.31
cpu_cycles_per_op:
	mean=   367504.74 standard-deviation=15124.15
	median= 361189.25 median-absolute-deviation=8415.51
	maximum=409261.76 minimum=353853.26

Enable expressions cache / isolation: only_rmw_uses_lwt
Running test with config: {workload=write_rmw, partitions=10000, concurrency=100, duration_in_seconds=30, operations-per-shard=0, flush=1}
3710.50 tps (1244.6 allocs/op,  78.2 logallocs/op, 185.0 tasks/op,  743213 insns/op,  380498 cycles/op,        0 errors)
4209.22 tps (1204.3 allocs/op,  66.3 logallocs/op, 165.7 tasks/op,  681473 insns/op,  360992 cycles/op,        0 errors)
4356.48 tps (1243.0 allocs/op,  63.7 logallocs/op, 161.4 tasks/op,  697971 insns/op,  356872 cycles/op,        0 errors)
4652.03 tps (1269.3 allocs/op,  61.8 logallocs/op, 157.3 tasks/op,  701945 insns/op,  348434 cycles/op,        0 errors)
5003.49 tps (1278.9 allocs/op,  60.9 logallocs/op, 155.2 tasks/op,  703332 insns/op,  335968 cycles/op,        0 errors)
5054.73 tps (1290.1 allocs/op,  60.1 logallocs/op, 153.8 tasks/op,  707352 insns/op,  333006 cycles/op,        0 errors)
4829.93 tps (1296.8 allocs/op,  59.5 logallocs/op, 152.9 tasks/op,  709825 insns/op,  337896 cycles/op,        0 errors)
5052.51 tps (1300.4 allocs/op,  59.5 logallocs/op, 152.9 tasks/op,  711004 insns/op,  333895 cycles/op,        0 errors)
5022.79 tps (1303.0 allocs/op,  59.2 logallocs/op, 152.4 tasks/op,  714388 insns/op,  335262 cycles/op,        0 errors)
5104.19 tps (1303.6 allocs/op,  59.2 logallocs/op, 152.3 tasks/op,  712716 insns/op,  332628 cycles/op,        0 errors)
5064.66 tps (1305.2 allocs/op,  59.1 logallocs/op, 152.3 tasks/op,  714170 insns/op,  330759 cycles/op,        0 errors)
4924.25 tps (1305.7 allocs/op,  59.1 logallocs/op, 152.2 tasks/op,  713171 insns/op,  337308 cycles/op,        0 errors)
5133.24 tps (1306.2 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  713215 insns/op,  329198 cycles/op,        0 errors)
4794.40 tps (1306.3 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  713736 insns/op,  333460 cycles/op,        0 errors)
4565.00 tps (1306.2 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  713755 insns/op,  335837 cycles/op,        0 errors)
4502.09 tps (1306.8 allocs/op,  59.0 logallocs/op, 152.3 tasks/op,  713693 insns/op,  343742 cycles/op,        0 errors)
4417.72 tps (1306.6 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  713300 insns/op,  344053 cycles/op,        0 errors)
4695.34 tps (1306.8 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  713478 insns/op,  335493 cycles/op,        0 errors)
4658.84 tps (1306.5 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  713499 insns/op,  334425 cycles/op,        0 errors)
4742.19 tps (1306.9 allocs/op,  59.0 logallocs/op, 152.3 tasks/op,  715032 insns/op,  339211 cycles/op,        0 errors)
5069.49 tps (1306.6 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  713632 insns/op,  332637 cycles/op,        0 errors)
4837.69 tps (1306.5 allocs/op,  59.0 logallocs/op, 152.0 tasks/op,  713785 insns/op,  337532 cycles/op,        0 errors)
4945.11 tps (1306.7 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  713337 insns/op,  334790 cycles/op,        0 errors)
5171.55 tps (1306.4 allocs/op,  58.9 logallocs/op, 151.8 tasks/op,  713015 insns/op,  329767 cycles/op,        0 errors)
5082.70 tps (1306.4 allocs/op,  59.1 logallocs/op, 152.0 tasks/op,  714142 insns/op,  330948 cycles/op,        0 errors)
5188.51 tps (1306.4 allocs/op,  58.9 logallocs/op, 151.7 tasks/op,  713414 insns/op,  327667 cycles/op,        0 errors)
4877.48 tps (1306.5 allocs/op,  59.1 logallocs/op, 152.1 tasks/op,  713593 insns/op,  337128 cycles/op,        0 errors)
5084.78 tps (1306.7 allocs/op,  59.0 logallocs/op, 152.1 tasks/op,  713391 insns/op,  332733 cycles/op,        0 errors)
5195.99 tps (1306.2 allocs/op,  58.9 logallocs/op, 151.6 tasks/op,  713428 insns/op,  330442 cycles/op,        0 errors)
5037.86 tps (1306.9 allocs/op,  59.1 logallocs/op, 152.4 tasks/op,  713930 insns/op,  333886 cycles/op,        0 errors)
throughput:
	mean=   4871.53 standard-deviation=268.45
	median= 4945.11 median-absolute-deviation=197.96
	maximum=5195.99 minimum=4209.22
instructions_per_op:
	mean=   710783.50 standard-deviation=6951.09
	median= 713413.89 median-absolute-deviation=2848.48
	maximum=715031.57 minimum=681472.63
cpu_cycles_per_op:
	mean=   336757.46 standard-deviation=7660.45
	median= 334790.42 median-absolute-deviation=3751.91
	maximum=360991.70 minimum=327666.51
```

**Comment by swasik** [comment]
> @m-szymon, @swasik told me this patch was waiting for my review, is this true?

Sorry for not being clear enough. I just wanted to underline that this is top priority so you should review it as soon as it is ready. Thanks @nyh for looking into it!

**Comment by m-szymon** [comment]
> #### Failed Tests (1/179044):
> 
>     * [test_timestamp_based_splitting_mutation_writer.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/19875/testReport/junit/boost.mutation_writer_test/cc/release___test_py___release___test_timestamp_based_splitting_mutation_writer_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_timestamp_based_splitting_mutation_writer.release.1)

https://github.com/scylladb/scylladb/issues/17076

@scylladbbot trigger-ci

File: test/alternator/test_condition_expression.py [hunk 84]
```diff
@@ -960,19 +960,20 @@ def test_update_condition_attribute_exists(test_table_s):
...
     test_table_s.update_item(Key={'p': p},
-            AttributeUpdates={'a': {'Value': 1, 'Action': 'PUT'}})
-    with pytest.raises(ClientError, match='ValidationException'):
-        test_table_s.update_item(Key={'p': p},
-            UpdateExpression='SET c = :val',
-                ConditionExpression='a',
-                ExpressionAttributeValues={':val': 1})
+            AttributeUpdates={'a': {'Value': True, 'Action': 'PUT'}})
+    for cond in ('a', ':val', 'NOT a', 'a AND :val', 'a OR NOT :val', 'a = :val OR NOT :val'):
+        with pytest.raises(ClientError, match='ValidationException'):
```
Comment (nyh) [inline test/alternator/test_condition_expression.py]: Nitpick: I would change the match to something like `ValidationException.*yntax error' to make sure we really got a parse error and not some other later-stage error.

File: alternator/expressions.g (hunk 83 above)
Comment (nyh) [reply alternator/expressions.g:251]: I didn't understand the last example: `size(a,a)` is a valid expression as what, `ConditionExpression`?
Why wouldn't it be - it's a function call and we said we'll allow that. Does DynamoDB print a syntax error on such a ConditionExpression, or a different error? We should have a test for this case if you thought that it's an interesting case. Even if it's not worth fixing, it's worth remembering as a test.

File: utils/lru_string_map.hh (hunk 76 above)
Comment (nyh) [reply utils/lru_string_map.hh:24]: I think if you have something good to say about how it differs from utils/lru.hh or why we can't use it, etc., a good place to write it is in the commit message of this new patch. Thanks.

File: utils/lru_string_map.hh (hunk 77 above)
Comment (nyh) [reply utils/lru_string_map.hh:77]: Ok. Maybe you can add a comment somewhere where this "pointer stability" is needed and mention this is why we used absl here? 
By "pointer stability", do you mean the fact that keys are never std::move()d, not even during rehash (we can't move them because we disabled move in our "key" object).

File: utils/lru_string_map.hh (hunk 79 above)
Comment (nyh) [reply utils/lru_string_map.hh]: Ok. 
I'm not enthusiastic in code that is designed only to be used in tests (in this case, it even looks like part of the test is embedded inside the code...), but if you do that, I think you should at least explain this situation in a comment. Otherwise potential users might start scratching their head whether the default "sanity_check::none" is what they should use, or if they should perhaps consider other "sanity checks" options.

File: utils/lru_string_map.hh (hunk 81 above)
Comment (nyh) [reply utils/lru_string_map.hh]: Looks very strange to me to avoid pointers, but ok...

File: utils/lru_string_map.hh (hunk 82 above)
Comment (nyh) [reply utils/lru_string_map.hh]: Yes, but the default is sanity_check::none. I really hope the code for sanity_check::none will get optimized somehow and doesn't actually calculate the size somehow on every iteration.

File: alternator/parsed_expression_cache.cc [hunk 85]
```diff
@@ -0,0 +1,118 @@
...
+            _stats.expression_cache.requests[StatsType].hits++;
+            try {
+                return std::get<ParseResult<Func, Args...>>(value->get());
+            } catch (const std::bad_variant_access&) {
+                // User can reach this code, by sending the same query string as a different expression type.
+                // In practice valid queries are different enough to not collide.
+                // Entries in cache are only valid queries.
+                // This request will fail at parsing below.
+                // If, by any chance this is a valid query, `push` below will update the cache with the new value.
+                logger_.error("Cache hit for '{}', but type mismatch.", query);
```
Comment (nyh) [inline alternator/parsed_expression_cache.cc]: I'm not sure this should be logged as an error. Normal syntax errors aren't logged - they just return an error to the request; So why does this need to be logged?

File: test/boost/alternator_unit_test.cc [hunk 86]
```diff
@@ -166,3 +168,172 @@ BOOST_AUTO_TEST_CASE(test_magnitude_and_precision) {
...
 }
+
+// parsed expression cache tests:
+using exp_type = alternator::stats::expression_types;
+int exp_type_i(exp_type type) {
+    if (static_cast<int>(type) >= exp_type::NUM_EXPRESSION_TYPES)
+        BOOST_FAIL("Invalid expression type");
+    return static_cast<int>(type);
+}
+auto str(exp_type type) {
```
Comment (nyh) [inline test/boost/alternator_unit_test.cc]: Please use static on all these short function names - we can have problems with them if we link all the tests together as one executable (which we do) and two tests decide to call something "str".

Comment (nyh) [reply test/boost/alternator_unit_test.cc]: Also, in general (not just here) please avoid "auto" return types unless in situations (e.g., templates) which it makes things much simpler.
Here with all those auto-returning functions you're making it harder for readers to understand what these functions return.

File: test/boost/alternator_unit_test.cc [hunk 87]
```diff
@@ -166,3 +168,172 @@ BOOST_AUTO_TEST_CASE(test_magnitude_and_precision) {
...
+}
+bool miss(alternator::stats& stats, exp_type type) {
+    misses(stats, type)++;
+    return true;
+}
+bool eviction_miss(alternator::stats& stats, exp_type type) {
+    stats.expression_cache.evictions++;
+    return miss(stats, type);
+}
+bool invalid(alternator::stats& stats, exp_type type) { return false; }
```
Comment (nyh) [inline test/boost/alternator_unit_test.cc]: Our coding conventions demand a newline after "{".

File: test/boost/alternator_unit_test.cc [hunk 88]
```diff
@@ -166,3 +168,172 @@ BOOST_AUTO_TEST_CASE(test_magnitude_and_precision) {
...
+
+    // Cache full - evicting old entrires
+    cache.try_parse("b", exp_type::PROJECTION_EXPRESSION, eviction_miss);
+    cache.try_parse("b", exp_type::PROJECTION_EXPRESSION, hit);
+    cache.try_parse("SET b=:v", exp_type::UPDATE_EXPRESSION, eviction_miss);
+    cache.try_parse("SET b=:v", exp_type::UPDATE_EXPRESSION, hit);
+    cache.try_parse("b=:v", exp_type::CONDITION_EXPRESSION, eviction_miss);
+    cache.try_parse("b=:v", exp_type::CONDITION_EXPRESSION, hit);
+
+    // Keys existing in cache, but of differnet type - raise exception
```
Comment (nyh) [inline test/boost/alternator_unit_test.cc]: This comment makes it sound like we raise an exception because it's a "different type" but it actually raises an exception because of a syntax error.
But I agree  it's a different type, and this code needs to be exercised.

File: test/boost/alternator_unit_test.cc [hunk 89]
```diff
@@ -166,3 +168,172 @@ BOOST_AUTO_TEST_CASE(test_magnitude_and_precision) {
...
+
+    cache.max_cache_entries.set(2);
+    cache.expected_stats.expression_cache.evictions += 2;
+    cache.check_stats("after resizing cache to 2 entries");
+
+    cache.max_cache_entries.set(0);
+    cache.expected_stats.expression_cache.evictions += 2;
+    cache.check_stats("after disabling cache");
+
+    co_return;
```
Comment (nyh) [inline test/boost/alternator_unit_test.cc:432]: Hmm, if we don't use futures here, maybe it doesn't need to be a SEASTAR_TEST_CASE and can be a boost test case without Seastar?

File: alternator/controller.cc (hunk 22 above)
Comment (nyh) [reply alternator/controller.cc]: I also I don't understand this technique (I see in git blame it was introduced by Kefu).  I see in executor.cc many calls to `_proxy.data_dictionary().get_config()` so it seems executor code can get its own configuration parameters, why does it need to have them passed separately from controller.cc?

It is possible that this get_timeout_in_ms isn't really needed and I was just sleeping under a rock when it got in (I see https://github.com/scylladb/scylladb/pull/12531 was never reviewed by me). I honestly don't remember. If you can just have executor use _proxy.data_dictionary().get_config() and don't need to add this extra parameter, it will be better.

File: test/alternator/test_expression_caching.py [hunk 90]
```diff
@@ -0,0 +1,398 @@
...
+#
+# As the cache is per shard, the caching events for each request rely on the shard that processes them.
+# E.g after the first request's 'miss', the repeated request would 'hit' only when it is processed by the same shard.
+# However cache functionality is tested in unit test. Here mainly we want to confirm that requests actually use cache.
+#
+# There are basic tests, checking minimum certain numbers of events, that work even if the shard handling 
+# the requests changes during the test.
+# More detailed tests (checking exact numbers) strictly require that all requests are handled by the same shard.
+# While in practice this is what happens (connection is reused), theoretically it is not guaranteed.
+# Such tests are marked xfail - they should use shard-aware port when it is implemented.
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: I don't think it is appropriate to mark tests as xfail because you don't know how to write the test - and not because Scylla has any bug. That's not the meaning of xfail, and these tests will be useless as regression tests because we just ignore if they start failing even more badly.

Also let's not wish for imaginary features we don't have like "shard-aware port", and just make it work today.

I believe that a "shard-aware port" is simply not needed - if you use **a single connection** to send multiple requests, you will send them over the same shard, always! So all we need to make sure is that we send multiple requests over the same connection. This is easy to do with manual connections (I have examples in test_manual_requests.py), but I don't think we even need to do this: I believe we can just the normal driver - it will normally try to reuse the same HTTP connection and not waste time making additional connections! I'm guessing it will **always** reuse the connection. But if you want to be safe, just try the same thing multiple times in a loop until the test succeeds. You can also **know** if the test should have succeeded by looking at the metrics of which shard answered how many requests - you can tell if all requests reached one shard, or not.

File: test/alternator/test_expression_caching.py (hunk 63 above)
Comment (nyh) [reply test/alternator/test_expression_caching.py]: So I don't understand if this line of the comment is relevant or not. If it's not, it can be deleted. If it's relevant, then I still don't understand what it is saying.

File: test/alternator/test_expression_caching.py [hunk 91]
```diff
@@ -0,0 +1,398 @@
...
+# We also need to know which shard was used (in case of LWT requests can be bounced and parsed again).
+# With shard-aware port it would be known. For now we assume shard 0.
+# Again in practice it is shard 0, theoretically it can be different and shard-aware port would solve it.
```
Comment (nyh) [inline test/alternator/test_expression_caching.py]: I don't understand why "in practice it is shard 0". Why is it not shard 1? (we have two shards). It can be random, no?

File: test/alternator/test_expression_caching.py [hunk 92]
```diff
@@ -0,0 +1,398 @@
...
+    assert all(cmp(actual_metric_values[metric], expected_metric_values[metric]) for metric in expected_metric_values), \
+        f'cache metrics: {actual_metric_values} changed not as expected: {expected_metric_values}'
+
+# Helper function that sets a new `value` in the table, by calling `UpdateItem` with UpdateExpression.
+# Success is confirmed by getting an item from table.
+# To succeed, `expression_variable` must be a valid expression 'variable' name to be used in ExpressionAttributeValues.
+# By changing `expression_variable` we get a different expression string, which is a cache key.
+def update_with_value(table, key, expression_variable, value):
+    table.update_item(Key={ 'p': key }, UpdateExpression=f'SET a = {expression_variable}', ExpressionAttributeValues={f'{expression_variable}': value})
+    assert table.get_item(Key={ 'p': key }, ConsistentRead=True)['Item']['a'] == value
```
Comment (nyh) [inline test/alternator/test_expression_caching.py:84]: Thanks. This helper function I can understand well.

File: test/alternator/test_expression_caching.py [hunk 93]
```diff
@@ -0,0 +1,398 @@
...
+
+# Helper function similar to `update_with_value`, but adding ConditionalExpression that check if new value is not equal to old one.
+# `update_should_succeed` indicates whether condition should be met (new value is set) or not (new value was equal to old one) and a exception is expected.
+def update_with_value_if_different(table, key, expression_variable, value, update_should_succeed):
+    with nullcontext() if update_should_succeed else pytest.raises(ClientError, match='ConditionalCheckFailedException'):
```
Comment (nyh) [inline test/alternator/test_expression_caching.py:89]: Nice trick!

File: test/alternator/test_expression_caching.py (hunk 90 above)
Comment (nyh) [reply test/alternator/test_expression_caching.py]: In any case, this comment trying to excuse why a certain test doesn't work - if it remains - should be moved to where it's relevant, i.e., before test_caching_update_expression(). Of course I prefer that the comment doesn't remain in this form and instead the problem is solved perhaps as I suggested here.

File: alternator/parsed_expression_cache.cc (hunk 85 above)
Comment (radoslawcybulski) [reply alternator/parsed_expression_cache.cc]: If you indent to keep the log, i'd add a code limiting it's output, as - if i understand correctly - this situation is sort-of key collision, so if it happened to a user, it will probably happen often and error log can get spammy.

File: test/alternator/test_filter_expression.py (hunk 21 above)
Comment (radoslawcybulski) [reply test/alternator/test_filter_expression.py:672]: +1 for separate patch.

File: test/boost/alternator_unit_test.cc [hunk 94]
```diff
@@ -166,3 +168,172 @@ BOOST_AUTO_TEST_CASE(test_magnitude_and_precision) {
...
+int exp_type_i(exp_type type) {
+    if (static_cast<int>(type) >= exp_type::NUM_EXPRESSION_TYPES)
+        BOOST_FAIL("Invalid expression type");
+    return static_cast<int>(type);
+}
+auto str(exp_type type) {
+    constexpr static std::string_view exp_type_s[exp_type::NUM_EXPRESSION_TYPES] = { "projection", "update", "condition" };
+    return exp_type_s[exp_type_i(type)];
+};
+auto& hits(alternator::stats& stats, exp_type type) {
```
Comment (radoslawcybulski) [inline test/boost/alternator_unit_test.cc]: Please separate getters and setters, so either `const auto &` or just `auto` as those seems integerish.

File: test/boost/alternator_unit_test.cc [hunk 95]
```diff
@@ -166,3 +168,172 @@ BOOST_AUTO_TEST_CASE(test_magnitude_and_precision) {
...
+            case exp_type::UPDATE_EXPRESSION:
+                cache.parse_update_expression(expr);
+                break;
+            case exp_type::CONDITION_EXPRESSION:
+                cache.parse_condition_expression(expr, "Test");
+                break;
+            default:
+                BOOST_FAIL("Invalid expression type");
+            }
+            if (!expected_result(expected_stats, type)) {
```
Comment (radoslawcybulski) [inline test/boost/alternator_unit_test.cc]: If i understand correctly, you pass `miss` (or `hit`) function here from line 193 (189) and run them. Then you check if those functions return false, in which case you bail with error. Both of those functions return true for all cases, what am i missing here?

File: test/boost/lru_string_map_test.cc [hunk 96]
```diff
@@ -0,0 +1,207 @@
...
+
+// Test verify that entries are removed in LRU order.
+// It tests that finding existing entries moves them at the end of the LRU list.
+// Removing from empty map is also tested.
+BOOST_AUTO_TEST_CASE(test_lru_string_map_pop) {
+    lru_map map;
+    for (bool reverse_order : {false, true}) {
+        for (bool touch_existing : {false, true}) {
+            // empty map
+            BOOST_REQUIRE(!map.pop());
```
Comment (radoslawcybulski) [inline test/boost/lru_string_map_test.cc:135]: Why don't you create `lru_map`?

File: test/boost/lru_string_map_test.cc [hunk 97]
```diff
@@ -0,0 +1,207 @@
...
+    void set(int v) {
+        *this = non_copyable_mapped_object(v);
+    }
+};
+
+// Basic compilation test for non-copyable mapped type
+BOOST_AUTO_TEST_CASE(test_lru_string_map_non_copyable_objects) {
+    lru_string_map<non_copyable_mapped_object> map;
+    map.push(std::string("test"), non_copyable_mapped_object(17));
+    BOOST_REQUIRE_EQUAL(map.find("test")->get(), non_copyable_mapped_object(17));
```
Comment (radoslawcybulski) [inline test/boost/lru_string_map_test.cc]: For clarity could you first check that `map.find` returns "true" (i've found an object) and then check it's value. Otherwise test app will crash here if it fails to find.

File: test/boost/lru_string_map_test.cc [hunk 98]
```diff
@@ -0,0 +1,207 @@
...
+    map.pop();
```
Comment (radoslawcybulski) [inline test/boost/lru_string_map_test.cc]: Why are we pop'ing here? It's end of test.

File: test/boost/lru_string_map_test.cc [hunk 99]
```diff
@@ -0,0 +1,207 @@
...
+}
+
+// Test that find returns reference to object and it can be modified
+BOOST_AUTO_TEST_CASE(test_lru_string_map_find_reference) {
+    lru_string_map<non_copyable_mapped_object> map;
+    map.push(std::string("test"), non_copyable_mapped_object(17));
```
Comment (radoslawcybulski) [inline test/boost/lru_string_map_test.cc]: Shouldn't `map.push` take first value as `std::string` and passing `"test"` raw should be fine? Otherwise others will have to do the same magic.

File: test/boost/lru_string_map_test.cc [hunk 100]
```diff
@@ -0,0 +1,207 @@
...
+    map.find("test")->get().set(42);
+    BOOST_REQUIRE_EQUAL(map.find("test")->get(), non_copyable_mapped_object(42));
+    check_size(map, 1);
+    map.pop();
```
Comment (radoslawcybulski) [inline test/boost/lru_string_map_test.cc]: We don't need `pop` here unless you also plan to check against `map` being empty.

File: utils/lru_string_map.hh [hunk 101]
```diff
@@ -0,0 +1,156 @@
...
+// Value must be moveable and is not copied internally.
+// The cache keeps track of the order of usage of the entries, and allows
+// to evict the least recently used entries.
+template<typename Value>
+class lru_string_map {
+    struct key {
+        mutable boost::intrusive::list_member_hook<> list_hook;
+        std::string str;
+        explicit key(std::string_view s) : str(s) {}
+        explicit key(std::string&& s) : str(std::move(s)) {}
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: Why not `explicit key(std::string s) : str(std::move(s)) {}` instead of those two constructors?

File: utils/lru_string_map.hh [hunk 102]
```diff
@@ -0,0 +1,156 @@
...
+        // We link keys in intrusive::list, so make sure main container provides stable address for keys (e.g in rehashing).
+        key() = delete;
+        key(const key& k) = delete;
+        key(const key&& k) = delete;
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh:45]: For clarity please delete assignment operators as well.

File: utils/lru_string_map.hh (hunk 77 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh:77]: `References and pointers to either key or data stored in the container are only invalidated by erasing that element, even when the corresponding iterator is invalidated.`

https://en.cppreference.com/w/cpp/container/unordered_map.html

File: utils/lru_string_map.hh (hunk 79 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh]: Good job, but an overkill in my opinion. A field with access pattern `if ([[unlikely]] check == sanity_check::basic)` or `if ([[unlikely]] check == sanity_check::detailed)` would do the same.

In fact adding just additional `sanity_check_basic` / `sanity_check_detailed` function and calling it from tests would be even better.

File: utils/lru_string_map.hh [hunk 103]
```diff
@@ -0,0 +1,156 @@
...
+        return _map.size();
+    }
+    void reserve(size_t n) { return _map.reserve(n); }
+
+    // Clears all entries from cache
+    // If `release` is true, the memory used by the cache is released.
+    // Returns the number of entries removed.
+    // WARNING: May stall the reactor when the size is too big.
+    // Consider limiting the size before calling this function.
+    size_t clear(bool release=false) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh:115]: I think it would be better to add reactor friendly implementation, as you as the owner are in better position to correctly write such function and guess correct step size of the loop.

File: utils/lru_string_map.hh [hunk 104]
```diff
@@ -0,0 +1,156 @@
...
+        }
+        key& key_ref = _lru_key_list.front();
+        _lru_key_list.pop_front();
+        _map.erase(key_ref);
+        return true;
+    }
+
+    // Insert or update the value for the given key.
+    // The key is copied into the cache.
+    void push(std::string_view key, Value&& value) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: Why not taking `std::string key` and `std::move` into the `insert_of_assign`? Does the same (minus additional `std::move` call), requires only one implementation function.

File: utils/lru_string_map.hh [hunk 105]
```diff
@@ -0,0 +1,156 @@
...
+
+    using string_map = absl::node_hash_map<key, Value, key_hash, key_equal>;
+    string_map _map;
+    using lru_key_list_hook = boost::intrusive::member_hook<key, boost::intrusive::list_member_hook<>,&key::list_hook>;
+    using lru_key_list = boost::intrusive::list<key, lru_key_list_hook>;
+    lru_key_list _lru_key_list;
+
+    // Move the accessed key to the back of the LRU list
+    template<bool IsNew=false> 
+    void touch(string_map::iterator it) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: I'd rather have a single function and take bool as parameter. If you worry about performance, force inlining.

Note, that by using `template` here you avoid one `if`, but you add one at the call site (for example line 141).

File: utils/lru_string_map.hh [hunk 106]
```diff
@@ -0,0 +1,156 @@
...
+    void push(std::string&& key, Value&& value) {
+        auto ret = _map.insert_or_assign(std::move(key), std::move(value));
+        (ret.second ? touch<true>(ret.first) : touch<false>(ret.first));
+    }
+
+    // Evict items until the size is at most max_size.
+    // Returns the number of evicted items.
+    // Optionally it can use sanity checks (see size() for details).
+    template<sanity_check check=sanity_check::none>
+    size_t evict_until_size(size_t max_size) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: As in previous comment - seems overkillish.

File: utils/lru_string_map.hh [hunk 107]
```diff
@@ -0,0 +1,156 @@
...
+        size_t ss, is;
+        ss = is = size<check>();
+        while (ss > max_size && pop()) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: Possibly doing raw loop and checking if size matches seems more explicit.

```
for(auto ss = ...; ss > max_size && pop(); --ss) {
  if (ss != size<check>()) FAIL_HERE;
}
```

**Review by radoslawcybulski — COMMENTED** [review]
Amazing patch, my 2cc.

File: test/alternator/test_condition_expression.py (hunk 84 above)
Comment (m-szymon) [reply test/alternator/test_condition_expression.py]: done

File: alternator/expressions.g (hunk 83 above)
Comment (m-szymon) [reply alternator/expressions.g:251]: There is already test for that. `size()` takes one argument. DynamoDB checks it early - we don't have "syntax errors", we have "ValidationError" with message - in `ConditionExpresion` these `size(a,a)` , `:val > size(a,a)` have the same error. `size(a)` has different.
My point is, that this is example of an expression that we parse as valid, but it is not valid - it will always result with ValidationError, but in our implementation only after resolving.

File: test/boost/lru_string_map_test.cc (hunk 96 above)
Comment (m-szymon) [reply test/boost/lru_string_map_test.cc:135]: You mean create new one for every loop?
Because I think several loop on the same object is a slightly better test.

File: utils/lru_string_map.hh (hunk 104 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: Starting from the beginning: I have a `string_view` from JSON. With your version it is immediately copied at the function call. But if the key already exists (`insert_of_assign` does assign) it doesn't need to be copied nor moved.

File: test/boost/lru_string_map_test.cc (hunk 97 above)
Comment (m-szymon) [reply test/boost/lru_string_map_test.cc]: fixed

File: test/boost/lru_string_map_test.cc (hunk 98 above)
Comment (m-szymon) [reply test/boost/lru_string_map_test.cc]: right

File: test/boost/lru_string_map_test.cc (hunk 100 above)
Comment (m-szymon) [reply test/boost/lru_string_map_test.cc]: fixed

File: test/boost/lru_string_map_test.cc (hunk 99 above)
Comment (m-szymon) [reply test/boost/lru_string_map_test.cc]: As I wrote below, in practice cache gets `string_view`s as an input. Coping it to string every time is pointless and functions with `string_view` allow us to avoid it if we can.
After your earlier suggestions - what if a user already has a movable string - I added `std::string&&` function, although it is not used.
With your current suggestion, whenever we have non-movable `std::string` you would have to explicitly convert it to `std::string_view` to avoid coping. Now it is done implicitly. And for `const char*` it would still be ambiguous - exactly like now.

File: utils/lru_string_map.hh (hunk 82 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: for `sanity_check::none` it is just `_map.size()`

File: utils/lru_string_map.hh (hunk 105 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: It is a bool parameter, but the one you solve statically.
But it seems such a use of templates is highly controversial - I am changing it.

File: utils/lru_string_map.hh (hunk 79 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: > potential users

That's why initially I wrote it as a helper class only for expressions cache. Now I am creating general purpose cache...
The question is - do I need these sanity checks. If yes, then every time I get the size it makes sense to do the sanity check.
As it seem controversial, I am changing it.

File: utils/lru_string_map.hh (hunk 101 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: It would make sense here, but with forwarding in other functions it wouldn't compile.

File: utils/lru_string_map.hh (hunk 102 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:45]: ok

File: test/boost/alternator_unit_test.cc (hunk 95 above)
Comment (m-szymon) [reply test/boost/alternator_unit_test.cc]: `invalid`. And `eviction_miss`, but it also returns true.

File: test/boost/alternator_unit_test.cc (hunk 88 above)
Comment (m-szymon) [reply test/boost/alternator_unit_test.cc]: right

File: test/boost/alternator_unit_test.cc (hunk 94 above)
Comment (m-szymon) [reply test/boost/alternator_unit_test.cc]: But whats the point? This is alias for long, unfriendly names.

File: test/boost/alternator_unit_test.cc (hunk 89 above)
Comment (m-szymon) [reply test/boost/alternator_unit_test.cc:432]: With boost test case it crashed. I think it is related to `stats` structure.

**Comment by nyh** [comment]
There are merge conflicts, please rebase.

File: utils/lru_string_map.hh (hunk 77 above)
Comment (nyh) [reply utils/lru_string_map.hh:77]: I don't know if @m-szymon is right, you (@radoslawcybulski) is right, or neither of you are right. The point of whether pointers to elements survives rehashing is a very subtle one (here's another discussion https://stackoverflow.com/questions/39868640/stdunordered-map-pointers-reference-invalidation) and I ask that it be mentioned in a comment.

I think that the fact that @m-szymon deleted both copy and move constructors guarantees that rehashing can't possibly need to copy these elements, so if the version with absail compiled, then it indeed can't be moving the elements on rehash. But I don't know if it would have failed with std::unordered_map - did you try and see it fail to compile?

File: utils/lru_string_map.hh (hunk 79 above)
Comment (nyh) [reply utils/lru_string_map.hh]: I think I agree about the last suggestion. It really does look like you inserted the sanity_check() function into size() for no reason and it could have been a separate function.
That is, unless you think that real users - not tests - will want to use the non-empty sanity check option?

File: utils/lru_string_map.hh (hunk 103 above)
Comment (nyh) [reply utils/lru_string_map.hh:115]: @m-szymon I vaguely recall that in the latest status call you suggested that maybe it's easier to get a stall here than you thought, and you want to fix it.
I think it's fairly straightforward the API to fix - by making a clear_gently() function that returns a future - but what is less clear to me is:
1. How can you implement the _lru_key_list.clear() and _map=string_map() without stalls. Perhaps you can take ideas from other clear_gently() implementations we have.
2. I'm worried that the places you want to use this clear() might not be futurized.

File: alternator/parsed_expression_cache.cc (hunk 85 above)
Comment (nyh) [reply alternator/parsed_expression_cache.cc]: ַPlease respond to this thread.

I honestly don't think this situation is more interesting than a regular syntax error. You already believe that it can only happen in case of a syntax error - because correct expressions never collide. So in a special silly kind of syntax error (when someone passes a projectionexpression as a conditionexpression or something), you write this ERROR to the long. Why is this useful?

If it's something you wanted for debugging, it can be DEBUG level or something, not ERROR.

**Comment by nyh** [comment]
> There are merge conflicts, please rebase.

Also there are multiple review comments that you didn't address. You don't need to agree with every comment or suggestion, but please at least respond to them. Thanks.

**Comment by m-szymon** [comment]
> 2\. I'm worried that the places you want to use this clear() might not be futurized.

Yes, that seems to be a problem that I run into. For these rare situation I am starting a thread with `seastar::async`, which in general seemed to work, but then I have a problem in destructors, I am still tring to solve. That's why I still didn't push other changes and finished replying to comments...

File: alternator/parsed_expression_cache.cc (hunk 85 above)
Comment (m-szymon) [reply alternator/parsed_expression_cache.cc]: Right - I agree.

File: utils/lru_string_map.hh (hunk 77 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:77]: @radoslawcybulski is right. When I started, I was using iterators and they were my problem. Pointer stability was an issue between `node_map` and `flat_map`.
std::unordered_map almost compiles. It doesn't implement transparent lookup for `insert_or_assign` yet (it should in c++26). Still absl should be slighly more efficient with erase.

File: alternator/parsed_expression_cache.cc [hunk 108]
```diff
@@ -0,0 +1,108 @@
...
+
+#include "expressions.hh"
+#include "utils/log.hh"
+
+#include "utils/lru_string_map.hh"
+#include <variant>
+
+static logging::logger logger_("parsed-expression-cache");
+
+namespace alternator {
```
Comment (radoslawcybulski) [inline alternator/parsed_expression_cache.cc]: Maybe `namespace alternator::parsed` ?

File: alternator/parsed_expression_cache.cc [hunk 109]
```diff
@@ -0,0 +1,108 @@
...
+            _stats.expression_cache.requests[StatsType].hits++;
+            try {
+                return std::get<ParseResult<Func, Args...>>(value->get());
+            } catch (const std::bad_variant_access&) {
+                // User can reach this code, by sending the same query string as a different expression type.
+                // In practice valid queries are different enough to not collide.
+                // Entries in cache are only valid queries.
+                // This request will fail at parsing below.
+                // If, by any chance this is a valid query, `insert_or_assign` below will update the cache with the new value.
+                logger_.debug("Cache hit for '{}', but type mismatch.", query);
```
Comment (radoslawcybulski) [inline alternator/parsed_expression_cache.cc]: This log will be printed on every type mismatch, so if user alternates between the same query for different types and has logging set to debug, the user will ddos it's own db.

Do we need this debug message at all? Maybe expressions's type should be part of a key in the cache?

File: test/alternator/test_expression_caching.py [hunk 110]
```diff
@@ -0,0 +1,461 @@
...
+class UnexpectedOperationCount(Exception):
+        pass
+
+# Helper function that sets a new `value` in the table, by calling `UpdateItem` with UpdateExpression.
+# Success is confirmed by getting an item from table.
+# To succeed, `expression_variable` must be a valid expression 'variable' name to be used in ExpressionAttributeValues.
+# By changing `expression_variable` we get a different expression string, which is a cache key.
+def update_with_value(table, key, expression_variable, value):
+    table.update_item(Key={ 'p': key }, UpdateExpression=f'SET a = {expression_variable}', ExpressionAttributeValues={f'{expression_variable}': value})
+    assert table.get_item(Key={ 'p': key }, ConsistentRead=True)['Item']['a'] == value
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py:84]: Out of curiosity - can't eventual consistency bite us here in some extremely rare cases?

File: test/alternator/test_expression_caching.py (hunk 93 above)
Comment (radoslawcybulski) [reply test/alternator/test_expression_caching.py:89]: +1

File: test/alternator/test_expression_caching.py [hunk 111]
```diff
@@ -0,0 +1,461 @@
...
+#
+# More detailed tests (checking exact numbers) strictly require that all requests are handled by the same shard.
+# While in practice this is what happens (connection is reused), theoretically it is not guaranteed.
+# To confirm that result is relyable, we check the number of operations reported by selected shard.
+# If it did not get all requests, we repeat the tests.
+
+# Context manager to temporarily change cache settings for the duration of the yield
+# Note: It flushes the cache, by first setting it to 0, then to the desired size.
+@contextmanager
+def cache_settings(cql, cache_size):
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py]: Maybe `max_cache_entries_per_shard_setting`? Or something less ambiguous, than `cache_settings` please.

File: test/alternator/test_expression_caching.py [hunk 112]
```diff
@@ -0,0 +1,461 @@
...
+    p = random_string()
+    update_with_value(table=test_table_s, key=p, expression_variable=':val', value="test")
+    with cache_settings(cql, 2):
+        connection_tables1 = [None] * scylla_shard_count(metrics)
+        connection_tables2 = [None] * scylla_shard_count(metrics)
+        to_drop = []
+        connection_tables1[get_connection_shard(metrics, test_table_s)] = test_table_s
+        setup_retries = 100*len(connection_tables1)
+        while (None in connection_tables1 or None in connection_tables2):
+            setup_retries = setup_retries - 1
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py]: `setup_retries -= 1`

File: test/alternator/test_expression_caching.py [hunk 113]
```diff
@@ -0,0 +1,461 @@
...
+            s = get_connection_shard(metrics, t)
+            print(s)
+            if connection_tables1[s] is None:
+                connection_tables1[s] = t
+            elif connection_tables2[s] is None:
+                connection_tables2[s] = t
+            else:
+                to_drop.append(t)
+
+        def get_item(table, expression_variable):
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py]: `assert_item_exists` or something similar, please, the function does more than just getting an item.

File: test/alternator/test_expression_caching.py [hunk 114]
```diff
@@ -0,0 +1,461 @@
...
+
+# Test that all shards use cache independently.
+# It strictly requires control over which shards processes each request.
+@retrying_on_unexpected_operation_count()
+def test_caching_on_shards(cql, metrics, test_table_s, new_dynamodb_session):
+    p = random_string()
+    update_with_value(table=test_table_s, key=p, expression_variable=':val', value="test")
+    with cache_settings(cql, 2):
+        connection_tables1 = [None] * scylla_shard_count(metrics)
+        connection_tables2 = [None] * scylla_shard_count(metrics)
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py:431]: What's the point of `connection_tables2`?

File: test/alternator/test_expression_caching.py [hunk 115]
```diff
@@ -0,0 +1,461 @@
...
+        to_drop = []
```
Comment (radoslawcybulski) [inline test/alternator/test_expression_caching.py:435]: Why do we need to keep `t` alive in `to_drop`?

File: test/boost/alternator_unit_test.cc [hunk 116]
```diff
@@ -207,4 +210,223 @@ BOOST_AUTO_TEST_CASE(exception_at_expression_parsing) {
...
+static int exp_type_i(exp_type type) {
+    if (static_cast<int>(type) >= exp_type::NUM_EXPRESSION_TYPES)
+        BOOST_FAIL("Invalid expression type");
+    return static_cast<int>(type);
+}
+static std::string_view str(exp_type type) {
+    constexpr static std::string_view exp_type_s[exp_type::NUM_EXPRESSION_TYPES] = { "projection", "update", "condition" };
+    return exp_type_s[exp_type_i(type)];
+};
+static uint64_t& hits(alternator::stats& stats, exp_type type) {
```
Comment (radoslawcybulski) [inline test/boost/alternator_unit_test.cc]: Renaming this to (for example) `hits_counter` (and `misses_counter`) would improve distinction between this and (below) `hit` function.

File: test/boost/alternator_unit_test.cc [hunk 117]
```diff
@@ -207,4 +210,223 @@ BOOST_AUTO_TEST_CASE(exception_at_expression_parsing) {
...
+    return stats.expression_cache.requests[exp_type_i(type)].hits;
+}
+static uint64_t& misses(alternator::stats& stats, exp_type type) {
+    return stats.expression_cache.requests[exp_type_i(type)].misses;
+}
+static bool hit(alternator::stats& stats, exp_type type) {
```
Comment (radoslawcybulski) [inline test/boost/alternator_unit_test.cc]: Another improvement would be to use `enum class` here and do something like this:
`enum class excepting_exception { no, yes }`, which will tell what return value from `miss` and friends do (and would also group them all together).

File: test/boost/alternator_unit_test.cc (hunk 95 above)
Comment (radoslawcybulski) [reply test/boost/alternator_unit_test.cc]: Ok, this is not result that is expected (as a value), but it's more update counters and check if exception should be raised. Could you, please, rename to reflect meaning?

File: test/boost/lru_string_map_test.cc [hunk 118]
```diff
@@ -0,0 +1,204 @@
...
+        return *this;
+    };
+
+    bool operator==(const mapped_object& other) const {
+        return _v == other._v;
+    }
+    friend std::ostream& operator<< (std::ostream& os, const mapped_object& obj);
+};
+std::ostream& operator<< (std::ostream& os, const mapped_object& obj) {
+    return os << "mapped_object(" << obj._v << ")";
```
Comment (radoslawcybulski) [inline test/boost/lru_string_map_test.cc]: You can define function in line 38. :)

File: utils/lru_string_map.hh [hunk 119]
```diff
@@ -0,0 +1,337 @@
...
+#include "utils/assert.hh"
+#include "utils/log.hh"
+
+// A simple LRU cache, mapping strings to values of type Value.
+// The cache keeps track of the order of usage of the entries, and allows
+// to evict the least recently used entries.
+// This implementation is optimized for string keys - it avoids unnecessary
+// string allocations on lookups by using transparent lookup in the underlying map.
+// The preexisting lru.hh implementation is not helpful for this use case,
+// - it has only LRU ordering with two lists, we integrate with a map and even re-using
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: typo

File: utils/lru_string_map.hh (hunk 103 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh:115]: They should i think. `executor` has `stop` method, where you can clear stuff up, other use cases probably as well?

File: utils/lru_string_map.hh [hunk 120]
```diff
@@ -0,0 +1,337 @@
...
+        } else {
+            touch_lru(ret.first);
+        }
+    }
+};
+
+// A sized LRU cache, with a maximum number of entries.
+// This class provides functions to manage cache size, especially evictions
+// and resizing.
+template<typename Value, bool EnableBackgroundResize = true, size_t MaxLoop=3000>
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: Please, take `EnableBackgroundResize` and `MaxLoop` by value not as template arguments.

File: utils/lru_string_map.hh [hunk 121]
```diff
@@ -0,0 +1,337 @@
...
+            }
+            while (!_map.empty()) {
+                _map.erase(_map.begin());
+                if (++ret % max_loop == 0) {
+                    co_await seastar::coroutine::maybe_yield();
+                }
+            }
+        }
+        clear(release);
+        co_return ret;
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: This will return `0` when `max_loop == 0` every time, probably not as intended.

File: utils/lru_string_map.hh [hunk 122]
```diff
@@ -0,0 +1,337 @@
...
+        }
+    }
+};
+
+// A sized LRU cache, with a maximum number of entries.
+// This class provides functions to manage cache size, especially evictions
+// and resizing.
+template<typename Value, bool EnableBackgroundResize = true, size_t MaxLoop=3000>
+class sized_lru_string_map : public lru_string_map<Value> {
+    logging::logger& _logger;
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh:188]: I think moving `_logger` to `lru_string_map.cc` and adding extern here in some additional (`detail`?) namespace would be better from user perspective.

File: utils/lru_string_map.hh [hunk 123]
```diff
@@ -0,0 +1,337 @@
...
+    }
+
+private:
+    size_t _resize_target = 0;
+    bool _resize_flush = false;
+
+    template<bool IsEmergency=false, bool IsResizing=false>
+    inline bool request_flush() {
+        if constexpr(IsEmergency) {
+            on_internal_error(_logger, ("Detected cache inconsistency, purging cache."));
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: I don't get it why requesting flush with `IsEmergency` causes this error? Something is missing here.
Shouldn't `sanity_check` do the error reporting?

File: utils/lru_string_map.hh [hunk 124]
```diff
@@ -0,0 +1,337 @@
...
+        _background_resizing.ignore_ready_future();
+        _background_resizing = resize_in_background();
+    }
+
+private:
+    size_t _resize_target = 0;
+    bool _resize_flush = false;
+
+    template<bool IsEmergency=false, bool IsResizing=false>
+    inline bool request_flush() {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: It's unclear for me, what both template arguments do and what return value represents, please rename or add some commentary.
You don't seem to be using `IsResizing`.
Also please take parameters by "normal" values.

File: utils/lru_string_map.hh [hunk 125]
```diff
@@ -0,0 +1,337 @@
...
+
+    seastar::future<size_t> clear_gently(bool release=false, size_t max_loop=0) {
+        size_t ret = 0;
+        if (max_loop > 0 && max_loop < _map.size()) {
+            while (pop()) {
+                if (++ret % max_loop == 0) {
+                    co_await seastar::coroutine::maybe_yield();
+                }
+            }
+            while (!_map.empty()) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: If i understand code correctly, we have an invariant, where size of `_map` is equal to size of `_lru_key_list`? I think here `_map` should always be empty and this second `while` should be an assert?

File: utils/lru_string_map.hh [hunk 126]
```diff
@@ -0,0 +1,337 @@
...
+        while (_resize_flush || _max_cache_entries != _resize_target) {
+            if (_resize_flush) {
+                _evictions += co_await this->clear_gently(true, MaxLoop);
+                _resize_flush = false;
+                _logger.trace("flushed.");
+            }
+
+            size_t chunk = MaxLoop;
+            while (this->size() > _resize_target) {
+                if (!this->pop() || !lru_string_map<Value>::sanity_check()) [[unlikely]] {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: `pop` would be better suited for `sanity_check` call i think (as it does the real modify) - that would remove need for `IsEmergency` parameter in `request_flush` (`request_flush` shouldn't be tasked with reporting an out of the blue error). Even better might be to move `sanity_check` call to after whole `while` loop (or just do it after each `MaxSize` batch is done) - that way you could integrate it into `clear_gently` function (since it would be so rare it could be non-optional) and with suggested changes around `_resize_target` the whole `while` here could replaced with calling `clear_gently` completely.

File: utils/lru_string_map.hh [hunk 127]
```diff
@@ -0,0 +1,337 @@
...
+        if (!_background_resizing.available()) {
+            // Background thread is already running
+            return;
+        }
+        _background_resizing.ignore_ready_future();
+        _background_resizing = resize_in_background();
+    }
+
+private:
+    size_t _resize_target = 0;
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh:239]: We have two sizes doing similar things and i feel it's not needed. Please correct me if i'm wrong. My idea - drop `_resize_target`. `_max_cache_entries` functions as max size we want to reach. `resize_in_background` will loop until condition `size() > _max_cache_entries` is true. `make_space_for_one` will `pop` one (or start background resizing) if `size() >= _max_cache_entries` is true. After this change you won't modify `_max_cache_entries` down every step, just on start of the resize request, so you will be able to unify `resize_in_background` internal while with `clear_gently` (as those whiles will be the same).

File: utils/lru_string_map.hh [hunk 128]
```diff
@@ -0,0 +1,337 @@
...
+            on_internal_error(_logger, ("Detected cache inconsistency, purging cache."));
+        }
+        _max_cache_entries = 0; // immediately block new entries
+        _resize_flush = true;
+        return resize_maybe_in_background(IsEmergency);
+    }
+
+    seastar::future<> resize_in_background() {
+        while (_resize_flush || _max_cache_entries != _resize_target) {
+            if (_resize_flush) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: This additional `if` is confusing - for example `clear_gently` will skip `sanity_check`, which is inconsistent with non resize flush behaviour. Can we move the `if` to after whole `while` - it's assumed `_max_cache_entries` is set to 0 with `_resize_flush`, so after `while` we could check if `_max_cache_entries` is still 0 and then if `_resize_flush` is true do the flushing.

File: utils/lru_string_map.hh [hunk 129]
```diff
@@ -0,0 +1,337 @@
...
+                }
+                _evictions++;
+                // Yield control to allow other tasks to run
+                if (--chunk == 0) {
+                    _max_cache_entries = this->size();
+                    co_await seastar::coroutine::maybe_yield();
+                    chunk = MaxLoop;
+                }
+            }
+            if (!_resize_flush) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: This `if` is confusing to me. `_resize_flush` in normal behaviour will be set to `false` in line 249, so this `if` will be always true (thus `reserve` will never execute). Only way it can execute is via abortish 256 line (or second outside call to `request_flush`).

File: utils/lru_string_map.hh [hunk 130]
```diff
@@ -0,0 +1,337 @@
...
+                continue;
+            }
+            // Reserve space for the new size
+            this->reserve(_resize_target);
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: `reserve` in a `while` loop that is supposed to do shrinking? Feels fishy - shouldn't it be after the loop?

File: utils/lru_string_map.hh [hunk 131]
```diff
@@ -0,0 +1,337 @@
...
+            _max_cache_entries = _resize_target;
+        }
+        _logger.trace("max entries changed to {}", _max_cache_entries);
+    }
+
+    // Evict excess entries in chunks, yielding between chunks to avoid stalling the reactor
+    bool resize_maybe_in_background(bool prefer_background=false) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: Why do we need this function? Do we need to guarantee that resize process (or rather shrinking) has done at least some work after we call `resize_maybe_in_background`? Can't we unconditionally start `resize_in_background` and let it fly, I don't think it's a big deal if cache is bigger that requested size for finite amount of time.

If you want to keep the option of disabling background resize, you can just `co_await` the call to `resize_in_background` i think.

File: utils/lru_string_map.hh [hunk 132]
```diff
@@ -0,0 +1,337 @@
...
+            // Background thread is already running
+            return;
+        }
+        _background_resizing.ignore_ready_future();
+        _background_resizing = resize_in_background();
+    }
+
+private:
+    size_t _resize_target = 0;
+    bool _resize_flush = false;
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh:240]: It might be worth to use `_resize_flush` as sort-of release unnecesary resources thing (in other words you might wish to release spare memory when resizing to non-zero maximum size). But this might be an overkill.

File: test/alternator/test_expression_caching.py (hunk 110 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py:84]: These are single-node tests.
Both write and read are LOCAL_QUORUM.
So I don't see such risk.

File: test/alternator/test_expression_caching.py (hunk 114 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py:431]: To check that another connection to the same shard uses the same cache.
I will add a comment to the test.

File: test/alternator/test_expression_caching.py (hunk 115 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py:435]: I am not sure if we have any guarantees about shard assignment. In practice I think it selects the lowest shard id (or maybe cpu) with lowest connections alive. So if we have one connection it is always on shard 0 and in this test it will probably fill the lists sequentially.
But in case, for any reason, we get a shard we already have - if we drop it, there is high chance it would be assigned again in new connection.

File: test/alternator/test_expression_caching.py (hunk 113 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: `try_projection_expression`? That's the purpose of this call, assert or get_item are just technicalities.

File: test/alternator/test_expression_caching.py (hunk 111 above)
Comment (m-szymon) [reply test/alternator/test_expression_caching.py]: If it has to be that long and specific, at least important part should be at the beginning: `config_max_cache_entries_per_shard`.
Probably I wouldn't like this as a reader, but I am not the reader.

File: test/boost/alternator_unit_test.cc (hunk 95 above)
Comment (m-szymon) [reply test/boost/alternator_unit_test.cc]: In the context of testing the cache, it is the expected cache behavior as a result of given operation, but I see the issue here.

File: utils/lru_string_map.hh (hunk 121 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: wow, nice catch

File: utils/lru_string_map.hh (hunk 122 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:188]: Which user?
If there is going to be any other user, then he definitely doesn't want to have logs mixed from different contexts. In my opinion it should bind to the user's logger.
If we expect only one user - then this class shouldn't be in utils, but directly in `parsed_expression_cache`.

File: utils/lru_string_map.hh (hunk 132 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:240]: I think it is an overkill. We release the oversized container by flushing.

File: utils/lru_string_map.hh (hunk 127 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:239]: Probably `_max_cache_entries`, `_resize_target`, `_resize_flush` could be encoded on one less variable, but that's the case when I oppose going cheap. 
If we invoke background resize, the cache is still usable and it can be used "in parallel". Unless we flush - then we temporarily disable cache, but it is not a hard requirement in case of user triggered flush - it just makes more sense.
`_max_cache_entries` is exposed to user. If user is doing everything correctly it never should be higher then actual size. We can easily set it to 0 to indicate to user that cache is disabled.
`_resize_target` is our internal thing - user requested it and it may not be available yet. User may request another value, before previous resizing ended. But we want to finish flush if it was requested.

File: utils/lru_string_map.hh (hunk 131 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: For the small changes I want it to be synchronous, mainly for testing.

Definitely I couldn't `co_await`, because it is not in the coroutine. But if I start background resize for small change and somehow wait for it to finish, there could be another request with much bigger change and the first one would still wait for it to finish.
I am really not sure if in case of config updates it would be possible, but I assume the worst.

File: utils/lru_string_map.hh (hunk 123 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: flush can have two reasons - user triggered (no message) or some sanity check failed.
I will change it.

File: utils/lru_string_map.hh (hunk 128 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: > `clear_gently` will skip `sanity_check`, which is inconsistent

clear is supposed to work even if sanity check fails - that's our way to restore correct state.

We want to do the flush first. With non-flush resize we want to allow user use cache in the yields.

File: utils/lru_string_map.hh (hunk 129 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: wow, I can tell what to say! It should be `if (_resize_flush)`, and actually test isn't working correctly when I run it. I don't know how and when it slipped in.

File: utils/lru_string_map.hh (hunk 130 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: It doesn't shrink, it grows.
The external loop is for checking if there were no change in requested settings (which would make more sense with yield in the end of the loop).
I will review it, as it is reminder from when I implemented using thread - which is much heavier to start and I wanted to reuse already existing one.

File: utils/lru_string_map.hh (hunk 125 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: Clearing is our way to recover from failed sanity checks.

File: utils/lru_string_map.hh (hunk 126 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: But we use pop when recover from failed sanity check. 
It is all moving things around and in the end something somewhere gets ugly.
The distinction is clear: pop and clear* are in a base class and are raw operations - they don't do sanity checks, because they don't know how to handle them.

File: utils/lru_string_map.hh [hunk 133]
```diff
@@ -0,0 +1,153 @@
...
+#include <optional>
+#include <string>
+#include <string_view>
+
+// A simple LRU cache, mapping strings to values of type Value.
+// The cache keeps track of the order of usage of the entries, and allows
+// to evict the least recently used entries.
+// This implementation is optimized for string keys - it avoids unnecessary
+// string allocations on lookups by using transparent lookup in the underlying map.
+// The preexisting lru.hh implementation is not helpful for this use case,
```
Comment (nyh) [inline utils/lru_string_map.hh]: A lesson to other developers (not you): don't rush to put things in utils/. If you write a class that is only really useful for one particular use case (utils/lru.hh is full of references to "index cache"), don't put it in utils/. Put it in your own module's directory, and someone will later move it to utils/ if it's found to be useful for other use cases. Or not.

File: utils/lru_string_map.hh (hunk 103 above)
Comment (nyh) [reply utils/lru_string_map.hh:115]: @radoslawcybulski I don't think we're very worried about stalls while stopping Scylla. Are there other places we need this clear() function? (I'm talking currently - not about some hypothetical future uses of this class).

File: utils/lru_string_map.hh [hunk 134]
```diff
@@ -115,6 +121,25 @@ public:
         return ret;
     }
 
+    seastar::future<size_t> clear_gently(bool release=false, size_t max_loop=0) {
```
Comment (nyh) [inline utils/lru_string_map.hh]: I think you need a comment on this function. Seeing it for the first time, I can't even guess what "max_loop" refers to, and what is the special significance of the default value 0.

After reading the code below I'm even more confused - it seems that by default max_loop=0 which causes the "gentle" loop to not be done, so this function isn't gentle at all by default... Why isn't max_loop 1 or 10 or 64 or something by default, not 0, to make it gentle?

File: utils/lru_string_map.hh (hunk 125 above)
Comment (nyh) [reply utils/lru_string_map.hh]: on_internal_error(), but I tend to agree, I don't know why we have this second loop.

File: utils/lru_string_map.hh [hunk 135]
```diff
@@ -151,3 +176,162 @@ public:
...
+public:
+    // Stop the background resizing task, if running.
+    seastar::future<> stop() {
+        set_max_size(0);
+        co_await std::move(_background_resizing);
+    }
+
+    // Start background resizing if not already running.
+    void start_background_resizing() {
+        SCYLLA_ASSERT(EnableBackgroundResize);
```
Comment (nyh) [inline utils/lru_string_map.hh]: If this is a template parameter, you can do static_assert.

File: utils/lru_string_map.hh [hunk 136]
```diff
@@ -151,3 +176,162 @@ public:
...
+    seastar::future<> resize_in_background() {
+        while (_resize_flush || _max_cache_entries != _resize_target) {
+            if (_resize_flush) {
+                _evictions += co_await this->clear_gently(true, MaxLoop);
+                _resize_flush = false;
+                _logger.trace("flushed.");
+            }
+
+            size_t chunk = MaxLoop;
+            while (this->size() > _resize_target) {
```
Comment (nyh) [inline utils/lru_string_map.hh]: I got confused by the _resize_flush() option. If that option it true, why do we continue this function and reach this loop? After the resize_flush() aren't we guaranteed that this_size() is 0, so this loop will be skipped?

File: utils/lru_string_map.hh [hunk 137]
```diff
@@ -151,3 +176,162 @@ public:
...
+                if (!this->pop() || !lru_string_map<Value>::sanity_check()) [[unlikely]] {
```
Comment (nyh) [inline utils/lru_string_map.hh]: What is this if()? It's entirely sanity checking? If so, why does it call request_flush<true> (what's that?) instead of on_internal_error() or something?

File: alternator/parsed_expression_cache.cc (hunk 109 above)
Comment (nyh) [reply alternator/parsed_expression_cache.cc]: In the previous version it was an error-level message, so at least "debug" is an improvement :-) (by default, I believe "debug" isn't printed at all).

File: alternator/expressions.hh [hunk 138]
```diff
@@ -26,6 +28,25 @@ public:
...
+class expression_cache {
+    std::unique_ptr<expression_cache_impl> _impl;
+public:
+    struct config {
+        utils::updateable_value<uint32_t> max_cache_entries;
+    };
+    expression_cache(config cfg, stats& stats);
+    ~expression_cache();
+    // stop background tasks, if any
+    seastar::future<> stop();
```
Comment (nyh) [inline alternator/expressions.hh]: Nitpick: In Scylla we normally just write "future", not "seastar::future". If it doesn't work, it means this header doesn't include "seastarx.hh" - most already do.

File: test/boost/alternator_unit_test.cc [hunk 139]
```diff
@@ -211,3 +214,219 @@ BOOST_AUTO_TEST_CASE(exception_at_expression_parsing) {
...
+    cache.max_cache_entries.set(2);
+    cache.expected_stats.expression_cache.evictions += 2;
+    cache.check_stats("after resizing cache to 2 entries");
+
+    cache.max_cache_entries.set(0);
+    cache.expected_stats.expression_cache.evictions += 2;
+    cache.check_stats("after disabling cache");
+
+    // for resizes down with more then 3000 evictions the change may be asynchronous
+    size_t large_size = 1000000;
```
Comment (nyh) [inline test/boost/alternator_unit_test.cc]: Yikes, how long does this test take? Do you really need a million items just to be more than 3000?

File: alternator/executor.cc [hunk 140]
```diff
@@ -5895,4 +5901,13 @@ future<> executor::start() {
     return make_ready_future<>();
 }
 
+future<> executor::stop() {
+    // disconnect from the value source, but keep the value unchanged.
+    s_default_timeout_in_ms = utils::updateable_value<uint32_t>{s_default_timeout_in_ms()};
+    if (_parsed_expression_cache) {
```
Comment (nyh) [inline alternator/executor.cc]: Why is that if() needed?
If the intention is to allow stop() to be run twice safely, then you should also set _parsd_expression_cache to null - because I don't think anything else does?

**Review by nyh — APPROVED** [review]
I'm left a few questions/comments but in general, I think this is mostly ready and I "approve".
But @radoslawcybulski left some good requests and comments, so please address those before we merge this. Thanks.

File: test/boost/alternator_unit_test.cc (hunk 139 above)
Comment (m-szymon) [reply test/boost/alternator_unit_test.cc]: ~5s. I wanted to really see the stalls, but for the permanent test it doesn't have to be that much.

File: utils/lru_string_map.hh (hunk 103 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:115]: It is not used now. clear_gently is used. Other places are user disabling cache (size=0) and failed sanity check.

File: utils/lru_string_map.hh (hunk 131 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh]: I meant the first function (a corutine version of this one).
I think the configuartion change is rare, but also it's expected, that if you change configuration, an app might need some time to settle, so it would be fine for the first one to wait.

File: test/alternator/test_expression_caching.py (hunk 115 above)
Comment (radoslawcybulski) [reply test/alternator/test_expression_caching.py:435]: This might warrant some comment, unless it's common knowledge.

File: utils/lru_string_map.hh (hunk 122 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh:188]: Interesting perspective. Our logs don't print code location, so printing on someone's logger might be confusing (source line wise), but also helpful (better context).

File: utils/lru_string_map.hh [hunk 141]
```diff
@@ -0,0 +1,354 @@
...
+    // Start background resizing if not already running.
+    void start_background_resizing() {
+        if (!_background_resizing.available()) {
+            // Background thread is already running
+            return;
+        }
+        _background_resizing.ignore_ready_future();
+        _background_resizing = resize_in_background();
+    }
+    size_t max_loop = 3000; // max number of evictions before yielding to other tasks
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: `const` or `constexpr` please.

File: utils/lru_string_map.hh [hunk 142]
```diff
@@ -0,0 +1,354 @@
...
+        return true;
+    }
+
+    // Background task to resize the cache. It yields between chunks to avoid stalling the reactor.
+    // Mind that during yielding the cache may be modified by other tasks or resizing may be requested again.
+    future<> resize_in_background() {
+        size_t loop = max_loop;
+        while (!_resize_flush && _base::size() > _resize_target && pop()) {
+            // Yield control to allow other tasks to run
+            if (loop && --loop == 0) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: `if (max_loop && --loop == 0)` will better show `max_loop == 0` means no yielding.

File: utils/lru_string_map.hh (hunk 131 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: I understood - I mean that it is not called in a coroutine:
https://github.com/scylladb/scylladb/blob/96888d6ba921fca9757e615ef76d832b0273f193/alternator/parsed_expression_cache.cc#L83-L85
The synchronous version does exactly what it was requested and ends.
Once I start in background, I shouldn't wait for it - another request may want much larger change (unless another request is globally blocked - I don't know that)

Then for the testing (I want to controllable flush and set size) I have two options - synchronous update or some kind of API to verify size is updated. I think that first option (up to a certain cache size) is better.

File: utils/lru_string_map.hh (hunk 122 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:188]: The alternative is to create context, e.g. give a name to each instance.
But for utility structures like that, I don't think it is a convenient strategy.
User wants to debug his class and enables his own logger. He doesn't know that there is some other logger, that may reference his context.

File: utils/lru_string_map.hh [hunk 143]
```diff
@@ -0,0 +1,354 @@
...
+    // Reserve space for new size. Evict excess entries.
+    // If the change is too big, run it in background to avoid stalling the reactor.
+    // Returns true if the resizing is done, false if it was started in background.
+    bool resize_maybe_in_background(bool prefer_background=false) {
+        if (!_background_resizing.available()) {
+            // Background task is running.
+            return false;
+        }
+        if (!_resize_flush && _base::size() > _resize_target) {
+            if (max_loop && (prefer_background || _base::size() - _resize_target > max_loop)) {
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: You can move this `if` before `if` from line 300 and remove one from line `310` - they differ only by a comment.

File: utils/lru_string_map.hh [hunk 144]
```diff
@@ -0,0 +1,354 @@
...
+            return;
+        }
+        _background_resizing.ignore_ready_future();
+        _background_resizing = resize_in_background();
+    }
+    size_t max_loop = 3000; // max number of evictions before yielding to other tasks
+                            // if 0 then no yielding is done
+
+private:
+    size_t _resize_target = 0;
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh:239]: Correct me if i'm wrong, but you don't need `_resize_target` and it's actually actively harming you making the code harder to follow. Use just `_max_cache_entries` and:
1. if cache is fine, then nothing changes, as `if` from line `342` guards against cache overflow
2. if we are growing, then we set `_max_cache_entries` directly and do nothing else, cache goes straight to point 1
3. if we are shrinking, we set `_max_cache_entries` directly and start purging. We use `size() > _max_cache_entries` condition. We need to fix `if` from line `347` (as in this version cache might occasionally be oversized - this is fine, as this happens in the same moment as cache purging is triggered, so eventually cache will drop back to point 1) - so we just remove this `if` and turn first one (from line `342`) into `_base::size() >= _max_cache_entries`.

File: utils/lru_string_map.hh (hunk 127 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh:239]: Excellent. So let's now just drop `_resize_target` and use only `_max_cache_entries`:

1. if cache is fine (`size() <= _max_cache_entries`), then nothing changes, as if from line 342 still guards against cache overflow.
2. if user wants cache to change size to bigger, then we set `_max_cache_entries` directly and do nothing else (either cache was in point 1 - then nothing changes, or was in point 3 and might or might not still be in point 3 after size change, but it still doesn't matter, as point 3 means background shrinking is in progress and it will pick new required size immediately).
3. if user wants cache to change size to smaller, we set `_max_cache_entries` directly and call resize function. The resize function either resizes immediately (thus sending cache to point 1) or starts background resize. The background resize uses `size() > _max_cache_entries` condition and works without other changes. We only need to fix `if` from line 347 (as in this version cache might occasionally be oversized - this is fine, as this happens in point 2, which in the same moment triggers resize, so eventually cache will drop back to point 1) - so we just remove this if and turn first one (from line 342) into `_base::size() >= _max_cache_entries`.

We could also drop `_resize_flush` if we assume resizing to 0 means flushing resources, but that's slightly  different behaviour and not really worth retesting.

Even if something goes wrong with starting background purge, we already have a safety net, in line `345` a new background resize will be started automatically.

In my opinion adding second variable makes code harder to follow. It's possible both variables together have some additional use i don't see tho.

File: utils/lru_string_map.hh (hunk 141 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: Actually this can be configured at any time.

File: utils/lru_string_map.hh (hunk 143 above)
Comment (m-szymon) [reply utils/lru_string_map.hh]: They are not the same. And even if the first one is passed, we may fall into the second one.
They are similar and this if could be move into `start_background_resizing` with the `expected_change` - I will check if this looks good.

File: utils/lru_string_map.hh (hunk 127 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:239]: Mind that it is intended to work in background.
Scenario one (after sanity check fail):
1. Block new entries. 2. Flush. 3. Restore initial size.
I think we need 2 variables - `_resize_flush` may also block new entries.

Scenario two: we are in the middle of shrinking and we yield. User wants to insert new item.
If we say that current max is the one after shrink, then we have cache overflow.

So I don't agree that we could leave only one value. 
As I said we could encode the state on lower number of total bits, but I don't think it is a good idea. Sure - changing the state requires updating up to 3 variables (actually 4 - `is_background_resizing` is implicitly there), but they map directly to conditions we check.
`_max_cache_entries` - tells user how much entries he can currently have - user reads it, system writes it.
`_resize_target`, `_resize_flush` - tells system what it should do - user writes it, system read it.
Honestly I can't see where is problem with that.

**Review by m-szymon — COMMENTED** [review]
@radoslawcybulski

File: utils/lru_string_map.hh (hunk 141 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh]: Oh, wait, this is public. Please, private + setter.

File: utils/lru_string_map.hh (hunk 127 above)
Comment (radoslawcybulski) [reply utils/lru_string_map.hh:239]: Scenario 1 could be resolved: remove synchronous purge function (this way we will always have a future, when resizing), on fail set `_max_cache_entries = 0`, start resizing, add `then` to the future, which sets `_max_cache_entries` back to old value.
In scenario 2 current implementation of `make_space_for_one` already would take care of it (after changes i've mentioned) - it would `pop` one old item and return `true`, which would allow the caller to insert new item. Cache would be overflowed, but would not have grown.

I'm not yet fully sure how oppresive i should be so i will accept this. I do think tho the implementation is too complicated for the importance of the feature it delivers.

File: utils/lru_string_map.hh [hunk 145]
```diff
@@ -0,0 +1,358 @@
...
+        if (disabled()) {
+            return false;
+        }
+        if (_base::size() == _max_cache_entries) {
+            if (!pop()) [[unlikely]] {
+                // Flush was ordered, make sure it happens
+                return resize_maybe_in_background(true);
+            }
+        } else if (_base::size() > _max_cache_entries) [[unlikely]] {
+            on_internal_error(_logger, ("Cache size exceeded maximum, resizing."));
```
Comment (radoslawcybulski) [inline utils/lru_string_map.hh]: Unnecesary parenthesis.

**Review by radoslawcybulski — COMMENTED** [review]
Few minor tidbits.

File: utils/lru_string_map.hh (hunk 127 above)
Comment (m-szymon) [reply utils/lru_string_map.hh:239]: > we will always have a future, when resizing

As I explained in some other place - in my primary case I want it synchronous and I can't wait for future there.

> In scenario 2 current implementation of `make_space_for_one` already would take care of it

It wouldn't - it would do `on_internal_error` and return `false`. Sure, it could handle it, but I think it is a reasonable sanity check to not overflow what was requested. I agree that dropping sanity checks would make code simpler.

> on fail set `_max_cache_entries = 0`, start resizing, add `then` to the future, which sets `_max_cache_entries`

If "normal" resizing is already started I want to stop it in case of failed sanity check (e.g. in insert). There is difference between flush and "normal" resize. 'resize_target' is cancelable. Flush is not. Again it this connected to sanity checks. 

I tried to simplify the code - there is a small change in logic, but it should clearer - there is common `partial_resize` function for sync and async case.
