### PR TITLE
sstables_manager: do not reclaim unlinked sstables

### LINKED ISSUE #21887: malformed_sstable_exception due to reclaim and reload of bloom filters from unlinked sstables
An unlinked sstable might linger on the active list inside the sstable manager if its reference is being held elsewhere (refcount > 0). Currently, such sstables are picked up by the sstable manager for bloom filter reclamation. No error occurs during reclamation, as the bloom filter memory is simply freed. However, when the same sstable is later reloaded, `malformed_sstable_exception` error occurs because the bloom filter is no longer available on disk.

The issue is very similar to https://github.com/scylladb/scylladb/issues/19722 but that issue occurs only with sstables that were already reclaimed before getting unlinked and in this case, the sstable is reclaimed after getting unlinked. In both the cases, the reason why an sstable reference is long held after it has been unlinked is unknown and is probably unrelated to the reload/reclaim mechanism.

A testcase that reproduces this issue is attached here : [reproducer.txt](https://github.com/user-attachments/files/18095763/reproducer.txt)

Testcase result :
```
Running 1 test case...
INFO  2024-12-11 18:07:55,103 seastar - Reactor backend: linux-aio
random-seed=3400003377
INFO  2024-12-11 18:07:55,138 [shard 0:main] features - Feature UUID_SSTABLE_IDENTIFIERS is enabled
INFO  2024-12-11 18:07:55,157 [shard 0:main] sstables_manager - Reclaimed 20 bytes of memory from SSTable components. Total memory reclaimed so far is 20 bytes
ERROR 2024-12-11 18:07:55,158 [shard 0:main] sstable - Could not create SSTable component /tmp/scylla-c39114df-b372-4db8-a1cd-972228ff01e8/me-3glz_0z37_0tsj6236pt9pnxpa9r-big-Filter.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/tmp/scylla-c39114df-b372-4db8-a1cd-972228ff01e8/me-3glz_0z37_0tsj6236pt9pnxpa9r-big-Filter.db])
WARN  2024-12-11 18:07:55,159 [shard 0:main] sstable - Failed to reload reclaimed SSTable components : sstables::malformed_sstable_exception (/tmp/scylla-c39114df-b372-4db8-a1cd-972228ff01e8/me-3glz_0z37_0tsj6236pt9pnxpa9r-big-Filter.db: file not found)

```

### PR DESCRIPTION
**Pull request by lkshminarayanan**
When an sstable is unlinked, it remains in the _active list of the
sstable manager. Its memory might be reclaimed and later reloaded,
causing issues since the sstable is already unlinked. This patch updates
the on_unlink method to reclaim memory from the sstable upon unlinking,
remove it from memory tracking, and thereby prevent the issues described
above.

Added a testcase to verify the fix.

Fixes #21887

This is a bug fix in the bloom filter reload/reclaim mechanism and should be backported to older versions.

### CODE REVIEW

File: sstables/sstables.hh [hunk 1]
```diff
@@ -142,6 +142,10 @@ inline std::string_view state_to_dir(sstable_state state) {
         return quarantine_dir;
     case sstable_state::upload:
         return upload_dir;
+    case sstable_state::unlinked:
+        // this should never be called and is here for completeness
+        SCYLLA_ASSERT(false);
+        return "";
     }
```
Comment (raphaelsc) [inline sstables/sstables.hh:149]: I'd rather not introduce a unlinked to sstable state, since as you can see, it's a bit more specific than a generic state. And I am sure we can break this assumption (e.g. compaction racing with streaming) :-) 

I'd prefer if we could confine the unlinked tracking in manager, by introducing a 'set_type _unlinked', which we update in on_unlink() and deactivate().

File: sstables/sstables_manager.cc [hunk 2]
```diff
@@ -196,6 +196,15 @@ future<> sstables_manager::components_reloader_fiber() {
         while (!_reclaimed.empty() && memory_available > 0) {
             auto sstable_to_reload = _reclaimed.begin();
             const size_t reclaimed_memory = sstable_to_reload->total_memory_reclaimed();
+
+            if (sstable_to_reload->is_unlinked()) {
+                // This sstable has been unlinked already,
+                // remove it from reclaimed and try the next sstable.
+                _reclaimed.erase(sstable_to_reload);
+                _total_memory_reclaimed -= reclaimed_memory;
```
Comment (denesb) [inline sstables/sstables_manager.cc:204]: Can we just add `_total_memory_reclaimed = 0` to `sstable::unlink()` so it is not even considered by this loop instead?

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc:204]: @denesb realised after typing the above comment - I can just free the memory in unlink() and set the  `_total_memory_reclaimed` to 0. That will fix the issue.

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc]: The patch sets the _total_memory_reclaimed on unlink now.

**Comment by lkshminarayanan** [comment]
Changelog V2:
 - On unlink, the _total_memory_reclaimed is set to 0 and thus the unlinked sstable avoids the reclaim/reload cycle despite being in the _active list.
 - Removed the old logic

**Comment by lkshminarayanan** [comment]
> #### Failed Tests (1/36178):
> * [test_view_build_status_with_replace_node.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13766/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_with_replace_node_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_with_replace_node.dev.2)

https://github.com/scylladb/scylladb/issues/20638

File: sstables/sstables_manager.cc [hunk 3]
```diff
@@ -330,6 +330,9 @@ std::vector<std::filesystem::path> sstables_manager::get_local_directories(const
 }
 
 void sstables_manager::on_unlink(sstable* sst) {
+    // Reclaim memory used by the sstable components and update the tracker
+    auto memory_reclaimed = sst->reclaim_memory_from_components();
+    _total_reclaimable_memory -= memory_reclaimed;
```
Comment (denesb) [inline sstables/sstables_manager.cc:335]: I think we should just 0 both `_total_reclaimable_memory` and `_total_memory_reclaimed` here, just to be on the safe side.

Comment (raphaelsc) [reply sstables/sstables_manager.cc:335]: this is in sstables_manager, so global stats. @lkshminarayanan don't we have to adjust _total_memory_reclaimed here? since it's decreased in deactive().


I think we can extract
```
    auto memory_reclaimed = sst_with_max_memory->reclaim_memory_from_components();
    _total_memory_reclaimed += memory_reclaimed;
    _total_reclaimable_memory -= memory_reclaimed;
```
into a function and reuse it here.

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc:335]: you're right. I'll update the patch.

**Comment by lkshminarayanan** [comment]
changelog v3:
 - fix updation of `_total_memory_reclaimed`

File: sstables/sstables_manager.cc [hunk 4]
```diff
@@ -334,6 +334,8 @@ std::vector<std::filesystem::path> sstables_manager::get_local_directories(const
 }
 
 void sstables_manager::on_unlink(sstable* sst) {
+    // Reclaim memory used by the sstable components
+    reclaim_memory_from_sstable(*sst);
```
Comment (denesb) [inline sstables/sstables_manager.cc:338]: How does this prevent the sstable from being selected for reload?

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc:338]: The sstable with the highest memory usage is reclaimed whenever a new sstable is added, and the total component memory, including the new sstable's memory, exceeds the threshold. This guarantees that whenever a reclamation code is triggered, there exists atleast one sstable whose component memory is non zero, ensuring that any sstable with components memory == 0 will never be picked up for reclamation.

Relevent code here - https://github.com/scylladb/scylladb/blob/98860905d820efa15458458e9c93f148fd81b62f/sstables/sstables_manager.cc#L159-L168

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc:338]: Shall I add the following line after `auto sst_with_max_memory = std::max_element...`?
```
    if (sst_with_max_memory->total_reclaimable_memory_size() == 0) {
        return;
    }
```

As per the logic I explained above this `if` will never be true but it will make the code more clear.

Comment (denesb) [reply sstables/sstables_manager.cc:338]: I ask about the other case: when we have some free memory and want to reload some previously evicted sstable component. How will the above prevent an unlinked sstable from being picked for reloading its component?

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc:338]: Only sstables from `_reclaimed` set will be picked up for reload. Unlinked table will never end up in that set for two reasons 
1. As explained above they will never be picked up for reclaim and hence never be reloaded
2. If they were already in `_reclaimed` when they are unlinked, we explicitly remove them from that set. (#19722)

**Comment by denesb** [comment]
Very unlucky PR :(
I re-kicked CI again, @lkshminarayanan please annotate previous CI failures.

File: sstables/sstables.cc [hunk 5]
```diff
@@ -1527,6 +1527,7 @@ size_t sstable::reclaim_memory_from_components() {
             // No need to remove it from _recognized_components as the filter is still in disk.
             _components->filter = std::make_unique<utils::filter::always_present_filter>();
             memory_reclaimed_this_iteration += filter_memory_size;
+            sstlog.info("Reclaimed bloom filter of {}", get_filename());
```
Comment (denesb) [inline sstables/sstables.cc:1530]: Isn't this redundant with the log that exists in `reclaim_memory_from_sstable()`?

File: sstables/sstables_manager.cc [hunk 6]
```diff
@@ -152,6 +152,13 @@ sstable_writer_config sstables_manager::configure_writer(sstring origin) const {
     return cfg;
 }
 
+void sstables_manager::reclaim_memory_from_sstable(sstable& sst) {
+    auto memory_reclaimed = sst.reclaim_memory_from_components();
+    _total_memory_reclaimed += memory_reclaimed;
+    _total_reclaimable_memory -= memory_reclaimed;
+    smlogger.info("Reclaimed {} bytes of memory from SSTable components. Total memory reclaimed so far is {} bytes", memory_reclaimed, _total_memory_reclaimed);
```
Comment (denesb) [inline sstables/sstables_manager.cc:159]: We can make `reclaim_memory_from_components()` return the list of evicted components (in addition to the current return value) and then you can also add that to the log line here, and drop the previous patch.

**Review by denesb — CHANGES_REQUESTED** [review]

**Comment by lkshminarayanan** [comment]
> Very unlucky PR :( I re-kicked CI again, @lkshminarayanan please annotate previous CI failures.

The PR is not unlucky rather incomplete. :(
The previous issues were all related to bloom filters. I'm not able to reproduce them locally though. 
Something is still missing in this PR - possibly related to what you mentioned here https://github.com/scylladb/scylladb/pull/21895#discussion_r1882158062

**Comment by denesb** [comment]
Cover-letter needs update.

File: sstables/sstables_manager.cc (hunk 4 above)
Comment (denesb) [reply sstables/sstables_manager.cc:338]: I see, I though the bug we fix here is that we unlink sstables that are already reclaimed, but after re-reading the issue, I realized the bug is that we reclaim already unlinked sstables (then reload them later).

File: sstables/sstables.cc (hunk 5 above)
Comment (lkshminarayanan) [reply sstables/sstables.cc]: I have removed it in the new version.

File: sstables/sstables_manager.cc (hunk 6 above)
Comment (lkshminarayanan) [reply sstables/sstables_manager.cc]: I have updated the log here to print the sstable file name. For now we only reclaim bloom filters so, I have not `reclaim_memory_from_components` to return all the components that are being reclaimed. If/When we add support to reclaim more components, we can update the code to return an exact list.

**Comment by lkshminarayanan** [comment]
Changelog V4: Another attempt to fix the issue with the following changes :
- Implemented `disable_component_memory_reload()` to sstables class that just sets the `_total_memory_reclaimed` of an sstable to 0. This effectively disables reload after that point.
- Implemented `reclaim_memory_and_stop_tracking_sstable()` to reclaim memory from an sstable (if it has not been done already) and remove the sstable from reclaimable tracking metrics. This is now called during both deactivate() and unlink() and post this call, any attempts by the sstable manager to reload or reclaim from the sstable will be a no-op. The method is also idempotent, so calling it twice from deactivate() and unlink() is safe. 
- Updated the testcases

**Comment by lkshminarayanan** [comment]
@raphaelsc @denesb This is now ready for review.

File: sstables/sstables_manager.cc [hunk 7]
```diff
@@ -171,7 +171,9 @@ void sstables_manager::increment_total_reclaimable_memory_and_maybe_reclaim(ssta
     _total_memory_reclaimed += memory_reclaimed;
     _total_reclaimable_memory -= memory_reclaimed;
     _reclaimed.insert(*sst_with_max_memory);
-    smlogger.info("Reclaimed {} bytes of memory from SSTable components. Total memory reclaimed so far is {} bytes", memory_reclaimed, _total_memory_reclaimed);
+    // TODO: As of now only bloom filter is reclaimed. Print actual component names when adding support for more components.
+    smlogger.info("Reclaimed {} bytes of memory from components of {}. Total memory reclaimed so far is {} bytes",
+            sst_with_max_memory->get_filename(), memory_reclaimed, _total_memory_reclaimed);
```
Comment (denesb) [inline sstables/sstables_manager.cc:176]: Won't this put the sstable's path in the `Reclaimed {} bytes`?

**Review by denesb — APPROVED** [review]
LGTM, one small comment.

File: sstables/sstables_manager.cc (hunk 7 above)
Comment (lkshminarayanan) [reply sstables/sstables_manager.cc:176]: my bad. I'll update it.

Comment (lkshminarayanan) [reply sstables/sstables_manager.cc]: fixed it now.

**Review by denesb — APPROVED** [review]

**Comment by lkshminarayanan** [comment]
> #### Failed Tests (1/36193):
> * [test_mv_topology_change.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13901/testReport/junit/topology_custom/test_mv_topology_change/Tests___Unit_Tests___test_mv_topology_change_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_mv_topology_change.dev.3)

From the [test_py.log](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13901/artifact/testlog/x86_64/dev/failed_test/test_mv_topology_change.3.dev.3/test_py.log) :
```
21:06:39.487 INFO> [dev/topology_custom.test_mv_topology_change.1] Cluster 0b788170-bcaa-11ef-8fe2-0e0ae25cfe27 waiting for new IP...
21:06:39.487 INFO> [dev/topology_custom.test_mv_topology_change.1] Cluster 0b788170-bcaa-11ef-8fe2-0e0ae25cfe27 obtained new IP: 127.22.148.44
21:06:39.490 INFO> [dev/topology_custom.test_mv_topology_change.1] Cluster ScyllaCluster(name: 0b788170-bcaa-11ef-8fe2-0e0ae25cfe27, running: , stopped: ) adding server...
21:06:39.495 INFO> [dev/topology_custom.test_mv_topology_change.1] installing Scylla server in /scylladir/testlog/x86_64/dev/scylla-3946...
21:07:33.026 INFO> [dev/topology_custom.test_mv_topology_change.3] [ScyllaClusterManager][Task-253755] http://api/cluster/all-servers
21:07:33.028 INFO>  [17/Dec/2024:21:07:33 +0200] "GET /cluster/all-servers HTTP/1.1" 200 303 "-" "Python/3.12 aiohttp/3.9.5"
21:07:33.031 INFO> [dev/topology_custom.test_mv_topology_change.3] [ScyllaClusterManager][Task-253756] http://api/cluster/server/3940/get_log_filename
```

There is no update after `installing Scylla server...` and the `server_add` call times out.

**Comment by lkshminarayanan** [comment]
> > #### Failed Tests (1/36193):
> > 
> > * [test_mv_topology_change.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13901/testReport/junit/topology_custom/test_mv_topology_change/Tests___Unit_Tests___test_mv_topology_change_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_mv_topology_change.dev.3)
> 
> From the [test_py.log](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13901/artifact/testlog/x86_64/dev/failed_test/test_mv_topology_change.3.dev.3/test_py.log) :
> 
> ```
> 21:06:39.487 INFO> [dev/topology_custom.test_mv_topology_change.1] Cluster 0b788170-bcaa-11ef-8fe2-0e0ae25cfe27 waiting for new IP...
> 21:06:39.487 INFO> [dev/topology_custom.test_mv_topology_change.1] Cluster 0b788170-bcaa-11ef-8fe2-0e0ae25cfe27 obtained new IP: 127.22.148.44
> 21:06:39.490 INFO> [dev/topology_custom.test_mv_topology_change.1] Cluster ScyllaCluster(name: 0b788170-bcaa-11ef-8fe2-0e0ae25cfe27, running: , stopped: ) adding server...
> 21:06:39.495 INFO> [dev/topology_custom.test_mv_topology_change.1] installing Scylla server in /scylladir/testlog/x86_64/dev/scylla-3946...
> 21:07:33.026 INFO> [dev/topology_custom.test_mv_topology_change.3] [ScyllaClusterManager][Task-253755] http://api/cluster/all-servers
> 21:07:33.028 INFO>  [17/Dec/2024:21:07:33 +0200] "GET /cluster/all-servers HTTP/1.1" 200 303 "-" "Python/3.12 aiohttp/3.9.5"
> 21:07:33.031 INFO> [dev/topology_custom.test_mv_topology_change.3] [ScyllaClusterManager][Task-253756] http://api/cluster/server/3940/get_log_filename
> ```
> 
> There is no update after `installing Scylla server...` and the `server_add` call times out.

https://github.com/scylladb/scylladb/issues/21912
