### PR TITLE
raft topology: restore gossiper eps

### LINKED ISSUE #14675: Gossiper state is absent after full cluster restart with consistent topology changes enabled
This manifests as a failure in  `test_cluster_features.test_joining_old_node_fails` (dev mode):

```
    
        # Wait until the feature is considered enabled by all nodes
        cql = manager.cql
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
        logging.info(f"Waiting until {TEST_FEATURE_NAME} is enabled on all nodes")
>       await asyncio.gather(*(wait_for_feature(TEST_FEATURE_NAME, cql, h, time.time() + 60) for h in hosts))

test/topology/test_cluster_features.py:141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/util.py:129: in wait_for_feature
    await wait_for(feature_is_enabled, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_feature.<locals>.feature_is_enabled at 0x7f8540516160>
deadline = 1689170433.9396355, period = 1

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float, period: float = 1) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:43: AssertionError
```

The feature is not getting enabled as expected. The reason is that gossiper doesn't see that other nodes support it. 

One of the reasons is that endpoint states are not restored after restart. 

See that `loaded_endpoints` is empty:

```
INFO  2023-07-12 23:01:51,683 [shard 0] storage_service - initial_contact_nodes={127.49.130.4}, loaded_endpoints={}, loaded_peer_features=2

```

This was disabled in fd1b1279c4324bc06a2d7710edc55546e72b93a5.

This also manifests as the following warnings in logs (triggered from `gossiper::is_alive()`:
```
WARN  2023-07-12 23:02:54,868 [shard 0] gossip - unknown endpoint 127.49.130.2
WARN  2023-07-12 23:02:54,868 [shard 0] gossip - unknown endpoint 127.49.130.3
WARN  2023-07-12 23:02:54,868 [shard 0] gossip - unknown endpoint 127.49.130.2
WARN  2023-07-12 23:02:54,869 [shard 0] gossip - unknown endpoint 127.49.130.3
WARN  2023-07-12 23:02:54,869 [shard 0] gossip - unknown endpoint 127.49.130.2
```

Reloading of topology from system.topology calls `storage_service::update_peer_info()`, which doesn't insert endpoint state:

```
future<> storage_service::update_peer_info(gms::inet_address endpoint) {
    slogger.debug("Update peer info: endpoint={}", endpoint);
    using namespace gms;
    auto* ep_state = _gossiper.get_endpoint_state_for_endpoint_ptr(endpoint);
    if (!ep_state) {
        co_return;
    }
```

The node doesn't see anyone to gossip with, so it won't learn about other nodes (on node .4):
```
TRACE 2023-07-12 23:01:53,364 [shard 0] gossip - === Gossip round START
TRACE 2023-07-12 23:01:53,364 [shard 0] gossip - My heartbeat is now 22
DEBUG 2023-07-12 23:01:53,364 [shard 0] gossip - Set live nodes to talk: endpoint_state_map=1, all_live_nodes={}, endpoints_to_talk_with={}
DEBUG 2023-07-12 23:01:53,364 [shard 0] gossip - No live nodes yet: try initial contact point nodes={}
DEBUG 2023-07-12 23:01:53,364 [shard 0] gossip - No one to talk with
TRACE 2023-07-12 23:01:53,364 [shard 0] gossip - Performing status check ...
DEBUG 2023-07-12 23:01:53,365 [shard 0] gossip - failure_detector_loop: Wait until live_nodes={} is not empty
TRACE 2023-07-12 23:01:53,365 [shard 0] gossip - === Gossip round OK
```

The node initially gossips only with seeds. If seed pointers form a graph which connects all the nodes, they all should eventually learn about each other. That's how seeds are configured here. For example, node .2 has seeds=[.4, .3]. However, so it happens that when .2 restarts, .4 is too early in the boot process and fails the gossip exchange:

```
WARN  2023-07-12 23:01:51,124 [shard 0] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.49.130.4, application_states = {{STATUS, Value(NORMAL,869247220184916093,1)}})
```

Only exchange with .3  completes. Then later, gossip will use only that (live) node, and won't use the other seed:

```
DEBUG 2023-07-12 23:01:50,968 [shard 0] gossip - Talk to live nodes: {127.49.130.3, 127.49.130.4}
....
TRACE 2023-07-12 23:01:51,974 [shard 0] gossip - === Gossip round START
TRACE 2023-07-12 23:01:51,974 [shard 0] gossip - My heartbeat is now 27
DEBUG 2023-07-12 23:01:51,974 [shard 0] gossip - Talk to live nodes: {127.49.130.3}
TRACE 2023-07-12 23:01:51,974 [shard 0] gossip - Sending a GossipDigestSyn to 127.49.130.3:0 ...
TRACE 2023-07-12 23:01:51,975 [shard 0] gossip - Performing status check ...
DEBUG 2023-07-12 23:01:51,983 [shard 0] gossip - replicating live endpoints to other shards
TRACE 2023-07-12 23:01:51,986 [shard 0] gossip - === Gossip round OK
```

In general, it is not guaranteed that seeds will be up to date and reachable at the time of restart, so we shouldn't rely on that.

### PR DESCRIPTION
**Pull request by gusev-p**
We don't load gossiper endpoint states in `storage_service::join_cluster` if `_raft_topology_change_enabled`, but gossiper is still needed even in case of `_raft_topology_change_enabled` mode, since it still contains part of the cluster state. To work correctly, the gossiper needs to know the current endpoints. We cannot rely on seeds alone, since it is not guaranteed that seeds will be up to date and reachable at the time of restart.

The problem was demonstrated by the test `test_joining_old_node_fails`, it fails occasionally with `experimental_features: [consistent-topology-changes]` on the line where it waits for `TEST_ONLY_FEATURE` to become enabled on all nodes. This doesn't happen since `SUPPORTED_FEATURES` gossiper state is not disseminated, and feature_service still relies on gossiper to disseminate information around the cluster.

The series also contains a fix for a problem in `gossiper::do_send_ack2_msg`, see commit message for details.

Fixes #14675

### CODE REVIEW

**Comment by kostja** [comment]
Adding my points from slack discussion here:
1) Not publishing endpoint states in the gossiper in raft mode was done on purpose, to catch all cases where the code still depends on them, and switch them to use new topology_state class in raft mode.
2) Not propagating loaded endpoint states at boot matches gossip philosophy of only gossiping what this node has the first-hand knowledge about, so the second patch may well be introducing a regression that could be hard to catch. 

To avoid both issues, it's best to finalize and queue https://github.com/scylladb/scylladb/pull/14722, which addresses the original problem within our strategy of transitioning to Raft.

File: gms/gossiper.cc [hunk 1]
```diff
@@ -340,10 +340,20 @@ future<> gossiper::do_send_ack2_msg(msg_addr from, utils::chunked_vector<gossip_
...
             }
+            // Local generation for addr may have been increased since the
+            // current node sent an initial SYN. Comparing versions across
+            // different generations in get_state_for_version_bigger_than
+            // could result in loosing some app states with smaller versions.
+            const auto version = es->get_heart_beat_state().get_generation() > g_digest.get_generation()
+                ? version_type(0)
+                : g_digest.get_max_version();
+            auto local_ep_state_ptr = this->get_state_for_version_bigger_than(addr, version);
+            assert(local_ep_state_ptr);
```
Comment (tgrabiec) [inline gms/gossiper.cc:355]: asserts are banned in favor of on_internal_error().

Why assert() and not an "if" like before?

Comment (gusev-p) [reply gms/gossiper.cc:355]: changed the code a bit, now there is
```
if (!es || es->get_heart_beat_state().get_generation() < g_digest.get_generation()) {
    continue;
}
```
above, `get_state_for_version_bigger_than` returns null only if it can't find the endpoint and this can't happen now.

Comment (gusev-p) [reply gms/gossiper.cc:355]: can change it to `on_internal_error` or revert to how it was before

Comment (tgrabiec) [reply gms/gossiper.cc:355]: get_state_for_version_bigger_than() also returns an empty optional if there are no states which match the version filter and local_hb_version <= version

Comment (gleb-cloudius) [reply gms/gossiper.cc:355]: > asserts are banned in favor of on_internal_error().
> 

Is it? Where is it written? If it is the rule is enforced inconsistently which is annoying. Here is very recent commit with an assert: 00db47292bdbd21e8fa72a6f681ee30e625b90bd. And here is relatively recent commit of yours: fe7922d65cbfaf924b6d6a9504cb588655d544bc

File: service/storage_service.cc [hunk 2]
```diff
@@ -354,6 +354,16 @@ future<> storage_service::topology_state_load(cdc::generation_service& cdc_gen_s
...
             // Also ip -> id mapping is needed for address map recreation on reboot
             if (!utils::fb_utilities::is_me(ip)) {
+                // We don't load gossiper endpoint states in storage_service::join_cluster
+                // if _raft_topology_change_enabled. On the other hand gossiper is still needed
+                // even in case of _raft_topology_change_enabled mode, since it still contains part
+                // of the cluster state. To work correctly, the gossiper needs to know the current
+                // endpoints. We cannot rely on seeds alone, since it is not guaranteed that seeds
+                // will be up to date and reachable at the time of restart.
+                if (!_gossiper.get_endpoint_state_for_endpoint_ptr(ip)) {
+                    co_await _gossiper.add_saved_endpoint(ip);
```
Comment (gleb-cloudius) [inline service/storage_service.cc:364]: We are in the middle of creation of the token metadata object here and `add_saved_endpoint` access the token metadata. Shouldn't this be done after the object is fully created otherwise it looks like we access the previous version of the object here.

File: gms/gossiper.cc (hunk 1 above)
Comment (gusev-p) [reply gms/gossiper.cc]: > get_state_for_version_bigger_than() also returns an empty optional if there are no states which match the version filter and local_hb_version <= version

fixed

File: service/storage_service.cc (hunk 2 above)
Comment (gusev-p) [reply service/storage_service.cc]: fixed

**Comment by gusev-p** [comment]
v2:
  * `topology_state_load`, move `add_saved_endpoint` after `mutate_token_metadata`, so that it see thew new `token_metadata`;
  * `gossiper::do_send_ack2_msg`, restored the the of `get_state_for_version_bigger_than` result.

File: gms/gossiper.cc (hunk 1 above)
Comment (tgrabiec) [reply gms/gossiper.cc]: > > asserts are banned in favor of on_internal_error().
> 
> Is it? Where is it written?

There was a discussion in https://github.com/scylladb/scylladb/issues/7871. I don't think it's documented yet.

> If it is the rule is enforced inconsistently which is annoying. Here is very recent commit with an assert: [00db472](https://github.com/scylladb/scylladb/commit/00db47292bdbd21e8fa72a6f681ee30e625b90bd). And here is relatively recent commit of yours: [fe7922d](https://github.com/scylladb/scylladb/commit/fe7922d65cbfaf924b6d6a9504cb588655d544bc)

I can see why it's annoying, we should be more consistent.
