### PR TITLE
readers: evictable_reader: don't accidentally consume the entire partition

### LINKED ISSUE #13491: sstableloader/nodetool refresh: bad_alloc (seastar - Failed to allocate 536870912 bytes)
[X] I have read the disclaimer, and I am reporting a suspected malfunction in Scylla.
And I asked my question in Slack first and have been advised to submit an issue.

*Installation details*
Scylla version (or git commit hash): 5.1.8-0.20230319.c90807d29f30
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Rocky Linux 8.7

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): KVM
Hardware: sockets=1 cores=4 hyperthreading=n/a memory=20GB
Disks: (SSD/HDD, count) single 500 GB NVMe

I'm trying to migrate from 4 nodes Cassandra 3.11 cluster with RF=1 to 3 nodes Scylla 5.1 cluster with RF=3. I have an issue with Scylla performance degradation when loading SSTables.
I have tiny Scylla 5.1 cluster of 3 nodes: KVM virtual machines with 4 CPU, 20 GB RAM, single vrtio-blk 500 GB disks with write through cache and none (noop) scheduler for data and commit logs backed up by host's NVMe and 1 Gbit/s virtio network interface. OS is fresh default minimal install of Rocky Linux 8. Each VM resides on separate physical server without any additional load, except one VM where I run `sstableloader` on. All 3 nodes are configured as seeds. `scylla_setup` successfully performed before cluster launch. Scylla is running with these parameters:
```
# ps aux | grep /usr/bin/scylla | grep -v grep
scylla    149334 19.5  3.0 17180289500 566716 ?  SLsl 16:01   0:03 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --memory 16G --smp 4 --overprovisioned --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-3 --lock-memory=1
```
And there are few tweaks in default `scylla.yaml`:
```
max_clustering_key_restrictions_per_query: 1000
max_partition_key_restrictions_per_query: 1000
auto_snapshot: false
```
There is no data in the cluster except system tables. I'm trying to do offline migration of single keyspace from Cassandra 3.11: I did `desc keyspace` and `nodetool snapshot` on each Cassandra node, copied snapshotted SSTables (~250 GB) to intermediate VM mentioned above, modified schema to have RF=3 and to fit Scylla requirements, removed materialized views SSTables and trying to run `sstableloader` with 'consistensy-level=QUORUM' and different values of 'throttle' option. I've managed to reach reasonable values of Load (80-90%) and RPS (~50k) in Grafana of Scylla Monitoring Stack, which is installed on the intermediate VM by the way, but at some point I start to get a lot of timeouts, RPS goes down to ~300-500 and Load down to ~10% and some stalls appear in graphs and logs ("Reactor stalled for 32 ms on shard..."). There were plenty of entries like "large_data - Writing large partition" and some "seastar_memory - oversized allocation" in the logs as well. I've increased log level via `--default-log-level` and repeated the procedure from scratch and got these messages followed performance degradation: 
```
[shard 3] table - failed to write sstable /var/lib/scylla/data/feed/comment_reactions-80011e30d3bd11ed80ea9c424ef35031/me-11-big-Data.db: std::bad_alloc (std::bad_alloc)
...
[shard 3] storage_proxy - exception during mutation write to 192.168.71.119: std::bad_alloc (std::bad_alloc)
...
[shard 0] view - Error applying view update to 192.168.71.119 (view: feed.feed_news2_group_id_idx_index, base token: -7209633517430772363, view token: 2945182322382062539): std::bad_alloc (std::bad_alloc)
...
[shard 3] table - failed to flush memtable for feed.likes: std::bad_alloc (std::bad_alloc)
...
[shard 3] sstable - failed reading index for /var/lib/scylla/data/feed/likes-70737d50d3bd11ed80ea9c424ef35031/me-63-big-Data.db: std::bad_alloc (std::bad_alloc)
```
I've been suggested in Slack to add `--abort-on-seastar-bad-alloc` argument to Scylla to make it generate coredump and to use `nodetool refresh` instead of `sstableloader` as more convenient way to achieve my goal. I tried to upload SSTables of largest table of keyspace (~35GB): put all SSTables of the table from all snapshots from all Cassandra nodes on one of Scylla nodes and run `nodetool refresh -las`, and looks like Scylla DoSed itself: after 58 minutes of silently doing something `nodetool` failed with "connection refused" and nodes went to restart loop (because of `--abort-on-seastar-bad-alloc` I guess) with this in logs: "seastar - Failed to allocate 536870912 bytes" (the value is always the same for different shards and nodes). And there are lots of messages about corrupted commit logs.

I'v been suggested to try `nodetool refresh` without `-las` and/or decrease number of CPUs/shards for Scylla to give it more memory per shard, but a) all of these option give almost same results: coredumps and restart loop and b) such setups differ from cluster configuration I'm planned to have. So I uploaded coredump and `node_health_check` report for the case with 4 CPUs and `nodetool refresh -las`: `fecd27b5-0bb2-4329-aaa9-b0491455d700` is the UUID.

So at the moment I'm not able to migrate from Cassandra to Scylla even in offline as `sstableloader`/`nodetool refresh` take extremely long to load not so much of data into Scylla, and I can't afford such downtime, or these operations just break Scylla.

Please suggest how to troubleshoot the issue.

### PR DESCRIPTION
**Pull request by kbr-scylla**
The evictable reader must ensure that each buffer fill makes forward progress, i.e. the last fragment in the buffer has a position larger than the last fragment from the previous buffer-fill. Otherwise, the reader could get stuck in an infinite loop between buffer fills, if the reader is evicted in-between.

The code guranteeing this forward progress had a bug: the comparison between the position after the last buffer-fill and the current last fragment position was done in the wrong direction.

So if the condition that we wanted to achieve was already true, we would continue filling the buffer until partition end which may lead to OOMs such as in #13491.

There was already a fix in this area to handle `partition_start` fragments correctly - #13563 - but it missed that the position comparison was done in the wrong order.

Fix the comparison and adjust one of the tests (added in #13563) to detect this case.

After the fix, the evictable reader starts generating some redundant (but expected) range tombstone change fragments since it's now being paused and resumed. For this we need to adjust mutation source tests which were a bit too specific. We modify `flat_mutation_reader_assertions` to squash the redundant `r_t_c`s.

Fixes #13491

### CODE REVIEW

**Comment by kbr-scylla** [comment]
Thanks to @michoecho for noticing this
https://github.com/scylladb/scylladb/pull/13563/files#r1239683274

**Review by michoecho — APPROVED** [review]
LGTM

**Comment by kbr-scylla** [comment]
Unfortunately, this breaks some tests, I don't understand why.

**Comment by kbr-scylla** [comment]
```
INFO  2023-06-23 17:22:04,568 [shard 0] testlog - void test_range_tombstones_v2(tests::reader_concurrency_semaphore_wrapper &, populate_fn_ex)
test/lib/flat_mutation_reader_assertions.hh(171): fatal error: in "test_multishard_combining_reader_with_tiny_buffer": Expected row with key ckp{000c636b30303030303030303035}, but got {mutation_fragment: range tombstone change {position: clustered, ckp{0
00c636b30303030303030303031}, -1} {range_tombstone_change: pos={position: clustered, ckp{000c636b30303030303030303031}, -1}, {tombstone: none}}}
```

**Comment by kbr-scylla** [comment]
Note that previously, if we had `buffer().back().position() < _next_position_in_partition` after calling `_reader->move_buffer_content_to(*this)`, we would never enter this loop:
```cpp
        while (!_next_position_in_partition.is_partition_start() && next_mf && _tri_cmp(_next_position_in_partition, buffer().back().position()) <= 0) {
            push_mutation_fragment(_reader->pop_mutation_fragment());
            next_mf = co_await _reader->peek();
        }
```
so we wouldn't actually guarantee this forward progress condition.

Maybe now when we actually run it, it has some unintended side effects.

**Comment by kbr-scylla** [comment]
```
INFO  2023-06-23 17:47:37,464 [shard 0] testlog - void test_range_tombstones_v2(tests::reader_concurrency_semaphore_wrapper &, populate_fn_ex)
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - Skip to next partition
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - Expecting partition start with key {key: pk{0008e0bfa7c48fdbbb75}, token: 5221359033865969216}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - read_next(): {mutation_fragment: partition start {position: partition_start, null, 0} {partition_start: pk {key: pk{0008e0bfa7c48fdbbb75}, token: 5221359033865969216} partition_tombstone {tombstone: none}
}}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - Expect ckp{000c636b30303030303030303030}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - read_next(): {mutation_fragment: clustering row {position: clustered, ckp{000c636b30303030303030303030}, 0} {clustering_row: ck 000c636b30303030303030303030 dr {deletable_row: {{row:
    v{ atomic_cell{v1,ts=-9223372036854775807,expiry=-1,ttl=0} }}}}}}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - Expect {range_tombstone_change: pos={position: clustered, ckp{000c636b30303030303030303031}, -1}, {tombstone: timestamp=-9223372036854775806, deletion_time=1687535257}}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - read_next(): {mutation_fragment: range tombstone change {position: clustered, ckp{000c636b30303030303030303031}, -1} {range_tombstone_change: pos={position: clustered, ckp{000c636b30303030303030303031}, -
1}, {tombstone: timestamp=-9223372036854775806, deletion_time=1687535257}}}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - Expect ckp{000c636b30303030303030303035}
TRACE 2023-06-23 17:47:37,465 [shard 0] testlog - read_next(): {mutation_fragment: range tombstone change {position: clustered, ckp{000c636b30303030303030303031}, -1} {range_tombstone_change: pos={position: clustered, ckp{000c636b30303030303030303031}, -
1}, {tombstone: none}}}
test/lib/flat_mutation_reader_assertions.hh(171): ESC[4;31;49mfatal error: in "test_multishard_combining_reader_with_tiny_buffer": Expected row with key ckp{000c636b30303030303030303035}, but got {mutation_fragment: range tombstone change {position: clus
tered, ckp{000c636b30303030303030303031}, -1} {range_tombstone_change: pos={position: clustered, ckp{000c636b30303030303030303031}, -1}, {tombstone: none}}}ESC[0;39;49m
```

since @michoecho is too shy to post his findings:

the tombstone closing `r_t_c`, which is unexpected by this test, is emitted by this code:
```cpp
    if (_reader_recreated) {
        // Recreating the reader breaks snapshot isolation and creates all sorts
        // of complications around the continuity of range tombstone changes,
        // e.g. a range tombstone started by the previous reader object
        // might not exist anymore with the new reader object.
        // To avoid complications we reset the tombstone state on each reader
        // recreation by emitting a null tombstone change, if we read at least
        // one clustering fragment from the partition.
        if (_next_position_in_partition.region() == partition_region::clustered
                && _tri_cmp(_next_position_in_partition, position_in_partition::before_all_clustered_rows()) > 0) {
            push_mutation_fragment(*_schema, _permit, range_tombstone_change{position_in_partition_view::before_key(_next_position_in_partition), {}});
        }
```

Apparently previously we would not have recreated the reader.
Now the question is: is the test too specific, or does this code break reader interface specification?

**Review by denesb — APPROVED** [review]
The fix looks good to me. My brain started hurting from starting to think over the entire context of this loop.

Incredible how this bug managed to hide for this long, the evictable reader has the most tailored tests of all readers, by far.

**Comment by michoecho** [comment]
@denesb Your insight is still needed to deal with the failing tests (see https://github.com/scylladb/scylladb/pull/14375#issuecomment-1604492306).

The failure seems benign, so I guess the test is at fault here (because it can't deal with noncanonical representations of the range tombstones).

But why is the reader recreated for every buffer? Shouldn't it be only paused or something? (I don't know anything about any of this, and I'm just asking based on how the words sound. The question might be completely off base).

File: readers/multishard.cc [hunk 1]
```diff
@@ -607,7 +607,7 @@ future<> evictable_reader_v2::fill_buffer() {
         // First make sure we've made progress w.r.t. _next_position_in_partition.
         // This loop becomes inifinite when next pos is a partition start.
         // In that case progress is guranteed anyway, so skip this loop entirely.
-        while (!_next_position_in_partition.is_partition_start() && next_mf && _tri_cmp(_next_position_in_partition, buffer().back().position()) <= 0) {
+        while (!_next_position_in_partition.is_partition_start() && next_mf && _tri_cmp(buffer().back().position(), _next_position_in_partition) <= 0) {
             push_mutation_fragment(_reader->pop_mutation_fragment());
             next_mf = co_await _reader->peek();
         }
```
Comment (denesb) [inline readers/multishard.cc:613]: I think we can drop this entire loop. We already validated in `examine_first_fragments()` that the first non-dropped fragment in the new buffer is` >= _next_position_in_partition`. So this loop is pointless now that I think of it.
We ensure separately that we have not stopped in the middle of a range of fragments that have the same position (the loop below).

**Comment by denesb** [comment]
> @denesb Your insight is still needed to deal with the failing tests (see [#14375 (comment)](https://github.com/scylladb/scylladb/pull/14375#issuecomment-1604492306)).
> 
> The failure seems benign, so I guess the test is at fault here (because it can't deal with noncanonical representations of the range tombstones).
> 
> But why is the reader recreated for every buffer? Shouldn't it be only paused or something? (I don't know anything about any of this, and I'm just asking based on how the words sound. The question might be completely off base).

The tests in this file intentionally evict the reader every single time. This is combined with a tiny reader buffer that can fit a single fragment only, so the logic around reader recreation is stressed to the maximum.

I don't know if the failure is benign or not, it possibly is. I'm afraid there is now way around this, someone has to dig into this test and find out what's wrong. This test is part of the standard mutation stream torture test suite, and as I remember, I didn't have to adapt this suite to the evictable reader and its downstream users so far.

File: readers/multishard.cc (hunk 1 above)
Comment (kbr-scylla) [reply readers/multishard.cc:613]: > I think we can drop this entire loop. We already validated in examine_first_fragments() that the first non-dropped fragment in the new buffer is >= _next_position_in_partition.

But only in the case of `_reader_recreated`, no?

**Comment by denesb** [comment]
> * Is closing and reopening the range tombstone like that in arbitrary points legal (w.r.t. the contract of flat readers)?

Yes, completely legal.

> * If it's legal, this makes mutation fragment streams non-canonical. What do we do we with the test? Do we teach the `.produces*` functions to eat useless redundant unnecessary unneeded range tombstone end/start pairs?

Correct, mutation fragment streams in general are not canonical, and not just because of range tombstone changes. The process to obtain a canonical mutation fragment stream is called compaction. We had to change tests to compact both expected and actual data before comparing, to avoid false-positive failures due to artificial and meaningless differences. Looks like this test needs such a treatment too.

**Comment by kbr-scylla** [comment]
v2:
added another commit (by Michał) which wraps the tested reader in mutation source tests, removing the redundant range tombstone change fragments.

Thanks to @michoecho for doing the dirty work

**Review by denesb — CHANGES_REQUESTED** [review]
Redundancy is allowed by the v2 spec and all code interacting with v2 streams must be able to deal with that, including tests. The proper way of getting rid of redundancy is compaction. So I don't understand why this PR is going to such lengths to avoid either adapting the test to the v2 spec, or use compaction to obtain a canonical stream which will not have redundant range tombstone changes.

**Comment by michoecho** [comment]
>The proper way of getting rid of redundancy is compaction. So I don't understand why this PR is going to such lengths to avoid either adapting the test to the v2 spec, or use compaction to obtain a canonical stream which will not have redundant range tombstone changes.

@denesb Could you be more specific? How do I do this compaction you are speaking of?

I expected `compacting_reader` to do that, but I tried, failed, read its code, and realized that it doesn't remove redundant RTCs.
I don't see any way to do that other than piping the fragments into a mutation_partition and reading it back. But that's not cool because it adds a dependency on mutation_partition, and doesn't detect reordering, among other things.

> Redundancy is allowed by the v2 spec and all code interacting with v2 streams must be able to deal with that, including tests. 

I gave a rationale in a comment and in the commit message. Rejecting redundant RTCs makes the test more fragile, but it's a good thing in moderation. E.g. if all tests were OK with redundant RTCs, you could accidentally change some reader to add a redundant RTC after every row and nobody would notice. It's all a matter of what we want.

**Comment by michoecho** [comment]
> I gave a rationale in a comment and in the commit message. Rejecting redundant RTCs makes the test more fragile, but it's a good thing in moderation.

I think the important thing when adding implementation-testing tests (as opposed to contract-testing tests) is to document it clearly, so that when the test fails due to a contract-correct change, the author knows that it's just an implementation change and can just delete the test if its no longer useful or applicable.

A blanket ban on implementation-testing tests wouldn't be useful, I think.

**Comment by kbr-scylla** [comment]
> or use compaction to obtain a canonical stream which will not have redundant range tombstone changes.

But that's exactly what Michał's wrapper is doing.

**Comment by michoecho** [comment]
> But that's exactly what Michał's wrapper is doing.

My wrapper isn't doing *exactly* that. In fact, it's only doing a tiny subset of actual compaction. Actual stream compaction replaces expired live cells with tombstones, removes expired tombstones, removes cells and tombstones covered by higher tombstones, and canonicalizes range tombstone changes.

My wrapper only does the last thing, and only partially — it removes RTCs which are redundant due to only covering a zero-length interval, but it doesn't remove RTCs which are redundant due to the fact that they don't change the tombstone (i.e. they "change" timestamp t1 to timestamp t2 where t1 == t2).

So I understand that Botond's point was that we shouldn't add special wrappers for this test if we can just use the "proper" compaction. The problem is, I can't find out how to do the proper compaction. (And I'm not convinced that slapping on a full compaction is a good idea, because it will allow nonfunctional — performance/redundancy — issues to pass through undetected more easily).

**Comment by denesb** [comment]
> > I gave a rationale in a comment and in the commit message. Rejecting redundant RTCs makes the test more fragile, but it's a good thing in moderation.
> 
> I think the important thing when adding implementation-testing tests (as opposed to contract-testing tests) is to document it clearly, so that when the test fails due to a contract-correct change, the change author can learn what was the test's author intention and can just delete the test if its no longer useful or applicable (or heed the test if it shows that some useful, but not mandatory, property was destroyed by the change).
> 
> A blanket ban on implementation-testing tests wouldn't be useful, I think.

All the tests in mutation_source_test.cc are contract tests. They test that an unspecified reader adheres to the reader contract. Implementation tests also exists, these test specific readers directly.

**Comment by denesb** [comment]
> So I understand that Botond's point was that we shouldn't add special wrappers for this test if we can just use the "proper" compaction. The problem is, I can't find out how to do the proper compaction. (And I'm not convinced that slapping on a full compaction is a good idea, because it will allow nonfunctional — performance/redundancy — issues to pass through undetected more easily).

Maybe we should make compaction do that, I thought it already does. But that is a bit too much to slap on a bugfix PR.
I think a better solution is to introduce a new `flat_reader_assertions_v2::produces_effective_range_tombstone_change()`, which is similar to the existing `flat_reader_assertions_v2::produces_range_tombstone_change()`, but it ignores redundant range tombstone changes.
We had similar methods for range tombstones, back in the v1 days, because range tombstones provided even more variety in representing the same set of underlying writes, so tests had to be even more lenient in how they check range tombstones coming from readers.

**Comment by kbr-scylla** [comment]
>  I think a better solution is to introduce a new flat_reader_assertions_v2::produces_effective_range_tombstone_change(), which is similar to the existing flat_reader_assertions_v2::produces_range_tombstone_change(), but it ignores redundant range tombstone changes.

We already have a working solution, what is the reason for implementing yet another solution (`produces_effective_range_tombstone_change`) compared to what we have here, considering that a significant part of an engineer's work day was already spent to implement this? Is there a clear, objective advantage of this other solution? If not, then it's just too much PITA to do this and IMO a waste of time. It looks like a subjective thing, some may like this more, some may like that.

The current solution is what you suggested initially, i.e. compacting the stream. It's not compacting it 100%, but it is compacting the RTCs. So I suggest we go with it.

**Comment by michoecho** [comment]
I too think we should leave testing framework improvement ideas out of a bugfix issue for a cluster-crashing bug. It's just a test, we can change it any time we want. But we don't want the bug to survive to another patch release because we were bikeshedding unit tests.

**Comment by kbr-scylla** [comment]
Looks like CI wasn't triggered automatically.
Started one manually: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2105/

**Comment by denesb** [comment]
Turns out we have an existing mechanism for ignoring spurious tombstones, it just has to be expanded a bit to cover this more contrived case:
```diff
$ git diff
diff --git a/test/lib/flat_mutation_reader_assertions.hh b/test/lib/flat_mutation_reader_assertions.hh
index fc3202c794..0678a83c82 100644
--- a/test/lib/flat_mutation_reader_assertions.hh
+++ b/test/lib/flat_mutation_reader_assertions.hh
@@ -59,10 +59,26 @@ class flat_reader_assertions_v2 {
                 continue;
             }
             // silently ignore rtcs that don't change anything
-            if (next->is_range_tombstone_change() && next->as_range_tombstone_change().tombstone() == _rt) {
-                testlog.trace("Received spurious closing rtc: {}", mutation_fragment_v2::printer(*_reader.schema(), *next));
-                _reader().get();
-                continue;
+            if (next->is_range_tombstone_change()) {
+                auto rtc_mf = std::move(*_reader().get());
+                auto tomb = rtc_mf.as_range_tombstone_change().tombstone();
+                auto cmp = position_in_partition::tri_compare(*_reader.schema());
+                // squash rtcs with the same pos
+                while (auto next_maybe_rtc = _reader.peek().get0()) {
+                    if (next_maybe_rtc->is_range_tombstone_change() && cmp(next_maybe_rtc->position(), rtc_mf.position()) == 0) {
+                        tomb = next_maybe_rtc->as_range_tombstone_change().tombstone();
+                        _reader().get0();
+                    } else {
+                        break;
+                    }
+                }
+                rtc_mf.mutate_as_range_tombstone_change(*_reader.schema(), [tomb] (range_tombstone_change& rtc) { rtc.set_tombstone(tomb); });
+                if (tomb == _rt) {
+                    testlog.trace("Received spurious closing rtcs, equivalent to: {}", mutation_fragment_v2::printer(*_reader.schema(), rtc_mf));
+                    continue;
+                }
+                _reader.unpop_mutation_fragment(std::move(rtc_mf));
+                next = _reader.peek().get0();
             }
             return next;
         }
```

When there is a problem, I much prefer to reuse and expand existing mechanisms, to creating a tailored "solution" (one might say hack) that only covers the problem at hand. I don't think this is bikeshedding.

**Comment by kbr-scylla** [comment]
@denesb one of the tests is failing with this:
```
=== TEST.PY STARTING TEST boost.sstable_conforms_to_mutation_source_test.test_sstable_reversing_reader_random_schema.1 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/home/kbr/dev/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
build/dev/test/boost/sstable_conforms_to_mutation_source_test --run_test=test_sstable_reversing_reader_random_schema --report_level=no --logger=HRF,test_suite:XML,test_suite,/home/kbr/dev/scylla/testlog/dev/xml/boost.sstable_conforms_to_mutation_source_test.test_sstable_reversing_reader_random_schema.1.xunit.xml --catch_system_errors=no --color_output=false -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100
=== TEST.PY TEST boost.sstable_conforms_to_mutation_source_test.test_sstable_reversing_reader_random_schema.1 OUTPUT ===
Running 1 test case...
Entering test module "Master Test Suite"
test/boost/sstable_conforms_to_mutation_source_test.cc(112): Test case "test_sstable_conforms_to_mutation_source_mc_tiny" is skipped because disabled
test/boost/sstable_conforms_to_mutation_source_test.cc(116): Test case "test_sstable_conforms_to_mutation_source_mc_medium" is skipped because disabled
test/boost/sstable_conforms_to_mutation_source_test.cc(120): Test case "test_sstable_conforms_to_mutation_source_mc_large" is skipped because disabled
test/boost/sstable_conforms_to_mutation_source_test.cc(124): Test case "test_sstable_conforms_to_mutation_source_md_tiny" is skipped because disabled
test/boost/sstable_conforms_to_mutation_source_test.cc(128): Test case "test_sstable_conforms_to_mutation_source_md_medium" is skipped because disabled
test/boost/sstable_conforms_to_mutation_source_test.cc(132): Test case "test_sstable_conforms_to_mutation_source_md_large" is skipped because disabled
test/boost/sstable_conforms_to_mutation_source_test.cc(188): Entering test case "test_sstable_reversing_reader_random_schema"
INFO  2023-06-27 13:28:32,293 seastar - Reactor backend: linux-aio
INFO  2023-06-27 13:28:32,293 [shard 0] seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
INFO  2023-06-27 13:28:32,294 [shard 0] seastar - Created fair group io-queue-0 for 2 queues, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000, per tick grab 6291456
INFO  2023-06-27 13:28:32,294 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-06-27 13:28:32,294 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-06-27 13:28:32,294 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
random-seed=124692838
test/lib/flat_mutation_reader_assertions.hh(333): fatal error: in "test_sstable_reversing_reader_random_schema": Expected {range_tombstone_change: pos={position: clustered, ckp{001c0000000200000008eebc144800077eff00000008ff4780ebb8672f8c000420ccc389001600000001000000087fc2c8e5a7ffe08e000000021e38}, -1}, {tombstone: none}}, but got {mutation_fragment: clustering row {position: clustered, ckp{001c0000000200000008eebc144800077eff00000008ff4780ebb8672f8c000420ccc389001600000001000000087fc2c8e5a7ffe08e000000021e38}, 0} {clustering_row: ck 001c0000000200000008eebc144800077eff00000008ff4780ebb8672f8c000420ccc389001600000001000000087fc2c8e5a7ffe08e000000021e38 dr {deletable_row: {row_tombstone: {tombstone: timestamp=4462215859686687488, deletion_time=1687865312}{shadowable tombstone: none}} {{row:
    v1{ atomic_cell{98764354y8mo25d22h30m29s385ms849us467ns,ts=4502222188215029579,expiry=-1,ttl=0} }}}}}}
test/boost/sstable_conforms_to_mutation_source_test.cc(188): Leaving test case "test_sstable_reversing_reader_random_schema"; testing time: 152100us
Leaving test module "Master Test Suite"; testing time: 152140us
=== TEST.PY SUMMARY START ===
Test exited with code 201

=== TEST.PY SUMMARY END ===
```

**Comment by kbr-scylla** [comment]
> When there is a problem, I much prefer to reuse and expand existing mechanisms, to creating a tailored "solution" (one might say hack) that only covers the problem at hand. I don't think this is bikeshedding.

Whether the diff you proposed is more or less hacky than `trivial_rtc_removing_reader`, is also subjective.
IMO `trivial_rtc_removing_reader` is a nice abstraction, just from reading the name and the comment I know what it's doing.

**Comment by denesb** [comment]
> Whether the diff you proposed is more or less hacky than `trivial_rtc_removing_reader`, is also subjective.

How is fixing code that was supposed to ignore rtcs that don't represent meaningful changes hacky? The original author of this code could have just patched the handful of tests that were suffering from this to resolve the pain. Instead they patched the generic test utility so all present and future users benefit from this. And BTW, there is a strict mode too, which tests can opt-in to use, and then nothing will be dropped and the stream is compared verbatim.

> IMO `trivial_rtc_removing_reader` is a nice abstraction, just from reading the name and the comment I know what it's doing.

See above. When we find a deficiency in the testing framework, let's fix that instead of creating a workaround that benefits the single test that happens to hit this deficiency.

**Comment by denesb** [comment]
> @denesb one of the tests is failing with this diff:

[fix.txt](https://github.com/scylladb/scylladb/files/11881795/fix.txt)

**Comment by michoecho** [comment]
> How is fixing code that was supposed to ignore rtcs that don't represent meaningful changes hacky?

Because _it wasn't_ supposed to do that.

flat_mutation_assertions_v2 wasn't supposed to ignore them at first, then this was changed (last year) to shut up tests failing after a mutation_partition change.

This means many tests were written with the assumption that flat_mutation_assertions_v2's _doesn't_ ignore redundant RTCs. What if they were meant to check the exact stream, not a canonicalized stream? Then the tests silently lost some of their diagnostic value.

Why would a user expect that flat_mutation_assertions_v2 ignores redundancy? I didn't.
Why would it remove some redundancy, but not all of it? It's not documented.

Anyway, I have no objections to modifying `flat_mutation_reader_assertions_v2`. But I disagree with it being the principled approach. It's moving the code from one undocumented, implementation-defined state to another.

**Review by michoecho — APPROVED** [review]

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
For the record, when we were discussing the v2 spec, I pushed hard for forbidding fragments sharing positions in the fragments stream. Exactly because I knew we would be in this mess.

**Comment by denesb** [comment]
> This means many tests were written with the assumption that flat_mutation_assertions_v2's _doesn't_ ignore redundant RTCs. What if they were meant to check the exact stream, not a canonicalized stream? Then the tests silently lost some of their diagnostic value.

I would say almost all tests are written with the assumption that the stream is canonicalized. Simply because it makes the tests simple and programmers are lazy.

> Why would a user expect that flat_mutation_assertions_v2 ignores redundancy? I didn't. Why would it remove some redundancy, but not all of it? It's not documented.

As a user you can expect that `flat_mutation_assertions_v2` knows what is important to check on a stream and what is not important (can be ignored) and that all this logic is centralized there. The fact that it is not documented is sad. For some reason we treat test code like second class citizen, which deserves no documentation at all.

**Comment by mykaul** [comment]
@avikivity , @tgrabiec  - please review in high priority, this is breaking repairs out there.

**Review by tgrabiec — APPROVED** [review]
