### PR TITLE
Fix secondary index feature with tablets

### LINKED ISSUE #16371: CQL LSI promises about synchronous view updates should match implementation
Today, Scylla's documentation promises that our CQL extension of "local secondary indexes" (LSI) provide **synchronous view updates**. The document docs/cql/cql-extensions.md claims that regular ("global") secondary indexes can be requested to be synchronous but for local secondary indexes (created using a ScyllaDB extension to CQL) this is the default:

> Local secondary indexes already have synchronous updates, so there's no need to explicitly mark them as such.

The official LSI documentation in docs/using-scylla/local-secondary-indexes.rst also says:

> As of Scylla Open Source 4.0, updates for local secondary indexes are performed **synchronously**. When updates are synchronous, the client acknowledges the write operation only **after both** the base table modification **and** the view up
date are written. This is important to note because the process is no longer asynchronous and the modifications are immediately reflected in the index. In addition, if the view update fails, the client receives a write error.

This is **no longer true** with tablets. With tablets, base and view tablet replication is not guaranteed to be the same, so view updates are not always local, and the serendipitous ("implicit") synchronous updates  no longer happen. So now we have two options:

1. Change the documentation to match the implementation. I.e., remove the promises of synchronous updates in CQL LSI in the aforementioned (and any more?) documents. This is we did for CQL materialized views in https://github.com/scylladb/scylladb/pull/16369

2. Change the implementation to match the documentation. I.e., leave the promise of synchronous updates, and enable the `synchronous_updates=true` option on the view created to back the LSI. This is what we did for Alternator LSI in https://github.com/scylladb/scylladb/pull/16353 - because the DynamoDB API requires that updates be synchronous (i.e., support a strongly-consistent read immediately after write).

The main question we need to ask ourselves is why we added the concept of LSI to Scylla as a CQL extension. If consistency is part of the story - the ability to read from the index immediately after a write - then we should choose option 2. I also lean towards option 2.

However, please note that option 2 implies a performance compromise - we no longer benefit from **local** updates that we had in the past and improved performance, and to make things even worse, we make updates synchronous and increase latency further. However, if in the future we implement a feature where base and view tablets can migrate together, we will win this performance back.

### LINKED ISSUE #16396: CREATE INDEX fails if the keyspace is based on tablets
In issue #16194 we noticed that CREATE MATERIALIZED VIEW fails on a keyspace based on tablets, and fixed it (in PR https://github.com/scylladb/scylladb/pull/16205).

We now have exactly the same problem with CREATE INDEX - it complains "Tablet map not found for table 8f21f6
51-9938-11ee-bb72-d0bc38cc08c7" exactly like we had in #16194. It needs to be fixed similarly.

### PR DESCRIPTION
**Pull request by nyh**
Before this series, materialized views already work correctly on keyspaces with tablets, but secondary indexes do not. The goal of these series is make CQL secondary indexes fully supported on tablets:

1. First we need to make CREATE INDEX work with tablets (it didn't before this series). Fixes #16396.
2. Then we need to keep the promise that our documentation makes - that **local** secondary index should be synchronously updated - Fixes #16371.

As you can see in the patches below, and as was expected already in the design phase, the code changes needed to make indexes support tablets were minimal. But writing reliable tests for these issues was the biggest effort that went into this series.

### CODE REVIEW

**Comment by nyh** [comment]
Note to reviewers: Only the last three patches are new in this PR, the previous ones are from previous PRs which haven't got in yet. Please review only the last three patches here.

File: db/schema_tables.cc [hunk 1]
```diff
@@ -2691,14 +2691,32 @@ static void make_update_indices_mutations(
...
+    // The callbacks must be called in a Seastar thread, which means that
+    // *this* function must be called in a Seastar thread when creating an
+    // index.
+    for (auto&& name : diff.entries_only_on_right) {
         const index_metadata& index = new_table->all_indices().at(name);
         add_index_to_schema_mutation(new_table, index, timestamp, indices_mutation);
         auto& cf = db.find_column_family(new_table);
         auto view = cf.get_index_manager().create_view_for_index(index, new_token_column_computation);
         auto view_mutations = make_view_mutations(view, timestamp, true);
         view_mutations.copy_to(mutations);
```
Comment (tgrabiec) [inline db/schema_tables.cc:2716]: Maybe worth extracting this to a function/lambda to avoid duplication?

File: test/topology_experimental_raft/test_mv_tablets.py [hunk 2]
```diff
@@ -7,15 +7,74 @@
...
+# information to propagate to all servers).
+async def get_tablet_replicas(manager: ManagerClient, server: ServerInfo, keyspace_name: str, table_or_view_name: str, token: int):
+    host = (await wait_for_cql_and_get_hosts(manager.cql, [server], time.time() + 60))[0]
+    await read_barrier(manager.cql, host)
+
+    # "table_or_view_name" may be either a table or a view, and those are
+    # listed in different system tables so we may need to search both:
+    matches = list(await manager.cql.run_async(f"select id from system_schema.tables where keyspace_name = '{keyspace_name}' and table_name = '{table_or_view_name}'"))
+    if not matches:
+        matches = list(await manager.cql.run_async(f"select id from system_schema.views where keyspace_name = '{keyspace_name}' and view_name = '{table_or_view_name}'"))
```
Comment (tgrabiec) [inline test/topology_experimental_raft/test_mv_tablets.py:38]: You could extend ManagerClient.get_table_id().

Comment (nyh) [reply test/topology_experimental_raft/test_mv_tablets.py:38]: That's exactly why I don't like putting convenience functions in "global" places - unless very well thought out, when the next user wants to use them they never do the right thing, and then they start to get 17 different options and features that people needed in 17 different tests. (again, this is my bad experience from dtest speaking..).

In this case, as you guessed I tried to use get_table_id() but it wasn't good enough because it didn't search for views. You're right I could have improved get_table_id() but the question is - why. Why should the get_table_id() functionality exist in the "manager"? Why is it the job of the cluster manager to provide 100 different convenience functions that perform specific CQL requests?

File: db/schema_tables.cc (hunk 1 above)
Comment (nyh) [reply db/schema_tables.cc:2716]: Maybe, I'll take a look how to do that in the least ugly way. Although the duplicates are just a few lines from each other so it's hard to make a mistake.

File: test/topology_experimental_raft/test_mv_tablets.py (hunk 2 above)
Comment (nyh) [reply test/topology_experimental_raft/test_mv_tablets.py:38]: By the way, I just realized that this function didn't need to use the concept of "table_id" at all this complicated way to fetch it. If could just look for the given `table_name` and `keyspace_name` (but need to use `ALLOW FILTERING`, this becomes a whole-table scan of the tablets table). This would find both tables and view names.

(Another by the way: If you do use table_id like you do today, you don't need to also filter the keyspace when reading the tablets table - a table_id can't possibly belong to other keyspaces).

Comment (nyh) [reply test/topology_experimental_raft/test_mv_tablets.py:38]: I decided to stop using table_id at all (so in particular I won't need get_table_id()). I'll send that change as a followup patch which will also improve the Alternator LSI tests (to use 2 nodes instead of 10).

Comment (tgrabiec) [reply test/topology_experimental_raft/test_mv_tablets.py:38]: > In this case, as you guessed I tried to use get_table_id() but it wasn't good enough because it didn't search for views. You're right I could have improved get_table_id() but the question is - why. Why should the get_table_id() functionality exist in the "manager"? Why is it the job of the cluster manager to provide 100 different convenience functions that perform specific CQL requests?

Why extend get_table_id() - because new logic fits into its semantics. 

Why have get_table_id() - It's good to have common vocabulary for working with scylla, so that tests are easier to write, read and maintain. When I see get_table_id() I immediately know what is intended. When writing a test, I don't have to figure out the implementation on my own (column names?). It's also more robust against changes of the system.  For example, you added another implementation of get_tablet_replicas(). If we change the layout of system.tablets, we now have to update it in two places rather than one.

Why manager - it doesn't have to live in the manager, it could live somewhere else. It's common to all tests which work with scylla.

> (Another by the way: If you do use table_id like you do today, you don't need to also filter the keyspace when reading the tablets table - a table_id can't possibly belong to other keyspaces).

Keyspace name is part of primary key, so it had to be specififed.

Comment (nyh) [reply test/topology_experimental_raft/test_mv_tablets.py:38]: I changed the test - https://github.com/scylladb/scylladb/pull/16440/commits/a24c16333865937b68bc2409e34561762711d01f - to completely avoid a table_id

Basically you can just look up (with ALLOW FILTERING - this is a full table scan) given table_name and keyspace_name - no need to look up the table_id. Maybe the table_id is useful when there might be thousands of tables in the system but this doesn't happen in our test.

File: db/schema_tables.cc (hunk 1 above)
Comment (nyh) [reply db/schema_tables.cc:2716]: I'll do it with a lambda, and send a new version of this PR in a few minutes.

**Comment by nyh** [comment]
Pushed a new version with:
1. Rebased on new master, so now this PR only has the right patches - no unrelated stuff from other PRs.
2. Fixed review comments - reduced code duplication and dropped the function get_table_id (and it use) in a test.

Guys, please review.

**Comment by nyh** [comment]
Oops, the first patch is still garbage, I'll remove it and push again, sorry about the spam.

**Comment by nyh** [comment]
> #### 🔴 CI State: ABORTED

I don't know what this abort means. I also see that unrelated tests failed before the abort. I'll restart the CI and hope for the best.

**Comment by nyh** [comment]
@benipeled or @kostja or somebody, do you know what these "empty" xml files mean?

Anyway, the fact those are failing secondary index unit tests - and my patch modified secondary index, suggests something's wrong in my patch. I'll take a look at it.

**Comment by kostja** [comment]
An empty xml file means an exception or a failure to generate the file contents.

**Comment by nyh** [comment]
> An empty xml file means an exception or a failure to generate the file contents.

Exception or failure by whom and why?

Anyway, I can reproduce this failure locally, for example:

```
build/dev/test/boost/secondary_index_test --run_test=test_local_index_multi_pk_columns -- -c1 -m1G
```

crashes with a segfault. I'll debug it.

**Comment by nyh** [comment]
Pushed a new version with a new third patch, fixing cql_test_env to add the "tags" extension which we forgot - and will now be needed for the LSI tests because LSIs will get the synchronous_updates tag. This should fix the failure Boost tests that we saw in the previous version of this PR.

**Comment by nyh** [comment]
Good - after I fixed the cql_test_env bug, the CI now passes. Please review - and we'll have tablets fully working (almost, sort of) for materialized views, secondary index and also Alternator :-)

File: db/view/view.cc [hunk 3]
```diff
@@ -1609,10 +1609,13 @@ static future<> apply_to_remote_endpoints(service::storage_proxy& proxy, locator
         gms::inet_address target, inet_address_vector_topology_change&& pending_endpoints,
         frozen_mutation_and_schema&& mut, const dht::token& base_token, const dht::token& view_token,
         service::allow_hints allow_hints, tracing::trace_state_ptr tr_state) {
-
+    // The "delay_before_remote_view_update" injection point can be
+    // used to add a short delay (currently 0.5 seconds) before a base
+    // replica sends its update to the remove view replica.
+    co_await utils::get_local_injector().inject("delay_before_remote_view_update", 500ms);
```
Comment (kostja) [inline db/view/view.cc:1615]: remove -> remote

**Review by kostja — APPROVED** [review]

File: test/topology_experimental_raft/test_mv_tablets.py (hunk 2 above)
Comment (kostja) [reply test/topology_experimental_raft/test_mv_tablets.py:38]: I wonder if we want to follow up with the changelog note re this change. If you agree it's the case, please update @tzach

File: test/lib/cql_test_env.cc [hunk 4]
```diff
@@ -109,6 +109,7 @@ cql_test_config::cql_test_config(shared_ptr<db::config> cfg)
 
     db_config->add_cdc_extension();
     db_config->add_per_partition_rate_limit_extension();
+    db_config->add_tags_extension();
```
Comment (tgrabiec) [inline test/lib/cql_test_env.cc:112]: Why can't we add all extensions here, and call the same add_all_extensions() from main?

Preexisting problem, so not a blocker.

**Review by tgrabiec — APPROVED** [review]

File: db/view/view.cc (hunk 3 above)
Comment (nyh) [reply db/view/view.cc:1615]: I'll fix this in my followup PR, thanks.
