### PR TITLE
db: system_keyspace: use microsecond resolution for group0_history range tombstone

### LINKED ISSUE #13594: boost.Master Test Suite.release.test_group0_history_clearing_old_entries
```
[Exception] - critical check co_await get_history_size() == 1 has failed [2 != 1]
 == [File] - test/boost/group0_test.cc
 == [Line] -98
```

Seen in:
* https://jenkins.scylladb.com/job/scylla-master/job/next/5897/
* https://jenkins.scylladb.com/job/scylla-master/job/next/5899/

@kbr-scylla @kostja @gleb-cloudius

### PR DESCRIPTION
**Pull request by kbr-scylla**
in `make_group0_history_state_id_mutation`, when adding a new entry to
the group 0 history table, if the parameter `gc_older_than` is engaged,
we create a range tombstone in the mutation which deletes entries older
than the new one by `gc_older_than`. In particular if
`gc_older_than = 0`, we want to delete all older entries.

There was a subtle bug there: we were using millisecond resolution when
generating the tombstone, while the provided state IDs used microsecond
resolution. On a super fast machine it could happen that we managed to
perform two schema changes in a single millisecond; this happened
sometimes in `group0_test.test_group0_history_clearing_old_entries`
on our new CI/promotion machines, causing the test to fail because the
tombstone didn't clear the entry correspodning to the previous schema
change when performing the next schema change (since they happened in
the same millisecond).

Use microsecond resolution to fix that. The consecutive state IDs used
in group 0 mutations are guaranteed to be strictly monotonic at
microsecond resolution (see `generate_group0_state_id` in
service/raft/raft_group0_client.cc).

Fixes #13594

### CODE REVIEW

File: utils/UUID_gen.hh [hunk 1]
```diff
@@ -289,13 +289,18 @@ public:
      * <b>Warning:</b> this method should only be used for querying as this
      * doesn't at all guarantee the uniqueness of the resulting UUID.
      */
-    static UUID min_time_UUID(milliseconds timestamp = milliseconds{0})
+    template <std::intmax_t N, std::intmax_t D>
+    static UUID min_time_UUID(std::chrono::duration<int64_t, std::ratio<N, D>> timestamp)
```
Comment (avikivity) [inline utils/UUID_gen.hh:293]: It's enough to use decimicroseconds as the type here, if you pass milliseconds or microseconds it will get auto-converted (and if you pass a higher resolution type it will be rejected).

Note it's odd to pass a duration as a timestamp, the right type is a time_point, but that's a different matter.

**Comment by kbr-scylla** [comment]
v2: accept `decimicroseconds` instead of templatizing `min_time_UUID`

**Review by denesb — APPROVED** [review]

File: db/system_keyspace.cc [hunk 2]
```diff
@@ -3398,11 +3398,11 @@ mutation system_keyspace::make_group0_history_state_id_mutation(
...
 
-        auto ts_millis = duration_cast<milliseconds>(microseconds{ts});
-        auto gc_older_than_millis = duration_cast<milliseconds>(*gc_older_than);
-        assert(gc_older_than_millis < ts_millis);
+        auto ts_micros = microseconds{ts};
+        auto gc_older_than_micros = duration_cast<microseconds>(*gc_older_than);
+        assert(gc_older_than_micros < ts_micros);
 
-        auto tomb_upper_bound = utils::UUID_gen::min_time_UUID(ts_millis - gc_older_than_millis);
+        auto tomb_upper_bound = utils::UUID_gen::min_time_UUID(ts_micros - gc_older_than_micros);
```
Comment (tgrabiec) [inline db/system_keyspace.cc:3405]: I don't understand one thing. You say that:

> The consecutive state IDs used in group 0 mutations are guaranteed to be strictly monotonic at
microsecond resolution 

Then why is generate_group0_state_id() using get_random_time_UUID_from_micros() to generate timestamps:

```
    return utils::UUID_gen::get_random_time_UUID_from_micros(std::chrono::microseconds{ts});
```

If ts was guaranteed to be monotonic, why not use `min_time_UUID()` like here.

Comment (kbr-scylla) [reply db/system_keyspace.cc:3405]: Hm, thinking about it more -- I lied.
They will be strictly monotonic in this particular test/scenario - when there's one node sending the requests.
But in general two nodes performing a group 0 operation could pick the same timestamp, hence we need timeUUIDs to resolve the collision, so that checking for `group0_concurrent_modification` works correctly.
