### PR TITLE
config: add index_cache_fraction

### LINKED ISSUE #15118: Re-enable index cache by default, capped to some memory limit
Index caching was disabled by default because it caused performance regressions
for some small-partition workloads. See https://github.com/scylladb/scylladb/issues/11202.

However, it also means that there are workloads (i.e. large partition workloads) which could
benefit from the index cache, but (by default) don't.

As a compromise, we can set a default limit on the memory usage of index cache,
which should be small enough to avoid catastrophic regressions in
small-partition workloads, but big enough to accommodate workloads where
index cache is obviously beneficial.

### PR DESCRIPTION
**Pull request by michoecho**
Index caching was disabled by default because it caused performance regressions
for some small-partition workloads. See https://github.com/scylladb/scylladb/issues/11202.

However, it also means that there are workloads which could benefit from the
index cache, but (by default) don't.

As a compromise, we can set a default limit on the memory usage of index cache,
which should be small enough to avoid catastrophic regressions in
small-partition workloads, but big enough to accommodate workloads where
index cache is obviously beneficial.

This series adds such a configurable limit, sets it to to 0.2 of total cache memory by default,
and re-enables index caching by default.

Fixes #15118

### CODE REVIEW

**Comment by michoecho** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2946/

Huh, TIL that copy initialization doesn't consider explicit constructors.

**Comment by bhalevy** [comment]
@tgrabiec please review

File: db/config.cc [hunk 1]
```diff
@@ -1001,7 +1001,9 @@ db::config::config(std::shared_ptr<db::extensions> exts)
     , nodeops_watchdog_timeout_seconds(this, "nodeops_watchdog_timeout_seconds", liveness::LiveUpdate, value_status::Used, 120, "Time in seconds after which node operations abort when not hearing from the coordinator")
     , nodeops_heartbeat_interval_seconds(this, "nodeops_heartbeat_interval_seconds", liveness::LiveUpdate, value_status::Used, 10, "Period of heartbeat ticks in node operations")
     , cache_index_pages(this, "cache_index_pages", liveness::LiveUpdate, value_status::Used, false,
-        "Keep SSTable index pages in the global cache after a SSTable read. Expected to improve performance for workloads with big partitions, but may degrade performance for workloads with small partitions.")
+        "Keep SSTable index pages in the global cache after a SSTable read. Expected to improve performance for workloads with big partitions, but may degrade performance for workloads with small partitions. The amount of memory usable by index cache is limited with `index_cache_fraction`.")
+    , index_cache_fraction(this, "index_cache_fraction", liveness::LiveUpdate, value_status::Used, 1.0,
```
Comment (avikivity) [inline db/config.cc]: 0.2

File: row_cache.cc [hunk 2]
```diff
@@ -51,17 +52,34 @@ row_cache::create_underlying_reader(read_context& ctx, mutation_source& src, con
...
+// Currently we are relying on metrics for that.
+//
+// FIXME: relying on thread-local metrics for the algorithm is unclean.
+// It would be better to pass some accessor to these metrics as a parameter
+// to the tracker.
+namespace sstables {
+    size_t space_used_by_index_cache();
+}
+
+cache_tracker::cache_tracker(utils::updateable_value<double> index_cache_fraction, mutation_application_stats& app_stats, register_metrics with_metrics)
```
Comment (avikivity) [inline row_cache.cc:78]: How about passing some struct here that contains index_cache_fraction and an std::function to determine the space used by the index cache, then we avoid the dependency (which is likely circular).

File: row_cache.cc [hunk 3]
```diff
@@ -78,7 +96,35 @@ cache_tracker::cache_tracker(mutation_application_stats& app_stats, register_met
...
+            //    Setting it to a medium number (something like 0.2) should work well enough
+            //    for both extremes, although it might be suboptimal for non-extremes.
+            // 3. The parameter is trivially live-updateable.
+            //
+            // Perhaps this logic should be encapsulated somewhere else, maybe in `class lru` itself.
+            size_t total_cache_space = _region.occupancy().total_space();
+            size_t index_cache_space = sstables::space_used_by_index_cache();
+            bool should_evict_index = index_cache_space > total_cache_space * _index_cache_fraction.get();
+
+            return _lru.evict(should_evict_index);
```
Comment (avikivity) [inline row_cache.cc:127]: Might want to loop here to amortize the cost of the decision.

**Comment by avikivity** [comment]
Need a test.

File: row_cache.cc (hunk 3 above)
Comment (michoecho) [reply row_cache.cc:127]: The decision should be very cheap, amortizing it isn't worth the added complexity.

**Comment by michoecho** [comment]
> Need a test.

What kind of test do you want?

An integration test that spams the worst-case workload (a schema with only partition keys) and checks that the index cache stays at the defined limit?
A unit test for `lru`?
A unit test for `cache_tracker`?
All of the above?

I'm very bad at deciding what tests are worth writing. I wish we had some methodology which makes that decision for us.

File: sstables/sstables.cc [hunk 4]
```diff
@@ -2817,6 +2817,10 @@ thread_local cached_file::metrics index_page_cache_metrics;
 thread_local mc::cached_promoted_index::metrics promoted_index_cache_metrics;
 static thread_local seastar::metrics::metric_groups metrics;
 
+size_t space_used_by_index_cache() {
+    return partition_index_cache::shard_stats().used_bytes + index_page_cache_metrics.cached_bytes;
```
Comment (tgrabiec) [inline sstables/sstables.cc:2821]: Maybe a cleaner way to achieve that would be to have a notion of region zones. When you create caches, instead of passing `get_cache_tracker().region()` you would get `get_cache_tracker().get_index_zone()` which returns 

```
struct region_zone {
    region& r;
    allocator& alloc;
}
```

And alloc is a zone-specific wrapper around region allocator which accounts memory allocated through the zone, like the current `measuring_allocator`.


In caches, instead of:
```
with_allocator(_region.allocator(), [&] {
``` 

you'd do:
```
with_allocator(_zone.allocator(), [&] {
```

**Review by tgrabiec — APPROVED** [review]

**Comment by mykaul** [comment]
Please add an issue so we can have 'fixes' or 'refs' comment refer to it.

File: row_cache.cc (hunk 2 above)
Comment (avikivity) [reply row_cache.cc:78]: Yes, it's important to me not to reduce modularity.

File: row_cache.cc (hunk 3 above)
Comment (avikivity) [reply row_cache.cc:127]: It may be cheap but the gain from an eviction can be tiny, so we have a low-cost decision against a low-gain outcome.

Comment (michoecho) [reply row_cache.cc:127]: The thing is, I expect eviction of an item to be orders of magnitude more expensive than computing the conditional. The minimum cost of a single eviction is DRAM latency (it's an uncached linked list, after all), and usually it also entails unlinking stuff from trees, destroying cells, freeing memory, etc. Compared to that, computing the conditional should be rather insignificant — it's a few cacheable loads and a bit of arithmetic.

Comment (avikivity) [reply row_cache.cc:127]: Yes probably true re. the uncacheability and its dominance.

**Comment by mykaul** [comment]
@michoecho - there are some conflicts that need to be resolved (seem benign).

**Comment by michoecho** [comment]
> @michoecho - there are some conflicts that need to be resolved (seem benign).

I know. This PR wasn't just waiting on conflict resolution — it was waiting for me to fix the reliance on globals and to add tests.

File: row_cache.cc (hunk 2 above)
Comment (michoecho) [reply row_cache.cc:67]: Solved by moving the ownership of index cache metrics to cache_tracker.

**Comment by michoecho** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3384/

An accident during final rebase, fixed.

File: test/boost/cache_algorithm_test.cc [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+        auto insert_query = e.prepare("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)").get0();
+        auto select_query = e.prepare("SELECT * FROM t WHERE pk = ? AND ck = ?").get0();
+
+        constexpr uint64_t pk_number = 10;
+        constexpr uint64_t ck_number = 300;
+        constexpr uint64_t v_size = 100000;
+        // Sanity check. The test assumes that the total table size is significantly bigger than RAM.
+        BOOST_REQUIRE_GT(pk_number * ck_number * v_size, 2 * seastar::memory::stats().total_memory());
+
+        // A bijection between uint64_t and blobs of size pk_size.
```
Comment (tgrabiec) [inline test/boost/cache_algorithm_test.cc:117]: There's no pk_size here.

File: test/boost/cache_algorithm_test.cc [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+        auto make_key = [] (uint64_t x) {
+            bytes b(bytes::initialized_later(), sizeof(x));
+            auto i = b.begin();
+            write<uint64_t>(i, x);
+            return b;
+        };
+
+        // Populate the table.
+        auto pk = bytes(sizeof(uint64_t), 0);
```
Comment (tgrabiec) [inline test/boost/cache_algorithm_test.cc:126]: pk is unused?

**Review by tgrabiec — COMMENTED** [review]
LGTM, just some nits

File: test/boost/cache_algorithm_test.cc (hunk 6 above)
Comment (michoecho) [reply test/boost/cache_algorithm_test.cc:126]: Right, this line is leftover from an earlier iteration of the test.

File: test/boost/cache_algorithm_test.cc (hunk 5 above)
Comment (michoecho) [reply test/boost/cache_algorithm_test.cc:117]: Right, it should be `x`, not `pk_size`.

File: test/boost/cache_algorithm_test.cc [hunk 7]
```diff
@@ -0,0 +1,152 @@
...
+        for (size_t i = 0; i < pk_number; ++i) {
+            e.execute_prepared(insert_query, {{cql3::raw_value::make_value(make_key(i))}}).get0();
+        }
+        // Flushing makes reasoning easier.
+        e.db().invoke_on_all(&replica::database::flush_all_memtables).get();
+
+
+        constexpr uint64_t hot_subset_size = 1000;
+        // Sanity check. The test assumes that the total *hot* index size is significantly bigger than RAM.
+        BOOST_REQUIRE_GT(hot_subset_size * pk_size * 2000, 2 * seastar::memory::stats().total_memory());
```
[the remark this answers is not in the document]
Comment (michoecho) [reply test/boost/cache_algorithm_test.cc:73]: 2000 is the `data file size : summary file size` ratio. Hence, in a table containing only primary keys, `pk_size * 2000` is approximately the size of an index page.

The sanity check here is that the maximum total size of the touched index pages is much greater than RAM. ("Maximum", because multiple rows can land in the same index page).

I'll add a comment which explains that.

**Comment by michoecho** [comment]
v3:
- Addressed @tgrabiec's comments
- Addressed the CI failure. It turns out that reads from `system_auth.roles` were generating unpredicted cache misses, breaking the sanity checks in the test. I dealt with that by effectively disabling CQL permission refreshes (by increasing their period to a giant value).
- Doubled the memory of the test and the size of the dataset. With 128 MiB I saw some spurious bad_allocs when running the test with a large repeat count.

**Comment by michoecho** [comment]
CI corrections:
- Added `#include <cstdint>` to the new headers, to make them self-sufficient.
- Disabled the new tests in debug mode, because debug mode ignores `--memory`. (And also the tests are relatively slow).

**Review by tgrabiec — APPROVED** [review]
