### PR TITLE
cache_algorithm_test: fix flaky failures

### LINKED ISSUE #21536: cache_algorithm_test.test_index_doesnt_flood_cache_in_small_partition_workload fails due to cache miss
```
[2024-11-11T10:36:36.517Z] Output of build/release/test/boost/cache_algorithm_test --run_test=test_index_doesnt_flood_cache_in_small_partition_workload --report_level=no --logger=HRF,test_suite:XML,test_suite,/scylladir/testlog/x86_64/release/xml/boost.cache_algorithm_test.test_index_doesnt_flood_cache_in_small_partition_workload.1.xunit.xml --catch_system_errors=no --color_output=false -- -c1 -m256M --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100:
[2024-11-11T10:36:36.519Z] === TEST.PY STARTING TEST boost.cache_algorithm_test.test_index_doesnt_flood_cache_in_small_partition_workload.1 ===
[2024-11-11T10:36:36.519Z] export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/scylla-ci/scylla/ubsan-suppressions.supp'
[2024-11-11T10:36:36.520Z] export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
[2024-11-11T10:36:36.520Z] build/release/test/boost/cache_algorithm_test --run_test=test_index_doesnt_flood_cache_in_small_partition_workload --report_level=no --logger=HRF,test_suite:XML,test_suite,/scylladir/testlog/x86_64/release/xml/boost.cache_algorithm_test.test_index_doesnt_flood_cache_in_small_partition_workload.1.xunit.xml --catch_system_errors=no --color_output=false -- -c1 -m256M --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100
[2024-11-11T10:36:36.524Z] === TEST.PY TEST boost.cache_algorithm_test.test_index_doesnt_flood_cache_in_small_partition_workload.1 OUTPUT ===
[2024-11-11T10:36:36.525Z] Running 1 test case...
[2024-11-11T10:36:36.525Z] Entering test module "Master Test Suite"
[2024-11-11T10:36:36.525Z] test/boost/cache_algorithm_test.cc(46): Entering test case "test_index_doesnt_flood_cache_in_small_partition_workload"
[2024-11-11T10:36:36.526Z] INFO  2024-11-11 12:31:44,327 seastar - Reactor backend: linux-aio
[2024-11-11T10:36:36.526Z] INFO  2024-11-11 12:31:44,327 seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
[2024-11-11T10:36:36.527Z] random-seed=31234841
...
[2024-11-11T10:36:36.748Z] test/boost/cache_algorithm_test.cc(112): fatal error: in "test_index_doesnt_flood_cache_in_small_partition_workload": critical check get_misses() == misses_before has failed [1001 != 1000]
```

the failing test is located at https://github.com/scylladb/scylladb/blob/b158ca734603d62fa8e173a72e60866a4d8d3bc7/test/boost/cache_algorithm_test.cc#L112

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13096

### PR DESCRIPTION
**Pull request by michoecho**
This series attempts to get read of flakiness in `cache_algorithm_test` by solving two problems.

Problem 1:

The test needs to create some arbitrary partition keys of a given size. It intends to create keys of the form:
0x0000000000000000000000000000000000000000...
0x0100000000000000000000000000000000000000...
0x0200000000000000000000000000000000000000...
But instead, unintentionally, it creates partially initialized keys of the form: 0x0000000000000000garbagegarbagegarbagegar...
0x0100000000000000garbagegarbagegarbagegar...
0x0200000000000000garbagegarbagegarbagegar...

Each of these keys is created several times and -- for the test to pass -- the result must be the same each time.
By coincidence, this is usually the case, since the same allocator slots are used. But if some background task happens to overwrite the allocator slot during a preemption, the keys used during "SELECT" will be different than the keys used during "INSERT", and the test will fail due to extra cache misses.

Problem 2:

Cache stats are global, so there's no good way to reliably
verify that e.g. a given read causes 0 cache misses,
because something done by Scylla in a background can trigger a cache miss.

This can cause the test to fail spuriously.

With how the test framework and the cache are designed, there's probably
no good way to test this properly. It would require ensuring that cache
stats are per-read, or at least per-table, and that Scylla's background
activity doesn't cause enough memory pressure to evict the tested rows.

This patch tries to deal with the flakiness without deleting the test
altogether by letting it retry after a failure if it notices that it
can be explained by a read which wasn't done by the test.
(Though, if the test can't be written well, maybe it just shouldn't be written...)

Fixes #21536

Should be backported to prevent flaky failures in older branches.

### CODE REVIEW

File: test/boost/cache_algorithm_test.cc [hunk 1]
```diff
@@ -69,7 +69,7 @@ SEASTAR_TEST_CASE(test_index_doesnt_flood_cache_in_small_partition_workload) {
 
         // A bijection between uint64_t and blobs of size pk_size.
         auto make_key = [pk_size] (uint64_t x) {
-            bytes b(bytes::initialized_later(), std::max(pk_size, sizeof(x)));
+            bytes b(std::max(pk_size, sizeof(x)), '\0');
```
Comment (avikivity) [inline test/boost/cache_algorithm_test.cc:72]: I was going to blame the compiler, but seeing this...

**Review by avikivity — APPROVED** [review]

**Comment by michoecho** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13873/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13873/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/cache_algorithm_test
> #### Failed Tests (1/2):
> 
>     * [test_index_doesnt_flood_cache_in_small_partition_workload](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13873/testReport/junit/boost/cache_algorithm_test/test_index_doesnt_flood_cache_in_small_partition_workload) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_index_doesnt_flood_cache_in_small_partition_workload)
> 
> 
> #### Build Details:
> 
>     * Duration: 36 min
> 
>     * Builder: spider5.cloudius-systems.com

Ugh, seems it now hit the "expected" source of flakiness that I talked about in https://github.com/scylladb/scylla-enterprise/issues/4504, aka some unrelated background read adding an extra cache miss. (Because it failed the sanity check that a single-partition read results in at most single cache miss).

For now, I'll patch this by letting the test retry itself if it notices extra unexpected reads. I'll post an updated version shortly.

**Comment by michoecho** [comment]
v2: added a second commit which lets the test retry itself after a failure, if it notices in the stats that some reads during the test weren't done by the test.

**Comment by michoecho** [comment]
It's a inherently fragile test, in multiple ways. Maybe it just shouldn't exist. Or maybe it should be a manual test living under `tools/perf`.

**Review by bhalevy — APPROVED** [review]

**Comment by kbr-scylla** [comment]
@michoecho please address scylladbbot's request, we need to backport this, next-6.2 and next-6.1 are still suffering

**Comment by michoecho** [comment]
> @michoecho please address scylladbbot's request, we need to backport this, next-6.2 and next-6.1 are still suffering

I can't, because the invite expired. (I didn't see it at the time it came. Turns out it was sent to my private email, not my scylla email.)

I opened backport PRs manually instead:
https://github.com/scylladb/scylladb/pull/22227
https://github.com/scylladb/scylladb/pull/22228
