### PR TITLE
Fix edge case issues related to tablet draining 

### LINKED ISSUE #21826: Replace node operation with tablets failed in MultiDC config  with additional DC with zero node if all nodes in DC1 are dead
## Packages

Scylla version: `6.3.0~dev-20241127.5e391eee256e` with build-id `c02c118dea1797c1774413e9feb3ce06782b93b7`

Kernel Version: `6.8.0-1019-aws`

## Issue description

- [x] This issue is NOT  a regression.
- [ ] It is unknown if this issue is a regression.

Test: test: https://github.com/scylladb/scylla-cluster-tests/pull/9230/files#diff-252a6c42ed5bca9952c39ee5577c05be7cb077aa95712dd558e05ded86dbefc4
Cluster configured with 2 DCes with 3 nodes in each. 
Also configured keyspace `keyspace1` with rf DC1: 3 and DC2: 3
1. All nodes in DC1 was stopped(Simulate that dc is not available). 
2. Using raft api, checking that raft quorum is lost
3. Start all node in DC1 and check that cluster is up and normal (both DCes).
4. Adding new DC3 and 1 zero node to DC3.
5. All nodes in DC1 was stopped again.
6. Using raft api validate that raft quorum is present.
7. Remove 1 node from DC1 with nodetool removenode <node1-hostid> --ignore-dead-nodes <node2-hostid>,<node3-hostid>
8. Node1 was removed 
9.  start replace node2 with new node in DC1 with configured --ignore-dead-nodes <node3-hostid> in yaml
without tablets it is passed
with tables replace failed with error:
```
2024-11-28 09:31:53.227 <2024-11-28 09:31:53.163>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=b48e06fc-8eba-4b61-bba4-a4c5812a4edd: type=RUNTIME_ERROR regex=std::runtime_error line_number=20310 node=add-new-dc-feater-z-db-node-c0ea5846-4
2024-11-28T09:31:53.163+00:00 add-new-dc-feater-z-db-node-c0ea5846-4      !ERR | scylla[5314]:  [shard 0: gms] raft_topology - topology change coordinator fiber got error std::runtime_error (Unable to find new replica for tablet 6cc5e1d0-ad63-11ef-94db-ef97c8ca5339:1 on d102e14f-8e0b-45dc-b50c-e21deb641724:1 when draining {d102e14f-8e0b-45dc-b50c-e21deb641724, e9df9414-c7ea-47ac-acfe-18ce90c1b3da}. Consider adding new nodes or reducing replication factor. (nodes [2d5fceb2-3def-468e-9d13-965ecd41e71e], replicas [d102e14f-8e0b-45dc-b50c-e21deb641724:1, 191d8af0-d78f-4616-95ec-f380be9ebf27:1, 2d5fceb2-3def-468e-9d13-965ecd41e71e:3, e4499c7d-dd13-4561-a86b-771ada7634a3:1, 6f4ea68b-8c36-431b-ae61-0ff2671ea465:1, 9de82f09-5d2a-4f84-9674-cbaed84e34d6:1]))
```
next steps are run without tablets sucessfully while with tabltes tests was aborted
10. replace third node
11. add new node to DC1

## Impact

Impossible to replace dead node in DC1 if all nodes in DC1 was die with tablets

## How frequently does it reproduce?

Always

## Installation details

Cluster size: 6 nodes (i4i.xlarge)

Scylla Nodes used in this run:
- add-new-dc-feater-z-db-node-c0ea5846-8 (3.254.101.40 | 10.4.1.142) (shards: 4)
- add-new-dc-feater-z-db-node-c0ea5846-7 (16.171.239.161 | 10.0.0.4) (shards: 4)
- add-new-dc-feater-z-db-node-c0ea5846-6 (35.179.113.121 | 10.3.3.250) (shards: -1)
- add-new-dc-feater-z-db-node-c0ea5846-5 (18.170.34.5 | 10.3.0.132) (shards: 4)
- add-new-dc-feater-z-db-node-c0ea5846-4 (18.169.172.62 | 10.3.0.130) (shards: 4)
- add-new-dc-feater-z-db-node-c0ea5846-3 (34.253.82.249 | 10.4.0.137) (shards: 4)
- add-new-dc-feater-z-db-node-c0ea5846-2 (52.19.114.181 | 10.4.0.48) (shards: 4)
- add-new-dc-feater-z-db-node-c0ea5846-1 (3.252.250.42 | 10.4.3.248) (shards: 4)

OS / Image: `ami-03fc5b24d01f87246 ami-0b21ed11932515c61 ami-0ca177d43cf95e4d7` (aws: undefined_region)

Test: `feature_test_multidc_add_zero_node_test`
Test id: `c0ea5846-93e5-44cc-81f5-16dd5ad30cce`
Test name: `scylla-staging/abykov/feature_test_multidc_add_zero_node_test`
Test method: `add_new_dc_test.TestAddNewDc.test_add_new_dc_with_zero_nodes`
Test config file(s):

- [add-new-dc-with-zero-nodes.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d2f283f4d44bdcb5ff539229d04cf1a10b27fc1e/test-cases/features/add-new-dc-with-zero-nodes.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c0ea5846-93e5-44cc-81f5-16dd5ad30cce`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c0ea5846-93e5-44cc-81f5-16dd5ad30cce)
- Show all stored logs command: `$ hydra investigate show-logs c0ea5846-93e5-44cc-81f5-16dd5ad30cce`

## Logs:
- **db-cluster-c0ea5846.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/db-cluster-c0ea5846.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/db-cluster-c0ea5846.tar.gz)
- **sct-runner-events-c0ea5846.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/sct-runner-events-c0ea5846.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/sct-runner-events-c0ea5846.tar.gz)
- **sct-c0ea5846.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/sct-c0ea5846.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/sct-c0ea5846.log.tar.gz)
- **loader-set-c0ea5846.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/loader-set-c0ea5846.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/loader-set-c0ea5846.tar.gz)
- **monitor-set-c0ea5846.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/monitor-set-c0ea5846.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/monitor-set-c0ea5846.tar.gz)
- **parallel-timelines-report-c0ea5846.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/parallel-timelines-report-c0ea5846.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c0ea5846-93e5-44cc-81f5-16dd5ad30cce/20241128_093701/parallel-timelines-report-c0ea5846.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/feature_test_multidc_add_zero_node_test/27/)
[Argus](https://argus.scylladb.com/test/5f74c11f-b4c0-4d22-98dd-75e72d0d09ba/runs?additionalRuns[]=c0ea5846-93e5-44cc-81f5-16dd5ad30cce)
</details>

### PR DESCRIPTION
**Pull request by tgrabiec**
Main problem:

If we're draining the last node in a DC, we won't have a chance to
evaluate candidates and notice that constraints cannot be satisfied (N
< RF). Draining will succeed and node will be removed with replicas
still present on that node. This will cause later draining in the same
DC to fail when we will have 2 replicas which need relocaiton for a
given tablet.

The expected behvior is for draining to fail, because we cannot keep
the RF in the DC. This is consistent, for example, with what happens
when removing a node in a 2-node cluster with RF=2.

Fixes #21826

Secondary problem:

We allowed tablet_draining transition to be exited with undrained nodes, leaving replicas on nodes in the "left" state.

Third problem: 

We removed DOWN nodes from the candidate node set, even when draining. This is not safe because it may lead to overload. This also makes the "main problem" more likely by extending it to the scenario when the DC is DOWN. 

The overload part in not a problem in practice currently, since migrations will block on global topology barrier if there are DOWN nodes.

### CODE REVIEW

File: service/topology_coordinator.cc [hunk 1]
```diff
@@ -1664,6 +1667,14 @@ class topology_coordinator : public endpoint_lifecycle_subscriber {
         }
 
         if (drain) {
+            if (has_nodes_to_drain) {
+                // Prevent jumping to write_both_read_old with un-drained tablets.
+                // This can happen when all candidate nodes are down.
+                rtlogger.warn("Tablet draining stalled: No tablets migrating but there are nodes to drain");
+                release_guard(std::move(guard));
+                co_await sleep(3s); // Throttle the above logging
```
Comment (bhalevy) [inline service/topology_coordinator.cc:1675]: If it's only about throttling the log message, why not use seastar::logger::rate_limit?

File: service/tablet_allocator.cc [hunk 2]
```diff
@@ -2443,15 +2443,27 @@ class load_balancer {
...
                     ensure_node(node.host_id());
                 }
             }
         });
 
+        // Apply skiplist only when not draining.
+        // It's unsafe to move tablets to non-skip nodes as this can lead to node overload.
+        if (nodes_to_drain.empty()) {
+            for (auto h : _skiplist) {
+                if (nodes.contains(h)) {
```
Comment (bhalevy) [inline service/tablet_allocator.cc:2459]: It'd be more efficient to use [extract](https://en.cppreference.com/w/cpp/container/unordered_map/extract) instead, since it will lookup the key once and allow you to access the node& before it's erased.

Comment (bhalevy) [reply service/tablet_allocator.cc:2459]: Otherwise LGTM

File: service/topology_coordinator.cc (hunk 1 above)
Comment (tgrabiec) [reply service/topology_coordinator.cc:1675]: Each cycle logs from many places, not just this one.

Comment (bhalevy) [reply service/topology_coordinator.cc:1675]: Why 3s? Can't that be too much, or too little in certain conditions?

File: service/tablet_allocator.cc (hunk 2 above)
Comment (tgrabiec) [reply service/tablet_allocator.cc:2459]: Ok.

File: service/topology_coordinator.cc (hunk 1 above)
Comment (tgrabiec) [reply service/topology_coordinator.cc:1675]: If we're here, it's unlikely the situation will resolve itself soon, because either we have a bug in the scheduler which will require manual intervention, or the nodes required to make progress went down, in which case bringing them up requires time scale larger than 3s.

There is no particular reason for 3s other than it being sufficiently large to not flood the logs excessively in the recovery time scale

**Comment by bhalevy** [comment]
@gleb-cloudius please review too
Cc @kbr-scylla

**Comment by tgrabiec** [comment]
In V1.1:
  - Use extract()
  - Adjust comment around sleep from "Throttle the above log line" to "Throttle retries" as to not suggest it's only about that particular log line but about the whole retry cycle.

**Review by bhalevy — APPROVED** [review]

**Comment by tgrabiec** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13845/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13845/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/tablets_test 🔹 topology_custom/test_tablets ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13439/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2310/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5428/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13845/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/109/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/707/)
> 
> #### Failed Tests (1/45564):
> * [test_database_with_data_in_sstables_is_a_mutation_source_plain_read_back_cg0](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13845/testReport/junit/boost/database_test/test_database_with_data_in_sstables_is_a_mutation_source_plain_read_back_cg0) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_database_with_data_in_sstables_is_a_mutation_source_plain_read_back_cg0)
> 
> #### Build Details:
> * Duration: 10 hr
> * Builder: spider2.cloudius-systems.com

https://github.com/scylladb/scylladb/issues/21968

**Comment by gleb-cloudius** [comment]
> If we're draining the last node in a DC

I do not understand this. In the issue linked we drained the first node in the DC and then tried to replace second node, so what do you mean by "last node" here?

**Comment by bhalevy** [comment]
> > If we're draining the last node in a DC
> 
> I do not understand this. In the issue linked we drained the first node in the DC and then tried to replace second node, so what do you mean by "last node" here?

ping @tgrabiec let's keep this rolling.

**Comment by tgrabiec** [comment]
> > If we're draining the last node in a DC
> 
> I do not understand this. In the issue linked we drained the first node in the DC and then tried to replace second node, so what do you mean by "last node" here?

In the issue we also hit the "Third problem" from the description. All nodes (3) are DOWN in the DC, so the scheduler sees only node being removed (drained) in the candidate node set. And we hit the same problematic path as when removing the last node.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider merging

File: service/topology_coordinator.cc [hunk 3]
```diff
@@ -1664,6 +1667,14 @@ class topology_coordinator : public endpoint_lifecycle_subscriber {
         }
 
         if (drain) {
+            if (has_nodes_to_drain) {
+                // Prevent jumping to write_both_read_old with un-drained tablets.
+                // This can happen when all candidate nodes are down.
+                rtlogger.warn("Tablet draining stalled: No tablets migrating but there are nodes to drain");
+                release_guard(std::move(guard));
+                co_await sleep(3s); // Throttle retries
```
Comment (denesb) [inline service/topology_coordinator.cc:1675]: This seems arbitrary amount, but I don't have a better suggestion.
