### PR TITLE
Purge old ip on change

### LINKED ISSUE #16691: Old records should be removed from PEERS table after node ip address was changed
*Installation details*
Scylla version (or git commit hash): 5.5.0~dev-0.20240105.7e84e03f5231 with build-id f21e4548b69223a75d01fd3bb9d4c9c2b1b71a6d
Cluster size: 3

Dtest `update_cluster_layout_tests.TestUpdateClusterLayout.test_change_node_ip` failed with error when experimental feature:`consistent-topology-changes` is enabled.
```
>           assert len(peers) == 2, f"There are more peers than expected.{peers}"
E           AssertionError: There are more peers than expected.[[UUID('e59eda2f-fffb-484c-b14b-8bb46e20ddc2'), '127.0.96.33'], [UUID('bf05eab8-e210-4d32-ba12-f95e1c168bf3'), '127.0.96.2'], [UUID('e59eda2f-fffb-484c-b14b-8bb46e20ddc2'), '127.0.96.3']]
E           assert 3 == 2
E            +  where 3 = len([[UUID('e59eda2f-fffb-484c-b14b-8bb46e20ddc2'), '127.0.96.33'], [UUID('bf05eab8-e210-4d32-ba12-f95e1c168bf3'), '127.0.96.2'], [UUID('e59eda2f-fffb-484c-b14b-8bb46e20ddc2'), '127.0.96.3']])

update_cluster_layout_tests.py:2256: AssertionError

```
this happened, because PEER table on node1 and node2 contains records with old and new ip for same host_id for node3, after node3 was started with new ip address.

run dtest:
`pytest --log-cli-level debug --keep-test-dir --scylla-version=unstable/master:latest --experimental-features=consistent-topology-changes  update_cluster_layout_tests.py::TestUpdateClusterLayout::test_change_node_ip`

test debug logs:
```
17:21:56,812 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2297 | Change IP address for node3
17:21:56,836 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2302 | Start node3 again with ip address 127.0.54.33
17:21:56,840 ccm             DEBUG cluster.py     :754  | node3: Starting scylla: args=['/home/abykov/.dtest/dtest-5k72mpz9/test/node3/bin/scylla', '--options-file', '/home/abykov/.dtest/dtest-5k72mpz9/test/node3/conf/scylla.yaml', '--log-to-stdout', '1', '--api-address', '127.0.54.33', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--overprovisioned', '--prometheus-address', '127.0.54.33', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=False wait_for_binary_proto=True
17:21:57,120 cassandra.pool  WARNING thread.py      :58   | Error attempting to reconnect to 127.0.54.3:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.54.3', 9042)]. Last error: Connection refused
17:21:57,180 ccm             DEBUG cluster.py     :754  | node3: Starting scylla-jmx: args=['/home/abykov/.dtest/dtest-5k72mpz9/test/node3/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.54.33', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.54.33', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.54.33', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/home/abykov/.dtest/dtest-5k72mpz9/test/node3/bin/scylla-jmx-1.0.jar']
17:21:57,532 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2305 | Node3 is now up
17:21:57,533 urllib3.connectionpool DEBUG connectionpool.py:246  | Starting new HTTP connection (1): 127.0.54.33:10000
17:21:57,534 urllib3.connectionpool DEBUG connectionpool.py:474  | http://127.0.54.33:10000 "GET /storage_service/hostid/local HTTP/1.1" 200 38
17:21:57,535 ccm             DEBUG cluster.py     :754  | node1: nodetool cmd=status  wait=True timeout=None
17:21:58,639 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2310 | nodetool status from node1: {'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.54.1', 'load': '211.84 KB', 'tokens': '256', 'owns': '?', 'host id': '35b7d7b0-f8be-49f2-a257-bf36b7749992', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.2', 'load': '448.37 KB', 'tokens': '256', 'owns': '?', 'host id': 'ac138eb5-8b27-430a-b67a-1008fa61876a', 'rack': 'rack1'}, {'status': 'DN', 'address': '127.0.54.3', 'load': '480.51 KB', 'tokens': '256', 'owns': '?', 'host id': 'ee1ade88-3304-4366-a83e-f15e2e3db31f', 'rack': 'rack1'}]}
17:21:58,641 ccm             DEBUG cluster.py     :754  | node2: nodetool cmd=status  wait=True timeout=None
17:21:59,866 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2310 | nodetool status from node2: {'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.54.33', 'load': '?', 'tokens': '256', 'owns': '?', 'host id': 'ee1ade88-3304-4366-a83e-f15e2e3db31f', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.1', 'load': '?', 'tokens': '256', 'owns': '?', 'host id': '35b7d7b0-f8be-49f2-a257-bf36b7749992', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.2', 'load': '448.37 KB', 'tokens': '256', 'owns': '?', 'host id': 'ac138eb5-8b27-430a-b67a-1008fa61876a', 'rack': 'rack1'}]}
17:21:59,867 ccm             DEBUG cluster.py     :754  | node3: nodetool cmd=status  wait=True timeout=None
17:22:01,019 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2310 | nodetool status from node3: {'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.54.1', 'load': '211.84 KB', 'tokens': '256', 'owns': '?', 'host id': '35b7d7b0-f8be-49f2-a257-bf36b7749992', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.2', 'load': '448.37 KB', 'tokens': '256', 'owns': '?', 'host id': 'ac138eb5-8b27-430a-b67a-1008fa61876a', 'rack': 'rack1'}, {'status': 'DN', 'address': '127.0.54.3', 'load': '480.51 KB', 'tokens': '256', 'owns': '?', 'host id': 'ee1ade88-3304-4366-a83e-f15e2e3db31f', 'rack': 'rack1'}]}
17:22:01,020 ccm             DEBUG cluster.py     :754  | node1: nodetool cmd=status  wait=True timeout=None
17:22:01,126 cassandra.pool  WARNING thread.py      :58   | Error attempting to reconnect to 127.0.54.3:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.54.3', 9042)]. Last error: Connection refused
17:22:02,032 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2249 | nodetool status from node1: {'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.54.33', 'load': '1.47 MB', 'tokens': '256', 'owns': '?', 'host id': 'ee1ade88-3304-4366-a83e-f15e2e3db31f', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.1', 'load': '211.84 KB', 'tokens': '256', 'owns': '?', 'host id': '35b7d7b0-f8be-49f2-a257-bf36b7749992', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.2', 'load': '448.37 KB', 'tokens': '256', 'owns': '?', 'host id': 'ac138eb5-8b27-430a-b67a-1008fa61876a', 'rack': 'rack1'}]}
17:22:02,037 cassandra.cluster INFO  dtest_setup.py :437  | New Cassandra host <Host: 127.0.54.3:9042 datacenter1> discovered
17:22:02,037 cassandra.cluster WARNING dtest_setup.py :437  | Found multiple hosts with the same host_id (ee1ade88-3304-4366-a83e-f15e2e3db31f). Excluding peer 127.0.54.33
17:22:02,037 cassandra.cluster INFO  dtest_setup.py :437  | New Cassandra host <Host: 127.0.54.2:9042 datacenter1> discovered
17:22:02,052 update_cluster_layout_tests INFO  update_cluster_layout_tests.py:2252 | PEERS: [[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2']]
17:22:02,053 update_cluster_layout_tests INFO  update_cluster_layout_tests.py:2254 | LOCAL: [[UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1']]
17:22:02,053 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2258 | Check peer table for node1 with ip address 127.0.54.1 : peers=[[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2']] 
17:22:02,054 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2259 | Check peer table for node1 with ip address 127.0.54.1 : local=[[UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1']] 
17:22:02,054 ccm             DEBUG cluster.py     :754  | node2: nodetool cmd=status  wait=True timeout=None
17:22:03,069 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2249 | nodetool status from node2: {'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.54.33', 'load': '1.47 MB', 'tokens': '256', 'owns': '?', 'host id': 'ee1ade88-3304-4366-a83e-f15e2e3db31f', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.1', 'load': '?', 'tokens': '256', 'owns': '?', 'host id': '35b7d7b0-f8be-49f2-a257-bf36b7749992', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.2', 'load': '448.37 KB', 'tokens': '256', 'owns': '?', 'host id': 'ac138eb5-8b27-430a-b67a-1008fa61876a', 'rack': 'rack1'}]}
17:22:03,073 cassandra.cluster INFO  dtest_setup.py :437  | New Cassandra host <Host: 127.0.54.3:9042 datacenter1> discovered
17:22:03,074 cassandra.cluster WARNING dtest_setup.py :437  | Found multiple hosts with the same host_id (ee1ade88-3304-4366-a83e-f15e2e3db31f). Excluding peer 127.0.54.33
17:22:03,074 cassandra.cluster INFO  dtest_setup.py :437  | New Cassandra host <Host: 127.0.54.1:9042 datacenter1> discovered
17:22:03,093 update_cluster_layout_tests INFO  update_cluster_layout_tests.py:2252 | PEERS: [[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33'], [UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1']]
17:22:03,094 update_cluster_layout_tests INFO  update_cluster_layout_tests.py:2254 | LOCAL: [[UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2']]
17:22:03,095 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2258 | Check peer table for node2 with ip address 127.0.54.2 : peers=[[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33'], [UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1']] 
17:22:03,095 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2259 | Check peer table for node2 with ip address 127.0.54.2 : local=[[UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2']] 
17:22:03,096 ccm             DEBUG cluster.py     :754  | node3: nodetool cmd=status  wait=True timeout=None
17:22:03,984 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2249 | nodetool status from node3: {'Datacenter': 'datacenter1', 'nodes': [{'status': 'UN', 'address': '127.0.54.1', 'load': '211.84 KB', 'tokens': '256', 'owns': '?', 'host id': '35b7d7b0-f8be-49f2-a257-bf36b7749992', 'rack': 'rack1'}, {'status': 'UN', 'address': '127.0.54.2', 'load': '448.37 KB', 'tokens': '256', 'owns': '?', 'host id': 'ac138eb5-8b27-430a-b67a-1008fa61876a', 'rack': 'rack1'}, {'status': 'DN', 'address': '127.0.54.3', 'load': '480.51 KB', 'tokens': '256', 'owns': '?', 'host id': 'ee1ade88-3304-4366-a83e-f15e2e3db31f', 'rack': 'rack1'}]}
17:22:03,988 cassandra.cluster WARNING dtest_setup.py :437  | Found multiple hosts with the same host_id (ee1ade88-3304-4366-a83e-f15e2e3db31f). Excluding peer 127.0.54.3
17:22:03,988 cassandra.cluster INFO  dtest_setup.py :437  | New Cassandra host <Host: 127.0.54.2:9042 datacenter1> discovered
17:22:03,989 cassandra.cluster INFO  dtest_setup.py :437  | New Cassandra host <Host: 127.0.54.1:9042 datacenter1> discovered
17:22:04,004 update_cluster_layout_tests INFO  update_cluster_layout_tests.py:2252 | PEERS: [[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2'], [UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1']]
17:22:04,006 update_cluster_layout_tests INFO  update_cluster_layout_tests.py:2254 | LOCAL: [[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33']]
17:22:04,006 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2258 | Check peer table for node3 with ip address 127.0.54.33 : peers=[[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2'], [UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1']] 
17:22:04,006 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2259 | Check peer table for node3 with ip address 127.0.54.33 : local=[[UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33']] 
17:22:04,007 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2262 | peers_and_local=["[[UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33']]", "[[UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33']]", "[[UUID('35b7d7b0-f8be-49f2-a257-bf36b7749992'), '127.0.54.1'], [UUID('ac138eb5-8b27-430a-b67a-1008fa61876a'), '127.0.54.2'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.3'], [UUID('ee1ade88-3304-4366-a83e-f15e2e3db31f'), '127.0.54.33']]"]
```

The issue should be fixed by: https://github.com/scylladb/scylladb/pull/16639

### LINKED ISSUE #16886: raft topology: IP address change, old IP isn't removed from system.peers and gossiper
In the gossiper mode this is handled by `handled_state_normal` - it removes IPs not referenced by token ring. In raft topology mode `handled_state_normal` is disabled and there is no other equivalent logic.

We should pass the `prev_ip` to `sync_raft_topology_nodes` and teach it to remove it after it inserts a new ip. When we load the mappings we should select the one with biggest timestamp and drop the old one in case scylla crashes before removing the old ip.

### LINKED ISSUE #17199: node decommission after ip was changed failed with coredump
Scylla version: 5.5.0~dev-0.20240206.c0c291b98536 with build-id ee177ddf9e48dacd755092d72e31345d862d2dd4

Dtest test: update_cluster_layout_tests.py::TestUpdateClusterLayout::test_decommission_after_changing_node_ip failed with coredump
when decommission running after node ip was changed:

node3 log:
```
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 764 out of 771 ranges, keyspace=system_auth, table=roles, range=(8826502176223842170,8832981112075931112], peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 765 out of 771 ranges, keyspace=system_auth, table=roles, range=(8934413887161157517,8970326380471345034], peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 766 out of 771 ranges, keyspace=system_auth, table=roles, range=(8970326380471345034,8991430120829323550], peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 767 out of 771 ranges, keyspace=system_auth, table=roles, range=(9059037876124851436,9124859997678578092], peers={127.0.20.1}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 768 out of 771 ranges, keyspace=system_auth, table=roles, range=(9170544693948247578,9175350817142350904], peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 769 out of 771 ranges, keyspace=system_auth, table=roles, range=(9175350817142350904,9178566980393479419], peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 770 out of 771 ranges, keyspace=system_auth, table=roles, range=(9201749406700076451,9212792264202661214], peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: Repair 771 out of 771 ranges, keyspace=system_auth, table=roles, range=(9212792264202661214,+inf), peers={127.0.20.2}, live_peers={}, status=skipped_no_live_peers
INFO  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: stats: repair_reason=decommission, keyspace=system_auth, tables={role_attributes, role_members, roles}, ranges_nr=257, round_nr=0, round_nr_fast_path_already_synced=0, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=0, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.009666039 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={}, row_from_disk_nr={}, row_from_disk_bytes_per_sec={} MiB/s, row_from_disk_rows_per_sec={} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
WARN  2024-02-07 09:00:55,238 [shard 1:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown
WARN  2024-02-07 09:00:55,238 [shard 0:strm] repair - repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: sync data for keyspace=system_auth, status=failed: std::runtime_error ({shard 0: std::runtime_error (repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown), shard 1: std::runtime_error (repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown)})
ERROR 2024-02-07 09:00:55,238 [shard 0: gms] raft_topology - raft_topology_cmd failed with: std::runtime_error ({shard 0: std::runtime_error (repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown), shard 1: std::runtime_error (repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown)})
ERROR 2024-02-07 09:00:55,266 [shard 0:strm] raft_topology - Decommission failed. See earlier errors (Rolled back: Failed stream ranges: std::runtime_error (failed status returned from f981b466-38c0-46ef-b847-f3535ea42b3b/127.0.20.33))
INFO  2024-02-07 09:00:55,663 [shard 0: gms] gossip - Node 127.0.20.2 has restarted, now UP, status = NORMAL
INFO  2024-02-07 09:00:55,663 [shard 0: gms] gossip - Node 127.0.20.1 has restarted, now UP, status = NORMAL
WARN  2024-02-07 09:00:55,664 [shard 0: gms] gossip - Fail to send EchoMessage to 127.0.20.3: seastar::rpc::closed_error (connection is closed)
INFO  2024-02-07 09:00:55,664 [shard 0: gms] gossip - InetAddress 127.0.20.3 is now DOWN, status = shutdown
INFO  2024-02-07 09:00:55,665 [shard 0: gms] gossip - InetAddress 127.0.20.2 is now UP, status = NORMAL
INFO  2024-02-07 09:00:55,665 [shard 0: gms] gossip - InetAddress 127.0.20.1 is now UP, status = NORMAL
INFO  2024-02-07 09:00:56,348 [shard 0:strm] api - decommission
INFO  2024-02-07 09:00:56,349 [shard 0:strm] raft_topology - request decommission for: f981b466-38c0-46ef-b847-f3535ea42b3b
INFO  2024-02-07 09:00:56,463 [shard 0:strm] raft_topology - retry streaming after previous attempt failed with std::runtime_error ({shard 0: std::runtime_error (repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown), shard 1: std::runtime_error (repair[fa0d2250-d53f-48fd-83d8-1b25d4d23132]: 771 out of 771 ranges failed, keyspace=system_auth, tables={role_attributes, role_members, roles}, repair_reason=decommission, nodes_down_during_repair={127.0.20.1, 127.0.20.2}, aborted_by_user=false, failed_because=unknown)})
INFO  2024-02-07 09:00:56,463 [shard 0:strm] storage_service - Started batchlog replay for decommission
INFO  2024-02-07 09:00:56,464 [shard 0:strm] storage_service - Finished batchlog replay for decommission
INFO  2024-02-07 09:00:56,464 [shard 0:strm] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={decommission ,bootstrap ,rebuild ,removenode ,replace}
ERROR 2024-02-07 09:00:56,464 [shard 0:strm] token_metadata - host_id for endpoint 127.0.20.33 is not found, at: 0x622024e 0x6220860 0x6220b48 0x5cdc2e7 0x3f73cea 0x43d0038 0x43cfe95 0x60fae76
Aborting on shard 0.
Backtrace:
  0x5d0abe8
  0x5d41291
  /jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.ccm/scylla-repository/c0c291b9853623d569c5f860216a8bb3cd671c5d/libreloc/libc.so.6+0x3dbaf
  /jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.ccm/scylla-repository/c0c291b9853623d569c5f860216a8bb3cd671c5d/libreloc/libc.so.6+0x8e883
  /jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.ccm/scylla-repository/c0c291b9853623d569c5f860216a8bb3cd671c5d/libreloc/libc.so.6+0x3dafd
  /jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.ccm/scylla-repository/c0c291b9853623d569c5f860216a8bb3cd671c5d/libreloc/libc.so.6+0x2687e
  0x5cdc367
  0x3f73cea
  0x43d0038
  0x43cfe95
  0x60fae76
```

log files and coredumpt could be found here:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/36/
[core file link](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/36/artifact/logs-full.release.000/1707296578003_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_decommission_after_changing_node_ip/node3-scylla.1293.1707296456.core.gz)

### PR DESCRIPTION
**Pull request by gusev-p**
When a node changes IP address we need to remove its old IP from `system.peers` and gossiper.

We do this in `sync_raft_topology_nodes` when the new IP is saved into `system.peers` to avoid losing the mapping if the node crashes between deleting and saving the new IP. We also handle the possible duplicates in this case by dropping them on the read path when the node is restarted.

The PR also fixes the problem with old IPs getting resurrected when a node changes its IP address.
The following scenario is possible: a node `A` changes its IP from `ip1` to `ip2` with restart, other nodes are not yet aware of `ip2` so they keep gossiping `ip1`. After restart `A` receives `ip1` in a gossip message and calls `handle_major_state_change` since it considers it as a new node. Then `on_join` event is called on the gossiper notification handlers, we receive such event in `raft_ip_address_updater` and reverts the IP of the node A back to ip1.

To fix this we ensure that the new gossiper generation number is used when a node registers its IP address in `raft_address_map` at startup.

The `test_change_ip` is adjusted to ensure that the old IPs are properly removed in all cases, even if the node crashes.

Fixes #16886
Fixes #16691
Fixes #17199

### CODE REVIEW

**Comment by gusev-p** [comment]
new version:
  * turn off the parts of `test_change_two` that rely on error injection in release mode.

[changes](https://github.com/scylladb/scylladb/compare/f733b97454adc2589cbe23cf43257ac3a198ea69..b20b66fe92893de05941b194d3f69ff31bc3822a)

File: service/storage_service.cc [hunk 1]
```diff
@@ -345,7 +345,10 @@ static locator::node::state to_topology_node_state(node_state ns) {
 
 // Synchronizes the local node state (token_metadata, system.peers/system.local tables,
 // gossiper) to align it with the other raft topology nodes.
-future<> storage_service::sync_raft_topology_nodes(mutable_token_metadata_ptr tmptr, std::optional<locator::host_id> target_node, std::unordered_set<raft::server_id> prev_normal) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:348]: re commit message / cover letter: you mean `system.peers`

File: service/storage_service.cc [hunk 2]
```diff
@@ -683,23 +683,23 @@ class storage_service::raft_ip_address_updater: public gms::i_endpoint_state_cha
     storage_service& _ss;
 
     future<>
-    on_endpoint_change(gms::inet_address endpoint, gms::endpoint_state_ptr ep_state) {
+    on_endpoint_change(gms::inet_address endpoint, gms::endpoint_state_ptr ep_state, const char* ev) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:691]: Why the abbreviation though. How about `event_name`?

File: db/system_keyspace.cc [hunk 3]
```diff
@@ -1464,19 +1464,17 @@ struct local_cache {
...
 
     std::unordered_map<gms::inet_address, locator::endpoint_dc_rack> ret;
     for (const auto& row : *msg) {
-        net::inet_address peer = row.template get_as<net::inet_address>("peer");
         if (!row.has("data_center") || !row.has("rack")) {
             continue;
         }
-        gms::inet_address gms_addr(std::move(peer));
-        sstring dc = row.template get_as<sstring>("data_center");
-        sstring rack = row.template get_as<sstring>("rack");
```
Comment (kbr-scylla) [inline db/system_keyspace.cc:1477]: Some people would argue that introducing such variables makes the code more readable. I don't have a strong opinion, but it's preferred to avoid such subjective stylistic changes. (I won't oppose this change.)

(The coroutinization below is definitely desired though.)

File: db/system_keyspace.cc [hunk 4]
```diff
@@ -1463,7 +1463,47 @@ struct local_cache {
     system_keyspace::bootstrap_state _state;
 };
```
Comment (kbr-scylla) [inline db/system_keyspace.cc:1464]: > The new function also removes the records with no host_id, so we no longer need the get_host_id function.

I'm not sure we want to do that. It could mask a bug -- such records should never appear in the first place.

File: db/system_keyspace.hh [hunk 5]
```diff
@@ -128,6 +128,7 @@ class system_keyspace : public seastar::peering_sharded_service<system_keyspace>
     static schema_ptr large_cells();
     static schema_ptr scylla_local();
     future<> force_blocking_flush(sstring cfname);
+    future<> ensure_peers_table_fixup();
```
Comment (kbr-scylla) [inline db/system_keyspace.hh:131]: Name is vague. I suggest to either use a more descriptive name (`remove_old_ips_from_peers_table`? but it doesn't cover the host ID part -- which I'm not a fan of though, comment above) or a comment (preferably both)

Comment (gusev-p) [reply db/system_keyspace.hh]: renamed the functions, added a comment

File: service/storage_service.cc (hunk 1 above)
Comment (gusev-p) [reply service/storage_service.cc:348]: fixed

**Comment by gusev-p** [comment]
new version:
  * renamed `ensure_peers_table_fixup -> peers_table_read_fixup`, added a comment

File: db/system_keyspace.cc (hunk 4 above)
Comment (gusev-p) [reply db/system_keyspace.cc:1464]: > Could also be that gossiper was missing HOST ID application state due to a bug (and then we persisted such entry in system.peers) -- and recently we're seeing errors for missing HOST ID, I think they only appear for removed nodes, but it's still unclear why, I believe they should never appear, a node either should have host id attached or not appear at all.

We can check if `host_id` is empty in `system_keyspace::update_peer_info` and trigger `on_internal_error` if it is. I don't know why we don't have such check yet.

My argument was that both of these inconsistencies can occur not only due to node crashes but also due to bugs, so why handle them differently then.

Comment (kbr-scylla) [reply db/system_keyspace.cc:1464]: > We can check if host_id is empty in system_keyspace::update_peer_info and trigger on_internal_error if it is. I don't know why we don't have such check yet.

Makes sense. @bhalevy please also give your opinion as you were modifying this code recently and probably thought about the problem too

Comment (bhalevy) [reply db/system_keyspace.cc:1464]: It was supposed to be covered in https://github.com/scylladb/scylladb/pull/16376.
There could be use cases to update other fields in system.peers (well the host_id should never change - it really should be the partition key).  So we can require it in `update_peer_info` and do read before write to make sure it's only set once, and in all other cases we can verify it matches the one given by the caller.

Comment (kbr-scylla) [reply db/system_keyspace.cc:1464]: > well the host_id should never change - it really should be the partition key

It does change -- replace-with-same-IP

Comment (bhalevy) [reply db/system_keyspace.cc:1464]: Yeah, well, it's not the same node anymore.
It's a replacing node that assumes ownership of the same tokens.
But I agree that makes the verification method I suggest impractical, unless we care to delete the previous record (a-la removenode) prior to inserting of the new one.

Comment (gusev-p) [reply db/system_keyspace.cc:1464]: added the check to `system_keyspace::update_peer_info` that `host_id` and `inet_address` are set.

**Comment by gusev-p** [comment]
new version:
  * rebased on master
  * added the check that host_id and inet_address are set in `system_keyspace::update_peer_info`
  * fixed a bug in `storage_service::on_change` - [we should grab the host_id from the gossiper](https://github.com/scylladb/scylladb/pull/17162/commits/fdc76d3b0a6fce8085dbb84c1f65d5a0a0971175), not from the set of changed app states.

**Comment by kbr-scylla** [comment]
@gusev-p please verify whether this
https://github.com/scylladb/scylladb/issues/16691
is fixed by this PR

**Comment by gusev-p** [comment]
new version:
  * added `fixes scylladb/scylladb#16691` to the commit message

File: db/system_keyspace.cc [hunk 6]
```diff
@@ -1463,7 +1463,47 @@ struct local_cache {
...
 
+future<> system_keyspace::peers_table_read_fixup() {
+    static bool done = false;
```
Comment (kbr-scylla) [inline db/system_keyspace.cc:1467]: `thread_local` or (better) we should assert that this is called on shard 0 only.

File: db/system_keyspace.cc [hunk 7]
```diff
@@ -1463,7 +1463,47 @@ struct local_cache {
...
+    }
+    done = true;
+
+    const auto cql = format("SELECT peer, host_id, WRITETIME(host_id) as ts from system.{}", PEERS);
+    std::unordered_map<utils::UUID, std::pair<net::inet_address, int64_t>> map{};
+    const auto cql_result = co_await execute_cql(cql);
+    for (const auto& row : *cql_result) {
+        const auto peer = row.get_as<net::inet_address>("peer");
+        if (!row.has("host_id")) {
+            slogger.warn("Peer {} has no host_id in system.{}, the record is broken, removing it",
```
Comment (kbr-scylla) [inline db/system_keyspace.cc:1479]: I'll merge, but this should be reported as an ERROR -- it most likely indicates a bug.
Please send a follow-up to address this

File: test/topology/test_change_ip.py [hunk 8]
```diff
@@ -11,47 +11,69 @@
...
+    if mode != 'release':
+        await manager.api.enable_injection(servers[0].ip_addr, 'crash-before-prev-ip-removed', one_shot=True)
     await manager.server_start(s_1)
+    if mode != 'release':
+        s0_logs = await manager.server_open_log(s_0)
+        await s0_logs.wait_for('crash-before-prev-ip-removed hit, killing the node')
+        await manager.server_stop(s_0)
+        await manager.server_start(s_0)
+    host0 = (await wait_for_cql_and_get_hosts(cql, [servers[0]], time.time() + 60))[0]
+    await wait_for_peers(host0, {s1_new_ip, s2_old_ip})
```
Comment (kbr-scylla) [inline test/topology/test_change_ip.py:64]: Previously (the inlined version of) `wait_for_peers` was called after reconnecting driver, which served as a workaround for https://github.com/scylladb/python-driver/issues/295 among other things.

Now you're calling it after a server restarts + wait_for_cql_and_get_hosts --- so the test might now likely hit https://github.com/scylladb/python-driver/issues/295, making it flaky.

I'll merge, the flakiness should be rare, but please send a follow-up to address this (we need a driver reconnect after server restart before doing queries)

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Unfortunately, there's a conflict with current `next`

File: test/topology/test_change_ip.py (hunk 8 above)
Comment (gusev-p) [reply test/topology/test_change_ip.py:64]: done

File: db/system_keyspace.cc (hunk 7 above)
Comment (gusev-p) [reply db/system_keyspace.cc:1479]: done for both problems - missing `host_id` and duplicate `IP`-s.

File: db/system_keyspace.cc (hunk 6 above)
Comment (gusev-p) [reply db/system_keyspace.cc:1467]: done

**Comment by gusev-p** [comment]
new version:
  * rebased on master;
  * fixed the review comments;
  * [two](https://github.com/scylladb/scylladb/pull/17162/commits/7559010441f72c1d84dc2909119d95ef26935507) [commits](https://github.com/scylladb/scylladb/pull/17162/commits/29346ab7b1b3629b43aced0b4a696444c37a40d8) were added to fix https://github.com/scylladb/scylladb/issues/17199;
  * `test_change_ip` refactored - added more checks for the problems fixed.

@kbr-scylla

**Comment by kbr-scylla** [comment]
I don't like it that the scope of the PR suddenly increased, it puts large overhead on the reviewers to understand what changed and what didn't from the previous version, incremental development is easier. Basically a second PR was added to the original one...

**Comment by kbr-scylla** [comment]
The cover letter is exactly the same as before, which makes things even more confusing.

File: main.cc [hunk 9]
```diff
@@ -1793,8 +1793,10 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
             // Set up group0 service earlier since it is needed by group0 setup just below
             ss.local().set_group0(group0_service, raft_topology_change_enabled);
```
Comment (kbr-scylla) [inline main.cc:1794]: > Also we remove the load_initial_raft_address_map function from raft_group0 as it seems redundant. When start_server_for_group0 is called from setup_group0_if_exist gossiper is not initialized yet, so this call has no effect.

But `start_server_for_group0` is also called from the other `setup_group0` -> `join_group0`, that's where it call is needed i.e. when we join the cluster. Not when we restart.

"seems redundant" is not a good enough reason to remove something, there was a reason it was added. The reason is that we might miss all gossiper notifications about endpoints that are delivered by gossiper before we subscribe to it.

File: service/raft/raft_group0.cc [hunk 10]
```diff
@@ -748,25 +742,6 @@ future<> raft_group0::setup_group0(
...
-        auto server_id = utils::UUID(value->value());
-        if (server_id == utils::UUID{}) {
-            upgrade_log.error("empty Host ID for host {} ", ip_addr);
-            return;
-        }
-        // The failure detector needs the IPs on all shards. We
-        // can safely overwrite existing entries since are loading
-        // them directly from gossiper app state - which is most
-        // recent.
-        _raft_gr.address_map().add_or_update_entry(raft::server_id{server_id}, ip_addr);
```
Comment (kbr-scylla) [inline service/raft/raft_group0.cc:766]: This should probably provide the generation number though

File: service/storage_service.cc [hunk 11]
```diff
@@ -704,9 +704,16 @@ class storage_service::raft_ip_address_updater: public gms::i_endpoint_state_cha
 
         const auto prev_ip = _address_map.find(id);
         _address_map.add_or_update_entry(id, endpoint, ep_state->get_heart_beat_state().get_generation());
+        if (prev_ip == endpoint) {
+            co_return;
+        }
+        if (_address_map.find(id) == prev_ip) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:715]: Comment should explain the reasoning behind this branch

File: service/storage_service.cc [hunk 12]
```diff
@@ -728,9 +733,13 @@ class storage_service::raft_ip_address_updater: public gms::i_endpoint_state_cha
             (void)_ss._group0->client().hold_read_apply_mutex().then([this, id, endpoint, prev_ip](semaphore_units<> g) {
                 const auto hid = locator::host_id{id.uuid()};
                 if (_address_map.find(id) == endpoint && _ss.get_token_metadata().get_endpoint_for_host_id_if_known(hid) != endpoint) {
-                    return _ss.mutate_token_metadata([this, hid, prev_ip](mutable_token_metadata_ptr t) {
-                        return _ss.sync_raft_topology_nodes(std::move(t), hid, prev_ip, {});
-                    }).finally([g = std::move(g)]{});
+                    return utils::get_local_injector().inject("ip-change-raft-sync-delay", std::chrono::milliseconds(500))
+                        .then([this, hid, prev_ip]() {
```
Comment (kbr-scylla) [inline service/storage_service.cc:737]: I see we're piling more and more `then`s, perhaps it's time to coroutinize this code?

File: test/topology/test_change_ip.py [hunk 13]
```diff
@@ -8,56 +8,118 @@
...
-    servers = await manager.running_servers()
+
+    logger.info(f"Servers {servers}, gracefully stopping servers {servers[1]} and {servers[2]} to change ips")
+    await manager.server_stop_gracefully(servers[1].server_id)
+    await manager.server_stop_gracefully(servers[2].server_id)
+    s1_new_ip = await manager.server_change_ip(servers[1].server_id)
+    s2_new_ip = await manager.server_change_ip(servers[2].server_id)
+    logger.info(f"s1 new ip {s1_new_ip}, s2 new ip {s2_new_ip}")
+
+    async def reconnect_driver():
```
Comment (kbr-scylla) [inline test/topology/test_change_ip.py:41]: You can import from test.topology.util

File: test/topology/test_change_ip.py [hunk 14]
```diff
@@ -8,56 +8,118 @@
...
 from test.pylib.random_tables import Column, IntType, TextType
-import time
+from test.pylib.util import wait_for_cql_and_get_hosts, wait_for
+
 logger = logging.getLogger(__name__)
 
 
 @pytest.mark.asyncio
-async def test_change_two(manager, random_tables):
+async def test_change_two(manager, random_tables, mode):
```
Comment (kbr-scylla) [inline test/topology/test_change_ip.py:24]: Please execute the test 100 times in debug mode to eliminate potential flakiness

File: test/topology/test_change_ip.py [hunk 15]
```diff
@@ -8,56 +8,118 @@
...
+    s1_new_ip = await manager.server_change_ip(servers[1].server_id)
+    s2_new_ip = await manager.server_change_ip(servers[2].server_id)
+    logger.info(f"s1 new ip {s1_new_ip}, s2 new ip {s2_new_ip}")
+
+    async def reconnect_driver():
+        manager.driver_close()
+        await manager.driver_connect()
+
+    async def wait_proper_ips(alive_servers: list[ServerInfo]):
+        hosts = {h.address: h for h in await wait_for_cql_and_get_hosts(manager.cql, alive_servers, time.time() + 60)}
```
Comment (kbr-scylla) [inline test/topology/test_change_ip.py:46]: manager.get_cql() to avoid type error

File: service/storage_service.cc [hunk 16]
```diff
@@ -431,6 +431,11 @@ future<> storage_service::sync_raft_topology_nodes(mutable_token_metadata_ptr tm
             }
 
             if (prev_ip) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:433]: >   * We inject failure before old IP is removed and verify  that after restart the node sees the proper peers - the  new IP for node2 and old IP for node2, which is not restarted  yet.

I think it was supposed to be new IP for node1

**Comment by gusev-p** [comment]
> I don't like it that the scope of the PR suddenly increased, it puts large overhead on the reviewers to understand what changed and what didn't from the previous version, incremental development is easier. Basically a second PR was added to the original one...

The changes are tightly coupled, especially in `test_change_ip.py`. With two PRs there would be many conflicts and dependencies. And I believe it's also easier and faster to review - one test_change_ip refactor instead of many changes scattered in different commits/PRs.

**Comment by gusev-p** [comment]
> The cover letter is exactly the same as before, which makes things even more confusing.

updated

File: test/topology/test_change_ip.py (hunk 14 above)
Comment (gusev-p) [reply test/topology/test_change_ip.py:25]: got two failures out of 100, will try to investigate tomorrow

**Comment by gusev-p** [comment]
new version:
  * small review fixes
  * coroutinized [raft_ip_address_updater::on_endpoint_change](https://github.com/scylladb/scylladb/pull/17162/commits/3f18f466539931cef0ae4a7b5e9f2d7c3961a172)

[all changes](https://github.com/scylladb/scylladb/compare/57705690e796a7c05ff04312e91f7227b03bafac..c8c9f485cc86f51fdf9e2defe06dc69b9e71510b)

File: service/raft/raft_group0.cc [hunk 17]
```diff
@@ -386,12 +386,6 @@ future<> raft_group0::start_server_for_group0(raft::group_id group0_id, service:
     // The address map may miss our own id in case we connect
     // to an existing Raft Group 0 leader.
     auto my_id = load_my_id();
-    _raft_gr.address_map().add_or_update_entry(my_id, _gossiper.get_broadcast_address());
-    // At this time the group registry is already up and running,
-    // so the address map is getting all the notifications from
-    // the gossiper. By reading the application state *after* subscribing to new gossip events,
-    // we ensure we haven't missed any IP update in the map.
```
[the remark this answers is not in the document]
Comment (kbr-scylla) [reply service/raft/raft_group0.cc:393]: > I don't see how we can miss anything with the current code - init_address_map is called before gossiper is started, it does both - adds the stored mappings and subscribes to gossiper.

Ok, if we now indeed subscribe to gossiper before starting it, it should work. I think previously the order was reversed, so we could have missed some updates that were delivered before we subscribed, and we needed to fill that missing state by this scan.

File: test/topology/test_change_ip.py [hunk 18]
```diff
@@ -8,56 +8,118 @@
...
+        await manager.api.enable_injection(servers[0].ip_addr, 'crash-before-prev-ip-removed', one_shot=True)
+        await manager.api.enable_injection(servers[0].ip_addr, 'ip-change-raft-sync-delay', one_shot=False)
+    await manager.server_start(servers[1].server_id)
+    servers[1] = ServerInfo(servers[1].server_id, s1_new_ip, s1_new_ip)
+    if mode != 'release':
+        s0_logs = await manager.server_open_log(servers[0].server_id)
+        await s0_logs.wait_for('crash-before-prev-ip-removed hit, killing the node')
+        await manager.server_stop(servers[0].server_id)
+        await manager.server_start(servers[0].server_id)
+        await manager.api.enable_injection(servers[0].ip_addr, 'ip-change-raft-sync-delay', one_shot=False)
```
[the remark this answers is not in the document]
Comment (kbr-scylla) [reply test/topology/test_change_ip.py:104]: Depends on which notification this is supposed to catch -- if it's supposed to observe `servers[1]` or itself on restart, that notification may happen before you inject, so the injection will not work. If you're injecting this to catch the `servers[2]` start below, then it's fine.

(BTW. comments would be helpful, why we're delaying these notifications and which notifications we want to delay)

File: service/storage_service.cc [hunk 19]
```diff
@@ -681,44 +694,76 @@ future<> storage_service::merge_topology_snapshot(raft_topology_snapshot snp) {
...
+                ev, id, prev_ip, endpoint);
 
             // We're in a gossiper event handler, so gossiper is currently holding a lock
             // for the endpoint parameter of on_endpoint_change.
             // The topology_state_load function can also try to acquire gossiper locks.
             // If we call sync_raft_topology_nodes here directly, a gossiper lock and
             // the _group0.read_apply_mutex could be taken in cross-order leading to a deadlock.
             // To avoid this, we don't wait for sync_raft_topology_nodes to finish.
-            (void)_ss._group0->client().hold_read_apply_mutex().then([this, id, endpoint](semaphore_units<> g) {
+            (void)_ss._group0->client().hold_read_apply_mutex().then(ensure_alive([this, id, endpoint, prev_ip, h = _ss._async_gate.hold()](semaphore_units<> g) -> future<> {
```
Comment (kbr-scylla) [inline service/storage_service.cc:755]: This problem was solved in existing code by turning the captures into arguments and then binding them with `bind_front`. See e.g. `raft_group0::discover_group0`
```cpp
    }).finally(std::bind_front([] (raft_group0& self, persistent_discovery& p_discovery) -> future<> {
        co_await p_discovery.stop();
        self._group0 = std::monostate{};
    }, std::ref(*this), std::ref(p_discovery)));
```

Comment (kbr-scylla) [reply service/storage_service.cc:755]: Also why leave this single `then`? It could be put into the coroutine too.

File: main.cc (hunk 9 above)
Comment (kbr-scylla) [reply main.cc:1794]: > I should have given a more detailed reasoning in the commit message, updated it.

The commit message looks the same to me as it was.

I would explain why it's also no longer necessary on the other path where we start server for group -- we subscribe to gossiper before starting gossiping, so we won't miss any gossiper notifications.

Comment (gusev-p) [reply main.cc:1794]: > The commit message looks the same to me as it was.

Idk what's happening, sometimes git just refuses to do what I want. I clearly remember how I updated the commit message.

We do this again.

File: test/topology/test_change_ip.py (hunk 18 above)
[the remark this answers is not in the document]
Comment (gusev-p) [reply test/topology/test_change_ip.py:104]: > (BTW. comments would be helpful, why we're delaying these notifications and which notifications we want to delay)

This is mentioned in the commit message.
> Note that we need to inject an additional delay ip-change-raft-sync-delay
> before old IP is removed. Otherwise the problem stop reproducing - other
> nodes remove the old IP before it's send back to the just restarted node.

> Depends on which notification this is supposed to catch -- if it's supposed to observe servers[1] or itself on restart, that notification may happen before you inject, so the injection will not work. (And then you should use the startup injections.) If you're injecting this to catch the servers[2] start below, then it's fine.

Injection into `servers[0]` should catch `server[1]` and `server[2]` restart. The `server[0]` itself restarts `if mode != 'release'`, so we need to inject `ip-change-raft-sync-delay` again after restart.

File: service/storage_service.cc [hunk 20]
```diff
@@ -681,44 +694,76 @@ future<> storage_service::merge_topology_snapshot(raft_topology_snapshot snp) {
...
 
+// Moves the coroutine lambda onto the heap and extends its
+// lifetime until the resulting future is completed.
+// This allows to use captures in coroutine lambda after co_await-s.
+// Without this helper the coroutine lambda is destroyed immediately after
+// the caller (e.g. 'then' function implementation) has invoked it and got the future,
+// so referencing the captures after co_await would be use-after-free.
+template <typename Coro>
+auto ensure_alive(Coro&& coro) {
+    return [coro_ptr = make_lw_shared<Coro>(std::move(coro))]<typename ...Args>(Args&&... args) {
```
[the remark this answers is not in the document]
Comment (gusev-p) [reply service/storage_service.cc:705]: done

**Comment by gusev-p** [comment]
new version:
  * rebased on master;
  * make `on_endpoint_change` even more coroutinized;
  * restored the lost commit message part about why `load_initial_raft_address_map` was removed;
  * use `unique_ptr` in `ensure_alive`.

File: db/system_keyspace.cc [hunk 21]
```diff
@@ -1735,114 +1773,98 @@ static std::vector<cdc::generation_id_v2> decode_cdc_generations_ids(const set_t
...
-            auto peer = gms::inet_address(row.get_as<net::inet_address>("peer"));
-            if (!get_host_id(peer, row)) {
-                continue;
-            }
-            if (row.has("tokens")) {
-                ret.emplace(peer, decode_tokens(deserialize_set_column(*peers(), row, "tokens")));
-            }
+    co_await peers_table_read_fixup();
+
+    const sstring req = format("SELECT peer, host_id, tokens FROM system.{}", PEERS);
```
Comment (bhalevy) [inline db/system_keyspace.cc:1779]: nit: host_id is unused now

File: db/system_keyspace.cc [hunk 22]
```diff
@@ -1735,114 +1773,98 @@ static std::vector<cdc::generation_id_v2> decode_cdc_generations_ids(const set_t
...
+            locator::host_id(row.get_as<utils::UUID>("host_id")));
+    }
+    co_return ret;
 }
 
 future<std::vector<gms::inet_address>> system_keyspace::load_peers() {
-    auto res = co_await execute_cql(format("SELECT peer, host_id, tokens FROM system.{}", PEERS));
+    co_await peers_table_read_fixup();
+
+    const auto res = co_await execute_cql(format("SELECT peer, host_id, tokens FROM system.{}", PEERS));
```
Comment (bhalevy) [inline db/system_keyspace.cc:1807]: nit: host_id is unused now

File: test/topology/test_change_ip.py (hunk 18 above)
[the remark this answers is not in the document]
Comment (kbr-scylla) [reply test/topology/test_change_ip.py:104]: > This is mentioned in the commit message.

I meant comments in the test code. The commit message is much harder to access (you need to `git blame` etc.)

File: test/topology/test_change_ip.py (hunk 14 above)
Comment (gusev-p) [reply test/topology/test_change_ip.py:25]: fixed

**Comment by gusev-p** [comment]
new version:
  * dropped background fibers from `raft_ip_address_updater::on_endpoint_change`, use `gms::permit_id` instead
  * make the `./test.py topology/test_change_ip --mode debug --save-log-on-success --repeat 100` pass
    * fixed the bug in old IP removal when a node changes IP -- passing `prev_ip` to `sync_raft_topology_nodes` doesn't work, since the node may be not in a normal state at the moment, we won't use `prev_ip` neither in the current `sync_raft_topology_nodes` call not in the subsequent `topology_state_load` where it will eventually become normal. Fixed it by constructing `host_id -> ip` map inside `sync_raft_topology_nodes` and consulting it every time we update a normal node.

**Comment by kbr-scylla** [comment]
@gusev-p I looked at one of these failures, it timed out on server_add, and e.g.
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6672/artifact/testlog/x86_64/debug/scylla-1303.log
```
INFO  2024-02-14 22:14:30,922 [shard 0:strm] query_processor - Column definitions for system_distributed.cdc_generation_timestamps changed, invalidating related prepared statements
INFO  2024-02-14 22:14:30,925 [shard 0:strm] schema_tables - Schema version changed to a31f558e-cb75-11ee-0e0a-4a3ffd80a9f8
INFO  2024-02-14 22:14:30,926 [shard 0:strm] messaging_service - Dropping connection to 127.35.2.8 because it was created without topology information
INFO  2024-02-14 22:14:30,926 [shard 0:strm] messaging_service - Dropping connection to 127.35.2.8 because it was created without topology information
INFO  2024-02-14 22:14:30,929 [shard 1:strm] messaging_service - Dropping connection to 127.35.2.11 because it was created without topology information
INFO  2024-02-14 22:14:30,930 [shard 0:strm] messaging_service - Dropping connection to 127.35.2.16 because it was created without topology information
INFO  2024-02-14 22:15:02,454 [shard 0:main] raft_group_registry - marking Raft server da6421f5-1938-4eb5-8d3b-583d42d00214 as dead for raft groups
INFO  2024-02-14 22:15:02,476 [shard 0:main] raft_group_registry - marking Raft server 5cff46f7-d35a-4502-ab56-97724a2bb50b as dead for raft groups
INFO  2024-02-14 22:15:02,477 [shard 0:main] raft_group_registry - marking Raft server becf031c-b903-46df-869f-9cafb4a643d7 as dead for raft groups
WARN  2024-02-14 22:15:03,273 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:05,275 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:07,277 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:09,278 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:11,280 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:13,282 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:15,283 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:17,285 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:19,287 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:21,289 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-14 22:15:23,291 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2024-02-14 22:15:23,291 [shard 0:strm] gossip - failure_detector_loop: Mark node 127.35.2.8 as DOWN
INFO  2024-02-14 22:15:23,292 [shard 0:strm] gossip - InetAddress 127.35.2.8 is now DOWN, status = NORMAL
ERROR 2024-02-14 22:15:30,629 [shard 0: gms] gossip - gms/gossiper.cc(1689:28) `future<> gms::gossiper::real_mark_alive(inet_address)`: waiting for endpoint lock (ep=127.35.2.16) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
ERROR 2024-02-14 22:15:30,629 [shard 0: gms] gossip - gms/gossiper.cc(1689:28) `future<> gms::gossiper::real_mark_alive(inet_address)`: waiting for endpoint lock (ep=127.35.2.11) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
ERROR 2024-02-14 22:15:30,764 [shard 0: gms] gossip - gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`: waiting for endpoint lock (ep=127.35.2.16) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
ERROR 2024-02-14 22:15:30,788 [shard 0: gms] gossip - gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`: waiting for endpoint lock (ep=127.35.2.11) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
ERROR 2024-02-14 22:15:30,934 [shard 0:strm] gossip - service/storage_service.cc(670:32) `future<> service::storage_service::topology_state_load()`: waiting for endpoint lock (ep=127.35.2.11) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
ERROR 2024-02-14 22:15:31,261 [shard 0: gms] gossip - gms/gossiper.cc(736:32) `future<> gms::gossiper::do_status_check()`: waiting for endpoint lock (ep=127.35.2.16) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
```

and so on, gossiper is deadlocked

**Comment by kbr-scylla** [comment]
Could be from
> dropped background fibers from raft_ip_address_updater::on_endpoint_change, use gms::permit_id instead

**Comment by gusev-p** [comment]
> @gusev-p I looked at one of these failures, it timed out on server_add, and e.g. https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6672/artifact/testlog/x86_64/debug/scylla-1303.log
> 
> ```
> INFO  2024-02-14 22:14:30,922 [shard 0:strm] query_processor - Column definitions for system_distributed.cdc_generation_timestamps changed, invalidating related prepared statements
> INFO  2024-02-14 22:14:30,925 [shard 0:strm] schema_tables - Schema version changed to a31f558e-cb75-11ee-0e0a-4a3ffd80a9f8
> INFO  2024-02-14 22:14:30,926 [shard 0:strm] messaging_service - Dropping connection to 127.35.2.8 because it was created without topology information
> INFO  2024-02-14 22:14:30,926 [shard 0:strm] messaging_service - Dropping connection to 127.35.2.8 because it was created without topology information
> INFO  2024-02-14 22:14:30,929 [shard 1:strm] messaging_service - Dropping connection to 127.35.2.11 because it was created without topology information
> INFO  2024-02-14 22:14:30,930 [shard 0:strm] messaging_service - Dropping connection to 127.35.2.16 because it was created without topology information
> INFO  2024-02-14 22:15:02,454 [shard 0:main] raft_group_registry - marking Raft server da6421f5-1938-4eb5-8d3b-583d42d00214 as dead for raft groups
> INFO  2024-02-14 22:15:02,476 [shard 0:main] raft_group_registry - marking Raft server 5cff46f7-d35a-4502-ab56-97724a2bb50b as dead for raft groups
> INFO  2024-02-14 22:15:02,477 [shard 0:main] raft_group_registry - marking Raft server becf031c-b903-46df-869f-9cafb4a643d7 as dead for raft groups
> WARN  2024-02-14 22:15:03,273 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:05,275 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:07,277 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:09,278 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:11,280 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:13,282 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:15,283 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:17,285 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:19,287 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:21,289 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> WARN  2024-02-14 22:15:23,291 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.35.2.8, status = failed: seastar::rpc::closed_error (connection is closed)
> INFO  2024-02-14 22:15:23,291 [shard 0:strm] gossip - failure_detector_loop: Mark node 127.35.2.8 as DOWN
> INFO  2024-02-14 22:15:23,292 [shard 0:strm] gossip - InetAddress 127.35.2.8 is now DOWN, status = NORMAL
> ERROR 2024-02-14 22:15:30,629 [shard 0: gms] gossip - gms/gossiper.cc(1689:28) `future<> gms::gossiper::real_mark_alive(inet_address)`: waiting for endpoint lock (ep=127.35.2.16) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
> ERROR 2024-02-14 22:15:30,629 [shard 0: gms] gossip - gms/gossiper.cc(1689:28) `future<> gms::gossiper::real_mark_alive(inet_address)`: waiting for endpoint lock (ep=127.35.2.11) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
> ERROR 2024-02-14 22:15:30,764 [shard 0: gms] gossip - gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`: waiting for endpoint lock (ep=127.35.2.16) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
> ERROR 2024-02-14 22:15:30,788 [shard 0: gms] gossip - gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`: waiting for endpoint lock (ep=127.35.2.11) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
> ERROR 2024-02-14 22:15:30,934 [shard 0:strm] gossip - service/storage_service.cc(670:32) `future<> service::storage_service::topology_state_load()`: waiting for endpoint lock (ep=127.35.2.11) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
> ERROR 2024-02-14 22:15:31,261 [shard 0: gms] gossip - gms/gossiper.cc(736:32) `future<> gms::gossiper::do_status_check()`: waiting for endpoint lock (ep=127.35.2.16) took more than 1m, signifying possible deadlock; holders: 1, first holder: gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`, last holder (might not be current): gms/gossiper.cc(569:28) `future<> gms::gossiper::do_apply_state_locally(gms::inet_address, endpoint_state, bool)`
> ```
> 
> and so on, gossiper is deadlocked

yes, same problem fixed by `ensure_alive`, gossiper permits don't help here, reverting back

**Comment by gusev-p** [comment]
new version:
  * fix tests, revert the stupid attempt at solving gossiper deadlock with `permit_id`-s, it doesn't work

File: service/storage_service.cc [hunk 23]
```diff
@@ -370,16 +370,37 @@ future<> storage_service::sync_raft_topology_nodes(mutable_token_metadata_ptr tm
...
+        co_return &*map;
+    };
+
     std::vector<future<>> sys_ks_futures;
 
+    auto remove_ip = [&](inet_address ip) -> future<> {
+        sys_ks_futures.push_back(_sys_ks.local().remove_endpoint(ip));
+
+        if (_gossiper.get_endpoint_state_ptr(ip) && !get_used_ips().contains(ip)) {
+            co_await _gossiper.force_remove_endpoint(ip, gms::null_permit_id);
```
Comment (kbr-scylla) [inline service/storage_service.cc:396]: Haven't noticed this earlier, but is it OK to do it before / concurrently with `_sys_ks.local().remove_endpoint(ip));`?

File: service/storage_service.cc [hunk 24]
```diff
@@ -425,6 +451,10 @@ future<> storage_service::sync_raft_topology_nodes(mutable_token_metadata_ptr tm
             if (!prev_normal.contains(id)) {
                 co_await notify_joined(*ip);
             }
+
+            if (const auto it = host_id_to_ip_map.find(host_id); it != host_id_to_ip_map.end() && it->second != *ip) {
```
Comment (kbr-scylla) [inline service/storage_service.cc:454]: I don't see any code that would add / update new mapping in this map, if one appears

Comment (kbr-scylla) [reply service/storage_service.cc:454]: So it looks like we'll purge the old IP only in very specific scenario, the first time we change a node's IP... Then when it's changed again into a third IP, we won't find the second, so we won't purge it

Comment (gusev-p) [reply service/storage_service.cc:454]: `host_id_to_ip_map` is local to the `sync_raft_topology_nodes` invocation, each node is processed only once

File: service/storage_service.cc (hunk 23 above)
Comment (gusev-p) [reply service/storage_service.cc:396]: > Hmm, I think this function is bugged currently, and gossiper updates need to happen after corresponding system keyspace updates.

why?

Comment (kbr-scylla) [reply service/storage_service.cc:396]: I'm not sure about remove_ip, the whole thing is hard to reason about..

but for example here
```cpp
            sys_ks_futures.push_back(_sys_ks.local().update_peer_info(*ip, info));
            if (!prev_normal.contains(id)) {
                co_await notify_joined(*ip);
            }
```

isn't it important that we put entry to peers before we send notifications? cc @gleb-cloudius 

Driver could receive such notification, then refresh peers but observe old state.

In general outside observes may see things happening out of order, and I'm worried it could cause hard to reproduce and debug bugs.


Or here
```cpp
            sys_ks_futures.push_back(_sys_ks.local().update_tokens(rs.ring.value().tokens));
            co_await _gossiper.add_local_application_state({
                { gms::application_state::TOKENS, gms::versioned_value::tokens(rs.ring.value().tokens) },
                { gms::application_state::CDC_GENERATION_ID, gms::versioned_value::cdc_generation_id(_topology_state_machine._topology.current_cdc_generation_id) },
                { gms::application_state::STATUS, gms::versioned_value::normal(rs.ring.value().tokens) }
            });
```

is it fine that other nodes might observe our gossip status update before we persist it locally? I think it's just asking for trouble...

File: service/storage_service.cc (hunk 24 above)
Comment (gusev-p) [reply service/storage_service.cc:454]: it's a local multishard read from memory (it should reside in row_cache), how  can it be more expensive than e.g. `o_dsync` write?

File: service/storage_service.cc (hunk 23 above)
Comment (kbr-scylla) [reply service/storage_service.cc:396]: Moving the concurrency "outside" these lambdas would simplify reasoning a lot, put some order to things, while keeping the optimization intact. (There would still be concurrency between updates for different peers, which was the goal.)

Comment (gusev-p) [reply service/storage_service.cc:396]: > The concurrency of system keyspace updates can be achieved by not co_awaiting on the process_normal_node etc. calls but putting them into a vector of futures. But inside process_normal_node etc., we should be doing operations in order.

It can't, this'll entail concurrent `token_metadata` mutations, e.g. multiple fibers mutating `_token_to_endpoint_map` through `update_normal_tokens`.

Comment (kbr-scylla) [reply service/storage_service.cc:396]: Anyway, it's out of scope of this PR.

File: service/storage_service.cc (hunk 24 above)
Comment (kbr-scylla) [reply service/storage_service.cc:454]: Anyway the simplest way would be to run the 100 node again and see whether there's any significant regression, maybe my worries are unfounded, @gusev-p could you please check?

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Qd

File: service/storage_service.cc (hunk 24 above)
Comment (kbr-scylla) [reply service/storage_service.cc:454]: We can address in follow-up if it turns out it's a problem.

Comment (gusev-p) [reply service/storage_service.cc:454]: I ran it (still getting 1000-sec timeout):
`INFO  2024-02-15 17:37:43,406 [shard 0:strm] raft_topology - sync_raft_topology_nodes, total us 289570, transition us 0, left us 0, total_update_peer_info_us 1158, total_update_peer_info_count 60, total_normal_us 1838, total_normal_count 61 get_host_id_to_ip_map_us 373 total_sys_ks_us 287646`

Comment (kbr-scylla) [reply service/storage_service.cc:454]: The previous result was (https://github.com/scylladb/scylladb/issues/17039#issuecomment-1935634888)
```
INFO  2024-02-09 10:58:14,679 [shard 0:strm] raft_topology - sync_raft_topology_nodes, total us 169330, transition us 76, left us 0, total_normal_us 1072, total_normal_count 57
```

so there is some regression, although better what we started with

(or maybe it's variability)
