### PR TITLE
Fix a few rare bugs in row cache

### LINKED ISSUE #15483: test_concurrent_reads_and_eviction: Mutation read doesn't match any expected version
This was hit in CI with an unrelated change so it can be attrobuted to baseline version b87660f90c
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3706/artifact/testlog/x86_64/release/boost.row_cache_test.test_concurrent_reads_and_eviction.3.log
```
random-seed=2470087052
random_mutation_generator seed: 2568563592
test/boost/row_cache_test.cc(3447): fatal error: in "test_concurrent_reads_and_eviction": Mutation read doesn't match any expected version ...
```

[boost.row_cache_test.test_concurrent_reads_and_eviction.3.log.gz](https://github.com/scylladb/scylladb/files/12669636/boost.row_cache_test.test_concurrent_reads_and_eviction.3.log.gz)

@michoecho please look into this

### PR DESCRIPTION
**Pull request by michoecho**
This is a loose collection of fixes to rare row cache bugs flushed out by running test_concurrent_reads_and_eviction several million times. See individual commits for details.

Fixes #15483

### CODE REVIEW

**Comment by bhalevy** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - Build ❌ - Sanity Tests ✅ - Unit Tests
> 
> #### Failed Tests (1/21259):
> * [test_replace_node_using_new_ip_then_shut_down[rbo_disabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4515/testReport/junit/replace_address_test/TestReplaceAddress/Tests___Sanity_Tests___test_replace_node_using_new_ip_then_shut_down_rbo_disabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_node_using_new_ip_then_shut_down%5Brbo_disabled%5D)
> 
> #### Build Details:
> * Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4515/
> * Duration: 2 hr 10 min
> * Builder: spider4.cloudius-systems.com

https://github.com/scylladb/scylladb/issues/15918

File: cache_flat_mutation_reader.hh [hunk 1]
```diff
@@ -1041,6 +1042,20 @@ void cache_flat_mutation_reader::maybe_set_static_row_continuous() {
...
+// due to the "older versions are evicted first" rule of MVCC.
+// Thus, when we make an entry continuous, we must ensure that it isn't an
+// unlinked last dummy.
+inline
+void cache_flat_mutation_reader::set_rows_entry_continuous(rows_entry& e) {
+    e.set_continuous(true);
+    if (!e.is_linked()) [[unlikely]] {
+        _snp->tracker()->touch(e);
+    }
+}
```
Comment (nyh) [inline cache_flat_mutation_reader.hh:1070]: I know all of these issues were found by a randomized test, but could we had a separate regression test for each one?

Another thing you can do is to keep a list of random seeds that must be run on every run of the randomized test because they reproduced known bugs. The problem with this approach, though, is that you have to trust that the random number algorithm will never change, and I don't see how you can trust this unless you add your own random number generator function, and then rerun your million random tests to find reproducers for each of these bugs :-(

**Review by nyh — COMMENTED** [review]
All the patches look like legal C++ to me ;-) But unfortunately I'm not familiar enough with how the Scylla caching code works to know if any of these changes are correct. Let's get someone who is familiar with this code (@tgrabiec ? @avikivity ? @denesb ?) to review it.

I would have liked to see a unit test that reproduces the need for every one of these changes, as this would be an even better "proof" that these fixes are correct than I can ever hope to achieve by reviewing the patches. I realize you discovered these issues through randomized testing, which is great, but surely you had to be able to reproduce each one of these issues - either by writing a new test - or by picking a specific random  seed for the randomized test? In that case, we should know what these new tests/seeds are, so we can run them every time to ensure regressions do not happen in these cases which we now know is not being tested in any other test (otherwise, we would have known these bugs already).

**Comment by michoecho** [comment]
@nyh

>  Let's get someone who is familiar with this code (@tgrabiec ? @avikivity ? @denesb ?) to review it.

@tgrabiec is *the* reviewer for row cache. I also requested @denesb because he spent some time debugging these issues before I took over.

> I realize you discovered these issues through randomized testing, which is great, but surely you had to be able to reproduce each one of these issues - either by writing a new test - or by picking a specific random seed for the randomized test? In that case, we should know what these new tests/seeds are, so we can run them every time to ensure regressions do not happen in these cases which we now know is not being tested in any other test (otherwise, we would have known these bugs already).

This test is nondeterministic. It performs many concurrent operations (reads, updates, evictions) on the cache, and its outcome depends on how exactly they are preempted and ordered by the reactor.

To debug the test, I had to make it deterministic: I modified Seastar so that preemption wasn't timing-dependent, but pseudorandom. Only then I could get the same execution every time.

But this technique only works for debugging, where you don't change any logic between runs. It can't be used for regression tests. As soon as you make some nontrivial change to the code, the seed will no longer be testing the case you want to test.

> I would have liked to see a unit test that reproduces the need for every one of these changes, as this would be an even better "proof" that these fixes are correct than I can ever hope to achieve by reviewing the patches.

 Unfortunately most of the bugs fixed by this PR are not testable. They require a specific state which can only be arrived at when preemptions happen at just the right points. There

**Comment by michoecho** [comment]
> Unfortunately most of the bugs fixed by this PR are not testable. They require a specific state which can only be arrived at when preemptions happen at just the right points.

Well, of course we could construct the specific state (at the point right before the buggy function runs) manually. But such a test would be very fragile.

> Another thing you can do is to keep a list of random seeds that must be run on every run of the randomized test because they reproduced known bugs.

We could also run the test 10 million times before releases. (For reference: the rarest of the bugs fixed by this PR were reproducing about once in ~300000 runs).

But there is only so much you can do with hand-written or random tests. The space of states to test is just too big. I wish we had a more systematic approach.

**Comment by nyh** [comment]
> > Let's get someone who is familiar with this code (@tgrabiec ? @avikivity ? @denesb ?) to review it.
> 
> @tgrabiec is _the_ reviewer for row cache. I also requested @denesb because he spent some time debugging these issues before I took over.

Yes, I know, this is why I asked them again. Pinging people on github isn't rude - it's the only real way to remind people if you want them to review your code. Because people don't normally (at least, I don't...) perform a query of all open PRs where they were mentioned in the past. Of course, it's also possible that Tomek and Botond have much better memory than I do, and remember they need to review your patch and just didn't get around to it yet, in which case - sorry for the spam.

> To debug the test, I had to make it deterministic: I modified Seastar so that preemption wasn't timing-dependent, but pseudorandom. Only then I could get the same execution every time.
> 
> But this technique only works for debugging, where you don't change any logic between runs. It can't be used for regression tests. As soon as you make some nontrivial change to the code, the seed will no longer be testing the case you want to test.

I see. Thanks. Did all these bugs depend on Seastar preemption - or just some of them did? For bugs that really can only be reproduced with particular sequence of preemption, maybe we could add some hooks in normal Seastar (without hacking Seastar) for disabling and forcing preemption and then somehow using those hooks in unit tests?

> Unfortunately most of the bugs fixed by this PR are not testable. They require a specific state which can only be arrived at when preemptions happen at just the right points.

Then how can you prove - or at least did you "prove" to yourself - that your fixes really fixed those bugs which you found?
How can anyone in the future ever modify the code which you change here without worrying he might re-introduce these bugs and not be aware that it happens?

I have another idea. You said that you discovered all these bugs using a randomized test. How long did this run take? Maybe we need to include this randomized test - with its million random attempts (and not just a handful) - in our battery of long-running tests - which we don't have to run on every CI run, but maybe we need to re-run at least once a week or something?

**Comment by michoecho** [comment]
> Of course, it's also possible that Tomek and Botond have much better memory than I do, and remember they need to review your patch and just didn't get around to it yet, in which case - sorry for the spam.

This PR was posted on Friday evening, and now it's Sunday evening.

> Did all these bugs depend on Seastar preemption - or just some of them did?

I think the bug in `partition_version: fix violation of "older versions are evicted first" during schema upgrades` is the only one that can be reproduced without depending on specific preemption sequences.

> For bugs that really can only be reproduced with particular sequence of preemption, maybe we could add some hooks in normal Seastar (without hacking Seastar) for disabling and forcing preemption and then somehow using those hooks in unit tests?

I don't see any sane way of solving the problem with hooks and injections. Yes, if you add enough of them, you can force "preemption" to work exactly as you need, but this is something worth doing? How much effort is reasonable to put into writing tests designed *extremely* specifically to reproduce an already-fixed bug?

> Then how can you prove - or at least did you "prove" to yourself - that your fixes really fixed those bugs which you found?

1. By understanding the bugs (gained by detailed observation — through logs and debuggers — of the failing random test cases).
2. By validating that the random test isn't failing over millions of runs.

> How can anyone in the future ever modify the code which you change here without worrying he might re-introduce these bugs and not be aware that it happens?

Without worrying? He can't.

And even if you could write a test that prevents specifically these bugs from being reintroduced, he would still have to worry about introducing new bugs in the other 1000 places where they can be introduced.

> I have another idea. You said that you discovered all these bugs using a randomized test. How long did this run take?

I ran it with shell loops (i.e. it the test binary had to do its setup and teardown every time — so perhaps it can be sped up), and it was doing ~2 attempts per second per core. So a million attempts on a 16-core machine took about 1000000 / 16 / (2/s) = 9 hours. 

> Maybe we need to include this randomized test - with its million random attempts (and not just a handful) - in our battery of long-running tests - which we don't have to run on every CI run, but maybe we need to re-run at least once a week or something?

There's probably no reason to run it periodically. Row cache code doesn't change every week. But it could be a good idea to do that when testing patchsets relevant to the cache.

**Comment by denesb** [comment]
@nyh the randomized test which revealed these bugs was failing intermittently for some time now. Because it is run in CI, it gets a lot of runtime spread over many PRs and it was telling us that there are bugs in the cache for some time now.
All this is to say -- for bugs found by looking into failures produced by a [flaky] test, I don't think we need separate regression tests -- there is already a test failing before and passing after.

**Comment by nyh** [comment]
> @nyh the randomized test which revealed these bugs was failing intermittently for some time now. Because it is run in CI, it gets a lot of runtime spread over many PRs and it was telling us that there are bugs in the cache for some time now. All this is to say -- for bugs found by looking into failures produced by a [flaky] test, I don't think we need separate regression tests -- there is already a test failing before and passing after.

On one hand, you're right. On the other hand, not entirely:

First of all, we (or at least I) don't have a good idea on how frequently or infrequently this test fails on actual Jenkins runs - if it only failed one a month, how will we ever notice if it fails again? @michoecho had to run this test in a loop for many hours to see some of these bugs - it is possible that we never saw them happen in any Jenkins run.

Second, and more importantly, as a reviewer I always suspect a fix that doesn't have a regression test - a test that shows the failure before the fix, and passing after the fix. Without such a regression test it's hard to know if a certain fix, which "looks" reasonable, actually fixes anything. This PR has many separate changes, how does its author or its reviewer know all of them are necessary or correct? But I agree that if @michoecho ran his many-hour-loop again after these patches, and it passed all of them, it increases the confidence that at least this PR is correct. It won't prevent other people from breaking this code in the future and then _not_ running the many-hour loop, but I guess nothing is perfect.

**Comment by bhalevy** [comment]
Also, we should consider the benefit of merging these fixes despite imperfect testing (and the risk of them introducing something new that our current test doesn't cover, even with 1M runs), vs. the risk of exposure if we don't merge those fixes, beyond the test failing from time to time.

**Comment by nyh** [comment]
> Also, we should consider the benefit of merging these fixes despite imperfect testing (and the risk of them introducing something new that our current test doesn't cover, even with 1M runs), vs. the risk of exposure if we don't merge those fixes, beyond the test failing from time to time.

I agree. This is why I asked that someone who is intimately familiar with this code (i.e., _not_ me) will review this PR before I merge it, because even if I don't fully trust the testing, a person who is familar with this code can look at the fixes and say "wow, that's right! great catch!". In a less optimistic case, such a reviewer may also look at the fix and say "no, this doesn't do what you think, if you didn't see the bug again after this fix you were just lucky".

I also agree that if @michoecho personally ran his 1-million-time test before and after his patches, and it failed many times before and not even once after, than his patches are most likely all correct, and I'm just making a mountain out of a mole-hill :-)

**Comment by bhalevy** [comment]
@tgrabiec @denesb please review and ack

**Comment by denesb** [comment]
> I also agree that if @michoecho personally ran his 1-million-time test before and after his patches, and it failed many times before and not even once after, than his patches are most likely all correct, and I'm just making a mountain out of a mole-hill :-)

The test failed quite often, I could reproduce a failure with a mere --repeat=20. Once making some changes to the test, it would fail on every other run. @michoecho maybe we could have a variant of this test with the equivalent of debuggable=true, which really translates to a smaller list of possible key values, producing more collisions and interesting overlaps. This was greatly improving the chances of reproducing bugs, when debugging this.

**Comment by avikivity** [comment]
> LGTM, but I cannot claim to have understood all the patches. In fact, as soon as I read "older versions are evicted first", my head starts to shutdown.
> 
> We need a review from @tgrabiec.


We need to simplify MVCC

File: cache_flat_mutation_reader.hh (hunk 1 above)
Comment (avikivity) [reply cache_flat_mutation_reader.hh:1070]: Those random seeds would be invalidated by any change to the algorithm, even if made preemption choices deterministic.

Comment (avikivity) [reply cache_flat_mutation_reader.hh:1070]: What we might do is add assertions (perhaps not in release mode) about invariants, so that the failure happens earlier. Thus, a failure that would otherwise not be detected (because we didn't read from the bad cache entry) would still cause a crash.

File: cache_flat_mutation_reader.hh [hunk 2]
```diff
@@ -510,7 +510,7 @@ bool cache_flat_mutation_reader::ensure_population_lower_bound() {
             return false;
         }
 
-        if (cmp(cur.position(), _last_row.position()) != 0) {
+        if (cmp(cur.table_position(), _last_row.position()) != 0) {
             return false;
```
Comment (avikivity) [inline cache_flat_mutation_reader.hh:525]: This one looks as if a simple unit test can be constructed for it (I'm not saying that creating the unit test would be simple, just that in the end it would probably be a large sequence of range tombstones or something).

**Comment by avikivity** [comment]
The conclusion of my review is that @tgrabiec must review it.

**Comment by bhalevy** [comment]
ping @tgrabiec

File: mutation/mutation_partition_v2.cc [hunk 3]
```diff
@@ -454,12 +454,12 @@ stop_iteration mutation_partition_v2::apply_monotonically(const schema& s, const
                 if (same_schema) [[likely]] {
```
Comment (tgrabiec) [inline mutation/mutation_partition_v2.cc:454]: > The last dummy in A is added to the front of LRU,
> so it will be evicted after the entries in B.

Since B is the new entry, you meant "The last dummy in B ... after ... in A" ?

File: cache_flat_mutation_reader.hh [hunk 4]
```diff
@@ -696,7 +696,7 @@ bool cache_flat_mutation_reader::maybe_add_to_cache(const range_tombstone_change
         if (ensure_population_lower_bound()) {
             // underlying may emit range_tombstone_change fragments with the same position.
             // In such case, the range to which the tombstone from the first fragment applies is empty and should be ignored.
-            if (q_cmp(_last_row.position(), it->position()) < 0) {
+            if (q_cmp(_last_row.position(), it->position()) != 0) {
```
[the remark this answers is not in the document]
Comment (tgrabiec) [reply cache_flat_mutation_reader.hh:712]: Oh, we're using query-domain comparator for table-domain positions here. For equality, it should give the same result. But it's a bit confusing, so a comment would be good.

[the remark this answers is not in the document]
Comment (michoecho) [reply cache_flat_mutation_reader.hh:712]: You got it right: `<` only works as intended for non-reverse queries, `!=` should work as intended for both types of queries.

I will add a comment about this.

File: mutation/mutation_partition_v2.cc (hunk 3 above)
Comment (michoecho) [reply mutation/mutation_partition_v2.cc:454]: Uh, right. I swapped A and B in this sentence.

Comment (michoecho) [reply mutation/mutation_partition_v2.cc:454]: And in the next one too.

Comment (michoecho) [reply mutation/mutation_partition_v2.cc:454]: I fixed the commit message.

File: cache_flat_mutation_reader.hh (hunk 4 above)
[the remark this answers is not in the document]
Comment (michoecho) [reply cache_flat_mutation_reader.hh:716]: Added a comment.

**Review by tgrabiec — APPROVED** [review]

**Comment by bhalevy** [comment]
@michoecho please rebase to get a clean baseline for re-testing.

**Comment by michoecho** [comment]
Rebased and restarted CI.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint pls merge
