### PR TITLE
storage_proxy: silence abort_requested_exception on reads and writes

### LINKED ISSUE #10447: Multiple error messages when node is drained  - `Exception when communicating with 10.142.0.30`, `abort requested`
## Installation details

Kernel Version: 5.13.0-1024-gcp
Scylla version (or git commit hash): `5.0~rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4 (34.75.26.179 | 10.142.0.125) (shards: 8)
- rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-3 (34.75.243.32 | 10.142.0.30) (shards: 8)
- rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-2 (34.148.118.119 | 10.142.0.29) (shards: 8)
- rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-1 (35.196.76.156 | 10.142.0.26) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts` (gce: eu-west-1)

Test: `rolling-upgrade-ubuntu20.04-test`
Test id: `e454ae74-e3ad-4ea2-afac-d47ea60beb00`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ubuntu20.04-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f485155a9f8b359c8e8da8d07cd3d4396aa5ca27/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

As part of the upgrade procedure, we first upgrade two nodes and then we rollback one of them. As part of the rollback, we drain said node (namely, node 3). After executing the drain command, however, the rest of the cluster reported on the same issue:
```
2022-04-23 06:54:56.586 <22-04-23 06:54:56.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=fa3a81ab-3b8b-4ef1-b125-e2bdedd81545: type=DATABASE_ERROR regex=Exception  line_number=11354 node=rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4
022-04-23T06:54:56+00:00 rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4 !     ERR |  [shard 2] storage_proxy - Exception when communicating with 10.142.0.30, to read from system_auth.roles: std::runtime_error (abort requested)
2022-04-23 06:54:56.586 <2022-04-23 06:54:56.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=fa3a81ab-3b8b-4ef1-b125-e2bdedd81545: type=DATABASE_ERROR regex=Exception  line_number=11355 node=rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4
2022-04-23T06:54:56+00:00 rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4 !     ERR |  [shard 2] storage_proxy - Exception when communicating with 10.142.0.30, to read from system_auth.roles: std::runtime_error (abort requested)
2022-04-23 06:54:56.588 <2022-04-23 06:54:56.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=fa3a81ab-3b8b-4ef1-b125-e2bdedd81545: type=DATABASE_ERROR regex=Exception  line_number=11361 node=rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4
2022-04-23T06:54:56+00:00 rolling-upgrade-master-ubuntu-focal-db-node-e454ae74-0-4 !     ERR |  [shard 3] storage_proxy - Exception when communicating with 10.142.0.30, to read from keyspace1.standard1: std::runtime_error (abort requested)
```
As soon as the drain process has ended, the errors no longer occur.

- Restore Monitor Stack command: `$ hydra investigate show-monitor e454ae74-e3ad-4ea2-afac-d47ea60beb00`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e454ae74-e3ad-4ea2-afac-d47ea60beb00)
- Show all stored logs command: `$ hydra investigate show-logs e454ae74-e3ad-4ea2-afac-d47ea60beb00`

## Logs:
- **db-cluster-e454ae74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/db-cluster-e454ae74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/db-cluster-e454ae74.tar.gz)
- **monitor-set-e454ae74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/monitor-set-e454ae74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/monitor-set-e454ae74.tar.gz)
- **loader-set-e454ae74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/loader-set-e454ae74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/loader-set-e454ae74.tar.gz)
- **sct-runner-e454ae74.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/sct-runner-e454ae74.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e454ae74-e3ad-4ea2-afac-d47ea60beb00/20220423_080906/sct-runner-e454ae74.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu20.04-test/64/)
The same error has happened in the rolling upgrade of:
- ami: 000670ad-44dd-4e7d-bcf9-7c4bca0ace2e
- centos7: ccf52aa1-7c09-4d4a-96a6-35abc974f353
- centos8: fb34651f-409c-4b28-8cb4-9bb1f23c4170
- debian10: 26147812-e601-41fa-8ad9-f4fdf56e48be
- ubuntu18: cbaa25c4-390a-4339-bda2-3ae23a82693e

### PR DESCRIPTION
**Pull request by patjed41**
Fixes #10447

This issue is an expected behavior. However, `abort_requested_exception` is not handled properly.

## Why this issue appeared

1. The node is drained.
2. `migration_manager::drain` is called and executes `_as.request_abort();`.
3. The coordinator sends read RPCs to the drained replica. On the replica side, `storage_proxy::handle_read` calls `migration_manager::get_schema_for_read`, which is defined like this:
```cpp
future<schema_ptr> migration_manager::get_schema_for_write(/* ... */) {
    if (_as.abort_requested()) {
        co_return coroutine::exception(std::make_exception_ptr(abort_requested_exception()));
    }
    /* ... */
```
So, `abort_requested_exception` is thrown.
4. RPC doesn't preserve information about its type, and it is converted to a string containing its error message.
5. It is rethrown as `std::runtime_error` on the coordinator side, and `abstract_resolve_reader::error()` logs information about it. However, we don't want to report `abort_requested_exception` there. This exception should be catched and ignored:
```cpp
void error(/* ... */) {
    /* ... */
   else if (try_catch<abort_requested_exception>(eptr)) {
        // do not report aborts, they are trigerred by shutdown or timeouts
    }
    /* ... */
```

## Proposed solution

To fix this issue, we can add `abort_requested_exception` to `replica::exception_variant` and make sure that if it is thrown by `migration_manager::get_schema_for_write`, `storage_proxy::handle_read` correctly  encodes it. Thanks to this change, `abstract_read_resolver::error` can correctly handle `abort_requested_exception` thrown on the replica side by not reporting it.

## Side effect of the proposed solution

If the replica supports it, the coordinator doesn't, and all nodes support `feature_service::typed_errors_in_read_rpc`, the coordinator will fail to decode `abort_requested_exception` and it will be decoded to `unknown_exception`. It will still be rethrown as `std::runtime_error`, however the message will change from *abort requested* to *unknown exception*.

## Another issue

Moreover, `handle_write` reports abort requests for the same reason. This also floods the logs (this time on the replica side) for the same reason. I don't think it is intended, so I've changed it too. This change is in the last commit.

### CODE REVIEW

File: service/storage_proxy.cc [hunk 1]
```diff
@@ -596,6 +596,8 @@ class storage_proxy::remote {
                     } else if constexpr(std::is_same_v<Ex, replica::stale_topology_exception>) {
                         msg = e.what();
                         return error::FAILURE;
+                    } else if constexpr (std::is_same_v<Ex, replica::abort_requested_exception>) {
+                        return error::FAILURE;
```
Comment (piodul) [inline service/storage_proxy.cc:608]: I think it could make sense to assign the error message to the `msg` variable. This will cause the "aborted requested" error message to be propagated back to the user, giving them a bit more context.

File: service/storage_proxy.cc [hunk 2]
```diff
@@ -689,17 +695,17 @@ class storage_proxy::remote {
         const auto fence = fence_opt.value_or(fencing_token{});
 
         if (auto stale = _sp.apply_fence(fence, src_ip)) {
-            co_return co_await encode_replica_exception_for_rpc<Result>(p->features(), to_future(std::move(*stale)));
+            co_return co_await add_replica_exception_to_query_result<Result>(p->features(), to_future(std::move(*stale)));
```
Comment (piodul) [inline service/storage_proxy.cc:704]: It looks like you could just replace the uses of `add_replica_exception_to_query_result` + `to_future` with just `encode_replica_exception_for_rpc`, no?

File: replica/exceptions.cc [hunk 3]
```diff
@@ -24,6 +24,8 @@ exception_variant try_encode_replica_exception(std::exception_ptr eptr) {
         return rate_limit_exception();
     } catch (const stale_topology_exception& e) {
         return e;
+    } catch (abort_requested_exception&) {
+        return abort_requested_exception();
```
Comment (piodul) [inline replica/exceptions.cc:28]: BTW, it looks like the `try_encode_replica_exception` function should be updated to use `utils::try_catch` and not throw. This is out of scope of this PR so no need to address it here, but it could be done in a follow up.

**Review by piodul — COMMENTED** [review]
Left some comments.

I'm not sure about the `unknown exception` issue. Usually, the right thing to do would be to introduce a cluster feature and let the error be encoded in the new form only after all nodes can recognize it. However, we know that we tend to avoid adding cluster features, and here it is mainly about printing the correct error message. One could argue whether "abort requested" in the logs has more meaning than "unknown exception". Maybe it is fine to leave it like this, but if we are OK with adding a cluster feature then we could add such protection with minimal amount of effort.

File: service/storage_proxy.cc [hunk 4]
```diff
@@ -482,8 +482,10 @@ class storage_proxy::remote {
                         errors.count++;
                         errors.local = replica::try_encode_replica_exception(eptr);
                         seastar::log_level l = seastar::log_level::warn;
-                        if (is_timeout_exception(eptr) || std::holds_alternative<replica::rate_limit_exception>(errors.local.reason)) {
-                            // ignore timeouts and rate limit exceptions so that logs are not flooded.
+                        if (is_timeout_exception(eptr)
+                            || std::holds_alternative<replica::rate_limit_exception>(errors.local.reason)
+                            || std::holds_alternative<abort_requested_exception>(errors.local.reason)) {
```
Comment (piodul) [inline service/storage_proxy.cc:487]: The seastar coding style (which we follow) requires to add two indents when you are breaking a long line like this. See: https://github.com/scylladb/seastar/blob/master/coding-style.md#long-lines.

**Comment by kbr-scylla** [comment]
> the coordinator will fail to decode abort_requested_exception and it will be decoded to unknown_exception

Can you point to the place in code where this will happen? I couldn't find any place where `unknown_exception` is constructed explicitly.

Have you tested that this is indeed what happens?

**Comment by kbr-scylla** [comment]
> Can you point to the place in code where this will happen? I couldn't find any place where unknown_exception is constructed explicitly.

I think I found the place, now trying to decipher it...
```cpp
template<typename Input, typename T, size_t... I>
T deserialize_std_variant(Input& in, boost::type<T> t,  size_t idx, std::index_sequence<I...>) {
    T v;
    (void)((I == idx ? v.template emplace<I>(deserialize(in, boost::type<std::variant_alternative_t<I, T>>())), true : false) || ...);
    return v;
}

template<typename Input, typename ...T>
std::variant<T...> deserialize(Input& in, boost::type<std::variant<T...>> v) {
    size_t idx = deserialize(in, boost::type<uint8_t>());
    return deserialize_std_variant(in, v, idx, std::make_index_sequence<sizeof...(T)>());
}
```

**Comment by kbr-scylla** [comment]
Hm, so since `idx` will be unknown for us, we will return a default-constructed `replica::exception_variant`.
https://en.cppreference.com/w/cpp/utility/variant/variant
> 1) Default constructor. Constructs a variant holding the [value-initialized](https://en.cppreference.com/w/cpp/language/value_initialization) value of the first alternative ([index()](https://en.cppreference.com/w/cpp/utility/variant/index) is zero).

So indeed it should be `unknown_exception`.

**Comment by patjed41** [comment]
> Have you tested that this is indeed what happens?

Yes, I have tested it, and the reason why it happens is exactly as you described.

File: replica/exceptions.cc (hunk 3 above)
Comment (kbr-scylla) [reply replica/exceptions.cc:28]: Also why do we return `no_exception{}` in the catch-all clause? Doesn't seem right.

File: service/storage_proxy.cc [hunk 5]
```diff
@@ -127,20 +127,26 @@ seastar::metrics::label_instance current_scheduling_group_label() {
...
-    if (!f.failed()) {
-        return make_ready_future<ResultTuple>(utils::tuple_insert<ResultTuple>(f.get(), replica::exception_variant{}));
-    }
-    std::exception_ptr eptr = f.get_exception();
+template<typename ResultTuple>
+static future<ResultTuple> encode_replica_exception_for_rpc(gms::feature_service& features, std::exception_ptr eptr) {
     if (features.typed_errors_in_read_rpc) {
         if (auto ex = replica::try_encode_replica_exception(eptr); ex) {
-            return make_ready_future<ResultTuple>(utils::tuple_insert<ResultTuple>(utils::make_default_rpc_tuple<SourceTuple>(), std::move(ex)));
+            ResultTuple encoded_ex = utils::make_default_rpc_tuple<ResultTuple>();
```
Comment (kbr-scylla) [inline service/storage_proxy.cc:134]: I would add a `static_assert` or a constraint here that `ResultTuple` contains `replica::exception_variant`, so we can be sure in compilation time that `std::get` below doesn't throw.

Comment (kbr-scylla) [reply service/storage_proxy.cc:134]: Note that the previously used `tuple_insert` did such checks (`constexpr auto match =...` followed by `static_assert(match.second == 1, ...)`)

**Review by kbr-scylla — COMMENTED** [review]
We should write a test.py test for this.

The test will require a feature in test.py framework which we don't have -- to browse the logs of nodes and detect messages -- similar to what dtest has.

Please create two follow-up issues:
- one for adding a feature to test.py for browsing node logs. For inspiration look at scylla-ccm: `mark_log`, `watch_log_for`, `grep_log`.
- second one for a regression test for this bug, which depends on the first issue. For the regression test I think it's enough to start a two node cluster -- we can use the `topology_custom` suite. Furthermore, we should only run this test in a single mode, like `dev` (definitely not `debug`).

**Comment by kbr-scylla** [comment]
Regarding the side effect question, I think changing "abort requested" to "unknown exception" during drain during upgrade will have minimal impact of users, if any, we don't know if they would even notice it. Not worth a cluster feature IMO, I agree with @piodul here. But I don't have a strong opinion.

But I think @avikivity has strong opinions about such cases. @avikivity please give your opinion here

**Comment by kostja** [comment]
Remember, if we didn't have Patryk join we would never find time to fix it. Let's not overdo the fix.

**Comment by kbr-scylla** [comment]
The node browsing feature would be useful in other contexts. If you want people to migrate from dtests completely then it's necessary.
The test itself is very easy to write if we have such a feature.

BTW. the issue is marked as P2, not P3/P4.

**Comment by kbr-scylla** [comment]
I don't require adding the test to this PR. I asked for follow-up issues.

File: service/storage_proxy.cc (hunk 2 above)
Comment (patjed41) [reply service/storage_proxy.cc]: Good catch. It made the complicated `to_future` redundant.

File: service/storage_proxy.cc (hunk 5 above)
Comment (patjed41) [reply service/storage_proxy.cc:134]: https://en.cppreference.com/w/cpp/utility/tuple/get
> 5-8) Extracts the element of the tuple `t` whose type is T. Fails to compile unless the tuple has exactly one element of that type.

We could still consider `static_assert` here so that we get a potentially nicer error, but I'm not sure if it's worth it.

**Comment by patjed41** [comment]
v2:
- set error message in `sync_point::handle_mutation_failed` in case of `abort_requested_exception`
- simplified `sync_point::handle_read` by removing `to_future`

File: service/storage_proxy.cc [hunk 6]
```diff
@@ -684,23 +690,21 @@ class storage_proxy::remote {
...
         };
-        auto to_future = [&](replica::stale_topology_exception e) {
-            return make_exception_future<typename decltype(do_query())::value_type>(std::move(e));
-        };
+
         const auto fence = fence_opt.value_or(fencing_token{});
 
         if (auto stale = _sp.apply_fence(fence, src_ip)) {
-            co_return co_await encode_replica_exception_for_rpc<Result>(p->features(), to_future(std::move(*stale)));
+            co_return co_await encode_replica_exception_for_rpc<Result>(p->features(), std::make_exception_ptr(*stale));
```
Comment (kbr-scylla) [inline service/storage_proxy.cc:703]: Why remove the `move`?

File: service/storage_proxy.cc [hunk 7]
```diff
@@ -684,23 +690,21 @@ class storage_proxy::remote {
...
         }
 
         auto f = co_await coroutine::as_future(do_query());
         tracing::trace(trace_state_ptr, "{} handling is done, sending a response to /{}", verb, src_ip);
 
         if (auto stale = _sp.apply_fence(fence, src_ip)) {
-            co_return co_await encode_replica_exception_for_rpc<Result>(p->features(), to_future(std::move(*stale)));
+            co_return co_await encode_replica_exception_for_rpc<Result>(p->features(), std::make_exception_ptr(*stale));
```
Comment (kbr-scylla) [inline service/storage_proxy.cc:710]: Why remove the `move`?

File: service/storage_proxy.cc (hunk 6 above)
Comment (patjed41) [reply service/storage_proxy.cc]: Fixed.

File: service/storage_proxy.cc (hunk 7 above)
Comment (patjed41) [reply service/storage_proxy.cc]: Fixed.

**Review by kbr-scylla — APPROVED** [review]
