### PR TITLE
message: messaging_service: topology independent connection settings for GOSSIP verbs

### LINKED ISSUE #11780: Decommission can fail due to concurrent fiber dropping RPC connections
The decommission operation sends a bunch of RPCs and opens RPC streams. These remote call may fail due to connection dropping by concurrently running fiber.

This concurrent dropping is caused by `storage_service::handle_state_normal`. Note that even if the operator first checks that every node is considered to be in NORMAL state from the POV of the decommissioned node before starting the operation, it does not guarantee that `handle_state_normal` has finished on this node - it may still be running.

`handle_state_normal` contains this call:
```cpp
    // Send joined notification only when this node was not a member prior to this
    if (!is_member) {
        co_await notify_joined(endpoint);
    }
```

`notify_joined` does:
```cpp
    co_await container().invoke_on_all([endpoint] (auto&& ss) {
        ss._messaging.local().remove_rpc_client_with_ignored_topology(netw::msg_addr{endpoint, 0});
        return ss._lifecycle_notifier.notify_joined(endpoint);
    });
```

and `remove_rpc_client_with_ignored_topology` drops all connections to this node, causing a concurrently running decommission to fail.

### LINKED ISSUE #11992: messaging_service: gossiper verbs should be encrypted regardless of topology knowledge
When a node creates a connection to another node in `messaging_service::get_rpc_client` it decides whether the connection should be encrypted by calculating a `must_encrypt` boolean (https://github.com/scylladb/scylladb/blob/d85f731478211c3952114247807eb424bb400b62/message/messaging_service.cc#L718). If inter-DC/rack encryption is enabled, we will not encrypt connections between nodes in the same DC/rack. However, a node might now know the topology of another node yet. In that case it will encrypt the connection even though they might be in the same DC/rack; there's no way to check the latter. (and the connection will eventually be dropped and replaced with a new connection once topology is known)

Similarly, when a node receives a connection attempt on unencrypted port and inter/DC-rack encryption is enabled, the node will verify whether the connection attempt comes from an address in the same DC-rack (`messaging_service::do_start_listen`; https://github.com/scylladb/scylladb/blob/d85f731478211c3952114247807eb424bb400b62/message/messaging_service.cc#L309). If not, it will reject the attempt. When writing this issue, on `master` branch, if the node does not have the topology of the sender's address, so it's not able to verify whether it's the same DC/rack, it will call `on_internal_error` (https://github.com/scylladb/scylladb/blob/d85f731478211c3952114247807eb424bb400b62/locator/token_metadata.cc#L1341; which is another problem that needs fixing; we should just drop these attempts if we don't know the topology).

As explained in https://github.com/scylladb/scylladb/pull/11942#issuecomment-1316817014: there is no guarantee that if a node X knows the topology of node Y, Y also knows the topology of X. So it may happen that X attempts unencrypted communication with Y, but Y will reject it. I obtained a situation where a node called `on_internal_error` (described in the previous paragraph) because it received unencrypted communication attempt from a node whose topology was yet unknown when trying to fix https://github.com/scylladb/scylladb/issues/11780, with https://github.com/scylladb/scylladb/pull/11942.

We need to guarantee that Y can eventually learn the topology of X. But we cannot give such guarantee if Y will reject any communication attempts from X! Perhaps Y could learn the topology of X from other nodes. But can we guarantee that Y can receive communication from other node? What if it told other nodes its topology, and then there was a failure which caused it not to learn the topology of others (dropped messages, a crash + restart before the knowledge was persisted etc.)?

The system is hard to reason about in the current state, and it's hard to prove if any such guarantees are given.

At some point there was the following piece of code in the definition of `must_encrypt` in `get_rpc_client`:
```
        // if we have dc/rack encryption but this is gossip, we should
        // use tls anyway, to avoid having mismatched ideas on which 
        // group we/client are in. 
        if (verb >= messaging_verb::GOSSIP_DIGEST_SYN && verb <= messaging_verb::GOSSIP_SHUTDOWN) {
            return true;
        }
```
i.e., when we create an RPC client due to a gossiper verb, we encrypt the communication (even though the nodes may live in the same DC/rack).

Later it was removed (https://github.com/scylladb/scylladb/commit/7bdad47de2f5ba4a0da220aff13e4c510782ee3e).

However, the check may be necessary for liveness: it's easy to see that it guarantees that every node can eventually learn every other node's topology through gossiping; nodes accept encrypted communication, they only reject unencrypted communication if they cannot verify that it's inter-DC/rack.

It's also not a performance problem to encrypt the RPC client used for gossiper verbs, because it doesn't contain any hot/data path verbs, only rare metadata verbs:
```cpp
static constexpr unsigned do_get_rpc_client_idx(messaging_verb verb) {
    switch (verb) {
    case messaging_verb::GOSSIP_DIGEST_SYN:
    case messaging_verb::GOSSIP_DIGEST_ACK:
    case messaging_verb::GOSSIP_DIGEST_ACK2:
    case messaging_verb::GOSSIP_SHUTDOWN:
    case messaging_verb::GOSSIP_ECHO:
    case messaging_verb::GOSSIP_GET_ENDPOINT_STATES:
    case messaging_verb::GET_SCHEMA_VERSION:
    case messaging_verb::GROUP0_PEER_EXCHANGE:
    case messaging_verb::GROUP0_MODIFY_CONFIG:
    case messaging_verb::GET_GROUP0_UPGRADE_STATE:
        return 0;
```

Finally, the check combined with https://github.com/scylladb/scylladb/pull/11942 will let me fix https://github.com/scylladb/scylladb/issues/11780.

### PR DESCRIPTION
**Pull request by kbr-**
The gossip verbs are used to learn about topology of other nodes. If inter-dc/rack encryption is enabled, the knowledge of topology is necessary to decide whether it's safe to send unencrypted messages to nodes (i.e., whether the destination lies in the same dc/rack).

The logic in `messaging_service::get_rpc_client`, which decided whether a connection must be encrypted, was this (given that encryption is enabled): if the topology of the peer is known, and the peer is in the same dc/rack, don't encrypt. Otherwise encrypt.

However, it may happen that node A knows node B's topology, but B doesn't know A's topology. A deduces that B is in the same DC and rack and tries sending B an unencrypted message. As the code currently stands, this would cause B to call `on_internal_error`. This is what I encountered when attempting to fix #11780.

To guarantee that it's always possible to deliver gossiper verbs (even if one or both sides don't know each other's topology), and to simplify reasoning about the system in general, choose connection settings that are independent of the topology - for the connection used by gossiper verbs (other connections are still topology-dependent and use complex logic to handle the situation of unknown-and-later-known topology).

This connection only contains 'rare' and 'cheap' verbs, so it's not a performance problem to always encrypt it (given that encryption is configured). And this is what already was happening in the past; it was at some point removed during topology knowledge management refactors. We just bring this logic back.

Fixes #11992.

Inspired by xemul/scylla@45d48f3d02fd48c6d186cc955cf83d747ac080b9.

### CODE REVIEW

File: message/messaging_service.cc [hunk 1]
```diff
@@ -753,22 +776,21 @@ shared_ptr<messaging_service::rpc_protocol_client_wrapper> messaging_service::ge
...
+        if (_cfg.compress == compress_what::all || idx == TOPOLOGY_INDEPENDENT_IDX) {
             return true;
         }
 
-        return !is_same_dc(id.addr);
+        return !has_topology() || !is_same_dc(id.addr);
     }();
 
     auto must_tcp_nodelay = [&] {
-        if (idx == 0) {
```
Comment (xemul) [inline message/messaging_service.cc:764]: This check has nothing to do with "topology independenc~~e da~~y ". It's just to make gossiper (see e.g. #11490) work smoother

File: message/messaging_service.cc [hunk 2]
```diff
@@ -753,22 +776,21 @@ shared_ptr<messaging_service::rpc_protocol_client_wrapper> messaging_service::ge
             return false;
         }
 
-        if (_cfg.compress == compress_what::all || !has_topology()) {
+        // See comment above `TOPOLOGY_INDEPENDENT_IDX`.
+        if (_cfg.compress == compress_what::all || idx == TOPOLOGY_INDEPENDENT_IDX) {
```
Comment (xemul) [inline message/messaging_service.cc:780]: Why does compression has anything to do with this? If A knows B's topo, but not the vice-versa, would B's compressed message sent to A make any harm?

Comment (kbr-) [reply message/messaging_service.cc:780]: It's done to simplify, as explained at `TOPOLOGY_INDEPENDENT_IDX` comment:
```
// And since we fixed a topology-independent setting for encryption and tcp_nodelay,
// to keep things simple, we also fix a setting for compression. This allows this RPC client
// to be established without checking the topology (which may not be known anyway
// when we first start gossiping).
```

This allows us to avoid the RPC dropping for IDX=0 altogether.

File: message/messaging_service.cc (hunk 1 above)
Comment (kbr-) [reply message/messaging_service.cc:764]: I mention tcp_nodelay at the TOPOLOGY_INDEPENDENT_IDX comment too.

**Comment by kbr-** [comment]
It appears that the only controversial thing in this patch is compression settings.

The main goal of the patch was to make encryption topology-independent for idx=0 rpc client. tcp_nodelay already is. So compression is the last thing. So I decided to make it consistent with the other two settings so that all settings, including compression, are topology-independent. Thanks to this we don't need to drop the RPC client later.

Advantages:
- the logic is simpler and more consistent, compression does not become an edge case
- we don't need to drop the RPC client for idx=0 later, so robustness is improved for RPCs in the idx=0 group
Disadvantages:
- potentially compressing inter-DC messages for idx=0 even though it's not needed (but the messages are rare and small so it probably doesn't matter anyway)

Compression could remain topology-dependent. It will be kind of awkward - dropping the RPC client just so it can be recreated with different compression settings, which doesn't really matter for this group of verbs. But we can do it.

I don't have a strong opinion on this.

@xemul how do we proceed?

**Comment by xemul** [comment]
I'd go with static configuration for index 0

**Comment by kbr-** [comment]
@xemul do you think the patch is ready for merging then?

**Comment by xemul** [comment]
Yes, I was going to merge it as a part of #11942
