### PR TITLE
raft topology: support --ignore-dead-nodes in removenode and replace

### LINKED ISSUE #15025: raft topology: implement `--ignore-dead-nodes` for removenode and replace
In gossiper mode it's possible to remove a node in presence of other dead nodes. This is necessary -- otherwise the cluster would be unable to proceed with topology operations as soon as two nodes die permanently.

This is not implemented yet in Raft topology.

For the first release we need a simple implementation that's similar to gossiper-mode behavior: assume that the nodes passed to `--ignore-dead-nodes` are permanently dead, we don't need to synchronize with them, and just ignore them when broadcasting commands to the cluster such as during `global_token_metadata_barrier`.

---

In the future we may aim for something more complicated, such as temporarily quarantining ignored nodes. But it's an open problem how to unquarantine nodes that we've been ignoring during topology operations. Bringing them up to the newest topology is not enough, because they may be missing some data; it's incorrect to serve reads from them. We basically need to "rebootstrap" these nodes (at least partially) -- i.e. start doing additional writes to them (while they don't yet serve reads), then stream whatever data they are missing; only after they obtain all missing pieces, it's safe to turn them back to normal members.

But for the initial implementation and release, simulating gossiper behavior should be enough.

cc @gleb-cloudius @tgrabiec @kostja

### PR DESCRIPTION
**Pull request by patjed41**
We add support for `--ignore-dead-nodes` in `raft_removenode` and `--ignore-dead-nodes-for-replace` in `raft_replace`. For now, we allow passing only host ids of the ignored nodes. Supporting IPs is currently impossible because `raft_address_map` doesn't provide a mapping from IP to a host id.

The main steps of the implementation are as follows:
- add the `ignore_nodes` column to `system.topology`,
- set the `ignore_nodes` value of the topology mutation in `raft_removenode` and `raft_replace`,
- extend `service::request_param` with alternative types that allow storing a set of ids of the ignored nodes,
- load `ignore_nodes` from `system.topology` into `request_param` in `system_keyspace::load_topology_state`,
- add `ignore_nodes` to `exclude_nodes` in `topology_coordinator::exec_global_command`,
- pass `ignore_nodes` to `replace_with_repair` and `remove_with_repair` in `storage_service::raft_topology_cmd_handler`.

Additionally, we add `test_raft_ignore_nodes.py` with two tests that verify the added changes.

Fixes #15025

### CODE REVIEW

File: db/system_keyspace.cc [hunk 1]
```diff
@@ -2526,6 +2535,11 @@ future<service::topology> system_keyspace::load_topology_state() {
             rebuild_option = row.get_as<sstring>("rebuild_option");
         }
 
+        std::unordered_set<raft::server_id> ignored_ids;
```
Comment (kbr-scylla) [inline db/system_keyspace.cc:2538]: > In system_keyspace::load_topology_state, we don't need to emplace
ignored_ids into ret.req_param if a row contains topology_request.
This parameter will only be used after deleting topology_request.

But I see that you emplace it unconditionally nevertheless. Is that paragraph of the commit message important in any way?

File: service/storage_service.cc [hunk 2]
```diff
@@ -960,6 +960,16 @@ class topology_coordinator {
...
     }
 
+    std::unordered_set<raft::server_id> parse_ignore_nodes(const node_to_work_on& node) {
+        if (node.rs->state == node_state::removing) {
+            return std::get<std::unordered_set<raft::server_id>>(node.req_param.value());
+        }
+        if (node.rs->state == node_state::replacing) {
+            return std::get<replace_param>(node.req_param.value()).ignored_ids;
+        }
+        return {};
```
Comment (kbr-scylla) [inline service/storage_service.cc:970]: Maybe we should do `on_internal_error` here for now since we're not supposed to call `parse_ignore_nodes` in situations other than `removing`/`replacing`?

File: service/storage_service.cc [hunk 3]
```diff
@@ -5747,12 +5747,20 @@ future<raft_topology_cmd_result> storage_service::raft_topology_cmd_handler(shar
                         // Bootstrap did not complete yet, but streaming did
                     } else {
                         co_await retrier(_bootstrap_result, coroutine::lambda([&] () ->future<> {
+                            assert(_topology_state_machine._topology.req_param.contains(raft_server.id()));
                             if (is_repair_based_node_ops_enabled(streaming::stream_reason::replace)) {
-                                co_await _repair.local().replace_with_repair(get_token_metadata_ptr(), rs.ring.value().tokens, {});
+                                std::unordered_set<gms::inet_address> ignored_ips;
+                                for (const auto& id : std::get<replace_param>(_topology_state_machine._topology.req_param[raft_server.id()]).ignored_ids) {
+                                    auto ip = _group0->address_map().find(id);
```
Comment (kbr-scylla) [inline service/storage_service.cc:5754]: Please live a FIXME with a reference to #6403 (we should not need to do this translation here)

File: service/storage_service.cc [hunk 4]
```diff
@@ -5780,20 +5788,29 @@ future<raft_topology_cmd_result> storage_service::raft_topology_cmd_handler(shar
...
                                 as->request_abort();
                             }
                         });
                         if (is_repair_based_node_ops_enabled(streaming::stream_reason::removenode)) {
-                            auto ops = seastar::make_shared<node_ops_info>(node_ops_id::create_random_id(), as, std::list<gms::inet_address>());
-                            // FIXME: ignore node list support
+                            assert(_topology_state_machine._topology.req_param.contains(id));
+                            std::list<gms::inet_address> ignored_ips;
+                            for (const auto& ignored_id : std::get<std::unordered_set<raft::server_id>>(_topology_state_machine._topology.req_param[id])) {
+                                auto ip = _group0->address_map().find(ignored_id);
```
Comment (kbr-scylla) [inline service/storage_service.cc:5807]: Same FIXME as above

File: service/storage_service.cc [hunk 5]
```diff
@@ -5780,20 +5788,29 @@ future<raft_topology_cmd_result> storage_service::raft_topology_cmd_handler(shar
...
                         auto as = make_shared<abort_source>();
                         auto sub = _abort_source.subscribe([as] () noexcept {
                             if (!as->abort_requested()) {
                                 as->request_abort();
                             }
                         });
                         if (is_repair_based_node_ops_enabled(streaming::stream_reason::removenode)) {
-                            auto ops = seastar::make_shared<node_ops_info>(node_ops_id::create_random_id(), as, std::list<gms::inet_address>());
-                            // FIXME: ignore node list support
+                            assert(_topology_state_machine._topology.req_param.contains(id));
```
Comment (kbr-scylla) [inline service/storage_service.cc:5804]: Use `on_internal_error` instead

File: service/storage_service.cc [hunk 6]
```diff
@@ -5747,12 +5747,20 @@ future<raft_topology_cmd_result> storage_service::raft_topology_cmd_handler(shar
                         // Bootstrap did not complete yet, but streaming did
                     } else {
                         co_await retrier(_bootstrap_result, coroutine::lambda([&] () ->future<> {
+                            assert(_topology_state_machine._topology.req_param.contains(raft_server.id()));
```
Comment (kbr-scylla) [inline service/storage_service.cc:5750]: Use `on_internal_error` instead

File: service/storage_service.cc [hunk 7]
```diff
@@ -2079,6 +2084,19 @@ future<> storage_service::raft_state_monitor_fiber(raft::server& raft, cdc::gene
 
 
 future<> storage_service::raft_replace(raft::server& raft_server, raft::server_id replaced_id, gms::inet_address replaced_ip) {
+    auto ignore_nodes_strs = utils::split_comma_separated_list(_db.local().get_config().ignore_dead_nodes_for_replace());
+    std::unordered_set<raft::server_id> ignored_ids;
+    for (const sstring& n : ignore_nodes_strs) {
+        raft::server_id ignored_id;
+        // FIXME: IPs should be supported, but the current implementation of raft_address_map doesn't allow this.
```
[the remark this answers is not in the document]
Comment (patjed41) [reply service/storage_service.cc:2102]: Sure, but I'd like to know if there is any expected solution for this FIXMEs to provide more information in the issue ticket. Is it simply adding a new member function -- `find_by_inet_address` -- to `raft_address_map` together with some unit tests?

By the way, I left two TODOs in `test_raft_ignore_nodes.py` that depend on these FIXMEs and should be done together with them.

[the remark this answers is not in the document]
Comment (kbr-scylla) [reply service/storage_service.cc:2102]: > Is it simply adding a new member function -- find_by_inet_address -- to raft_address_map together with some unit tests?

That is one of the alternatives.
Although we should probably do the translation the same way regular removenode does, IIRC it's done using `locator::topology` somehow.

Another alternative is to update the documentation that we no longer support passing IP addresses to this option. However that's a bit problematic because there was no deprecation period.

Best would be a mix of both: update the documentation that passing IPs is deprecated, and do the translation here. Two releases later we would update the documentation that passing IPs is no longer supported and remove the translation.

Comment (gleb-cloudius) [inline service/storage_service.cc:2102]: We can also deprecate the use of IPs with consistent topology.

File: db/system_keyspace.cc (hunk 1 above)
Comment (gleb-cloudius) [reply db/system_keyspace.cc:2538]: The code emplaces an empty set in this case, but why the complication?

**Review by gleb-cloudius — APPROVED** [review]
LGTM. But missing the isolation of ignored nodes. Not a merge blocker, but a TODO item that needs to be addressed at some point.

File: service/storage_service.cc [hunk 8]
```diff
@@ -2089,14 +2107,20 @@ future<> storage_service::raft_replace(raft::server& raft_server, raft::server_i
...
         auto guard = co_await _group0->client().start_operation(&_abort_source);
 
         auto it = _topology_state_machine._topology.normal_nodes.find(replaced_id);
         if (it == _topology_state_machine._topology.normal_nodes.end()) {
             throw std::runtime_error(::format("Cannot replace node {}/{} because it is not in the 'normal' state", replaced_ip, replaced_id));
         }
 
+        for (const auto& ignored_id : ignored_ids) {
+            if (!_topology_state_machine._topology.find(ignored_id)) {
+                throw std::runtime_error(::format("raft topology replace: ignored node {} is not found in the cluster", ignored_id));
```
[the remark this answers is not in the document]
Comment (patjed41) [reply service/storage_service.cc]: > Is this the same behavior as for old replace?

I think so. The old replace also throws `runtime_error` if an ignored node is not in the cluster (see `storage_service::parse_node_list`). Only the error message is different.

> BTW let's remove "raft topology " prefix from errors that we throw through user APIs ("raft topology" is an implementation detail). It's fine to keep it in log messages.

I changed the errors added by me. What about the ones already present in `raft_removenode`? Should I fix them in another PR, since they are unrelated?

File: service/topology_state_machine.hh [hunk 9]
```diff
@@ -46,7 +46,12 @@ enum class topology_request: uint16_t {
     rebuild
 };
 
-using request_param = std::variant<raft::server_id, sstring, uint32_t>;
+struct replace_param {
```
[the remark this answers is not in the document]
Comment (patjed41) [reply service/topology_state_machine.hh:53]: > Can you also create a struct for the `std::unordered_set<raft::server_id>`?

Done.

> As a follow-up, we should also create structs for the `sstring` and `uint32_t`.

I can work on that.

File: db/system_keyspace.cc (hunk 1 above)
Comment (patjed41) [reply db/system_keyspace.cc:2538]: > The code emplaces an empty set in this case, but why the complication?

Right, it's not worth doing it. I changed it to emplace `ignored_ids` for the replace operation in both cased.

The paragraph still applies to the removenode operation, but I think it brings more confusion than help, so I removed it.

File: service/storage_service.cc (hunk 5 above)
Comment (patjed41) [reply service/storage_service.cc]: Done.

File: service/storage_service.cc (hunk 7 above)
Comment (patjed41) [reply service/storage_service.cc:2102]: I added this to the FIXME description.

File: service/storage_service.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (kbr-scylla) [reply service/storage_service.cc]: > Should I fix them in another PR, since they are unrelated?

Sure, after this PR is merged.

**Comment by patjed41** [comment]
v2:
- introduced `service::removenode_param`
- removed "raft topology" prefixes from the errors thrown in `raft_removenode` and `raft_replace`
- changed `assert`s to `on_internal_error`s in `storage_service::raft_topology_cmd_handler`
- added 2 FIXMEs in `storage_service::raft_topology_cmd_handler` about `id -> IP` translation
- changed descriptions of the FIXMEs in `raft_removenode` and `raft_replace`
- fixed some typos

File: service/storage_service.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (patjed41) [reply service/storage_service.cc:2102]: I created the follow-up issue -- #15126.
