### PR TITLE
Guard tables in compaction tasks

### LINKED ISSUE #16305: cleanup_test.TestCleanup.test_drop_table_during_cleanup fails due to seastar::gate_closed_exception logged in logging message
we drop tables while performing cleanup to them in parallel. but there are chances that the operation hits a table whose `gate` is closed, and hence the error in logging message.

```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-12-06 06:42:23,055 [shard 0:strm] api - force_keyspace_cleanup: keyspace=ks tables={table{name=cf2, id=91e455d0-9402-11ee-81cc-18cc756a1466}, table{name=cf1, id=88f5f550-9402-11ee-81cc-18cc756a1466}, table{name=cf0, id=80d60860-9402-11ee-81cc-18cc756a1466}} failed: seastar::gate_closed_exception (gate closed)', 'ERROR 2023-12-06 06:42:23,003 [shard 0:strm] task_manager - Failed force_keyspace_cleanup of ks.cf0: seastar::gate_closed_exception (gate closed)'])]"
...
```
see also https://jenkins.scylladb.com/job/scylla-master/job/next/6900/testReport/junit/cleanup_test/TestCleanup/Build___x86___dtest___test_drop_table_during_cleanup/

### PR DESCRIPTION
**Pull request by bhalevy**
Currently, if a compaction function enters the table
or compaction_group async_gate, we can't stop it
on the table/compaction_group stop path as they co_await
their respective async_gate.close().

This series introduces a table_ptr smart pointer to guards
the table object by entering its async_gate, and
it also defers awaiting the gate.close future
till after stopping ongoing compaction so that
closing the gate will prevent starting new compactions
while ongoing compaction can be stopped and finally
awaiting the close() future will wait for them to
unwind and exit the gate after being stopped.

Fixes #16305

### CODE REVIEW

File: replica/database.hh [hunk 1]
```diff
@@ -1180,6 +1180,33 @@ public:
     friend class compaction_group;
 };
 
+// Smart table pointer that guards the table object
+// while it's being accessed asynchronously
+class table_ptr {
```
Comment (tchaikov) [inline replica/database.hh:1185]: nit, i'd suggest rename it to `table_holder` . and add a `hold()` helper to `table` class. the helper constructors calling into `find_column_family()` are nice but not quite necessary.

File: compaction/task_manager_module.cc [hunk 2]
```diff
@@ -193,7 +193,8 @@ future<> run_on_table(sstring op, replica::database& db, std::string keyspace, t
     std::exception_ptr ex;
     tasks::tmlogger.debug("Starting {} on {}.{}", op, keyspace, ti.name);
     try {
-        co_await func(db.find_column_family(ti.id));
+        auto tptr = replica::table_ptr(db, ti.id);
```
Comment (tchaikov) [inline compaction/task_manager_module.cc:196]: nit, the commit message reads:

> To ensure the table will be dropped while ...

i think it misses a "not".

**Review by tchaikov — APPROVED** [review]
lgtm modulo some nits.

File: replica/table.cc [hunk 3]
```diff
@@ -1073,10 +1073,14 @@ table::stop() {
     if (_async_gate.is_closed()) {
         co_return;
     }
-    co_await _async_gate.close();
+    // Allow `compaction_manager::stop` to stop ongoing compactions
```
Comment (Deexie) [inline replica/table.cc:1089]: `compaction_group::stop`

File: replica/table.cc [hunk 4]
```diff
@@ -1073,10 +1073,14 @@ table::stop() {
...
+    // while they may still hold the _async_gate
+    // entered in `compaction_manager::start_compaction`
```
Comment (Deexie) [inline replica/table.cc:1091]: `compaction_manager::start_compaction` enters `compaction_state::gate`, but here `table::_async_gate` is closed

File: replica/table.cc [hunk 5]
```diff
@@ -1654,9 +1658,13 @@ future<> compaction_group::stop() noexcept {
     if (_async_gate.is_closed()) {
         co_return;
     }
-    co_await _async_gate.close();
+    // Allow `compaction_manager::remove` to stop ongoing compactions
+    // while they may still hold the _async_gate
+    // entered in `compaction_manager::start_compaction`
```
Comment (Deexie) [inline replica/table.cc:1676]: ditto

File: replica/table.cc (hunk 4 above)
Comment (bhalevy) [reply replica/table.cc:1091]: right, I'll revise the comment

File: replica/table.cc (hunk 5 above)
Comment (bhalevy) [reply replica/table.cc:1676]: no, here it is the compaction_group::_async_gate.
The previous mention was copy-pasted

Comment (Deexie) [reply replica/table.cc:1676]: Yes, but it's still a different gate than the one entered in `compaction_manager::start_compaction`

File: replica/database.hh (hunk 1 above)
Comment (bhalevy) [reply replica/database.hh]: renamed in v2

File: compaction/task_manager_module.cc (hunk 2 above)
Comment (bhalevy) [reply compaction/task_manager_module.cc]: fixed in v2

File: replica/table.cc (hunk 3 above)
Comment (bhalevy) [reply replica/table.cc]: fixed in v2

File: replica/table.cc (hunk 4 above)
Comment (bhalevy) [reply replica/table.cc]: simplified the comment in v2

File: replica/table.cc (hunk 5 above)
Comment (bhalevy) [reply replica/table.cc]: You're right.
Dropped this hunk changing to compacton_group::stop in v2

**Comment by bhalevy** [comment]
In v2 ([7843025](https://github.com/scylladb/scylladb/commit/7843025a53fc808120c4f28e578a59817214ce04)):
- table: stop: allow compactions to be stopped while closing async_gate:
  - kept only change in table::stop
  - simplified comment
- table: add table_holder and hold method
  - table_ptr renamed to table_holder
  - dropped db related constructors
  - find_column_family is done by caller (`run_on_table`)
- compaction: run_on_table: hold table
  - adapted to previous patch

**Review by Deexie — APPROVED** [review]
LGTM

**Review by denesb — APPROVED** [review]
