### PR TITLE
sstable_loader: fix cross-shard resource cleanup in download_task_impl 

### LINKED ISSUE #22759: test_backup_restore_with_nodetool assertion failed during shutdown: shared_ptr accessed on non-owner cpu
Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/382/artifact/logs-full.debug.001/1739082810764_backup_restore_object_storage_tests.py%3A%3ATestBackupRestoreObjectStorage%3A%3Atest_backup_restore_with_nodetool/node1.log

```
INFO  2025-02-09 06:33:14,074 [shard 0:main] init - Scylla version 2025.2.0~dev-0.20250208.93f53f4eb824 with build-id d4a1db3a8fa036a6a118ef5004d7288209027344 starting ...
...
INFO  2025-02-09 06:33:27,757 [shard 0:main] compaction_manager - Asked to stop
INFO  2025-02-09 06:33:27,757 [shard 0:main] view_update_generator - Terminating background fiber
WARN  2025-02-09 06:33:27,758 [shard 0:strm] gossip - failure_detector_loop: Got error in the loop, live_nodes={127.0.94.2}: seastar::sleep_aborted (Sleep is aborted)
INFO  2025-02-09 06:33:27,758 [shard 0:strm] gossip - failure_detector_loop: Finished main loop
INFO  2025-02-09 06:33:27,758 [shard 0:strm] view_update_generator - leaving 0 unstaged sstables unprocessed
ERROR 2025-02-09 06:33:27,758 [shard 0:strm] seastar - shared_ptr accessed on non-owner cpu, at: 0x347c505 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x444b1c4 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x444ae46 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x444c861 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x444f07f /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x34035ca /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x3403df0 0x957efbe 0x9584576 0x9581c4a 0x959f9a6 0x37560d9 0x3755f73 0x3755e0a 0x9a0d885 0x9a0d1a0 0x99a3bbd 0x99c0ff3 0x36843be 0x368408c 0x3683cc4 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x361a09d /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x36256cc /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x362a68b /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x3628816 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x31d77ca /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x31d4c40 0x351cc1d 0x351a1b7 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x3247 /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x330a 0x3435b64
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0, in scheduling group streaming.
Backtrace:
  0x347c505
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x37a1a64
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x37a1732
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x35f3bf4
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x362bc52
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x36fd879
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x36fdb75
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x36fd9bf
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x1a04f
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x73113
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x19f9d
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x1941
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x3403dfa
  0x957efbe
  0x9584576
  0x9581c4a
  0x959f9a6
  0x37560d9
  0x3755f73
  0x3755e0a
  0x9a0d885
  0x9a0d1a0
  0x99a3bbd
  0x99c0ff3
  0x36843be
  0x368408c
  0x3683cc4
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x361a09d
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x36256cc
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x362a68b
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x3628816
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x31d77ca
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libseastar.so+0x31d4c40
  0x351cc1d
  0x351a1b7
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x3247
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/93f53f4eb82497a32ed89e32f4a88cdff5b0d123/libreloc/libc.so.6+0x330a
  0x3435b64
```

Decoded:
```
[Backtrace #0]
__interceptor_backtrace at /mnt/clang_build/llvm-project-x86_64/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4369
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:69
seastar::backtrace_buffer::append_backtrace() at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:805
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:838
seastar::print_with_backtrace(char const*, bool) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:850
seastar::sigabrt_action() at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:3994
seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:3971
seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:3966
/data/scylla-s3-reloc.cache/by-build-id/d4a1db3a8fa036a6a118ef5004d7288209027344/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=515c33a35f41020661fea8ac4eb995e26ccd6b00, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_fatal_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/on_internal_error.cc:80
seastar::shared_ptr<stream_progress>::~shared_ptr() at ././seastar/include/seastar/core/shared_ptr.hh:562
void std::_Destroy_aux<false>::__destroy<seastar::shared_ptr<stream_progress>*>(seastar::shared_ptr<stream_progress>*, seastar::shared_ptr<stream_progress>*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_construct.h:88
 (inlined by) void std::_Destroy<seastar::shared_ptr<stream_progress>*>(seastar::shared_ptr<stream_progress>*, seastar::shared_ptr<stream_progress>*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_construct.h:195
 (inlined by) void std::_Destroy<seastar::shared_ptr<stream_progress>*, seastar::shared_ptr<stream_progress> >(seastar::shared_ptr<stream_progress>*, seastar::shared_ptr<stream_progress>*, std::allocator<seastar::shared_ptr<stream_progress> >&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/alloc_traits.h:993
 (inlined by) std::vector<seastar::shared_ptr<stream_progress>, std::allocator<seastar::shared_ptr<stream_progress> > >::~vector() at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_vector.h:735
sstables_loader::download_task_impl::~download_task_impl() at ././sstables_loader.cc:575
seastar::shared_ptr_count_for<sstables_loader::download_task_impl>::~shared_ptr_count_for() at ././seastar/include/seastar/core/shared_ptr.hh:485
seastar::internal::lw_shared_ptr_accessors_esft<tasks::task_manager::task>::dispose(seastar::lw_shared_ptr_counter_base*) at ././tasks/task_manager.hh:117
std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >::~pair() at ././seastar/include/seastar/core/shared_ptr.hh:324
std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >, false> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >, false>*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_construct.h:88
std::_Hashtable<utils::tagged_uuid<tasks::task_id_tag>, std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >, std::allocator<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> > >, std::__detail::_Select1st, std::equal_to<utils::tagged_uuid<tasks::task_id_tag> >, std::hash<utils::tagged_uuid<tasks::task_id_tag> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_erase(unsigned long, std::__detail::_Hash_node_base*, std::__detail::_Hash_node<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >, false>*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable.h:2417
std::_Hashtable<utils::tagged_uuid<tasks::task_id_tag>, std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >, std::allocator<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> > >, std::__detail::_Select1st, std::equal_to<utils::tagged_uuid<tasks::task_id_tag> >, std::hash<utils::tagged_uuid<tasks::task_id_tag> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_erase(std::integral_constant<bool, true>, utils::tagged_uuid<tasks::task_id_tag> const&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable.h:2460
std::_Hashtable<utils::tagged_uuid<tasks::task_id_tag>, std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> >, std::allocator<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> > >, std::__detail::_Select1st, std::equal_to<utils::tagged_uuid<tasks::task_id_tag> >, std::hash<utils::tagged_uuid<tasks::task_id_tag> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase(utils::tagged_uuid<tasks::task_id_tag> const&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/hashtable.h:1028
 (inlined by) std::unordered_map<utils::tagged_uuid<tasks::task_id_tag>, seastar::lw_shared_ptr<tasks::task_manager::task>, std::hash<utils::tagged_uuid<tasks::task_id_tag> >, std::equal_to<utils::tagged_uuid<tasks::task_id_tag> >, std::allocator<std::pair<utils::tagged_uuid<tasks::task_id_tag> const, seastar::lw_shared_ptr<tasks::task_manager::task> > > >::erase(utils::tagged_uuid<tasks::task_id_tag> const&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unordered_map.h:771
 (inlined by) tasks::task_manager::unregister_task(utils::tagged_uuid<tasks::task_id_tag>) at ././tasks/task_manager.cc:795
 (inlined by) tasks::task_manager::module::unregister_task(utils::tagged_uuid<tasks::task_id_tag>) at ././tasks/task_manager.cc:597
seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>::direct_vtable_for<seastar::future<void>::then_wrapped_maybe_erase<true, void, tasks::task_manager::task::start()::$_1>(tasks::task_manager::task::start()::$_1&&)::{lambda(seastar::future<void>&&)#1}>::call(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> const*, seastar::future<void>&&) at ././tasks/task_manager.cc:332
seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}::operator()() const at ././seastar/include/seastar/util/noncopyable_function.hh:215
_ZN7seastar8futurizeINS_6futureIvEEE22satisfy_with_result_ofITkSt9invocableZZNS2_17then_wrapped_nrvoIS2_NS_20noncopyable_functionIFS2_OS2_EEEEENS0_IT_E4typeEOT0_ENKUlONS_8internal22promise_base_with_typeIvEERS9_ONS_12future_stateINSF_9monostateEEEE_clESI_SJ_SN_EUlvE_EEvSI_OSA_ at ././seastar/include/seastar/core/future.hh:1996
seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&) const at ././seastar/include/seastar/core/future.hh:1543
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ././seastar/include/seastar/core/future.hh:727
```

### PR DESCRIPTION
**Pull request by tchaikov**
This PR addresses two related issues in our task system:

1. Prepares for asynchronous resource cleanup by converting release_resources() to a coroutine. This refactoring enables future improvements in how we handle resource cleanup.

2. Fixes a cross-shard resource cleanup issue in the SSTable loader where destruction of per-shard progress elements could trigger "shared_ptr accessed on non-owner cpu" errors in multi-shard environments. The fix uses coroutines to ensure resources are released on their owner shards.

Fixes #22759

---

this change addresses a regression introduced by d815d7013cb7c74dfb265f3fe920a3c5b2226646, which is contained by 2025.1 and master branches. so it should be backported to 2025.1 branch.

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]
LGTM

@Deexie please review too

File: sstables_loader.cc [hunk 1]
```diff
@@ -620,6 +620,12 @@ class sstables_loader::download_task_impl : public tasks::task_manager::task::im
         return tasks::is_abortable::yes;
     }
 
+    virtual future<> release_resources() noexcept override {
```
Comment (Deexie) [inline sstables_loader.cc:623]: We call `release_resources` when the task is complete, but it may still be kept in task manager. If users check the status of the finished task they will see 0/0 progress. 

Please save the final progress here and adjust `get_progress()` accordingly.

**Comment by tchaikov** [comment]
v2:

- preserve the final progress before cleanup the per-shard progress, and return the final progress if it is available.

File: sstables_loader.cc [hunk 2]
```diff
@@ -582,6 +582,7 @@ class sstables_loader::download_task_impl : public tasks::task_manager::task::im
     sstables_loader::stream_scope _scope;
     std::vector<sstring> _sstables;
     std::vector<shared_ptr<stream_progress>> _progress_per_shard;
```
Comment (xemul) [inline sstables_loader.cc:584]: Is it possible to make it `std::vector<foreign_ptr<shared_ptr<stream_progress>>>` instead?

Comment (tchaikov) [reply sstables_loader.cc:584]: I tried. But abandoned the work in progress branch, because of the limit of foreign_ptr. I was not able to come up with an acceptable API interface allowing me to pass a smart pointer down to the delegated API.

Comment (avikivity) [reply sstables_loader.cc:584]: What about sharded<stream_progress>?

Comment (tchaikov) [reply sstables_loader.cc]: > What about sharded<stream_progress>?

good idea! but instead of using `stream_progress`, i am using `shared_ptr<stream_progress>`. let me quote from the comment in the code to explain the rationales:
```c++
        // Wrap stream_progress in a smart pointer to enable polymorphism.
        // This allows derived progress types to be passed down for per-tablet
        // progress tracking while maintaining the base interface.
```

**Comment by tchaikov** [comment]
v3:

- instead of using a `vector<stream_progress>` , use `shaded<progress_holder>` to manager the lifecycle of the per-shard progress. simpler this way.

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15181/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3356/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14490/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6471/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15181/)
> #### Failed Tests (6/37931):
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15181/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15181/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15181/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15181/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15181/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15181/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3)
> 
> 
#22799

**Review by xemul — APPROVED** [review]

File: sstables_loader.cc [hunk 3]
```diff
@@ -678,11 +679,10 @@ future<> sstables_loader::download_task_impl::run() {
             } catch (...) {
             }
         });
+        co_await _progress_per_shard.start();
```
Comment (Deexie) [inline sstables_loader.cc:682]: If a user requests task status between the moment a task is registered in task manager and this point, we will do `map_reduce` on uninitialized `_progress_per_shard` (line 641)

Comment (tchaikov) [reply sstables_loader.cc:696]: because neither `sharded<>` nor `task::impl` provides the facility to track if the progress is started, i added an enum to track the status of the progress.

**Review by Deexie — APPROVED** [review]
LGTM

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15238/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3394/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6510/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14530/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15238/)
> #### Failed Tests (7/38013):
> 
>     * [test_delete_elements_from_a_set](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/alternator_tests/TesterAlternator/Tests___dtest_with_topology_changes___test_delete_elements_from_a_set) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_elements_from_a_set)

#22396

> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2)
> 
>     * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15238/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3)
> 

#22799

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15256/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6517/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3401/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14537/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15256/)
> 
> #### Failed Tests (6/38024):
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15256/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.1)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15256/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.2)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15256/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.dev.3)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15256/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.1)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15256/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.2)
> * [cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15256/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_cassandra_tests_validation_entities_uf_types_test_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.cassandra_tests/validation/entities/uf_types_test.release.3)
> 

#22799

**Comment by tchaikov** [comment]
> #### 🔴 CI State: UNSTABLE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15274/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3411/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6528/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14547/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15274/)
> #### Build Details:
> 

#22628

**Comment by tchaikov** [comment]
v5:

- rebased onto master HEAD to pick up the workaround of #22799

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?
