### PR TITLE
[backport 2025.1] alternator: fix schema "concurrent modification" errors

### LINKED ISSUE #13152: Alternator: schema modifications need to retry in a loop
Alternator code which modifies the schema includes `executor::create_table()`, `executor::delete_table()`, `executor::update_table()`, and `db::modify_tags()` (the latter is used by TagResource, UntagResource and UpdateTimeToLive).

All these functions use the idiom starting with `mm.start_group0_operation()` and ending with `mm.announce()`.

But as far as I understood (CC @gleb-cloudius), this idiom is a type of "optimistic locking", and the proper way to use it is in a loop: In case of contention between multiple modifications on multiple coordinators, `mm.announce()` may fail and we need to do the whole thing from start_group0_operation to announce (lock, read and write), again.

Before fixing this issue, we should write a test that reproduces the problem. The Alternator tests that I already have for concurrent schema modifications - `test_tag.py::test_concurrent_tag` and `test_table.py::test_concurrent_create_and_delete_table`, are single-node tests so can't reproduce **this** bug. To reproduce this bug, we'll need a distributed test (probably in dtest).

If I understand this issue correctly (we'll know better once we write the test), this is a fairly low-priority bug because at worst it will cause some schema operations to fail on an internal error during contention of multiple concurrent table operations (something which is rare anyway), and when that happens the AWS library will usually just retry the request anyway.

### PR DESCRIPTION
**Pull request by nyh**
In ScyllaDB, schema modification operations use "optimistic locking": A schema operation reads the current schema, decides what it wants to do and prepares changes to the schema, and then attempts to commit those changes - but only if the schema hasn't changed since the first read. If the schema has already been changed by some other node - we need to try again. In a loop.

In Alternator, there are six operations that perform schema modification: CreateTable, DeleteTable, UpdateTable, TagResource, UntagResource and UpdateTimeToLive. All of them were missing this loop. We knew about this - and even had FIXME in all places. So all these operations, when facing contention of concurrent schema modifications on different nodes may fail one of these operations with an error like:

   Internal server error: service::group0_concurrent_modification
   (Failed to apply group 0 change due to concurrent modification).

This problem had very minor effect, if any, on real users because the DynamoDB SDK automatically retries operations that fail with retryable errors - like this "Internal server error" - and most likely the schema operation will succeed upon retry. However, as shown in issue #13152 these failures were annoying in our CI, where tests - which disable request retries - failed on these errors.

This patch fixes all six operations (the last three operations all use one common function, db::modify_tags(), so are fixed by one change) to add the missing loop.

The patch also includes reproducing tests for all these operations - the new tests all fail before this patch, and pass with it.

These new tests are much more reliable reproducers than the dtests we had that only sometimes - very rarely - reproduced the problem. Moreover, the new tests reproduces the bug seperately for each of the six operations, so if we forget to fix one of the six operations, one of the tests would have continued to fail. Of course I checked this during development.

The new tests are in the test/cluster framework, not test/alternator, because this problem can only be reproduced in a multi-node cluster: On a single node, it serializes its schema modifications on its own; The collisions only happen when more than one node attempts schema modifications at the same time.

Fixes #13152

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

Closes scylladb/scylladb#23827

(cherry picked from commit 3ce7e250cc211f2b7b349f2bf84b49b77986ffdc)

### CODE REVIEW

**Comment by nyh** [comment]
This is a manual backport of https://github.com/scylladb/scylladb/pull/23827 to 2025.1, to replace the conflicted automated one (https://github.com/scylladb/scylladb/pull/24009).

Note that as I explained in the original PR this backport was never strictly necessary - it should have little or no practical impact on users (whose drivers will retry the failed operation anyway). But this problem keeps causing annoying test flakiness on 2025.1 tests (most recently https://jenkins.scylladb.com/job/scylla-2025.1/job/next/251/)  which is why it might be a good idea to do this backport anyway. CC @ScyllaPiotr who reminded me to do this backport (which I would have been happy to forget about ;-)).

File: alternator/executor.cc [hunk 1]
```diff
@@ -761,8 +761,8 @@ future<executor::request_return_type> executor::delete_table(client_state& clien
     rjson::value table_description = co_await fill_table_description(schema, table_status::deleting, _proxy, client_state, trace_state, permit);
     co_await verify_permission(_enforce_authorization, client_state, schema, auth::permission::DROP);
     co_await _mm.container().invoke_on(0, [&, cs = client_state.move_to_other_shard()] (service::migration_manager& mm) -> future<> {
-        // FIXME: the following needs to be in a loop. If mm.announce() below
-        // fails, we need to retry the whole thing.
+        size_t retries = mm.get_concurrent_ddl_retries();
+        for (;;) {
         auto group0_guard = co_await mm.start_group0_operation();
```
Comment (ScyllaPiotr) [inline alternator/executor.cc]: With the new loop**s**, indentation is incorrect all over the file...

**Review by ScyllaPiotr — CHANGES_REQUESTED** [review]
I'd gladly accept, but with the new loops, indentation is incorrect all over the file `alternator/executor.cc`...

**Comment by nyh** [comment]
> I'd gladly accept, but with the new loops, indentation is incorrect all over the file `alternator/executor.cc`...

I know. The question is, does it matter? 
My original patch re-indented the code that needed re-indenting. The problem is some code in those reindented blocks didn't exist in 2025.1, which caused these backport failures.
I can add to my backport PR another patch to re-indent the code that needs re-indenting. I didn't think it's important, but if you think it is, I can do it.

**Comment by ScyllaPiotr** [comment]
The version is recent, so we will deal with it for some time. The reformat can be done almost automatically. It's been a habit to care about the quality of the code, also on the aesthetics level (code formatting rules are documented for a reason). All in all, I like your idea:
> I can add to my backport PR another patch to re-indent the code that needs re-indenting.

**Comment by nyh** [comment]
Pushed a second patch to this backport to reindent all the looped code as appropriate.

**Review by ScyllaPiotr — APPROVED** [review]

**Comment by mykaul** [comment]
@scylladb/scylla-maint please review for merge

**Comment by nyh** [comment]
Already merged to next-2025.1 two days ago (by Botond) but not yet promoted. When it promotes, this PR will need to be closed manually (it doesn't happen automatically).

**Comment by nyh** [comment]
When PR was promoted to branch-2025.1, this issue was automatically closed - even though I thought it wouldn't. I guess the problem of no-automatic-closing happens only on single-patch backports, where the patch is not "merged" but rather "rebased", and the "Closes:" line is what gets ignored.
